(() => {
  'use strict';
  const CHANNEL='everstead-phase-10b3',inlineJson=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  function installRuntime(config){
    const slots=new Map(Object.entries(config.slots)),nativeSetTimeout=window.setTimeout.bind(window),nativeClearTimeout=window.clearTimeout.bind(window);let saveIndex=0,transactionIndex=0;
    const nativeStorageAccesses=[],errors=[],keydownListeners=new Set();let nativeStorageInstrumented=false;try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    const add=document.addEventListener.bind(document),remove=document.removeEventListener.bind(document);document.addEventListener=function(type,listener,options){if(type==='keydown')keydownListeners.add(listener);return add(type,listener,options)};document.removeEventListener=function(type,listener,options){if(type==='keydown')keydownListeners.delete(listener);return remove(type,listener,options)};
    window.__PHASE_10B3_CONFIG__=config;window.__PHASE_10B3_SLOTS__=slots;window.__PHASE_10B3_ERRORS__=errors;window.__PHASE_10B3_NATIVE_STORAGE_ACCESSES__=nativeStorageAccesses;window.__PHASE_10B3_NATIVE_STORAGE_INSTRUMENTED__=nativeStorageInstrumented;window.__PHASE_10B3_KEYDOWN_LISTENERS__=keydownListeners;
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>slots.set(String(key),String(value)),removeItem:key=>slots.delete(String(key))},runtime={storage:memoryStorage,clock:{now:()=>config.now,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.5,confirm:()=>true,ids:{save:()=>`save-p10b3-browser-${++saveIndex}`,transaction:()=>`tx-p10b3-browser-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
    window.__EVERSTEAD_RUNTIME__=runtime;
  }
  function runSuite(){
    const channel='everstead-phase-10b3',config=window.__PHASE_10B3_CONFIG__,slots=window.__PHASE_10B3_SLOTS__,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),expected=(id,invariant=false)=>invariant||config.mode==='CANDIDATE'?true:(Object.hasOwn(config.baselineExpected,id)?config.baselineExpected[id]:false),add=(id,actual,detail='',invariant=false)=>{const want=expected(id,invariant);results.push({id,actual:Boolean(actual),expected:want,pass:Boolean(actual)===want,detail:String(detail)})},send=()=>parent.postMessage({channel,nonce:config.nonce,results,errors:window.__PHASE_10B3_ERRORS__.slice(),slots:Object.fromEntries(slots)},'*'),bridge=()=>window.__EVERSTEAD_QA__,snapshot=()=>bridge().snapshot().state;
    const navigate=async view=>{const result=bridge().act('navigate',{view});if(!result.ok)throw new Error(`Navigation to ${view} failed: ${result.error}`);await wait(10)};
    const roster=async tab=>{if(tab==='relics'){const button=document.querySelector('[data-roster="relics"]');if(!button)throw new Error('Relics roster control is missing');button.click()}else{const result=bridge().act('roster',{tab});if(!result.ok)throw new Error(`Roster ${tab} failed: ${result.error}`)}await wait(10)};
    const adventure=async tab=>{const result=bridge().act('adventure',{tab});if(!result.ok)throw new Error(`Adventure ${tab} failed: ${result.error}`);await wait(10)};
    const closeOverlay=async()=>{document.querySelector('[data-modal-close]')?.click();await wait(10)};
    const summaryCounts=()=>[...document.querySelectorAll('[data-fellow].char-card')].map(card=>[...card.querySelectorAll('.char-copy p')].filter(item=>item.classList.contains('relic-summary')||item.textContent.trim()==='No Relic').length);
    const parseColor=value=>{const match=value.match(/rgba?\(([^)]+)\)/i);if(!match)return null;const parts=match[1].split(/[, ]+/).filter(Boolean).map(Number);return parts.length>=3?{r:parts[0],g:parts[1],b:parts[2],a:parts.length>3?parts[3]:1}:null},luminance=color=>{const component=value=>{const normalized=value/255;return normalized<=.03928?normalized/12.92:Math.pow((normalized+.055)/1.055,2.4)};return .2126*component(color.r)+.7152*component(color.g)+.0722*component(color.b)},contrast=(a,b)=>{const first=luminance(a),second=luminance(b);return(Math.max(first,second)+.05)/(Math.min(first,second)+.05)};
    const intersects=(a,b)=>Math.min(a.right,b.right)-Math.max(a.left,b.left)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>1;
    const hotspotEvidence=()=>{const blockers=[document.querySelector('.village-hud'),document.querySelector('.bottom-nav'),document.querySelector('.topbar')].filter(Boolean).map(item=>item.getBoundingClientRect()),items=[...document.querySelectorAll('.building-hotspot')].map(button=>{const rect=button.getBoundingClientRect(),points=[[.5,.5],[.25,.25],[.75,.25],[.25,.75],[.75,.75]].map(([x,y])=>[rect.left+rect.width*x,rect.top+rect.height*y]),hits=points.every(([x,y])=>{const target=document.elementFromPoint(x,y);return target===button||button.contains(target)}),clear=blockers.every(blocker=>!intersects(rect,blocker)),inside=rect.left>=-1&&rect.top>=-1&&rect.right<=innerWidth+1&&rect.bottom<=innerHeight+1;return{id:button.dataset.building,width:rect.width,height:rect.height,hits,clear,inside}});return{items,ok:items.length===4&&items.every(item=>item.width>=44&&item.height>=44&&item.hits&&item.clear&&item.inside)}};
    const visibleText=()=>{const values=[],walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){const parent=node.parentElement;if(!parent||parent.closest('script,style,textarea[readonly],[hidden],[aria-hidden="true"],[data-qa-surface]'))continue;const style=getComputedStyle(parent);if(style.display==='none'||style.visibility==='hidden')continue;const value=node.nodeValue.trim();if(value)values.push(value)}return values.join(' ')};
    const forbiddenHits=()=>config.forbiddenVisiblePatterns.flatMap(pattern=>{const match=visibleText().match(new RegExp(pattern,'ig'));return match?[...new Set(match.map(value=>`${pattern}:${value}`))]:[]});
    const focusables=dialog=>[...dialog.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(item=>!item.hidden&&getComputedStyle(item).display!=='none');
    async function dialogTarget(){await navigate('more');const trigger=document.querySelector('[data-player-profile]');trigger.focus();trigger.click();await wait(20);const modal=document.querySelector('.modal'),titles=modal?[...modal.querySelectorAll('#everstead-modal-title')]:[],firstHeading=modal?.querySelector('h2'),semantic=Boolean(modal?.matches('[role="dialog"][aria-modal="true"][aria-labelledby="everstead-modal-title"]'))&&titles.length===1&&firstHeading===titles[0],focusInside=Boolean(modal?.contains(document.activeElement)),inertOpen=Boolean(document.querySelector('#app')?.inert||document.querySelector('#app')?.hasAttribute('inert')),nodes=modal?focusables(modal):[],first=nodes[0]||modal,last=nodes.at(-1)||modal;last?.focus();document.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true}));await wait(5);const forward=document.activeElement===first;first?.focus();document.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true,cancelable:true}));await wait(5);const reverse=document.activeElement===last;document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));await wait(15);const escaped=!document.querySelector('[data-overlay]'),restored=document.activeElement===trigger,inertClosed=!document.querySelector('#app')?.inert&&!document.querySelector('#app')?.hasAttribute('inert');if(!escaped)await closeOverlay();const listenerAfterFirst=window.__PHASE_10B3_KEYDOWN_LISTENERS__.size;for(let index=0;index<2;index++){trigger.focus();trigger.click();await wait(10);document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));await wait(10);if(document.querySelector('[data-overlay]'))await closeOverlay()}const listenerAfterCycles=window.__PHASE_10B3_KEYDOWN_LISTENERS__.size,listenerStable=listenerAfterCycles===listenerAfterFirst&&listenerAfterCycles<=1;return{ok:semantic&&focusInside&&inertOpen&&forward&&reverse&&escaped&&restored&&inertClosed&&listenerStable,semantic,focusInside,inertOpen,forward,reverse,escaped,restored,inertClosed,listenerAfterFirst,listenerAfterCycles}}
    async function tabTarget(){await navigate('fellows');await roster('fellows');const inspect=()=>{const list=document.querySelector('[role="tablist"][aria-label="Fellowship roster"]'),tabs=list?[...list.querySelectorAll('[role="tab"]')]:[],selected=tabs.filter(tab=>tab.getAttribute('aria-selected')==='true'),panels=[...document.querySelectorAll('[role="tabpanel"]')];return{list,tabs,selected,panels,ok:Boolean(list)&&tabs.length===4&&selected.length===1&&panels.length===1&&tabs.every(tab=>tab.id&&tab.getAttribute('aria-controls')&&tab.tabIndex===(tab===selected[0]?0:-1))&&panels[0]?.getAttribute('aria-labelledby')===selected[0]?.id}};let state=inspect();if(!state.ok)return{ok:false,initial:state};const dispatch=key=>{const selected=document.querySelector('[role="tab"][aria-selected="true"]');selected.focus();selected.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}))};dispatch('ArrowRight');await wait(10);const right=document.querySelector('[role="tab"][aria-selected="true"]')?.dataset.roster==='family';dispatch('End');await wait(10);const end=document.querySelector('[role="tab"][aria-selected="true"]')?.dataset.roster==='relics';dispatch('Home');await wait(10);const home=document.querySelector('[role="tab"][aria-selected="true"]')?.dataset.roster==='fellows';dispatch('ArrowLeft');await wait(10);const wrap=document.querySelector('[role="tab"][aria-selected="true"]')?.dataset.roster==='relics';state=inspect();return{ok:state.ok&&right&&end&&home&&wrap,right,end,home,wrap,selected:state.selected[0]?.dataset.roster}}
    async function terminologyTarget(){const hits=[];const scan=label=>{for(const hit of forbiddenHits())hits.push(`${label}:${hit}`)};for(const view of ['village','oaths']){await navigate(view);scan(view)}await navigate('fellows');for(const tab of ['fellows','family','companions','relics']){await roster(tab);scan(`roster-${tab}`)}await navigate('village');document.querySelector('[data-building="training"]')?.click();await wait(10);scan('building-modal');await closeOverlay();await navigate('fellows');await roster('companions');document.querySelector('[data-companion="bramble"]')?.click();await wait(10);scan('companion-modal');await closeOverlay();for(const id of ['cael','lyra','orin','selene','rook','mira'])bridge().controls.grant({resource:'fellowExp',id,amount:1000000});bridge().controls.grant({resource:'gold',amount:1000000000});const alreadyCleared=new Set(snapshot().fellowCampaign.clearedStageIds);for(let stage=1;stage<=10;stage++){const stageId=`broken-roads-${stage}`;if(alreadyCleared.has(stageId))continue;const result=bridge().act('campaign-run',{id:stageId});if(!result.ok)throw new Error(`Campaign preparation failed at ${stage}: ${result.error}`)}await navigate('adventure');for(const tab of ['fellowCampaign','fellowExpedition','companionCampaign','companionTower']){await adventure(tab);scan(`adventure-${tab}`)}await navigate('more');scan('more');document.querySelector('[data-act="export"]')?.click();await wait(10);scan('save-export-chrome');await closeOverlay();return{ok:hits.length===0,hits}}
    (async()=>{await wait(500);add('bridge-present',Boolean(bridge()),'',true);add('viewport-exact',innerWidth===config.viewport.width&&innerHeight===config.viewport.height,`${innerWidth}x${innerHeight}`,true);add('schema10-runtime-invariant',snapshot().schemaVersion===10,snapshot().schemaVersion,true);add('protected-slots-isolated',Object.keys(config.keys).length===12,Object.keys(config.keys).length,true);add('no-horizontal-overflow-initial',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`,true);add('native-storage-instrumented',window.__PHASE_10B3_NATIVE_STORAGE_INSTRUMENTED__===true,'',true);
      await navigate('village');const geometry=hotspotEvidence(),geometryId=`village-hotspots-unobstructed:${config.viewport.id}`;add(geometryId,geometry.ok,JSON.stringify(geometry.items));add('village-four-semantic-buttons',document.querySelectorAll('button.building-hotspot').length===4,'',true);add('village-no-horizontal-overflow',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`,true);const collect=document.querySelector('.patrol-row .btn.primary'),style=collect?getComputedStyle(collect):null,foreground=style?parseColor(style.color):null,background=style?parseColor(style.backgroundColor):null,ratio=foreground&&background?contrast(foreground,background):0;add('collect-readable-contrast',Boolean(collect&&background?.a===1&&ratio>=4.5),`${style?.color} on ${style?.backgroundColor} = ${ratio.toFixed(3)}`);
      await navigate('fellows');await roster('fellows');let counts=summaryCounts();add('relic-summary-unequipped',counts.length===6&&counts.every(value=>value===1),JSON.stringify(counts));const run=bridge().act('campaign-run',{id:config.relicFixture.stageId}),equip=bridge().act('relic-equip',{fellowId:config.relicFixture.fellowId,relicId:config.relicFixture.relicId});if(!run.ok||!equip.ok)throw new Error(`Relic fixture failed: run=${run.error||run.ok}, equip=${equip.error||equip.ok}`);await navigate('fellows');await roster('fellows');counts=summaryCounts();add('relic-summary-equipped',counts.length===6&&counts.every(value=>value===1)&&document.querySelector(`[data-fellow="${config.relicFixture.fellowId}"] .relic-summary`)?.textContent.includes('First-Road Lantern'),JSON.stringify(counts));const navLabel=document.querySelector('.bottom-nav [data-nav="fellows"]')?.textContent.replace(/♙/g,'').trim();add('fellowship-bottom-label',navLabel==='FELLOWSHIP'&&document.documentElement.scrollWidth<=innerWidth,navLabel);
      await navigate('oaths');const oathButtons=[...document.querySelectorAll('.oath-check')],incompleteNames=config.starterOaths.every(item=>{const button=document.querySelector(`[data-oath="${item.id}"]`),name=button?.getAttribute('aria-label')||button?.textContent.trim();return name===(item.type==='habit'?`Log Habit: ${item.title}. 0 completed today.`:`Complete Oath: ${item.title}`)&&(item.restDay?button.disabled:true)});const habit=document.querySelector('[data-oath="o4"]'),habitArticle=habit?.closest('.oath');add('oath-accessible-names',oathButtons.length===8&&incompleteNames,`${oathButtons.length} buttons`);add('habit-visible-action-and-count',habit?.textContent.trim()==='+1'&&/\b0 today\b/.test(habitArticle?.textContent||''),`${habit?.textContent.trim()} · ${habitArticle?.textContent.trim()}`);const complete=bridge().act('complete-oath',{id:'o1'});await wait(10);document.querySelector('[data-modal-close]')?.click();await wait(10);const completed=document.querySelector('[data-oath="o1"]'),completedName=completed?.getAttribute('aria-label')||completed?.textContent.trim();add('completed-oath-accessible-name',complete.ok&&completedName==='Undo Oath completion: Morning prayer',completedName,config.mode==='BASELINE_GAPS_CONFIRMED'?false:false);
      const dialog=await dialogTarget();add('dialog-semantics-focus-lifecycle',dialog.ok,JSON.stringify(dialog));const tabs=await tabTarget();add('roster-tab-semantics-keyboard',tabs.ok,JSON.stringify(tabs));const terminology=await terminologyTarget();add('player-copy-qa-terminology-absent',terminology.ok,terminology.hits.slice(0,20).join(' | '));add('final-no-horizontal-overflow',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`,true);add('zero-native-storage-calls',window.__PHASE_10B3_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_10B3_NATIVE_STORAGE_ACCESSES__.join(','),true);add('realm-zero-errors',window.__PHASE_10B3_ERRORS__.length===0,window.__PHASE_10B3_ERRORS__.join('\n'),true);send()})().catch(error=>{add('realm-fatal',false,error.stack||error.message,true);send()});
  }
  let loaderNonce='unknown';(async()=>{const config=JSON.parse(window.name);loaderNonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error('index.html: HTTP '+response.status);const source=await response.text(),firstScript=source.indexOf('<script>');if(firstScript<0)throw new Error('Production script is missing');const bootstrap='<script>('+installRuntime.toString()+')('+inlineJson(config)+')<\/script>',suite='<script>('+runSuite.toString()+')()<\/script>',instrumented=source.slice(0,firstScript)+bootstrap+source.slice(firstScript).replace('</body>',suite+'</body>');document.open();document.write(instrumented);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce:loaderNonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
