import {readFileSync,existsSync,readdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';

const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),QA=resolve(ROOT,'qa/phase-10b3'),BASE='14efe7f0c85c91c78d3bb3e79049694fd0975d07',sha=value=>createHash('sha256').update(value).digest('hex'),read=path=>readFileSync(resolve(ROOT,path)),source=read('index.html').toString('utf8'),artifact={sha256:sha(read('index.html')),byteLength:read('index.html').length},scenarios=JSON.parse(read('qa/phase-10b3/scenarios.json')),manifest=JSON.parse(read('qa/phase-10b3/current-manifest.json')),mode=artifact.sha256===scenarios.baseArtifact.sha256&&artifact.byteLength===scenarios.baseArtifact.byteLength?'BASELINE_GAPS_CONFIRMED':'CANDIDATE';
const results=[],record=(id,actual,expected=true,detail='')=>results.push({id,actual:Boolean(actual),expected:Boolean(expected),pass:Boolean(actual)===Boolean(expected),detail:String(detail)}),target=(id,actual,detail='')=>record(id,actual,mode==='CANDIDATE'?true:scenarios.baselineExpected[id]??false,detail);
const exactFiles=['README.md','build-contract.mjs','checksums.sha256','current-manifest.json','index.html','realm.html','realm.js','runner.js','scenarios.json','verify.mjs'],ownedPaths=['docs/PHASE_10B3_UI_CORRECTION_CONTRACT.md','docs/PHASE_10B3_EXECUTION.md',...exactFiles.map(name=>`qa/phase-10b3/${name}`)],slotNames=['NS','RAW_BACKUP_KEY','PRE_V2_BACKUP_KEY','PRE_V3_BACKUP_KEY','PRE_V4_BACKUP_KEY','PRE_V5_BACKUP_KEY','PRE_V6_BACKUP_KEY','PRE_V7_BACKUP_KEY','PRE_V8_BACKUP_KEY','PRE_V9_BACKUP_KEY','PRE_V10_BACKUP_KEY','STAGING_KEY'];

record('scenario-phase',scenarios.phase==='10B-3');record('scenario-base-commit',scenarios.baseCommit===BASE);record('scenario-viewports',JSON.stringify(scenarios.viewports)===JSON.stringify([{id:'phone-320x568',width:320,height:568},{id:'phone-390x667',width:390,height:667},{id:'phone-390x844',width:390,height:844}]));record('scenario-eight-oaths',scenarios.starterOaths.length===8&&new Set(scenarios.starterOaths.map(item=>item.id)).size===8);record('scenario-forbidden-patterns',scenarios.forbiddenVisiblePatterns.length===9);record('scenario-baseline-targets',Object.keys(scenarios.baselineExpected).length===12);record('manifest-scenario-identity',manifest.scenarios.sha256===sha(read('qa/phase-10b3/scenarios.json'))&&manifest.scenarios.byteLength===read('qa/phase-10b3/scenarios.json').length);record('qa-exact-topology',JSON.stringify(readdirSync(QA).sort())===JSON.stringify(exactFiles));record('owned-paths-present',ownedPaths.every(path=>existsSync(resolve(ROOT,path))));
const changed=execFileSync('git',['diff','--name-only',BASE,'--'],{cwd:ROOT,encoding:'utf8'}).trim().split('\n').filter(Boolean),untracked=execFileSync('git',['ls-files','--others','--exclude-standard'],{cwd:ROOT,encoding:'utf8'}).trim().split('\n').filter(Boolean),touched=[...new Set([...changed,...untracked])].sort();record('additive-preimage-topology',touched.every(path=>path.startsWith('qa/phase-10b3/')||path==='docs/PHASE_10B3_UI_CORRECTION_CONTRACT.md'||path==='docs/PHASE_10B3_EXECUTION.md'),touched.join(','));record('production-unchanged-in-preimage',mode==='CANDIDATE'||artifact.sha256===scenarios.baseArtifact.sha256&&artifact.byteLength===scenarios.baseArtifact.byteLength,true,`${mode} · ${artifact.sha256} · ${artifact.byteLength}`);record('schema10-source',source.includes('CURRENT_SCHEMA_VERSION=10'));record('twelve-protected-slot-identifiers',slotNames.every(name=>source.includes(name)),true,slotNames.length);
const assetMatches=[...source.matchAll(/data:image\/[^;]+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]),assetAggregate=sha(Buffer.from(assetMatches.join('\n')));record('five-embedded-assets',assetMatches.length===5,true,assetMatches.length);record('embedded-asset-aggregate',assetAggregate===scenarios.baseArtifact.assetAggregateSha256,true,assetAggregate);
const relicAnchored=!source.includes("html=html.replace(needle,needle+summary)")&&/data-fellow/.test(source)&&/relic-summary/.test(source)&&/No Relic/.test(source);target('relic-summary-unequipped',relicAnchored);target('relic-summary-equipped',relicAnchored);
target('fellowship-bottom-label',/\['fellows','♙','Fellowship'\]/.test(source)&&!(/\['fellows','♙','Fellows'\]/.test(source)));
const oathNames=source.includes('Complete Oath:')&&source.includes('Undo Oath completion:')&&source.includes('Log Habit:')&&source.includes('completed today.');target('oath-accessible-names',oathNames);target('habit-visible-action-and-count',oathNames&&source.includes("'+1'")&&source.includes(' today'));
const modalSemantics=source.includes('role="dialog"')&&source.includes('aria-modal="true"')&&source.includes('everstead-modal-title')&&source.includes("event.key==='Escape'")&&source.includes("event.key==='Tab'")&&/\.inert\s*=/.test(source);target('dialog-semantics-focus-lifecycle',modalSemantics);
const tabSemantics=source.includes('role="tablist"')&&source.includes('aria-label="Fellowship roster"')&&source.includes('role="tab"')&&source.includes('aria-selected=')&&source.includes('role="tabpanel"')&&['ArrowLeft','ArrowRight','Home','End'].every(value=>source.includes(value));target('roster-tab-semantics-keyboard',tabSemantics);
const collectTarget=/\.patrol-row\s+\.btn\.primary[^}]*background\s*:\s*#08131e/i.test(source)&&/\.patrol-row\s+\.btn\.primary[^}]*color\s*:\s*var\(--gold\)/i.test(source);target('collect-readable-contrast',collectTarget);
const shortRule=/@media[^{}]*max-height[^{}]*\{[\s\S]{0,5000}\.building-hotspot/i.test(source);for(const viewport of scenarios.viewports)target(`village-hotspots-unobstructed:${viewport.id}`,shortRule||viewport.id==='phone-390x844');
const forbiddenRenderSnippets=['Phase 5 campaign foundation','Save schema','Player Rank spine','All Phase 9 roads open.','neutral in Phase 4','Stones deterministically','Deterministic Relic result','Phase 8 epoch ceiling','Production formula','formula order','Actual Gold','Might nominal','Mastery nominal','Campaign history capacity'],playerCopyClean=forbiddenRenderSnippets.every(value=>!source.includes(value));target('player-copy-qa-terminology-absent',playerCopyClean,forbiddenRenderSnippets.filter(value=>source.includes(value)).join(' | '));
record('no-production-network-addition',!/<script[^>]+src=["']https?:|fetch\(["']https?:|new WebSocket\(/i.test(source));record('single-file-production-shell',/^<!doctype html>/i.test(source)&&source.includes('<style>')&&source.includes('<script>'));

const passed=results.filter(item=>item.pass).length,failed=results.length-passed;console.log(JSON.stringify({phase:'10B-3',mode,artifact,assetAggregate,total:results.length,passed,failed,results},null,2));if(failed)process.exitCode=1;
