(() => {
  'use strict';
  const CHANNEL='everstead-phase-11b1';
  const json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config,fixtureRaw){
    const fixture=JSON.parse(fixtureRaw);fixture.oaths[0].memo=config.fixture.privateSentinel;fixtureRaw=JSON.stringify(fixture);
    const slots=new Map([[config.keys.active,fixtureRaw]]),reads=[],writes=[],downloads=[],blobs=new Map(),nativeSetTimeout=window.setTimeout.bind(window),nativeClearTimeout=window.clearTimeout.bind(window),nativeStorageAccesses=[],errors=[];let saveIndex=0,transactionIndex=0,blobIndex=0,nativeStorageInstrumented=false;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>{key=String(key);reads.push(key);return slots.get(key)??null},setItem:(key,value)=>{key=String(key);value=String(value);writes.push({op:'set',key});slots.set(key,value)},removeItem:key=>{key=String(key);writes.push({op:'remove',key});slots.delete(key)}};
    class CapturedBlob{constructor(parts=[],options={}){this.parts=parts.map(part=>String(part));this.type=String(options.type||'');this.size=new TextEncoder().encode(this.parts.join('')).byteLength}}
    Object.defineProperty(window,'Blob',{configurable:true,writable:true,value:CapturedBlob});
    Object.defineProperty(URL,'createObjectURL',{configurable:true,writable:true,value:blob=>{const url=`blob:phase-11b1-${++blobIndex}`;blobs.set(url,blob);return url}});
    Object.defineProperty(URL,'revokeObjectURL',{configurable:true,writable:true,value:url=>blobs.delete(String(url))});
    const anchorClick=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){downloads.push({href:this.href,download:this.download,blob:blobs.get(this.href)||null});return undefined};
    window.__PHASE_11B1_CONFIG__=config;window.__PHASE_11B1_SLOTS__=slots;window.__PHASE_11B1_READS__=reads;window.__PHASE_11B1_WRITES__=writes;window.__PHASE_11B1_DOWNLOADS__=downloads;window.__PHASE_11B1_ERRORS__=errors;window.__PHASE_11B1_NATIVE_STORAGE_ACCESSES__=nativeStorageAccesses;window.__PHASE_11B1_NATIVE_STORAGE_INSTRUMENTED__=nativeStorageInstrumented;window.__PHASE_11B1_ORIGINAL_ANCHOR_CLICK__=anchorClick;
    window.__EVERSTEAD_RUNTIME__={storage:memoryStorage,clock:{now:()=>config.now,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.5,confirm:()=>true,ids:{save:()=>++saveIndex===1?config.fixture.maliciousSaveId:`save-p11b1-${saveIndex}`,transaction:()=>`tx-p11b1-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
  }

  function runSuite(){
    const config=window.__PHASE_11B1_CONFIG__,slots=window.__PHASE_11B1_SLOTS__,writes=window.__PHASE_11B1_WRITES__,downloads=window.__PHASE_11B1_DOWNLOADS__,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)}),bridge=()=>window.__EVERSTEAD_QA__,snapshot=()=>bridge().snapshot().state,send=()=>parent.postMessage({channel:'everstead-phase-11b1',nonce:config.nonce,results,errors:window.__PHASE_11B1_ERRORS__.slice(),nativeStorageAccesses:window.__PHASE_11B1_NATIVE_STORAGE_ACCESSES__.slice()},'*');
    const text=node=>node?.textContent.replace(/\s+/g,' ').trim()||'',productText=()=>['#app','#overlay','#toast'].map(selector=>text(document.querySelector(selector))).join(' '),close=async()=>{document.querySelector('[data-modal-close]')?.click();await wait(20)},slotSnapshot=()=>Object.fromEntries(Object.entries(config.keys).map(([name,key])=>[name,slots.get(key)??null])),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),sha256=async value=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(byte=>byte.toString(16).padStart(2,'0')).join(''),inside=node=>{const rect=node?.getBoundingClientRect();return Boolean(rect)&&rect.left>=-1&&rect.right<=innerWidth+1&&rect.width>0};
    const bundleSlotMap={active:'active',rawBackup:'backup',preV2:'preV2',preV3:'preV3',preV4:'preV4',preV5:'preV5',preV6:'preV6',preV7:'preV7',preV8:'preV8',preV9:'preV9',preV10:'preV10',preV11:'preV11'};

    (async()=>{
      await wait(750);const qa=bridge();add('bridge-present',Boolean(qa));add('viewport-exact',innerWidth===config.viewport.width&&innerHeight===config.viewport.height,`${innerWidth}x${innerHeight}`);add('native-storage-instrumented',window.__PHASE_11B1_NATIVE_STORAGE_INSTRUMENTED__===true);add('schema11-runtime',snapshot().schemaVersion===11,snapshot().schemaVersion);add('thirteen-protected-slots',Object.keys(config.keys).length===13,Object.keys(config.keys).length);
      const initialModal=document.querySelector('.modal');add('phase11a-offline-boundary',Boolean(initialModal)===config.viewport.offlineModal,`${config.viewport.offlineElapsed} · ${Boolean(initialModal)}`);if(initialModal)await close();
      const gifts=document.querySelector('[data-resource="gifts"]'),gold=document.querySelector('[data-resource="gold"]');add('phase11a-resource-accessible-names',gifts?.getAttribute('aria-label')?.startsWith('Gifts:')&&gold?.getAttribute('aria-label')?.startsWith('Gold:'),`${gifts?.getAttribute('aria-label')} / ${gold?.getAttribute('aria-label')}`);

      const writesBeforeMore=writes.length,revisionBefore=snapshot().saveMeta.revision,navigation=qa.act('navigate',{view:'more'});await wait(35);const moreWriteDelta=writes.slice(writesBeforeMore),stateAtMore=snapshot();add('more-navigation-succeeds',navigation.ok&&stateAtMore.ui.view==='more');add('health-render-adds-no-navigation-writes',stateAtMore.saveMeta.revision===revisionBefore+1&&moreWriteDelta.length===3&&same(moreWriteDelta.map(item=>item.op),['set','set','remove']),JSON.stringify(moreWriteDelta));
      const health=document.querySelector('[data-save-health="verified"]'),history=document.querySelector('[data-migration-history]'),recovery=document.querySelector('[data-save-recovery]'),downloadButton=document.querySelector('[data-act="export"]'),historyItems=[...document.querySelectorAll('[data-migration-history] li')],writesAfterHealth=writes.length,slotsAtHealth=slotSnapshot();await wait(30);
      add('save-health-verified',Boolean(health)&&text(health).includes('Schema 11')&&text(health).includes('11/11')&&text(health).includes(`Revision ${stateAtMore.saveMeta.revision}`),text(health));add('migration-history-complete',Boolean(history)&&historyItems.length===stateAtMore.saveMeta.appliedMigrations.length&&historyItems.length===11,historyItems.length);add('health-id-escaped',text(health).includes('<img data-he')&&!health.querySelector('[data-health-xss]')&&!document.querySelector('[data-health-xss]'),text(health));add('normal-dom-omits-private-raw',!productText().includes(config.fixture.privateSentinel));add('health-settled-zero-writes',writes.length===writesAfterHealth&&same(slotSnapshot(),slotsAtHealth),writes.length-writesAfterHealth);
      add('save-recovery-privacy-copy',Boolean(recovery)&&text(recovery).includes('Oaths, private memos, links, and full progress')&&downloadButton?.getAttribute('aria-describedby')==='save-recovery-intro save-recovery-privacy');add('three-phone-more-layout',inside(health)&&inside(history)&&inside(recovery)&&inside(downloadButton)&&document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);

      const writesBeforeNormal=writes.length,slotsBeforeNormal=slotSnapshot();downloadButton.click();await wait(180);const normalModal=document.querySelector('.modal'),normalAction=document.querySelector('[data-download-recovery]');add('normal-download-confirmation-modal',Boolean(normalModal)&&normalModal.getAttribute('role')==='dialog'&&normalModal.getAttribute('aria-modal')==='true'&&text(normalModal).includes('Verified recovery file')&&normalAction?.getAttribute('aria-describedby')==='recovery-download-warning',text(normalModal));add('normal-modal-phone-layout',inside(normalModal)&&inside(normalAction)&&document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);add('normal-preview-zero-writes',writes.length===writesBeforeNormal&&same(slotSnapshot(),slotsBeforeNormal),writes.length-writesBeforeNormal);
      normalAction.click();await wait(35);const normalDownload=downloads.at(-1),normalData=normalDownload?.blob?.parts?.join('')||'',bundle=normalData?JSON.parse(normalData):null,topKeys=bundle?Object.keys(bundle):[],slotKeys=bundle?Object.keys(bundle.slots):[],{integrity,...payload}=bundle||{integrity:null},expectedDigest=bundle?await sha256(JSON.stringify(payload)):null;
      add('normal-download-captured',downloads.length===1&&normalDownload.download==='everstead-recovery-2030-06-17.json'&&normalDownload.blob?.type==='application/json;charset=utf-8',normalDownload?.download);add('bundle-canonical-topology',same(topKeys,config.bundle.topLevelKeys)&&same(slotKeys,config.bundle.slotKeys)&&same(Object.keys(integrity||{}),['algorithm','digest']),JSON.stringify({topKeys,slotKeys}));add('bundle-canonical-metadata',bundle?.product==='Everstead'&&bundle.format===config.bundle.format&&bundle.formatVersion===config.bundle.formatVersion&&bundle.exportedAt===config.now&&typeof bundle.appVersion==='string');add('bundle-canonical-sha256',integrity?.algorithm==='SHA-256'&&integrity.digest===expectedDigest&&/^[0-9a-f]{64}$/.test(integrity.digest),integrity?.digest);add('bundle-pretty-bytes-exact',normalData===JSON.stringify(bundle,null,2)&&new TextEncoder().encode(normalData).byteLength<=config.bundle.maxBytes,normalDownload.blob?.size);
      const slotMismatches=bundle?Object.entries(bundleSlotMap).filter(([bundleName,configName])=>bundle.slots[bundleName]!==slotsBeforeNormal[configName]).map(([name])=>name):['missing'];add('bundle-exact-twelve-slots',slotMismatches.length===0&&!Object.hasOwn(bundle?.slots||{},'staging'),slotMismatches.join(','));add('normal-download-zero-writes',writes.length===writesBeforeNormal&&same(slotSnapshot(),slotsBeforeNormal),writes.length-writesBeforeNormal);

      slots.set(config.keys.active,config.fixture.corruptRaw);const writesBeforeBlocked=writes.length,blockedReload=qa.recovery.reload();await wait(50);add('blocked-runtime-preserves-active',blockedReload.ok===false&&slots.get(config.keys.active)===config.fixture.corruptRaw&&Boolean(document.querySelector('[data-persistence-act="export"]')),JSON.stringify(blockedReload));add('blocked-reload-zero-writes',writes.length===writesBeforeBlocked,writes.length-writesBeforeBlocked);
      const blockedSlots=slotSnapshot(),blockedExport=document.querySelector('[data-persistence-act="export"]');blockedExport.click();await wait(60);const diagnosticModal=document.querySelector('.modal'),diagnosticAction=document.querySelector('[data-download-diagnostics]');add('blocked-diagnostic-modal',Boolean(diagnosticModal)&&text(diagnosticModal).includes('Recovery stopped to protect your data')&&text(diagnosticModal).includes('Nothing was deleted or overwritten')&&diagnosticAction?.getAttribute('aria-describedby')==='diagnostic-warning',text(diagnosticModal));add('blocked-modal-phone-layout',inside(diagnosticModal)&&inside(diagnosticAction)&&document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);add('blocked-preview-zero-writes',writes.length===writesBeforeBlocked&&same(slotSnapshot(),blockedSlots),writes.length-writesBeforeBlocked);
      diagnosticAction.click();await wait(35);const diagnosticDownload=downloads.at(-1),diagnosticData=diagnosticDownload?.blob?.parts?.join('')||'',diagnostic=diagnosticData?JSON.parse(diagnosticData):null;add('diagnostic-download-captured',downloads.length===2&&diagnosticDownload.download==='everstead-recovery-diagnostics-2030-06-17.json'&&diagnosticDownload.blob?.type==='application/json;charset=utf-8',diagnosticDownload?.download);add('diagnostic-exact-active',diagnostic?.exportVersion===11&&diagnostic.activeRaw===config.fixture.corruptRaw&&diagnostic.stagingRaw===null,JSON.stringify({exportVersion:diagnostic?.exportVersion,activeRaw:diagnostic?.activeRaw}));add('blocked-download-zero-writes',writes.length===writesBeforeBlocked&&same(slotSnapshot(),blockedSlots),writes.length-writesBeforeBlocked);add('blocked-dom-omits-private-raw',!productText().includes(config.fixture.privateSentinel)&&!productText().includes(config.fixture.corruptRaw));

      add('zero-native-storage-accesses',window.__PHASE_11B1_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_11B1_NATIVE_STORAGE_ACCESSES__.join(','));add('zero-warning-error-console',window.__PHASE_11B1_ERRORS__.length===0,window.__PHASE_11B1_ERRORS__.join('\n'));send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const [appResponse,fixtureResponse]=await Promise.all([fetch('../../index.html',{cache:'no-store'}),fetch(config.fixture.path,{cache:'no-store'})]);if(!appResponse.ok)throw new Error(`index.html: HTTP ${appResponse.status}`);if(!fixtureResponse.ok)throw new Error(`fixture: HTTP ${fixtureResponse.status}`);const source=await appResponse.text(),fixtureRaw=await fixtureResponse.text(),firstScript=source.indexOf('<script>');if(firstScript<0)throw new Error('Production script is missing');const bootstrap=`<script>(${installRuntime.toString()})(${json(config)},${json(fixtureRaw)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`,instrumented=source.slice(0,firstScript)+bootstrap+source.slice(firstScript).replace('</body>',suite+'</body>');document.open();document.write(instrumented);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
