(() => {
  'use strict';
  const CHANNEL='everstead-phase-11b1',byId=id=>document.getElementById(id),escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),hex=bytes=>[...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,'0')).join(''),sha256=async bytes=>hex(await crypto.subtle.digest('SHA-256',bytes)),decode=bytes=>new TextDecoder('utf-8',{fatal:true}).decode(bytes),row=(id,actual,detail='')=>({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)});
  async function bytes(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return new Uint8Array(await response.arrayBuffer())}
  async function loadContract(){const [scenarioBytes,artifactBytes]=await Promise.all([bytes('./scenarios.json'),bytes('../../index.html')]),scenarios=JSON.parse(decode(scenarioBytes)),artifactHash=await sha256(artifactBytes),source=decode(artifactBytes),assets=[...source.matchAll(/data:image\/[^;]+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]),assetHash=await sha256(new TextEncoder().encode(assets.join('\n'))),rows=[];rows.push(row('candidate-artifact-identity',artifactHash===scenarios.artifact.sha256&&artifactBytes.byteLength===scenarios.artifact.byteLength,`${artifactHash} · ${artifactBytes.byteLength}`));rows.push(row('embedded-assets-byte-identical',assets.length===scenarios.artifact.assetCount&&assetHash===scenarios.artifact.assetAggregateSha256,`${assets.length} · ${assetHash}`));rows.push(row('phase11b1-source-boundary',source.includes('/* Phase 11B-1 · read-only save health, recovery bundle download, and migration history. */')&&source.includes("PHASE_ELEVEN_B_BUNDLE_FORMAT='everstead-recovery-bundle'")));rows.push(row('scenario-bundle-contract',JSON.stringify(scenarios.bundle.topLevelKeys)===JSON.stringify(['product','format','formatVersion','exportedAt','appVersion','slots','integrity'])&&scenarios.bundle.slotKeys.length===12&&scenarios.bundle.maxBytes===33554432));return{scenarios,rows}}
  function executeRealm(contract,viewport){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),config={nonce,viewport,now:contract.scenarios.fixture.lastGoldAt+viewport.offlineElapsed,keys:contract.scenarios.storageKeys,bundle:contract.scenarios.bundle,fixture:contract.scenarios.fixture};frame.name=JSON.stringify(config);frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0`;let timeout;const finish=(error,value)=>{clearTimeout(timeout);removeEventListener('message',onMessage);frame.remove();error?reject(error):resolve(value)},onMessage=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=event.data.results.map(item=>({...item,id:`${viewport.id}-${item.id}`}));if(event.data.errors?.length&&!rows.some(item=>item.id.endsWith('zero-warning-error-console')&&!item.pass))rows.push(row(`${viewport.id}-captured-errors`,false,event.data.errors.join('\n')));finish(null,rows)};timeout=setTimeout(()=>finish(new Error(`${viewport.id} timed out`)),120000);addEventListener('message',onMessage);frame.src=`./realm.html?qa=1&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  function render(mode,rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('mode').textContent=mode;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)} · observed ${item.actual?'true':'false'} · expected true${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_11B1_RESULT__={mode,passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const contract=await loadContract(),rows=[...contract.rows];for(const viewport of contract.scenarios.viewports)rows.push(...await executeRealm(contract,viewport));render('CANDIDATE',rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render('FATAL',[row('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
