import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {existsSync,readFileSync,readdirSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {runPhaseElevenBOneProbe} from './probe.mjs';

const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),QA=resolve(ROOT,'qa/phase-11b1');
const EXPECTED_NAMES=['README.md','build-contract.mjs','checksums.sha256','current-manifest.json','index.html','probe.mjs','realm.html','realm.js','runner.js','scenarios.json','verify.mjs'];
const SOURCE_FILES=EXPECTED_NAMES.filter(name=>!['checksums.sha256','current-manifest.json'].includes(name)).map(name=>`qa/phase-11b1/${name}`);
const results=[],record=(id,pass,detail='')=>results.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),sha=value=>createHash('sha256').update(value).digest('hex'),read=path=>readFileSync(resolve(ROOT,path)),identity=raw=>({sha256:sha(raw),byteLength:raw.length}),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const scenarios=JSON.parse(read('qa/phase-11b1/scenarios.json')),source=read('index.html'),artifact=identity(source),expectedArtifact={sha256:scenarios.artifact.sha256,byteLength:scenarios.artifact.byteLength};
record('production-parent-reachable',execFileSync('git',['merge-base','--is-ancestor',scenarios.authority.productionParentCommit,'HEAD'],{cwd:ROOT,encoding:'utf8'})==='');record('exact-candidate-artifact',same(artifact,expectedArtifact),artifact);
const assets=[...source.toString('utf8').matchAll(/data:image\/[^;]+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]);record('embedded-assets-byte-identical',assets.length===scenarios.artifact.assetCount&&sha(Buffer.from(assets.join('\n')))===scenarios.artifact.assetAggregateSha256,`${assets.length} · ${sha(Buffer.from(assets.join('\n')))}`);
record('package-topology',same(readdirSync(QA).sort(),EXPECTED_NAMES),readdirSync(QA).sort());record('contract-and-result-present',existsSync(resolve(ROOT,'docs/PHASE_11B_SAVE_RECOVERY_CONTRACT.md'))&&existsSync(resolve(ROOT,'docs/PHASE_11B1_SAVE_RECOVERY_RESULT.md')));
const historicalTracked=execFileSync('git',['diff','--name-only','HEAD','--','qa'],{cwd:ROOT,encoding:'utf8'}).trim().split('\n').filter(path=>path&&!path.startsWith('qa/phase-11b1/'));record('historical-tracked-qa-unchanged',historicalTracked.length===0,historicalTracked);
for(const file of ['probe.mjs','realm.js','runner.js']){try{execFileSync(process.execPath,['--check',`qa/phase-11b1/${file}`],{cwd:ROOT,encoding:'utf8'});record(`syntax-${file}`,true)}catch(error){record(`syntax-${file}`,false,error.stderr||error.message)}}
const focused=await runPhaseElevenBOneProbe();for(const row of focused.rows)record(`focused-${row.id}`,row.pass,row.detail);record('focused-probe-189-of-189',focused.rows.length===189&&focused.evidence.failed===0,focused.evidence);
const manifest=JSON.parse(read('qa/phase-11b1/current-manifest.json'));record('manifest-authority',manifest.phase==='11B-1'&&manifest.status==='PASS_LOCAL'&&manifest.productionParentCommit===scenarios.authority.productionParentCommit&&manifest.phase11aCandidateCommit===scenarios.authority.phase11aCandidateCommit&&manifest.candidateCommit===scenarios.authority.candidateCommit&&execFileSync('git',['merge-base','--is-ancestor',manifest.candidateCommit,'HEAD'],{cwd:ROOT,encoding:'utf8'})===''&&same(manifest.artifact,expectedArtifact)&&manifest.phase11aSemanticRows===168&&manifest.focusedProbeRows===189&&manifest.sealedCliRows===203&&manifest.liveRows===115&&manifest.observedGate?.focusedCli?.passed===189&&manifest.observedGate?.focusedCli?.failed===0&&manifest.observedGate?.sealedCli?.passed===203&&manifest.observedGate?.sealedCli?.failed===0&&manifest.observedGate?.sealedCli?.runs===2&&manifest.observedGate?.liveBrowser?.passed===115&&manifest.observedGate?.liveBrowser?.failed===0&&manifest.observedGate?.liveBrowser?.runs===2&&manifest.observedGate?.liveBrowser?.consoleWarningsOrErrors===0&&manifest.observedGate?.liveBrowser?.nativeStorageAccesses===0,manifest);
const packageFailures=Object.entries(manifest.packageFiles).filter(([path,entry])=>{const raw=read(path);return sha(raw)!==entry.sha256||raw.length!==entry.byteLength}).map(([path])=>path);record('manifest-package-identities',Object.keys(manifest.packageFiles).length===SOURCE_FILES.length&&packageFailures.length===0,packageFailures);
const checksumRows=read('qa/phase-11b1/checksums.sha256').toString('utf8').trim().split('\n'),checksumFailures=[];for(const line of checksumRows){const match=line.match(/^([0-9a-f]{64})  (.+)$/);if(!match||!existsSync(resolve(ROOT,match[2]))||sha(read(match[2]))!==match[1])checksumFailures.push(match?.[2]||line)}record('phase11b1-checksums',checksumRows.length===24&&checksumFailures.length===0,checksumFailures);
try{const output=execFileSync(process.execPath,['qa/phase-11b1/build-contract.mjs'],{cwd:ROOT,encoding:'utf8'}),result=JSON.parse(output);record('builder-read-only',result.writes===0&&result.artifact.sha256===expectedArtifact.sha256,result)}catch(error){record('builder-read-only',false,error.stderr||error.message)}
const passed=results.filter(row=>row.pass).length,failed=results.length-passed;console.log(JSON.stringify({phase:'11B-1',status:failed?'FAIL':'PASS',artifact:expectedArtifact,focused:focused.evidence,total:results.length,passed,failed,results},null,2));if(failed)process.exitCode=1;
