(() => {
  'use strict';
  const CHANNEL='everstead-phase-18-19-independent';
  const json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config){
    const slots=new Map(),writes=[],errors=[],nativeStorageAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);
    let saveIndex=0,transactionIndex=0,nativeStorageInstrumented=false;
    window.matchMedia=query=>({matches:config.viewport.reducedMotion&&query==='(prefers-reduced-motion: reduce)',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});
    document.documentElement.style.fontSize=`${config.viewport.copyScale||1}em`;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));
    const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>{key=String(key);writes.push({op:'set',key,value:String(value)});slots.set(key,String(value))},removeItem:key=>{key=String(key);writes.push({op:'remove',key});slots.delete(key)}};
    Object.assign(window,{__P1819I_CONFIG__:config,__P1819I_SLOTS__:slots,__P1819I_WRITES__:writes,__P1819I_ERRORS__:errors,__P1819I_NATIVE_ACCESSES__:nativeStorageAccesses,__P1819I_NATIVE_INSTRUMENTED__:nativeStorageInstrumented});
    window.__EVERSTEAD_RUNTIME__={storage:memoryStorage,clock:{now:()=>config.fixtures.frozenNow,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.4375,confirm:()=>true,ids:{save:()=>`save-p1819i-${++saveIndex}`,transaction:()=>`tx-p1819i-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
  }

  function runSuite(){
    const config=window.__P1819I_CONFIG__,f=config.fixtures,results=[];
    const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));const until=async(predicate,limit=8000)=>{const started=performance.now();while(performance.now()-started<limit){if(predicate())return true;await wait(25)}return false};
    const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),unique=values=>new Set(values).size===values.length,sorted=values=>[...new Set(values)].sort();
    const add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:typeof detail==='string'?detail:JSON.stringify(detail)});
    const send=()=>parent.postMessage({channel:config.channel,nonce:config.nonce,results,errors:window.__P1819I_ERRORS__.slice()},'*');
    const bridge=()=>window.__EVERSTEAD_PHASE_18_19_QA__,phase17Bridge=()=>window.__EVERSTEAD_PHASE_17_QA__,safe=(label,fn)=>{try{return fn()}catch(error){add(label,false,error.stack||error.message);return null}},call=(group,name,...args)=>safe(`${name}-call`,()=>bridge()[group][name](...args)),call17=(group,name,...args)=>safe(`phase17-${name}-call`,()=>phase17Bridge()[group][name](...args));
    const state=snapshot=>snapshot?.state||snapshot,revision=snapshot=>state(snapshot)?.saveMeta?.revision;
    const apothecary=data=>data?.apothecary||data?.facilities?.apothecary||{},schoolhouse=data=>data?.schoolhouse||data?.facilities?.schoolhouse||{},claims=data=>data?.claims||{},archive=data=>data?.claimArchive||claims(data)?.archive||{},resources=data=>data?.resources||{};
    const cases=data=>apothecary(data)?.cases||[],lessons=data=>schoolhouse(data)?.lessons||[],pupils=data=>schoolhouse(data)?.pupils||[],offers=data=>claims(data)?.pendingOffers||data?.offers||[],receipts=data=>archive(data)?.recentReceipts||[];
    const firstCase=data=>cases(data)[0],firstLesson=data=>lessons(data)[0];

    (async()=>{
      await until(()=>bridge(),5000);const qa=bridge();add('bridge-present',Boolean(qa));
      if(!qa){add('phase18-19-contract-unavailable',false,'Expected before Phases 18-19 implementation: window.__EVERSTEAD_PHASE_18_19_QA__ is absent.');send();return}
      add('bridge-version',qa.version===f.bridgeVersion,qa.version);
      const requiredRead=['definitions','snapshot','validate','derive','tutorialLog','raw','exportSave','passiveBaseline','policyReport'];
      const requiredDestructive=['resetFixture','reload','importFixture','advanceOffline','mutateInvalid','settle','openFacility','beginApothecary','chooseDiagnosis','chooseRemedy','resolveApothecary','seatPupil','beginLesson','chooseApproach','resolveLesson','claim','claimGraduation','tutorial','simulateConcurrent','probeFinalizerFailure'];
      add('bridge-read-surface',requiredRead.every(name=>typeof qa.read?.[name]==='function'),Object.keys(qa.read||{}));add('bridge-destructive-surface',requiredDestructive.every(name=>typeof qa.destructive?.[name]==='function'),Object.keys(qa.destructive||{}));add('phase17-opening-fault-bridge',typeof phase17Bridge()?.destructive?.probeFacilityIntroductionFailure==='function',Object.keys(phase17Bridge()?.destructive||{}));
      if(!requiredRead.every(name=>typeof qa.read?.[name]==='function')||!requiredDestructive.every(name=>typeof qa.destructive?.[name]==='function')||typeof phase17Bridge()?.destructive?.probeFacilityIntroductionFailure!=='function'){send();return}

      const defs=call('read','definitions');if(!defs){send();return}
      add('predecessor-v2-runtime-seams',defs.predecessor?.phase12Coordinator===true&&defs.predecessor?.phase14Envelope===true&&defs.predecessor?.phase15OfferShape===f.predecessor.phase15OfferShape&&defs.predecessor?.phase15ReceiptEnvelopeVersion===f.predecessor.phase15ReceiptEnvelopeVersion&&defs.predecessor?.archiveConfigId===f.predecessor.phase15ArchiveConfigId&&defs.predecessor?.phase17StoryRegistryId===f.predecessor.phase17StoryRegistryId,defs.predecessor);
      add('distinct-facility-definition-lineage',defs.apothecary?.configId===f.facilities.apothecary.configId&&defs.apothecary?.definitionSetId===f.facilities.apothecary.definitionSetId&&defs.schoolhouse?.configId===f.facilities.schoolhouse.configId&&defs.schoolhouse?.definitionSetId===f.facilities.schoolhouse.definitionSetId,defs);
      add('nonexpiring-manual-opportunity-contract',defs.apothecary?.opportunity?.id===f.facilities.apothecary.opportunityDefinitionId&&defs.apothecary?.opportunity?.expires===false&&defs.apothecary?.opportunity?.claimMode==='manual'&&defs.schoolhouse?.opportunity?.id===f.facilities.schoolhouse.opportunityDefinitionId&&defs.schoolhouse?.opportunity?.expires===false&&defs.schoolhouse?.opportunity?.claimMode==='manual',{apothecary:defs.apothecary?.opportunity,schoolhouse:defs.schoolhouse?.opportunity});
      add('apothecary-content-identities',same((defs.apothecary?.cases||[]).map(item=>item.id),f.apothecary.caseIds)&&same((defs.apothecary?.clues||[]).map(item=>item.id),f.apothecary.clueIds)&&same((defs.apothecary?.diagnoses||[]).map(item=>item.id),f.apothecary.diagnosisIds)&&same((defs.apothecary?.remedies||[]).map(item=>item.id),f.apothecary.remedyIds),defs.apothecary);
      add('apothecary-forgiving-outcomes',same((defs.apothecary?.outcomes||[]).map(item=>item.id),f.apothecary.outcomeIds)&&defs.apothecary.outcomes[0]?.terminal===false&&defs.apothecary.outcomes[0]?.rewards==null&&!defs.apothecary.outcomes.some(item=>item.terminal&&String(item.id).includes('fail')),defs.apothecary?.outcomes);
      add('schoolhouse-persistent-content-identities',same((defs.schoolhouse?.domains||[]).map(item=>item.id),f.schoolhouse.domainIds)&&same((defs.schoolhouse?.approaches||[]).map(item=>item.id),f.schoolhouse.approachIds)&&same((defs.schoolhouse?.lessons||[]).map(item=>item.id),f.schoolhouse.lessonIds)&&same((defs.schoolhouse?.pupils||[]).map(item=>item.id),f.schoolhouse.pupilIds),defs.schoolhouse);
      add('graduation-v2-one-shot-contract',defs.schoolhouse?.graduation?.definitionId===f.schoolhouse.graduationDefinitionId&&defs.schoolhouse?.graduation?.offerTemplate===f.schoolhouse.graduationOfferTemplate&&defs.schoolhouse?.graduation?.domainClaimKind===f.schoolhouse.graduationDomainClaimKind&&defs.schoolhouse?.graduation?.recurringOpportunityRequired===false&&defs.schoolhouse?.graduation?.manual===true&&defs.schoolhouse?.graduation?.exactlyOnce===true,defs.schoolhouse?.graduation);
      add('three-immutable-finalizers',same(defs.finalizers,f.finalizers)&&defs.finalizers.every(item=>item.immutable===true&&item.callerSupplied===false),defs.finalizers);
      add('family-mentor-positive-only-contract',defs.schoolhouse?.mentor?.stackLimit===1&&defs.schoolhouse?.mentor?.positiveOnly===true&&defs.schoolhouse?.mentor?.absenceUsesBaseline===true&&defs.schoolhouse?.mentor?.consumesOrMutatesRelationship===false&&defs.schoolhouse?.mentor?.captureAt==='lesson-resolution',defs.schoolhouse?.mentor);
      add('nine-tutorials-segmented-exact',same((defs.tutorials||[]).map(item=>item.id),f.tutorialIds)&&same(defs.schoolhouseFirstLessonSegments,f.schoolhouseFirstLessonSegments)&&(defs.tutorials||[]).every(item=>item.blocking===false&&item.reward==null&&item.skippable===true&&item.replayable===true),defs.tutorials);
      add('ten-actor-subset-player-separation-and-visual-policy',same(sorted((defs.cast||[]).map(item=>item.actorId)),sorted(f.actorIds))&&!(defs.cast||[]).some(item=>item.actorId===f.protagonist.id)&&defs.castPolicy?.lockedFellowsExcluded===true&&defs.castPolicy?.protagonistId===f.protagonist.id&&defs.castPolicy?.protagonistRosterKind==='player-character'&&same(defs.castPolicy?.protagonistExcludedRosterKinds,f.protagonist.excludedRosterKinds)&&same(defs.castPolicy?.artFallbackOrder,f.approvedVisualFallbacks)&&defs.castPolicy?.forbiddenPresentation==='unframed-full-background-profile-overlay'&&defs.visualPolishBoundary?.originalEversteadOnly===true&&defs.visualPolishBoundary?.referenceAssetsIngested===false&&defs.visualPolishBoundary?.referenceTradeDressCopied===false,{cast:defs.cast,policy:defs.castPolicy,visual:defs.visualPolishBoundary});
      const expectedMotionMarker=config.viewport.reducedMotion?f.reducedMotionContract.reduceMarker:f.reducedMotionContract.defaultMarker,actualMotionMarker=document.documentElement.getAttribute(f.reducedMotionContract.rootMarkerAttribute),cssMotion=config.candidateReducedCssContract||{};add('runtime-marker-and-static-css-reduced-motion-contract',actualMotionMarker===expectedMotionMarker&&defs.runtime?.reducedMotionMarker===expectedMotionMarker&&cssMotion.hasMediaRule===true&&cssMotion.globalAnimationNone===true&&cssMotion.globalTransitionNone===true,{expectedMotionMarker,actualMotionMarker,bridgeMarker:defs.runtime?.reducedMotionMarker,cssMotion});
      const policy=call('read','policyReport');if(defs.productionEnabled===true)add('enabled-policy-complete-and-not-restaurant',policy?.approved===true&&policy?.qaOnly!==true&&policy?.apothecary?.complete===true&&policy?.schoolhouse?.complete===true&&policy?.restaurantPolicyIdsUsed?.length===0&&policy?.fiveYearHeadroomApproved===true,policy);else add('null-policy-fails-closed',policy?.productionEnabled===false&&policy?.apothecary?.generationEnabled===false&&policy?.apothecary?.resolutionEnabled===false&&policy?.schoolhouse?.generationEnabled===false&&policy?.schoolhouse?.resolutionEnabled===false&&policy?.schoolhouse?.graduationEnabled===false&&policy?.fallbackUsed===false,policy);

      const passiveAt=f.passiveSnapshotContract.capturedAt,passiveBefore=call('read','passiveBaseline',passiveAt),passiveFieldsOk=f.passiveSnapshotContract.requiredFields.every(key=>Object.hasOwn(passiveBefore||{},key)),passiveBuildings=passiveBefore?.buildingSemantics||[],volatilePassiveJson=JSON.stringify(passiveBefore);add('passive-baseline-same-time-normalized-contract',passiveFieldsOk&&passiveBefore?.capturedAt===passiveAt&&passiveBefore?.offlineCapMs===f.offlineCapMs&&passiveBuildings.length===4&&same(passiveBuildings.map(item=>item.facilityId),f.originalPassiveFacilityIds)&&passiveBuildings.every(item=>f.passiveSnapshotContract.buildingFields.every(key=>Object.hasOwn(item,key)))&&f.passiveSnapshotContract.excludedVolatileFields.every(key=>!volatilePassiveJson.includes(`"${key}"`)),passiveBefore);
      const exerciseIntroduction=async({facilityId,fixtureId,resolution,tutorialId,keyboard})=>{
        const openIntroduction=async({reset=false}={})=>{
          const fixtureReset=reset?call('destructive','resetFixture',fixtureId):{ok:true};await wait(40);
          const hotspot=document.querySelector(`[data-phase15-facility-id="${facilityId}"]`),ambient=document.querySelector('[data-nav="more"]');ambient?.focus();const beforeOpenRaw=call('read','raw');
          if(keyboard){hotspot?.focus();hotspot?.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))}else hotspot?.click();
          await wait(40);const introduction=document.querySelector(`[data-phase17-facility-introduction="${facilityId}"][data-phase17-facility-introduction-mode="opening"]`);
          return{fixtureReset,hotspot,beforeOpenRaw,introduction,entryFocus:Boolean(introduction)&&introduction.contains(document.activeElement)}
        };
        let opening=await openIntroduction({reset:true});const fixtureReset=opening.fixtureReset?.ok===true,faults=[];let faultAtomic=true;
        for(const mode of ['after-unlock','after-projection','after-outcome']){
          const faultRaw=call('read','raw'),faultSnapshot=call('read','snapshot'),faultRevision=revision(faultSnapshot),item=call17('destructive','probeFacilityIntroductionFailure',facilityId,mode),afterFaultSnapshot=call('read','snapshot'),stateUnchanged=same(item?.before,item?.after)&&same(faultSnapshot,afterFaultSnapshot),rawUnchanged=item?.rawChanged===false&&call('read','raw')===faultRaw,revisionUnchanged=revision(afterFaultSnapshot)===faultRevision,recovery=call('destructive','reload');await wait(40);const recoverySnapshot=call('read','snapshot'),recoveryNoop=recovery?.ok===true&&recovery?.rawUnchanged===true&&call('read','raw')===faultRaw&&revision(recoverySnapshot)===faultRevision&&same(state(recoverySnapshot),state(faultSnapshot));faults.push({mode,ok:item?.ok,reason:item?.reason,writes:item?.writes,stateUnchanged,rawUnchanged,revisionUnchanged,recoveryNoop});faultAtomic&&=item?.ok===false&&stateUnchanged&&rawUnchanged&&revisionUnchanged&&recoveryNoop;opening=await openIntroduction()
        }
        const {hotspot,beforeOpenRaw,introduction,entryFocus}=opening,faultRaw=call('read','raw'),beforeResolve=call('read','derive'),beforeResolveRevision=revision(call('read','snapshot')),resolutionButton=document.querySelector(`[data-phase17-opening-resolution="${resolution}"][data-phase17-opening-facility="${facilityId}"]`);resolutionButton?.click();await wait(60);
        const afterResolve=call('read','derive'),snapshotAfter=call('read','snapshot'),openingId=facilityId==='facility.apothecary'?f.facilities.apothecary.openingContentId:f.facilities.schoolhouse.openingContentId,outcome=state(snapshotAfter)?.phase1819?.tutorials?.facilityIntroductionResolutionsByContentId?.[openingId],focusReturned=document.activeElement===hotspot,facilityUnlocked=state(snapshotAfter)?.facilityProgress?.unlockedIds?.includes(facilityId)&&state(snapshotAfter)?.phase1819?.[facilityId.split('.').at(-1)]?.unlocked===true,atomicSuccess=revision(snapshotAfter)===beforeResolveRevision+1&&outcome===resolution&&facilityUnlocked&&same(resources(afterResolve),resources(beforeResolve));
        let liveNamedPatientNoop=true;if(facilityId==='facility.apothecary'){call('destructive','settle',facilityId,f.frozenNow+f.syntheticPolicy.apothecary.intervalMs);const patientBefore=call('read','snapshot'),patientRaw=call('read','raw'),patientRevision=revision(patientBefore),patientReload=call('destructive','reload'),patientAfter=call('read','snapshot'),patientRoot=state(patientAfter)?.phase1819?.apothecary,liveRook=Object.values(patientRoot?.cases||{}).filter(item=>item.patientId==='apothecary.patient.named.rook').length,pendingRook=(patientRoot?.pendingNamedPatientIds||[]).filter(id=>id==='apothecary.patient.named.rook').length;liveNamedPatientNoop=patientReload?.ok===true&&patientReload?.rawUnchanged===true&&call('read','raw')===patientRaw&&revision(patientAfter)===patientRevision&&same(state(patientAfter),state(patientBefore))&&liveRook===1&&pendingRook===0}
        const completedSnapshot=call('read','snapshot'),completedRaw=call('read','raw'),completedRevision=revision(completedSnapshot),reload=call('destructive','reload'),reloadedSnapshot=call('read','snapshot'),reloadNoop=reload?.ok===true&&reload?.rawUnchanged===true&&call('read','raw')===completedRaw&&revision(reloadedSnapshot)===completedRevision&&same(state(reloadedSnapshot),state(completedSnapshot));document.querySelector('[data-nav="more"]')?.click();await wait(40);document.querySelector('[data-phase13-tutorial-log]')?.click();await wait(40);
        const row=document.querySelector(`[data-phase1819-tutorial-log-row="${tutorialId}"]`),rowPersisted=Boolean(row)&&row.textContent.toLowerCase().includes(resolution),replayButton=row?.querySelector('[data-phase1819-tutorial-replay]'),beforeReplayRaw=call('read','raw'),beforeReplayRevision=revision(call('read','snapshot'));replayButton?.click();await wait(40);const replay=document.querySelector(`[data-phase17-facility-introduction="${facilityId}"][data-phase17-facility-introduction-mode="replay"]`),replayNeutral=Boolean(replay)&&call('read','raw')===beforeReplayRaw&&revision(call('read','snapshot'))===beforeReplayRevision;document.activeElement?.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(40);
        return{fixtureReset,hotspot:Boolean(hotspot),opening:beforeOpenRaw===faultRaw&&Boolean(introduction),entryFocus,faultAtomic,atomicSuccess,focusReturned,liveNamedPatientNoop,reloadNoop,rowPersisted,replayNeutral,outcome,faults}
      };
      const apothecaryIntroduction=await exerciseIntroduction({facilityId:f.facilities.apothecary.facilityId,fixtureId:f.saveFixtures.apothecaryIntroduction,resolution:'watched',tutorialId:'tutorial.facility.apothecary.first-case',keyboard:false});add('apothecary-pointer-discover-introduce-atomic-focus-log-replay',Object.entries(apothecaryIntroduction).filter(([key])=>!['outcome','faults'].includes(key)).every(([,value])=>value===true),apothecaryIntroduction);
      const schoolhouseIntroduction=await exerciseIntroduction({facilityId:f.facilities.schoolhouse.facilityId,fixtureId:f.saveFixtures.schoolhouseIntroduction,resolution:'skipped',tutorialId:'tutorial.facility.schoolhouse.first-lesson',keyboard:true});add('schoolhouse-keyboard-discover-introduce-atomic-focus-log-replay',Object.entries(schoolhouseIntroduction).filter(([key])=>!['outcome','faults'].includes(key)).every(([,value])=>value===true),schoolhouseIntroduction);
      const openingFaultResults=[...apothecaryIntroduction.faults,...schoolhouseIntroduction.faults];add('facility-introduction-three-stage-rollback-atomic',apothecaryIntroduction.faultAtomic===true&&schoolhouseIntroduction.faultAtomic===true&&openingFaultResults.length===6&&openingFaultResults.every(item=>item?.ok===false&&item?.stateUnchanged===true&&item?.rawUnchanged===true&&item?.revisionUnchanged===true&&item?.recoveryNoop===true),{modes:['after-unlock','after-projection','after-outcome'],apothecary:apothecaryIntroduction.faults,schoolhouse:schoolhouseIntroduction.faults});
      call('destructive','resetFixture',f.saveFixtures.apothecaryUnlocked);const empty=call('read','derive'),emptyResources=resources(empty),partial=call('destructive','settle',f.facilities.apothecary.facilityId,f.frozenNow+f.syntheticPolicy.apothecary.intervalMs-1);add('apothecary-partial-carry-zero-credit',partial?.ok===true&&partial?.createdCount===0&&partial?.carryMs===f.syntheticPolicy.apothecary.intervalMs-1&&cases(call('read','derive')).length===0&&same(resources(call('read','derive')),emptyResources),partial);
      call('destructive','resetFixture',f.saveFixtures.apothecaryUnlocked);const settled=call('destructive','settle',f.facilities.apothecary.facilityId,f.frozenNow+2*f.syntheticPolicy.apothecary.intervalMs),settledCases=cases(call('read','derive'));add('apothecary-nonexpiring-deterministic-bank',settled?.ok===true&&settled?.createdCount===2&&same(settledCases.map(item=>item.ordinal),[1,2])&&unique(settledCases.map(item=>item.identity))&&settledCases.every(item=>item.expiresAt==null&&item.status==='banked'),{settled,settledCases});
      const bankRaw=call('read','raw');call('destructive','reload');add('apothecary-bank-survives-reload',call('read','raw')===bankRaw&&same(cases(call('read','derive')),settledCases),cases(call('read','derive')));
      const saturated=call('destructive','settle',f.facilities.apothecary.facilityId,f.frozenNow+48*f.syntheticPolicy.apothecary.intervalMs);add('apothecary-saturation-no-hidden-debt',saturated?.ok===true&&cases(call('read','derive')).length===f.syntheticPolicy.apothecary.bankCapacity&&saturated?.hiddenDebtMs===0&&cases(call('read','derive')).every(item=>item.expiresAt==null),saturated);

      call('destructive','resetFixture',f.saveFixtures.apothecaryBanked);let caseItem=firstCase(call('read','derive')),begin=call('destructive','beginApothecary',caseItem.id,caseItem.identity),engaged=firstCase(call('read','derive'));add('apothecary-begin-shows-immutable-detail',begin?.ok===true&&engaged?.status==='engaged'&&f.apothecary.caseIds.includes(engaged?.caseTemplateId)&&Array.isArray(engaged?.clueIds)&&engaged.clueIds.length===3&&engaged.clueIds.every(id=>f.apothecary.clueIds.includes(id)),engaged);
      const wrongDiagnosis=f.apothecary.diagnosisIds.find(id=>id!==engaged.preciseDiagnosisId),support=f.apothecary.remedyIds.at(-1);call('destructive','chooseDiagnosis',engaged.id,engaged.identity,wrongDiagnosis);call('destructive','chooseRemedy',engaged.id,engaged.identity,engaged.preciseRemedyIds?.[0]||f.apothecary.remedyIds[0]);const beforeRecheck=call('read','derive'),recheck=call('destructive','resolveApothecary',engaged.id,engaged.identity),afterRecheck=call('read','derive'),rechecked=firstCase(afterRecheck);add('apothecary-recheck-nonterminal-rewardless',recheck?.ok===true&&recheck?.outcomeId==='apothecary.outcome.recheck'&&rechecked?.status==='engaged'&&rechecked?.resumeStep==='recheck'&&offers(afterRecheck).length===0&&same(resources(afterRecheck),resources(beforeRecheck))&&Number(recheck?.rewardApplications||0)===0&&Number(recheck?.masteryApplications||0)===0,recheck);
      const recheckRaw=call('read','raw');call('destructive','reload');add('apothecary-recheck-resumes-same-case',firstCase(call('read','derive'))?.identity===engaged.identity&&firstCase(call('read','derive'))?.resumeStep==='recheck'&&call('read','raw')===recheckRaw,firstCase(call('read','derive')));
      call('destructive','chooseDiagnosis',engaged.id,engaged.identity,engaged.preciseDiagnosisId);call('destructive','chooseRemedy',engaged.id,engaged.identity,support);const beforeResolve=call('read','derive'),terminal=call('destructive','resolveApothecary',engaged.id,engaged.identity),readyState=call('read','derive'),readyCase=firstCase(readyState),caseOffer=offers(readyState)[0];add('apothecary-supportive-terminal-zero-payment',terminal?.ok===true&&terminal?.outcomeId==='apothecary.outcome.supportive'&&readyCase?.status==='claim-ready'&&offers(readyState).length===1&&caseOffer?.sourceId===f.facilities.apothecary.activityId&&same(resources(readyState),resources(beforeResolve)),{terminal,readyCase,caseOffer});
      const beforeCaseClaim=call('read','derive'),beforeCaseSnapshot=call('read','snapshot'),caseClaim=call('destructive','claim',caseOffer.id,caseOffer.identity),afterCaseClaim=call('read','derive');add('apothecary-claim-atomic-global-local-history-v2',caseClaim?.ok===true&&revision(call('read','snapshot'))===revision(beforeCaseSnapshot)+1&&caseClaim?.globalApplications===1&&caseClaim?.localApplications===1&&caseClaim?.receiptApplications===1&&cases(afterCaseClaim).length===0&&offers(afterCaseClaim).length===0&&Number(resources(afterCaseClaim).gold)>Number(resources(beforeCaseClaim).gold)&&receipts(afterCaseClaim).at(-1)?.sourceId===f.facilities.apothecary.activityId,caseClaim);
      const claimedRaw=call('read','raw'),repeatCase=call('destructive','claim',caseOffer.id,caseOffer.identity);add('apothecary-claim-exactly-once',repeatCase?.ok===false&&Number(repeatCase?.writes||0)===0&&call('read','raw')===claimedRaw,repeatCase);

      call('destructive','resetFixture',f.saveFixtures.schoolhouseUnlocked);const lessonSettle=call('destructive','settle',f.facilities.schoolhouse.facilityId,f.frozenNow+2*f.syntheticPolicy.schoolhouse.intervalMs),bankedLessons=lessons(call('read','derive'));add('schoolhouse-lessons-bank-without-pupil',lessonSettle?.ok===true&&bankedLessons.length===2&&pupils(call('read','derive')).length===0&&bankedLessons.every(item=>item.status==='banked'&&item.expiresAt==null),{lessonSettle,bankedLessons});
      call('destructive','resetFixture',f.saveFixtures.schoolhouseCandidate);const pupilId=f.schoolhouse.pupilIds[0],seatId='schoolhouse.seat.1',seat=call('destructive','seatPupil',pupilId,seatId),afterSeat=call('read','derive'),seatAgain=call('destructive','seatPupil',pupilId,seatId);add('schoolhouse-unique-neutral-seating',seat?.ok===true&&pupils(afterSeat).filter(item=>item.id===pupilId&&item.seatId===seatId).length===1&&seatAgain?.ok===false&&Number(seatAgain?.writes||0)===0&&Number(seat?.rewardApplications||0)===0&&Number(seat?.relationshipApplications||0)===0,{seat,seatAgain,pupils:pupils(afterSeat)});
      call('destructive','resetFixture',f.saveFixtures.schoolhouseLessonsBanked);let lesson=firstLesson(call('read','derive'));const lessonBegin=call('destructive','beginLesson',lesson.id,lesson.identity,pupilId,seatId),lessonEngaged=firstLesson(call('read','derive')),approach=f.schoolhouse.approachIds[0];call('destructive','chooseApproach',lessonEngaged.id,lessonEngaged.identity,approach,null);const engagedRaw=call('read','raw');call('destructive','reload');add('schoolhouse-engagement-resumes-exactly',call('read','raw')===engagedRaw&&firstLesson(call('read','derive'))?.identity===lessonEngaged.identity&&firstLesson(call('read','derive'))?.pupilId===pupilId&&firstLesson(call('read','derive'))?.seatId===seatId&&firstLesson(call('read','derive'))?.approachId===approach,{lessonBegin,lesson:firstLesson(call('read','derive'))});
      const beforeLessonResolve=call('read','derive'),lessonResolve=call('destructive','resolveLesson',lessonEngaged.id,lessonEngaged.identity),lessonReady=call('read','derive'),lessonOffer=offers(lessonReady)[0];add('schoolhouse-guided-or-resonant-zero-payment',lessonResolve?.ok===true&&f.schoolhouse.outcomeIds.includes(lessonResolve?.outcomeId)&&firstLesson(lessonReady)?.status==='claim-ready'&&offers(lessonReady).length===1&&lessonOffer?.sourceId===f.facilities.schoolhouse.activityId&&same(resources(lessonReady),resources(beforeLessonResolve)),{lessonResolve,lesson:firstLesson(lessonReady),offer:lessonOffer});
      const familyBefore=call('read','snapshot')?.state?.family,beforeLessonSnapshot=call('read','snapshot'),lessonClaim=call('destructive','claim',lessonOffer.id,lessonOffer.identity),afterLesson=call('read','derive'),pupilAfter=pupils(afterLesson).find(item=>item.id===pupilId);add('schoolhouse-lesson-claim-persistent-development',lessonClaim?.ok===true&&revision(call('read','snapshot'))===revision(beforeLessonSnapshot)+1&&lessonClaim?.globalApplications===1&&lessonClaim?.developmentApplications===1&&lessonClaim?.educationApplications===1&&lessonClaim?.receiptApplications===1&&pupilAfter?.claimedLessonCount>=1&&pupilAfter?.seatId===seatId,lessonClaim);add('family-bytes-never-mutated-by-mentor',same(call('read','snapshot')?.state?.family,familyBefore),{before:familyBefore,after:call('read','snapshot')?.state?.family});

      call('destructive','resetFixture',f.saveFixtures.schoolhouseGraduationReady);const graduationBefore=call('read','derive'),graduationOffer=offers(graduationBefore).find(item=>item.domainClaimKind===f.schoolhouse.graduationDomainClaimKind),graduation=call('destructive','claimGraduation',graduationOffer.id,graduationOffer.identity),graduated=call('read','derive');add('graduation-v2-exactly-once-seat-release',graduation?.ok===true&&graduation?.majorRewardApplications===1&&graduation?.educationApplications===1&&graduation?.receiptApplications===1&&schoolhouse(graduated)?.graduatedPupilIds?.includes(pupilId)&&schoolhouse(graduated)?.graduationReceiptIdByPupilId?.[pupilId]&&pupils(graduated).find(item=>item.id===pupilId)?.seatId==null&&offers(graduated).every(item=>item.id!==graduationOffer.id),graduation);
      const graduatedRaw=call('read','raw'),graduationAgain=call('destructive','claimGraduation',graduationOffer.id,graduationOffer.identity);add('graduation-repeat-reload-safe',graduationAgain?.ok===false&&Number(graduationAgain?.writes||0)===0&&call('read','raw')===graduatedRaw,graduationAgain);

      for(const entry of f.finalizers)for(const mode of ['missing','throw','local','archive']){const failure=call('destructive','probeFinalizerFailure',entry.domainClaimKind,mode);add(`finalizer-${entry.domainClaimKind}-${mode}-atomic-refusal`,failure?.ok===false&&failure?.partialApplications===0&&failure?.activeUnchanged===true&&failure?.rawUnchanged===true&&failure?.revisionUnchanged===true&&failure?.resourcesUnchanged===true&&failure?.localUnchanged===true&&failure?.archiveUnchanged===true,failure)}
      for(const kind of f.concurrencyKinds){const race=call('destructive','simulateConcurrent',kind);add(`two-client-${kind}-one-winner`,race?.ok===true&&race?.winnerCount===1&&race?.loserCount===1&&race?.losingWrites===0&&race?.duplicateOpportunityCount===0&&race?.duplicateOutcomeCount===0&&race?.duplicatePupilCount===0&&race?.duplicateReceiptCount===0&&race?.finalValid===true,race)}

      call('destructive','resetFixture',f.saveFixtures.archiveWindow);const archiveBefore=archive(call('read','derive')),archiveOffer=offers(call('read','derive'))[0],archiveClaim=archiveOffer?.domainClaimKind===f.schoolhouse.graduationDomainClaimKind?call('destructive','claimGraduation',archiveOffer.id,archiveOffer.identity):call('destructive','claim',archiveOffer.id,archiveOffer.identity),archiveAfter=archive(call('read','derive'));add('v2-archive-fold-preserves-domain-authority',archiveBefore?.recentReceipts?.length===512&&archiveClaim?.ok===true&&archiveAfter?.recentReceipts?.length===f.archivePolicy.expectedRecentAfterNextClaim&&archiveAfter?.throughSequence===f.archivePolicy.expectedThroughAfterNextClaim&&archiveClaim?.domainReplayAuthorityPreserved===true,{before:archiveBefore,after:archiveAfter,claim:archiveClaim});
      const exported=call('read','exportSave'),exportRaw=call('read','raw'),imported=call('destructive','importFixture',exported);add('export-import-preserves-both-facilities-v2',imported?.ok===true&&call('read','raw')===exportRaw&&call('read','validate')?.ok===true,imported);
      call('destructive','resetFixture',f.saveFixtures.migrated19);const migrated=call('read','derive');add('ordered-additive-migration-no-inferred-value',call('read','validate')?.ok===true&&same(migrated?.migrationIds?.slice(-2),f.migrationIds)&&cases(migrated).length===0&&lessons(migrated).length===0&&offers(migrated).length===0&&schoolhouse(migrated)?.graduationReadyCount===0,migrated);
      call('destructive','resetFixture',f.saveFixtures.recovery);const recovery=call('destructive','reload');add('recovery-one-authority-no-duplicates',recovery?.ok===true&&call('read','validate')?.ok===true&&unique([...cases(call('read','derive')).map(item=>item.identity),...lessons(call('read','derive')).map(item=>item.identity)])&&unique(receipts(call('read','derive')).map(item=>item.id)),recovery);
      call('destructive','resetFixture',f.saveFixtures.freshNullPolicy);const safeRaw=call('read','raw'),invalid=f.invalidMutationChecks.map(kind=>call('destructive','mutateInvalid',kind));add('malformed-imports-fail-closed',invalid.every((item,index)=>item?.ok===false&&item?.check===f.invalidMutationChecks[index]&&Number(item?.writes||0)===0)&&call('read','raw')===safeRaw,invalid);
      const offline=call('destructive','advanceOffline',{elapsedMs:f.offlineCapMs*2,includeMidnight:true,includeDst:true});add('offline-cap-banks-only-no-agency',offline?.ok===true&&offline?.appliedMs===f.offlineCapMs&&offline?.timezoneEquivalent===true&&offline?.midnightSegmented===false&&offline?.chosenCount===0&&offline?.resolvedCount===0&&offline?.claimedCount===0&&offline?.graduatedCount===0,offline);

      const tutorialA=call('destructive','tutorial',f.tutorialIds[6],'open'),tutorialB=call('destructive','tutorial',f.tutorialIds[6],'advance-context'),tutorialRaw=call('read','raw'),tutorialReplay=call('destructive','tutorial',f.tutorialIds[6],'replay');add('schoolhouse-tutorial-segments-existing-steps',tutorialA?.ok===true&&tutorialB?.ok===true&&same(tutorialB?.segments,f.schoolhouseFirstLessonSegments),{tutorialA,tutorialB});add('tutorial-replay-mechanically-neutral',tutorialReplay?.ok===true&&call('read','raw')===tutorialRaw,tutorialReplay);
      call('destructive','resetFixture',f.saveFixtures.lockedRoster);const rosterState=call('read','derive')?.roster||{},dialogue=call('read','derive')?.dialogue||{},joined=rosterState.joinedFellowIds||[],selected=dialogue.selectedSpeakers||[],collectibleIds=[...(rosterState.fellowIds||[]),...(rosterState.familyIds||[]),...(rosterState.companionIds||[])],assignmentIds=[...(rosterState.fellowAssignmentIds||[]),...(rosterState.familyAssignmentIds||[]),...(rosterState.companionAssignmentIds||[])],shardIds=rosterState.shardOwnerIds||[];add('exact-ten-cast-locked-fellows-never-speak',same(sorted(dialogue.registeredActorIds||[]),sorted(f.actorIds))&&selected.every(actorId=>!String(actorId).startsWith('fellow.')||joined.includes(actorId)),{registered:dialogue.registeredActorIds,selected,joined});add('player-wayfarer-separate-from-collectible-rosters',rosterState.playerCharacterId===f.protagonist.id&&!collectibleIds.includes(f.protagonist.id)&&!assignmentIds.includes(f.protagonist.id)&&!shardIds.includes(f.protagonist.id)&&!dialogue.registeredActorIds?.includes(f.protagonist.id),{playerCharacterId:rosterState.playerCharacterId,collectibleIds,assignmentIds,shardIds});add('approved-visual-fallback-only',(dialogue.presentations||[]).every(item=>f.approvedVisualFallbacks.includes(item.mode)&&item.unframedFullPortrait!==true),dialogue.presentations);

      call('destructive','resetFixture',f.saveFixtures.apothecaryBanked);await wait(50);const nav=[...document.querySelectorAll('[data-tab],nav button,[role="navigation"] button')].filter(node=>{const style=getComputedStyle(node);return style.display!=='none'&&style.visibility!=='hidden'}),board=document.querySelector('[data-phase15-facility-board]'),apothecaryHotspot=document.querySelector('[data-phase15-facility-id="facility.apothecary"]'),schoolhouseHotspot=document.querySelector('[data-phase15-facility-id="facility.schoolhouse"]');
      add('actual-dom-five-nav-two-eastern-hotspots',nav.length===5&&Boolean(board)&&Boolean(apothecaryHotspot)&&Boolean(schoolhouseHotspot)&&apothecaryHotspot?.dataset.phase15MapAnchor===f.facilities.apothecary.mapAnchor&&schoolhouseHotspot?.dataset.phase15MapAnchor===f.facilities.schoolhouse.mapAnchor,{nav:nav.map(node=>node.textContent.trim()),board:Boolean(board)});
      const targetOk=hotspot=>{const rect=hotspot?.getBoundingClientRect();return Boolean(rect&&rect.width>=44&&rect.height>=44&&rect.left>=0&&rect.right<=innerWidth+1&&rect.top>=0&&rect.bottom<=innerHeight+1)};add('actual-dom-hotspots-44px-in-viewport',targetOk(apothecaryHotspot)&&targetOk(schoolhouseHotspot),{apothecary:apothecaryHotspot?.getBoundingClientRect(),schoolhouse:schoolhouseHotspot?.getBoundingClientRect()});
      const exerciseSurface=async(hotspot,key,sheetSelector,selectors)=>{if(!hotspot)return{opened:false,focus:false,keyboard:false,escape:false,sheetClosed:false,focusReturned:false,controls:false,statusText:false,singleActivation:false};hotspot.focus();const beforeOpen=call('read','raw');hotspot.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true}));await wait(30);const sheet=document.querySelector(sheetSelector),focus=Boolean(sheet)&&sheet.contains(document.activeElement),controls=selectors.every(selector=>document.querySelector(selector)),keyboard=Boolean(sheet)&&[...sheet.querySelectorAll('button,[role="button"],input,select')].every(node=>node.matches(':disabled')||node.tabIndex>=0),statusText=Boolean(sheet?.textContent?.trim()),singleActivation=call('read','raw')===beforeOpen,escapeTarget=document.activeElement||sheet;escapeTarget?.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(50);const sheetClosed=!document.querySelector(sheetSelector),focusReturned=document.activeElement===hotspot;return{opened:Boolean(sheet),focus,keyboard,escape:sheetClosed&&focusReturned,sheetClosed,focusReturned,controls,statusText,singleActivation}};
      const beforeDomRaw=call('read','raw'),apothecaryDom=await exerciseSurface(apothecaryHotspot,'Enter','[data-phase18-apothecary-sheet]',f.requiredDomSelectors.apothecary),schoolhouseDom=await exerciseSurface(schoolhouseHotspot,' ','[data-phase19-schoolhouse-sheet]',f.requiredDomSelectors.schoolhouse);add('actual-dom-apothecary-focus-keyboard-escape-controls',Object.values(apothecaryDom).every(Boolean),apothecaryDom);add('actual-dom-schoolhouse-focus-keyboard-escape-controls',Object.values(schoolhouseDom).every(Boolean),schoolhouseDom);add('actual-dom-open-close-write-neutral',call('read','raw')===beforeDomRaw);
      const noOverflow=document.documentElement.scrollWidth<=document.documentElement.clientWidth+1&&document.body.scrollWidth<=document.body.clientWidth+1;add('actual-dom-no-overflow-at-copy-scale',noOverflow,{viewport:[innerWidth,innerHeight],copyScale:config.viewport.copyScale,document:[document.documentElement.clientWidth,document.documentElement.scrollWidth]});
      add('actual-dom-reduced-motion-semantic-nodes-present',!config.viewport.reducedMotion||[board,apothecaryHotspot,schoolhouseHotspot].every(Boolean),{reducedMotion:config.viewport.reducedMotion,marker:actualMotionMarker,cssMotion});
      const passiveAfter=call('read','passiveBaseline',passiveAt);add('passive-original-four-same-time-semantics-preserved',same(passiveAfter,passiveBefore),{capturedAt:passiveAt,before:passiveBefore,after:passiveAfter});add('final-state-valid',call('read','validate')?.ok===true,call('read','validate'));add('native-storage-instrumented',window.__P1819I_NATIVE_INSTRUMENTED__===true);add('zero-native-storage-accesses',window.__P1819I_NATIVE_ACCESSES__.length===0,window.__P1819I_NATIVE_ACCESSES__);add('zero-warning-error-console',window.__P1819I_ERRORS__.length===0,window.__P1819I_ERRORS__);send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();if(source.indexOf('<script')<0)throw new Error('Production script tag missing');const styleText=[...source.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)].map(match=>match[1]).join('\n');config.candidateReducedCssContract={hasMediaRule:/@media\s*\(\s*prefers-reduced-motion\s*:\s*reduce\s*\)/i.test(styleText),globalAnimationNone:/\*,\s*\*::?before,\s*\*::?after\s*\{[^}]*animation\s*:\s*none\s*!important/i.test(styleText),globalTransitionNone:/\*,\s*\*::?before,\s*\*::?after\s*\{[^}]*transition\s*:\s*none\s*!important/i.test(styleText)};const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`;source=source.replace('<head>','<head><base href="../../">');const insertion=source.indexOf('<script');source=source.slice(0,insertion)+bootstrap+source.slice(insertion).replace('</body>',suite+'</body>');document.open();document.write(source);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
