(()=>{
  'use strict';
  const CHANNEL='everstead-phase-23-independent-v1',byId=id=>document.getElementById(id),escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),row=(id,actual,detail='')=>({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)});
  async function loadJson(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.json()}
  function realm(fixtures,viewport,mode){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),config={channel:CHANNEL,nonce,viewport,fixtures,mode};frame.name=JSON.stringify(config);frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0`;let timer;const finish=(error,value)=>{clearTimeout(timer);removeEventListener('message',receive);frame.remove();error?reject(error):resolve(value)},receive=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=(event.data.results||[]).map(item=>({...item,id:`${viewport.id}-${mode}-${item.id}`}));if(event.data.errors?.length&&!rows.some(item=>item.id.endsWith('zero-warning-error-console')&&!item.pass))rows.push(row(`${viewport.id}-${mode}-captured-errors`,false,event.data.errors.join('\n')));finish(null,rows)};timer=setTimeout(()=>finish(new Error(`${viewport.id} ${mode} timed out`)),120000);addEventListener('message',receive);frame.src=`./realm.html?qa=1&mode=${encodeURIComponent(mode)}&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  function render(mode,rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('mode').textContent=mode;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)} · observed ${item.actual?'true':'false'} · expected true${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_23_INDEPENDENT_RESULT__={mode,passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const f=await loadJson('./fixtures/contract.json'),rows=[],ids=f.roster.map(item=>item.id),unique=values=>new Set(values).size===values.length;rows.push(row('fixture-contract-v1',f.contractVersion===1&&f.phase===23&&f.schemaVersion===13&&f.bridgeVersion==='phase-23-independent-qa-v1'));rows.push(row('fixture-exact-20-order',ids.length===20&&unique(ids)&&ids.join(',')==='arcanine,dewgong,snorlax,dragonite,charizard,venusaur,blastoise,jolteon,machamp,meganium,feraligatr,miltank,donphan,lucario,boltund,stoutland,mabosstiff,zacian,lugia,suicune'));rows.push(row('fixture-aggregate-2200',f.roster.reduce((sum,item)=>sum+item.basePower,0)===2200&&f.aggregateBasePower===2200));rows.push(row('fixture-private-rights-fail-closed',f.assetPolicy.privateBuildOnly===true&&f.assetPolicy.publicReleaseAllowed===false&&f.assetPolicy.trackedRightsLimitedBinariesAllowed===false));rows.push(row('fixture-ten-two-member-pools-cover-all',f.stagePools.length===10&&f.stagePools.every(item=>item.targetIds.length===2)&&f.stagePools.flatMap(item=>item.targetIds).join(',')===ids.join(',')));for(const viewport of f.viewports)rows.push(...await realm(f,viewport,'active'));rows.push(...await realm(f,f.inactiveViewport,'inactive'));render('CANDIDATE',rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render('FATAL',[row('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
