import {createHash} from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
import {existsSync,readFileSync,readdirSync,statSync} from 'node:fs';
import {extname,resolve} from 'node:path';
import {Script,createContext,runInContext} from 'node:vm';

const ROOT=resolve(new URL('../..',import.meta.url).pathname),QA=resolve(ROOT,'qa/phase-23-independent'),PACKAGE_ONLY=process.argv.includes('--package-only'),EXPECTED=['README.md','checksums.sha256','fixtures/contract.json','index.html','realm.html','realm.js','runner.js','verify.mjs'],rows=[];
const read=path=>readFileSync(resolve(ROOT,path)),text=path=>read(path).toString('utf8'),json=path=>JSON.parse(text(path)),sha=value=>createHash('sha256').update(value).digest('hex'),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),unique=values=>new Set(values).size===values.length,record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),git=args=>execFileSync('/usr/bin/git',args,{cwd:ROOT,encoding:'utf8',maxBuffer:128*1024*1024});
function filesBelow(directory,prefix=''){if(!existsSync(directory))return[];return readdirSync(directory).flatMap(name=>{const absolute=resolve(directory,name),path=prefix?`${prefix}/${name}`:name;return statSync(absolute).isDirectory()?filesBelow(absolute,path):[path]}).sort()}
function productionFiles(){const files=['index.html','.gitignore'];for(const root of ['src','assets','design/phase-23']){const absolute=resolve(ROOT,root);if(!existsSync(absolute))continue;for(const item of filesBelow(absolute,root))if(/\.(?:html|m?js|json|css|md|sha256|sha1)$/.test(item))files.push(item)}for(const item of ['scripts/build-phase23-private-assets.py','scripts/check-phase23-public-release.py'])if(existsRelative(item))files.push(item);return files.filter(existsRelative).sort()}
const existsRelative=path=>existsSync(resolve(ROOT,path)),f=json('qa/phase-23-independent/fixtures/contract.json'),realmSource=text('qa/phase-23-independent/realm.js'),runnerSource=text('qa/phase-23-independent/runner.js'),contract=text('docs/PHASE_23_INDEPENDENT_QA_CONTRACT.md');

async function generatedFailClosed(){
  let written='',loaderMessage=null,resolveWritten;const writtenPromise=new Promise(resolvePromise=>{resolveWritten=resolvePromise}),config={channel:'everstead-phase-23-independent-v1',nonce:'verify-p23-generated',viewport:f.viewports[0],fixtures:f,mode:'active'},loaderWindow={name:JSON.stringify(config)},loaderContext={window:loaderWindow,document:{open(){},write(value){written=String(value);resolveWritten()},close(){}},fetch:async()=>({ok:true,text:async()=>text('index.html')}),parent:{postMessage(value){loaderMessage=value;resolveWritten()}},console,setTimeout,clearTimeout};loaderWindow.window=loaderWindow;createContext(loaderContext);
  try{runInContext(realmSource,loaderContext,{filename:'qa/phase-23-independent/realm.js'});await Promise.race([writtenPromise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('loader generation timed out')),1000))]);if(loaderMessage)throw new Error(`loader posted before generation: ${JSON.stringify(loaderMessage)}`);const scripts=[...written.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(match=>match[1]),bootstrap=scripts.find(source=>source.includes('function installRuntime(config)')),suite=scripts.find(source=>source.includes('function runSuite()'));if(!bootstrap||!suite)throw new Error(`generated payload missing: bootstrap=${Boolean(bootstrap)} suite=${Boolean(suite)}`);new Script(bootstrap,{filename:'generated-p23-bootstrap.js'});const suiteScript=new Script(suite,{filename:'generated-p23-suite.js'});let resolvePosted;const postedPromise=new Promise(resolvePromise=>{resolvePosted=resolvePromise}),suiteWindow={__P23I_CONFIG__:config,__P23I_ERRORS__:[]},suiteContext={window:suiteWindow,parent:{postMessage:value=>resolvePosted(value)},console,setTimeout,clearTimeout};suiteWindow.window=suiteWindow;createContext(suiteContext);suiteScript.runInContext(suiteContext);const posted=await Promise.race([postedPromise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('generated suite did not fail closed')),1000))]);return{ok:posted.channel===config.channel&&posted.nonce===config.nonce&&posted.results?.length===1&&posted.results[0].id==='trusted-phase23-bridge-present-version'&&posted.results[0].pass===false&&posted.errors?.length===0,ids:posted.results?.map(item=>item.id),errors:posted.errors};
  }catch(error){return{ok:false,error:error.stack||error.message,loaderMessage,writtenBytes:written.length}}
}

record('predecessor-commit-reachable',git(['merge-base','--is-ancestor',f.predecessorCommit,'HEAD'])==='');
record('package-topology',same(filesBelow(QA),EXPECTED),filesBelow(QA));
const checksumRows=existsRelative('qa/phase-23-independent/checksums.sha256')?text('qa/phase-23-independent/checksums.sha256').trim().split('\n').filter(line=>line&&!line.startsWith('#')).map(line=>{const match=line.match(/^([0-9a-f]{64})  (.+)$/);return match?{expected:match[1],path:match[2]}:null}):[],checksumFailures=checksumRows.filter(item=>!item||!existsRelative(item.path)||sha(read(item.path))!==item.expected).map(item=>item?.path||'malformed');record('package-checksums',checksumRows.length===7&&checksumFailures.length===0,{count:checksumRows.length,failures:checksumFailures});
record('contract-and-result-documents',['docs/PHASE_23_INDEPENDENT_QA_CONTRACT.md','docs/PHASE_23_INDEPENDENT_QA_RESULT.md'].every(existsRelative));
record('contract-qa-only-private-release-boundary',['does not implement, emulate, repair, or weaken','local private candidate','does not authorize a merge, push, deployment, public release','rights-limited Companion artwork'].every(value=>contract.includes(value)));
record('contract-schema13-history-offline-exactly-once',['Schema 13 is a real migration boundary','exact pre-schema-13 checkpoint','authenticated migration receipt','never reinterpreted','never repriced','one migration, one checkpoint, and no duplicate reward'].every(value=>contract.includes(value)));
record('contract-private-art-and-no-fake-cutout',['private-assets/companions/<id>/portrait.webp','private-assets/companions/<id>/thumb.webp','1024×1536','320×480','original Everstead Companion crest','never present it as a transparent dialogue or walking cutout'].every(value=>contract.includes(value)));
record('contract-browser-accessibility-neutrality',['320×568','390×844','1024×768','130% copy','reduced motion','44×44','zero save writes','return focus','five-item navigation'].every(value=>contract.includes(value)));

const ids=f.roster.map(item=>item.id),hashes=f.roster.map(item=>item.sourceSha256),poolIds=f.stagePools.flatMap(item=>item.targetIds);record('fixture-exact-20-stable-order',f.contractVersion===1&&f.phase===23&&f.schemaVersion===13&&same(ids,['arcanine','dewgong','snorlax','dragonite','charizard','venusaur','blastoise','jolteon','machamp','meganium','feraligatr','miltank','donphan','lucario','boltund','stoutland','mabosstiff','zacian','lugia','suicune'])&&unique(ids));record('fixture-20-unique-source-hashes-and-2-to-3-masters',hashes.length===20&&unique(hashes)&&hashes.every(value=>/^[0-9a-f]{64}$/.test(value))&&f.assetPolicy.fullWidth*3===f.assetPolicy.fullHeight*2&&f.assetPolicy.thumbWidth*3===f.assetPolicy.thumbHeight*2);record('fixture-exact-base-table-aggregate-2200',f.aggregateBasePower===2200&&f.roster.reduce((sum,item)=>sum+item.basePower,0)===2200&&same(f.roster.map(item=>item.basePower),[115,100,115,125,125,115,115,100,100,100,115,100,100,100,100,100,100,125,125,125]));record('fixture-all-owned-no-gacha-private-fail-closed',Object.values(f.acquisition).every(value=>value===true||value===false)&&f.acquisition.allVisible===true&&f.acquisition.allOwned===true&&['summoning','pulls','acquisitionCurrency','duplicateConversion','gachaGate'].every(key=>f.acquisition[key]===false)&&f.assetPolicy.privateBuildOnly===true&&f.assetPolicy.publicReleaseAllowed===false&&f.assetPolicy.trackedRightsLimitedBinariesAllowed===false);record('fixture-exact-positional-map-defaults-and-history',same(f.migration.legacyMap,{bramble:'arcanine',cinderwing:'dewgong'})&&same(f.defaultCompanion,{owned:true,exp:0,level:1,rarity:1,shards:0,assignedFellowId:null})&&f.legacyHistoryExpected.campaignLastTargetId==='bramble'&&f.legacyHistoryExpected.towerLastTargetId==='cinderwing');record('fixture-ten-two-member-pools-exact-cover',f.stagePools.length===10&&f.stagePools.every((item,index)=>item.stageId===`companion-trail-${index+1}`&&item.targetIds.length===2)&&same(poolIds,ids)&&unique(poolIds));record('fixture-versioned-targeting-tutorial-invalid-matrices',typeof f.campaignPolicyId==='string'&&typeof f.towerPolicyId==='string'&&same(f.towerTargetOrder,ids)&&f.tutorialIds.length===8&&unique(f.tutorialIds)&&f.invalidMutationKinds.length===18&&unique(f.invalidMutationKinds));record('fixture-migration-offline-viewports',f.migration.id==='schema-12-to-13'&&f.migration.from===12&&f.migration.to===13&&f.migration.checkpointRequired===true&&f.migration.authenticatedReceiptRequired===true&&f.offlineAdvanceMs===f.offlineCapMs*2&&f.viewports.length===5&&[[320,568],[390,844],[1024,768]].every(([width,height])=>f.viewports.some(item=>item.width===width&&item.height===height))&&f.viewports.some(item=>item.copyScale===1.3)&&f.viewports.some(item=>item.reducedMotion));

const historicalPaths=['qa/phase-6','qa/phase-11d','qa/phase-11f','qa/phase-11g','qa/phase-12','qa/phase-12-independent','qa/phase-17-independent','qa/phase-17-runtime','qa/phase-20-21-independent','qa/phase-20-21-runtime','qa/phase-20-21-ui','qa/phase-22a-independent','qa/phase-22a-shell','qa/phase-22b-features','qa/phase-22b-independent','qa/phase-22c-facility-polish','qa/phase-22c-independent'],historicalDelta=git(['diff','--name-only',f.predecessorCommit,'--',...historicalPaths]).trim().split('\n').filter(Boolean);record('historical-inherited-gates-byte-frozen',historicalDelta.length===0,historicalDelta);
record('runner-real-candidate-isolated-fail-closed',realmSource.includes("fetch('../../index.html'")&&realmSource.includes('allowDestructive:true')&&realmSource.includes('isolatedStorage:true')&&realmSource.includes('__EVERSTEAD_PHASE_23_QA__')&&realmSource.includes('trusted-phase23-bridge-present-version')&&realmSource.includes('__P23I_RESOURCE_URLS__')&&realmSource.includes('PerformanceObserver')&&realmSource.includes('window.fetch=(input,init)')&&!realmSource.includes('fakeEngine'));
record('runner-migration-history-offline-concurrency',['migration-positional-progression-and-assignment-exact','migration-one-authenticated-receipt-and-checkpoint-lineage','migration-retry-exactly-once-byte-stable','interrupted-migration-recovers-one-authority','pre13-campaign-tower-history-frozen-not-reinterpreted','pending-offline-boundary-captured-no-repricing','two-client-migration-one-winner-one-checkpoint','phase23-invalid-mutation-matrix-fails-closed'].every(value=>realmSource.includes(value)));
record('runner-campaign-tower-all20-and-no-retroactive',['campaign-two-member-deterministic-rotation-covers-all-20','tower-versioned-deterministic-targeting-covers-all-20','retroactiveRewardApplications','duplicateRewardApplications','receiptApplications===1'].every(value=>realmSource.includes(value)));
record('runner-frozen-tower-receipts-survive-later-real-claims',['tower-clear-receipt-survives-later-real-companion-claim-reload','tower-idle-receipt-survives-later-real-companion-claim-reload','claimProgressReward','already-claimed','towerClaimReceiptCount===1','idleClaimReceiptCount===1','receiptStableAfterClaim','receiptStableAfterReload',"item.targetId==='snorlax'","item.targetId==='dragonite'",'towerClaimStateDelta','idleClaimStateDelta'].every(value=>realmSource.includes(value)));
record('runner-all20-real-profiles-lazy-fallback-focus',['actual-dom-fellowship-chrome-advertises-20-before-companion-open','initialCompanionUnselected','initialCompanionClosed','actual-dom-derived-exact-20-roster-and-counts','selectedCompanionTabs.length===1','actual-dom-thumbnails-only-before-profile','actual-dom-all-20-full-screen-background-profiles-unoccluded-fallback-focus-return','data-phase23-companion-card','data-phase23-companion-profile','data-phase23-companion-full-art','data-phase23-profile-close','fullScreenShell','expectedWidth','mobileEdges','artCoversStage','pseudoInert','crestZ>beforeZ','crestHitIndex===0','crestCenterReachable','afterInactive','document.activeElement===card'].every(value=>realmSource.includes(value)));
record('runner-touch-overflow-copy-motion-zero-write',['actual-dom-44px-touch-targets','actual-dom-no-horizontal-overflow','actual-dom-130-copy-and-reduced-motion-safe','visible-presentations-cleared-before-traversal','all-traversal-presentations-genuinely-dismissed','visual-traversal-zero-save-writes','visual-traversal-authoritative-state-neutral','visual-traversal-reward-neutral','authoritativeFingerprint','minimumTargetPx','scrollWidth','copyScale'].every(value=>realmSource.includes(value)));
record('runner-tutorial-and-inherited-regressions',['tutorial-optional-skip-logged-and-durable','tutorial-log-replay-save-and-reward-neutral','completed-legacy-tutorials-no-popup-cascade','inherited-phase6-companion-progression-survives','inherited-phase11d-11f-11g-rosters-player-and-assignment-survive','inherited-phase12-bridge-and-validation-survive','inherited-phase17-story-wayfarer-survives','inherited-phase20-22-facility-and-shell-survive'].every(value=>realmSource.includes(value)));
record('runner-five-active-one-inactive-console-native-storage',runnerSource.includes('for(const viewport of f.viewports)')&&runnerSource.includes("realm(f,f.inactiveViewport,'inactive')")&&realmSource.includes('inactive-no-private-companion-binary-requested-or-referenced')&&realmSource.includes('privateResourceEvidence')&&realmSource.includes("includes('private-assets/companions/')")&&realmSource.includes('inactive-companion-tab-user-reachable-and-selected')&&realmSource.includes('inactive-visible-presentations-cleared-before-traversal')&&realmSource.includes('slotsAfter===slotsBefore')&&realmSource.includes('zero-native-storage-accesses')&&realmSource.includes('zero-warning-error-console')&&realmSource.includes('inactive-zero-native-storage-accesses')&&realmSource.includes('inactive-zero-warning-error-console')&&runnerSource.includes('__EVERSTEAD_PHASE_23_INDEPENDENT_RESULT__'));
for(const file of ['runner.js','realm.js','verify.mjs']){const checked=spawnSync(process.execPath,['--check',`qa/phase-23-independent/${file}`],{cwd:ROOT,encoding:'utf8'});record(`syntax-${file}`,checked.status===0,checked.stderr.trim())}
const generated=await generatedFailClosed();record('runtime-generated-realm-fails-closed',generated.ok,generated);

if(!PACKAGE_ONLY){
  const files=productionFiles(),source=files.map(path=>text(path)).join('\n'),phase23Files=files.filter(path=>/phase[-_]?23|companion/i.test(path)||ids.some(id=>text(path).includes(`'${id}'`)||text(path).includes(`"${id}"`))),phase23Source=phase23Files.map(path=>text(path)).join('\n'),assetContract=existsRelative('design/phase-23/companion-assets.json')?json('design/phase-23/companion-assets.json'):null;record('candidate-phase23-production-surface-present',phase23Files.length>=1&&ids.every(id=>phase23Source.includes(id)),phase23Files);
  record('candidate-schema13-real-migration-and-bridge',source.includes('schema-12-to-13')&&source.includes('phase-23-independent-qa-v1')&&source.includes('__EVERSTEAD_PHASE_23_QA__')&&['resetFixture','reload','importFixture','advanceOffline','clearCampaign','clearTower','claimProgressReward','tutorial','probeInvalid','simulateConcurrent'].every(name=>phase23Source.includes(name)));
  record('candidate-exact-20-hashes-and-base-table',hashes.every(value=>phase23Source.includes(value))&&f.roster.every(item=>phase23Source.includes(item.id)&&phase23Source.includes(String(item.basePower))));
  record('candidate-private-rights-release-guard',assetContract?.rights?.distribution==='private-build-only'&&assetContract?.rights?.publicReleaseAllowed===false&&assetContract?.rights?.trackedPrivateBinariesAllowed===false&&assetContract?.runtime?.root===f.assetPolicy.runtimeRoot&&phase23Source.includes('check-phase23-public-release'));
  const tracked=git(['ls-files']).trim().split('\n').filter(Boolean),trackedRightsBinaries=tracked.filter(path=>/\.(?:png|webp)$/i.test(path)&&(path.startsWith(`${f.assetPolicy.runtimeRoot}/`)||ids.some(id=>new RegExp(`(?:^|/)${id}(?:/|[-_.])`,'i').test(path))));record('candidate-no-tracked-rights-limited-companion-binaries',trackedRightsBinaries.length===0,trackedRightsBinaries);record('candidate-private-runtime-root-ignored',text('.gitignore').split(/\r?\n/).some(line=>line.trim().replace(/^\//,'')===`${f.assetPolicy.runtimeRoot}/`),text('.gitignore'));
  record('candidate-versioned-stage-and-tower-policies',phase23Source.includes(f.campaignPolicyId)&&phase23Source.includes(f.towerPolicyId)&&f.stagePools.every(pool=>phase23Source.includes(pool.stageId)&&pool.targetIds.every(id=>phase23Source.includes(id))));
  const phase23AuthoritySource=phase23Files.filter(path=>/phase[-_]?23/i.test(path)&&/\.(?:m?js|json)$/.test(path)).map(path=>text(path)).join('\n');record('candidate-original-crest-fallback-no-two-frame-atlas-authority',phase23AuthoritySource.includes(f.assetPolicy.fallbackMode)&&!/(?:COMPANION_DEFS|companionDefinitions)[\s\S]{0,1200}bramble[\s\S]{0,400}cinderwing/.test(phase23AuthoritySource)&&!phase23AuthoritySource.includes("atlas('companion')")&&!phase23AuthoritySource.includes('assets/portraits/companions/atlas.webp'));
  record('candidate-dom-hook-contract',['data-phase23-companion-roster','data-phase23-companion-card','data-phase23-companion-count','data-phase23-companion-thumb','data-phase23-companion-profile','data-phase23-companion-full-art','data-phase23-profile-close','data-phase23-companion-target','data-phase23-target-policy'].every(value=>source.includes(value)));
  record('candidate-tutorial-contract-all-eight',f.tutorialIds.every(id=>phase23Source.includes(id))&&/skippable\s*:\s*true/.test(phase23Source)&&/replayable\s*:\s*true/.test(phase23Source)&&/rewardNeutral\s*:\s*true/.test(phase23Source));
  record('candidate-preserves-five-navigation-and-four-roster-tabs',source.includes("['village','oaths','fellows','adventure','more']")||source.includes("['village', 'oaths', 'fellows', 'adventure', 'more']"));
  const privateRoot=resolve(ROOT,f.assetPolicy.runtimeRoot),privateFiles=existsSync(privateRoot)?filesBelow(privateRoot):[],expectedPrivate=ids.flatMap(id=>[`${id}/${f.assetPolicy.fullFile}`,`${id}/${f.assetPolicy.thumbFile}`]),actualPrivate=privateFiles.filter(path=>/\.(?:webp)$/i.test(path));record('candidate-private-runtime-derivatives-installed',same([...actualPrivate].sort(),[...expectedPrivate].sort()),{expected:expectedPrivate.length,actual:actualPrivate.length,files:privateFiles});
  const phase23Scripts=phase23Files.filter(path=>/\.m?js$/.test(path));for(const path of phase23Scripts){const checked=spawnSync(process.execPath,['--check',path],{cwd:ROOT,encoding:'utf8'});record(`candidate-syntax-${path}`,checked.status===0,checked.stderr.trim())}
}

const passed=rows.filter(row=>row.pass).length,failed=rows.length-passed;for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` — ${row.detail}`:''}`);console.log(`RESULT ${passed} passed, ${failed} failed${PACKAGE_ONLY?' (package only)':''}`);process.exitCode=failed?1:0;
