import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {runSchemaCandidate} from '../phase-10c1/schema-probe.mjs';
import {runEngineProbe} from '../phase-10c2/engine-probe.mjs';

const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),BASE='ac7592348c1a11668822b0355ae86ab6db1b2688';
const source=readFileSync(resolve(ROOT,'index.html'),'utf8'),base=execFileSync('git',['show',`${BASE}:index.html`],{cwd:ROOT,encoding:'utf8',maxBuffer:32*1024*1024}),rows=[];
const add=(id,actual,detail='')=>rows.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)}),sha=value=>createHash('sha256').update(value).digest('hex'),lineContaining=needle=>{const line=source.split('\n').find(item=>item.includes(needle));if(!line)throw new Error(`Missing source line: ${needle}`);return line},between=(text,start,end)=>{const a=text.indexOf(start),b=text.indexOf(end,a);if(a<0||b<0)throw new Error(`Missing section ${start}`);return text.slice(a,b)};

const assets=[...source.matchAll(/data:image\/[^;]+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]),baseAssets=[...base.matchAll(/data:image\/[^;]+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]);
add('schema11-frozen',source.includes('CURRENT_SCHEMA_VERSION=11'));add('embedded-assets-byte-frozen',assets.length===5&&JSON.stringify(assets)===JSON.stringify(baseAssets),`${assets.length} · ${sha(assets.join('\n'))}`);
const frozenStart='/* Phase 10C-1 · schema-11 economy-profile authority and thirteen-slot persistence. */',baseFrozen=between(base,frozenStart,'const report=load();render();installQaBridge();'),candidateFrozen=between(source,frozenStart,'/* Phase 11A · daily-use clarity');add('phase10c-authority-byte-frozen',candidateFrozen===baseFrozen,`${candidateFrozen.length}/${baseFrozen.length}`);
add('phase11a-final-boundary',source.indexOf('/* Phase 11A · daily-use clarity')>source.indexOf('function phaseTenCThreeBuildingUpgradePreview')&&source.indexOf('/* Phase 11A · daily-use clarity')<source.lastIndexOf('const report=load();render();installQaBridge();'));

const diffLine=lineContaining('const DIFF=');add('dead-difficulty-bond-removed',!diffLine.includes('bond:')&&diffLine.includes("boost:.03")&&diffLine.includes("boost:.05")&&diffLine.includes("boost:.08")&&diffLine.includes('prosperity:2')&&diffLine.includes('prosperity:4')&&diffLine.includes('prosperity:7'),diffLine);add('oath-bond-three-preserved',source.includes('S.fellows[S.focusFellow].bond+=3')&&source.includes('+3 Bond ·'));

const durationContext={};vm.runInNewContext(lineContaining('function phaseElevenAOfflineDuration'),durationContext);add('offline-duration-copy',durationContext.phaseElevenAOfflineDuration(300000)==='5 minutes'&&durationContext.phaseElevenAOfflineDuration(3600000)==='1 hour'&&durationContext.phaseElevenAOfflineDuration(7200000)==='2 hours'&&durationContext.phaseElevenAOfflineDuration(7500000)==='2h 5m');
let previewCalls=0;const previewContext={PHASE_ELEVEN_A_OFFLINE_SUMMARY_MS:300000,runtimeNow:()=>0,S:{},phaseTenCTwoProfileActive:()=>true,offlineClaimPreview:at=>{previewCalls++;return{at,elapsed:at,total:77,lines:[1],segments:[2],pendingBefore:3,pendingAfter:80,opensSummary:false,nextLastGoldAt:at}}};vm.runInNewContext(lineContaining('const offlineClaimPreviewBeforePhaseElevenA'),previewContext);const low=previewContext.offlineClaimPreview(299999,previewContext.S),edge=previewContext.offlineClaimPreview(300000,previewContext.S);add('offline-threshold-boundary',low.opensSummary===false&&edge.opensSummary===true&&previewCalls===2,`${low.opensSummary}/${edge.opensSummary}/${previewCalls}`);const strip=value=>{const copy={...value};delete copy.opensSummary;return copy};add('offline-wrapper-changes-boolean-only',JSON.stringify(strip(low))===JSON.stringify({at:299999,elapsed:299999,total:77,lines:[1],segments:[2],pendingBefore:3,pendingAfter:80,nextLastGoldAt:299999})&&JSON.stringify(strip(edge))===JSON.stringify({at:300000,elapsed:300000,total:77,lines:[1],segments:[2],pendingBefore:3,pendingAfter:80,nextLastGoldAt:300000}));

const topbarContext={S:{pendingGold:2300,gifts:1,gold:50000,player:{rank:2},familyDrops:{pendingGifts:1,pendingShards:{a:1,b:0}}},fmt:value=>value===50000?'50.0K':value===2300?'2.3K':String(value),esc:value=>String(value),topbar:()=>''};vm.runInNewContext(lineContaining('topbar=function(){const pendingGold='),topbarContext);const topbar=topbarContext.topbar();add('topbar-resource-contract',topbar.includes('data-resource="gifts" aria-label="Gifts: 1"')&&topbar.includes('>Gift <b data-gifts>1</b>')&&topbar.includes('data-resource="gold" aria-label="Gold: 50.0K"')&&topbar.includes('>Gold <b data-gold>50.0K</b>')&&topbar.includes('Collect Village rewards: 2.3K Gold and 2 bonus rewards ready')&&topbar.includes('>+2.3K Gold · 2 bonus</button>')&&topbar.includes('Rank 2')&&!topbar.includes('✦'),topbar);
add('small-phone-header-contract',source.includes('@media(max-width:360px)')&&source.includes('.brand{display:none}')&&source.includes('.resources{width:100%;display:grid;grid-template-columns:minmax(0,1fr) auto auto auto;gap:3px}')&&source.includes('.collect-mini{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}'));

const relicContext={S:{relics:{r:{owned:false}},fellowCampaign:{clearedStageIds:[]}},relicCard:()=>'<p>Replay its source stage to acquire.</p>',fellowCampaignStage:()=>({name:'Village Toll'}),esc:String};vm.runInNewContext(lineContaining('const relicCardBeforePhaseElevenA'),relicContext);let relic=relicContext.relicCard({id:'r',stageId:'s'});const fresh=relic.includes('First clear Village Toll in Fellow Campaign to acquire.');relicContext.S.fellowCampaign.clearedStageIds=['s'];relic=relicContext.relicCard({id:'r',stageId:'s'});add('contextual-relic-card-copy',fresh&&relic.includes('Complete Village Toll in Fellow Campaign to acquire.')&&!relic.includes('Replay its source')&&!relic.includes('once more'),relic);
add('relic-stone-pluralization',source.includes("value===1?'':'s'")&&source.includes('+${phaseElevenARelicStoneCopy(outcome.totalRelicStones)}'));
add('power-label-selectors',['data-village-fellow-economy-power','data-combat-fellow-roster-power="campaign"','data-combat-fellow-roster-power="expedition"','Village Fellow Economy Power','Combat Fellow Roster Power'].every(needle=>source.includes(needle)));

const oathLine=lineContaining('openOathForm=function(id){const o=id?');add('new-oath-types-contract',oathLine.includes("types=[['daily','Daily'],['habit','Habit'],['weekly','Weekly'],['monthly','Monthly']]")&&!oathLine.includes("types=['daily','habit','weekly','monthly','quest']"));add('legacy-quest-conversion-contract',oathLine.includes('Quest (legacy — choose a schedule)')&&oathLine.includes('select name="type" required')&&oathLine.includes('value="" selected disabled')&&oathLine.includes('saving converts this Oath.'));
add('legacy-quest-schema-compatible',source.includes("['daily','habit','weekly','monthly','quest'].includes(o.type)")&&source.includes("['daily','habit','weekly','monthly','quest'].includes(o.type)"));
add('readme-current-phase',readFileSync(resolve(ROOT,'README.md'),'utf8').includes('runnable schema-11 build through Phase 10C')&&readFileSync(resolve(ROOT,'README.md'),'utf8').includes('Phase 11A clarity contract'));

const schema=await runSchemaCandidate(),schemaFailures=schema.rows.filter(row=>!row.pass);for(const row of schema.rows)add(`schema-${row.id}`,row.pass,row.detail);add('schema-probe-47-of-47',schema.rows.length===47&&schemaFailures.length===0,JSON.stringify(schemaFailures));
const engine=await runEngineProbe(),engineFailures=engine.rows.filter(row=>!row.pass);for(const row of engine.rows)add(`engine-${row.id}`,row.pass,row.detail);add('engine-probe-100-of-100',engine.rows.length===100&&engineFailures.length===0,JSON.stringify(engineFailures));add('engine-native-storage-zero',engine.evidence.nativeStorageCalls===0,JSON.stringify(engine.evidence));

export async function runPhaseElevenAProbe(){return{rows,evidence:{total:rows.length,passed:rows.filter(row=>row.pass).length,failed:rows.filter(row=>!row.pass).length,artifact:{sha256:sha(Buffer.from(source)),byteLength:Buffer.byteLength(source)},assetAggregateSha256:sha(assets.join('\n')),schemaRows:schema.rows.length,engineRows:engine.rows.length}}}
if(fileURLToPath(import.meta.url)===resolve(process.argv[1])){const result=await runPhaseElevenAProbe();for(const row of result.rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` · ${row.detail}`:''}`);console.log(`Phase 11A probe: ${result.evidence.passed}/${result.evidence.total}`);if(result.evidence.failed)process.exitCode=1}
