(() => {
  'use strict';
  const CHANNEL='everstead-phase-11a';
  const json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config,fixtureRaw){
    const slots=new Map([[config.keys.active,fixtureRaw]]),nativeSetTimeout=window.setTimeout.bind(window),nativeClearTimeout=window.clearTimeout.bind(window),nativeStorageAccesses=[],errors=[];let saveIndex=0,transactionIndex=0,nativeStorageInstrumented=false;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    window.__PHASE_11A_CONFIG__=config;window.__PHASE_11A_SLOTS__=slots;window.__PHASE_11A_ERRORS__=errors;window.__PHASE_11A_NATIVE_STORAGE_ACCESSES__=nativeStorageAccesses;window.__PHASE_11A_NATIVE_STORAGE_INSTRUMENTED__=nativeStorageInstrumented;
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>slots.set(String(key),String(value)),removeItem:key=>slots.delete(String(key))};
    window.__EVERSTEAD_RUNTIME__={storage:memoryStorage,clock:{now:()=>config.now,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.5,confirm:()=>true,ids:{save:()=>`save-p11a-${++saveIndex}`,transaction:()=>`tx-p11a-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
  }

  function runSuite(){
    const config=window.__PHASE_11A_CONFIG__,slots=window.__PHASE_11A_SLOTS__,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)}),bridge=()=>window.__EVERSTEAD_QA__,snapshot=()=>bridge().snapshot().state,send=()=>parent.postMessage({channel:'everstead-phase-11a',nonce:config.nonce,results,errors:window.__PHASE_11A_ERRORS__.slice(),nativeStorageAccesses:window.__PHASE_11A_NATIVE_STORAGE_ACCESSES__.slice()},'*');
    const navigate=async view=>{const result=bridge().act('navigate',{view});if(!result.ok)throw new Error(`Navigation to ${view} failed: ${result.error}`);await wait(15)};
    const roster=async tab=>{const result=bridge().act('roster',{tab});if(!result.ok)throw new Error(`Roster ${tab} failed: ${result.error}`);await wait(15)};
    const compact=value=>value>=1e6?(value/1e6).toFixed(value>=1e7?1:2)+'M':value>=1e3?(value/1e3).toFixed(value>=1e5?0:1)+'K':String(Math.floor(value));
    const close=async()=>{document.querySelector('[data-modal-close]')?.click();await wait(15)};
    const text=node=>node?.textContent.replace(/\s+/g,' ').trim()||'';
    const rect=node=>node?.getBoundingClientRect();

    (async()=>{
      await wait(700);const qa=bridge();add('bridge-present',Boolean(qa));add('viewport-exact',innerWidth===config.viewport.width&&innerHeight===config.viewport.height,`${innerWidth}x${innerHeight}`);add('schema11-runtime',snapshot().schemaVersion===11,snapshot().schemaVersion);add('thirteen-protected-slots',Object.keys(config.keys).length===13,Object.keys(config.keys).length);add('native-storage-instrumented',window.__PHASE_11A_NATIVE_STORAGE_INSTRUMENTED__===true);

      const modal=document.querySelector('.modal'),expectedModal=config.viewport.offlineModal,elapsed=config.viewport.offlineElapsed,stateAtBoot=snapshot(),collect=document.querySelector('.collect-mini'),gift=document.querySelector('[data-resource="gifts"]'),gold=document.querySelector('[data-resource="gold"]'),brand=document.querySelector('.brand'),resources=document.querySelector('.resources'),brandRect=rect(brand),resourcesRect=rect(resources),layoutClear=Boolean(brandRect&&resourcesRect&&brandRect.right<=resourcesRect.left+1&&resourcesRect.right<=innerWidth+1);
      add('offline-five-minute-boundary',Boolean(modal)===expectedModal,`${elapsed}ms · modal ${Boolean(modal)}`);add('offline-pending-preserved',stateAtBoot.pendingGold>0&&stateAtBoot.gold===config.fixture.gold,JSON.stringify({pendingGold:stateAtBoot.pendingGold,gold:stateAtBoot.gold}));
      if(expectedModal){const expectedDuration=elapsed===300000?'5 minutes':'2 hours';add('offline-readable-duration',text(modal).includes(`${expectedDuration} of Village production`)&&!text(modal).includes('0.0 hours'),text(modal))}else add('offline-readable-duration',true,'summary intentionally suppressed');
      add('topbar-resource-names',gift?.getAttribute('aria-label')===`Gifts: ${compact(stateAtBoot.gifts)}`&&gold?.getAttribute('aria-label')===`Gold: ${compact(stateAtBoot.gold)}`&&/^Gift\s/.test(text(gift))&&/^Gold\s/.test(text(gold)),JSON.stringify({gift:text(gift),giftAria:gift?.getAttribute('aria-label'),gold:text(gold),goldAria:gold?.getAttribute('aria-label')}));
      const collectAccessible=collect?.getAttribute('aria-label')||'',collectVisible=text(collect),bonusCopyMatches=!collectAccessible.includes('bonus')||collectVisible.includes('bonus');add('topbar-collect-name',collectAccessible.startsWith('Collect Village rewards:')&&collectAccessible.endsWith('ready')&&collectAccessible.includes('Gold')&&collectVisible.includes('Gold')&&bonusCopyMatches&&!collectVisible.includes('✦'),JSON.stringify({visible:collectVisible,accessible:collectAccessible}));add('topbar-layout-clear',layoutClear,JSON.stringify({brand:brandRect&&{left:brandRect.left,right:brandRect.right},resources:resourcesRect&&{left:resourcesRect.left,right:resourcesRect.right},width:innerWidth}));
      if(modal)await close();

      await navigate('fellows');await roster('fellows');const economyNode=document.querySelector('[data-village-fellow-economy-power]'),summary=document.querySelector('[data-village-roster-multiplier="fellow"]'),diagnostics=qa.diagnostics({}).diagnostics,economyPower=diagnostics.buildingRateComponents.training.fellowRosterPower,combatPower=diagnostics.totalFellowRosterPower;
      add('village-economy-power-copy',Boolean(economyNode)&&text(summary).includes('Village Fellow Economy Power')&&text(summary).includes('Bond, Family Bonds, and Companion transfer affect combat only.'),text(summary));add('economy-combat-power-disjoint',Number.isSafeInteger(economyPower)&&Number.isSafeInteger(combatPower)&&economyPower!==combatPower,`${economyPower}/${combatPower}`);
      await navigate('adventure');const campaignPower=document.querySelector('[data-combat-fellow-roster-power="campaign"]');add('campaign-combat-power-copy',Boolean(campaignPower)&&text(campaignPower.parentElement).includes('Combat Fellow Roster Power'),text(campaignPower?.parentElement));

      await navigate('fellows');document.querySelector('[data-roster="relics"]')?.click();await wait(20);const locked=[...document.querySelectorAll('[data-relic-card].locked')],lockedText=locked.map(text),clearedCount=snapshot().fellowCampaign.clearedStageIds.length;add('contextual-relic-guidance',locked.length>0&&!lockedText.some(value=>value.includes('Replay its source'))&&!lockedText.some(value=>value.includes('once more'))&&lockedText.some(value=>value.includes('Complete ')&&value.includes(' in Fellow Campaign to acquire.'))&&lockedText.some(value=>value.includes('First clear')),JSON.stringify({clearedCount,lockedText}));

      await navigate('oaths');const legacy=document.querySelector(`[data-edit-oath="${config.fixture.questId}"]`),legacyRawBefore=slots.get(config.keys.active);legacy?.focus();legacy?.click();await wait(20);const legacyDialog=document.querySelector('.modal'),legacyType=legacyDialog?.querySelector('select[name="type"]'),legacyForm=legacyDialog?.querySelector('#oath-form');add('legacy-quest-required-conversion',Boolean(legacyDialog)&&legacyType?.required&&legacyType.value===''&&legacyType.options[0]?.disabled&&legacyType.options[0]?.textContent.includes('Quest (legacy')&&!legacyForm.checkValidity()&&text(legacyDialog).includes('saving converts this Oath'),JSON.stringify({value:legacyType?.value,options:legacyType&&[...legacyType.options].map(option=>option.textContent),valid:legacyForm?.checkValidity()}));document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));await wait(20);add('legacy-quest-cancel-zero-write-focus',!document.querySelector('[data-overlay]')&&slots.get(config.keys.active)===legacyRawBefore&&document.activeElement===legacy,JSON.stringify({rawSame:slots.get(config.keys.active)===legacyRawBefore,focus:document.activeElement?.getAttribute('data-edit-oath')}));

      const addButton=document.querySelector('[data-act="add-oath"]'),newRawBefore=slots.get(config.keys.active);addButton.focus();addButton.click();await wait(20);const newDialog=document.querySelector('.modal'),newType=newDialog?.querySelector('select[name="type"]'),values=newType?[...newType.options].map(option=>option.value):[];add('new-oath-supported-types-only',JSON.stringify(values)===JSON.stringify(['daily','habit','weekly','monthly'])&&!text(newDialog).includes('Quest (legacy'),JSON.stringify(values));document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));await wait(20);add('new-oath-cancel-zero-write-focus',!document.querySelector('[data-overlay]')&&slots.get(config.keys.active)===newRawBefore&&document.activeElement===addButton,JSON.stringify({rawSame:slots.get(config.keys.active)===newRawBefore,focus:document.activeElement?.getAttribute('data-act')}));

      add('no-horizontal-overflow',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);add('zero-native-storage-accesses',window.__PHASE_11A_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_11A_NATIVE_STORAGE_ACCESSES__.join(','));add('zero-warning-error-console',window.__PHASE_11A_ERRORS__.length===0,window.__PHASE_11A_ERRORS__.join('\n'));send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const [appResponse,fixtureResponse]=await Promise.all([fetch('../../index.html',{cache:'no-store'}),fetch(config.fixture.path,{cache:'no-store'})]);if(!appResponse.ok)throw new Error(`index.html: HTTP ${appResponse.status}`);if(!fixtureResponse.ok)throw new Error(`fixture: HTTP ${fixtureResponse.status}`);const source=await appResponse.text(),fixtureRaw=await fixtureResponse.text(),firstScript=source.indexOf('<script>');if(firstScript<0)throw new Error('Production script is missing');const bootstrap=`<script>(${installRuntime.toString()})(${json(config)},${json(fixtureRaw)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`,instrumented=source.slice(0,firstScript)+bootstrap+source.slice(firstScript).replace('</body>',suite+'</body>');document.open();document.write(instrumented);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
