import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const read=file=>fs.readFileSync(path.join(ROOT,file),'utf8');
const clone=value=>JSON.parse(JSON.stringify(value));
const rows=[];
const check=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail});
const same=(left,right)=>JSON.stringify(left)===JSON.stringify(right);

const attrs=new Map();
const context={console,document:{documentElement:{getAttribute:name=>attrs.get(name)??null,setAttribute:(name,value)=>attrs.set(name,String(value))},activeElement:null,querySelector:()=>null,querySelectorAll:()=>[]},setTimeout:callback=>{callback();return 1},clearTimeout:()=>{}};
context.globalThis=context;
vm.createContext(context);
vm.runInContext(read('src/phase18-19-facilities.js'),context,{filename:'src/phase18-19-facilities.js'});
vm.runInContext(read('src/phase18-19-runtime.js'),context,{filename:'src/phase18-19-runtime.js'});
const definitions=context.EVERSTEAD_PHASE_18_19;
const factory=context.EVERSTEAD_PHASE_18_19_RUNTIME_FACTORY;

let clock=200000000,mutations=0,renders=0,runtime=null,privateAllowed=true,writes=0,raw='';
const familyIds=['scarlet-witch','yennefer','shadowheart','aerith','ahsoka','hermione'];
const facilityIds=['facility.apothecary','facility.schoolhouse'];
const row=()=>({nextOrdinal:0,claimedOrdinalRanges:[],pendingById:{}});
const baseState=()=>({saveMeta:{saveId:'save-phase1819-focused',revision:1,updatedAt:clock,source:'fresh'},gold:100000,prosperity:0,gifts:0,relicStones:0,buildings:Object.fromEntries(['command-center','archives','training-grounds','hearth'].map((id,index)=>[id,{level:index+1}])),family:Object.fromEntries(familyIds.map(id=>[id,{intimacy:50,assignedBuildingId:null}])),fellows:{},companions:{},storyV1:{completedSceneIds:[]},facilityProgress:{discoveredIds:[],unlockedIds:[]},phase15FacilityFoundation:{capabilityIds:[],facilitiesById:Object.fromEntries(facilityIds.map(id=>[id,row()])),pendingOffers:{},claimArchive:{nextSequence:0,recentReceipts:[],archiveCheckpoint:{throughSequence:0}}}});
let state=baseState();
const buildingDefs=[{id:'command-center',base:120},{id:'archives',base:180},{id:'training-grounds',base:240},{id:'hearth',base:300}];
const safeAdd=(left,right,label)=>{const result=left+right;if(!Number.isSafeInteger(result)||result<0)throw new Error(`${label} overflow`);return result};
const resources=value=>({gold:value.gold,prosperity:value.prosperity,gifts:value.gifts,relicStones:value.relicStones});
const applyRewards=(value,rewards)=>{for(const reward of rewards){if(!['gold','prosperity','gifts','relicStones'].includes(reward.kind))throw new Error('unsupported reward');value[reward.kind]=safeAdd(value[reward.kind],reward.amount,reward.kind)}};
const mutate=(mutator,source,options={})=>{const before=state,beforeRaw=raw,draft=clone(state),at=options.capturedNow??clock;state=draft;try{const value=mutator(state,at);state.saveMeta.revision=safeAdd(state.saveMeta.revision,1,'revision');state.saveMeta.updatedAt=Math.max(state.saveMeta.updatedAt,at);state.saveMeta.source=source;const valid=runtime?runtime.validate(state,baseValidate):{ok:true,errors:[]};if(!valid.ok)throw new Error(valid.errors.join(','));mutations++;writes++;raw=JSON.stringify(state);return{ok:true,value}}catch(error){state=before;raw=beforeRaw;return{ok:false,error}}};
const passiveBaseline=at=>({capturedAt:at,offlineCapMs:86400000,goldCurrencyId:'currency.gold',oathMultiplierPolicyId:'economy.oath-multiplier.v1',buildingSemantics:buildingDefs.map(definition=>({facilityId:`facility.${definition.id}`,baseGoldPerHour:definition.base,level:state.buildings[definition.id].level,familyAssignmentId:null,familyAssignmentMultiplier:1,effectiveOathBoost:0,effectiveGoldPerHour:definition.base*Math.pow(1.22,state.buildings[definition.id].level-1),formulaOrder:['base','levelMultiplier','familyAssignmentMultiplier','fellowRosterMultiplier','companionRosterMultiplier','overallDayMultiplier','oathMultiplier']}))});

const identity=value=>definitions.identity('focused-canonical',state.saveMeta.saveId,value);
const claimed=(ranges,ordinal)=>ranges.some(([start,end])=>ordinal>=start&&ordinal<=end);
const addClaimed=(ranges,ordinal)=>[...ranges,[ordinal,ordinal]].sort((a,b)=>a[0]-b[0]);
const canonicalOffer=(value,input)=>{const offer={id:input.id,sourceType:'opportunity.facility.activity',sourceId:input.sourceId,offeredAt:input.offeredAt,rewards:clone(input.rewards),identity:''};offer.identity=definitions.identity('focused-offer',value.saveMeta.saveId,[offer.id,offer.sourceType,offer.sourceId,offer.offeredAt,JSON.stringify(offer.rewards)]);return offer};
const validOffer=(value,offer)=>Boolean(offer)&&same(offer,canonicalOffer(value,offer));
const createFacilityOffer=(value,input)=>{const store=value.phase15FacilityFoundation,row=store.facilitiesById[input.facilityId],domainOrdinal=++row.nextOrdinal,offer=canonicalOffer(value,input);if(store.pendingOffers[offer.id]||claimed(row.claimedOrdinalRanges,domainOrdinal))throw new Error('duplicate');store.pendingOffers[offer.id]=offer;return{offer,domainOrdinal}};
const receiptFor=(value,offer,plan,at)=>{const sequence=++value.phase15FacilityFoundation.claimArchive.nextSequence,receipt={envelopeVersion:2,id:`reward.receipt.v2.${offer.id.slice('reward.offer.'.length)}.${sequence}`,offerId:offer.id,sourceType:offer.sourceType,sourceId:offer.sourceId,facilityId:plan.facilityId,domainOrdinal:plan.domainOrdinal,definitionVersion:1,rewardPolicyVersion:1,claimedAt:at,sequence,pendingIdentity:offer.identity,rewards:clone(offer.rewards),identity:''};receipt.identity=definitions.identity('focused-receipt',value.saveMeta.saveId,[JSON.stringify({...receipt,identity:''})]);return receipt};
const finalizeFacilityClaim=(value,pending,plan,at,fault=null)=>{const store=value.phase15FacilityFoundation,row=store.facilitiesById[plan.facilityId],offer=store.pendingOffers[plan.id];if(!offer||claimed(row.claimedOrdinalRanges,plan.domainOrdinal))throw new Error('stale');const receipt=receiptFor(value,offer,plan,at);row.claimedOrdinalRanges=addClaimed(row.claimedOrdinalRanges,plan.domainOrdinal);if(fault==='range')throw new Error('range');delete store.pendingOffers[plan.id];if(fault==='delete')throw new Error('delete');store.claimArchive.recentReceipts.push(receipt);if(store.claimArchive.recentReceipts.length>512){store.claimArchive.recentReceipts.splice(0,128);store.claimArchive.archiveCheckpoint.throughSequence+=128}if(fault==='archive')throw new Error('archive');return receipt};
const committedContentIds=value=>{const ids=[...value.storyV1.completedSceneIds];for(const [facilityId,opening,capability,discovery] of [['facility.apothecary','facility.apothecary.possibility-case','capability.apothecary-cases.v1','story.book1.chapter2.records-in-rain'],['facility.schoolhouse','facility.schoolhouse.first-mentor-lesson','capability.schoolhouse-lessons.v1','story.book1.chapter3.river-accord.resolution']])if(ids.includes(discovery)&&value.facilityProgress.discoveredIds.includes(facilityId)&&value.facilityProgress.unlockedIds.includes(facilityId)&&value.phase15FacilityFoundation.capabilityIds.includes(capability))ids.push(opening);return[...new Set(ids)]};
const projectPredecessor=(value,ids)=>{const out=clone(value);for(const id of ids)delete out.phase15FacilityFoundation.pendingOffers[id];delete out.phase1819;return out};
const validateSharedClaimAuthority=(value,plans)=>{const store=value.phase15FacilityFoundation,ids=new Set(plans.map(item=>item.id)),owned=Object.values(store.pendingOffers).filter(item=>['activity.apothecary-cases','activity.school-lessons'].includes(item.sourceId)),errors=[];if(owned.length!==plans.length||owned.some(item=>!ids.has(item.id)))errors.push('orphan-offer');for(const plan of plans){const row=store.facilitiesById[plan.facilityId];if(claimed(row.claimedOrdinalRanges,plan.domainOrdinal)||Object.values(row.pendingById).some(item=>item.opportunity?.sequence===plan.domainOrdinal))errors.push('pending-ordinal-replayed')}return{ok:!errors.length,errors}};
const graduationTriggerReceiptExists=(value,snapshot)=>{const proof=snapshot?.triggerReceipt,row=value.phase15FacilityFoundation.facilitiesById['facility.schoolhouse'],recent=value.phase15FacilityFoundation.claimArchive.recentReceipts.find(item=>item.id===proof?.id);return Boolean(proof&&proof.id===snapshot.triggerReceiptId&&proof.identity===snapshot.triggerReceiptIdentity&&proof.offerId===snapshot.triggerOfferId&&proof.domainOrdinal===snapshot.triggerDomainOrdinal&&(recent?same(recent,proof):claimed(row.claimedOrdinalRanges,proof.domainOrdinal)&&proof.sequence<=value.phase15FacilityFoundation.claimArchive.archiveCheckpoint.throughSequence))};
const qaCreateGraduationTriggerReceipt=(value,at)=>{const created=createFacilityOffer(value,{id:`reward.offer.facility.schoolhouse.lesson.qa-trigger.${value.phase15FacilityFoundation.claimArchive.nextSequence+1}.v1`,sourceId:'activity.school-lessons',rewards:[{kind:'gold',targetId:null,amount:1}],offeredAt:at,facilityId:'facility.schoolhouse'});return finalizeFacilityClaim(value,created.offer,{id:created.offer.id,offerIdentity:created.offer.identity,sourceId:created.offer.sourceId,facilityId:'facility.schoolhouse',domainOrdinal:created.domainOrdinal,definitionVersion:1,rewardPolicyVersion:1},at)};
const qaSeedArchive=(value,count,at)=>{const store=value.phase15FacilityFoundation;for(let i=1;i<=count;i++){const offer=canonicalOffer(value,{id:`reward.offer.facility.archive-seed.${i}`,sourceId:'activity.apothecary-cases',offeredAt:at,rewards:[{kind:'gold',targetId:null,amount:1}]}),plan={facilityId:'facility.apothecary',domainOrdinal:1000+i},receipt=receiptFor(value,offer,plan,at);store.claimArchive.recentReceipts.push(receipt)}store.facilitiesById['facility.apothecary'].nextOrdinal=1000+count;store.facilitiesById['facility.apothecary'].claimedOrdinalRanges=[[1001,1000+count]]};
const requestFacilityIntroduction=facilityId=>({ok:true,facilityId,introduction:true,writes:0});
const baseValidate=value=>{const archive=value.phase15FacilityFoundation?.claimArchive,errors=[];if(!archive||archive.nextSequence!==archive.archiveCheckpoint.throughSequence+archive.recentReceipts.length||archive.recentReceipts.some((item,index)=>item.sequence!==archive.archiveCheckpoint.throughSequence+index+1))errors.push('phase15.claimArchive');return{ok:!errors.length,errors}};

runtime=factory.createIntegration({clone,getState:()=>state,mutate,privateReleaseAllowed:()=>privateAllowed,qaAuthorized:()=>true,phase17Ready:()=>Boolean(state.storyV1),buildings:buildingDefs,levelMultiplier:1.22,safeAdd,applyRewards,error:result=>String(result?.error?.message||'failed'),toast:()=>{},resources,joinedFellows:()=>['rook','daredevil'],roster:(_state,joined)=>({playerCharacterId:'player.wayfarer',joinedFellowIds:[...joined],fellowIds:['fellow.rook','fellow.daredevil'],familyIds:familyIds.map(id=>`family.${id}`),companionIds:[],fellowAssignmentIds:[],familyAssignmentIds:[],companionAssignmentIds:[],shardOwnerIds:[]}),passiveBaseline,showModal:()=>{},closeModal:()=>{},defer:callback=>callback(),now:()=>clock,render:()=>{renders++},committedContentIds,contentEventEligible:(value,id)=>committedContentIds(value).includes(id),requestFacilityIntroduction,createFacilityOffer,pendingFacilityOffer:(value,id)=>value.phase15FacilityFoundation.pendingOffers[id]||null,projectPredecessor,finalizeFacilityClaim,graduationTriggerReceiptExists,validateSharedClaimAuthority,validateCanonicalOffer:validOffer,facilityOfferClaimed:(value,id)=>value.phase15FacilityFoundation.claimArchive.recentReceipts.some(item=>item.offerId===id),claimArchive:value=>clone(value.phase15FacilityFoundation.claimArchive),activeRaw:()=>raw,writeCount:()=>writes,qaCreateGraduationTriggerReceipt,qaSeedArchive,qaCorruptArchive:value=>value.phase15FacilityFoundation.claimArchive.nextSequence++,predecessorFacilityRow:(value,id)=>value.phase15FacilityFoundation.facilitiesById[id],resetBase:()=>{state=baseState();raw=JSON.stringify(state)},validate:value=>runtime.validate(value??state,baseValidate)});
const commitDiscovery=(contentId,facilityId)=>{state.storyV1.completedSceneIds.push(contentId);state.facilityProgress.discoveredIds.push(facilityId)};
const commitOpening=(facilityId,capabilityId,contentId,resolution='watched')=>mutate((draft,now)=>{draft.phase15FacilityFoundation.capabilityIds.push(capabilityId);draft.facilityProgress.unlockedIds.push(facilityId);runtime.commitFacilityIntroductionInState(draft,contentId,resolution,now)},'focused-phase17-opening');

check('factory-and-approved-definitions',Boolean(factory&&definitions)&&definitions.policy.status==='approved-private-release'&&definitions.policy.authoritative===true&&definitions.policy.productionEnabled===true);
check('activation-private-and-save-bound',runtime.activate()===true&&state.phase1819.publicRelease===false&&state.phase1819.policyMode==='approved'&&runtime.validate(state,()=>({ok:true,errors:[]})).ok);
check('story-gated-at-activation',state.phase1819.apothecary.unlocked===false&&state.phase1819.schoolhouse.unlocked===false&&runtime.openFacility('facility.apothecary').ok===false);
commitDiscovery('story.book1.chapter2.records-in-rain','facility.apothecary');
check('apothecary-discovery-precedes-opening',runtime.contentEvent('story.book1.chapter2.records-in-rain').ok&&state.phase1819.apothecary.discovered===true&&state.phase1819.apothecary.unlocked===false&&runtime.openFacility('facility.apothecary').introduction===true);
const apothecaryIntroduction=runtime.openFacility('facility.apothecary'),apothecaryOpening=commitOpening('facility.apothecary','capability.apothecary-cases.v1','facility.apothecary.possibility-case');
check('apothecary-story-unlock',apothecaryOpening.ok&&state.phase1819.apothecary.unlocked&&same(state.phase1819.apothecary.pendingNamedPatientIds,['apothecary.patient.named.rook'])&&state.phase1819.tutorials.facilityIntroductionResolutionsByContentId['facility.apothecary.possibility-case']==='watched');
check('apothecary-explicit-introduction-before-opening',apothecaryIntroduction.ok&&apothecaryIntroduction.introduction===true);
const firstTutorialVisit=runtime.openFacility('facility.apothecary');runtime.closeFacility();
check('contextual-tutorial-delivers-once-without-blocking',firstTutorialVisit.ok&&firstTutorialVisit.tutorialId==='tutorial.facility.board.discover-hotspots'&&state.phase1819.tutorials.presentedSegmentKeys.includes('tutorial.facility.board.discover-hotspots:facility-first-discovered')&&state.phase1819.tutorials.completedIds.includes('tutorial.facility.board.discover-hotspots'));
const openingApothecary=runtime.derive().apothecary;
check('apothecary-mastery-story-selection-gates',same(openingApothecary.availableCaseIds,['apothecary.case.dustbloom-irritation'])&&same(openingApothecary.availableRemedyIds,['apothecary.remedy.soothing-draught','apothecary.remedy.rest-and-water']));

clock+=3600000;
const apSettle=runtime.settle('facility.apothecary',clock,{renderAfter:false}),apCase=runtime.derive().apothecary.cases[0];
check('approved-apothecary-cadence-and-named-schedule',apSettle.ok&&apSettle.createdCount===1&&apCase.patientId==='apothecary.patient.named.rook'&&apCase.expiresAt===null&&state.phase1819.tutorials.pendingSegmentKeys.includes('tutorial.facility.opportunities.banking:facility-first-opportunity-ready'));
const livePatientRaw=raw,livePatientRevision=state.saveMeta.revision,livePatientWrites=writes,livePatientOffline=runtime.settleOffline(clock),livePatientReconcile=runtime.reconcileCommittedTruth();
check('live-named-patient-reload-and-same-clock-noop',livePatientOffline.ok&&livePatientOffline.writes===0&&livePatientReconcile.ok&&livePatientReconcile.writes===0&&writes===livePatientWrites&&state.saveMeta.revision===livePatientRevision&&raw===livePatientRaw&&!state.phase1819.apothecary.pendingNamedPatientIds.includes('apothecary.patient.named.rook')&&Object.values(state.phase1819.apothecary.cases).filter(item=>item.patientId==='apothecary.patient.named.rook').length===1);
const capturedApothecaryBand=definitions.rewardTable.bands.find(item=>item.id===apCase.rewardBandId),capturedSupportiveGold=capturedApothecaryBand.apothecaryGoldByOutcomeBandId['apothecary.outcome.supportive'];
mutate(draft=>{draft.buildings['command-center'].level=52},'focused-building-upgrade-after-generation');
runtime.beginApothecary(apCase.id,apCase.identity);
const engaged=runtime.derive().apothecary.cases[0],wrong=engaged.diagnosisOptionIds.find(id=>id!==engaged.preciseDiagnosisId);
runtime.chooseDiagnosis(engaged.id,engaged.identity,wrong);runtime.chooseRemedy(engaged.id,engaged.identity,engaged.preciseRemedyIds[0]);
const beforeRecheck=resources(state),recheck=runtime.resolveApothecary(engaged.id,engaged.identity);
check('recheck-is-nonterminal-and-rewardless',recheck.ok&&recheck.outcomeId==='apothecary.outcome.recheck'&&runtime.derive().apothecary.cases[0].status==='engaged'&&runtime.derive().claims.pendingOffers.length===0&&same(resources(state),beforeRecheck));
runtime.chooseDiagnosis(engaged.id,engaged.identity,engaged.preciseDiagnosisId);runtime.chooseRemedy(engaged.id,engaged.identity,'apothecary.remedy.rest-and-water');
const beforeResolve=resources(state),resolved=runtime.resolveApothecary(engaged.id,engaged.identity),caseOffer=runtime.derive().claims.pendingOffers[0];
check('apothecary-resolution-captures-no-payment',resolved.ok&&resolved.outcomeId==='apothecary.outcome.supportive'&&same(resources(state),beforeResolve)&&Object.keys(state.phase15FacilityFoundation.pendingOffers[caseOffer.id]).sort().join(',')==='id,identity,offeredAt,rewards,sourceId,sourceType'&&caseOffer.rewards[0].amount===capturedSupportiveGold&&caseOffer.localSnapshot.rewardBandId===apCase.rewardBandId);
const beforeClaimGold=state.gold,caseClaim=runtime.claim(caseOffer.id,caseOffer.identity,{present:false}),afterCaseRevision=state.saveMeta.revision,caseRepeat=runtime.claim(caseOffer.id,caseOffer.identity,{present:false});
check('apothecary-manual-exact-once-claim',caseClaim.ok&&caseClaim.globalApplications===1&&caseClaim.localApplications===1&&state.gold>beforeClaimGold&&state.phase1819.apothecary.cases&&Object.keys(state.phase1819.apothecary.cases).length===0&&!caseRepeat.ok&&state.saveMeta.revision===afterCaseRevision);
check('achievement-readiness-metrics-update',state.phase1819.achievements.metricValues['legacy.achievement.apothecary.cases-claimed']===1&&state.phase1819.achievements.metricValues['legacy.feat.apothecary.named-patients']===1);

commitDiscovery('story.book1.chapter3.river-accord.resolution','facility.schoolhouse');
check('schoolhouse-discovery-precedes-opening',runtime.contentEvent('story.book1.chapter3.river-accord.resolution').ok&&state.phase1819.schoolhouse.discovered===true&&state.phase1819.schoolhouse.unlocked===false&&runtime.openFacility('facility.schoolhouse').ok===true);
const schoolhouseOpening=commitOpening('facility.schoolhouse','capability.schoolhouse-lessons.v1','facility.schoolhouse.first-mentor-lesson','skipped');
check('schoolhouse-story-unlock-and-finite-arrival',schoolhouseOpening.ok&&state.phase1819.schoolhouse.unlocked&&same(state.phase1819.schoolhouse.candidatePupilIds,['schoolhouse.pupil.ena'])&&state.phase1819.tutorials.facilityIntroductionResolutionsByContentId['facility.schoolhouse.first-mentor-lesson']==='skipped'&&runtime.derive().schoolhouse.seatCapacity===1&&runtime.derive().schoolhouse.eligibleMentorActorIds.includes('family.yennefer')&&same(runtime.derive().schoolhouse.availableLessonIds,['schoolhouse.lesson.reading-the-road']));
const tutorialEntries=runtime.tutorialLogEntries(),tutorialReplayBefore=raw,tutorialReplayWrites=writes,tutorialReplay=runtime.tutorial('tutorial.facility.schoolhouse.first-lesson','replay');
check('persisted-introductions-appear-in-write-neutral-tutorial-log',tutorialEntries.find(item=>item.id==='tutorial.facility.apothecary.first-case')?.status==='watched'&&tutorialEntries.find(item=>item.id==='tutorial.facility.schoolhouse.first-lesson')?.status==='skipped'&&tutorialReplay.ok&&tutorialReplay.writes===0&&writes===tutorialReplayWrites&&raw===tutorialReplayBefore);
clock+=5400000;
const schoolSettle=runtime.settle('facility.schoolhouse',clock,{renderAfter:false}),lesson=runtime.derive().schoolhouse.lessons[0],seat=runtime.seatPupil('schoolhouse.pupil.ena','schoolhouse.seat.1');
check('approved-schoolhouse-cadence-seat',schoolSettle.ok&&schoolSettle.createdCount===1&&lesson.expiresAt===null&&seat.ok&&runtime.derive().schoolhouse.pupils.find(item=>item.id==='schoolhouse.pupil.ena').seatId==='schoolhouse.seat.1');
runtime.beginLesson(lesson.id,lesson.identity,'schoolhouse.pupil.ena','schoolhouse.seat.1');runtime.chooseApproach(lesson.id,lesson.identity,'schoolhouse.approach.demonstrate','family.yennefer');
const beforeLessonResolve=resources(state),lessonResolve=runtime.resolveLesson(lesson.id,lesson.identity),lessonOffer=runtime.derive().claims.pendingOffers[0];
check('schoolhouse-resolution-captures-no-payment',lessonResolve.ok&&['schoolhouse.outcome.guided','schoolhouse.outcome.resonant'].includes(lessonResolve.outcomeId)&&same(resources(state),beforeLessonResolve)&&lessonOffer.domainClaimKind==='schoolhouse-lesson'&&lessonOffer.localSnapshot.mentorActorId==='family.yennefer'&&lessonOffer.localSnapshot.mentorProgressBonus===1&&lessonOffer.localSnapshot.mentorGoldBonus>0);
const familyBefore=clone(state.family),lessonClaim=runtime.claim(lessonOffer.id,lessonOffer.identity,{present:false}),pupilAfter=runtime.derive().schoolhouse.pupils.find(item=>item.id==='schoolhouse.pupil.ena');
check('schoolhouse-claim-development-and-family-neutral',lessonClaim.ok&&lessonClaim.developmentApplications===1&&lessonClaim.educationApplications===1&&pupilAfter.claimedLessonCount===1&&same(state.family,familyBefore));
state.storyV1.completedSceneIds.push('story.book1.interlude.young-futures');check('second-seat-remains-gated',runtime.contentEvent('story.book1.interlude.young-futures').ok&&runtime.seatPupil('schoolhouse.pupil.bram','schoolhouse.seat.2').ok===false);

runtime.resetFixture('p19.qa.schoolhouse-graduation-ready.v1');
const graduationOffer=runtime.derive().claims.pendingOffers.find(item=>item.domainClaimKind==='schoolhouse-graduation'),graduation=runtime.claim(graduationOffer.id,graduationOffer.identity,{present:false}),graduationRevision=state.saveMeta.revision,graduationRepeat=runtime.claim(graduationOffer.id,graduationOffer.identity,{present:false});
check('graduation-v2-exact-once',graduation.ok&&graduation.majorRewardApplications===1&&graduation.educationApplications===1&&runtime.derive().schoolhouse.graduatedPupilIds.includes('schoolhouse.pupil.ena')&&runtime.derive().schoolhouse.graduationReceiptIdByPupilId['schoolhouse.pupil.ena']&&!graduationRepeat.ok&&state.saveMeta.revision===graduationRevision);

runtime.resetFixture('p18-19.qa.archive-window.v1');
const archiveBefore=runtime.derive().claimArchive,archiveOffer=runtime.derive().claims.pendingOffers[0],archiveClaim=runtime.claim(archiveOffer.id,archiveOffer.identity,{present:false}),archiveAfter=runtime.derive().claimArchive;
check('archive-fold-retains-bounded-recent-window',archiveBefore.recentReceipts.length===512&&archiveClaim.ok&&archiveAfter.recentReceipts.length===385&&archiveAfter.archiveCheckpoint.throughSequence===128);
check('serialized-state-valid',runtime.validate(JSON.parse(JSON.stringify(state)),()=>({ok:true,errors:[]})).ok);

runtime.resetFixture('p18-19.qa.fresh-null-policy.v1');
const rawBeforeInvalid=JSON.stringify(state),invalidResults=runtime.INVALID_MUTATION_CHECKS.map(id=>runtime.invalidMutation(id));
check('invalid-probes-are-write-neutral',invalidResults.every(result=>result.ok===false&&result.writes===0)&&JSON.stringify(state)===rawBeforeInvalid);
check('all-invalid-probes-fail-validation',invalidResults.every(result=>result.validationFailed===true),invalidResults.filter(result=>result.validationFailed!==true).map(result=>result.check).join(','));

const finalizerProbes=runtime.FINALIZER_DEFS.flatMap(definition=>['missing','throw','plan-tamper','local','range','delete','archive'].map(mode=>runtime.probeFinalizerFailure(definition.domainClaimKind,mode)));
check('finalizer-probes-atomic-refusal',finalizerProbes.every(result=>result.ok===false&&result.writes===0&&result.partialApplications===0&&result.activeUnchanged===true&&result.rawUnchanged===true&&result.revisionUnchanged===true&&result.resourcesUnchanged===true&&result.localUnchanged===true&&result.archiveUnchanged===true));
const passiveBefore=runtime.passiveBaseline(200000000);runtime.openFacility('facility.apothecary');const passiveAfter=runtime.passiveBaseline(200000000);
check('passive-original-four-immutable',same(passiveBefore,passiveAfter)&&passiveBefore.buildingSemantics.length===4);
const runtimeDefinitions=runtime.definitions(),policyReport=runtime.policyReport();
check('three-immutable-finalizers',runtimeDefinitions.finalizers.length===3&&runtimeDefinitions.finalizers.every(item=>item.immutable===true&&item.callerSupplied===false));
check('seven-approved-legacy-policies',runtimeDefinitions.achievements.length===7&&new Set(runtimeDefinitions.achievements.map(item=>item.definitionId)).size===7);
check('no-restaurant-policy-reuse',same(policyReport.restaurantPolicyIdsUsed,[])&&!read('src/phase18-19-runtime.js').includes('restaurant.recipe.')&&!read('src/phase18-19-runtime.js').includes('restaurant.station.'));
const privateRaw=JSON.stringify(state);privateAllowed=false;const publicSettle=runtime.settle('facility.apothecary',clock,{renderAfter:false}),publicVillage=runtime.villageHtml('<main class="screen village-screen"><section class="village-hud">');privateAllowed=true;
check('private-release-remains-disabled',policyReport.publicReleaseAllowed===false&&runtimeDefinitions.privateReleaseOnly===true&&runtimeDefinitions.publicReleaseAllowed===false&&!publicSettle.ok&&publicSettle.writes===0&&JSON.stringify(state)===privateRaw&&!publicVillage.includes('data-phase15-facility-board'));
runtime.setQaMode(false);state=baseState();raw=JSON.stringify(state);state.storyV1.completedSceneIds.push('story.book1.chapter2.records-in-rain');state.facilityProgress.discoveredIds.push('facility.apothecary');state.facilityProgress.unlockedIds.push('facility.apothecary');state.phase15FacilityFoundation.capabilityIds.push('capability.apothecary-cases.v1');const establishedActivation=runtime.activate(),establishedRoot=state.phase1819,establishedRaw=raw,establishedWrites=writes,establishedRevision=state.saveMeta.revision,establishedReloadNoop=runtime.settleOffline(clock),establishedReconcileNoop=runtime.reconcileCommittedTruth(),establishedEntry=runtime.tutorialLogEntries().find(item=>item.id==='tutorial.facility.apothecary.first-case');
check('established-phase17-opening-migrates-as-recap',establishedActivation===true&&establishedRoot.apothecary.unlocked===true&&establishedRoot.tutorials.facilityIntroductionResolutionsByContentId['facility.apothecary.possibility-case']==='migrated-recap'&&establishedEntry?.status==='migrated-recap'&&runtime.validate(state,baseValidate).ok&&establishedReloadNoop.writes===0&&establishedReconcileNoop.writes===0&&writes===establishedWrites&&state.saveMeta.revision===establishedRevision&&raw===establishedRaw);
check('closure-coordinator-was-used',mutations>20&&state.saveMeta.revision>1&&renders>0,{mutations,renders,revision:state.saveMeta.revision});

const passed=rows.filter(row=>row.pass).length,failed=rows.length-passed;
for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` — ${typeof row.detail==='string'?row.detail:JSON.stringify(row.detail)}`:''}`);
console.log(`RESULT ${passed} passed, ${failed} failed`);
process.exitCode=failed?1:0;
