(() => {
  'use strict';
  const PHASE_10B_API_TRAPS=true,PHASE_10B_GET_ALLOWLIST=Object.freeze(['./current-report.json','./scenarios.json','./current-manifest.json','./golden-current.json','./row-registry.json','../../index.html']),EXPECTED_TRAPS=Object.freeze(['window.localStorage','window.sessionStorage','window.indexedDB','window.caches','navigator.serviceWorker','navigator.clipboard','document.cookie','window.WebSocket','window.EventSource','window.XMLHttpRequest','window.open','window.showSaveFilePicker','navigator.sendBeacon','anchor.download','window.fetch']),CHANNEL='everstead-phase-10b',params=new URLSearchParams(location.search),realmKey=params.get('key')||'unknown',requestedMotion=params.get('motion')||'normal',byId=id=>document.getElementById(id),row=(id,pass,detail='')=>({id,pass:Boolean(pass),detail:String(detail)}),format=value=>Number(value).toLocaleString('en-US',{maximumFractionDigits:3}),errors=[],metrics={allowedGets:[],prohibitedApiCalls:[],storageCalls:[],renderSequence:[],installedTraps:[],trapFailures:[],fetchRequests:[]},nativeFetch=window.fetch.bind(window),allowedUrls=new Map(PHASE_10B_GET_ALLOWLIST.map(path=>[new URL(path,location.href).href,path]));
  const prohibit=name=>(...args)=>{metrics.prohibitedApiCalls.push({name,args:args.length});throw new Error(`Phase 10B prohibited API: ${name}`)},install=(name,operation)=>{try{operation();metrics.installedTraps.push(name)}catch(error){metrics.trapFailures.push({name,message:error.message});errors.push(`trap ${name}: ${error.message}`)}},trapProperty=(target,key,name,category=metrics.prohibitedApiCalls)=>install(name,()=>Object.defineProperty(target,key,{configurable:true,get(){category.push({name,operation:'get'});throw new Error(`Phase 10B prohibited API: ${name}`)},set(){category.push({name,operation:'set'});throw new Error(`Phase 10B prohibited API: ${name}`)}}));
  trapProperty(window,'localStorage','window.localStorage',metrics.storageCalls);trapProperty(window,'sessionStorage','window.sessionStorage',metrics.storageCalls);trapProperty(window,'indexedDB','window.indexedDB');trapProperty(window,'caches','window.caches');trapProperty(navigator,'serviceWorker','navigator.serviceWorker');trapProperty(navigator,'clipboard','navigator.clipboard');
  install('document.cookie',()=>Object.defineProperty(document,'cookie',{configurable:true,get:prohibit('document.cookie:get'),set:prohibit('document.cookie:set')}));
  for(const [name,value] of [['WebSocket',prohibit('WebSocket')],['EventSource',prohibit('EventSource')],['XMLHttpRequest',prohibit('XMLHttpRequest')],['open',prohibit('window.open')],['showSaveFilePicker',prohibit('showSaveFilePicker')]])install('window.'+name,()=>Object.defineProperty(window,name,{configurable:true,writable:false,value}));
  install('navigator.sendBeacon',()=>Object.defineProperty(navigator,'sendBeacon',{configurable:true,writable:false,value:prohibit('sendBeacon')}));
  install('anchor.download',()=>{const nativeClick=HTMLAnchorElement.prototype.click;Object.defineProperty(HTMLAnchorElement.prototype,'click',{configurable:true,value:function(){if(this.hasAttribute('download'))return prohibit('download')();return nativeClick.call(this)}})});
  install('window.fetch',()=>{window.fetch=async(resource,options={})=>{const requestUrl=new URL(typeof resource==='string'?resource:resource.url,location.href),method=String(options.method||(typeof resource==='object'&&resource.method)||'GET').toUpperCase(),canonical=allowedUrls.get(requestUrl.href),credentials='omit';if(method!=='GET'||!canonical||requestUrl.origin!==location.origin){metrics.prohibitedApiCalls.push({name:'fetch',method,url:requestUrl.href});throw new Error(`Phase 10B fetch refused: ${method} ${requestUrl.href}`)}const response=await nativeFetch(requestUrl.href,{cache:'no-store',credentials:'omit',method:'GET',referrerPolicy:'no-referrer'});metrics.allowedGets.push(canonical);metrics.fetchRequests.push({path:canonical,method,credentials,setCookieVisible:response.headers.has('set-cookie')});return response}});
  addEventListener('error',event=>errors.push(String(event.error?.stack||event.message||'realm error')));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason||'unhandled rejection')));document.documentElement.dataset.motion=requestedMotion;
  async function json(path){const response=await fetch(path);if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.json()}
  function unwrapCanonicalInPlace(value){if(Array.isArray(value)){for(let index=0;index<value.length;index++)value[index]=unwrapCanonicalInPlace(value[index]);return value}if(value&&typeof value==='object'){const keys=Object.keys(value);if(keys.length===2&&keys[0]==='$float64'&&keys[1]==='decimal'&&/^[0-9a-f]{16}$/.test(value.$float64)&&typeof value.decimal==='string'){const bytes=Uint8Array.from(value.$float64.match(/../g),part=>parseInt(part,16)),number=new DataView(bytes.buffer).getFloat64(0,false);if(String(number)!==value.decimal)throw new Error('Invalid canonical Float64 wrapper');return number}for(const key of keys)value[key]=unwrapCanonicalInPlace(value[key]);return value}return value}
  function options(select,values){select.replaceChildren(...values.map(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;return option}))}
  function put(target,entries){target.replaceChildren(...entries.flatMap(([label,value,className=''])=>{const left=document.createElement('span'),right=document.createElement('strong');left.textContent=label;right.textContent=String(value);right.className=className;return[left,right]}))}
  function render(report){const configId=byId('config').value,archetypeId=byId('archetype').value,horizonId=byId('horizon').value,bundle=report.bundles.find(item=>item.metadata.configId===configId&&item.metadata.archetypeId===archetypeId&&item.metadata.horizonId===horizonId);if(!bundle)throw new Error('Selected bundle missing');const gold=bundle.ledger.gold;
    byId('identity').textContent=`Report ${report.reportIdentity} · Bundle ${bundle.identity}`;byId('status').textContent=bundle.metadata.status;byId('status').className=`chip ${bundle.metadata.status==='released parity'?'ok':'warn'}`;
    put(byId('ledger'),[['Starting Gold',format(gold.startGold)],['Generated',format(gold.buildingGeneratedTotal)],['Pending start / end',`${format(gold.pendingStart)} / ${format(gold.pendingEnd)}`],['Claimed',format(gold.claimedGold)],['Fellow Campaign',format(gold.fellowCampaignSpent)],['Companion Campaign',format(gold.companionCampaignSpent)],['Building upgrades',format(gold.buildingUpgradeSpent)],['Ending Gold',format(gold.endGold)],['Conserved',String(gold.conserved),gold.conserved?'ok':'warn']]);
    put(byId('power'),[['Fellow economy Power',format(bundle.power.ending.fellowEconomyPower)],['Companion economy Power',format(bundle.power.ending.companionEconomyPower)],['Fellow combat Power',format(bundle.power.ending.fellowCombatPower)],['Fellow bonus',`${bundle.power.ending.fellowBonusBps} bps`],['Companion bonus',`${bundle.power.ending.companionBonusBps} bps`],['Excluded from Fellow',bundle.power.ending.fellowRows[0].economyExcludedTerms.join(', ')]]);
    put(byId('buildings'),[['Levels',Object.values(bundle.buildings.endingLevels).join(' / ')],['Gold per hour',format(bundle.buildings.totalRate)],['Capped 24h output',format(bundle.buildings.capped24HourOutput)],['Claims',bundle.pacing.claimCount],['Upgrades',bundle.pacing.upgradeCount],['Segments',bundle.ledger.segments.length]]);
    put(byId('checks'),Object.entries(bundle.safety).filter(([,value])=>typeof value==='boolean').map(([key,value])=>[key,String(value),value?'ok':'warn']));metrics.renderSequence.push({configId,archetypeId,horizonId,identity:bundle.identity,status:bundle.metadata.status,ledger:byId('ledger').textContent,power:byId('power').textContent});return bundle
  }
  function selectAndDispatch(select,value){select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));return metrics.renderSequence.at(-1)}
  async function run(){try{const [canonicalReport,scenarios,manifest,golden,registry]=await Promise.all([json('./current-report.json'),json('./scenarios.json'),json('./current-manifest.json'),json('./golden-current.json'),json('./row-registry.json')]),report=unwrapCanonicalInPlace(canonicalReport),configIds=scenarios.candidateConfigs,archetypeIds=scenarios.archetypes,horizonIds=scenarios.horizons,expectedIds=scenarios.simulation.live.realmRowIds;
      options(byId('config'),configIds);options(byId('archetype'),archetypeIds);options(byId('horizon'),horizonIds);const initial=render(report);for(const id of ['config','archetype','horizon'])byId(id).addEventListener('change',()=>render(report));
      const released=report.bundles.filter(bundle=>bundle.metadata.status==='released parity'),advisory=report.bundles.filter(bundle=>bundle.metadata.status==='advisory candidate'),numbers=[];(function collect(value){if(typeof value==='number')numbers.push(value);else if(Array.isArray(value))value.forEach(collect);else if(value&&typeof value==='object')Object.values(value).forEach(collect)})(report);
      const beforeConfig=metrics.renderSequence.at(-1),afterConfig=selectAndDispatch(byId('config'),'candidate-growth-120'),afterArchetype=selectAndDispatch(byId('archetype'),'mid'),afterHorizon=selectAndDispatch(byId('horizon'),'7-day'),finalBundle=report.bundles.find(bundle=>bundle.identity===afterHorizon.identity),gold=initial.ledger.gold;
      const rows=[
        row('realm-boot',PHASE_10B_API_TRAPS&&realmKey!=='unknown',realmKey),row('report-version',report.reportVersion===3),row('report-phase',report.phase==='10B-1'),row('report-bundle-count',report.bundleCount===144&&report.bundles.length===144,report.bundles.length),row('report-advisory-only',report.candidateStatus==='advisory-only'),row('production-unchanged',report.productionChanged===false&&manifest.productionChanged===false),row('config-count',configIds.length===4,configIds.length),row('archetype-count',archetypeIds.length===6,archetypeIds.length),row('horizon-count',horizonIds.length===6,horizonIds.length),row('bundle-combinations',new Set(report.bundles.map(bundle=>[bundle.metadata.configId,bundle.metadata.archetypeId,bundle.metadata.horizonId].join('|'))).size===144),
        row('released-count',released.length===36,released.length),row('advisory-count',advisory.length===108,advisory.length),row('bundle-identities',report.bundles.every(bundle=>/^[a-f0-9]{64}$/.test(bundle.identity))),row('finite-values',numbers.every(Number.isFinite)),row('conserved-ledgers',report.bundles.every(bundle=>bundle.ledger.gold.conserved)),row('safe-values',report.bundles.every(bundle=>bundle.safety.safe)),row('nonnegative-values',report.bundles.every(bundle=>bundle.safety.nonnegative)),row('caps-respected',report.bundles.every(bundle=>bundle.safety.caps)),row('power-disjoint',report.bundles.every(bundle=>bundle.power.noDoubleCountProof.disjoint)),row('labels-correct',released.every(bundle=>bundle.metadata.comparisonStatus==='released parity')&&advisory.every(bundle=>bundle.metadata.comparisonStatus==='advisory candidate')),
        row('companion-transfer-excluded',advisory.every(bundle=>bundle.power.ending.fellowRows.every(item=>item.economyExcludedTerms.includes('companionPowerTransfer')))),row('family-bond-excluded',advisory.every(bundle=>bundle.power.ending.fellowRows.every(item=>item.economyExcludedTerms.includes('familyBondMultiplier')))),row('companion-power-positive',report.bundles.every(bundle=>bundle.power.ending.companionEconomyPower>0)),row('source-ledger-visible',Object.keys(gold.buildingGeneratedByBuilding).length===4&&byId('ledger').textContent.includes('Generated')),row('sink-ledger-visible',['fellowCampaignSpent','companionCampaignSpent','buildingUpgradeSpent'].every(key=>Object.hasOwn(gold,key))),row('rate-table-visible',Object.keys(initial.buildings.rows).length===4&&byId('buildings').textContent.includes('Gold per hour')),row('capped-output-visible',Object.hasOwn(initial.buildings,'capped24HourOutput')&&byId('buildings').textContent.includes('Capped 24h output')),row('ending-levels-visible',Object.keys(initial.buildings.endingLevels).length===4&&byId('buildings').textContent.includes('Levels')),row('pending-collection-visible',Object.hasOwn(gold,'pendingStart')&&Object.hasOwn(gold,'claimedGold')&&byId('ledger').textContent.includes('Pending start / end')),row('selected-bundle-rendered',byId('identity').textContent.includes(finalBundle.identity)),
        row('config-control-updates',afterConfig.configId==='candidate-growth-120'&&afterConfig.identity!==beforeConfig.identity),row('archetype-control-updates',afterArchetype.archetypeId==='mid'&&afterArchetype.identity!==afterConfig.identity),row('horizon-control-updates',afterHorizon.horizonId==='7-day'&&afterHorizon.identity!==afterArchetype.identity),row('status-label-updates',afterConfig.status==='advisory candidate'&&byId('status').textContent==='advisory candidate'),row('source-sink-render-updates',beforeConfig.ledger!==afterHorizon.ledger),row('power-render-updates',beforeConfig.power!==afterArchetype.power),row('no-horizontal-overflow',document.documentElement.scrollWidth<=document.documentElement.clientWidth,`${document.documentElement.scrollWidth}/${document.documentElement.clientWidth}`),row('motion-mode',document.documentElement.dataset.motion===requestedMotion,requestedMotion),row('zero-prohibited-api-calls',metrics.prohibitedApiCalls.length===0&&metrics.storageCalls.length===0&&metrics.trapFailures.length===0&&sameIds(metrics.installedTraps,EXPECTED_TRAPS)&&metrics.fetchRequests.every(request=>request.method==='GET'&&request.credentials==='omit'&&request.setCookieVisible===false)&&errors.length===0&&sameGets(metrics.allowedGets,['./current-report.json','./scenarios.json','./current-manifest.json','./golden-current.json','./row-registry.json']),JSON.stringify({allowedGets:metrics.allowedGets,prohibited:metrics.prohibitedApiCalls,storage:metrics.storageCalls,installed:metrics.installedTraps,trapFailures:metrics.trapFailures,fetchRequests:metrics.fetchRequests,errors})),row('frozen-registry-visible',registry.exactTotal===624&&golden.goldenVersion===2&&expectedIds.length===40&&new Set(expectedIds).size===40)
      ];
      function sameIds(left,right){return JSON.stringify(left)===JSON.stringify(right)}function sameGets(left,right){return sameIds(left.slice().sort(),right.slice().sort())}
      if(rows.length!==40||!sameIds(rows.map(item=>item.id),expectedIds)||new Set(rows.map(item=>item.id)).size!==40)throw new Error(`Realm row registry mismatch: ${rows.length}`);parent.postMessage({channel:CHANNEL,key:realmKey,rows,errors,fatal:'',metrics},location.origin)
    }catch(error){parent.postMessage({channel:CHANNEL,key:realmKey,rows:[],errors,fatal:String(error.stack||error.message||error),metrics},location.origin)}}
  run();
})();
