import {createHash} from 'node:crypto';

const CONFIG_IDS=['released-schema10','candidate-growth-120','candidate-growth-122','candidate-growth-124'];
const ARCHETYPE_IDS=['fresh','early','mid','late','near-cap','max-stress'];
const HORIZON_IDS=['instant','1-hour','24-hour','3-day','7-day','30-day'];
const ROOT_KEYS=['scenarioVersion','phase','timeZone','fixedSaveId','buildingLevels','buildingProfiles','offlineDurations','fellowPowerProfiles','companionPowerProfiles','candidateConfigs','archetypes','horizons','simulation'];
const SIM_KEYS=['simulatorVersion','scenarioFormatVersion','identities','fixedStartAt','timeZone','saveId','oathBoosts','policy','safety','releasedConstants','configs','archetypes','horizons','fellowCampaignStages','companionCampaignStages','live'];
const ARCHETYPE_KEYS=['id','buildingLevels','upgradeLimitPerClaim','rosterState','goldClock','campaignState','idleState'];
const ROSTER_KEYS=['fellows','companions','family','gifts','relicStones','relicInventory','mightPoints','masteryPoints','player'];
const FELLOW_KEYS=['owned','exp','level','rarity','shards','bond','equippedRelicId'];
const COMPANION_KEYS=['owned','exp','level','rarity','shards','assignedFellowId'];
const FAMILY_KEYS=['intimacy','rarity','shards','assignedBuildingId'];
const CAMPAIGN_KEYS=['selectedStageId','clearedStageIds','firstClearClaimedStageIds','runOrdinal','runCountsByStage'];
const ARTIFACT_SHA='717160cdddc5fa540532cdebd29f30d127ded2f761edd677684a2609fde9a4ed';
const CONTRACT_BASE='723492b1e968407f23c7d78deabf66813f14c229';
const REFERENCE_MODEL_ID='phase-10b-independent-reference-v3';
const RAW_AUTHORITIES=Object.freeze({
  scenarios:'759bcbc68001a898f3379931f4cb64b12ab442bab7976282ebedebb1ee0819c8',simulation:'b11935d043c7699a73f362f7dff44b8164696ff9b7cce4851152211f0d04a9f1',releasedConstants:'199d2f1efca2300bc24a488ebb847821af034368d8791afcf5661661aae1fa6a',policy:'4ae05ec09475847f66986195b0710b82bb752efa930d4d9ada2788c0eddfac5e',safety:'b518d9b18f1a27dce41d88e56bf8e4249e6f8da5a968b6437ad178dcdecedfc8',oathBoosts:'b9b28542a657385327df461b367f0ebf164654dd3e48adfd1283175d0133b5c7',fellowCampaignStages:'018d2635efc4ecb7a32ad71a1de0ff795878f637d42fc50d2b990c3bc2b9bf78',companionCampaignStages:'d5f3a4d5c54e37aaccd89f8847343b7ffaa1aa33062ab8350615eba7b3d45fdd',live:'f00f080ce2b2cdfce1782bcc7e8b8b797b4022420799236ead07cfcc7dacd9ef',
  configs:Object.freeze({'released-schema10':'4f4ea2aedef3da8244b7dcbc5115284441cbfad5c8157034b1d5441481446a20','candidate-growth-120':'816b2c50b005ed698328854fc73cf3dc73bc814b25847d442a1e92c06cf43c4d','candidate-growth-122':'86c4a13a8e2137447dc790d412d70159ab1ac91e06ca1cf91ad53c3fed14bb23','candidate-growth-124':'6bfad46d8e0eab69845ed32465fbb045743d32336188b57a4455d33f010b5207'}),
  archetypes:Object.freeze({fresh:'19b975e2951f53f6c737106170fd11f3170fad978292cb5fb02fa09fe3bf288c',early:'8913cb5495ca374af1f0354e229579bd5f715e3ea18b1c2404a2eea12057b53f',mid:'163fa33a2e2e8502c0bb55837837cc3ddba8db994e7531919fba2a677709ce40',late:'f19341a79449ef2bcdeb89f564bb20ba40139bfbe9d76ca15a4023ab2a2cb5fa','near-cap':'497f95ba65319bca0c1ebc63e5bb35e43e9542950850ccbc363fd7de8f611d1b','max-stress':'a2228b40dd630a318c635c8afc08b86dd5bc948f91fe233205296c5feddf0fab'}),
  horizons:Object.freeze({instant:'ad9d6f41888cabf1b70c51a2f6c6d40055ced4256cba12b503d9ce977173356d','1-hour':'6ccf7d70bae32bb03da1b51cbfcc7235f397cad83f4a118386f9d063344f1db0','24-hour':'69b8d990bfb405267824a634a64a0011300be72acc186976f4531bd81ed069ac','3-day':'a6141eeba469aa51f4f7d9218d637a964e0a832241f10611a90c3d1c46dfd31c','7-day':'3e6b6c19921ea425bf104b219c6dad4711934d2374d9892d17b9e3f3ee45bb03','30-day':'b4798604906640160a6554ea7936a3ce829e90224e1f6dd7a6a7f74f211f17a3'})
});
const clone=value=>structuredClone(value);
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const exactKeys=(value,keys)=>value!==null&&typeof value==='object'&&!Array.isArray(value)&&same(Object.keys(value),keys);
const deepFreeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))deepFreeze(child)}return value};
const stable=value=>{if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])]));return value};
const canonicalText=value=>JSON.stringify(stable(value));
const sha=value=>createHash('sha256').update(typeof value==='string'?value:canonicalText(value)).digest('hex');
const rawSha=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const fail=message=>{throw new Error('Phase 10B scenario refused: '+message)};
const integer=value=>Number.isSafeInteger(value)&&value>=0;
const finite=value=>typeof value==='number'&&Number.isFinite(value)&&value>=0;
const exactIdMap=(value,ids)=>exactKeys(value,ids);
const sum=values=>values.reduce((total,value)=>total+value,0);
const sumMap=value=>sum(Object.values(value));
const rewardMap=ids=>Object.fromEntries(ids.map(id=>[id,0]));
const addSafe=(left,right,label)=>{const result=left+right;if(!Number.isSafeInteger(result)||result<0)throw new Error(label+' exceeds safe integer precision');return result};
const walkNumbers=(value,path,rows=[])=>{path=path||'$';if(typeof value==='number')rows.push({path,value});else if(Array.isArray(value))value.forEach((item,index)=>walkNumbers(item,path+'['+index+']',rows));else if(value&&typeof value==='object')for(const [key,item]of Object.entries(value))walkNumbers(item,path+'.'+key,rows);return rows};
const canonicalFloat=value=>{
  if(typeof value==='number'&&!Number.isInteger(value)){const bytes=Buffer.allocUnsafe(8);bytes.writeDoubleBE(value);return{$float64:bytes.toString('hex'),decimal:String(value)}}
  if(Array.isArray(value))return value.map(canonicalFloat);
  if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonicalFloat(value[key])]));
  return value;
};
export const unwrapCanonical=value=>{
  if(Array.isArray(value))return value.map(unwrapCanonical);
  if(value&&typeof value==='object'){
    if(exactKeys(value,['$float64','decimal'])&&typeof value.$float64==='string'&&/^[0-9a-f]{16}$/.test(value.$float64)&&typeof value.decimal==='string'){const number=Buffer.from(value.$float64,'hex').readDoubleBE();if(String(number)!==value.decimal)throw new Error('Invalid canonical Float64 wrapper');return number}
    return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,unwrapCanonical(item)]));
  }
  return value;
};
const expToNext=(level,base,growth,cap)=>Math.round(base*Math.pow(growth,Math.max(1,Math.min(cap,Math.floor(level)))-1));
const expThreshold=(level,base,growth,cap)=>{let total=0;for(let current=1;current<Math.min(level,cap);current++)total+=expToNext(current,base,growth,cap);return total};
const progressionState=(member,base,growth,cap,rarityMax,rarityCosts)=>{const currentLevelThreshold=expThreshold(member.level,base,growth,cap),nextLevelCost=member.level>=cap?null:expToNext(member.level,base,growth,cap),nextLevelThreshold=nextLevelCost===null?null:currentLevelThreshold+nextLevelCost,expIntoLevel=member.exp-currentLevelThreshold,nextRarityCost=member.rarity>=rarityMax?null:rarityCosts[member.rarity-1];return{...clone(member),currentLevelThreshold,nextLevelCost,nextLevelThreshold,expIntoLevel,expRemainingToNext:nextLevelCost===null?null:nextLevelCost-expIntoLevel,rarityMax,rarityShardCosts:clone(rarityCosts),nextRarityCost,shardsRemainingToAscend:nextRarityCost===null?null:Math.max(0,nextRarityCost-member.shards),cumulativeRaritySpend:sum(rarityCosts.slice(0,Math.max(0,member.rarity-1)))}};
const levelForExp=(exp,base,growth,cap)=>{let level=1,total=0;while(level<cap){const next=expToNext(level,base,growth,cap);if(exp<total+next)break;total+=next;level++}return level};
const rankForExp=(exp,thresholds)=>{let rank=1;for(let index=1;index<thresholds.length;index++)if(exp>=thresholds[index])rank=index+1;return rank};
const progress=(points,factor,cap,perLevel,pointsCap)=>{let level=0;while(level<cap&&factor*(level+1)*(level+1)<=points)level++;return{points,level,threshold:factor*level*level,nextThreshold:level>=cap?pointsCap:factor*(level+1)*(level+1),multiplier:1+perLevel*level,pointsCap,levelCap:cap}};
const stableUnit=(saveId,scope,ordinal,salt)=>{const text=[saveId,scope,ordinal,salt].join('\u001f');let hash=2166136261;for(let index=0;index<text.length;index++){hash^=text.charCodeAt(index);hash=Math.imul(hash,16777619)}return(hash>>>0)/4294967296};
const dayKey=timestamp=>{const date=new Date(timestamp);return'D'+date.getFullYear()+'-'+(date.getMonth()+1)+'-'+date.getDate()};
const nextMidnight=timestamp=>{const date=new Date(timestamp);date.setHours(24,0,0,0);return date.getTime()};
const curveBps=(power,curve)=>curve.enabled?Math.min(curve.capBps,Math.floor(curve.numeratorBps*power/(power+curve.kneePower))):0;
const upgradeCost=(level,input)=>level>=input.releasedConstants.buildingLevelCap?null:Math.round(input.releasedConstants.upgradeBase*Math.pow(input.config.upgradeGrowth,level-1));
const campaignEfficiency=(power,stage,c)=>{const surplusRatio=Math.max(0,power/stage.recommendedPower-1),discountRate=Math.min(c.campaignDiscountCap,surplusRatio*c.campaignDiscountScale);return{baseCost:stage.baseCost,recommendedPower:stage.recommendedPower,totalRosterPower:power,surplusRatio,discountRate,effectiveCost:Math.max(1,Math.ceil(stage.baseCost*(1-discountRate)))}};
const relicComponents=(id,inventory,c)=>{const def=c.relics[id],item=inventory[id],level=item.level,bonusBps=item.owned?def.baseBonusBps+def.perLevelBonusBps*(level-1):0;return{id,tier:def.tier,sourceStageId:def.stageId,owned:item.owned,level,bonusBps,multiplier:1+bonusBps/10000,nextCost:!item.owned||level>=c.relicLevelCap?null:def.upgradeCostFactor*level}};

function validateCampaignState(lane,state,stages,rank,c){
  if(!exactKeys(state,CAMPAIGN_KEYS)||(state.selectedStageId!==null&&!stages.some(stage=>stage.id===state.selectedStageId))||!Array.isArray(state.clearedStageIds)||!Array.isArray(state.firstClearClaimedStageIds)||!integer(state.runOrdinal)||!exactIdMap(state.runCountsByStage,stages.map(stage=>stage.id)))fail('campaign '+lane+' shape');
  const prefix=stages.slice(0,state.clearedStageIds.length).map(stage=>stage.id);
  if(!same(state.clearedStageIds,prefix)||!same(state.firstClearClaimedStageIds,prefix)||new Set(prefix).size!==prefix.length||state.runOrdinal!==prefix.length||Object.values(state.runCountsByStage).some(value=>!integer(value))||stages.some(stage=>state.runCountsByStage[stage.id]!==Number(prefix.includes(stage.id))))fail('campaign '+lane+' no-replay history');
  const expectedSelected=prefix.length===stages.length?null:stages[prefix.length].id;if(state.selectedStageId!==expectedSelected)fail('campaign '+lane+' next first-clear selection');
  if(lane==='fellow'&&expectedSelected!==null&&c.playerStageRankRequirements[prefix.length]>rank)fail('campaign '+lane+' rank access');
}


export function simulateCanonicalInput(rawInput){
  const input=validateInput(rawInput),c=input.releasedConstants,a=input.archetype,initial=clone(a.rosterState),state=initialState(input),awards=awardLedger(c),campaignAwards=awardLedger(c),generatedByBuilding=rewardMap(c.buildingIds),segments=[],claims=[],goldOperations=[],campaignReceipts=[],idleReceipts=[],startingPower=powerSnapshot(input,state),startingStageTables={fellow:stageTable(input,state,'fellow',startingPower),companion:stageTable(input,state,'companion',startingPower)};let elapsedHours=0,claimCount=0,upgradeCount=0,claimedGold=0,fellowCampaignSpent=0,companionCampaignSpent=0,upgradeSpent=0,operationSequence=0;
  while(elapsedHours<input.horizon.hours){
    const stepHours=Math.min(input.policy.claimCadenceHours,input.horizon.hours-elapsedHours);if(++claimCount>input.safety.maxClaims)throw new Error('claim safety limit');const claimStart=input.fixedStartAt+elapsedHours*3600000,claimEnd=claimStart+stepHours*3600000,powerBefore=powerSnapshot(input,state),claimLineTotals=rewardMap(c.buildingIds);let cursor=claimStart;
    while(cursor<claimEnd){if(segments.length>=input.safety.maxSegments*2)throw new Error('segment safety limit');const end=Math.min(claimEnd,nextMidnight(cursor)),durationMs=end-cursor,rows=buildingRows(input,state,powerBefore,cursor),buildingValues={};for(const row of rows){const value=row.rate*durationMs/3600000,lineBefore=claimLineTotals[row.id];buildingValues[row.id]=value;generatedByBuilding[row.id]+=value;claimLineTotals[row.id]+=value;goldOperations.push({sequence:++operationSequence,claim:claimCount,at:end,type:'building-line-accumulation',buildingId:row.id,lineOperation:'add',lineDelta:value,lineBefore,lineAfter:claimLineTotals[row.id],pendingOperation:'none',pendingDelta:0,goldOperation:'none',goldDelta:0,pendingBefore:state.pendingGold,pendingAfter:state.pendingGold,goldBefore:state.gold,goldAfter:state.gold})}segments.push({claim:claimCount,start:cursor,end,durationMs,day:dayKey(cursor),buildingValues,total:sumMap(buildingValues),lineTotalsAfter:clone(claimLineTotals),pendingAfter:state.pendingGold,oathActive:dayKey(cursor)===dayKey(input.fixedStartAt)});cursor=end}
    let claimGeneratedTotal=0;for(const buildingId of c.buildingIds){const reductionBefore=claimGeneratedTotal;claimGeneratedTotal+=claimLineTotals[buildingId];goldOperations.push({sequence:++operationSequence,claim:claimCount,at:claimEnd,type:'building-line-reduction',buildingId,lineOperation:'reduce',lineDelta:claimLineTotals[buildingId],lineBefore:reductionBefore,lineAfter:claimGeneratedTotal,pendingOperation:'none',pendingDelta:0,goldOperation:'none',goldDelta:0,pendingBefore:state.pendingGold,pendingAfter:state.pendingGold,goldBefore:state.gold,goldAfter:state.gold})}const pendingBeforeAccrual=state.pendingGold;state.pendingGold+=claimGeneratedTotal;goldOperations.push({sequence:++operationSequence,claim:claimCount,at:claimEnd,type:'pending-accrual',buildingId:null,reductionOrder:clone(c.buildingIds),lineTotals:clone(claimLineTotals),lineOperation:'commit',lineDelta:claimGeneratedTotal,lineBefore:claimGeneratedTotal,lineAfter:claimGeneratedTotal,pendingOperation:'add',pendingDelta:claimGeneratedTotal,goldOperation:'none',goldDelta:0,pendingBefore:pendingBeforeAccrual,pendingAfter:state.pendingGold,goldBefore:state.gold,goldAfter:state.gold});
    const towerSettlement=settleLane(state.idleState.tower,claimEnd,state.idleState.tower.highestFloor,c,'tower'),towerRewards=applyLaneRewards(input,state,'tower',towerSettlement,awards),expeditionSettlement=settleLane(state.idleState.expedition,claimEnd,state.idleState.expedition.highestStage,c,'expedition'),expeditionRewards=applyLaneRewards(input,state,'expedition',expeditionSettlement,awards),familySettlement=settleFamily(input,state,stepHours*3600000,awards);
    idleReceipts.push({claim:claimCount,at:claimEnd,tower:{...towerSettlement,rewards:towerRewards},expedition:{...expeditionSettlement,rewards:expeditionRewards},family:familySettlement,goldGenerated:0});
    const pendingBeforeCollection=state.pendingGold,wholeGold=Math.floor(state.pendingGold),goldBeforeCollection=state.gold;state.pendingGold-=wholeGold;state.gold+=wholeGold;claimedGold+=wholeGold;goldOperations.push({sequence:++operationSequence,claim:claimCount,at:claimEnd,type:'pending-collection',buildingId:null,pendingOperation:'subtract',pendingDelta:wholeGold,goldOperation:'add',goldDelta:wholeGold,pendingBefore:pendingBeforeCollection,pendingAfter:state.pendingGold,goldBefore:goldBeforeCollection,goldAfter:state.gold});const claim={claim:claimCount,at:claimEnd,pendingBeforeCollection,claimedGold:wholeGold,pendingAfterCollection:state.pendingGold,campaigns:[],upgrades:[]};
    for(const lane of input.policy.campaignOrder)for(let run=0;run<input.policy.campaignRunsPerClaim[lane];run++){if(campaignReceipts.length>=input.safety.maxCampaignRuns)throw new Error('campaign safety limit');const goldBeforeCampaign=state.gold,receipt=runCampaign(input,state,lane,powerSnapshot(input,state),claimEnd,awards,campaignAwards);if(receipt.status==='complete')break;claim.campaigns.push(receipt);campaignReceipts.push(receipt);if(receipt.status==='cleared'){const cost=receipt.efficiency.effectiveCost;if(lane==='fellow')fellowCampaignSpent+=cost;else companionCampaignSpent+=cost;goldOperations.push({sequence:++operationSequence,claim:claimCount,at:claimEnd,type:lane+'-campaign-spend',buildingId:null,pendingOperation:'none',pendingDelta:0,goldOperation:'subtract',goldDelta:cost,pendingBefore:state.pendingGold,pendingAfter:state.pendingGold,goldBefore:goldBeforeCampaign,goldAfter:state.gold})}}
    for(let attempt=0;attempt<a.upgradeLimitPerClaim;attempt++){if(upgradeCount>=input.safety.maxUpgrades)throw new Error('upgrade safety limit');let chosen=null;for(const id of input.policy.buildingTieOrder){const cost=upgradeCost(state.buildingLevels[id],input);if(cost!==null&&(!chosen||cost<chosen.cost))chosen={id,cost}}if(!chosen||state.gold<chosen.cost)break;const goldBeforeUpgrade=state.gold;state.gold-=chosen.cost;upgradeSpent+=chosen.cost;state.buildingLevels[chosen.id]++;upgradeCount++;goldOperations.push({sequence:++operationSequence,claim:claimCount,at:claimEnd,type:'building-upgrade-spend',buildingId:chosen.id,pendingOperation:'none',pendingDelta:0,goldOperation:'subtract',goldDelta:chosen.cost,pendingBefore:state.pendingGold,pendingAfter:state.pendingGold,goldBefore:goldBeforeUpgrade,goldAfter:state.gold});claim.upgrades.push({buildingId:chosen.id,cost:chosen.cost,nextLevel:state.buildingLevels[chosen.id]})}
    claims.push(claim);elapsedHours+=stepHours;
  }
  let expectedEndGold=input.config.freshGold,expectedPendingGold=a.goldClock.pendingGold,operationTraceExact=true,replayClaim=0,replayLineTotals=rewardMap(c.buildingIds),replayReduction=0;
  for(const operation of goldOperations){if(operation.claim!==replayClaim){replayClaim=operation.claim;replayLineTotals=rewardMap(c.buildingIds);replayReduction=0}if(!Object.is(expectedEndGold,operation.goldBefore)||!Object.is(expectedPendingGold,operation.pendingBefore))operationTraceExact=false;if(operation.type==='building-line-accumulation'){if(!Object.is(replayLineTotals[operation.buildingId],operation.lineBefore))operationTraceExact=false;replayLineTotals[operation.buildingId]+=operation.lineDelta;if(!Object.is(replayLineTotals[operation.buildingId],operation.lineAfter))operationTraceExact=false}else if(operation.type==='building-line-reduction'){if(!Object.is(replayReduction,operation.lineBefore)||!Object.is(replayLineTotals[operation.buildingId],operation.lineDelta))operationTraceExact=false;replayReduction+=replayLineTotals[operation.buildingId];if(!Object.is(replayReduction,operation.lineAfter))operationTraceExact=false}else if(operation.type==='pending-accrual'){if(!same(operation.reductionOrder,c.buildingIds)||!same(operation.lineTotals,replayLineTotals)||!Object.is(replayReduction,operation.pendingDelta))operationTraceExact=false}if(operation.pendingOperation==='add')expectedPendingGold+=operation.pendingDelta;else if(operation.pendingOperation==='subtract')expectedPendingGold-=operation.pendingDelta;if(operation.goldOperation==='add')expectedEndGold+=operation.goldDelta;else if(operation.goldOperation==='subtract')expectedEndGold-=operation.goldDelta;if(!Object.is(expectedEndGold,operation.goldAfter)||!Object.is(expectedPendingGold,operation.pendingAfter))operationTraceExact=false}
  const endingPower=powerSnapshot(input,state),endingRows=buildingRows(input,state,endingPower,input.fixedStartAt+input.horizon.hours*3600000),generatedTotal=sumMap(generatedByBuilding),totalSpent=fellowCampaignSpent+companionCampaignSpent+upgradeSpent,conserved=operationTraceExact&&Object.is(state.gold,expectedEndGold)&&Object.is(state.pendingGold,expectedPendingGold),totalRate=sum(endingRows.map(row=>row.rate));
  const buildingTable=Object.fromEntries(endingRows.map(row=>[row.id,{...row,timeToAffordHours:row.nextUpgradeCost===null?null:state.gold>=row.nextUpgradeCost?0:Math.max(0,(row.nextUpgradeCost-state.gold-Math.floor(state.pendingGold))/Math.max(1,totalRate))}]));
  const relicRows=Object.fromEntries(Object.keys(c.relics).map(id=>{const parts=relicComponents(id,state.relicInventory,c),starting=relicComponents(id,initial.relicInventory,c),equippedBy=c.fellowIds.find(fellowId=>state.fellows[fellowId].equippedRelicId===id)||null;return[id,{tier:parts.tier,sourceStageId:parts.sourceStageId,owned:parts.owned,startingLevel:starting.level,endingLevel:parts.level,bonusBps:parts.bonusBps,multiplier:parts.multiplier,nextCost:parts.nextCost,equippedBy}]}));
  const startingMight=progress(initial.mightPoints,c.mightThresholdFactor,c.mightLevelCap,c.mightPowerPerLevel,c.mightPointsCap),endingMight=progress(state.mightPoints,c.mightThresholdFactor,c.mightLevelCap,c.mightPowerPerLevel,c.mightPointsCap),startingMastery=progress(initial.masteryPoints,c.masteryThresholdFactor,c.masteryLevelCap,c.masteryPowerPerLevel,c.masteryPointsCap),endingMastery=progress(state.masteryPoints,c.masteryThresholdFactor,c.masteryLevelCap,c.masteryPowerPerLevel,c.masteryPointsCap),endingStageTables={fellow:stageTable(input,state,'fellow',endingPower),companion:stageTable(input,state,'companion',endingPower)},rankAccess=input.fellowCampaignStages.map(stage=>({stageId:stage.id,ordinal:stage.ordinal,requiredRank:c.playerStageRankRequirements[stage.ordinal-1],startingAccess:initial.player.rank>=c.playerStageRankRequirements[stage.ordinal-1],endingAccess:state.player.rank>=c.playerStageRankRequirements[stage.ordinal-1]}));
  const actualAwards={fellowExp:Object.fromEntries(c.fellowIds.map(id=>[id,state.fellows[id].exp-initial.fellows[id].exp])),fellowShards:Object.fromEntries(c.fellowIds.map(id=>[id,state.fellows[id].shards-initial.fellows[id].shards])),companionExp:Object.fromEntries(c.companionIds.map(id=>[id,state.companions[id].exp-initial.companions[id].exp])),companionShards:Object.fromEntries(c.companionIds.map(id=>[id,state.companions[id].shards-initial.companions[id].shards])),familyShards:Object.fromEntries(c.familyIds.map(id=>[id,state.family[id].shards-initial.family[id].shards])),gifts:state.gifts-initial.gifts,rankExp:state.player.rankExp-initial.player.rankExp,might:state.mightPoints-initial.mightPoints,mastery:state.masteryPoints-initial.masteryPoints},resourceBalances=Object.fromEntries(Object.keys(actualAwards).map(key=>[key,typeof actualAwards[key]==='object'?same(actualAwards[key],awards[key]):actualAwards[key]===awards[key]])),rewardedCampaignReceipts=campaignReceipts.filter(receipt=>receipt.status==='cleared'),rewardedNonFirstClearReceipts=rewardedCampaignReceipts.filter(receipt=>receipt.firstClear!==true).map(receipt=>({lane:receipt.lane,stageId:receipt.stageId,status:receipt.status})),campaignRewardIds=rewardedCampaignReceipts.map(receipt=>'campaign:'+receipt.lane+':'+receipt.stageId+':first-clear'),idleRewardIds=idleReceipts.flatMap(receipt=>['tower:claim-'+receipt.claim,'expedition:claim-'+receipt.claim,'family:claim-'+receipt.claim]),rewardIds=campaignRewardIds.concat(idleRewardIds),duplicateRewardIds=campaignRewardIds.filter((id,index)=>campaignRewardIds.indexOf(id)!==index),lostResources=Object.entries(resourceBalances).filter(([,ok])=>!ok).map(([id])=>id),campaignNoReplay=proveCampaignNoReplay(input,a,state,campaignReceipts,campaignAwards,{fellow:fellowCampaignSpent,companion:companionCampaignSpent});
  const allValues=walkNumbers({state,generatedByBuilding,segments,startingPower,endingPower,awards}),safe=allValues.every(item=>Math.abs(item.value)<=input.safety.maxSafeInteger),nonnegative=allValues.every(item=>item.value>=0),caps=Object.values(state.buildingLevels).every(level=>level<=c.buildingLevelCap)&&Object.values(state.fellows).every(member=>member.level<=c.fellowLevelCap&&member.rarity<=c.fellowRarityMax)&&Object.values(state.companions).every(member=>member.level<=c.companionLevelCap&&member.rarity<=c.companionRarityMax)&&state.mightPoints<=c.mightPointsCap&&state.masteryPoints<=c.masteryPointsCap&&endingPower.fellowBonusBps<=input.config.fellowRosterCurve.capBps&&endingPower.companionBonusBps<=input.config.companionRosterCurve.capBps,familyCounts=Object.fromEntries(endingRows.map(row=>[row.id,row.familyApplicationCount])),familyDirectOnce=endingRows.every(row=>row.familyApplicationCount===1&&row.componentSequence.filter(item=>item==='familyAssignmentMultiplier').length===1);
  const timeToUpgradeBands=Object.fromEntries(endingRows.map(row=>[row.id,{nextCost:row.nextUpgradeCost,fromCurrentGoldHours:row.nextUpgradeCost===null?null:state.gold>=row.nextUpgradeCost?0:(row.nextUpgradeCost-state.gold)/Math.max(1,totalRate),fromZeroHours:row.nextUpgradeCost===null?null:row.nextUpgradeCost/Math.max(1,totalRate),band:row.nextUpgradeCost===null?'cap':state.gold>=row.nextUpgradeCost?'now':(row.nextUpgradeCost-state.gold)/Math.max(1,totalRate)<=24?'within-24h':'over-24h'}])),stageAffordability={fellow:endingStageTables.fellow.map(row=>({stageId:row.stageId,effectiveCost:row.efficiency.effectiveCost,goldReady:row.goldReady,powerReady:row.powerReady,rankReady:row.rankReady,sequenceReady:row.sequenceReady,canRun:row.canRun})),companion:endingStageTables.companion.map(row=>({stageId:row.stageId,effectiveCost:row.efficiency.effectiveCost,goldReady:row.goldReady,powerReady:row.powerReady,rankReady:row.rankReady,sequenceReady:row.sequenceReady,canRun:row.canRun}))},shardDrought={tower:{starting:a.idleState.tower.pityMisses,ending:state.idleState.tower.pityMisses,forceAt:c.towerPityForceAt,remaining:Math.max(0,c.towerPityForceAt-1-state.idleState.tower.pityMisses)},expedition:{starting:a.idleState.expedition.pityMisses,ending:state.idleState.expedition.pityMisses,forceAt:c.expeditionPityForceAt,remaining:Math.max(0,c.expeditionPityForceAt-1-state.idleState.expedition.pityMisses)},family:Object.fromEntries(c.buildingIds.map(id=>[id,{starting:a.idleState.family[id].shardDrought,ending:state.idleState.family[id].shardDrought,forceAt:c.familyPityForceAt,remaining:Math.max(0,c.familyPityForceAt-1-state.idleState.family[id].shardDrought)}]))};
  const body={
    metadata:{phase:'10B-1',simulatorVersion:input.simulatorVersion,scenarioFormatVersion:input.scenarioFormatVersion,status:input.config.status,configId:input.config.id,archetypeId:a.id,horizonId:input.horizon.id,hours:input.horizon.hours,fixedStartAt:input.fixedStartAt,timeZone:input.timeZone,saveId:input.saveId,inputIdentity:sha(input),identities:clone(input.identities),policyId:input.policy.id,comparisonStatus:input.config.status},
    inputs:{config:clone(input.config),archetype:clone(a),horizon:clone(input.horizon),policy:clone(input.policy),safety:clone(input.safety),progressionConstants:{fellow:{levelCap:c.fellowLevelCap,expBase:c.fellowExpBase,expGrowth:c.fellowExpGrowth,expRounding:'Math.round each level step',rarityMax:c.fellowRarityMax,rarityShardCosts:clone(c.fellowRarityCosts)},companion:{levelCap:c.companionLevelCap,expBase:c.companionExpBase,expGrowth:c.companionExpGrowth,expRounding:'Math.round each level step',rarityMax:c.companionRarityMax,rarityShardCosts:clone(c.companionRarityCosts)},sourceIdentity:input.identities.releasedConstantsIdentity}},
    ledger:{gold:{startGold:input.config.freshGold,buildingGeneratedByBuilding:generatedByBuilding,buildingGeneratedTotal:generatedTotal,pendingStart:a.goldClock.pendingGold,pendingEnd:state.pendingGold,claimedGold,fellowCampaignSpent,companionCampaignSpent,buildingUpgradeSpent:upgradeSpent,totalSpent,endGold:state.gold,expectedEndGold,expectedPendingGold,operationTraceExact,conserved},operations:goldOperations,segments,claims},
    buildings:{rows:buildingTable,startingLevels:clone(a.buildingLevels),endingLevels:clone(state.buildingLevels),totalRate,capped24HourOutput:totalRate*24,familyDirectOnce:{applicationCounts:familyCounts,passed:familyDirectOnce}},
    power:{starting:startingPower,ending:endingPower,acceptedCombatOwnership:['Fellow own','assigned Companion unrounded transfer','Family Bond','Might'],candidateEconomyOwnership:['Fellow own + Relic + Might','Companion own + Mastery'],excludedFromFellowEconomy:['companionPowerTransfer','familyBondMultiplier'],noDoubleCountProof:endingPower.noDoubleCountProof},
    progression:{fellows:Object.fromEntries(c.fellowIds.map(id=>[id,{starting:progressionState(initial.fellows[id],c.fellowExpBase,c.fellowExpGrowth,c.fellowLevelCap,c.fellowRarityMax,c.fellowRarityCosts),ending:progressionState(state.fellows[id],c.fellowExpBase,c.fellowExpGrowth,c.fellowLevelCap,c.fellowRarityMax,c.fellowRarityCosts)}])),companions:Object.fromEntries(c.companionIds.map(id=>[id,{starting:progressionState(initial.companions[id],c.companionExpBase,c.companionExpGrowth,c.companionLevelCap,c.companionRarityMax,c.companionRarityCosts),ending:progressionState(state.companions[id],c.companionExpBase,c.companionExpGrowth,c.companionLevelCap,c.companionRarityMax,c.companionRarityCosts)}])),family:{startingGifts:initial.gifts,endingGifts:state.gifts,rows:Object.fromEntries(c.familyIds.map(id=>[id,{intimacy:state.family[id].intimacy,rarity:state.family[id].rarity,startingShards:initial.family[id].shards,endingShards:state.family[id].shards,assignedBuildingId:state.family[id].assignedBuildingId}]))},player:{starting:{...clone(initial.player),threshold:c.playerRankThresholds[initial.player.rank-1],nextThreshold:initial.player.rank<c.playerRankCap?c.playerRankThresholds[initial.player.rank]:null},ending:{...clone(state.player),threshold:c.playerRankThresholds[state.player.rank-1],nextThreshold:state.player.rank<c.playerRankCap?c.playerRankThresholds[state.player.rank]:null},rankAccess},might:{starting:startingMight,ending:endingMight},mastery:{starting:startingMastery,ending:endingMastery},relics:relicRows,campaign:{startingState:clone(a.campaignState),endingState:clone(state.campaignState),startingStageTables,endingStageTables,receipts:campaignReceipts,noReplayProof:campaignNoReplay}},
    idle:{receipts:idleReceipts,starting:clone(a.idleState),ending:clone(state.idleState),carryProvenance:{tower:{startingSegments:clone(a.idleState.tower.segments),endingSegments:clone(state.idleState.tower.segments)},expedition:{startingSegments:clone(a.idleState.expedition.segments),endingSegments:clone(state.idleState.expedition.segments)},family:Object.fromEntries(c.buildingIds.map(id=>[id,{startingContext:clone(a.idleState.family[id].carryContext),endingContext:clone(state.idleState.family[id].carryContext),startingCarryMs:a.idleState.family[id].rollCarryMs,endingCarryMs:state.idleState.family[id].rollCarryMs}]))},goldNeutral:idleReceipts.every(receipt=>receipt.goldGenerated===0)},
    pacing:{horizonHours:input.horizon.hours,claimCount,upgradeCount,campaignRuns:campaignReceipts.filter(receipt=>receipt.status==='cleared').length,timeToUpgradeBands,stageAffordability,shardDrought,cappedVsUncapped:{gold:{nominalHours:input.horizon.hours,acceptedHours:sum(segments.map(segment=>segment.durationMs))/3600000,capHoursPerClaim:c.offlineGoldCapMs/3600000},tower:{nominalElapsedMs:sum(idleReceipts.map(receipt=>receipt.tower.settlement.nominalElapsedMs)),acceptedElapsedMs:sum(idleReceipts.map(receipt=>receipt.tower.settlement.acceptedElapsedMs)),discardedElapsedMs:sum(idleReceipts.map(receipt=>receipt.tower.settlement.cappedDiscardedMs)),capMsPerClaim:c.towerElapsedCapMs},expedition:{nominalElapsedMs:sum(idleReceipts.map(receipt=>receipt.expedition.settlement.nominalElapsedMs)),acceptedElapsedMs:sum(idleReceipts.map(receipt=>receipt.expedition.settlement.acceptedElapsedMs)),discardedElapsedMs:sum(idleReceipts.map(receipt=>receipt.expedition.settlement.cappedDiscardedMs)),capMsPerClaim:c.expeditionElapsedCapMs}}},
    safety:{finite:allValues.every(item=>Number.isFinite(item.value)),safe,nonnegative,caps,sourceSinkConserved:conserved,noDoubleCount:endingPower.noDoubleCountProof.disjoint,familyDirectOnce,stepLimits:{claims:claimCount<=input.safety.maxClaims,campaigns:campaignReceipts.length<=input.safety.maxCampaignRuns,upgrades:upgradeCount<=input.safety.maxUpgrades,segments:segments.length<=input.safety.maxSegments*2},inputUnchanged:JSON.stringify(rawInput)===JSON.stringify(input),resourceAccounting:{awardLedger:awards,campaignAwardLedger:campaignAwards,actualAwards,balances:resourceBalances,rewardIds,campaignRewardIds,rewardedNonFirstClearReceipts,duplicateRewardIds,lostResources,campaignNoReplay:campaignNoReplay.valid,noDuplicateRewards:duplicateRewardIds.length===0&&rewardedNonFirstClearReceipts.length===0&&campaignNoReplay.valid,noLostResources:lostResources.length===0}}
  };
  return{...body,identity:sha(body)};
}
export function simulateBundle(scenarios,configId,archetypeId,horizonId){return simulateCanonicalInput(buildCanonicalInput(scenarios,configId,archetypeId,horizonId))}
export function buildAdvisoryReportRaw(scenarios){const sim=validateScenarioRegistry(scenarios),bundles=[];for(const config of sim.configs)for(const archetype of sim.archetypes)for(const horizon of sim.horizons)bundles.push(simulateBundle(scenarios,config.id,archetype.id,horizon.id));if(bundles.length!==144)throw new Error('Advisory report expected 144 bundles, received '+bundles.length);const body={reportVersion:3,phase:'10B-1',productionChanged:false,candidateStatus:'advisory-only',scenarioIdentity:sha(sim),bundleCount:bundles.length,bundles};return{...body,reportIdentity:sha(body)}}
export function buildAdvisoryReport(scenarios){return canonicalFloat(buildAdvisoryReportRaw(scenarios))}
export function canonicalReportText(report){return JSON.stringify(report,null,2)+'\n'}
export const simulatorIdentities=Object.freeze({artifactSha256:ARTIFACT_SHA,contractBase:CONTRACT_BASE,referenceModelIdentity:REFERENCE_MODEL_ID});



function laneStagePreview(input,state,lane,powerState){
  const stages=lane==='fellow'?input.fellowCampaignStages:input.companionCampaignStages,history=state.campaignState[lane];
  if(history.selectedStageId===null)return{lane,stageId:null,stageOrdinal:null,targetId:null,firstClear:false,replayRefused:false,complete:true,requiredRank:null,sequenceReady:false,rankReady:false,powerReady:false,goldReady:false,canRun:false,efficiency:null,rewards:{exp:0,shards:0,rankExp:0}};
  const stage=stages.find(item=>item.id===history.selectedStageId);if(!stage)throw new Error('campaign selected stage is not canonical');const firstClear=!history.clearedStageIds.includes(stage.id),efficiency=campaignEfficiency(lane==='fellow'?powerState.fellowCombatPower:powerState.companionCombatPower,stage,input.releasedConstants),sequenceReady=firstClear&&history.clearedStageIds.length===stage.ordinal-1,requiredRank=lane==='fellow'?input.releasedConstants.playerStageRankRequirements[stage.ordinal-1]:1,rankReady=state.player.rank>=requiredRank,powerReady=efficiency.totalRosterPower>=stage.recommendedPower,goldReady=state.gold>=efficiency.effectiveCost;
  return{lane,stageId:stage.id,stageOrdinal:stage.ordinal,targetId:stage.targetId,firstClear,replayRefused:!firstClear,complete:false,requiredRank,sequenceReady,rankReady,powerReady,goldReady,canRun:firstClear&&sequenceReady&&rankReady&&powerReady&&goldReady,efficiency,rewards:{exp:stage.firstClearExp,shards:stage.firstClearShards,rankExp:lane==='fellow'?stage.rankExp:0}};
}
function runCampaign(input,state,lane,powerState,at,awards,campaignAwards){
  const preview=laneStagePreview(input,state,lane,powerState),history=state.campaignState[lane];
  if(!preview.canRun){const status=preview.complete?'complete':preview.replayRefused?'replay-refused':preview.sequenceReady&&preview.rankReady&&preview.powerReady?'gold-blocked':preview.sequenceReady&&preview.rankReady?'power-blocked':preview.sequenceReady?'rank-blocked':'sequence-blocked';return{...preview,status,completedAt:null,rewards:{exp:0,shards:0,rankExp:0,gifts:0}}}
  state.gold-=preview.efficiency.effectiveCost;const target=lane==='fellow'?state.fellows[preview.targetId]:state.companions[preview.targetId],c=input.releasedConstants,expKey=lane==='fellow'?'fellowExp':'companionExp',shardKey=lane==='fellow'?'fellowShards':'companionShards';
  target.exp=addSafe(target.exp,preview.rewards.exp,preview.targetId+' Campaign EXP');target.level=levelForExp(target.exp,lane==='fellow'?c.fellowExpBase:c.companionExpBase,lane==='fellow'?c.fellowExpGrowth:c.companionExpGrowth,lane==='fellow'?c.fellowLevelCap:c.companionLevelCap);target.shards=addSafe(target.shards,preview.rewards.shards,preview.targetId+' Campaign shards');awards[expKey][preview.targetId]+=preview.rewards.exp;campaignAwards[expKey][preview.targetId]+=preview.rewards.exp;awards[shardKey][preview.targetId]+=preview.rewards.shards;campaignAwards[shardKey][preview.targetId]+=preview.rewards.shards;
  let gift=0;if(lane==='fellow'){state.player.rankExp=addSafe(state.player.rankExp,preview.rewards.rankExp,'Rank EXP');state.player.rank=rankForExp(state.player.rankExp,c.playerRankThresholds);awards.rankExp+=preview.rewards.rankExp;campaignAwards.rankExp+=preview.rewards.rankExp;gift=stableUnit(input.saveId,preview.stageId,history.runOrdinal,c.stableSalts.fellowCampaignGift)<c.fellowCampaignGiftChance?1:0;state.gifts+=gift;awards.gifts+=gift;campaignAwards.gifts+=gift}
  history.clearedStageIds.push(preview.stageId);history.firstClearClaimedStageIds.push(preview.stageId);const stages=lane==='fellow'?input.fellowCampaignStages:input.companionCampaignStages;history.selectedStageId=preview.stageOrdinal<stages.length?stages[preview.stageOrdinal].id:null;
  history.runCountsByStage[preview.stageId]++;history.runOrdinal++;
  return{...preview,status:'cleared',completedAt:at,sequence:history.runOrdinal,rewards:{...preview.rewards,gifts:gift}};
}
function stageTable(input,state,lane,powerState){
  const stages=lane==='fellow'?input.fellowCampaignStages:input.companionCampaignStages,history=state.campaignState[lane],totalPower=lane==='fellow'?powerState.fellowCombatPower:powerState.companionCombatPower;
  return stages.map(stage=>{const efficiency=campaignEfficiency(totalPower,stage,input.releasedConstants),firstClear=!history.clearedStageIds.includes(stage.id),sequenceReady=firstClear&&history.clearedStageIds.length===stage.ordinal-1,requiredRank=lane==='fellow'?input.releasedConstants.playerStageRankRequirements[stage.ordinal-1]:1,rankReady=state.player.rank>=requiredRank,powerReady=totalPower>=stage.recommendedPower,goldReady=state.gold>=efficiency.effectiveCost;return{stageId:stage.id,ordinal:stage.ordinal,targetId:stage.targetId,selected:history.selectedStageId===stage.id,firstClear,replayRefused:!firstClear,requiredRank,sequenceReady,rankReady,powerReady,goldReady,canRun:firstClear&&sequenceReady&&rankReady&&powerReady&&goldReady,efficiency,rewards:{exp:stage.firstClearExp,shards:stage.firstClearShards,rankExp:lane==='fellow'?stage.rankExp:0}}});
}
function proveCampaignNoReplay(input,initial,state,receipts,campaignAwards,spentByLane){
  const lanes={};let valid=true;
  for(const lane of ['fellow','companion']){
    const stages=lane==='fellow'?input.fellowCampaignStages:input.companionCampaignStages,start=initial.campaignState[lane],end=state.campaignState[lane],expectedCleared=clone(start.clearedStageIds),expectedClaimed=clone(start.firstClearClaimedStageIds),expectedCounts=clone(start.runCountsByStage);let expectedOrdinal=start.runOrdinal,expectedSpend=0;
    const rewarded=receipts.filter(receipt=>receipt.lane===lane&&receipt.status==='cleared'),blocked=receipts.filter(receipt=>receipt.lane===lane&&receipt.status!=='cleared');
    for(const receipt of rewarded){const stage=stages.find(item=>item.id===receipt.stageId),expectedStage=stages[expectedCleared.length],firstClearValid=receipt.firstClear===true&&stage===expectedStage&&!expectedCleared.includes(receipt.stageId),rewardValid=!!stage&&receipt.rewards.exp===stage.firstClearExp&&receipt.rewards.shards===stage.firstClearShards&&receipt.rewards.rankExp===(lane==='fellow'?stage.rankExp:0);if(!firstClearValid||!rewardValid)valid=false;expectedCleared.push(receipt.stageId);expectedClaimed.push(receipt.stageId);expectedCounts[receipt.stageId]++;expectedOrdinal++;expectedSpend+=receipt.efficiency.effectiveCost}
    const blockedZero=blocked.every(receipt=>receipt.rewards.exp===0&&receipt.rewards.shards===0&&receipt.rewards.rankExp===0&&receipt.rewards.gifts===0),endingMatches=same(end.clearedStageIds,expectedCleared)&&same(end.firstClearClaimedStageIds,expectedClaimed)&&same(end.runCountsByStage,expectedCounts)&&end.runOrdinal===expectedOrdinal&&end.selectedStageId===(expectedCleared.length===stages.length?null:stages[expectedCleared.length].id),spendMatches=Object.is(spentByLane[lane],expectedSpend),naturalRewardIds=rewarded.map(receipt=>'campaign:'+lane+':'+receipt.stageId+':first-clear'),uniqueNaturalIds=new Set(naturalRewardIds).size===naturalRewardIds.length;
    if(!blockedZero||!endingMatches||!spendMatches||!uniqueNaturalIds)valid=false;
    lanes[lane]={initialClearedPrefix:clone(start.clearedStageIds),rewardedStageIds:rewarded.map(receipt=>receipt.stageId),naturalRewardIds,blockedZero,endingMatches,spendMatches,expectedSpend,actualSpend:spentByLane[lane],complete:end.selectedStageId===null,postCapNoReceipt:end.selectedStageId!==null||!receipts.some(receipt=>receipt.lane===lane&&receipt.status==='complete'),uniqueNaturalIds};
    if(!lanes[lane].postCapNoReceipt)valid=false;
  }
  const expectedCampaignAwards=awardLedger(input.releasedConstants);for(const receipt of receipts.filter(item=>item.status==='cleared')){const expKey=receipt.lane==='fellow'?'fellowExp':'companionExp',shardKey=receipt.lane==='fellow'?'fellowShards':'companionShards';expectedCampaignAwards[expKey][receipt.targetId]+=receipt.rewards.exp;expectedCampaignAwards[shardKey][receipt.targetId]+=receipt.rewards.shards;if(receipt.lane==='fellow'){expectedCampaignAwards.rankExp+=receipt.rewards.rankExp;expectedCampaignAwards.gifts+=receipt.rewards.gifts}}
  const campaignAwardsMatch=same(expectedCampaignAwards,campaignAwards);if(!campaignAwardsMatch)valid=false;
  return{valid,lanes,campaignAwards:clone(campaignAwards),expectedCampaignAwards,campaignAwardsMatch,rewardedNonFirstClear:receipts.filter(receipt=>receipt.status==='cleared'&&receipt.firstClear!==true).map(receipt=>({lane:receipt.lane,stageId:receipt.stageId}))};
}
function initialState(input){
  const a=input.archetype,r=a.rosterState;
  return{gold:input.config.freshGold,pendingGold:a.goldClock.pendingGold,buildingLevels:clone(a.buildingLevels),fellows:clone(r.fellows),companions:clone(r.companions),family:clone(r.family),gifts:r.gifts,relicStones:r.relicStones,relicInventory:clone(r.relicInventory),mightPoints:r.mightPoints,masteryPoints:r.masteryPoints,player:clone(r.player),campaignState:clone(a.campaignState),idleState:clone(a.idleState)};
}
function awardLedger(c){return{fellowExp:rewardMap(c.fellowIds),fellowShards:rewardMap(c.fellowIds),companionExp:rewardMap(c.companionIds),companionShards:rewardMap(c.companionIds),familyShards:rewardMap(c.familyIds),gifts:0,rankExp:0,might:0,mastery:0}}

function validateSegments(segments,key,cap){
  if(!Array.isArray(segments)||segments.length>50)return false;let total=0;
  for(const segment of segments){if(!exactKeys(segment,[key,'elapsedMs'])||!integer(segment[key])||segment[key]<1||segment[key]>50||!integer(segment.elapsedMs)||segment.elapsedMs<1)return false;total+=segment.elapsedMs}
  return total<=cap;
}
function validateCountMap(value){const ids=Array.from({length:50},(_,index)=>String(index+1));return exactIdMap(value,ids)&&Object.values(value).every(integer)}

export function validateScenarioRegistry(scenarios){
  if(!exactKeys(scenarios,ROOT_KEYS)||scenarios.scenarioVersion!==1||scenarios.phase!=='10B-1'||scenarios.timeZone!=='America/Phoenix')fail('root shape/version');
  if(rawSha(scenarios)!==RAW_AUTHORITIES.scenarios)fail('registry bytes/order/value authority');
  const sim=scenarios.simulation;
  if(!exactKeys(sim,SIM_KEYS)||sim.simulatorVersion!==3||sim.scenarioFormatVersion!==4||sim.timeZone!=='America/Phoenix'||!integer(sim.fixedStartAt)||typeof sim.saveId!=='string'||!sim.saveId)fail('simulation shape/version');
  if(!exactKeys(sim.identities,['productionArtifactSha256','productionArtifactBytes','contractBase','phase10aBase','releasedConfigId','referenceModelId','scenarioRegistryId'])||sim.identities.productionArtifactSha256!==ARTIFACT_SHA||sim.identities.productionArtifactBytes!==18916682||sim.identities.contractBase!==CONTRACT_BASE||sim.identities.referenceModelId!==REFERENCE_MODEL_ID)fail('authoritative identities');
  if(!same(scenarios.candidateConfigs,CONFIG_IDS)||!same(sim.configs.map(item=>item.id),CONFIG_IDS)||!same(scenarios.archetypes,ARCHETYPE_IDS)||!same(sim.archetypes.map(item=>item.id),ARCHETYPE_IDS)||!same(scenarios.horizons,HORIZON_IDS)||!same(sim.horizons.map(item=>item.id),HORIZON_IDS))fail('registry IDs/order');
  const c=sim.releasedConstants,b=c.buildingIds,f=c.fellowIds,co=c.companionIds,fa=c.familyIds,relicIds=Object.keys(c.relics);
  if(!same(b,['training','command','archives','hearth'])||!same(f,['cael','lyra','orin','selene','rook','mira'])||!same(co,['bramble','cinderwing'])||!same(fa,['elara','tamsin','isolde'])||relicIds.length!==6)fail('released ID order');
  if(!exactIdMap(c.buildingBaseRates,b)||!exactIdMap(c.familySpecialties,fa)||!exactIdMap(c.fellowBasePower,f)||!exactIdMap(c.fellowFamilyLinkCount,f)||!exactIdMap(c.fellowFamilyLinks,f))fail('released map order');
  if(!exactIdMap(sim.oathBoosts,b)||Object.values(sim.oathBoosts).some(value=>!finite(value)||value>c.oathDailyCap))fail('Oath inputs');
  if(!exactKeys(sim.policy,['id','claimCadenceHours','campaignRunsPerClaim','campaignOrder','idleSettlementOrder','familyDropsWithGoldAccrual','buildingTieOrder','collectWholePendingGoldOnly','upgradeAfterCampaigns','finalPartialHorizonClaim','campaignFirstClearRule','campaignReplayRule','campaignRefusalRule','idlePushSettlementRule','progressionApplicationRule','stopConditions'])||!exactKeys(sim.policy.campaignRunsPerClaim,['fellow','companion'])||!same(sim.policy.campaignOrder,['fellow','companion'])||!same(sim.policy.buildingTieOrder,b)||sim.policy.collectWholePendingGoldOnly!==true||sim.policy.finalPartialHorizonClaim!=='settle-and-collect-at-horizon-end'||!Array.isArray(sim.policy.stopConditions)||new Set(sim.policy.stopConditions).size!==sim.policy.stopConditions.length)fail('policy');
  if(!exactKeys(sim.safety,['maxHorizonHours','maxClaims','maxCampaignRuns','maxUpgrades','maxIdleIntervalsPerLane','maxFamilyRolls','maxSegments','maxSafeInteger'])||Object.values(sim.safety).some(value=>!integer(value))||sim.safety.maxSafeInteger!==Number.MAX_SAFE_INTEGER)fail('safety');
  for(const config of sim.configs)if(!exactKeys(config,['id','label','status','freshGold','upgradeGrowth','fellowRosterCurve','companionRosterCurve'])||!integer(config.freshGold)||!finite(config.upgradeGrowth)||!['released parity','advisory candidate'].includes(config.status))fail('config '+config.id);
  for(const curve of sim.configs.flatMap(config=>[config.fellowRosterCurve,config.companionRosterCurve]))if(!exactKeys(curve,['enabled','numeratorBps','kneePower','capBps'])||typeof curve.enabled!=='boolean'||![curve.numeratorBps,curve.kneePower,curve.capBps].every(integer)||curve.kneePower===0)fail('curve');
  const stageKeysF=['id','ordinal','recommendedPower','baseCost','firstClearExp','targetId','firstClearShards','rankExp'],stageKeysC=['id','ordinal','recommendedPower','baseCost','firstClearExp','targetId','firstClearShards'];
  for(const group of [['fellow',sim.fellowCampaignStages,stageKeysF,f],['companion',sim.companionCampaignStages,stageKeysC,co]]){const lane=group[0],stages=group[1],keys=group[2],ids=group[3];if(stages.length!==10||new Set(stages.map(stage=>stage.id)).size!==10)fail(lane+' stage IDs');stages.forEach((stage,index)=>{if(!exactKeys(stage,keys)||stage.ordinal!==index+1||!ids.includes(stage.targetId)||Object.values(stage).filter(value=>typeof value==='number').some(value=>!integer(value)))fail(lane+' stage '+(index+1))})}
  for(const [id,def]of Object.entries(c.relics))if(!exactKeys(def,['tier','stageId','baseBonusBps','perLevelBonusBps','upgradeCostFactor'])||!integer(def.tier)||def.tier<1||def.tier>3||!sim.fellowCampaignStages.some(stage=>stage.id===def.stageId)||![def.baseBonusBps,def.perLevelBonusBps,def.upgradeCostFactor].every(integer))fail('Relic '+id);
  for(const archetype of sim.archetypes){
    if(!exactKeys(archetype,ARCHETYPE_KEYS)||!exactIdMap(archetype.buildingLevels,b)||Object.values(archetype.buildingLevels).some(level=>!integer(level)||level<1||level>c.buildingLevelCap)||!integer(archetype.upgradeLimitPerClaim))fail('archetype '+archetype.id);
    const roster=archetype.rosterState;
    if(!exactKeys(roster,ROSTER_KEYS)||!exactIdMap(roster.fellows,f)||!exactIdMap(roster.companions,co)||!exactIdMap(roster.family,fa)||!exactIdMap(roster.relicInventory,relicIds)||![roster.gifts,roster.relicStones,roster.mightPoints,roster.masteryPoints].every(integer))fail(archetype.id+' roster');
    for(const [id,value]of Object.entries(roster.fellows))if(!exactKeys(value,FELLOW_KEYS)||value.owned!==true||!integer(value.exp)||!integer(value.level)||value.level!==levelForExp(value.exp,c.fellowExpBase,c.fellowExpGrowth,c.fellowLevelCap)||!integer(value.rarity)||value.rarity<1||value.rarity>c.fellowRarityMax||!integer(value.shards)||!finite(value.bond)||(value.equippedRelicId!==null&&!relicIds.includes(value.equippedRelicId)))fail(archetype.id+' Fellow '+id);
    const companionAssignments=[];for(const [id,value]of Object.entries(roster.companions)){if(!exactKeys(value,COMPANION_KEYS)||value.owned!==true||!integer(value.exp)||!integer(value.level)||value.level!==levelForExp(value.exp,c.companionExpBase,c.companionExpGrowth,c.companionLevelCap)||!integer(value.rarity)||value.rarity<1||value.rarity>c.companionRarityMax||!integer(value.shards)||(value.assignedFellowId!==null&&!f.includes(value.assignedFellowId)))fail(archetype.id+' Companion '+id);if(value.assignedFellowId)companionAssignments.push(value.assignedFellowId)}
    if(new Set(companionAssignments).size!==companionAssignments.length)fail(archetype.id+' Companion assignments');
    const familyAssignments=[];for(const [id,value]of Object.entries(roster.family)){if(!exactKeys(value,FAMILY_KEYS)||!finite(value.intimacy)||!integer(value.rarity)||value.rarity<1||value.rarity>c.familyRarityMax||!integer(value.shards)||(value.assignedBuildingId!==null&&!b.includes(value.assignedBuildingId)))fail(archetype.id+' Family '+id);if(value.assignedBuildingId)familyAssignments.push(value.assignedBuildingId)}
    if(new Set(familyAssignments).size!==familyAssignments.length)fail(archetype.id+' Family assignments');
    const equipped=[];for(const [id,value]of Object.entries(roster.relicInventory))if(!exactKeys(value,['owned','level'])||typeof value.owned!=='boolean'||!integer(value.level)||(value.owned?(value.level<1||value.level>c.relicLevelCap):value.level!==0))fail(archetype.id+' Relic '+id);
    for(const fellow of Object.values(roster.fellows))if(fellow.equippedRelicId){if(!roster.relicInventory[fellow.equippedRelicId].owned)fail(archetype.id+' equipped Relic ownership');equipped.push(fellow.equippedRelicId)}
    const player=roster.player;if(new Set(equipped).size!==equipped.length||!exactKeys(player,['rankExp','rank','grandfatheredUnlockIds'])||!integer(player.rankExp)||player.rank!==rankForExp(player.rankExp,c.playerRankThresholds)||!Array.isArray(player.grandfatheredUnlockIds)||new Set(player.grandfatheredUnlockIds).size!==player.grandfatheredUnlockIds.length)fail(archetype.id+' Player/Relic state');
    if(!exactKeys(archetype.goldClock,['pendingGold','lastGoldAt','pendingContextDay'])||!finite(archetype.goldClock.pendingGold)||archetype.goldClock.lastGoldAt!==sim.fixedStartAt||archetype.goldClock.pendingContextDay!==dayKey(sim.fixedStartAt))fail(archetype.id+' Gold clock');
    if(!exactKeys(archetype.campaignState,['fellow','companion']))fail(archetype.id+' campaign root');validateCampaignState('fellow',archetype.campaignState.fellow,sim.fellowCampaignStages,player.rank,c);validateCampaignState('companion',archetype.campaignState.companion,sim.companionCampaignStages,player.rank,c);
    if(!exactKeys(archetype.idleState,['tower','expedition','family'])||!exactKeys(archetype.idleState.tower,['highestFloor','cursorAt','segments','intervalOrdinal','pityMisses','claimOrdinal','claimedIntervalsByFloor'])||!exactKeys(archetype.idleState.expedition,['highestStage','bestRunSequence','cursorAt','segments','intervalOrdinal','pityMisses','claimOrdinal','claimedIntervalsByStage'])||!exactIdMap(archetype.idleState.family,b))fail(archetype.id+' idle root');
    const tower=archetype.idleState.tower,expedition=archetype.idleState.expedition;
    if(!integer(tower.highestFloor)||tower.highestFloor>50||tower.cursorAt!==sim.fixedStartAt||!validateSegments(tower.segments,'floor',c.towerElapsedCapMs)||!integer(tower.intervalOrdinal)||!integer(tower.pityMisses)||tower.pityMisses>=c.towerPityForceAt||!integer(tower.claimOrdinal)||!validateCountMap(tower.claimedIntervalsByFloor))fail(archetype.id+' Tower');
    if(!integer(expedition.highestStage)||expedition.highestStage>50||!integer(expedition.bestRunSequence)||expedition.cursorAt!==sim.fixedStartAt||!validateSegments(expedition.segments,'stage',c.expeditionElapsedCapMs)||!integer(expedition.intervalOrdinal)||!integer(expedition.pityMisses)||expedition.pityMisses>=c.expeditionPityForceAt||!integer(expedition.claimOrdinal)||!validateCountMap(expedition.claimedIntervalsByStage))fail(archetype.id+' Expedition');
    for(const [buildingId,value]of Object.entries(archetype.idleState.family))if(!exactKeys(value,['rollCarryMs','carryContext','nextRollOrdinal','shardDrought'])||!integer(value.rollCarryMs)||value.rollCarryMs>=c.familyRollIntervalMs||!exactKeys(value.carryContext,['assignedFamilyId','buildingLevel'])||(value.carryContext.assignedFamilyId!==null&&!fa.includes(value.carryContext.assignedFamilyId))||!integer(value.carryContext.buildingLevel)||value.carryContext.buildingLevel<1||value.carryContext.buildingLevel>archetype.buildingLevels[buildingId]||!integer(value.nextRollOrdinal)||!integer(value.shardDrought)||value.shardDrought>=c.familyPityForceAt)fail(archetype.id+' Family idle '+buildingId);
  }
  for(const horizon of sim.horizons)if(!exactKeys(horizon,['id','hours'])||!integer(horizon.hours)||horizon.hours>sim.safety.maxHorizonHours)fail('horizon '+horizon.id);
  if(!exactKeys(sim.live,['runnerRowIds','realmRowIds','viewports','motionModes','getAllowlist'])||sim.live.viewports.length!==2||sim.live.motionModes.length!==2||sim.live.runnerRowIds.length!==4||new Set(sim.live.runnerRowIds).size!==4||sim.live.realmRowIds.length!==40||new Set(sim.live.realmRowIds).size!==40||!Array.isArray(sim.live.getAllowlist)||new Set(sim.live.getAllowlist).size!==sim.live.getAllowlist.length||rawSha(sim.live)!==RAW_AUTHORITIES.live)fail('live registry');
  if(walkNumbers(sim).some(item=>!finite(item.value)))fail('negative/nonfinite input');
  return deepFreeze(clone(sim));
}

export function buildCanonicalInput(scenarios,configId,archetypeId,horizonId){
  const sim=validateScenarioRegistry(scenarios),config=sim.configs.find(item=>item.id===configId),archetype=sim.archetypes.find(item=>item.id===archetypeId),horizon=sim.horizons.find(item=>item.id===horizonId);
  if(!config||!archetype||!horizon)fail('unknown bundle '+configId+'/'+archetypeId+'/'+horizonId);
  return deepFreeze({simulatorVersion:sim.simulatorVersion,scenarioFormatVersion:sim.scenarioFormatVersion,identities:{contractBase:CONTRACT_BASE,artifactSha256:ARTIFACT_SHA,scenarioIdentity:sha(sim),releasedConstantsIdentity:sha(sim.releasedConstants),referenceModelIdentity:REFERENCE_MODEL_ID,policyIdentity:sha(sim.policy)},config:clone(config),archetype:clone(archetype),horizon:clone(horizon),fixedStartAt:sim.fixedStartAt,timeZone:sim.timeZone,saveId:sim.saveId,oathBoosts:clone(sim.oathBoosts),policy:clone(sim.policy),safety:clone(sim.safety),releasedConstants:clone(sim.releasedConstants),fellowCampaignStages:clone(sim.fellowCampaignStages),companionCampaignStages:clone(sim.companionCampaignStages)});
}
const INPUT_KEYS=['simulatorVersion','scenarioFormatVersion','identities','config','archetype','horizon','fixedStartAt','timeZone','saveId','oathBoosts','policy','safety','releasedConstants','fellowCampaignStages','companionCampaignStages'];
export function validateInput(input){
  if(!exactKeys(input,INPUT_KEYS)||input.simulatorVersion!==3||input.scenarioFormatVersion!==4||input.fixedStartAt!==1788026400000||input.timeZone!=='America/Phoenix'||input.saveId!=='phase-10b-reviewed-save')fail('canonical input shape/version/time');
  if(!exactKeys(input.identities,['contractBase','artifactSha256','scenarioIdentity','releasedConstantsIdentity','referenceModelIdentity','policyIdentity'])||input.identities.artifactSha256!==ARTIFACT_SHA||input.identities.contractBase!==CONTRACT_BASE||input.identities.scenarioIdentity!=='e7298080d94ca24955be460fb2b7c39d2644d57e71d0c3e0ec97b178b0992e91'||input.identities.releasedConstantsIdentity!=='3dc83cd45e16c23f0a7d041ee3e2d92bdbfa59243f8b3ef47819d1fe40675969'||input.identities.referenceModelIdentity!==REFERENCE_MODEL_ID||input.identities.policyIdentity!=='522a6a63d5b2996a7ca06518211f588391dadc00e02814fb30e9e7590778f2aa')fail('canonical input identities');
  const configHash=RAW_AUTHORITIES.configs[input.config&&input.config.id],archetypeHash=RAW_AUTHORITIES.archetypes[input.archetype&&input.archetype.id],horizonHash=RAW_AUTHORITIES.horizons[input.horizon&&input.horizon.id];
  if(!configHash||rawSha(input.config)!==configHash||!['released parity','advisory candidate'].includes(input.config.status)||(input.config.id==='released-schema10')!==(input.config.status==='released parity')||/(accept|promot|recommend|select|production)/i.test(input.config.label))fail('canonical config authority/status');
  if(!archetypeHash||rawSha(input.archetype)!==archetypeHash)fail('canonical archetype authority');
  if(!horizonHash||rawSha(input.horizon)!==horizonHash||!integer(input.horizon.hours)||input.horizon.hours>input.safety.maxHorizonHours)fail('canonical horizon authority');
  if(rawSha(input.oathBoosts)!==RAW_AUTHORITIES.oathBoosts||rawSha(input.policy)!==RAW_AUTHORITIES.policy||rawSha(input.safety)!==RAW_AUTHORITIES.safety||rawSha(input.releasedConstants)!==RAW_AUTHORITIES.releasedConstants||rawSha(input.fellowCampaignStages)!==RAW_AUTHORITIES.fellowCampaignStages||rawSha(input.companionCampaignStages)!==RAW_AUTHORITIES.companionCampaignStages)fail('canonical nested authority/order/value');
  if(sha(input.releasedConstants)!==input.identities.releasedConstantsIdentity||sha(input.policy)!==input.identities.policyIdentity)fail('canonical identity coherence');
  return deepFreeze(clone(input));
}


function familyAssignmentForBuilding(state,buildingId,c){
  const entry=Object.entries(state.family).find(([,member])=>member.assignedBuildingId===buildingId);
  if(!entry)return null;
  return{id:entry[0],...entry[1],specialty:c.familySpecialties[entry[0]]};
}
function familyBuildingComponents(member,buildingId,c){
  if(!member)return{familyId:null,baseBonus:0,intimacyBonus:0,rarityBonus:0,specialtyBonus:0,uncappedBonus:0,bonus:0,multiplier:1};
  const baseBonus=c.familyBuildingBase,intimacyBonus=Math.min(c.familyBuildingIntimacyCap,member.intimacy*c.familyBuildingIntimacyRate),rarityBonus=c.familyBuildingRarityRate*(member.rarity-1),specialtyBonus=member.specialty===buildingId?c.familyBuildingSpecialtyMatch:0,uncappedBonus=baseBonus+intimacyBonus+rarityBonus+specialtyBonus,bonus=Math.min(c.familyBuildingBonusCap,uncappedBonus);
  return{familyId:member.id,baseBonus,intimacyBonus,rarityBonus,specialtyBonus,uncappedBonus,bonus,multiplier:1+bonus};
}
function powerSnapshot(input,state){
  const c=input.releasedConstants,mastery=progress(state.masteryPoints,c.masteryThresholdFactor,c.masteryLevelCap,c.masteryPowerPerLevel,c.masteryPointsCap),might=progress(state.mightPoints,c.mightThresholdFactor,c.mightLevelCap,c.mightPowerPerLevel,c.mightPointsCap);
  const companionRows=c.companionIds.map(id=>{const member=state.companions[id],basePower=c.companionBasePower[id],levelMultiplier=1+c.companionLevelGrowth*(member.level-1),afterLevel=basePower*levelMultiplier,rarityMultiplier=1+c.companionRarityGrowth*(member.rarity-1),afterRarity=afterLevel*rarityMultiplier,unroundedPower=afterRarity*mastery.multiplier;return{id,owned:member.owned,exp:member.exp,level:member.level,rarity:member.rarity,shards:member.shards,assignedFellowId:member.assignedFellowId,basePower,levelMultiplier,afterLevel,rarityMultiplier,afterRarity,mastery:clone(mastery),unroundedPower,effectivePower:Math.round(unroundedPower),ownedTerms:[id+':base',id+':level',id+':rarity',id+':mastery'],formulaOrder:['base','level','rarity','mastery','round']}});
  const fellowRows=c.fellowIds.map(id=>{const member=state.fellows[id],basePower=c.fellowBasePower[id],levelMultiplier=1+c.fellowLevelGrowth*(member.level-1),afterLevel=basePower*levelMultiplier,rarityMultiplier=1+c.fellowRarityGrowth*(member.rarity-1),afterRarity=afterLevel*rarityMultiplier,relic=member.equippedRelicId?relicComponents(member.equippedRelicId,state.relicInventory,c):{id:null,tier:0,sourceStageId:null,owned:false,level:0,bonusBps:0,multiplier:1,nextCost:null},afterRelic=afterRarity*relic.multiplier,assignedCompanion=companionRows.find(row=>row.assignedFellowId===id)||null,transferredPower=(assignedCompanion?assignedCompanion.unroundedPower:0)*c.companionTransferRate,links=c.fellowFamilyLinks[id].map(familyId=>{const family=state.family[familyId],intimacyBonus=Math.min(c.familyLinkedIntimacyCap,family.intimacy*c.familyLinkedIntimacyRate),rarityBonus=c.familyLinkedRarityRate*(family.rarity-1),bonus=Math.min(c.familyLinkedPerFamilyCap,intimacyBonus+rarityBonus);return{familyId,intimacy:family.intimacy,rarity:family.rarity,intimacyBonus,rarityBonus,bonus}}),familyUncappedBonus=sum(links.map(link=>link.bonus)),familyBonus=Math.min(c.familyLinkedAggregateCap,familyUncappedBonus),familyMultiplier=1+familyBonus,combatUnroundedPower=(afterRelic+transferredPower)*familyMultiplier*might.multiplier,economyUnroundedPower=afterRelic*might.multiplier;return{id,owned:member.owned,exp:member.exp,level:member.level,rarity:member.rarity,shards:member.shards,bond:member.bond,basePower,levelMultiplier,afterLevel,rarityMultiplier,afterRarity,relic,afterRelic,assignedCompanionId:assignedCompanion?assignedCompanion.id:null,companionUnroundedPower:assignedCompanion?assignedCompanion.unroundedPower:0,transferredPower,familyLinks:links,familyUncappedBonus,familyBonus,familyMultiplier,might:clone(might),combatUnroundedPower,combatEffectivePower:Math.round(combatUnroundedPower),economyUnroundedPower,economyPower:Math.round(economyUnroundedPower),economyOwnedTerms:[id+':base',id+':level',id+':rarity',id+':relic',id+':might'],economyExcludedTerms:['companionPowerTransfer','familyBondMultiplier'],combatFormulaOrder:['base','level','rarity','relic','companionTransfer','familyBond','might','round']}});
  const fellowEconomyPower=sum(fellowRows.map(row=>row.economyPower)),companionEconomyPower=sum(companionRows.map(row=>row.effectivePower)),fellowCombatPower=sum(fellowRows.map(row=>row.combatEffectivePower)),companionCombatPower=companionEconomyPower,fellowTerms=fellowRows.flatMap(row=>row.economyOwnedTerms),companionTerms=companionRows.flatMap(row=>row.ownedTerms),overlap=fellowTerms.filter(term=>companionTerms.includes(term)),noDoubleCountProof={fellowSumMatches:sum(fellowRows.map(row=>row.economyPower))===fellowEconomyPower,companionSumMatches:sum(companionRows.map(row=>row.effectivePower))===companionEconomyPower,termIdentityOverlap:overlap,companionTransferExcluded:fellowRows.every(row=>row.economyExcludedTerms.includes('companionPowerTransfer')&&!row.economyOwnedTerms.includes('companionPowerTransfer')),familyBondExcluded:fellowRows.every(row=>row.economyExcludedTerms.includes('familyBondMultiplier')&&!row.economyOwnedTerms.includes('familyBondMultiplier'))};
  noDoubleCountProof.disjoint=noDoubleCountProof.fellowSumMatches&&noDoubleCountProof.companionSumMatches&&overlap.length===0&&noDoubleCountProof.companionTransferExcluded&&noDoubleCountProof.familyBondExcluded;
  return{fellowRows,companionRows,fellowEconomyPower,companionEconomyPower,fellowCombatPower,companionCombatPower,fellowBonusBps:curveBps(fellowEconomyPower,input.config.fellowRosterCurve),companionBonusBps:curveBps(companionEconomyPower,input.config.companionRosterCurve),might,mastery,noDoubleCountProof};
}
function buildingRows(input,state,powerState,at){
  const c=input.releasedConstants,startDay=dayKey(input.fixedStartAt);
  return c.buildingIds.map(id=>{const level=state.buildingLevels[id],base=c.buildingBaseRates[id],levelMultiplier=Math.pow(c.buildingLevelMultiplier,level-1),family=familyBuildingComponents(familyAssignmentForBuilding(state,id,c),id,c),fellowRosterMultiplier=1+powerState.fellowBonusBps/10000,companionRosterMultiplier=1+powerState.companionBonusBps/10000,overallDayMultiplier=1,oathBoost=dayKey(at)===startDay?Math.min(c.oathDailyCap,input.oathBoosts[id]):0,oathMultiplier=1+oathBoost,componentSequence=['base','levelMultiplier','familyAssignmentMultiplier','fellowRosterMultiplier','companionRosterMultiplier','overallDayMultiplier','oathMultiplier'],familyApplicationCount=componentSequence.filter(component=>component==='familyAssignmentMultiplier').length,rate=base*levelMultiplier*family.multiplier*fellowRosterMultiplier*companionRosterMultiplier*overallDayMultiplier*oathMultiplier;return{id,level,base,levelMultiplier,family,fellowRosterBonusBps:powerState.fellowBonusBps,fellowRosterMultiplier,companionRosterBonusBps:powerState.companionBonusBps,companionRosterMultiplier,overallDayMultiplier,oathBoost,oathMultiplier,componentSequence,familyApplicationCount,rate,capped24HourOutput:rate*24,nextUpgradeCost:upgradeCost(level,input)}});
}
function settleLane(lane,at,progressValue,c,laneName){
  const key=laneName==='tower'?'floor':'stage',cap=laneName==='tower'?c.towerElapsedCapMs:c.expeditionElapsedCapMs,interval=laneName==='tower'?c.towerIntervalMs:c.expeditionIntervalMs,before={cursorAt:lane.cursorAt,segments:clone(lane.segments)},elapsed=Math.max(0,at-lane.cursorAt),occupied=sum(lane.segments.map(segment=>segment.elapsedMs)),accepted=progressValue===0?0:Math.min(elapsed,Math.max(0,cap-occupied)),discarded=elapsed-accepted;
  if(accepted>0){const last=lane.segments.at(-1);if(last&&last[key]===progressValue)last.elapsedMs+=accepted;else lane.segments.push({[key]:progressValue,elapsedMs:accepted})}
  lane.cursorAt=at;const counts=rewardMap(Array.from({length:50},(_,index)=>String(index+1)));let intervals=0,consumedElapsedMs=0;
  while(sum(lane.segments.map(segment=>segment.elapsedMs))>=interval){const earned=lane.segments[0][key];let remaining=interval;while(remaining>0){const take=Math.min(remaining,lane.segments[0].elapsedMs);lane.segments[0].elapsedMs-=take;remaining-=take;if(lane.segments[0].elapsedMs===0)lane.segments.shift()}counts[String(earned)]++;intervals++;consumedElapsedMs+=interval}
  return{before,settlement:{at,progress:progressValue,nominalElapsedMs:elapsed,acceptedElapsedMs:accepted,cappedDiscardedMs:discarded,capMs:cap,occupiedBeforeMs:occupied,occupiedAfterSettlementMs:occupied+accepted},consumption:{intervalMs:interval,intervals,consumedElapsedMs,counts},after:{cursorAt:lane.cursorAt,segments:clone(lane.segments),partialCarryMs:sum(lane.segments.map(segment=>segment.elapsedMs))}};
}
function applyLaneRewards(input,state,laneName,settled,awards){
  const c=input.releasedConstants,lane=state.idleState[laneName],rows=[];
  for(const [progressKey,count]of Object.entries(settled.consumption.counts)){const progressValue=Number(progressKey);for(let index=0;index<count;index++){const ordinal=lane.intervalOrdinal,forceAt=laneName==='tower'?c.towerPityForceAt:c.expeditionPityForceAt,forced=lane.pityMisses===forceAt-1,chance=laneName==='tower'?Math.min(.30,.08+.005*(progressValue-1)):Math.min(.30,.08+.02*(progressValue-1)),hit=forced||stableUnit(input.saveId,(laneName==='tower'?'floor-':'stage-')+progressValue,ordinal,laneName==='tower'?c.stableSalts.towerHit:c.stableSalts.expeditionHit)<chance;let recipient=null,nominal=0,accepted=0;
    if(laneName==='tower'){
      for(const id of c.companionIds){const amount=20+2*progressValue;state.companions[id].exp=addSafe(state.companions[id].exp,amount,id+' Tower EXP');state.companions[id].level=levelForExp(state.companions[id].exp,c.companionExpBase,c.companionExpGrowth,c.companionLevelCap);awards.companionExp[id]+=amount}
      nominal=1+Math.floor((progressValue-1)/10);accepted=Math.min(nominal,c.masteryPointsCap-state.masteryPoints);state.masteryPoints+=accepted;awards.mastery+=accepted;
      if(hit){const unit=stableUnit(input.saveId,'floor-'+progressValue,ordinal,c.stableSalts.towerRecipient);recipient=c.companionIds[Math.min(c.companionIds.length-1,Math.floor(unit*c.companionIds.length))];state.companions[recipient].shards=addSafe(state.companions[recipient].shards,1,recipient+' Tower shard');awards.companionShards[recipient]++;lane.pityMisses=0}else lane.pityMisses++;
    }else{
      nominal=1+Math.floor((progressValue-1)/2);accepted=Math.min(nominal,c.mightPointsCap-state.mightPoints);state.mightPoints+=accepted;awards.might+=accepted;
      if(hit){const owned=c.fellowIds.filter(id=>state.fellows[id].owned),unit=stableUnit(input.saveId,'stage-'+progressValue,ordinal,c.stableSalts.expeditionRecipient);recipient=owned[Math.min(owned.length-1,Math.floor(unit*owned.length))];state.fellows[recipient].shards=addSafe(state.fellows[recipient].shards,1,recipient+' Expedition shard');awards.fellowShards[recipient]++;lane.pityMisses=0}else lane.pityMisses++;
    }
    lane.intervalOrdinal++;if(laneName==='tower')lane.claimedIntervalsByFloor[progressKey]++;else lane.claimedIntervalsByStage[progressKey]++;rows.push({progress:progressValue,ordinal,forced,chance,hit,recipient,nominalProgress:nominal,acceptedProgress:accepted,pityAfter:lane.pityMisses});
  }}
  if(settled.consumption.intervals>0)lane.claimOrdinal++;return rows;
}
function familyCurrentContext(state,buildingId){const entry=Object.entries(state.family).find(([,member])=>member.assignedBuildingId===buildingId);return{assignedFamilyId:entry?entry[0]:null,buildingLevel:state.buildingLevels[buildingId]}}
function familyRecipient(input,buildingId,ordinal,assignedId){const c=input.releasedConstants,unit=stableUnit(input.saveId,buildingId,ordinal,c.stableSalts.familyRecipient);if(!assignedId)return c.familyIds[Math.min(c.familyIds.length-1,Math.floor(unit*c.familyIds.length))];if(unit<c.familyAssignedWeight)return assignedId;const others=c.familyIds.filter(id=>id!==assignedId),scaled=(unit-c.familyAssignedWeight)/(1-c.familyAssignedWeight);return others[Math.min(others.length-1,Math.floor(scaled*others.length))]}
function settleFamily(input,state,durationMs,awards){
  const c=input.releasedConstants,byBuilding={};
  for(const buildingId of c.buildingIds){const lane=state.idleState.family[buildingId],before=clone(lane),currentContext=familyCurrentContext(state,buildingId),total=lane.rollCarryMs+durationMs,count=Math.min(input.safety.maxFamilyRolls,Math.floor(total/c.familyRollIntervalMs)),rolls=[];let gifts=0,priorContextUsed=false;
    for(let index=0;index<count;index++){const context=!priorContextUsed&&before.rollCarryMs>0?before.carryContext:currentContext;priorContextUsed=true;const ordinal=lane.nextRollOrdinal,forced=lane.shardDrought===c.familyPityForceAt-1,chance=Math.min(c.familyShardChanceCap,c.familyShardChanceBase+c.familyShardChancePerLevel*(context.buildingLevel-1)),hit=forced||stableUnit(input.saveId,buildingId,ordinal,c.stableSalts.familyHit)<chance;let recipient=null;if(hit){recipient=familyRecipient(input,buildingId,ordinal,context.assignedFamilyId);state.family[recipient].shards=addSafe(state.family[recipient].shards,1,recipient+' Family shard');awards.familyShards[recipient]++;lane.shardDrought=0}else lane.shardDrought++;const gift=buildingId==='hearth'&&stableUnit(input.saveId,buildingId,ordinal,c.stableSalts.familyGift)<c.hearthGiftChance?1:0;if(gift){state.gifts=addSafe(state.gifts,gift,'Gifts');awards.gifts+=gift;gifts+=gift}lane.nextRollOrdinal++;rolls.push({ordinal,context:clone(context),forced,chance,hit,recipient,gift,pityAfter:lane.shardDrought})}
    lane.rollCarryMs=total-count*c.familyRollIntervalMs;lane.carryContext=clone(currentContext);byBuilding[buildingId]={before,currentContext,nominalElapsedMs:durationMs,intervalMs:c.familyRollIntervalMs,rollCount:count,rolls,gifts,after:clone(lane),carryProvenancePreserved:before.rollCarryMs===0||rolls.length===0||same(rolls[0].context,before.carryContext)};
  }
  return{byBuilding,totalRolls:sum(Object.values(byBuilding).map(row=>row.rollCount)),gifts:sum(Object.values(byBuilding).map(row=>row.gifts)),goldGenerated:0};
}
