(() => {
  'use strict';
  const CHANNEL = 'everstead-gate-0b';
  const byId = id => document.getElementById(id);
  const escapeHtml = value => String(value).replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  const inlineJson = value => JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  const bytesToHex = bytes => [...new Uint8Array(bytes)].map(value => value.toString(16).padStart(2,'0')).join('');
  const sha256 = async bytes => bytesToHex(await crypto.subtle.digest('SHA-256', bytes));
  async function fetchBytes(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return new Uint8Array(await response.arrayBuffer())}
  const decode = bytes => new TextDecoder('utf-8',{fatal:true}).decode(bytes);
  const result = (id,pass,detail='') => ({id,pass:Boolean(pass),detail:String(detail)});

  function realmSuite(config) {
    const results=[];
    const add=(id,pass,detail='')=>results.push({id,pass:Boolean(pass),detail:String(detail)});
    const clone=value=>JSON.parse(JSON.stringify(value));
    const wait=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
    const activeKey=config.keys.active,backupKey=config.keys.backup,stagingKey=config.keys.staging;
    const NativeDate=Date,offsetMilliseconds=config.timezoneOffsetMinutes*60000;
    async function waitFor(condition,{timeoutMs=1000,pollMs=10}={}){const deadline=NativeDate.now()+timeoutMs;while(NativeDate.now()<deadline){if(condition())return true;await wait(pollMs)}return Boolean(condition())}
    class FixedDate extends NativeDate{constructor(...args){if(args.length===0)super(config.now);else if(args.length===1)super(args[0]);else{const[y,m,d=1,h=0,mi=0,s=0,ms=0]=args;super(NativeDate.UTC(y,m,d,h,mi,s,ms)+offsetMilliseconds)}}static now(){return config.now}static parse(value){return NativeDate.parse(value)}static UTC(...args){return NativeDate.UTC(...args)}_shifted(){return new NativeDate(this.getTime()-offsetMilliseconds)}getFullYear(){return this._shifted().getUTCFullYear()}getMonth(){return this._shifted().getUTCMonth()}getDate(){return this._shifted().getUTCDate()}getDay(){return this._shifted().getUTCDay()}getHours(){return this._shifted().getUTCHours()}getMinutes(){return this._shifted().getUTCMinutes()}getTimezoneOffset(){return config.timezoneOffsetMinutes}setDate(value){const shifted=this._shifted(),next=NativeDate.UTC(shifted.getUTCFullYear(),shifted.getUTCMonth(),value,shifted.getUTCHours(),shifted.getUTCMinutes(),shifted.getUTCSeconds(),shifted.getUTCMilliseconds())+offsetMilliseconds;return this.setTime(next)}}
    window.Date=FixedDate;window.confirm=()=>true;
    function rawIdentity(raw){if(raw==null)return'null:0:00000000';let hash=2166136261;for(let i=0;i<raw.length;i++){hash^=raw.charCodeAt(i);hash=Math.imul(hash,16777619)}return`fnv1a32:${raw.length}:${(hash>>>0).toString(16).padStart(8,'0')}`}
    function fixture(id){if(id==null)return null;if(config.raws[id]!=null)return config.raws[id];if(id==='current-undo-ready')return config.raws['current-v1'];if(id==='current-unknown-fields'){const state=JSON.parse(config.raws['current-v1']);state.expansionState={chapter:'future-one',flags:['alpha','beta']};state.ui.experimentalPanel='ledger';state.buildings.training.craftingQueue=[{recipe:'future-ingot',count:2}];state.oaths[0].futureReward={currency:'starlight',amount:7};return JSON.stringify(state)}if(['current-offline-2h','current-offline-24h','current-offline-30h'].includes(id)){const state=JSON.parse(config.raws['current-v1']),hours=id.endsWith('2h')?2:id.endsWith('24h')?24:30;state.pendingGold=0;state.lastGoldAt=config.now-hours*3600000;state.lastSeen=state.lastGoldAt;return JSON.stringify(state)}if(id==='staging-successor-for-corrupt'){const state=JSON.parse(config.raws['current-v1']);return JSON.stringify({stagingVersion:1,transactionId:'tx-corrupt-recovery',baseSaveId:null,baseRevision:null,sourceRawIdentity:rawIdentity(config.raws['corrupt-json']),source:'fixture-corrupt-recovery',state})}throw new Error(`Unknown fixture ${id}`)}
    function current(raw){try{const value=JSON.parse(raw);return value?.schemaVersion===1&&Number.isInteger(value?.saveMeta?.revision)?value:null}catch{return null}}
    function resetDom(){document.querySelector('#app').innerHTML='';document.querySelector('#overlay').innerHTML='';document.querySelector('#toast').innerHTML=''}
    function makeTest(slots,plan,seed){
      let saveIndex=seed,txIndex=seed;
      const operationLog=[],status={};
      return{storage:{get length(){return slots.size},clear(){slots.clear()},getItem(key){return slots.get(String(key))??null},key(index){return[...slots.keys()][index]??null},removeItem(key){slots.delete(String(key))},setItem(key,value){slots.set(String(key),String(value))}},operationLog,status,faultPlan:plan,idFactory:()=>`save-gate-0b-${++saveIndex}`,transactionIdFactory:()=>`tx-gate-0b-${++txIndex}`,fault(context){
        if(!plan?.enabled||plan.used||context.step!==plan.step||context.phase!==plan.phase)return null;
        plan.matches+=1;if(plan.matches!==(plan.occurrence??1))return null;plan.used=true;
        if(plan.type==='foreign-staging'){let foreign;try{foreign=JSON.parse(slots.get(stagingKey)??'{}')}catch{foreign={}}foreign.stagingVersion??=1;foreign.transactionId='tx-foreign-later';foreign.source='foreign-tab';plan.foreignRaw=JSON.stringify(foreign);slots.set(stagingKey,plan.foreignRaw);return null}
        return plan.type==='mismatch'?{type:'mismatch',value:`${context.value??''}__fault_mismatch__`}:{type:'throw',message:`fault ${plan.phase} ${plan.step}`}
      }}
    }
    async function boot(input,slots=null,seed=0){resetDom();const memory=slots||new Map();if(!slots){if(input.active!=null)memory.set(activeKey,fixture(input.active));if(input.backup!=null)memory.set(backupKey,fixture(input.backup));if(input.staging!=null)memory.set(stagingKey,fixture(input.staging))}const plan=input.faultPlan?{...input.faultPlan,enabled:input.faultPlan.enabled!==false,used:false,matches:0}:null,test=makeTest(memory,plan,seed);window.__EVERSTEAD_PERSISTENCE_TEST__=test;let error=null;try{window.eval(config.productionScript)}catch(caught){error=caught}await wait(30);return{slots:memory,test,plan,error}}
    const scenarioStates={};
    async function runScenario(scenario){
      let run=await boot(scenario);for(let repeat=1;repeat<(scenario.repeatBoots||1);repeat++)run=await boot({},run.slots,repeat*10);
      let beforeAction=null,afterCompletion=null,afterCollect=null,afterSameField=null,rawBeforeRefusal=null,deleteData=null,gameplay=null,externalRaw=null,offlineReady=null;
      if(scenario.id.startsWith('current-offline-'))offlineReady=await waitFor(()=>Boolean(document.querySelector('#overlay .offline-list')));
      if(scenario.action==='recover'||scenario.action==='safe-reset'){document.querySelector(`[data-persistence-act="${scenario.action}"]`)?.click();await wait(20)}
      if(scenario.action==='scoped-undo'){beforeAction=clone(current(run.slots.get(activeKey)));document.querySelector('[data-nav="oaths"]')?.click();document.querySelector('[data-oath="o1"]')?.click();afterCompletion=clone(current(run.slots.get(activeKey)));document.querySelector('#app [data-act="collect"]')?.click();afterCollect=clone(current(run.slots.get(activeKey)));document.querySelector('[data-modal-act="undo-oath"]')?.click();await wait(20)}
      if(scenario.action==='scoped-undo-diverged'){beforeAction=clone(current(run.slots.get(activeKey)));document.querySelector('[data-nav="oaths"]')?.click();document.querySelector('[data-oath="o1"]')?.click();afterCompletion=clone(current(run.slots.get(activeKey)));document.querySelector('[data-modal-close]')?.click();document.querySelector('[data-nav="village"]')?.click();document.querySelector('[data-act="patrol"]')?.click();document.querySelector('[data-patrol-choice]')?.click();afterSameField=clone(current(run.slots.get(activeKey)));rawBeforeRefusal=run.slots.get(activeKey);document.querySelector('[data-nav="oaths"]')?.click();document.querySelector('[data-oath="o1"]')?.click();await wait(20)}
      if(scenario.action==='delete-oath-with-undo'){document.querySelector('[data-nav="oaths"]')?.click();document.querySelector('[data-oath="o1"]')?.click();const completed=clone(current(run.slots.get(activeKey)));document.querySelector('[data-modal-close]')?.click();document.querySelector('[data-nav="oaths"]')?.click();document.querySelector('[data-edit-oath="o1"]')?.click();document.querySelector('[data-delete-oath="o1"]')?.click();await wait(20);deleteData={completed}}
      if(scenario.action==='gameplay-regressions'){const navigation=[];for(const view of['village','oaths','fellows','adventure','more']){document.querySelector(`[data-nav="${view}"]`)?.click();navigation.push(Boolean(document.querySelector(`[data-nav="${view}"].on`)))}document.querySelector('[data-nav="fellows"]')?.click();const roster={};for(const tab of['fellows','family','companions']){document.querySelector(`[data-roster="${tab}"]`)?.click();roster[tab]=document.querySelectorAll('.char-card').length}document.querySelector('[data-nav="village"]')?.click();const before=clone(current(run.slots.get(activeKey)));document.querySelector('[data-building="training"]')?.click();const modalOpen=Boolean(document.querySelector('[data-modal-act="upgrade-building"]'));document.querySelector('[data-modal-act="upgrade-building"]')?.click();const after=clone(current(run.slots.get(activeKey)));gameplay={navigation,roster,before,after,modalOpen}}
      if(scenario.action==='unknown-field-mutation')document.querySelector('[data-nav="more"]')?.click();
      if(scenario.action==='precommit-raw-conflict'){const external=JSON.parse(run.slots.get(activeKey));external.concurrentMarker='external-write';externalRaw=JSON.stringify(external);run.slots.set(activeKey,externalRaw);document.querySelector('[data-nav="more"]')?.click();await wait(20)}
      if(scenario.action==='fail-navigation'){beforeAction=clone(current(run.slots.get(activeKey)));run.plan.enabled=true;document.querySelector('[data-nav="more"]')?.click();await wait(20)}
      const activeRaw=run.slots.get(activeKey)??null,backupRaw=run.slots.get(backupKey)??null,stagingRaw=run.slots.get(stagingKey)??null,active=current(activeRaw),outcome=run.test.status.outcome,foreignStagingScenario=scenario.id==='foreign-staging-before-commit-cleanup'||scenario.id==='foreign-staging-before-recovery-cleanup';if(active)scenarioStates[scenario.id]=active;
      add(`${scenario.id}-no-uncaught`,!run.error,run.error?.stack||'');add(`${scenario.id}-outcome`,outcome===scenario.expectedOutcome,outcome);
      if(scenario.expectedOutcome==='REJECT_PRESERVE'&&!scenario.action&&!foreignStagingScenario){add(`${scenario.id}-active-preserved`,activeRaw===fixture(scenario.active));add(`${scenario.id}-backup-exact`,backupRaw===fixture(scenario.backup??scenario.active));add(`${scenario.id}-recovery-render`,document.querySelector('#app').textContent.includes('Save Needs Attention'))}else if(scenario.expectedOutcome!=='REJECT_PRESERVE'){add(`${scenario.id}-current-active`,Boolean(active));if(!foreignStagingScenario)add(`${scenario.id}-staging-clean`,stagingRaw==null)}
      if(scenario.id==='legacy-representative'){add('legacy-backup-exact',backupRaw===fixture('legacy-representative'));add('legacy-receipt-once',active?.saveMeta.appliedMigrations.length===1&&active.saveMeta.appliedMigrations[0].id==='legacy-v0.1-to-1');add('legacy-undo-versioned',active?.undo?.version===1&&active.undo?.snapshot==null&&active.undo?.expected);add('legacy-unicode-preserved',active?.oaths.find(o=>o.id==='fixture-custom')?.title==='Fixture café review 🌵')}
      if(scenario.id==='legacy-mismatched-backup-preserve')add('legacy-mismatched-backup-no-active-write',!run.test.operationLog.some(entry=>entry.step==='active-write'&&entry.status==='begin'));
      if(scenario.id==='twice-migrated')add('twice-migrated-idempotent',active?.saveMeta.appliedMigrations.length===1);
      if(scenario.id==='current-mismatched-backup')add('mismatched-backup-preserved',backupRaw===fixture('legacy-representative'));
      if(scenario.id==='staged-successor')add('staged-successor-promoted',active?.gold===JSON.parse(fixture('current-v1')).gold+777);
      if(['staged-stale','staged-conflicting-save','staged-invalid-state'].includes(scenario.id))add(`${scenario.id}-current-precedence`,active?.gold===JSON.parse(fixture('current-v1')).gold);
      if(scenario.id==='corrupt-safe-reset')add('safe-reset-backup-retained',backupRaw===fixture('corrupt-json'));
      if(['corrupt-backup-recovery','corrupt-safe-reset-mismatched-backup','invalid-safe-reset-mismatched-backup'].includes(scenario.id)){add(`${scenario.id}-active-preserved`,activeRaw===fixture(scenario.active));add(`${scenario.id}-backup-preserved`,backupRaw===fixture(scenario.backup));add(`${scenario.id}-no-active-write`,!run.test.operationLog.some(entry=>entry.step==='active-write'&&entry.status==='begin'));add(`${scenario.id}-recovery-remains`,document.querySelector('#app').textContent.includes('Save Needs Attention'))}
      if(scenario.id==='scoped-oath-undo'){const final=current(activeRaw),beforeOath=beforeAction.oaths.find(o=>o.id==='o1'),finalOath=final.oaths.find(o=>o.id==='o1');add('scoped-undo-restores-oath',beforeOath.doneKey===finalOath.doneKey&&beforeOath.streak===finalOath.streak);add('scoped-undo-preserves-unrelated-gold',final.gold===afterCollect.gold&&final.gold>beforeAction.gold);add('scoped-undo-keeps-newer-revision',final.saveMeta.revision>afterCollect.saveMeta.revision);add('scoped-undo-clears-inverse',final.undo===null)}
      if(scenario.id==='scoped-oath-undo-diverged'){const final=current(activeRaw),completedOath=afterCompletion.oaths.find(o=>o.id==='o1'),finalOath=final.oaths.find(o=>o.id==='o1');add('scoped-undo-diverged-same-field-changed',afterSameField.prosperity>afterCompletion.prosperity);add('scoped-undo-diverged-refuses-without-write',activeRaw===rawBeforeRefusal&&final.saveMeta.revision===afterSameField.saveMeta.revision);add('scoped-undo-diverged-keeps-completion',finalOath.doneKey===completedOath.doneKey&&finalOath.streak===completedOath.streak);add('scoped-undo-diverged-keeps-record',final.undo?.oathId==='o1');add('scoped-undo-diverged-not-blocked',outcome==='NORMAL'&&!document.querySelector('#app').textContent.includes('Save Needs Attention'));add('scoped-undo-diverged-explains-refusal',document.querySelector('#toast').textContent.includes('Undo refused'))}
      if(scenario.id==='delete-oath-clears-undo'){add('delete-oath-created-targeted-undo',deleteData.completed.undo?.oathId==='o1');add('delete-oath-target-removed',!active.oaths.some(o=>o.id==='o1'));add('delete-oath-undo-cleared',active.undo===null);add('delete-oath-valid-committed-save',Boolean(active)&&!document.querySelector('#app').textContent.includes('Save Needs Attention'))}
      if(foreignStagingScenario){add(`${scenario.id}-fault-triggered`,run.plan?.used===true);add(`${scenario.id}-foreign-staging-retained`,stagingRaw===run.plan?.foreignRaw&&JSON.parse(stagingRaw).transactionId==='tx-foreign-later');const logStep=scenario.id.includes('recovery')?'recovery-staging-cleanup-foreign':'staging-cleanup-foreign',foreignIndex=run.test.operationLog.findIndex(entry=>entry.step===logStep&&entry.operation==='retain');add(`${scenario.id}-retention-logged`,foreignIndex>=0);add(`${scenario.id}-no-later-staging-overwrite`,!run.test.operationLog.slice(foreignIndex+1).some(entry=>entry.step==='staging-write'&&entry.status==='begin'));add(`${scenario.id}-valid-active-recovery-screen`,Boolean(active)&&document.querySelector('#app').textContent.includes('Save Needs Attention'))}
      if(scenario.id==='gameplay-regressions'){add('gameplay-navigation',gameplay.navigation.every(Boolean));add('gameplay-roster-counts',gameplay.roster.fellows===6&&gameplay.roster.family===3&&gameplay.roster.companions===2);add('gameplay-building-modal',gameplay.modalOpen);add('gameplay-building-upgrade',gameplay.after.buildings.training.level===gameplay.before.buildings.training.level+1&&gameplay.after.gold===gameplay.before.gold-Math.round(15000*Math.pow(1.7,gameplay.before.buildings.training.level-1)))}
      if(scenario.id==='unknown-fields-preserved'){add('unknown-root-field-preserved',active?.expansionState?.chapter==='future-one'&&active.expansionState.flags?.join(',')==='alpha,beta');add('unknown-nested-fields-preserved',active?.ui?.experimentalPanel==='ledger'&&active?.buildings?.training?.craftingQueue?.[0]?.recipe==='future-ingot'&&active?.oaths?.[0]?.futureReward?.amount===7)}
      if(scenario.id==='precommit-raw-conflict'){add('precommit-conflict-preserves-external',activeRaw===externalRaw);add('precommit-conflict-recovery-ui',document.querySelector('#app').textContent.includes('Save Needs Attention'))}
      if(scenario.id==='current-offline-2h')add('offline-2h-summary',active.pendingGold>0&&offlineReady);
      if(scenario.id==='mutation-write-failure'){const final=current(activeRaw);add('failed-mutation-not-adopted',!final||final.ui.view===beforeAction.ui.view);add('failed-mutation-recovery-ui',document.querySelector('#app').textContent.includes('Save Needs Attention'))}
    }
    async function runFault(faultCase,index){const scenario={active:'legacy-representative',faultPlan:faultCase},run=await boot(scenario,null,1000+index),activeRaw=run.slots.get(activeKey)??null,backupRaw=run.slots.get(backupKey)??null,stagingRaw=run.slots.get(stagingKey)??null,active=current(activeRaw),id=`fault-${faultCase.step}-${faultCase.phase}-${faultCase.type}`;add(`${id}-triggered`,run.plan.used);add(`${id}-caught`,!run.error,run.error?.stack||'');if(faultCase.commitExpected){add(`${id}-commit-valid`,Boolean(active));add(`${id}-backup-exact`,backupRaw===fixture('legacy-representative'))}else{add(`${id}-recoverable`,activeRaw===fixture('legacy-representative')||Boolean(active));if(active)add(`${id}-changed-active-backed-up`,backupRaw===fixture('legacy-representative'))}const logged=faultCase.type==='foreign-staging'?run.test.operationLog.some(entry=>entry.step==='staging-cleanup-foreign'&&entry.operation==='retain'):run.test.operationLog.some(entry=>entry.step===faultCase.step&&['error','mismatch'].includes(entry.status));add(`${id}-logged`,logged);if(faultCase.foreignStagingExpected)add(`${id}-foreign-staging-retained`,stagingRaw===run.plan.foreignRaw&&JSON.parse(stagingRaw).transactionId==='tx-foreign-later')}
    (async()=>{for(const scenario of config.scenarios)await runScenario(scenario);add('offline-24h-cap',Math.abs(scenarioStates['current-offline-24h'].pendingGold-scenarioStates['current-offline-30h'].pendingGold)<1e-7);for(let index=0;index<config.faultMatrix.length;index++)await runFault(config.faultMatrix[index],index);parent.postMessage({channel:'everstead-gate-0b',nonce:config.nonce,results},'*')})().catch(error=>parent.postMessage({channel:'everstead-gate-0b',nonce:config.nonce,results:[...results,{id:'realm-fatal',pass:false,detail:error.stack||error.message}]},'*'));
  }

  async function loadContract(){const manifestBytes=await fetchBytes('./current-manifest.json'),manifest=JSON.parse(decode(manifestBytes)),scenarioBytes=await fetchBytes('../../'+manifest.scenarios.path);if(await sha256(scenarioBytes)!==manifest.scenarios.sha256)throw new Error('Scenario checksum mismatch');const scenarioData=JSON.parse(decode(scenarioBytes)),raws={},staticResults=[];for(const[path,expected]of Object.entries(manifest.historicalFiles||{})){const bytes=await fetchBytes('../../'+path),hash=await sha256(bytes);staticResults.push(result(`historical-${path.replaceAll('/','-')}`,hash===expected,hash))}for(const fixture of manifest.fixtures){const bytes=await fetchBytes('../../'+fixture.path),raw=decode(bytes),hash=await sha256(bytes),pass=hash===fixture.sha256&&bytes.byteLength===fixture.byteLength&&raw.length===fixture.codeUnitLength&&raw.endsWith('\n')===fixture.trailingNewline;staticResults.push(result(`fixture-${fixture.id}`,pass,hash));raws[fixture.id]=raw}raws['legacy-representative']=raws['representative-v0.1'];raws['legacy-sparse']=raws['sparse-v0.1'];raws['legacy-wrong-type']=raws['wrong-type-v0.1'];const artifactBytes=await fetchBytes('../../'+manifest.artifact.path),artifactHash=await sha256(artifactBytes);staticResults.push(result('current-artifact',artifactHash===manifest.artifact.sha256&&artifactBytes.byteLength===manifest.artifact.byteLength,artifactHash));const source=decode(artifactBytes),scriptMatch=source.match(/<script>([\s\S]*?)<\/script>/);if(!scriptMatch)throw new Error('Current artifact script missing');return{manifest,scenarioData,raws,source,productionScript:scriptMatch[1],staticResults}}
  function executeRealm(contract){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe');frame.setAttribute('sandbox','allow-scripts');frame.style.cssText='position:absolute;left:-10000px;top:0;width:390px;height:844px;border:0';const finish=(error,value)=>{clearTimeout(timeout);window.removeEventListener('message',onMessage);frame.remove();error?reject(error):resolve(value)},onMessage=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;finish(null,event.data.results)},timeout=setTimeout(()=>finish(new Error('Gate 0B realm timed out')),120000);window.addEventListener('message',onMessage);const config={nonce,now:Date.parse(contract.scenarioData.frozenNow),timezoneOffsetMinutes:contract.scenarioData.timezoneOffsetMinutes,keys:contract.scenarioData.storageKeys,scenarios:contract.scenarioData.scenarios,faultMatrix:contract.scenarioData.faultMatrix,raws:contract.raws,productionScript:contract.productionScript},suiteScript=`<script>(${realmSuite.toString()})(${inlineJson(config)})<\/script>`,fullScript=contract.source.match(/<script>[\s\S]*?<\/script>/)?.[0];frame.srcdoc=contract.source.replace(fullScript,()=>suiteScript);document.body.appendChild(frame)})}
  function render(results){const passed=results.filter(item=>item.pass).length,failed=results.length-passed;byId('total').textContent=results.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=results.map(item=>`<article class="result"><code>${escapeHtml(item.id)}</code><span>${escapeHtml(item.detail)}</span><b class="status ${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_GATE_0B_RESULT__={passed,failed,total:results.length,results}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const contract=await loadContract(),results=[...contract.staticResults,...await executeRealm(contract)];render(results)}catch(error){byId('fatal').textContent=error.stack||error.message;render([result('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
