import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
import {performance} from 'node:perf_hooks';
import {spawnSync} from 'node:child_process';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const CANDIDATE_ROOT=path.resolve(process.env.EVERSTEAD_V3_CANDIDATE_ROOT||ROOT);
const MODEL_ONLY=process.argv.includes('--model-only');
const read=(file,root=ROOT)=>fs.readFileSync(path.join(root,file),'utf8');
const clone=value=>JSON.parse(JSON.stringify(value));
const bytes=value=>Buffer.byteLength(JSON.stringify(value));
const sha256=value=>crypto.createHash('sha256').update(value).digest('hex');
const same=(left,right)=>JSON.stringify(left)===JSON.stringify(right);
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
const safeAdd=(left,right,label)=>{const value=left+right;assert(Number.isSafeInteger(value)&&value>=0,`${label} overflow`);return value};
const rawIdentity=raw=>{let hash=2166136261;for(let index=0;index<raw.length;index++){hash^=raw.charCodeAt(index);hash=Math.imul(hash,16777619)}return`fnv1a32:${raw.length}:${(hash>>>0).toString(16).padStart(8,'0')}`};
const identity=(label,saveId,value)=>rawIdentity(JSON.stringify([label,saveId,value]));

const FIXTURE=JSON.parse(read('qa/phase-20-21-five-year-archive/fixture-v3.json'));
let runtimeEvidence=null;
if(!MODEL_ONLY){
  assert(FIXTURE.candidate&&typeof FIXTURE.candidate.commit==='string','V3 candidate is not frozen; use --model-only while preparing the gate');
  const candidateHead=spawnSync('git',['rev-parse','HEAD'],{cwd:CANDIDATE_ROOT,encoding:'utf8',timeout:30000});
  assert(candidateHead.status===0&&candidateHead.stdout.trim()===FIXTURE.candidate.commit,`Candidate HEAD is ${candidateHead.stdout.trim()||'unavailable'}, expected frozen ${FIXTURE.candidate.commit}`);
  for(const [file,expected] of Object.entries(FIXTURE.candidate.sourceHashes)){const actual=sha256(read(file,CANDIDATE_ROOT));assert(actual===expected,`${file} is ${actual}, expected frozen ${expected}`)}
  const index=read('index.html',CANDIDATE_ROOT),runtimeVerifier=read('qa/phase-20-21-runtime/verify.mjs',CANDIDATE_ROOT),productionRealm=read('qa/phase-20-21-ui/realm.js',CANDIDATE_ROOT);
  for(const token of ['successorFoldCheckpoint','activationSequenceFloor','activationFoldedThrough','observedFoldedThrough','foldedClaimCountByFacilityId','latestFoldedReceiptByFacilityId','foldedSuccessorClaimCount','phase-20-21-canonical-claim-authority-v3','phase-20-21-successor-fold-checkpoint-v3','phase2021BuildClaimValidationContext','phase2021ValidateSuccessorClaimAuthoritiesIndexed','phase2021ObservedPhaseFifteenFold','phaseFifteenFoldArchiveBeforePhase2021','function phase2021FinalizeFacilityClaim(state,offer,plan,now)'])assert(index.includes(token),`Candidate is missing V3 token ${token}`);
  assert(!index.includes("'claimedReceiptSequenceRanges'"),'Candidate still declares V2 receipt range authority');
  for(const token of ['successorFoldCheckpoint','bounded-fold-high-water-anchor-and-authority-forgeries','bounded-checkpoint-interleaving-malformation-and-v2-rejection'])assert(runtimeVerifier.includes(token),`Focused runtime verifier is missing ${token}`);
  for(const token of ['actual-production-512-to-513-successor-fold','actual-production-predecessor-fold-advances-only-observed-through','actual-production-stale-fold-is-zero-storage-write-atomic','production-off-retains-no-successor-synthetic-state'])assert(productionRealm.includes(token),`Frozen production realm is missing ${token}`);
  const runtimeRun=spawnSync(process.execPath,['qa/phase-20-21-runtime/verify.mjs'],{cwd:CANDIDATE_ROOT,encoding:'utf8',timeout:180000,maxBuffer:16*1024*1024});
  assert(runtimeRun.status===0,`Focused V3 runtime verifier failed: ${runtimeRun.stderr||runtimeRun.stdout}`);
  for(const id of FIXTURE.candidate.requiredRuntimeChecks||[])assert(runtimeRun.stdout.includes(`PASS ${id}`),`Focused runtime verifier did not pass ${id}`);
  runtimeEvidence={outputSha256:sha256(runtimeRun.stdout),resultLine:runtimeRun.stdout.trim().split('\n').at(-1),requiredChecks:[...(FIXTURE.candidate.requiredRuntimeChecks||[])]};
  if(FIXTURE.candidate.runtimeVerifierOutputSha256)assert(runtimeEvidence.outputSha256===FIXTURE.candidate.runtimeVerifierOutputSha256,'Focused runtime verifier output changed');
}

const realm={};realm.globalThis=realm;vm.createContext(realm);
for(const file of ['src/phase15-facilities.js','src/phase20-21-facilities.js'])vm.runInContext(read(file,CANDIDATE_ROOT),realm,{filename:file});
const phase15=realm.EVERSTEAD_PHASE15_FACILITIES,phase2021=realm.EVERSTEAD_PHASE20_21_FACILITIES,facilities=phase2021.facilities;
assert(facilities.length===8,'Expected the fixed eight successor facilities');
assert(phase15.recentReceiptLimit===512&&phase15.foldBatchSize===128,'Phase 15 archive policy changed');

const SAVE_ID='save.phase20-21.longevity.bounded-v3.qa.v1',START_AT=Date.parse(FIXTURE.cadence.start),END_AT=Date.parse(FIXTURE.cadence.end),ANNIVERSARIES=FIXTURE.cadence.anniversaryDays,DAYS=ANNIVERSARIES.at(-1),ROUNDS=FIXTURE.cadence.successorClaimRoundsPerFacilityPerDay;
const EXPECTED_SUCCESSOR_CLAIMS=DAYS*ROUNDS*facilities.length,PRE_ACTIVATION_RECEIPTS=FIXTURE.cadence.preActivationPredecessorReceipts,PREDECESSOR_INTERVAL=FIXTURE.cadence.postActivationPredecessorReceiptEverySuccessorClaims,SOURCE_TYPE='opportunity.facility.activity',REWARD_KEY='reward-aggregate.gold.global';
const capacities=phase2021.syntheticPolicy.bankCapacityByFacility,domainVisitBudget=facilities.reduce((sum,item)=>sum+capacities[item.facilityId]+1,0),computedVisitBudget=phase15.recentReceiptLimit+facilities.length*4+domainVisitBudget;
assert(END_AT-START_AT===DAYS*86400000,'Fixture calendar span is invalid');
assert(EXPECTED_SUCCESSOR_CLAIMS>=FIXTURE.thresholds.minimumSuccessorClaims,'Cadence is below the frozen minimum');
assert(computedVisitBudget===FIXTURE.thresholds.validationVisitBudget,'Validation visit budget no longer equals fixed maps + recent window + bounded domain fragments');

function checkpointIdentity(row){const copy=clone(row);copy.identity='';return identity('phase-15-claim-archive-checkpoint-v1',SAVE_ID,copy)}
function receiptIdentity(row){const copy=clone(row);copy.identity='';return identity('phase-15-reward-receipt-v2',SAVE_ID,copy)}
function authorityIdentity(row){const copy=clone(row);copy.identity='';return identity('phase-20-21-canonical-claim-authority-v3',SAVE_ID,copy)}
function foldIdentity(row){const copy=clone(row);copy.identity='';return identity('phase-20-21-successor-fold-checkpoint-v3',SAVE_ID,copy)}
function emptyArchiveCheckpoint(){const row={throughSequence:0,receiptCount:0,aggregateRewards:{},sourceCountsByType:{},previousIdentity:null,identity:''};row.identity=checkpointIdentity(row);return row}
function rangeCount(ranges){let total=0,prior=0;for(const [start,end] of ranges){assert(Number.isSafeInteger(start)&&Number.isSafeInteger(end)&&start>=1&&end>=start,'Invalid domain range');assert(prior===0||start>prior+1,'Overlapping or adjacent domain ranges');total=safeAdd(total,end-start+1,'domain count');prior=end}return total}
function rangeHas(ranges,ordinal){return ranges.some(([start,end])=>ordinal>=start&&ordinal<=end)}
function rangeAdd(ranges,ordinal){assert(Number.isSafeInteger(ordinal)&&ordinal>=1&&!rangeHas(ranges,ordinal),'Duplicate/invalid domain ordinal');const values=[...clone(ranges),[ordinal,ordinal]].sort((left,right)=>left[0]-right[0]),result=[];for(const [start,end] of values){const tail=result.at(-1);if(tail&&start<=tail[1]+1)tail[1]=Math.max(tail[1],end);else result.push([start,end])}return result}

function successorReceipt(item,domainOrdinal,sequence,claimedAt){const amount=phase2021.syntheticPolicy.rewardGoldByFacility[item.facilityId],offerId=`reward.offer.facility.successor.${item.facilityId.slice(9)}.${domainOrdinal}.v2`,pendingIdentity=identity('reward-offer-v1',SAVE_ID,{offerId,sequence});const row={envelopeVersion:2,id:`reward.receipt.v2.${offerId.slice('reward.offer.'.length)}.${sequence}`,offerId,sourceType:SOURCE_TYPE,sourceId:item.activityId,facilityId:item.facilityId,domainOrdinal,definitionVersion:1,rewardPolicyVersion:1,claimedAt,sequence,pendingIdentity,rewards:[{kind:'gold',targetId:null,amount}],identity:''};row.identity=receiptIdentity(row);return row}
function predecessorReceipt(sequence,claimedAt,phase='pre'){const offerId=`reward.offer.story.longevity.${phase}.${sequence}`,row={envelopeVersion:2,id:`reward.receipt.v2.story.longevity.${phase}.${sequence}`,offerId,sourceType:'opportunity.story.reward',sourceId:`story.longevity.${phase}`,facilityId:null,domainOrdinal:null,definitionVersion:1,rewardPolicyVersion:1,claimedAt,sequence,pendingIdentity:identity('reward-offer-v1',SAVE_ID,{offerId,sequence}),rewards:[{kind:'gold',targetId:null,amount:1}],identity:''};row.identity=receiptIdentity(row);return row}

const state={saveMeta:{saveId:SAVE_ID,revision:0,updatedAt:START_AT,source:'phase20-21-bounded-v3-longevity-qa'},gold:0,phase15FacilityFoundation:{facilitiesById:Object.fromEntries(facilities.map(item=>[item.facilityId,{nextOrdinal:0,localProgress:0,claimedOrdinalRanges:[],pendingById:{}}])),pendingOffers:{},claimArchive:{configId:phase15.claimArchiveConfigId,nextSequence:0,recentReceipts:[],predecessorClaimedOfferIds:[],globalClaimedSourceIds:[],archiveCheckpoint:emptyArchiveCheckpoint()},successorClaimAuthorityByFacilityId:null,successorFoldCheckpoint:null}};
const archive=state.phase15FacilityFoundation.claimArchive;
let successorGold=0,successorClaims=0,foldCount=0,predecessorOnlyFolds=0,mixedFolds=0,successorOnlyFolds=0,preclaimNeutralChecks=0;
let peakSerializedBytes=0;
const maxDomainFragments=Object.fromEntries(facilities.map(item=>[item.facilityId,0])),domainQueues=Object.fromEntries(facilities.map(item=>[item.facilityId,[]]));

function applyGlobalReceipt(receipt){archive.nextSequence=receipt.sequence;archive.recentReceipts.push(receipt);state.gold=safeAdd(state.gold,receipt.rewards[0].amount,'global Gold');state.saveMeta.revision=archive.nextSequence;state.saveMeta.updatedAt=receipt.claimedAt;foldIfNeeded()}
function appendPredecessor(at,phase){const sequence=archive.nextSequence+1;applyGlobalReceipt(predecessorReceipt(sequence,at,phase))}
for(let index=0;index<PRE_ACTIVATION_RECEIPTS;index++)appendPredecessor(START_AT-PRE_ACTIVATION_RECEIPTS+index,'pre');

function activate(){const foundation=state.phase15FacilityFoundation;if(foundation.successorClaimAuthorityByFacilityId||foundation.successorFoldCheckpoint)return false;foundation.successorClaimAuthorityByFacilityId=Object.fromEntries(facilities.map(item=>{const row={facilityId:item.facilityId,sourceId:item.activityId,pendingBankAllocationsByRecordId:{},claimedDomainOrdinalRanges:[],claimCount:0,localProgress:0,lastReceipt:null,identity:''};row.identity=authorityIdentity(row);return[item.facilityId,row]}));const ids=facilities.map(item=>item.facilityId),row={authorityVersion:3,activationSequenceFloor:archive.nextSequence,activationFoldedThrough:archive.archiveCheckpoint.throughSequence,observedFoldedThrough:archive.archiveCheckpoint.throughSequence,foldedClaimCountByFacilityId:Object.fromEntries(ids.map(id=>[id,0])),latestFoldedReceiptByFacilityId:Object.fromEntries(ids.map(id=>[id,null])),foldedSuccessorClaimCount:0,identity:''};row.identity=foldIdentity(row);foundation.successorFoldCheckpoint=row;return true}
assert(activate(),'Initial V3 activation failed');
const activationRaw=JSON.stringify(state),activationSequenceFloor=archive.nextSequence;
peakSerializedBytes=Buffer.byteLength(activationRaw);
assert(!activate()&&JSON.stringify(state)===activationRaw,'V3 activation was not idempotent');

function classify(receipt,checkpoint=state.phase15FacilityFoundation.successorFoldCheckpoint){if(!receipt||receipt.sequence<=checkpoint.activationSequenceFloor||!receipt.offerId.startsWith('reward.offer.facility.successor.'))return{kind:'other'};const item=facilities.find(candidate=>receipt.offerId===`reward.offer.facility.successor.${candidate.facilityId.slice(9)}.${receipt.domainOrdinal}.v2`);if(!item||receipt.sourceType!==SOURCE_TYPE||receipt.sourceId!==item.activityId||receipt.facilityId!==item.facilityId||receipt.identity!==receiptIdentity(receipt)||!rangeHas(state.phase15FacilityFoundation.facilitiesById[item.facilityId].claimedOrdinalRanges,receipt.domainOrdinal))return{kind:'invalid'};return{kind:'successor',item}}

function foldIfNeeded(){if(archive.recentReceipts.length<=phase15.recentReceiptLimit)return;if(state.phase15FacilityFoundation.successorFoldCheckpoint)refreshIdentities(state);peakSerializedBytes=Math.max(peakSerializedBytes,bytes(state));const removed=archive.recentReceipts.splice(0,phase15.foldBatchSize),prior=archive.archiveCheckpoint,aggregate=clone(prior.aggregateRewards),sources=clone(prior.sourceCountsByType);for(const receipt of removed){const reward=receipt.rewards[0];aggregate[REWARD_KEY]=safeAdd(aggregate[REWARD_KEY]||0,reward.amount,'archive Gold');sources[receipt.sourceType]=safeAdd(sources[receipt.sourceType]||0,1,'archive source count')}const checkpoint={throughSequence:removed.at(-1).sequence,receiptCount:safeAdd(prior.receiptCount,removed.length,'archive receipts'),aggregateRewards:aggregate,sourceCountsByType:sources,previousIdentity:prior.identity,identity:''};checkpoint.identity=checkpointIdentity(checkpoint);archive.archiveCheckpoint=checkpoint;foldCount++;
  const successorCheckpoint=state.phase15FacilityFoundation.successorFoldCheckpoint;if(!successorCheckpoint)return;
  let successorInFold=0,otherInFold=0;for(const receipt of removed){const result=classify(receipt,successorCheckpoint);assert(result.kind!=='invalid','Malformed successor receipt reached fold');if(result.kind==='other'){otherInFold++;continue}const id=result.item.facilityId;successorCheckpoint.foldedClaimCountByFacilityId[id]=safeAdd(successorCheckpoint.foldedClaimCountByFacilityId[id],1,'folded facility claims');successorCheckpoint.foldedSuccessorClaimCount=safeAdd(successorCheckpoint.foldedSuccessorClaimCount,1,'folded successor claims');successorCheckpoint.latestFoldedReceiptByFacilityId[id]=clone(receipt);successorInFold++}successorCheckpoint.observedFoldedThrough=checkpoint.throughSequence;successorCheckpoint.identity=foldIdentity(successorCheckpoint);if(successorInFold&&otherInFold)mixedFolds++;else if(successorInFold)successorOnlyFolds++;else predecessorOnlyFolds++}

function nextDomainOrdinal(item,remaining){const id=item.facilityId,queue=domainQueues[id],facility=state.phase15FacilityFoundation.facilitiesById[id];if(!queue.length){const size=Math.min(capacities[id],remaining),values=Array.from({length:size},(_,index)=>facility.nextOrdinal+index+1),ordered=[...values.filter((_,index)=>index%2===1),...values.filter((_,index)=>index%2===0)];queue.push(...ordered);facility.nextOrdinal+=size}return queue.shift()}

function claim(item,at,remaining){const foundation=state.phase15FacilityFoundation,facility=foundation.facilitiesById[item.facilityId],authority=foundation.successorClaimAuthorityByFacilityId[item.facilityId],domainOrdinal=nextDomainOrdinal(item,remaining),sequence=archive.nextSequence+1,amount=phase2021.syntheticPolicy.rewardGoldByFacility[item.facilityId],local=phase2021.syntheticPolicy.localProgressByFacility[item.facilityId],before={gold:state.gold,local:authority.localProgress,count:authority.claimCount,sequence:archive.nextSequence};const receipt=successorReceipt(item,domainOrdinal,sequence,at);assert(same(before,{gold:state.gold,local:authority.localProgress,count:authority.claimCount,sequence:archive.nextSequence}),'Preclaim state changed');preclaimNeutralChecks++;
  facility.claimedOrdinalRanges=rangeAdd(facility.claimedOrdinalRanges,domainOrdinal);facility.localProgress=safeAdd(facility.localProgress,local,'facility local progress');authority.claimedDomainOrdinalRanges=rangeAdd(authority.claimedDomainOrdinalRanges,domainOrdinal);authority.claimCount=safeAdd(authority.claimCount,1,'claim count');authority.localProgress=safeAdd(authority.localProgress,local,'authority local progress');authority.lastReceipt=clone(receipt);maxDomainFragments[item.facilityId]=Math.max(maxDomainFragments[item.facilityId],authority.claimedDomainOrdinalRanges.length);successorClaims++;successorGold=safeAdd(successorGold,amount,'successor Gold');applyGlobalReceipt(receipt);authority.identity=authorityIdentity(authority)}

function refreshIdentities(value){const foundation=value.phase15FacilityFoundation;for(const row of Object.values(foundation.successorClaimAuthorityByFacilityId))row.identity=authorityIdentity(row);foundation.successorFoldCheckpoint.identity=foldIdentity(foundation.successorFoldCheckpoint)}

function validate(value){const started=performance.now();try{const foundation=value.phase15FacilityFoundation,checkpoint=foundation.successorFoldCheckpoint,archiveValue=foundation.claimArchive,errors=[],fail=id=>{if(!errors.includes(id))errors.push(id)},ids=facilities.map(item=>item.facilityId),counts=checkpoint?.foldedClaimCountByFacilityId,latest=checkpoint?.latestFoldedReceiptByFacilityId;
  if(!checkpoint||checkpoint.authorityVersion!==3||checkpoint.activationSequenceFloor!==activationSequenceFloor||checkpoint.activationFoldedThrough!==0||checkpoint.observedFoldedThrough!==archiveValue.archiveCheckpoint.throughSequence||checkpoint.identity!==foldIdentity(checkpoint))fail('checkpoint');
  if(!same(Object.keys(counts||{}).sort(),[...ids].sort())||!same(Object.keys(latest||{}).sort(),[...ids].sort())||!same(Object.keys(foundation.successorClaimAuthorityByFacilityId||{}).sort(),[...ids].sort()))fail('fixed-maps');
  if(archiveValue.nextSequence!==archiveValue.archiveCheckpoint.throughSequence+archiveValue.recentReceipts.length||archiveValue.recentReceipts.length>phase15.recentReceiptLimit||archiveValue.archiveCheckpoint.identity!==checkpointIdentity(archiveValue.archiveCheckpoint))fail('archive');
  let foldedTotal=0,rowTotal=0,domainVisits=0;const recentCounts=Object.fromEntries(ids.map(id=>[id,0])),recentLatest=Object.fromEntries(ids.map(id=>[id,null]));
  for(const receipt of archiveValue.recentReceipts){const result=classifyFor(value,receipt,checkpoint);if(result.kind==='invalid')fail('recent-invalid');if(result.kind==='successor'){recentCounts[result.item.facilityId]++;recentLatest[result.item.facilityId]=receipt}}
  for(const item of facilities){const id=item.facilityId,row=foundation.successorClaimAuthorityByFacilityId[id],facility=foundation.facilitiesById[id],folded=counts?.[id],foldedReceipt=latest?.[id],expectedLast=recentLatest[id]||foldedReceipt,foldedValid=Number.isSafeInteger(folded)&&folded>=0;domainVisits+=row?.claimedDomainOrdinalRanges?.length||0;if(!row||row.facilityId!==id||row.sourceId!==item.activityId||row.identity!==authorityIdentity(row))fail(`${id}.row`);if(!foldedValid||(folded===0)!==(foldedReceipt===null))fail(`${id}.folded`);if(foldedReceipt){const result=classifyFor(value,foldedReceipt,checkpoint);if(result.kind!=='successor'||result.item.facilityId!==id||foldedReceipt.sequence>checkpoint.observedFoldedThrough)fail(`${id}.folded-proof`)}const count=rangeCount(row.claimedDomainOrdinalRanges);if(count!==row.claimCount||!foldedValid||row.claimCount!==folded+recentCounts[id]||row.localProgress!==row.claimCount*phase2021.syntheticPolicy.localProgressByFacility[id]||facility.localProgress!==row.localProgress||!same(row.claimedDomainOrdinalRanges,facility.claimedOrdinalRanges)||row.claimedDomainOrdinalRanges.length>capacities[id]+1)fail(`${id}.conservation`);if(row.claimCount===0?row.lastReceipt!==null:!same(row.lastReceipt,expectedLast))fail(`${id}.last`);foldedTotal=safeAdd(foldedTotal,foldedValid?folded:0,'folded total');rowTotal=safeAdd(rowTotal,row.claimCount,'row total')}
  const recentTotal=Object.values(recentCounts).reduce((sum,count)=>sum+count,0);if(foldedTotal!==checkpoint.foldedSuccessorClaimCount||rowTotal!==foldedTotal+recentTotal)fail('global-conservation');
  const visitCount=archiveValue.recentReceipts.length+facilities.length*4+domainVisits;if(visitCount>computedVisitBudget)fail('visit-budget');
  return{ok:errors.length===0,errors,successorClaims:rowTotal,foldedSuccessorClaims:foldedTotal,recentSuccessorClaims:recentTotal,domainVisits,visitCount,validationMs:Number((performance.now()-started).toFixed(3))}}catch{return{ok:false,errors:['structure-or-overflow'],successorClaims:null,foldedSuccessorClaims:null,recentSuccessorClaims:null,domainVisits:null,visitCount:null,validationMs:Number((performance.now()-started).toFixed(3))}}}

function classifyFor(value,receipt,checkpoint){if(!receipt||receipt.sequence<=checkpoint.activationSequenceFloor||!receipt.offerId.startsWith('reward.offer.facility.successor.'))return{kind:'other'};const item=facilities.find(candidate=>receipt.offerId===`reward.offer.facility.successor.${candidate.facilityId.slice(9)}.${receipt.domainOrdinal}.v2`),facility=item&&value.phase15FacilityFoundation.facilitiesById[item.facilityId];if(!item||receipt.sourceType!==SOURCE_TYPE||receipt.sourceId!==item.activityId||receipt.facilityId!==item.facilityId||receipt.identity!==receiptIdentity(receipt)||!rangeHas(facility.claimedOrdinalRanges,receipt.domainOrdinal))return{kind:'invalid'};return{kind:'successor',item}}

function snapshot(year){refreshIdentities(state);const raw=JSON.stringify(state),parsed=JSON.parse(raw),validation=validate(parsed);return{year,globalSequence:archive.nextSequence,successorClaims,foldedReceipts:archive.archiveCheckpoint.receiptCount,recentReceipts:archive.recentReceipts.length,foldedSuccessorClaims:state.phase15FacilityFoundation.successorFoldCheckpoint.foldedSuccessorClaimCount,serializedBytes:Buffer.byteLength(raw),incrementalBytes:Buffer.byteLength(raw)-Buffer.byteLength(activationRaw),reloadValid:validation.ok,validationErrors:validation.errors,validationVisits:validation.visitCount,domainRangeEntries:validation.domainVisits,validationMs:validation.validationMs}}

const wallStarted=performance.now(),snapshots=[snapshot(0)];let anniversary=0;
for(let day=1;day<=DAYS;day++)for(let round=0;round<ROUNDS;round++){
  for(const item of facilities){const perFacilityDone=state.phase15FacilityFoundation.successorClaimAuthorityByFacilityId[item.facilityId].claimCount,remaining=EXPECTED_SUCCESSOR_CLAIMS/facilities.length-perFacilityDone;claim(item,START_AT+day*86400000+round*3600000,remaining)}
  if(successorClaims%PREDECESSOR_INTERVAL===0)appendPredecessor(START_AT+day*86400000+round*3600000+1800000,'post');
  if(day===ANNIVERSARIES[anniversary]&&round===ROUNDS-1){snapshots.push(snapshot(anniversary+1));anniversary++}
}
refreshIdentities(state);const finalRaw=JSON.stringify(state),reloaded=JSON.parse(finalRaw),finalValidation=validate(reloaded),exportEnvelope={formatVersion:1,payload:finalRaw,payloadIdentity:sha256(finalRaw)},imported=JSON.parse(exportEnvelope.payload),importValid=sha256(exportEnvelope.payload)===exportEnvelope.payloadIdentity&&validate(imported).ok;
const idempotentBefore=JSON.stringify(state),idempotent=!activate()&&JSON.stringify(state)===idempotentBefore;
const overflowCandidate=clone(state),overflowCheckpoint=overflowCandidate.phase15FacilityFoundation.successorFoldCheckpoint;overflowCheckpoint.foldedClaimCountByFacilityId['facility.command-center']=Number.MAX_SAFE_INTEGER;overflowCheckpoint.foldedSuccessorClaimCount=Number.MAX_SAFE_INTEGER;overflowCheckpoint.identity=foldIdentity(overflowCheckpoint);const overflowBefore=JSON.stringify(overflowCandidate);let overflowResult,overflowThrew=false;try{overflowResult=validate(overflowCandidate)}catch{overflowThrew=true}const overflowRejected=!overflowThrew&&overflowResult?.ok===false&&JSON.stringify(overflowCandidate)===overflowBefore;
const malformed=[];
for(const mutate of [candidate=>{delete candidate.phase15FacilityFoundation.successorFoldCheckpoint.foldedClaimCountByFacilityId['facility.forge'];candidate.phase15FacilityFoundation.successorFoldCheckpoint.identity=foldIdentity(candidate.phase15FacilityFoundation.successorFoldCheckpoint)},candidate=>{candidate.phase15FacilityFoundation.successorFoldCheckpoint.activationSequenceFloor=candidate.phase15FacilityFoundation.claimArchive.nextSequence+1;candidate.phase15FacilityFoundation.successorFoldCheckpoint.identity=foldIdentity(candidate.phase15FacilityFoundation.successorFoldCheckpoint)},candidate=>{const proof=candidate.phase15FacilityFoundation.successorFoldCheckpoint.latestFoldedReceiptByFacilityId['facility.command-center'];proof.sourceId='activity.research';proof.identity=receiptIdentity(proof);candidate.phase15FacilityFoundation.successorFoldCheckpoint.identity=foldIdentity(candidate.phase15FacilityFoundation.successorFoldCheckpoint)}]){const candidate=clone(state);mutate(candidate);malformed.push(validate(candidate).ok===false)}
const incrementalBytes=bytes(state)-Buffer.byteLength(activationRaw),peakIncrementalBytes=peakSerializedBytes-Buffer.byteLength(activationRaw),yearFiveGrowth=snapshots.at(-1).serializedBytes-snapshots.at(-2).serializedBytes,domainBounds=facilities.every(item=>maxDomainFragments[item.facilityId]<=capacities[item.facilityId]+1),sourceGold=facilities.reduce((sum,item)=>sum+state.phase15FacilityFoundation.successorClaimAuthorityByFacilityId[item.facilityId].claimCount*phase2021.syntheticPolicy.rewardGoldByFacility[item.facilityId],0);
const invariants={
  '01-minimum-strict-interleaved-claims':successorClaims===EXPECTED_SUCCESSOR_CLAIMS&&successorClaims>=FIXTURE.thresholds.minimumSuccessorClaims,
  '02-predecessor-triggered-and-mixed-folds':predecessorOnlyFolds>=4&&mixedFolds>=1&&successorOnlyFolds>=1,
  '03-fixed-eight-authority-maps':same(Object.keys(state.phase15FacilityFoundation.successorClaimAuthorityByFacilityId).sort(),facilities.map(item=>item.facilityId).sort())&&same(Object.keys(state.phase15FacilityFoundation.successorFoldCheckpoint.foldedClaimCountByFacilityId).sort(),facilities.map(item=>item.facilityId).sort())&&same(Object.keys(state.phase15FacilityFoundation.successorFoldCheckpoint.latestFoldedReceiptByFacilityId).sort(),facilities.map(item=>item.facilityId).sort()),
  '04-activation-floor-excludes-predecessor':activationSequenceFloor===PRE_ACTIVATION_RECEIPTS&&state.phase15FacilityFoundation.successorFoldCheckpoint.activationFoldedThrough===0,
  '05-exact-recent-folded-conservation':finalValidation.ok&&finalValidation.successorClaims===finalValidation.foldedSuccessorClaims+finalValidation.recentSuccessorClaims,
  '06-json-reload-valid':snapshots.every(row=>row.reloadValid)&&finalValidation.ok,
  '07-export-import-valid':importValid&&sha256(exportEnvelope.payload+'corrupt')!==exportEnvelope.payloadIdentity,
  '08-activation-idempotent':idempotent,
  '09-overflow-rejects-without-write':overflowRejected,
  '10-malformed-checkpoint-map-rejected':malformed[0],
  '11-malformed-floor-rejected':malformed[1],
  '12-malformed-folded-proof-rejected':malformed[2],
  '13-out-of-order-domain-fragments-bounded':domainBounds,
  '14-incremental-save-below-one-mib':peakIncrementalBytes<FIXTURE.thresholds.incrementalSerializedBytesMaxExclusive,
  '15-year-five-growth-at-most-64-kib':yearFiveGrowth<=FIXTURE.thresholds.yearFiveGrowthBytesMax,
  '16-validation-visits-fixed-map-plus-recent':snapshots.every(row=>row.validationVisits<=FIXTURE.thresholds.validationVisitBudget)&&finalValidation.visitCount<=FIXTURE.thresholds.validationVisitBudget
};
const deterministic={candidate:MODEL_ONLY?null:FIXTURE.candidate,runtimeEvidence,cadence:{...FIXTURE.cadence,days:DAYS,facilities:facilities.length,totalSuccessorClaims:EXPECTED_SUCCESSOR_CLAIMS},archivePolicy:{recentReceiptLimit:phase15.recentReceiptLimit,foldBatchSize:phase15.foldBatchSize},thresholds:FIXTURE.thresholds,snapshots:snapshots.map(({validationMs,...row})=>row),final:{successorClaims,successorGold,sourceGoldMatches:sourceGold===successorGold,globalGold:state.gold,globalSequence:archive.nextSequence,foldCount,predecessorOnlyFolds,mixedFolds,successorOnlyFolds,preclaimNeutralChecks,maxDomainFragments,foldedSuccessorClaimCount:state.phase15FacilityFoundation.successorFoldCheckpoint.foldedSuccessorClaimCount,recentReceiptCount:archive.recentReceipts.length,incrementalBytes,peakIncrementalBytes,yearFiveGrowthBytes:yearFiveGrowth,validationVisits:finalValidation.visitCount,serializedBytes:bytes(state),serializedSha256:sha256(finalRaw)},invariants};
deterministic.verdict=Object.values(invariants).every(Boolean)&&deterministic.final.sourceGoldMatches?'PASS':'FAIL';const deterministicEvidenceSha256=sha256(JSON.stringify(deterministic));
const expectedResult=MODEL_ONLY?FIXTURE.expectedModelOnlyResult:FIXTURE.expectedModelResult;
if(expectedResult){const expected=expectedResult;assert(deterministic.verdict===expected.verdict&&deterministicEvidenceSha256===expected.deterministicEvidenceSha256&&deterministic.final.serializedSha256===expected.serializedSha256&&deterministic.final.serializedBytes===expected.serializedBytes&&deterministic.final.incrementalBytes===expected.incrementalBytes&&deterministic.final.peakIncrementalBytes===expected.peakIncrementalBytes&&deterministic.final.yearFiveGrowthBytes===expected.yearFiveGrowthBytes&&deterministic.final.validationVisits===expected.validationVisits,`Frozen V3 ${MODEL_ONLY?'model-only':'candidate'} result changed`)}
assert(deterministic.verdict==='PASS',`V3 bounded model failed: ${Object.entries(invariants).filter(([,pass])=>!pass).map(([id])=>id).join(', ')}`);
process.stdout.write(JSON.stringify({contract:'phase-20-21-five-year-bounded-v3-qa-v1',mode:MODEL_ONLY?'model-only':'frozen-candidate',deterministicEvidenceSha256,deterministic,observedWallClock:{simulationMs:Number((performance.now()-wallStarted).toFixed(3)),snapshotValidationMs:snapshots.map(row=>row.validationMs),finalValidationMs:finalValidation.validationMs}},null,2)+'\n');
