(()=>{
  'use strict';
  const CHANNEL='everstead-phase-24c2d-integration-v1';
  const json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config){
    const shared=parent.__P24C2D_SHARED_STORES__?.get(config.viewport.sharedId);
    if(!shared)throw new Error('Isolated shared memory store is unavailable');
    const errors=[],nativeAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);
    let nativeStorageInstrumented=false;
    window.matchMedia=query=>({matches:config.viewport.reducedMotion===true&&String(query).includes('prefers-reduced-motion'),media:String(query),onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});
    addEventListener('error',event=>{const target=event.target;if(target&&target!==window&&(target.src||target.href)){if(target.matches?.('img[data-roster-art],img[data-village-cutout],[data-phase23-companion-full-art],[data-phase23-companion-thumb]'))return;errors.push(`asset-error ${target.src||target.href}`)}else errors.push(String(event.error?.stack||event.message))},true);
    addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));
    const warn=console.warn.bind(console),error=console.error.bind(console);
    console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};
    console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    try{
      const native=window.localStorage;
      for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===native)nativeAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}
      nativeStorageInstrumented=true;
    }catch{}
    const memoryStorage={
      getItem:key=>shared.slots.get(String(key))??null,
      setItem:(key,value)=>{key=String(key);value=String(value);const oldValue=shared.slots.get(key)??null;shared.writes.push({op:'set',key,oldValue,newValue:value,realm:config.viewport.id});shared.slots.set(key,value)},
      removeItem:key=>{key=String(key);const oldValue=shared.slots.get(key)??null;shared.writes.push({op:'remove',key,oldValue,newValue:null,realm:config.viewport.id});shared.slots.delete(key)}
    };
    Object.assign(window,{__P24C2D_CONFIG__:config,__P24C2D_STORE__:shared,__P24C2D_ERRORS__:errors,__P24C2D_NATIVE_ACCESSES__:nativeAccesses,__P24C2D_NATIVE_INSTRUMENTED__:nativeStorageInstrumented});
    window.__EVERSTEAD_PERSISTENCE_TEST__={storage:memoryStorage,operationLog:[]};
    const runtime={storage:memoryStorage,clock:{now:()=>config.contract.frozenNow,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.731,confirm:()=>true,ids:{save:()=>`save-phase24c2d-${++shared.saveIndex}`,transaction:()=>`tx-phase24c2d-${++shared.transactionIndex}`}};
    if(config.viewport.publicRelease!==true)runtime.qa={allowDestructive:true,isolatedStorage:true};
    window.__EVERSTEAD_RUNTIME__=runtime;
  }

  function installSuite(){
    const CHANNEL='everstead-phase-24c2d-integration-v1',config=window.__P24C2D_CONFIG__,f=config.contract,v=config.viewport,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
    const clone=value=>value===undefined?undefined:JSON.parse(JSON.stringify(value)),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),add=(id,actual,detail='')=>results.push({id:`${v.id}-${id}`,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:typeof detail==='string'?detail:JSON.stringify(detail).slice(0,6000)}),visible=node=>{if(!node)return false;const style=getComputedStyle(node),rect=node.getBoundingClientRect();return style.display!=='none'&&style.visibility!=='hidden'&&style.opacity!=='0'&&rect.width>0&&rect.height>0},touch=node=>{const rect=node?.getBoundingClientRect();return Boolean(rect&&rect.width>=f.minimumTouchTargetPx&&rect.height>=f.minimumTouchTargetPx)},send=()=>parent.postMessage({channel:CHANNEL,nonce:config.nonce,scenario:v.scenario,results,errors:window.__P24C2D_ERRORS__.slice()},'*');
    const bridge=()=>window[f.bridge.global],restaurantBridge=()=>window[f.bridge.restaurantBridgeGlobal],recoveryBridge=()=>window[f.bridge.recoveryBridgeGlobal],baseBridge=()=>window.__EVERSTEAD_QA__,snap=()=>bridge()?.read.snapshot(),activeRaw=()=>window.__P24C2D_STORE__.slots.get(f.storage.activeKey)??null,activeState=()=>{const raw=activeRaw();return raw===null?null:JSON.parse(raw)},formula=amount=>bridge()?.read.formula(amount),collections=state=>state?.durableProgression?.collections,receiptCount=state=>(collections(state)?.recentGrantReceipts||[]).filter(item=>item.definitionId===f.release.grantId).length,activationReceipts=state=>(state?.saveMeta?.appliedMigrations||[]).filter(item=>item.id===f.release.activationReceiptId),goldReward=offer=>(offer?.rewards||[]).filter(item=>item.kind==='gold').reduce((sum,item)=>sum+item.amount,0),restaurant=data=>data?.restaurant||null;
    const dismiss=async()=>{for(let attempt=0;attempt<30;attempt++){const overlay=[...document.querySelectorAll('.overlay,[data-overlay]')].filter(visible).at(-1);if(!overlay)return true;const close=[...overlay.querySelectorAll('[data-modal-close],[data-phase13-story="skip"],[data-phase15-tutorial-action="skip"],[data-phase16-tutorial-action="skip"],[data-phase13-tutorial-action="skip"]')].find(visible);if(close)close.click();else document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(35)}return ![...document.querySelectorAll('.overlay,[data-overlay]')].some(visible)};
    const openCodex=async()=>{await dismiss();const more=document.querySelector('.bottom-nav [data-nav="more"]');more?.click();await wait(45);const opener=document.querySelector('[data-phase-11d-codex-open]');opener?.click();await wait(90);return{more,opener,codex:document.querySelector('[data-phase-11d-codex]')}};
    const call=(group,name,...args)=>{const target={collection:bridge(),restaurant:restaurantBridge(),recovery:recoveryBridge()}[group];const fn=target?.destructive?.[name];if(typeof fn!=='function')throw new Error(`${group}.${name} bridge method unavailable`);return fn(...args)};
    const resetRecoveryClock=()=>{const before=window.__P24C2D_STORE__.writes.length,result=baseBridge()?.clock?.reset?.();if(result?.ok!==true||window.__P24C2D_STORE__.writes.length!==before)throw new Error('The isolated recovery clock could not be reset without storage writes');return result};
    const derive=()=>restaurantBridge()?.read?.derive?.();
    const driveService=async(label,record)=>{
      let live=record,result=call('restaurant','begin',live.id,live.identity);if(result?.ok!==true)throw new Error(`${label} begin: ${result?.reason||'failed'}`);
      live=restaurant(derive()).customers.find(item=>item.id===record.id);
      result=call('restaurant','prepare',live.id,live.identity,{recipeId:f.restaurant.recipeId,stationId:f.restaurant.stationId,stockIdentity:`${f.restaurant.stockIdentityPrefix}.${live.ordinal}`});if(result?.ok!==true)throw new Error(`${label} prepare: ${result?.reason||'failed'}`);
      live=restaurant(derive()).customers.find(item=>item.id===record.id);
      if(live.status==='preparing'){result=call('restaurant','advancePreparation',live.id,live.identity,live.preparationCompletesAt);if(result?.ok!==true)throw new Error(`${label} complete: ${result?.reason||'failed'}`);live=restaurant(derive()).customers.find(item=>item.id===record.id)}
      if(live.status==='awaiting-stock-transfer'){result=call('restaurant','transferStock',live.id,live.identity,live.batchIdentity);if(result?.ok!==true)throw new Error(`${label} transfer: ${result?.reason||'failed'}`);live=restaurant(derive()).customers.find(item=>item.id===record.id)}
      result=call('restaurant','serve',live.id,live.identity);if(result?.ok!==true)throw new Error(`${label} serve: ${result?.reason||'failed'}`);
      const after=restaurant(derive()),served=after.customers.find(item=>item.id===record.id),offer=after.offers.find(item=>item.id===served?.offerId),outcome=after.outcomes.find(item=>item.offerId===offer?.id);return{served,offer,outcome,derive:after}
    };
    const exactTotals=(snapshot,bps)=>snapshot?.totals?.powerBps===0&&snapshot?.totals?.earningsBps===0&&snapshot?.totals?.expBps===0&&same(snapshot?.totals?.facilityBpsByFacilityId,bps?{[f.release.facilityId]:bps}:{});
    const currentReleaseActive=snapshot=>{const receipt=activationReceipts(snapshot?.state);return snapshot?.state?.schemaVersion===14&&snapshot?.validation?.ok===true&&receipt.length===1&&receipt[0]?.from===14&&receipt[0]?.to===14&&receipt[0]?.toAuthorityHash===snapshot?.authorityHash&&receipt[0]?.rewardApplications===0&&snapshot?.releaseId===f.release.id&&snapshot?.grantId===f.release.grantId};

    async function claimScenario(){
      const candidate=bridge(),restaurantCandidate=restaurantBridge(),recoveryCandidate=recoveryBridge(),descriptor=Object.getOwnPropertyDescriptor(window,f.bridge.global),readKeys=Object.keys(candidate?.read||{}).sort(),destructiveKeys=Object.keys(candidate?.destructive||{}).sort();
      add('bounded-bridge-present-frozen-and-exact',candidate?.version===f.bridge.version&&Object.isFrozen(candidate)&&Object.isFrozen(candidate.read)&&Object.isFrozen(candidate.destructive)&&same(readKeys,[...f.bridge.readMethods].sort())&&same(destructiveKeys,[...f.bridge.destructiveMethods].sort()),{version:candidate?.version,readKeys,destructiveKeys});
      add('bridge-nonenumerable-guarded-getter',descriptor?.enumerable===false&&typeof descriptor?.get==='function'&&descriptor?.set===undefined&&descriptor?.configurable===true,{enumerable:descriptor?.enumerable,get:typeof descriptor?.get,set:typeof descriptor?.set,configurable:descriptor?.configurable});
      add('historical-bridges-present-only-for-real-restaurant-and-recovery-paths',restaurantCandidate?.version===f.bridge.restaurantBridgeVersion&&recoveryCandidate?.version===f.bridge.recoveryBridgeVersion,{restaurant:restaurantCandidate?.version,recovery:recoveryCandidate?.version});
      const initial=snap(),initialState=initial?.state,activation=activationReceipts(initialState);
      add('fresh-boot-activated-schema14-valid',initialState?.schemaVersion===14&&initial?.validation?.ok===true&&initial?.authorityHash===f.candidate.authoritySha256&&initial?.releaseId===f.release.id&&initial?.grantId===f.release.grantId,initial?.validation);
      add('activation-exactly-once-and-reward-neutral',activation.length===1&&activation[0].rewardApplications===0&&activation[0].from===14&&activation[0].to===14&&activation[0].activatedReleaseIds?.join(',')===f.release.id,{activation});
      add('initial-zero-reward-and-zero-global-pools',initial?.claimed===false&&initial?.ready===false&&exactTotals(initial,0)&&receiptCount(initialState)===0,{claimed:initial?.claimed,ready:initial?.ready,totals:initial?.totals,receiptCount:receiptCount(initialState)});
      add('initial-0-of-3-exact-recipe-readiness',initial?.progress?.count===0&&initial?.progress?.complete===false&&same(initial?.progress?.rows?.map(item=>item.id),f.release.recipeIds)&&initial.progress.rows.every(item=>item.mastery===0&&item.complete===false),initial?.progress);
      await dismiss();const initialMore=document.querySelector('.bottom-nav [data-nav="more"]');initialMore?.click();await wait(45);const initialTutorialLogButton=document.querySelector('[data-phase13-tutorial-log]');initialTutorialLogButton?.click();await wait(60);const initialCollectionTutorialRows=[...document.querySelectorAll('[data-phase24c2d-log]')];
      add('collection-tutorial-log-rows-hidden-before-restaurant-discovery',visible(initialTutorialLogButton)&&initialCollectionTutorialRows.length===0,{buttonVisible:visible(initialTutorialLogButton),collectionRows:initialCollectionTutorialRows.length});
      await dismiss();
      for(const row of f.formula.cases){const observed=formula(row.baseSaleGold);add(`preclaim-formula-${row.baseSaleGold}-unchanged`,observed?.bps===0&&observed?.result===row.beforeClaim,observed)}
      const beforeActivateRaw=initial.raw,beforeActivateRevision=initialState.saveMeta.revision,activate=call('collection','activate'),afterActivate=snap();
      add('repeat-activation-is-write-free',activate?.ok===true&&activate?.changed===false&&activate?.writes===0&&afterActivate?.raw===beforeActivateRaw&&afterActivate?.state?.saveMeta?.revision===beforeActivateRevision&&activationReceipts(afterActivate.state).length===1,activate);
      for(const kind of ['duplicate-step','duplicate-receipt']){const beforeTamper=snap(),tamper=call('collection','probeTutorialTamper',kind),afterTamper=snap();add(`tutorial-${kind}-candidate-is-rejected-write-free`,tamper?.ok===false&&tamper?.rejected===true&&tamper?.reason==='phase24c2d.tutorial'&&tamper?.writes===0&&tamper?.rawUnchanged===true&&tamper?.revisionUnchanged===true&&afterTamper.raw===beforeTamper.raw&&afterTamper.state.saveMeta.revision===beforeTamper.state.saveMeta.revision&&afterTamper.validation.ok===true,{tamper,beforeRevision:beforeTamper.state.saveMeta.revision,afterRevision:afterTamper.state.saveMeta.revision})}

      const definitions=restaurantCandidate.read.definitions(),policy=restaurantCandidate.read.economyReport()?.policy,prepared=call('collection','prepareRestaurant'),preparedSnapshot=snap();
      add('isolated-fixture-seeds-only-canonical-phase17-restaurant-discovery',prepared?.ok===true&&preparedSnapshot?.validation?.ok===true&&preparedSnapshot?.state?.facilityProgress?.discoveredIds?.includes(f.release.facilityId)&&!preparedSnapshot?.state?.facilityProgress?.unlockedIds?.includes(f.release.facilityId),{prepared:{ok:prepared?.ok,reason:prepared?.reason},discovered:preparedSnapshot?.state?.facilityProgress?.discoveredIds,unlocked:preparedSnapshot?.state?.facilityProgress?.unlockedIds,validation:preparedSnapshot?.validation});
      await dismiss();const village=document.querySelector('.bottom-nav [data-nav="village"]');village?.click();await wait(70);const restaurantHotspot=document.querySelector(`[data-phase15-facility-id="${f.release.facilityId}"]`),hotspotState=restaurantHotspot?.dataset.phase15State;restaurantHotspot?.click();await wait(85);const introduction=document.querySelector('[data-phase17-facility-introduction]'),watchIntroduction=introduction?.querySelector(`[data-phase17-opening-resolution="watched"][data-phase17-opening-facility="${f.release.facilityId}"]`),skipIntroduction=introduction?.querySelector(`[data-phase17-opening-resolution="skipped"][data-phase17-opening-facility="${f.release.facilityId}"]`);
      add('real-village-restaurant-hotspot-opens-phase17-introduction',visible(restaurantHotspot)&&hotspotState==='discovered'&&visible(introduction)&&introduction?.dataset.phase17FacilityIntroduction===f.release.facilityId&&touch(watchIntroduction)&&touch(skipIntroduction),{hotspotState,hotspotSize:restaurantHotspot?{width:restaurantHotspot.getBoundingClientRect().width,height:restaurantHotspot.getBoundingClientRect().height}:null,introductionFacilityId:introduction?.dataset.phase17FacilityIntroduction,introductionVisible:visible(introduction),introductionText:introduction?.textContent.slice(0,700)});
      watchIntroduction?.click();await wait(120);const openedRestaurant=snap(),restaurantAfterIntroduction=restaurant(derive());
      add('phase17-watch-route-opens-production-phase16-restaurant',openedRestaurant?.validation?.ok===true&&openedRestaurant?.state?.facilityProgress?.unlockedIds?.includes(f.release.facilityId)&&Number.isSafeInteger(restaurantAfterIntroduction?.unlockedAt)&&openedRestaurant?.state?.phase16Restaurant?.storyEvents?.discoveryResolved===true,{unlocked:openedRestaurant?.state?.facilityProgress?.unlockedIds,restaurant:restaurantAfterIntroduction,storyEvents:openedRestaurant?.state?.phase16Restaurant?.storyEvents,validation:openedRestaurant?.validation});
      const interval=policy?.intervalMs||3600000,settled=call('restaurant','advanceOffline',{kind:'phase24c2d-capture',elapsedMs:interval*f.restaurant.minimumCustomerCount}),banked=restaurant(derive())?.customers||[];
      add('two-real-restaurant-customers-banked',settled?.ok===true&&banked.length>=f.restaurant.minimumCustomerCount&&banked.slice(0,2).every(item=>item.status==='banked'),{settled:{ok:settled?.ok,createdCount:settled?.createdCount},count:banked.length,policyId:policy?.id,definitionId:definitions?.definitionSetId});
      const first=await driveService('preclaim',banked[0]),preOffer=clone(first.offer),preAuthored=first.outcome?.totalGold;
      add('preclaim-service-offer-captures-no-collection-value',Number.isSafeInteger(preAuthored)&&goldReward(preOffer)===preAuthored&&initial?.totals?.facilityBpsByFacilityId?.[f.release.facilityId]===undefined,{authored:preAuthored,reward:goldReward(preOffer),outcome:first.outcome});

      const completion=call('collection','completeFoundingRecipes'),ready=snap();
      add('completion-reaches-exact-3-of-3-ready-with-zero-reward',completion?.ok===true&&ready?.progress?.count===3&&ready?.progress?.complete===true&&ready?.progress?.rows.every(item=>item.complete&&item.mastery>=1)&&ready?.ready===true&&ready?.claimed===false&&exactTotals(ready,0)&&receiptCount(ready.state)===0,{completion,progress:ready?.progress,totals:ready?.totals});
      const readyUi=await openCodex(),readyTutorial=document.querySelector(`[data-phase13-tutorial="${f.tutorials[0].id}"]`),readyDone=readyTutorial?.querySelector('[data-phase13-tutorial-action="complete"]'),readySkip=readyTutorial?.querySelector('[data-phase13-tutorial-action="skip"]'),readyLog=readyTutorial?.querySelector('[data-phase13-tutorial-action="log"]');
      add('ready-tutorial-auto-introduced-by-isolde',visible(readyTutorial)&&readyTutorial.textContent.includes(f.tutorials[0].actorName)&&readyTutorial.textContent.includes('2.00%')&&[readyDone,readySkip,readyLog].every(touch),{visible:visible(readyTutorial),text:readyTutorial?.textContent.slice(0,500)});
      readyDone?.click();await wait(70);
      const afterReadyTutorial=snap(),readyProgress=afterReadyTutorial.state.tutorialProgress;
      add('ready-tutorial-completion-reward-neutral',readyProgress.seenStepIds.includes(f.tutorials[0].stepId)&&readyProgress.completedStepIds.includes(f.tutorials[0].stepId)&&!readyProgress.dismissedStepIds.includes(f.tutorials[0].stepId)&&exactTotals(afterReadyTutorial,0),{seen:readyProgress.seenStepIds.includes(f.tutorials[0].stepId),completed:readyProgress.completedStepIds.includes(f.tutorials[0].stepId),totals:afterReadyTutorial.totals});
      const reopenedReady=await openCodex(),card=document.querySelector('[data-phase24c2d-collection]'),claimButton=card?.querySelector('[data-phase24c2d-claim]'),recipeRows=[...card?.querySelectorAll('[data-recipe-id]')||[]];
      add('ready-mobile-codex-card-3-of-3-accessible',visible(reopenedReady.codex)&&visible(card)&&card?.dataset.state==='ready'&&card.textContent.includes('3 / 3')&&recipeRows.length===3&&recipeRows.every(node=>node.dataset.complete==='true')&&claimButton?.disabled===false&&touch(claimButton),{state:card?.dataset.state,text:card?.textContent.slice(0,700),button:{disabled:claimButton?.disabled,width:claimButton?.getBoundingClientRect().width,height:claimButton?.getBoundingClientRect().height}});
      add('ready-mobile-layout-has-no-horizontal-overflow',document.documentElement.scrollWidth<=innerWidth+1,{scrollWidth:document.documentElement.scrollWidth,innerWidth});

      const beforeClaimOffer=clone(restaurant(derive()).offers.find(item=>item.id===preOffer.id)),beforeClaim=snap();claimButton?.click();await wait(110);const claimResult=document.querySelector('[data-phase24c2d-claim-result]'),returnButton=claimResult?.querySelector('[data-phase24c2d-return-codex]'),claimed=snap(),claimReceipt=collections(claimed.state).recentGrantReceipts.find(item=>item.definitionId===f.release.grantId),afterClaimOffer=clone(restaurant(derive()).offers.find(item=>item.id===preOffer.id));
      add('visible-claim-button-opens-result-with-exact-equation-and-return',visible(claimResult)&&claimResult.textContent.includes('The Founding Table')&&claimResult.textContent.includes('Old bonus')&&claimResult.textContent.includes('Gained')&&claimResult.textContent.includes('New total')&&claimResult.textContent.includes('2.00%')&&touch(returnButton),{visible:visible(claimResult),text:claimResult?.textContent.slice(0,700),returnSize:returnButton?{width:returnButton.getBoundingClientRect().width,height:returnButton.getBoundingClientRect().height}:null});
      add('manual-visible-claim-exact-single-receipt-and-200-bps',claimed?.raw!==beforeClaim?.raw&&claimed?.state?.saveMeta?.revision===beforeClaim?.state?.saveMeta?.revision+1&&claimed?.claimed===true&&claimed?.ready===false&&exactTotals(claimed,f.release.bps)&&receiptCount(claimed.state)===1&&claimReceipt?.definitionId===f.release.grantId&&claimReceipt?.bps===f.release.bps&&claimReceipt?.oldTotalBps===0&&claimReceipt?.newTotalBps===f.release.bps,{receipt:claimReceipt,totals:claimed?.totals});
      add('pre-ready-offer-remains-byte-identical-after-collection-claim',same(beforeClaimOffer,afterClaimOffer)&&same(preOffer,afterClaimOffer)&&goldReward(afterClaimOffer)===preAuthored,{before:beforeClaimOffer,after:afterClaimOffer});
      returnButton?.click();await wait(150);const claimTutorial=document.querySelector(`[data-phase13-tutorial="${f.tutorials[1].id}"]`),readyTutorialAfterClaim=document.querySelector(`[data-phase13-tutorial="${f.tutorials[0].id}"]`),claimSkip=claimTutorial?.querySelector('[data-phase13-tutorial-action="skip"]');
      add('return-to-codex-path-introduces-claim-tutorial-by-lyra',visible(claimTutorial)&&claimTutorial.textContent.includes(f.tutorials[1].actorName)&&claimTutorial.textContent.includes('additive')&&touch(claimSkip),{visible:visible(claimTutorial),text:claimTutorial?.textContent.slice(0,500)});
      add('claimed-lesson-has-priority-over-ready-lesson',visible(claimTutorial)&&!visible(readyTutorialAfterClaim),{claimVisible:visible(claimTutorial),readyVisible:visible(readyTutorialAfterClaim)});
      for(const row of f.formula.cases){const observed=formula(row.baseSaleGold);add(`postclaim-formula-${row.baseSaleGold}-floor`,observed?.bps===f.release.bps&&observed?.result===row.afterClaim,observed)}
      const beforeDuplicate=snap(),beforeDuplicateRaw=beforeDuplicate.raw,beforeDuplicateRevision=beforeDuplicate.state.saveMeta.revision,duplicate=call('collection','claim'),afterDuplicate=snap();
      add('duplicate-collection-claim-refuses-with-zero-write',duplicate?.ok===false&&duplicate?.reason==='already-claimed'&&duplicate?.writes===0&&afterDuplicate.raw===beforeDuplicateRaw&&afterDuplicate.state.saveMeta.revision===beforeDuplicateRevision&&receiptCount(afterDuplicate.state)===1,duplicate);

      const remaining=(restaurant(derive()).customers||[]).find(item=>item.status==='banked'),second=await driveService('postclaim',remaining),postOffer=second.offer,postOutcome=second.outcome,expectedPost=postOutcome.totalGold+Math.floor(postOutcome.baseSaleGold*f.release.bps/10000);
      add('postclaim-real-service-captures-base-only-floor-plus-authored-tip',goldReward(postOffer)===expectedPost&&goldReward(postOffer)-postOutcome.totalGold===Math.floor(postOutcome.baseSaleGold*f.release.bps/10000)&&postOutcome.totalGold===postOutcome.baseSaleGold+postOutcome.tipGold,{baseSaleGold:postOutcome.baseSaleGold,tipGold:postOutcome.tipGold,authoredTotalGold:postOutcome.totalGold,collectionGold:goldReward(postOffer)-postOutcome.totalGold,offerGold:goldReward(postOffer),expectedPost});
      add('postclaim-capture-does-not-reprice-earlier-ready-offer',goldReward(restaurant(derive()).offers.find(item=>item.id===preOffer.id))===preAuthored,{preAuthored,preOfferGold:goldReward(restaurant(derive()).offers.find(item=>item.id===preOffer.id))});

      claimSkip?.click();await wait(70);
      const afterClaimTutorial=snap(),claimProgress=afterClaimTutorial.state.tutorialProgress;
      add('claim-tutorial-skip-is-optional-and-reward-neutral',claimProgress.seenStepIds.includes(f.tutorials[1].stepId)&&claimProgress.dismissedStepIds.includes(f.tutorials[1].stepId)&&!claimProgress.completedStepIds.includes(f.tutorials[1].stepId)&&exactTotals(afterClaimTutorial,f.release.bps)&&receiptCount(afterClaimTutorial.state)===1,{seen:claimProgress.seenStepIds.includes(f.tutorials[1].stepId),dismissed:claimProgress.dismissedStepIds.includes(f.tutorials[1].stepId)});
      const replayBefore=afterClaimTutorial.state.tutorialProgress.replayCountsByTutorial[f.tutorials[0].id];await dismiss();const replayMore=document.querySelector('.bottom-nav [data-nav="more"]');replayMore?.click();await wait(45);const tutorialLogButton=document.querySelector('[data-phase13-tutorial-log]');tutorialLogButton?.click();await wait(60);const collectionLogRows=[...document.querySelectorAll('[data-phase24c2d-log]')],replayButton=document.querySelector(`[data-phase13-tutorial-action="replay"][data-phase13-tutorial-id="${f.tutorials[0].id}"]`),replayButtonTouch=touch(replayButton),beforeReplay=snap();replayButton?.click();await wait(75);const afterReplay=snap(),terminalReplay=document.querySelector(`[data-phase13-tutorial="${f.tutorials[0].id}"]`),terminalClose=terminalReplay?.querySelector('[data-modal-close]'),terminalDone=terminalReplay?.querySelector('[data-phase13-tutorial-action="complete"]'),terminalSkip=terminalReplay?.querySelector('[data-phase13-tutorial-action="skip"]');
      add('collection-tutorial-log-rows-visible-after-discovery',visible(tutorialLogButton)&&collectionLogRows.length===2&&replayButtonTouch,{buttonVisible:visible(tutorialLogButton),collectionRows:collectionLogRows.length,replayButtonTouch});
      add('tutorial-replay-is-reward-neutral',beforeReplay.raw!==afterReplay.raw&&afterReplay.state.saveMeta.revision===beforeReplay.state.saveMeta.revision+1&&afterReplay.state.tutorialProgress.replayCountsByTutorial[f.tutorials[0].id]===replayBefore+1&&exactTotals(afterReplay,f.release.bps)&&receiptCount(afterReplay.state)===1,{beforeRevision:beforeReplay.state.saveMeta.revision,afterRevision:afterReplay.state.saveMeta.revision,replayCount:afterReplay.state.tutorialProgress.replayCountsByTutorial[f.tutorials[0].id]});
      add('terminal-replay-modal-offers-close-not-inert-done-or-skip',visible(terminalReplay)&&visible(terminalClose)&&touch(terminalClose)&&!terminalDone&&!terminalSkip,{visible:visible(terminalReplay),closeVisible:visible(terminalClose),done:Boolean(terminalDone),skip:Boolean(terminalSkip),text:terminalReplay?.textContent.slice(0,500)});
      terminalClose?.click();await wait(50);
      const finalUi=await openCodex(),claimedCard=document.querySelector('[data-phase24c2d-collection]'),claimedButton=claimedCard?.querySelector('[data-phase24c2d-claim]');
      add('claimed-mobile-codex-state-accessible',visible(finalUi.codex)&&visible(claimedCard)&&claimedCard?.dataset.state==='claimed'&&claimedCard.textContent.includes('Claimed')&&claimedCard.textContent.includes('+2.00%')&&claimedButton?.disabled===true&&touch(claimedButton),{state:claimedCard?.dataset.state,text:claimedCard?.textContent.slice(0,700)});
      add('claimed-mobile-layout-and-reduced-motion-contract',document.documentElement.scrollWidth<=innerWidth+1&&matchMedia('(prefers-reduced-motion: reduce)').matches===v.reducedMotion,{scrollWidth:document.documentElement.scrollWidth,innerWidth,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches});
      const final=snap();window.__P24C2D_STORE__.handoff={raw:final.raw,saveId:final.state.saveMeta.saveId,revision:final.state.saveMeta.revision,receiptIdentity:collections(final.state).recentGrantReceipts.find(item=>item.definitionId===f.release.grantId)?.identity,preOffer:clone(restaurant(derive()).offers.find(item=>item.id===preOffer.id)),postOffer:clone(postOffer)};
    }

    async function reloadScenario(){
      const handoff=window.__P24C2D_STORE__.handoff,candidate=bridge(),current=snap(),state=current?.state,receipt=collections(state)?.recentGrantReceipts?.find(item=>item.definitionId===f.release.grantId);
      add('shared-claimed-installation-handoff-present',Boolean(handoff?.raw&&handoff?.receiptIdentity&&handoff?.saveId),{saveId:handoff?.saveId,revision:handoff?.revision,receiptIdentity:handoff?.receiptIdentity});
      add('real-page-reload-restores-valid-schema14',candidate?.version===f.bridge.version&&state?.schemaVersion===14&&current?.validation?.ok===true&&state.saveMeta.saveId===handoff?.saveId,{version:candidate?.version,schemaVersion:state?.schemaVersion,validation:current?.validation,saveId:state?.saveMeta?.saveId});
      add('reload-preserves-exactly-one-collection-receipt',current?.claimed===true&&current?.ready===false&&receiptCount(state)===1&&receipt?.identity===handoff?.receiptIdentity&&receipt?.bps===f.release.bps&&receipt?.definitionId===f.release.grantId,{receiptCount:receiptCount(state),receipt});
      add('reload-preserves-200-bps-and-zero-global-pools',exactTotals(current,f.release.bps),current?.totals);
      add('reload-preserves-3-of-3-and-tutorial-history',current?.progress?.count===3&&current?.progress?.complete===true&&f.tutorials.every(item=>state.tutorialProgress.seenStepIds.includes(item.stepId))&&state.tutorialProgress.completedStepIds.includes(f.tutorials[0].stepId)&&state.tutorialProgress.dismissedStepIds.includes(f.tutorials[1].stepId),{progress:current?.progress,tutorialProgress:state?.tutorialProgress});
      const before=current.raw,beforeRevision=state.saveMeta.revision,duplicate=call('collection','claim'),after=snap();
      add('reload-duplicate-claim-still-refuses-write-free',duplicate?.ok===false&&duplicate?.reason==='already-claimed'&&duplicate?.writes===0&&after.raw===before&&after.state.saveMeta.revision===beforeRevision&&receiptCount(after.state)===1,duplicate);
      for(const row of f.formula.cases){const observed=formula(row.baseSaleGold);add(`reload-formula-${row.baseSaleGold}-floor-stable`,observed?.bps===f.release.bps&&observed?.result===row.afterClaim,observed)}
      const ui=await openCodex(),card=document.querySelector('[data-phase24c2d-collection]'),button=card?.querySelector('[data-phase24c2d-claim]');
      add('reload-390x844-claimed-card-visible-and-accessible',visible(ui.codex)&&visible(card)&&card?.dataset.state==='claimed'&&card.textContent.includes('3 / 3')&&card.textContent.includes('+2.00%')&&button?.disabled===true&&touch(button),{state:card?.dataset.state,text:card?.textContent.slice(0,700),button:{width:button?.getBoundingClientRect().width,height:button?.getBoundingClientRect().height}});
      add('reload-390x844-no-horizontal-overflow-reduced-motion',document.documentElement.scrollWidth<=innerWidth+1&&matchMedia('(prefers-reduced-motion: reduce)').matches===true,{scrollWidth:document.documentElement.scrollWidth,innerWidth,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches});

      await dismiss();resetRecoveryClock();const safeReset=call('recovery','resetSafe'),afterSafeReset=snap();
      add('safe-reset-reactivates-current-release-reward-neutral',safeReset?.ok===true&&currentReleaseActive(afterSafeReset)&&afterSafeReset?.claimed===false&&exactTotals(afterSafeReset,0)&&receiptCount(afterSafeReset.state)===0,{safeReset,activation:activationReceipts(afterSafeReset?.state),validation:afterSafeReset?.validation,totals:afterSafeReset?.totals});
      resetRecoveryClock();const rollback=call('recovery','roundTripRollback'),afterRollback=snap();
      add('rollback-restore-reactivates-current-release-reward-neutral',rollback?.ok===true&&rollback?.terminalControlsClean===true&&currentReleaseActive(afterRollback)&&afterRollback?.claimed===false&&exactTotals(afterRollback,0)&&receiptCount(afterRollback.state)===0,{rollback,activation:activationReceipts(afterRollback?.state),validation:afterRollback?.validation});
      for(const version of [1,2,3]){resetRecoveryClock();const imported=call('recovery','roundTripExportImport',version),afterImport=snap();add(`save-import-v${version}-reactivates-current-release-reward-neutral`,imported?.ok===true&&imported?.formatVersion===version&&imported?.terminalControlsClean===true&&currentReleaseActive(afterImport)&&afterImport?.claimed===false&&exactTotals(afterImport,0)&&receiptCount(afterImport.state)===0,{imported,activation:activationReceipts(afterImport?.state),validation:afterImport?.validation,totals:afterImport?.totals})}
      for(const [version,method] of [[13,'migrateSchema13'],[12,'migrateSchema12']]){resetRecoveryClock();const migrated=call('recovery',method,'established'),beforeProductionReload=snap(),productionReload=call('recovery','reload'),afterMigrationReload=snap();add(`schema${version}-migration-production-reload-activates-current-release`,migrated?.ok===true&&beforeProductionReload?.state?.schemaVersion===14&&productionReload?.ok===true&&productionReload?.actualProductionLoadPath===true&&currentReleaseActive(afterMigrationReload)&&afterMigrationReload?.claimed===false&&exactTotals(afterMigrationReload,0)&&receiptCount(afterMigrationReload.state)===0,{migrated,productionReload,beforeActivationHash:beforeProductionReload?.state?.durableProgression?.manifestHash,afterActivation:activationReceipts(afterMigrationReload?.state),validation:afterMigrationReload?.validation})}
      resetRecoveryClock();const thinSeed=call('recovery','migrateSchema13','fresh'),thinBefore=snap(),thinRaw=thinBefore?.raw,thinRevision=thinBefore?.state?.saveMeta?.revision,thinReload=call('recovery','reload'),thinAfter=snap(),thinRoot=thinAfter?.state?.durableProgression,thinTotals=thinRoot?.collections?.checkpoint?.totals;
      add('foundation-thin-schema14-defers-release-with-zero-write-and-zero-reward',thinSeed?.ok===true&&!thinBefore?.state?.tutorialProgress&&thinReload?.ok===true&&thinReload?.actualProductionLoadPath===true&&thinAfter?.raw===thinRaw&&thinAfter?.state?.saveMeta?.revision===thinRevision&&thinAfter?.validation?.ok===true&&thinRoot?.manifestHash===thinBefore?.state?.durableProgression?.manifestHash&&thinRoot?.manifestHash!==f.candidate.authoritySha256&&thinRoot?.activeReleaseIds?.length===0&&thinRoot?.collections?.claimedDefinitionIds?.length===0&&thinRoot?.collections?.recentGrantReceipts?.length===0&&thinTotals?.powerBps===0&&thinTotals?.earningsBps===0&&thinTotals?.expBps===0&&same(thinTotals?.facilityBpsByFacilityId,{}),{thinSeed,thinReload,beforeRevision:thinRevision,afterRevision:thinAfter?.state?.saveMeta?.revision,beforeHash:thinBefore?.state?.durableProgression?.manifestHash,afterHash:thinRoot?.manifestHash,validation:thinAfter?.validation,totals:thinTotals});
      window.__P24C2D_STORE__.thinHandoff={fixtureId:'phase24c2e.schema14-foundation-thin.v1',raw:thinAfter.raw,saveId:thinAfter.state.saveMeta.saveId,revision:thinAfter.state.saveMeta.revision};
    }

    async function thinScenario(){
      const handoff=window.__P24C2D_STORE__.thinHandoff,beforeRaw=activeRaw(),before=activeState(),beforeErrors=window.__P24C2D_ERRORS__.length,qaGlobals=['__EVERSTEAD_QA__','__EVERSTEAD_PHASE_12_QA__','__EVERSTEAD_PHASE_13_QA__','__EVERSTEAD_PHASE_23_QA__','__EVERSTEAD_PHASE_24C2C_QA__','__EVERSTEAD_PHASE_24C2D_QA__'].filter(name=>Object.hasOwn(window,name));
      add('foundation-thin-fixture-boots-through-non-qa-production-path',v.publicRelease===true&&v.fixtureId===handoff?.fixtureId&&beforeRaw===handoff?.raw&&before?.schemaVersion===14&&!before?.tutorialProgress&&qaGlobals.length===0&&!location.search.includes('qa=1'),{publicRelease:v.publicRelease,fixtureId:v.fixtureId,handoffFixtureId:handoff?.fixtureId,rawRestored:beforeRaw===handoff?.raw,schemaVersion:before?.schemaVersion,tutorialStatePresent:Boolean(before?.tutorialProgress),qaGlobals,search:location.search});
      await dismiss();const fellowship=document.querySelector('.bottom-nav [data-nav="fellows"]'),fellowshipInitiallyVisible=visible(fellowship);fellowship?.click();await wait(70);const familyTab=document.querySelector('[data-roster="family"]');familyTab?.click();await wait(70);const familyCardsBefore=[...document.querySelectorAll('[data-family]')],companionTab=document.querySelector('[data-roster="companions"]');companionTab?.click();await wait(110);const selectedCompanionTab=document.querySelector('[data-roster="companions"]'),afterRaw=activeRaw(),after=activeState(),companionCards=[...document.querySelectorAll('[data-phase23-companion-card]')],familyCardsAfter=[...document.querySelectorAll('[data-family]')],tutorialCards=[...document.querySelectorAll('[data-phase23-context-tutorial]')],currentFellowship=document.querySelector('.bottom-nav [data-nav="fellows"]');
      add('foundation-thin-schema14-real-click-journey-renders-companions-after-family',fellowshipInitiallyVisible&&visible(currentFellowship)&&familyCardsBefore.length===20&&selectedCompanionTab?.classList.contains('on')&&companionCards.length===20&&familyCardsAfter.length===0,{fellowshipInitiallyVisible,currentFellowshipVisible:visible(currentFellowship),familyTabPresent:Boolean(familyTab),companionTabPresent:Boolean(companionTab),familyCardsBefore:familyCardsBefore.length,companionCards:companionCards.length,familyCardsAfter:familyCardsAfter.length,tabClass:selectedCompanionTab?.className,appText:document.querySelector('#app')?.textContent.slice(0,500)});
      add('foundation-thin-schema14-tutorial-fallback-is-save-neutral',window.__P24C2D_ERRORS__.length===beforeErrors&&afterRaw===beforeRaw&&after?.saveMeta?.revision===before?.saveMeta?.revision&&!after?.tutorialProgress&&tutorialCards.length===0,{errorsBefore:beforeErrors,errorsAfter:window.__P24C2D_ERRORS__.length,rawUnchanged:afterRaw===beforeRaw,beforeRevision:before?.saveMeta?.revision,afterRevision:after?.saveMeta?.revision,tutorialStatePresent:Boolean(after?.tutorialProgress),tutorialCards:tutorialCards.length});
      const oathsNav=document.querySelector('.bottom-nav [data-nav="oaths"]');oathsNav?.click();await wait(80);const oath=document.querySelector('[data-oath="o1"]'),oathInitiallyVisible=visible(oath);oath?.click();await wait(110);const usedRaw=activeRaw(),used=activeState(),usedFellowship=document.querySelector('.bottom-nav [data-nav="fellows"]');usedFellowship?.click();await wait(70);const usedFamilyTab=document.querySelector('[data-roster="family"]');usedFamilyTab?.click();await wait(70);const usedCompanionTab=document.querySelector('[data-roster="companions"]');usedCompanionTab?.click();await wait(110);const usedAfterRaw=activeRaw(),usedAfter=activeState(),usedSelectedTab=document.querySelector('[data-roster="companions"]'),usedCompanionCards=[...document.querySelectorAll('[data-phase23-companion-card]')];
      add('foundation-thin-schema14-remains-playable-after-first-real-save',oathInitiallyVisible&&usedRaw!==afterRaw&&used?.saveMeta?.revision===after?.saveMeta?.revision+1&&!used?.tutorialProgress&&usedSelectedTab?.classList.contains('on')&&usedCompanionCards.length===20,{oathInitiallyVisible,tutorialStatePresent:Boolean(used?.tutorialProgress),beforeRevision:after?.saveMeta?.revision,afterRevision:used?.saveMeta?.revision,selectedTab:usedSelectedTab?.className,companionCards:usedCompanionCards.length});
      add('foundation-thin-post-use-roster-navigation-is-save-neutral',usedAfterRaw===usedRaw&&usedAfter?.saveMeta?.revision===used?.saveMeta?.revision&&window.__P24C2D_ERRORS__.length===beforeErrors,{rawUnchanged:usedAfterRaw===usedRaw,beforeRevision:used?.saveMeta?.revision,afterRevision:usedAfter?.saveMeta?.revision,errorsBefore:beforeErrors,errorsAfter:window.__P24C2D_ERRORS__.length});
    }

    (async()=>{if(v.publicRelease===true){for(let attempt=0;attempt<240&&!document.querySelector('.bottom-nav');attempt++)await wait(25);if(!document.querySelector('.bottom-nav'))throw new Error('Non-QA production navigation unavailable')}else{for(let attempt=0;attempt<240&&!bridge();attempt++)await wait(25);if(!bridge())throw new Error('Phase 24C-2D bridge unavailable')}await wait(350);await dismiss();if(v.scenario==='claim')await claimScenario();else if(v.scenario==='reload')await reloadScenario();else if(v.scenario==='thin')await thinScenario();else throw new Error(`Unknown scenario ${v.scenario}`);add('isolated-adapter-never-used-native-storage',window.__P24C2D_NATIVE_INSTRUMENTED__===true&&window.__P24C2D_NATIVE_ACCESSES__.length===0,window.__P24C2D_NATIVE_ACCESSES__);add('zero-warning-error-console',window.__P24C2D_ERRORS__.length===0,window.__P24C2D_ERRORS__);send()})().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';
  (async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();if(!source.includes('phase24c2dInstallQaBridge'))throw new Error('Phase 24C-2D integration is missing');source=source.replace('<head>','<head><base href="../../">');const firstScript=source.indexOf('<script'),bodyClose=source.lastIndexOf('</body>');if(firstScript<0||bodyClose<0)throw new Error('Production document boundaries are missing');const runtime=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${installSuite.toString()})()<\/script>`;source=source.slice(0,firstScript)+runtime+source.slice(firstScript,bodyClose)+suite+source.slice(bodyClose);document.open();document.write(source);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,scenario:'loader',results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:String(error.stack||error.message)}],errors:[String(error.stack||error.message)]},'*'));
})();
