(()=>{
  'use strict';
  const CHANNEL='everstead-phase-24c2d-integration-v1',byId=id=>document.getElementById(id),escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),row=(id,pass,detail='')=>({id,actual:Boolean(pass),expected:true,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)});
  const loadJson=async url=>{const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`${url}: HTTP ${response.status}`);return response.json()};
  function realm(contract,viewport){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe');frame.width=String(viewport.width);frame.height=String(viewport.height);frame.style.cssText=`position:fixed;left:-10000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0;visibility:visible`;frame.name=JSON.stringify({channel:CHANNEL,nonce,contract,viewport});let timer;const finish=(error,rows)=>{clearTimeout(timer);removeEventListener('message',receive);frame.remove();error?reject(error):resolve(rows)},receive=event=>{const data=event.data;if(data?.channel!==CHANNEL||data?.nonce!==nonce)return;const rows=Array.isArray(data.results)?data.results:[];if(Array.isArray(data.errors)&&data.errors.length)rows.push(row(`${viewport.id}-captured-runtime-errors`,false,data.errors));finish(null,rows)};timer=setTimeout(()=>finish(new Error(`${viewport.id} realm timed out`)),90000);addEventListener('message',receive);frame.src=`./realm.html?qa=1&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  function render(mode,rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('mode').textContent=mode;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)} · observed ${item.actual?'true':'false'} · expected true${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_24C2D_RESULT__={complete:true,mode,passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const contract=await loadJson('./contract.json'),rows=[];rows.push(row('contract-phase-24c2d-schema14',contract.contractVersion===1&&contract.phase==='24C-2D'&&contract.schemaVersion===14));rows.push(row('contract-one-permanent-restaurant-grant',contract.release.id==='release.phase-24c2d.founding-table.v1'&&contract.release.grantId==='collection.grant.restaurant.founding-table.facility.v1'&&contract.release.facilityId==='facility.restaurant'&&contract.release.bps===200));rows.push(row('contract-exact-three-founding-recipes',contract.release.recipeIds.join(',')==='restaurant.recipe.hearth-stew,restaurant.recipe.garden-flatbread,restaurant.recipe.roadside-tea'));rows.push(row('contract-two-mobile-realms',contract.viewports.length===2&&contract.viewports[0].width===320&&contract.viewports[0].height===568&&contract.viewports[1].width===390&&contract.viewports[1].height===844&&contract.viewports[1].reducedMotion===true));window.__P24C2D_SHARED_STORES__=new Map(contract.viewports.map(item=>[item.sharedId,{slots:new Map(),writes:[],handoff:null,saveIndex:0,transactionIndex:0}]));for(const viewport of contract.viewports){byId('progress').textContent=`${viewport.id}`;rows.push(...await realm(contract,viewport))}render('CANDIDATE',rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render('FATAL',[row('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
