import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..'),rows=[];
const read=relative=>fs.readFileSync(path.join(root,relative),'utf8'),hashBytes=value=>crypto.createHash('sha256').update(value).digest('hex'),fileHash=relative=>hashBytes(fs.readFileSync(path.join(root,relative))),same=(left,right)=>JSON.stringify(left)===JSON.stringify(right),count=(source,token)=>source.split(token).length-1;
const contract=JSON.parse(read('qa/phase-24c2d-integration/contract.json')),candidate=read(contract.candidate.indexPath),authority=read(contract.candidate.authorityPath),realm=read('qa/phase-24c2d-integration/realm.js'),runner=read('qa/phase-24c2d-integration/runner.js');
let passed=0,failed=0;const failures=[];
function check(id,condition,detail=''){if(condition){passed++;rows.push({id,pass:true});return}failed++;rows.push({id,pass:false});failures.push({id,detail:typeof detail==='string'?detail:JSON.stringify(detail)})}
function between(source,start,end){const from=source.indexOf(start),to=source.indexOf(end,from<0?0:from+start.length);return from<0||to<0?'':source.slice(from,to+end.length)}

check('contract-is-phase24c2d-schema14-release-candidate',contract.contractVersion===1&&contract.phase==='24C-2D'&&contract.schemaVersion===14&&contract.status==='release-candidate-final-identities-frozen');
check('contract-exact-one-permanent-restaurant-grant',contract.release.id==='release.phase-24c2d.founding-table.v1'&&contract.release.grantId==='collection.grant.restaurant.founding-table.facility.v1'&&contract.release.facilityId==='facility.restaurant'&&contract.release.bps===200);
check('contract-exact-three-current-founding-recipes',same(contract.release.recipeIds,['restaurant.recipe.hearth-stew','restaurant.recipe.garden-flatbread','restaurant.recipe.roadside-tea']));
check('contract-exact-two-gradual-tutorials',same(contract.tutorials.map(item=>[item.id,item.actorId]),[['tutorial.phase-24c.collection-first-ready.v1','family.isolde'],['tutorial.phase-24c.collection-first-claim.v1','fellow.lyra']]));
check('contract-three-real-mobile-viewports-including-non-qa-thin-save',contract.viewports.length===3&&contract.viewports[0].scenario==='claim'&&contract.viewports[0].width===320&&contract.viewports[0].height===568&&contract.viewports[1].scenario==='reload'&&contract.viewports[1].width===390&&contract.viewports[1].height===844&&contract.viewports[1].reducedMotion===true&&contract.viewports[2].scenario==='thin'&&contract.viewports[2].fixtureId==='phase24c2e.schema14-foundation-thin.v1'&&contract.viewports[2].publicRelease===true);
check('contract-pins-exact-production-storage-keys',contract.storage.activeKey==='oathforge_new_world_proto_v01'&&contract.storage.stagingKey==='oathforge_new_world_proto_v01__staging'&&candidate.includes("const NS='oathforge_new_world_proto_v01'")&&candidate.includes("STAGING_KEY=NS+'__staging'"));
check('contract-formula-cases-pin-floor-boundaries',same(contract.formula.cases,[{baseSaleGold:1,beforeClaim:1,afterClaim:1},{baseSaleGold:99,beforeClaim:99,afterClaim:100},{baseSaleGold:101,beforeClaim:101,afterClaim:103},{baseSaleGold:10000,beforeClaim:10000,afterClaim:10200}]));

check('authority-source-hash-frozen',fileHash(contract.candidate.authorityPath)===contract.candidate.authoritySourceSha256,fileHash(contract.candidate.authorityPath));
check('candidate-index-hash-frozen-after-integration-review',/^[0-9a-f]{64}$/.test(contract.candidate.indexSha256)&&fileHash(contract.candidate.indexPath)===contract.candidate.indexSha256,{expected:contract.candidate.indexSha256,actual:fileHash(contract.candidate.indexPath)});
check('authority-loader-markers-exactly-once',count(candidate,'<!-- Phase 24C-2D Founding Table successor authority load BEGIN -->')===1&&count(candidate,'<!-- Phase 24C-2D Founding Table successor authority load END -->')===1&&count(candidate,'src/phase24c2d-founding-table-release-authority.js?v=phase24c2d-v1')===1);
check('integration-and-bridge-install-markers-exactly-once',count(candidate,'/* Phase 24C-2D Founding Table Collection integration BEGIN */')===1&&count(candidate,'/* Phase 24C-2D Founding Table Collection integration END */')===1&&count(candidate,'/* Phase 24C-2D Founding Table QA bridge install BEGIN */')===1&&count(candidate,'/* Phase 24C-2D Founding Table QA bridge install END */')===1&&count(candidate,'phase24c2dInstallQaBridge();')===1);
check('phase24c2e-compatibility-hotfix-markers-exactly-once',count(candidate,'/* Phase 24C-2E migrated tutorial-state compatibility hotfix BEGIN */')===1&&count(candidate,'/* Phase 24C-2E migrated tutorial-state compatibility hotfix END */')===1);
check('successor-authority-loads-before-inline-runtime',candidate.indexOf('src/phase24c2d-founding-table-release-authority.js')<candidate.indexOf("(()=>{'use strict'"));
const integration=between(candidate,'/* Phase 24C-2D Founding Table Collection integration BEGIN */','/* Phase 24C-2D Founding Table Collection integration END */');
const compatibility=between(integration,'/* Phase 24C-2E migrated tutorial-state compatibility hotfix BEGIN */','/* Phase 24C-2E migrated tutorial-state compatibility hotfix END */');
check('immediate-migration-render-allows-only-current-save-neutral-ui-projection',compatibility.includes('state!==S')&&compatibility.includes("checked.errors[0]!=='phase24c2c.immediate-migration-target'")&&compatibility.includes('typeof PERSISTED_RAW!==\'string\'')&&compatibility.includes('phase24c2cValidateBeforePhase24C2E(persisted,physical)')&&compatibility.includes('comparable.ui=clone(persisted.ui)')&&compatibility.includes('comparable.featured=persisted.featured')&&compatibility.includes('JSON.stringify(comparable)===PERSISTED_RAW?{ok:true,errors:[]}:checked'));
check('missing-tutorial-state-has-defensive-read-view-and-disabled-actions',compatibility.includes('PHASE_24C2E_EMPTY_TUTORIAL_PROGRESS')&&compatibility.includes('function phase24c2eTutorialStateAvailable')&&compatibility.includes('function phase24c2eTutorialProgressView')&&compatibility.includes("return'unavailable'")&&compatibility.includes("reason:'tutorial-state-unavailable',writes:0,rewardApplications:0")&&compatibility.includes("phase24c2eTutorialStateAvailable(S)?phase23TutorialCardBeforePhase24C2E(ids):''"));
check('compatibility-hotfix-is-save-neutral-and-does-not-fabricate-foundations',!compatibility.includes('mutatePersisted')&&!compatibility.includes('commitPrepared')&&!compatibility.includes('tutorialProgress=')&&!compatibility.includes('phase24c2dEnsureFoundations'));
check('runtime-authenticates-exact-frozen-authority',integration.includes("authorityId!=='phase-24c2d-founding-table-release-authority.v1'")&&integration.includes("deployedCommit!=='2770bb95a970eaef93db65fe4ade39172943fc5e'")&&integration.includes('validateReleaseAuthority(PHASE_24C2D_AUTHORITY).ok!==true')&&integration.includes('authorityHash(PHASE_24C2D_AUTHORITY)!==PHASE_24C2D_AUTHORITY_HASH'));
check('activation-is-schema14-to-schema14-and-reward-neutral',integration.includes("PHASE_24C2D_ACTIVATION_ID='authority-epoch.phase-24c2c-to-phase-24c2d.founding-table.v1'")&&integration.includes('from:14,to:14')&&integration.includes('rewardApplications:0')&&integration.includes('activatedReleaseIds:[PHASE_24C2D_RELEASE_ID]'));
check('activation-validates-zero-authority-predecessor-before-commit',integration.includes('phase24c2cValidateBeforePhase24C2D(S,physical)')&&integration.includes("predecessor-authority: ${sourceChecked.errors.join(', ')}")&&integration.includes("mutatePersisted((state,now)=>phase24c2dActivateInState(state,now),PHASE_24C2D_ACTIVATION_SOURCE"));
check('post-save-tool-adoption-reactivates-or-blocks-fail-closed',integration.includes('function phase24c2dPostSaveToolActivation')&&integration.includes("!['source','target'].includes(result.outcome)")&&integration.includes("'phase24c2d-post-adoption-activation'")&&integration.includes('phaseElevenBTwoRunTransactionBeforePhase24C2D'));
check('boot-and-reload-retarget-through-activation',integration.includes('const bootstrapPersistenceBeforePhase24C2D=bootstrapPersistence')&&integration.includes('const persistenceActionBeforePhase24C2D=persistenceAction')&&integration.includes('phase24c2dEnsureActivated({renderAfter:false})'));
check('foundation-thin-schema14-defers-without-reward-or-write',integration.includes('function phase24c2dFoundationActivationDeferred')&&integration.includes("reason:'legacy-foundation-migration-pending'")&&integration.includes('writes:0,rewardApplications:0')&&realm.includes('foundation-thin-schema14-defers-release-with-zero-write-and-zero-reward'));
check('legacy-schema12-qa-fixture-preserves-construction-time-after-adoption',candidate.includes('phase23QaAdoptLegacySeed(context);QA_CLOCK_NOW=at;CURRENT_SCHEMA_VERSION=12;phaseElevenGEnsureActivated()'));

check('readiness-is-discovery-plus-exact-three-masteries',integration.includes('function phase24c2dCollectionReady')&&integration.includes('phase24c2dRestaurantDiscovered(state)&&phase24c2dRecipeProgress(state).complete')&&contract.release.recipeIds.every(id=>integration.includes(id)));
check('claim-uses-foundation-capture-preview-finalize-chain',integration.includes('captureCollectionGrantPayload')&&integration.includes('previewCollectionGrant')&&integration.includes('finalizeCollectionGrant')&&integration.includes("PHASE_24C2D_CLAIM_SOURCE,{renderAfter:false,allowRefusal:true}"));
check('claim-remains-manual-and-exactly-once-refuses',integration.includes("phase24c2dCollectionClaimed(S)?'already-claimed':'not-ready'")&&integration.includes('rewardApplications:1')&&integration.includes('data-phase24c2d-claim'));
check('validation-permits-only-zero-or-exact-200-restaurant-pool',integration.includes("errors.push('phase24c2d.pool-boundary')")&&integration.includes('!claimed&&facilityBps!==0||claimed&&facilityBps!==200')&&integration.includes("id!==PHASE_24C2D_FACILITY_ID"));
check('formula-is-base-only-floor-then-safe-added-to-authored-total',integration.includes('function phase24c2dRestaurantClaimGold(state,baseSaleGold,authoredTotalGold=baseSaleGold)')&&integration.includes("evaluateAdditivePool(baseSaleGold,0,bps,{rounding:'floor'})")&&integration.includes("safeAddInteger(authoredTotalGold,collectionGold,'Restaurant Collection Gold')"));
check('real-restaurant-serve-captures-base-only-bonus-at-offer-creation',candidate.includes('amount:phase24c2dRestaurantClaimGold(state,planned.baseSaleGold,planned.totalGold)'));
check('restaurant-claim-accounting-uses-captured-offer-reward',candidate.includes('const plan=phaseSixteenFinalizerPlan(state,liveOffer,live),actualGold=phase24c2dRewardGold(plan.rewards)')&&candidate.includes("local.profitGold=safeAddInteger(local.profitGold,actualGold,'Restaurant profit Gold')")&&candidate.includes("metric.gold-claimed-after-activation'],actualGold"));
check('restaurant-ui-discloses-captured-vs-authored-values',integration.includes('phase24c2d-restaurant-breakdown')&&integration.includes('<span>Sale<b>')&&integration.includes('<span>Tip<b>')&&integration.includes('<span>Collection<b>')&&integration.includes('<span>Authored total<b>')&&integration.includes('<span>Final claim<b>'));

check('tutorials-are-optional-skippable-replayable-reward-neutral',integration.includes('PHASE_24C2D_TUTORIAL_AUTHORITY_ROWS.map')&&contract.tutorials.every(row=>integration.includes(`'${row.id}'`)&&integration.includes(`'${row.actorId}'`))&&integration.includes('row.optional!==true')&&integration.includes('row.skippable!==true')&&integration.includes('row.replayable!==true')&&integration.includes('row.rewardNeutral!==true')&&integration.includes("!['open','complete','skip','replay'].includes(action)")&&integration.includes('rewardApplications:0'));
check('tutorial-validation-rejects-duplicate-steps-and-completion-receipts',integration.includes('seenCount<0||seenCount>1')&&integration.includes('completedCount<0||completedCount>1')&&integration.includes('dismissedCount<0||dismissedCount>1')&&integration.includes('receiptCount<0||receiptCount>1')&&integration.includes('completed!==(receiptCount===1)'));
check('bounded-tutorial-tamper-probe-has-two-fixed-write-free-candidates',integration.includes("mode==='duplicate-step'")&&integration.includes("mode==='duplicate-receipt'")&&integration.includes("checked.errors.includes('phase24c2d.tutorial')")&&integration.includes('writes:0')&&integration.includes('rawUnchanged:PERSISTED_RAW===beforeRaw')&&integration.includes('revisionUnchanged:S.saveMeta.revision===beforeRevision'));
check('tutorial-log-is-discovery-gated-and-terminal-replay-has-close-only',integration.includes('function phase24c2dTutorialVisible')&&integration.includes('phase24c2dRestaurantDiscovered(state)||status!==\'available\'||replays>0')&&integration.includes('PHASE_24C2D_TUTORIAL_DEFS.filter(item=>phase24c2dTutorialVisible(item))')&&integration.includes("terminal?`<button class=\"btn primary\" data-modal-close>CLOSE</button>")&&integration.includes('data-phase13-tutorial-action="log"'));
check('claimed-collection-lesson-has-priority-over-ready-lesson',integration.includes("candidate=claimed&&phaseThirteenTutorialStatus(claimTutorial)==='available'?claimTutorial:ready&&phaseThirteenTutorialStatus(readyTutorial)==='available'?readyTutorial:null"));
check('tutorial-copy-explains-manual-bank-and-capture-time',integration.includes('reward is banked permanently until you claim it')&&integration.includes('rewards that were already waiting keep their original value'));
check('codex-card-exposes-0-through-3-state-and-four-pools',integration.includes('${progress.count} / 3 founding recipes served')&&integration.includes('Collection Power')&&integration.includes('Collection Earnings')&&integration.includes('Collection EXP')&&integration.includes('Restaurant facility'));
check('mobile-css-includes-320-collapse-and-reduced-motion',candidate.includes('@media(max-width:340px)')&&candidate.includes('@media(prefers-reduced-motion:reduce)')&&candidate.includes('.phase24c2d-equation{grid-template-columns:1fr}'));

const bridgeBlock=between(integration,'function phase24c2dInstallQaBridge()','/* Phase 24C-2D Founding Table Collection integration END */');
check('qa-bridge-is-exactly-gated-to-isolated-destructive-boundary',bridgeBlock.includes('if(!QA_BRIDGE_ALLOWED||!QA_ALLOW_DESTRUCTIVE)return false')&&bridgeBlock.includes('requireQaDestructiveAuthorization()')&&bridgeBlock.includes("get:()=>QA_ALLOW_DESTRUCTIVE&&qaBridgeAllowed()?bridge:undefined"));
check('qa-bridge-is-frozen-nonenumerable-bounded-surface',bridgeBlock.includes('const read=Object.freeze')&&bridgeBlock.includes('destructive=Object.freeze')&&bridgeBlock.includes('bridge=Object.freeze')&&bridgeBlock.includes('configurable:true,enumerable:false')&&contract.bridge.readMethods.every(name=>bridgeBlock.includes(`${name}:`))&&contract.bridge.destructiveMethods.every(name=>bridgeBlock.includes(`${name}:`)));
check('qa-bridge-has-no-generic-state-storage-or-callback-writer',!/(writeRaw|setItem|removeItem|import|export|callback|eval|Function|grantPayload|previewCollection|finalizeCollection)/.test(bridgeBlock));

check('browser-realm-fetches-real-index-and-injects-distinct-memory-storage',realm.includes("fetch('../../index.html'")&&realm.includes('__EVERSTEAD_RUNTIME__')&&realm.includes('storage:memoryStorage')&&realm.includes('allowDestructive:true,isolatedStorage:true')&&realm.includes('__EVERSTEAD_PERSISTENCE_TEST__'));
check('browser-shared-origin-ids-remain-monotonic-across-page-realms',runner.includes('saveIndex:0,transactionIndex:0')&&realm.includes('++shared.saveIndex')&&realm.includes('++shared.transactionIndex')&&!realm.includes('let saveIndex=0,transactionIndex=0'));
check('browser-realm-instruments-and-rejects-native-storage-use',realm.includes('__P24C2D_NATIVE_ACCESSES__')&&realm.includes('isolated-adapter-never-used-native-storage')&&realm.includes('window.localStorage'));
check('browser-covers-activation-zero-and-0-to-3-readiness',['activation-exactly-once-and-reward-neutral','initial-zero-reward-and-zero-global-pools','initial-0-of-3-exact-recipe-readiness','completion-reaches-exact-3-of-3-ready-with-zero-reward'].every(id=>realm.includes(id)));
check('browser-reaches-restaurant-through-real-village-phase17-watch-route',['isolated-fixture-seeds-only-canonical-phase17-restaurant-discovery','real-village-restaurant-hotspot-opens-phase17-introduction','phase17-watch-route-opens-production-phase16-restaurant'].every(id=>realm.includes(id)));
check('browser-covers-exactly-once-visible-claim-result-return-and-real-reload',['visible-claim-button-opens-result-with-exact-equation-and-return','manual-visible-claim-exact-single-receipt-and-200-bps','duplicate-collection-claim-refuses-with-zero-write','return-to-codex-path-introduces-claim-tutorial-by-lyra','reload-preserves-exactly-one-collection-receipt','reload-duplicate-claim-still-refuses-write-free'].every(id=>realm.includes(id)));
check('browser-covers-independent-floor-formula-cases',realm.includes('Math.floor(postOutcome.baseSaleGold*f.release.bps/10000)')&&realm.includes('postclaim-formula-')&&realm.includes('reload-formula-'));
check('browser-covers-pre-ready-immutability-and-post-claim-real-capture',['pre-ready-offer-remains-byte-identical-after-collection-claim','postclaim-real-service-captures-base-only-floor-plus-authored-tip','postclaim-capture-does-not-reprice-earlier-ready-offer'].every(id=>realm.includes(id)));
check('browser-covers-both-tutorials-log-gating-priority-and-terminal-replay',['ready-tutorial-auto-introduced-by-isolde','return-to-codex-path-introduces-claim-tutorial-by-lyra','ready-tutorial-completion-reward-neutral','claim-tutorial-skip-is-optional-and-reward-neutral','tutorial-replay-is-reward-neutral','collection-tutorial-log-rows-hidden-before-restaurant-discovery','collection-tutorial-log-rows-visible-after-discovery','claimed-lesson-has-priority-over-ready-lesson','terminal-replay-modal-offers-close-not-inert-done-or-skip'].every(id=>realm.includes(id)));
check('browser-covers-duplicate-tutorial-step-and-receipt-refusal',realm.includes("for(const kind of ['duplicate-step','duplicate-receipt'])")&&realm.includes('tutorial-${kind}-candidate-is-rejected-write-free'));
check('browser-covers-mobile-accessibility-overflow-and-reduced-motion',['ready-mobile-codex-card-3-of-3-accessible','claimed-mobile-layout-and-reduced-motion-contract','reload-390x844-claimed-card-visible-and-accessible','reload-390x844-no-horizontal-overflow-reduced-motion'].every(id=>realm.includes(id)));
check('browser-covers-safe-reset-rollback-import-and-schema-migration-reactivation',['safe-reset-reactivates-current-release-reward-neutral','rollback-restore-reactivates-current-release-reward-neutral','save-import-v${version}-reactivates-current-release-reward-neutral','schema${version}-migration-production-reload-activates-current-release'].every(id=>realm.includes(id)));
check('browser-covers-non-qa-fresh-and-used-thin-save-family-to-companion-journeys',realm.includes("fixtureId:'phase24c2e.schema14-foundation-thin.v1'")&&runner.includes("viewport.publicRelease===true?`./realm.html?nonce=")&&realm.includes("if(config.viewport.publicRelease!==true)runtime.qa=")&&realm.includes("!location.search.includes('qa=1')")&&realm.includes("document.querySelector('.bottom-nav [data-nav=\"fellows\"]')")&&realm.includes('familyTab?.click()')&&realm.includes('companionTab?.click()')&&realm.includes("document.querySelector('[data-oath=\"o1\"]')")&&['foundation-thin-fixture-boots-through-non-qa-production-path','foundation-thin-schema14-real-click-journey-renders-companions-after-family','foundation-thin-schema14-tutorial-fallback-is-save-neutral','foundation-thin-schema14-remains-playable-after-first-real-save','foundation-thin-post-use-roster-navigation-is-save-neutral'].every(id=>realm.includes(id)));
check('browser-recovery-fixtures-reset-isolated-clock-with-zero-storage-writes',realm.includes('const resetRecoveryClock=')&&realm.includes('baseBridge()?.clock?.reset?.()')&&realm.includes("throw new Error('The isolated recovery clock could not be reset without storage writes')")&&count(realm,'resetRecoveryClock();')===5);
check('browser-covers-clean-console-and-publishes-complete-result',realm.includes('zero-warning-error-console')&&runner.includes('__EVERSTEAD_PHASE_24C2D_RESULT__={complete:true')&&runner.includes('run();'));
check('browser-source-has-no-temporary-diagnostics',!/(P24C2D_PREDECESSOR_PROBES|diagnosticProjection|diagnosticValidation|diagnosticMessage)/.test(realm));

let projection=candidate;
const removeBlock=(start,end)=>{const body=between(projection,start,end);if(body)projection=projection.replace(body+'\n','').replace(body,'')};
const styleStart='  <style>\n    .phase24c2d-collection',styleAt=projection.indexOf(styleStart);if(styleAt>=0){const styleEnd=projection.indexOf('  </style>\n',styleAt);if(styleEnd>=0)projection=projection.slice(0,styleAt)+projection.slice(styleEnd+'  </style>\n'.length)}
removeBlock('  <!-- Phase 24C-2D Founding Table successor authority load BEGIN -->','  <!-- Phase 24C-2D Founding Table successor authority load END -->');
removeBlock('/* Phase 24C-2D Founding Table Collection integration BEGIN */','/* Phase 24C-2D Founding Table Collection integration END */');
removeBlock('/* Phase 24C-2D Founding Table QA bridge install BEGIN */','/* Phase 24C-2D Founding Table QA bridge install END */');
projection=projection.replace('amount:phase24c2dRestaurantClaimGold(state,planned.baseSaleGold,planned.totalGold)','amount:planned.totalGold');
projection=projection.replace('const plan=phaseSixteenFinalizerPlan(state,liveOffer,live),actualGold=phase24c2dRewardGold(plan.rewards);','const plan=phaseSixteenFinalizerPlan(state,liveOffer,live);').replace("local.profitGold=safeAddInteger(local.profitGold,actualGold,'Restaurant profit Gold')","local.profitGold=safeAddInteger(local.profitGold,outcome.totalGold,'Restaurant profit Gold')").replace("metric.gold-claimed-after-activation']=safeAddInteger(state.legacyProgress.metricDeltas['metric.gold-claimed-after-activation'],actualGold,'Restaurant claimed Gold metric')","metric.gold-claimed-after-activation']=safeAddInteger(state.legacyProgress.metricDeltas['metric.gold-claimed-after-activation'],outcome.totalGold,'Restaurant claimed Gold metric')");
projection=projection.replace('commitSuccessorStoryInState:(state,contentId,now)=>{const committed=PHASE_1819_RUNTIME?.commitStoryContentInState?.(state,contentId,now);phase24c2dReconcileRestaurantStoryInState(state,contentId,now);return committed}','commitSuccessorStoryInState:(state,contentId,now)=>PHASE_1819_RUNTIME?.commitStoryContentInState?.(state,contentId,now)');
projection=projection.replace('phase23QaAdoptLegacySeed(context);QA_CLOCK_NOW=at;CURRENT_SCHEMA_VERSION=12;','phase23QaAdoptLegacySeed(context);CURRENT_SCHEMA_VERSION=12;');
check('historical-production-projection-is-byte-identical-to-deployed-predecessor',hashBytes(projection)===contract.candidate.predecessorIndexSha256,{expected:contract.candidate.predecessorIndexSha256,actual:hashBytes(projection)});

for(const file of ['qa/phase-24c2d-integration/realm.js','qa/phase-24c2d-integration/runner.js','qa/phase-24c2d-integration/verify.mjs']){const syntax=spawnSync(process.execPath,['--check',file],{cwd:root,encoding:'utf8'});check(`syntax-${path.basename(file)}`,syntax.status===0,syntax.stderr)}
for(const file of ['contract.json','index.html','realm.html','realm.js','runner.js','README.md','RESULT.md','checksums.sha256','verify.mjs'])check(`package-file-${file}-present`,fs.existsSync(path.join(here,file)));

for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}`);
console.log(`RESULT ${passed} passed, ${failed} failed`);
if(failures.length)console.error(JSON.stringify(failures,null,2));
process.exitCode=failed?1:0;
