(() => {
  'use strict';
  const CHANNEL='everstead-phase-17-independent',json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');
  function installRuntime(config){
    const slots=new Map(),writes=[],errors=[],nativeStorageAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);let saveIndex=0,transactionIndex=0,nativeStorageInstrumented=false;
    window.matchMedia=query=>({matches:config.viewport.reducedMotion&&query==='(prefers-reduced-motion: reduce)',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});document.documentElement.style.fontSize=`${config.viewport.copyScale||1}em`;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>{key=String(key);writes.push({op:'set',key,value:String(value)});slots.set(key,String(value))},removeItem:key=>{key=String(key);writes.push({op:'remove',key});slots.delete(key)}};
    Object.assign(window,{__P17I_CONFIG__:config,__P17I_ERRORS__:errors,__P17I_NATIVE_ACCESSES__:nativeStorageAccesses,__P17I_NATIVE_INSTRUMENTED__:nativeStorageInstrumented});window.__EVERSTEAD_RUNTIME__={storage:memoryStorage,clock:{now:()=>config.fixtures.frozenNow,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.375,confirm:()=>true,ids:{save:()=>`save-p17i-${++saveIndex}`,transaction:()=>`tx-p17i-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
  }
  function runSuite(){
    const config=window.__P17I_CONFIG__,f=config.fixtures,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),until=async(predicate,limit=8000)=>{const started=performance.now();while(performance.now()-started<limit){if(predicate())return true;await wait(25)}return false},same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),unique=values=>new Set(values).size===values.length,sorted=values=>[...new Set(values)].sort();
    const add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),send=()=>parent.postMessage({channel:config.channel,nonce:config.nonce,results,errors:window.__P17I_ERRORS__.slice()},'*'),bridge=()=>window.__EVERSTEAD_PHASE_17_QA__,safe=(label,fn)=>{try{return fn()}catch(error){add(label,false,error.stack||error.message);return null}},call=(group,name,...args)=>safe(`${name}-call`,()=>bridge()[group][name](...args));
    const state=snapshot=>snapshot?.state||null,revision=snapshot=>state(snapshot)?.saveMeta?.revision,story=data=>data?.storyV1||data?.story||{},queue=data=>story(data)?.queuedSceneItems||story(data)?.queue||[],chronicle=data=>story(data)?.chronicleRecords||[],offers=data=>data?.storyOffers||data?.claims?.storyOffers||[],facilities=data=>data?.board?.facilities||data?.facilities||[],visuals=data=>data?.village?.activeChangeIds||data?.activeVillageChangeIds||[],tutorials=data=>data?.tutorials?.items||data?.tutorials||[],resources=data=>data?.resources||{},roster=data=>data?.roster||{},storyProjection=data=>({story:story(data),facilities:facilities(data),visuals:visuals(data),tutorials:tutorials(data),offers:offers(data)});
    (async()=>{
      await until(()=>bridge(),5000);const qa=bridge();add('bridge-present',Boolean(qa));if(!qa){add('phase17-contract-unavailable',false,'Expected before Phase 17 implementation: window.__EVERSTEAD_PHASE_17_QA__ is absent.');send();return}
      add('bridge-version',qa.version===f.bridgeVersion,qa.version);const requiredRead=['definitions','snapshot','validate','derive','raw','exportSave','passiveBaseline','chronicle'],requiredDestructive=['resetFixture','event','openStory','openChronicle','resolveScene','replayScene','clearStage','tutorial','safeVisit','advanceOffline','reload','importFixture','claim','simulateConcurrent','mutateInvalid','probeFinalizerFailure'];add('bridge-read-surface',requiredRead.every(name=>typeof qa.read?.[name]==='function'),Object.keys(qa.read||{}));add('bridge-destructive-surface',requiredDestructive.every(name=>typeof qa.destructive?.[name]==='function'),Object.keys(qa.destructive||{}));if(!requiredRead.every(name=>typeof qa.read?.[name]==='function')||!requiredDestructive.every(name=>typeof qa.destructive?.[name]==='function')){send();return}
      const defs=call('read','definitions');if(!defs){send();return}
      add('inherited-phase12-through-phase16-seams',defs.inherited?.phase12Coordinator===true&&defs.inherited?.phase13StoryTutorialCast===true&&defs.inherited?.phase15PhysicalBoard===true&&defs.inherited?.phase15V2Archive===true&&defs.inherited?.phase16Restaurant===true&&defs.inherited?.phase16BridgeVersion===f.phase16BridgeVersion,defs.inherited);
      add('definition-lineage',defs.schemaVersion===f.schemaVersion&&defs.storySchemaVersion===f.storySchemaVersion&&same(defs.definitionSetIds,f.definitionSetIds)&&defs.book?.id===f.bookId,defs);
      add('six-sections-ten-stage-mappings',same((defs.chapters||[]).map(item=>item.id),f.chapterIds)&&same((defs.stageMappings||[]).map(item=>[item.stageId,item.stageName,item.introSceneId,item.resolutionSceneId]),f.stageMappings),defs.stageMappings);
      add('thirty-one-unique-scenes',same((defs.scenes||[]).map(item=>item.id),f.sceneIds)&&unique((defs.scenes||[]).map(item=>item.id))&&defs.scenes.every(item=>item.definitionVersion===1&&item.replayable===true),defs.scenes);
      add('rank-arrival-order-exact',same((defs.arrivalOrder||[]).map(item=>[item.rank,item.sceneId]),f.arrivalScenes)&&defs.arrivalOrder.every(item=>item.grantsRoster===false),defs.arrivalOrder);
      add('story-rewards-native-manual-and-disabled',(defs.rewards||[]).map(item=>item.id).every((id,index)=>id===f.rewardDefinitionIds[index])&&defs.rewards.every(item=>item.sourceType===f.storyRewardSourceType&&item.rewards==null&&item.productionEnabled===false&&item.claimMode==='manual'&&item.expires===false),defs.rewards);
      const facilityDefs=defs.facilities||[];add('twelve-canonical-facility-unlocks',same(facilityDefs.map(item=>[item.id,item.mapAnchor,item.targetPhase,item.discoveryContentId,item.requiredCapabilityId,item.openingContentId]),f.facilityUnlocks)&&unique(facilityDefs.map(item=>item.mapAnchor)),facilityDefs);
      add('facility-scoped-anchor-aliases',same(defs.facilityScopedAnchorAliases,f.facilityScopedAnchorAliases)&&defs.anchorPolicy?.unscopedRegionalAliasNotFacilityTarget===true&&f.regionalAnchorIds.every(id=>defs.anchorPolicy?.regionalAnchorIds?.includes(id)),defs.anchorPolicy);
      add('story-capability-opening-separate',defs.facilityRules?.storyIsDiscoveryAuthority===true&&defs.facilityRules?.activeInteractionNeedsCapabilityAndOpening===true&&defs.facilityRules?.passiveBuildingStateIsIndependent===true&&defs.facilityRules?.neverRelockOperationalSuccessor===true&&defs.facilityRules?.prosperityThreshold==null&&defs.facilityRules?.headquartersThreshold==null,defs.facilityRules);
      add('eight-derived-static-fallback-visuals',same((defs.visualChanges||[]).map(item=>item.id),f.visualChangeIds)&&defs.visualChanges.every(item=>item.artTreatmentId==null&&item.cssTreatmentId==null&&item.fallback&&item.derivedOnly===true),defs.visualChanges);
      add('twelve-gradual-tutorials',same((defs.tutorials||[]).map(item=>item.id),f.tutorialIds)&&defs.tutorials.every(item=>item.skippable===true&&item.replayable===true&&item.loggable===true&&item.blocking===false&&item.reward==null),defs.tutorials);
      add('exact-38-cast-and-original-writing',same((defs.cast||[]).map(item=>item.actorId),f.actorIds)&&defs.cast.every(item=>item.phase13PrimaryPreserved===true&&item.phase1516HooksPreserved===true)&&defs.castPolicy?.lockedFellowsExcluded===true&&same(defs.castPolicy?.artFallbackOrder,f.approvedVisualFallbacks)&&defs.castPolicy?.originalEversteadWriting===true&&defs.castPolicy?.franchiseImitationForbidden===true,defs.castPolicy);
      add('chronicle-more-five-tabs',defs.presentation?.bottomNavigationCount===5&&defs.presentation?.chronicleLocation==='more'&&defs.presentation?.autoAdvance===false&&defs.presentation?.maxAutoStoryPerSafeVisit===1&&defs.presentation?.maxAutoTutorialPerSafeVisit<=1,defs.presentation);

      const passiveBefore=call('read','passiveBaseline');call('destructive','resetFixture',f.saveFixtures.fresh);const freshBefore=call('read','derive'),freshResources=resources(freshBefore),freshRoster=roster(freshBefore),visit=call('destructive','safeVisit',{surface:'village',userInitiated:true}),freshAfter=call('read','derive');add('fresh-safe-visit-creates-story-once',visit?.ok===true&&story(freshAfter)?.schemaVersion===1&&queue(freshAfter).length===1&&queue(freshAfter)[0]?.sceneId==='story.book1.prologue.waystone-call'&&same(resources(freshAfter),freshResources)&&same(roster(freshAfter),freshRoster),{visit,story:story(freshAfter)});const repeatVisitRaw=call('read','raw'),repeatVisit=call('destructive','safeVisit',{surface:'village',userInitiated:true});add('fresh-safe-visit-repeat-does-not-duplicate',queue(call('read','derive')).length===1&&unique(queue(call('read','derive')).map(item=>item.queueId))&&Number(repeatVisit?.writes||0)===0&&call('read','raw')===repeatVisitRaw,repeatVisit);
      const waystoneResolve=call('destructive','resolveScene','story.book1.prologue.waystone-call','watched',null),afterWaystone=call('read','derive');add('scene-resolution-one-chronicle-and-derived-waystone',waystoneResolve?.ok===true&&chronicle(afterWaystone).filter(item=>item.sceneId==='story.book1.prologue.waystone-call').length===1&&visuals(afterWaystone).includes('village-change.waystone-awakened')&&facilities(afterWaystone).find(item=>item.id==='facility.waystone')?.discovered===true,{waystoneResolve,afterWaystone});

      call('destructive','resetFixture',f.saveFixtures.stage1Ready);const beforeIntro=call('read','derive'),battleBefore=beforeIntro?.campaign?.attemptMath,intro=call('destructive','openStory','story.book1.chapter1.village-toll.intro'),skipIntro=call('destructive','resolveScene','story.book1.chapter1.village-toll.intro','skipped',null),afterIntro=call('read','derive');add('stage-intro-before-spend-skip-neutral',intro?.ok===true&&intro?.beforeSpend===true&&skipIntro?.ok===true&&same(afterIntro?.campaign?.attemptMath,battleBefore)&&same(resources(afterIntro),resources(beforeIntro)),{intro,skipIntro});const clear1=call('destructive','clearStage','broken-roads-1',{firstClear:true}),afterClear1=call('read','derive');add('first-clear-commits-before-resolution-queue',clear1?.ok===true&&clear1?.campaignCommitted===true&&clear1?.storyCommittedAfterCampaign===true&&queue(afterClear1).some(item=>item.sceneId==='story.book1.chapter1.village-toll.resolution')&&!facilities(afterClear1).find(item=>item.id==='facility.restaurant')?.discovered,clear1);const resolve1=call('destructive','resolveScene','story.book1.chapter1.village-toll.resolution','watched','choice.qa'),afterResolve1=call('read','derive'),restaurant=facilities(afterResolve1).find(item=>item.id==='facility.restaurant');add('resolution-discovers-restaurant-without-opening',resolve1?.ok===true&&restaurant?.discovered===true&&restaurant?.available===false&&restaurant?.openingResolved===false&&restaurant?.bankedCount===0,{resolve1,restaurant});const grant=call('destructive','event','facility.capability-granted',{facilityId:'facility.restaurant',capabilityId:'capability.restaurant-service.v1'}),afterGrant=facilities(call('read','derive')).find(item=>item.id==='facility.restaurant');add('capability-alone-does-not-open',grant?.ok===true&&afterGrant?.discovered===true&&afterGrant?.capabilityEnabled===true&&afterGrant?.available===false,afterGrant);const opening=call('destructive','event','content.resolved',{contentId:'facility.restaurant.opening-service'}),opened=facilities(call('read','derive')).find(item=>item.id==='facility.restaurant');add('opening-after-story-and-capability-opens',opening?.ok===true&&opened?.available===true&&opened?.openingResolved===true,opened);

      call('destructive','resetFixture',f.saveFixtures.stage2Rank2);const clear2=call('destructive','clearStage','broken-roads-2',{firstClear:true}),stage2State=call('read','derive');add('rank-crossing-resolution-precedes-arrival',clear2?.ok===true&&queue(stage2State)[0]?.sceneId==='story.book1.chapter1.merchant-dispute.resolution'&&!queue(stage2State).some(item=>item.sceneId==='story.book1.rank2.roadbound-arrivals'),{clear2,queue:queue(stage2State)});call('destructive','resolveScene','story.book1.chapter1.merchant-dispute.resolution','watched',null);call('destructive','safeVisit',{surface:'village',userInitiated:true});const rank2State=call('read','derive');add('rank-arrival-second-and-observes-roster',queue(rank2State)[0]?.sceneId==='story.book1.rank2.roadbound-arrivals'&&same(roster(rank2State)?.joinedFellowIds,roster(stage2State)?.joinedFellowIds),rank2State);call('destructive','resolveScene','story.book1.rank2.roadbound-arrivals','watched',null);const afterArrival=call('read','derive');add('arrival-tutorial-only-after-resolution',tutorials(afterArrival).some(item=>item.id==='tutorial.rank.new-fellows.rank-2'&&item.eligible===true),tutorials(afterArrival));const repeatProjection=storyProjection(afterArrival),repeatClear=call('destructive','clearStage','broken-roads-2',{firstClear:false}),afterRepeat=call('read','derive');add('repeat-clear-no-story-facility-visual-tutorial-effects',repeatClear?.ok===true&&repeatClear?.contextualLineOnly===true&&same(storyProjection(afterRepeat),repeatProjection),repeatClear);

      call('destructive','resetFixture',f.saveFixtures.chronicle);const replayBefore=call('read','raw'),replay=call('destructive','replayScene','story.book1.chapter1.merchant-dispute.resolution',{choiceId:'choice.alternate'});add('chronicle-replay-byte-neutral',replay?.ok===true&&replay?.capturedDefinitionVersion===1&&call('read','raw')===replayBefore,replay);const chron=call('read','chronicle');add('chronicle-groups-spoiler-safe-and-loggable',chron?.location==='more'&&chron?.bookId===f.bookId&&chron?.groups?.length===6&&chron?.lockedEntries?.every(item=>item.spoilerSafe===true)&&chron?.resolvedEntries?.every(item=>item.replayable===true&&item.logAvailable===true),chron);

      call('destructive','resetFixture',f.saveFixtures.rankJump);const rankVisit1=call('destructive','safeVisit',{surface:'village',userInitiated:true}),rankQueue1=queue(call('read','derive'));add('rank-jump-arrivals-start-at-two',rankVisit1?.ok===true&&rankQueue1.filter(item=>item.reason==='rank-arrival').length===1&&rankQueue1.find(item=>item.reason==='rank-arrival')?.sceneId===f.arrivalScenes[0][1],rankQueue1);const arrivalOrder=[];for(const [,sceneId] of f.arrivalScenes){const current=queue(call('read','derive')).find(item=>item.reason==='rank-arrival');if(current){arrivalOrder.push(current.sceneId);call('destructive','resolveScene',current.sceneId,'watched',null)}call('destructive','safeVisit',{surface:'village',userInitiated:true})}add('rank-jump-arrivals-ascending-one-per-visit',same(arrivalOrder,f.arrivalScenes.map(item=>item[1])),arrivalOrder);
      call('destructive','resetFixture',f.saveFixtures.migrated);const migrated=call('read','derive');add('migration-uses-stage-clears-bounded-recaps',story(migrated)?.historicalAuthority==='committed-first-clears'&&chronicle(migrated).every(item=>item.resolution==='migrated-recap')&&story(migrated)?.forcedHistoricalSceneCount===0&&story(migrated)?.maxRecapPerSafeVisit===1&&offers(migrated).length===0,migrated);
      call('destructive','resetFixture',f.saveFixtures.grandfathered);const grandfather=call('read','derive'),grandRestaurant=facilities(grandfather).find(item=>item.id==='facility.restaurant');add('operational-restaurant-grandfathered-never-relocked',grandRestaurant?.available===true&&grandRestaurant?.grandfathered===true&&grandRestaurant?.discovered===true&&grandRestaurant?.openingGrantReplayCount===0,grandRestaurant);
      call('destructive','resetFixture',f.saveFixtures.discoveredLocked);const locked=call('read','derive'),apothecary=facilities(locked).find(item=>item.id==='facility.apothecary');add('future-facility-discovered-locked-not-active',apothecary?.discovered===true&&apothecary?.available===false&&apothecary?.state==='discovered-locked'&&apothecary?.claimReadyCount===0,apothecary);

      const passiveMid=call('read','passiveBaseline');add('original-four-passive-preserved-through-story',same(passiveMid,passiveBefore),{before:passiveBefore,after:passiveMid});const facilityRows=facilities(locked);add('all-twelve-facilities-one-canonical-anchor',facilityRows.length===12&&unique(facilityRows.map(item=>item.id))&&unique(facilityRows.map(item=>item.mapAnchor))&&facilityRows.every(item=>f.facilityUnlocks.some(row=>row[0]===item.id&&row[1]===item.mapAnchor)),facilityRows);
      const aliasProbe=call('destructive','event','qa.anchor-alias-probe',{scope:'facility.restaurant',anchor:'western-plaza'});add('scoped-alias-resolves-without-regional-collision',aliasProbe?.ok===true&&aliasProbe?.canonical==='western-plaza-restaurant'&&aliasProbe?.regionalProjectionAnchor==='western-plaza'&&aliasProbe?.unscopedFacilityResolutionRefused===true,aliasProbe);

      call('destructive','resetFixture',f.saveFixtures.finaleReady);const finaleBefore=call('read','derive'),finale=call('destructive','resolveScene',f.bookCompletionSceneId,'skipped',null),finaleAfter=call('read','derive');add('finale-skip-completes-book-and-visual-without-claim',finale?.ok===true&&story(finaleAfter)?.completedBookIds?.includes(f.bookId)&&visuals(finaleAfter).includes('village-change.first-covenant')&&offers(finaleAfter).length===offers(finaleBefore).length&&same(resources(finaleAfter),resources(finaleBefore)),{finale,after:finaleAfter});call('destructive','reload');const finaleReload=call('read','derive');add('visual-projections-durable-and-derived',same(visuals(finaleReload),visuals(finaleAfter))&&call('read','validate')?.ok===true,visuals(finaleReload));const invalidVisual=call('destructive','mutateInvalid','unreproducible-visual-projection');add('independent-visual-grant-refused',invalidVisual?.ok===false&&Number(invalidVisual?.writes||0)===0,invalidVisual);
      const nullReward=call('destructive','event','story.reward-eligible',{definitionId:f.rewardDefinitionIds[0]});add('null-story-reward-fails-closed',nullReward?.ok===false&&nullReward?.reason==='reward-disabled'&&Number(nullReward?.writes||0)===0&&offers(call('read','derive')).length===0,nullReward);
      call('destructive','resetFixture',f.saveFixtures.syntheticReward);const syntheticOffer=offers(call('read','derive'))[0],syntheticBefore=call('read','derive'),syntheticSnapshot=call('read','snapshot'),syntheticClaim=call('destructive','claim',syntheticOffer.id,syntheticOffer.identity),syntheticAfter=call('read','derive');add('synthetic-story-claim-v2-exact-once',syntheticClaim?.ok===true&&revision(call('read','snapshot'))===revision(syntheticSnapshot)+1&&syntheticClaim?.resourceApplications===1&&syntheticClaim?.receiptApplications===1&&Number(resources(syntheticAfter).gold)===Number(resources(syntheticBefore).gold)+f.syntheticReward.gold&&syntheticAfter?.claimArchive?.configId===f.archiveConfigId,{syntheticClaim,syntheticAfter});const claimedRaw=call('read','raw'),repeatClaim=call('destructive','claim',syntheticOffer.id,syntheticOffer.identity);add('story-claim-repeat-write-free',repeatClaim?.ok===false&&Number(repeatClaim?.writes||0)===0&&call('read','raw')===claimedRaw,repeatClaim);for(const mode of ['missing','throw','archive']){call('destructive','resetFixture',f.saveFixtures.syntheticReward);const raw=call('read','raw'),failure=call('destructive','probeFinalizerFailure',mode);add(`story-finalizer-${mode}-atomic-refusal`,failure?.ok===false&&Number(failure?.writes||0)===0&&call('read','raw')===raw,failure)}

      call('destructive','resetFixture',f.saveFixtures.offline);const offlineBefore=call('read','derive'),offlineStory=storyProjection(offlineBefore),offline=call('destructive','advanceOffline',f.offlineCapMs*2),offlineAfter=call('read','derive');add('offline-never-consumes-or-rewards-story',offline?.ok===true&&offline?.appliedMs===f.offlineCapMs&&same(storyProjection(offlineAfter),offlineStory)&&offline?.storyApplications===0&&offline?.rewardApplications===0,{offline,before:offlineStory,after:storyProjection(offlineAfter)});const foreground=call('destructive','safeVisit',{surface:'village',userInitiated:true});add('offline-eligibility-reconciles-only-foreground',foreground?.ok===true&&foreground?.reconciledFromCommittedTruth===true,foreground);
      for(const kind of ['scene-resolution','arrival-queue','story-claim']){const race=call('destructive','simulateConcurrent',kind);add(`two-client-${kind}-one-winner`,race?.ok===true&&race?.winnerCount===1&&race?.loserCount===1&&race?.losingWrites===0&&race?.duplicateChronicleCount===0&&race?.duplicateQueueCount===0&&race?.duplicateOfferCount===0&&race?.duplicateReceiptCount===0&&race?.finalValid===true,race)}

      call('destructive','resetFixture',f.saveFixtures.chronicle);const tutorialId='tutorial.chronicle.replay-and-log',tutorialOpen=call('destructive','tutorial',tutorialId,'open'),secondAuto=call('destructive','tutorial','tutorial.story.objective.chapter-change','open'),tutorialSkip=call('destructive','tutorial',tutorialId,'skip'),tutorialRaw=call('read','raw'),tutorialLog=call('destructive','tutorial',tutorialId,'log'),tutorialReplay=call('destructive','tutorial',tutorialId,'replay');add('tutorial-gradual-one-auto-and-skippable',tutorialOpen?.ok===true&&tutorialOpen?.autoPresented===true&&secondAuto?.ok===false&&Number(secondAuto?.writes||0)===0&&tutorialSkip?.ok===true,{tutorialOpen,secondAuto,tutorialSkip});add('tutorial-log-replay-presentation-only',tutorialLog?.ok===true&&tutorialReplay?.ok===true&&call('read','raw')===tutorialRaw,{tutorialLog,tutorialReplay});
      call('destructive','resetFixture',f.saveFixtures.lockedRoster);call('destructive','safeVisit',{surface:'village',userInitiated:true});const dialogue=call('read','derive')?.dialogue||{},joined=roster(call('read','derive'))?.joinedFellowIds||[];add('all-38-cast-hooks-resolve',same(sorted(dialogue.registeredActorIds||[]),sorted(f.actorIds)),dialogue.registeredActorIds);add('locked-fellows-never-speak',(dialogue.selectedSpeakers||[]).every(actorId=>!String(actorId).startsWith('fellow.')||joined.includes(actorId)),{speakers:dialogue.selectedSpeakers,joined});add('dialogue-approved-fallback-original-copy',(dialogue.presentations||[]).every(item=>f.approvedVisualFallbacks.includes(item.mode)&&item.unframedFullPortrait!==true&&item.originalEversteadCopy===true),dialogue.presentations);

      call('destructive','resetFixture',f.saveFixtures.recovery);const recoveryBefore=call('read','derive'),recovery=call('destructive','reload'),recoveryAfter=call('read','derive');add('recovery-one-authority-no-duplicates',recovery?.ok===true&&call('read','validate')?.ok===true&&unique(queue(recoveryAfter).map(item=>item.queueId))&&unique(chronicle(recoveryAfter).map(item=>item.recordId))&&chronicle(recoveryAfter).length===chronicle(recoveryBefore).length,{recovery,before:recoveryBefore,after:recoveryAfter});const exported=call('read','exportSave'),exportRaw=call('read','raw'),imported=call('destructive','importFixture',exported);add('export-import-preserves-story-lineage',imported?.ok===true&&call('read','raw')===exportRaw&&call('read','validate')?.ok===true,imported);call('destructive','resetFixture',f.saveFixtures.fresh);const safeRaw=call('read','raw'),corrupt=call('destructive','resetFixture',f.saveFixtures.corrupt),future=call('destructive','resetFixture',f.saveFixtures.future);add('corrupt-and-future-preserved-for-export',[corrupt,future].every(item=>item?.ok===false&&item?.preservedForExport===true&&Number(item?.writes||0)===0)&&call('read','raw')===safeRaw,{corrupt,future});const invalid=f.invalidMutationChecks.map(kind=>call('destructive','mutateInvalid',kind));add('invalid-story-import-matrix-fails-closed',invalid.every((item,index)=>item?.ok===false&&item?.check===f.invalidMutationChecks[index]&&Number(item?.writes||0)===0)&&call('read','raw')===safeRaw,invalid);

      call('destructive','resetFixture',f.saveFixtures.chronicle);await wait(50);const nav=[...document.querySelectorAll('[data-tab],nav button,[role="navigation"] button')].filter(node=>{const style=getComputedStyle(node);return style.display!=='none'&&style.visibility!=='hidden'}),more=[...nav].find(node=>/more/i.test(node.textContent));if(more){more.click();await wait(20)}const chronicleNode=document.querySelector('[data-phase17-chronicle]'),entry=document.querySelector('[data-phase17-chronicle-entry]'),replayButton=document.querySelector('[data-phase17-replay]');add('actual-dom-five-nav-chronicle-under-more',nav.length===5&&Boolean(more)&&Boolean(chronicleNode)&&Boolean(entry)&&Boolean(replayButton),{nav:nav.map(node=>node.textContent.trim()),chronicle:Boolean(chronicleNode)});
      const beforeReplayDom=call('read','raw');if(replayButton){replayButton.focus();replayButton.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));replayButton.click();await wait(30)}const scene=document.querySelector('[data-phase17-story-scene]'),required=f.requiredDomSelectors.slice(1,8).every(selector=>document.querySelector(selector)),focusIn=Boolean(scene)&&scene.contains(document.activeElement),controls=[...document.querySelectorAll('[data-phase17-next],[data-phase17-skip],[data-phase17-log],[data-phase17-back],[data-phase17-close]')],targets=controls.every(node=>{const rect=node.getBoundingClientRect();return node.matches(':disabled')||(rect.width>=44&&rect.height>=44&&rect.left>=0&&rect.right<=innerWidth+1)});add('actual-dom-scene-controls-focus-keyboard',Boolean(scene)&&required&&focusIn&&targets,{scene:Boolean(scene),required,focusIn,targets,controls:controls.map(node=>node.textContent.trim())});document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(20);add('actual-dom-replay-escape-focus-return-neutral',call('read','raw')===beforeReplayDom&&(!replayButton||document.activeElement===replayButton),{neutral:call('read','raw')===beforeReplayDom,active:document.activeElement?.outerHTML?.slice(0,200)});
      const noOverflow=document.documentElement.scrollWidth<=document.documentElement.clientWidth+1&&document.body.scrollWidth<=document.body.clientWidth+1;add('actual-dom-no-overflow-copy-expansion',noOverflow,{copyScale:config.viewport.copyScale,document:[document.documentElement.clientWidth,document.documentElement.scrollWidth]});const reducedOk=config.viewport.reducedMotion?[...document.querySelectorAll('[data-phase17-story-scene],[data-phase17-village-change]')].every(node=>{const style=getComputedStyle(node);return style.animationName==='none'||style.animationDuration==='0s'}):true;add('actual-dom-reduced-motion-static',reducedOk,{reducedMotion:config.viewport.reducedMotion});const status=document.querySelector('[role="status"],[aria-live]');add('actual-dom-accessible-status-and-labels',Boolean(status)&&[...document.querySelectorAll('[data-phase15-facility-id]')].every(node=>node.getAttribute('aria-label')||node.textContent.trim()),Boolean(status));
      add('final-passive-baseline-preserved',same(call('read','passiveBaseline'),passiveBefore),{before:passiveBefore,after:call('read','passiveBaseline')});add('final-state-valid',call('read','validate')?.ok===true,call('read','validate'));add('native-storage-instrumented',window.__P17I_NATIVE_INSTRUMENTED__===true);add('zero-native-storage-accesses',window.__P17I_NATIVE_ACCESSES__.length===0,window.__P17I_NATIVE_ACCESSES__);add('zero-warning-error-console',window.__P17I_ERRORS__.length===0,window.__P17I_ERRORS__);send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }
  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();if(source.indexOf('<script')<0)throw new Error('Production script tag missing');const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`;source=source.replace('<head>','<head><base href="../../">');const insertion=source.indexOf('<script');source=source.slice(0,insertion)+bootstrap+source.slice(insertion).replace('</body>',suite+'</body>');document.open();document.write(source);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
