import {createHash} from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
import {existsSync,readFileSync,readdirSync,statSync} from 'node:fs';
import {resolve} from 'node:path';
const ROOT=resolve(new URL('../..',import.meta.url).pathname),QA=resolve(ROOT,'qa/phase-17-independent'),NODE=process.execPath,BASE='70201ab52e6e3510747bee1a977794a8c900bdd1',PACKAGE_ONLY=process.argv.includes('--package-only'),EXPECTED=['README.md','checksums.sha256','fixtures/contract-fixtures.json','fixtures/inherited-hashes.json','index.html','realm.html','realm.js','runner.js','verify.mjs'];
const rows=[],record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),read=path=>readFileSync(resolve(ROOT,path)),text=path=>read(path).toString('utf8'),json=path=>JSON.parse(text(path)),sha=value=>createHash('sha256').update(value).digest('hex'),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),unique=values=>new Set(values).size===values.length;
const git=args=>execFileSync('/usr/bin/git',args,{cwd:ROOT,encoding:'utf8',maxBuffer:128*1024*1024}),gitBytes=args=>execFileSync('/usr/bin/git',args,{cwd:ROOT,maxBuffer:256*1024*1024}),baseRead=path=>gitBytes(['show',`${BASE}:${path}`]);
const f=json('qa/phase-17-independent/fixtures/contract-fixtures.json'),inherited=json('qa/phase-17-independent/fixtures/inherited-hashes.json'),story=json('design/phase-17/book1-story.json'),unlocks=json('design/phase-17/facility-unlocks.json'),visuals=json('design/phase-17/village-visual-changes.json'),tutorials=json('design/phase-17/tutorial-bindings.json'),cast=json('design/phase-17/book1-cast-distribution.json'),designFixtures=json('design/phase-17/fixtures.json'),p13=json('qa/phase-13-independent/fixtures/contract-fixtures.json'),p16=json('qa/phase-16-independent/fixtures/contract-fixtures.json');
function filesBelow(directory,prefix=''){const paths=[];for(const name of readdirSync(directory)){const absolute=resolve(directory,name),path=prefix?`${prefix}/${name}`:name;if(statSync(absolute).isDirectory())paths.push(...filesBelow(absolute,path));else paths.push(path)}return paths.sort()}
function productionSources(){const files=[];function visit(directory,prefix=''){for(const entry of readdirSync(directory,{withFileTypes:true})){if(!prefix&&['.git','assets','design','docs','qa'].includes(entry.name))continue;const path=prefix?`${prefix}/${entry.name}`:entry.name,absolute=resolve(directory,entry.name);if(entry.isDirectory())visit(absolute,path);else if(/\.(?:html|m?js|json)$/.test(path))files.push(path)}}visit(ROOT);return files.sort()}
const normalizedStages=story.stageMappings.map(item=>[item.stageId,item.stageName,item.chapterId,item.introSceneId,item.resolutionSceneId]),normalizedUnlocks=unlocks.facilityUnlocks.map(item=>[item.facilityId,item.mapAnchor,item.targetPhase,item.discovery.contentId,item.activeInteraction.requiredCapabilityId,item.activeInteraction.openingContentId]);

record('base-commit-reachable',git(['merge-base','--is-ancestor',BASE,'HEAD'])==='');record('package-topology',same(filesBelow(QA),EXPECTED),filesBelow(QA));
const checksumRows=existsSync(resolve(ROOT,'qa/phase-17-independent/checksums.sha256'))?text('qa/phase-17-independent/checksums.sha256').trim().split('\n').filter(Boolean).map(line=>{const match=line.match(/^([0-9a-f]{64})  (.+)$/);return match?{expected:match[1],path:match[2]}:null}):[],checksumFailures=checksumRows.filter(item=>!item||!existsSync(resolve(ROOT,item.path))||sha(read(item.path))!==item.expected).map(item=>item?.path||'malformed');record('package-checksums',checksumRows.length===10&&checksumFailures.length===0,{count:checksumRows.length,failures:checksumFailures});
record('contract-and-result-documents',['docs/PHASE_17_INDEPENDENT_QA_CONTRACT.md','docs/PHASE_17_INDEPENDENT_QA_RESULT.md'].every(path=>existsSync(resolve(ROOT,path))));const contract=text('docs/PHASE_17_INDEPENDENT_QA_CONTRACT.md');
record('contract-scope-correct',contract.includes('full runtime expansion')&&contract.includes('ten released Fellow Campaign stages')&&contract.includes('changes no production runtime')&&contract.includes('Accepted Phase 12–16 seams remain mandatory'));
record('contract-story-ordering-complete',['six sections','31 stable scene IDs','Campaign commit → stage resolution → Rank arrival → arrival tutorial','Rank 2, 3, 4, then 5','Repeat clears','Offline time never','migrated-recap'].every(value=>contract.includes(value)));
record('contract-village-and-alias-complete',['All twelve facilities','Story completion supplies discovery only','exact capability and authored opening','western-plaza-restaurant','regional visual-projection anchor','original four Building','Prosperity and Headquarters thresholds remain null','Eight Village changes'].every(value=>contract.includes(value)));
record('contract-chronicle-rewards-tutorial-cast',['Chronicle remains inside **More**','five bottom tabs','opportunity.story.reward','exact 79-ID successor ledger','18 Fellows and 20 Family','Locked Fellows never speak','original Everstead writing'].every(value=>contract.includes(value)));
record('contract-save-concurrency-dom-blind-spots',['storyV1','fails closed into recovery','Scene resolution, arrival queue mutation, and native story claim','two-client race','320×568','390×844','1024×768','30 percent localized-copy expansion','Normalized output alone cannot prove'].every(value=>contract.includes(value)));
record('contract-passive-motion-wayfarer-hardening',['one captured time','wall-clock-derived','data-everstead-reduced-motion','must not monkey-patch `matchMedia`','`player.wayfarer`','title/profile only','never enters Fellow, Family, or Companion roster counts','original Everstead silhouette'].every(value=>contract.includes(value)));

record('fixture-provenance',f.contractVersion===1&&f.bridgeVersion==='phase-17-independent-qa-v1'&&f.baseCommit===BASE&&f.schemaVersion===12&&f.storySchemaVersion===1);record('fixture-definition-sets',same(f.definitionSetIds,['definition-set.phase-17-book1.v1','definition-set.phase-17-village-unlocks.v1','definition-set.phase-17-village-visuals.v1']));
record('fixture-six-sections-ten-stages',f.chapterIds.length===6&&f.stageMappings.length===10&&unique(f.stageMappings.map(item=>item[0])));record('fixture-thirty-one-scenes',f.sceneCount===31&&f.sceneIds.length===31&&unique(f.sceneIds));record('fixture-rank-arrivals-and-five-rewards',same(f.arrivalScenes.map(item=>item[0]),[2,3,4,5])&&f.rewardDefinitionIds.length===5&&unique(f.rewardDefinitionIds));
record('fixture-twelve-unique-facilities-and-anchors',f.facilityUnlocks.length===12&&unique(f.facilityUnlocks.map(item=>item[0]))&&unique(f.facilityUnlocks.map(item=>item[1])));record('fixture-scoped-alias-not-regional-collision',same(f.facilityScopedAnchorAliases,[{scope:'facility.restaurant',alias:'western-plaza',canonical:'western-plaza-restaurant'}])&&f.regionalAnchorIds.includes('western-plaza'));
record('fixture-eight-visuals-twelve-tutorials',f.visualChangeIds.length===8&&f.tutorialIds.length===12&&unique(f.visualChangeIds)&&unique(f.tutorialIds));record('fixture-exact-thirty-eight-cast',f.actorIds.length===38&&f.actorIds.filter(id=>id.startsWith('fellow.')).length===18&&f.actorIds.filter(id=>id.startsWith('family.')).length===20&&unique(f.actorIds));
record('fixture-save-invalid-and-design-matrices',Object.keys(f.saveFixtures).length===15&&f.invalidMutationChecks.length===17&&f.fixtureIds.length===34&&unique(Object.values(f.saveFixtures))&&unique(f.invalidMutationChecks)&&unique(f.fixtureIds));record('fixture-synthetic-reward-qa-only',f.syntheticReward.qaOnly===true&&f.syntheticReward.definitionId.startsWith('qa-only.')&&Number.isSafeInteger(f.syntheticReward.gold));record('fixture-five-realms',f.viewports.length===5&&f.viewports.some(item=>item.width===320&&item.height===568)&&f.viewports.some(item=>item.width===390&&item.height===844)&&f.viewports.some(item=>item.width===1024&&item.height===768)&&f.viewports.some(item=>item.reducedMotion)&&f.viewports.some(item=>item.copyScale===1.3));
record('fixture-player-passive-motion-contracts',f.playerCharacter?.id==='player.wayfarer'&&f.playerCharacter?.kind==='player-character'&&f.playerCharacter?.avatarId==='wayfarer'&&f.playerCharacter?.titleProfileAsset?.sha256==='a34c2d3a858f46be58450048b77c53965d4644690c2eb9a9c7649bd1b5139aaf'&&f.playerCharacter?.titleProfileAsset?.use==='title-profile-only'&&f.playerCharacter?.campaignDefaultUntilCutoutApproved==='original-everstead-silhouette'&&f.playerCharacter?.excludedDomains?.includes('roster-count')&&f.playerCharacter?.excludedDomains?.includes('facility-speaker-eligibility')&&f.passiveBaselineContract?.capturedAt===f.frozenNow&&f.passiveBaselineContract?.wallClockDerivedExcluded===true&&same(f.passiveBaselineContract?.originalFourFacilityIds,f.originalPassiveFacilityIds)&&f.reducedMotionContract?.rootAttribute==='data-everstead-reduced-motion'&&f.reducedMotionContract?.forbiddenTestTechnique==='javascript-matchMedia-monkey-patch-only');

record('design-story-provenance',story.contractId==='phase-17-book1-story-v1'&&story.definitionSetId===f.definitionSetIds[0]&&story.book.id===f.bookId&&story.productionEnabled===false);record('design-six-sections-exact',same(story.chapters.map(item=>item.id),f.chapterIds)&&story.chapters.flatMap(item=>item.stageIds).length===10);record('design-stage-mappings-exact',same(normalizedStages,f.stageMappings),normalizedStages);record('design-scenes-exact',same(story.scenes.map(item=>item.id),f.sceneIds)&&story.scenes.every(item=>item.definitionVersion===1&&item.replayable===true));record('design-scene-kinds-complete',['prologue','stage-intro','stage-resolution','chapter-resolution','rank-arrival','optional-interlude','bridge','book-resolution'].every(kind=>story.scenes.some(item=>item.kind===kind)));
record('design-arrivals-exact-and-observational',same(story.arrivalOrder.map(item=>[item.rank,item.sceneId]),f.arrivalScenes)&&story.arrivalOrder.flatMap(item=>item.actorIds).length===12&&story.scenes.filter(item=>item.kind==='rank-arrival').every(item=>item.beatIntentIds.includes('roster-state-observed-not-granted')));record('design-rewards-disabled-null-native',same(story.storyRewardDefinitions.map(item=>item.id),f.rewardDefinitionIds)&&story.storyRewardDefinitions.every(item=>item.sourceType===f.storyRewardSourceType&&item.rewards===null&&item.enablementStatus==='blocked-economy'));
record('design-facility-unlocks-exact',unlocks.definitionSetId===f.definitionSetIds[1]&&same(normalizedUnlocks,f.facilityUnlocks),normalizedUnlocks);record('design-story-capability-opening-separation',unlocks.globalRules.storyIsDiscoveryAuthority===true&&unlocks.globalRules.activeInteractionNeedsCapabilityAndOpening===true&&unlocks.globalRules.passiveBuildingStateIsIndependent===true&&unlocks.globalRules.neverRelockAnOperationalSuccessor===true);record('design-no-economic-unlock-thresholds',unlocks.globalRules.prosperityThreshold===null&&unlocks.globalRules.headquartersThreshold===null);record('design-original-four-passive',f.originalPassiveFacilityIds.every(id=>unlocks.facilityUnlocks.find(item=>item.facilityId===id)?.passivePolicy==='preserve-existing-building-production-and-family-assignment'));
record('design-eight-visuals-derived-null-fallback',visuals.definitionSetId===f.definitionSetIds[2]&&same(visuals.changes.map(item=>item.id),f.visualChangeIds)&&visuals.changes.every(item=>item.artTreatmentId===null&&item.cssTreatmentId===null&&item.fallback));record('design-visual-sources-valid',visuals.changes.every(item=>story.scenes.some(scene=>scene.id===item.source.contentId))&&visuals.authority.includes('pure projections'));
record('design-twelve-tutorials-exact-ledger',tutorials.sourceLedgerCount===79&&same(tutorials.bindings.map(item=>item.tutorialId),f.tutorialIds)&&f.tutorialIds.every(id=>p13.allTutorialCoverageIds.includes(id)));record('design-tutorial-successor-preserves-history',tutorials.stateRegistry.preservePredecessorHistory===true&&tutorials.globalRules.some(value=>value.includes('At most one tutorial'))&&tutorials.globalRules.some(value=>value.includes('30 percent text expansion')));
record('design-exact-38-cast',same(cast.actors.map(item=>item.actorId),f.actorIds)&&cast.coverageRule.includes('18 Fellows and 20 Family'));record('design-cast-primary-and-hooks-preserved',cast.actors.every(item=>item.primaryContentId&&Array.isArray(item.book1AppearanceIds)&&Array.isArray(item.facilityHookIds))&&cast.presentationPolicy.includes('Unframed full-background portraits are forbidden'));record('design-original-writing-guardrail',cast.writingPolicy.includes('Do not imitate any external franchise'));
record('design-thirty-four-fixtures-exact',same(designFixtures.fixtures.map(item=>item.id),f.fixtureIds)&&designFixtures.syntheticValuesAreNonProduction===true);const designValidation=spawnSync('python3',['design/phase-17/validate.py'],{cwd:ROOT,encoding:'utf8'});record('accepted-design-validator-31-of-31',designValidation.status===0&&designValidation.stdout.includes('SUMMARY 31/31 checks'),designValidation.stdout.trim());
record('phase16-anchor-alias-lineage',p16.facilityId==='facility.restaurant'&&p16.designMapAnchorAlias==='western-plaza'&&p16.physicalMapAnchor==='western-plaza-restaurant');

const inheritedFailures=Object.entries(inherited.files).filter(([path,expected])=>{try{return sha(baseRead(path))!==expected}catch{return true}}).map(([path])=>path);record('inherited-phase12-through-phase16-byte-frozen',inherited.baseCommit===BASE&&Object.keys(inherited.files).length===31&&inheritedFailures.length===0,{count:Object.keys(inherited.files).length,failures:inheritedFailures});const assets=JSON.parse(baseRead('qa/phase-13-independent/fixtures/phase11h-assets.json').toString('utf8'));record('phase11h-asset-manifest-byte-frozen',Object.keys(assets.files).length===47&&sha(baseRead('qa/phase-13-independent/fixtures/phase11h-assets.json'))===inherited.files['qa/phase-13-independent/fixtures/phase11h-assets.json'],{count:Object.keys(assets.files).length});
record('runner-isolated-and-fail-closed',text('qa/phase-17-independent/realm.js').includes('allowDestructive:true')&&text('qa/phase-17-independent/realm.js').includes('isolatedStorage:true')&&text('qa/phase-17-independent/realm.js').includes('phase17-contract-unavailable')&&text('qa/phase-17-independent/realm.js').includes('if(!qa){'));record('runner-actual-dom-contract',['document.querySelector','document.querySelectorAll','getBoundingClientRect','getComputedStyle','document.activeElement','KeyboardEvent','scrollWidth','data-everstead-reduced-motion','data-phase17-player-character'].every(value=>text('qa/phase-17-independent/realm.js').includes(value))&&!text('qa/phase-17-independent/realm.js').includes('window.matchMedia='));
record('runner-required-behavior-coverage',['fresh-safe-visit-creates-story-once','stage-intro-before-spend-skip-neutral','first-clear-commits-before-resolution-queue','rank-crossing-resolution-precedes-arrival','rank-jump-arrivals-ascending-one-per-visit','chronicle-replay-byte-neutral','scoped-alias-resolves-without-regional-collision','finale-skip-completes-book-and-visual-without-claim','offline-never-consumes-or-rewards-story','two-client-${kind}-one-winner','tutorial-log-replay-presentation-only','all-38-cast-actors-have-resolved-intentional-role','locked-fellows-never-speak','actual-dom-replay-escape-focus-return-neutral','fresh-story-preserves-passive-at-captured-time','campaign-story-and-opening-preserve-passive-at-captured-time','actual-dom-wayfarer-separate-campaign-presence','final-passive-at-captured-time-preserved'].every(id=>text('qa/phase-17-independent/realm.js').includes(id)));
for(const path of ['verify.mjs','runner.js','realm.js']){const run=spawnSync(NODE,['--check',`qa/phase-17-independent/${path}`],{cwd:ROOT,encoding:'utf8'});record(`syntax-${path}`,run.status===0,run.stderr.trim())}

if(PACKAGE_ONLY){const artifact=baseRead('index.html');record('exact-frozen-base-artifact',sha(artifact)===inherited.files['index.html']&&artifact.length===1126624,{sha256:sha(artifact),byteLength:artifact.length});record('base-has-phase12-phase13-no-phase17',artifact.includes(Buffer.from('__EVERSTEAD_PHASE_12_QA__'))&&artifact.includes(Buffer.from('__EVERSTEAD_PHASE_13_QA__'))&&!artifact.includes(Buffer.from('__EVERSTEAD_PHASE_17_QA__')))}else{
  const paths=productionSources(),combined=paths.map(path=>text(path)).join('\n'),versions=[...combined.matchAll(/CURRENT_SCHEMA_VERSION\s*=\s*(\d+)/g)].map(match=>Number(match[1]));
  record('candidate-phase17-bridge-contract',combined.includes('__EVERSTEAD_PHASE_17_QA__')&&combined.includes(f.bridgeVersion)&&combined.includes('allowDestructive')&&combined.includes('isolatedStorage')&&combined.includes('NATIVE_STORAGE'),paths);
  record('candidate-book1-definition-contract',combined.includes(f.bookId)&&f.definitionSetIds.every(id=>combined.includes(id))&&f.stageMappings.every(item=>combined.includes(item[0])&&combined.includes(item[2])&&combined.includes(item[3])&&combined.includes(item[4])));
  record('candidate-story-successor-and-ordering',combined.includes('storyV1')&&combined.includes('queuedSceneItems')&&combined.includes('chronicleRecords')&&combined.includes('migrated-recap')&&combined.includes('eligibleRevision')&&combined.includes('predecessorSceneId'));
  record('candidate-facility-unlock-and-alias-contract',f.facilityUnlocks.every(item=>combined.includes(item[0])&&combined.includes(item[1])&&combined.includes(item[3])&&combined.includes(item[4])&&combined.includes(item[5]))&&combined.includes('facilityScopedAnchorAliases'));
  record('candidate-chronicle-dom-contract',combined.includes('data-phase17-story-scene')&&combined.includes('data-phase17-chronicle-open')&&combined.includes('data-phase17-chronicle')&&combined.includes('data-phase17-chronicle-entry')&&combined.includes('data-phase17-replay')&&combined.includes('data-phase17-village-change'));
  record('candidate-story-reward-finalizer-contract',combined.includes(f.storyRewardSourceType)&&combined.includes(f.archiveConfigId)&&combined.includes('immutableFinalizer')&&combined.includes('rewardOfferId')&&combined.includes('capturedDefinitionVersion'));
  record('candidate-tutorial-and-cast-contract',f.tutorialIds.every(id=>combined.includes(id))&&f.actorIds.every(id=>combined.includes(id))&&combined.includes('lockedFellowsExcluded')&&combined.includes('originalEversteadWriting'));
  record('candidate-phase17-inherited-seam-attestation',combined.includes(f.bridgeVersion)&&combined.includes(f.phase15BridgeVersion)&&combined.includes(f.phase16BridgeVersion)&&combined.includes(f.phase12ActivationId));
  record('candidate-wayfarer-separate-player-contract',combined.includes(f.playerCharacter.id)&&combined.includes(f.playerCharacter.kind)&&combined.includes(f.playerCharacter.rankSource)&&combined.includes(f.playerCharacter.titleProfileAsset.assetId)&&combined.includes(f.playerCharacter.titleProfileAsset.sha256)&&combined.includes(f.playerCharacter.campaignDefaultUntilCutoutApproved)&&f.playerCharacter.excludedDomains.every(id=>combined.includes(id))&&combined.includes('data-phase17-player-character'));
  record('candidate-nontautological-reduced-motion-contract',combined.includes(f.reducedMotionContract.rootAttribute)&&combined.includes(f.reducedMotionContract.reducedValue)&&combined.includes('data-motion-state')&&/@media\s*\(prefers-reduced-motion:\s*reduce\)/.test(combined)&&combined.includes('matchMediaMonkeyPatchEvidenceAccepted'));
  record('candidate-schema-remains-12',Math.max(0,...versions)===12,versions);
}
const owned=path=>['docs/PHASE_17_INDEPENDENT_QA_CONTRACT.md','docs/PHASE_17_INDEPENDENT_QA_RESULT.md'].includes(path)||path.startsWith('qa/phase-17-independent/'),packageCommits=git(['log','--format=%H',`${BASE}..HEAD`,'--','docs/PHASE_17_INDEPENDENT_QA_CONTRACT.md','docs/PHASE_17_INDEPENDENT_QA_RESULT.md','qa/phase-17-independent']).trim().split('\n').filter(Boolean),ownershipViolations=[];for(const commit of packageCommits){for(const path of git(['diff-tree','--root','--no-commit-id','--name-only','-r',commit]).trim().split('\n').filter(Boolean))if(!owned(path))ownershipViolations.push({commit,path})}record('committed-qa-paths-owned',packageCommits.length>=1&&ownershipViolations.length===0,{packageCommits,violations:ownershipViolations});
const passed=rows.filter(row=>row.pass).length,failed=rows.length-passed,result={phase:'17-independent-book1',mode:PACKAGE_ONLY?'PACKAGE_ONLY':'CANDIDATE',status:failed?'FAIL':'PASS',baseCommit:BASE,total:rows.length,passed,failed,rows};console.log(JSON.stringify(result,null,2));if(failed)process.exitCode=1;
