(() => {
  'use strict';
  const CHANNEL='everstead-phase-20-21-ui';
  const json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config){
    const slots=new Map(),writes=[],errors=[],nativeStorageAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);
    let saveIndex=0,transactionIndex=0,clock=config.fixtures.frozenNow,nativeStorageInstrumented=false;
    window.matchMedia=query=>({matches:config.viewport.reducedMotion&&query==='(prefers-reduced-motion: reduce)',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});
    document.documentElement.style.fontSize=`${config.viewport.copyScale||1}em`;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));
    const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>{key=String(key);writes.push({op:'set',key,value:String(value)});slots.set(key,String(value))},removeItem:key=>{key=String(key);writes.push({op:'remove',key});slots.delete(key)}};
    Object.assign(window,{__P2021UI_CONFIG__:config,__P2021UI_SLOTS__:slots,__P2021UI_WRITES__:writes,__P2021UI_ERRORS__:errors,__P2021UI_NATIVE_ACCESSES__:nativeStorageAccesses,__P2021UI_NATIVE_INSTRUMENTED__:nativeStorageInstrumented,__P2021UI_SET_CLOCK__:value=>{clock=Number(value)}});
    const runtime={storage:memoryStorage,clock:{now:()=>clock,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.4375,confirm:()=>true,ids:{save:()=>`save-p2021ui-${++saveIndex}`,transaction:()=>`tx-p2021ui-${++transactionIndex}`}};
    if(config.mode==='active')runtime.qa={allowDestructive:true,isolatedStorage:true};
    window.__EVERSTEAD_RUNTIME__=runtime;
  }

  function runSuite(){
    const config=window.__P2021UI_CONFIG__,f=config.fixtures,results=[];
    const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
    const until=async(predicate,limit=10000)=>{const started=performance.now();while(performance.now()-started<limit){if(predicate())return true;await wait(25)}return false};
    const same=(left,right)=>JSON.stringify(left)===JSON.stringify(right);
    const add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:typeof detail==='string'?detail:JSON.stringify(detail)});
    const send=()=>parent.postMessage({channel:config.channel,nonce:config.nonce,results,errors:window.__P2021UI_ERRORS__.slice()},'*');
    const bridge=()=>window.__EVERSTEAD_PHASE_20_21_QA__;
    const archiveBridge=()=>window.__EVERSTEAD_PHASE_20_21_ARCHIVE_QA__;
    const phaseData=(element,key)=>element?.getAttribute(`data-phase20-21-${key}`);
    const safe=(label,operation)=>{try{return operation()}catch(error){add(`${label}-call`,false,error.stack||error.message);return null}};
    const call=(group,name,...args)=>safe(name,()=>bridge()[group][name](...args));
    const click=async(selector,label=selector)=>{const button=document.querySelector(selector);if(!button){add(`${label}-control-present`,false,selector);return null}button.click();await wait(35);return button};
    const currentFacility=facilityId=>call('read','derive')?.facilities?.[facilityId];
    const currentRecord=facilityId=>currentFacility(facilityId)?.records?.[0]||null;
    const hotspotFor=facilityId=>document.querySelector(`[data-phase15-facility-id="${facilityId}"]`);
    const predecessorReplayContract=(button,id)=>button?.hasAttribute('data-phase13-tutorial-id')?{layer:'phase13',surface:`[data-phase13-tutorial="${id}"]`,close:`[data-phase13-tutorial="${id}"] [data-modal-close]`}:button?.hasAttribute('data-phase15-tutorial-id')?{layer:'phase15',surface:`[data-phase15-tutorial="${id}"]`,close:`[data-phase15-tutorial="${id}"] [data-modal-close]`}:button?.hasAttribute('data-phase16-tutorial-id')?{layer:'phase16',surface:`[data-phase16-tutorial="${id}"]`,close:`[data-phase16-tutorial="${id}"] [data-modal-close]`}:button?.hasAttribute('data-phase1819-tutorial-replay')?{layer:'phase1819',surface:`[data-phase1819-tutorial-replay-sheet="${id}"],[data-phase17-facility-introduction]`,close:'[data-phase1819-tutorial-replay-close],[data-phase17-close]'}:null;
    const minTarget=node=>{const rect=node?.getBoundingClientRect();return Boolean(rect&&rect.width>=44&&rect.height>=44)};
    const noOverflow=()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1&&document.body.scrollWidth<=document.body.clientWidth+1;
    const dismissAmbient=async()=>{const close=document.querySelector('[data-modal-close]');if(close){close.click();await wait(35)}};
    const stockValue=(facilityId,requirementId)=>{const view=call('read','derive');return requirementId==='relic-stones'?view?.resources?.relicStones:view?.facilities?.[facilityId]?.stock?.workshopComponents};
    const claimThroughProduction=facilityId=>{const seeded=call('destructive','seedRecord',facilityId);if(!seeded?.ok)return seeded;let record=currentFacility(facilityId)?.records?.at(-1),result=call('destructive','begin',facilityId,record.opportunity.id,record.identity);if(!result?.ok)return result;record=currentFacility(facilityId).records.find(item=>item.opportunity.id===record.opportunity.id);const choice=window.EVERSTEAD_PHASE20_21_FACILITIES.choicesFor(facilityId,record.templateId)[0]?.id;result=call('destructive','choose',facilityId,record.opportunity.id,record.identity,choice);if(!result?.ok)return result;record=currentFacility(facilityId).records.find(item=>item.opportunity.id===record.opportunity.id);result=call('destructive','commit',facilityId,record.opportunity.id,record.identity);if(!result?.ok)return result;record=currentFacility(facilityId).records.find(item=>item.opportunity.id===record.opportunity.id);result=call('destructive','resolve',facilityId,record.opportunity.id,record.identity);if(!result?.ok)return result;record=currentFacility(facilityId).records.find(item=>item.opportunity.id===record.opportunity.id);return call('destructive','claim',record.outcome.offerId,record.outcome.offerIdentity)};

    async function activeSuite(){
      await until(()=>bridge(),7000);const qa=bridge();add('bridge-present',Boolean(qa));if(!qa){send();return}
      add('bridge-version',qa.version===f.bridgeVersion,qa.version);
      add('eight-definition-facilities',same(call('read','definitions')?.facilities?.map(item=>item.facilityId),f.facilityIds));
      const lifecycleDetails=[];
      for(const facilityId of f.facilityIds){
        call('destructive','resetFixture',f.fixtureId);await wait(45);await dismissAmbient();
        const emptyHotspot=hotspotFor(facilityId),emptyState=emptyHotspot?.getAttribute('data-phase20-21-board-state');
        add(`${facilityId}-honest-available-board`,emptyState==='available'&&emptyHotspot?.getAttribute('data-phase15-state')==='available',{emptyState,phase15:emptyHotspot?.getAttribute('data-phase15-state')});
        const seedResult=call('destructive','seedRecord',facilityId);add(`${facilityId}-canonical-seed-record`,seedResult?.ok===true,seedResult);call('destructive','reload');await wait(55);await dismissAmbient();
        let hotspot=hotspotFor(facilityId),record=currentRecord(facilityId),recordId=record?.opportunity?.id;
        const readyState=hotspot?.getAttribute('data-phase20-21-board-state');
        add(`${facilityId}-honest-opportunity-board-and-human-label`,readyState==='opportunity-ready'&&hotspot?.getAttribute('data-phase15-state')==='ready'&&/opportunity ready/i.test(hotspot?.getAttribute('aria-label')||'')&&minTarget(hotspot),{readyState,label:hotspot?.getAttribute('aria-label'),recordId});
        hotspot?.focus();hotspot?.click();await wait(45);
        let sheet=document.querySelector(`[data-phase20-21-sheet][data-facility-id="${facilityId}"]`);
        add(`${facilityId}-exact-sheet-root-and-focus`,Boolean(sheet)&&sheet.getAttribute('data-phase20-21-state')==='opportunity-ready'&&sheet.contains(document.activeElement),{sheet:Boolean(sheet),focus:document.activeElement?.outerHTML?.slice(0,120)});
        add(`${facilityId}-stable-presentation-hooks`,Boolean(sheet?.querySelector('.es-feature-masthead,.es-state-chip'))&&Boolean(sheet?.querySelector('.es-stat-ribbon'))&&Boolean(sheet?.querySelector('.es-action-dock'))&&Boolean(sheet?.querySelector(`[data-phase20-21-record-id="${recordId}"]`)));
        const tutorial=document.querySelector('[data-phase20-21-contextual-tutorial]');if(tutorial){await click('[data-phase20-21-tutorial-action="complete"]',`${facilityId}-tutorial-complete`);sheet=document.querySelector(`[data-phase20-21-sheet][data-facility-id="${facilityId}"]`)}
        const goldAtStart=call('read','derive')?.resources?.gold;
        const beginButton=document.querySelector(`[data-phase20-21-begin="${recordId}"]`);add(`${facilityId}-exact-begin-id-hook`,Boolean(beginButton)&&phaseData(beginButton,'begin')===recordId,beginButton?.outerHTML);
        beginButton?.click();await wait(40);record=currentRecord(facilityId);
        add(`${facilityId}-actual-begin-click-routes-record`,record?.opportunity?.id===recordId&&record?.status==='engaged'&&document.querySelector('[data-phase20-21-sheet]')?.getAttribute('data-phase20-21-state')==='in-progress',record);
        let requirement=document.querySelector('[data-phase20-21-requirement]'),requirementId=requirement?.getAttribute('data-phase20-21-requirement')||null,reservedValue=requirementId?stockValue(facilityId,requirementId):null;
        if(f.reservationFacilityIds.includes(facilityId))add(`${facilityId}-begin-reserves-visible-stock`,Boolean(requirementId)&&record?.reservation?.quantity===2&&reservedValue===2,{requirementId,reservedValue,reservation:record?.reservation});
        const choice=document.querySelector('[data-phase20-21-choice-id]'),choiceId=choice?.getAttribute('data-phase20-21-choice-id');choice?.click();await wait(35);
        if(f.participantFacilityIds.includes(facilityId)){
          for(let index=0;index<2;index++){const actor=document.querySelectorAll('[data-phase20-21-actor-choice]')[index];actor?.click();await wait(35)}
          const actorIds=[...document.querySelectorAll('[data-phase20-21-actor-choice][aria-pressed="true"]')].map(item=>phaseData(item,'actor-choice'));
          add(`${facilityId}-participant-picker-excludes-wayfarer`,actorIds.length===2&&!document.querySelector('[data-phase20-21-actor-choice="player.wayfarer"]'),actorIds);
          await click('[data-phase20-21-save-participants]',`${facilityId}-save-participants`);
        }
        record=currentRecord(facilityId);const firstChoice=record?.choiceId,firstParticipants=record?.participantIds||[];
        await click(`[data-phase20-21-cancel="${recordId}"]`,`${facilityId}-cancel`);record=currentRecord(facilityId);
        add(`${facilityId}-actual-cancel-restores-banked-state`,record?.status==='banked'&&record?.choiceId===null&&record?.participantIds?.length===0&&record?.reservation===null,record);
        if(requirementId)add(`${facilityId}-cancel-restores-stock-exactly`,stockValue(facilityId,requirementId)===4,{requirementId,stock:stockValue(facilityId,requirementId)});
        await click(`[data-phase20-21-begin="${recordId}"]`,`${facilityId}-begin-again`);
        const choiceAgain=document.querySelector(`[data-phase20-21-choice-id="${choiceId}"]`)||document.querySelector('[data-phase20-21-choice-id]');choiceAgain?.click();await wait(35);
        if(f.participantFacilityIds.includes(facilityId)){
          for(let index=0;index<2;index++){const actor=document.querySelectorAll('[data-phase20-21-actor-choice]')[index];actor?.click();await wait(35)}
          await click('[data-phase20-21-save-participants]',`${facilityId}-save-participants-again`);
        }
        record=currentRecord(facilityId);const committedParticipants=[...(record?.participantIds||[])];
        await click(`[data-phase20-21-commit="${recordId}"]`,`${facilityId}-commit`);record=currentRecord(facilityId);
        add(`${facilityId}-actual-commit-no-early-reward`,['committed','growing'].includes(record?.status)&&call('read','derive')?.resources?.gold===goldAtStart,{status:record?.status,gold:call('read','derive')?.resources?.gold,goldAtStart});
        hotspot=hotspotFor(facilityId);await click('[data-phase20-21-close]',`${facilityId}-close-after-commit`);await wait(35);
        add(`${facilityId}-close-returns-exact-hotspot-focus`,document.activeElement===hotspot,{active:document.activeElement?.getAttribute('data-phase15-facility-id')});
        call('destructive','reload');await wait(50);hotspot=hotspotFor(facilityId);hotspot?.click();await wait(35);
        add(`${facilityId}-reload-persists-exact-participants`,same(currentRecord(facilityId)?.participantIds,committedParticipants)&&!currentRecord(facilityId)?.participantIds?.includes('player.wayfarer'),{before:committedParticipants,after:currentRecord(facilityId)?.participantIds});
        const resume=document.querySelector(`[data-phase20-21-resume="${recordId}"]`);add(`${facilityId}-close-reopen-offers-resume`,Boolean(resume)&&phaseData(resume,'resume')===recordId,resume?.outerHTML);resume?.click();await wait(35);
        record=currentRecord(facilityId);
        if(facilityId==='facility.gardens'){
          add(`${facilityId}-resume-shows-cultivation-check`,Boolean(document.querySelector(`[data-phase20-21-check-growth="${recordId}"]`))&&record?.status==='growing');
          window.__P2021UI_SET_CLOCK__(record.readyAt);await click(`[data-phase20-21-check-growth="${recordId}"]`,`${facilityId}-mature`);
        }else await click(`[data-phase20-21-resolve="${recordId}"]`,`${facilityId}-resolve`);
        record=currentRecord(facilityId);hotspot=hotspotFor(facilityId);
        add(`${facilityId}-honest-claim-ready-board`,record?.status==='claim-ready'&&hotspot?.getAttribute('data-phase20-21-board-state')==='claim-ready'&&document.querySelector('[data-phase20-21-claim-ready]')?.textContent?.includes('No reward or local progress has been applied yet'),{recordStatus:record?.status,board:hotspot?.getAttribute('data-phase20-21-board-state')});
        add(`${facilityId}-resolve-or-mature-still-no-reward`,call('read','derive')?.resources?.gold===goldAtStart,{gold:call('read','derive')?.resources?.gold,goldAtStart});
        const offerId=record?.outcome?.offerId,claimButton=document.querySelector(`[data-phase20-21-claim="${offerId}"]`);add(`${facilityId}-exact-manual-claim-id-hook`,Boolean(claimButton)&&phaseData(claimButton,'claim')===offerId,claimButton?.outerHTML);claimButton?.click();await wait(45);
        const afterClaim=currentFacility(facilityId),reward=call('read','definitions')?.facilities?.find(item=>item.facilityId===facilityId)?call('read','snapshot')?.state?.phase15FacilityFoundation?.successorClaimAuthorityByFacilityId?.[facilityId]?.lastReceipt?.rewards?.[0]?.amount:null;
        add(`${facilityId}-manual-claim-only-exactly-once`,afterClaim?.records?.length===0&&afterClaim?.claimedCount===1&&call('read','derive')?.resources?.gold===goldAtStart+reward&&!document.querySelector(`[data-phase20-21-claim="${offerId}"]`)&&Boolean(document.querySelector('[data-phase20-21-receipt-summary]')),{afterClaim,reward,gold:call('read','derive')?.resources?.gold});
        add(`${facilityId}-board-returns-available`,hotspotFor(facilityId)?.getAttribute('data-phase20-21-board-state')==='available',hotspotFor(facilityId)?.getAttribute('data-phase20-21-board-state'));
        add(`${facilityId}-sheet-targets-and-no-overflow`,[...document.querySelectorAll('[data-phase20-21-sheet] button')].every(minTarget)&&noOverflow(),{buttons:document.querySelectorAll('[data-phase20-21-sheet] button').length,viewport:[innerWidth,innerHeight],scroll:[document.documentElement.clientWidth,document.documentElement.scrollWidth]});
        lifecycleDetails.push({facilityId,choice:firstChoice,participants:firstParticipants,receipt:afterClaim?.lastReceiptId});
        await click('[data-phase20-21-close]',`${facilityId}-final-close`);
      }
      add('all-eight-real-dom-lifecycles-complete',lifecycleDetails.length===8&&new Set(lifecycleDetails.map(item=>item.receipt)).size===8,lifecycleDetails);
      call('destructive','resetFixture',f.fixtureId);const archiveQa=archiveBridge();add('archive-qa-production-bridge-present',archiveQa?.version==='phase-20-21-archive-qa-v1',archiveQa?.version);const firstThresholdClaim=claimThroughProduction('facility.command-center'),padded=archiveQa?.destructive.padToThreshold(),secondThresholdClaim=claimThroughProduction('facility.archives'),thresholdState=archiveQa?.read.snapshot()?.state,thresholdFoundation=thresholdState?.phase15FacilityFoundation,thresholdCheckpoint=thresholdFoundation?.successorFoldCheckpoint;
      add('actual-production-512-to-513-successor-fold',firstThresholdClaim?.ok&&padded?.ok&&secondThresholdClaim?.ok&&thresholdFoundation?.claimArchive?.archiveCheckpoint?.throughSequence===128&&thresholdFoundation?.claimArchive?.recentReceipts?.length===385&&thresholdCheckpoint?.observedFoldedThrough===128&&thresholdCheckpoint?.foldedClaimCountByFacilityId?.['facility.command-center']===1&&thresholdCheckpoint?.foldedClaimCountByFacilityId?.['facility.archives']===0&&thresholdFoundation?.successorClaimAuthorityByFacilityId?.['facility.command-center']?.claimCount===1&&thresholdFoundation?.successorClaimAuthorityByFacilityId?.['facility.archives']?.claimCount===1&&archiveQa?.read.validate()?.ok===true,{firstThresholdClaim,padded,secondThresholdClaim,through:thresholdFoundation?.claimArchive?.archiveCheckpoint?.throughSequence,recent:thresholdFoundation?.claimArchive?.recentReceipts?.length,checkpoint:thresholdCheckpoint});
      call('destructive','resetFixture',f.fixtureId);const predecessorPadded=archiveQa?.destructive.padToThreshold(),predecessorFold=archiveQa?.destructive.appendPredecessorAndFold(),predecessorState=archiveQa?.read.snapshot()?.state,predecessorCheckpoint=predecessorState?.phase15FacilityFoundation?.successorFoldCheckpoint;
      add('actual-production-predecessor-fold-advances-only-observed-through',predecessorPadded?.ok&&predecessorFold?.ok&&predecessorCheckpoint?.observedFoldedThrough===128&&predecessorCheckpoint?.foldedSuccessorClaimCount===0&&Object.values(predecessorCheckpoint?.foldedClaimCountByFacilityId||{}).every(count=>count===0)&&archiveQa?.read.validate()?.ok===true,{predecessorPadded,predecessorFold,checkpoint:predecessorCheckpoint});
      const faultPadded=archiveQa?.destructive.padToThreshold(),faultBefore=archiveQa?.read.snapshot(),adapterWritesBefore=window.__P2021UI_WRITES__.length,fault=archiveQa?.destructive.probeStaleFold(),adapterWriteDelta=window.__P2021UI_WRITES__.length-adapterWritesBefore,faultAfter=archiveQa?.read.snapshot(),faultResourcesBefore={gold:faultBefore?.state?.gold,prosperity:faultBefore?.state?.prosperity,gifts:faultBefore?.state?.gifts,relicStones:faultBefore?.state?.relicStones},faultResourcesAfter={gold:faultAfter?.state?.gold,prosperity:faultAfter?.state?.prosperity,gifts:faultAfter?.state?.gifts,relicStones:faultAfter?.state?.relicStones};add('actual-production-stale-fold-is-zero-storage-write-atomic',faultPadded?.ok&&fault?.ok===false&&adapterWriteDelta===0&&fault?.writes===2&&fault?.rawChanged===false&&faultBefore?.raw===faultAfter?.raw&&same(faultResourcesBefore,faultResourcesAfter)&&archiveQa?.read.validate()?.ok===true,{faultPadded,fault,adapterWriteDelta,expectedDiagnosticEntries:['outcome','block'],faultResourcesBefore,faultResourcesAfter});
      call('destructive','resetFixture',f.fixtureId);call('destructive','seedRecord','facility.command-center');call('destructive','reload');await wait(45);hotspotFor('facility.command-center')?.click();await wait(35);const contextual=document.querySelector('[data-phase20-21-contextual-tutorial]');if(contextual)await click('[data-phase20-21-tutorial-action="complete"]','tutorial-ledger-contextual');await click('[data-phase20-21-open-tutorial-log]','open-tutorial-log');await wait(45);
      const visibleLessonRows=[...document.querySelectorAll('.phase-13-log-list .phase-13-log-row')],successorRows=[...document.querySelectorAll('[data-phase20-21-tutorial-log-row][data-phase20-21-tutorial-origin="successor"]')],predecessorRows=visibleLessonRows.filter(item=>item.getAttribute('data-phase20-21-tutorial-origin')!=='successor');
      const canonicalPredecessorIds=Object.keys(call('read','derive')?.tutorials?.statusById||{}).sort(),canonicalPredecessorSet=new Set(canonicalPredecessorIds),visiblePredecessorIds=predecessorRows.map(row=>row.getAttribute('data-phase20-21-tutorial-log-row')||Object.values(row.querySelector('button')?.dataset||{}).find(value=>canonicalPredecessorSet.has(value))||null).filter(Boolean).sort(),visibleSuccessorIds=successorRows.map(row=>row.getAttribute('data-phase20-21-tutorial-log-row')).sort(),expectedSuccessorIds=call('read','definitions')?.tutorials?.map(item=>item.id).sort()||[];
      add('tutorial-log-visible-79-plus-19-exact',visibleLessonRows.length===f.tutorialCounts.total&&predecessorRows.length===f.tutorialCounts.predecessor&&successorRows.length===f.tutorialCounts.successor&&same(visiblePredecessorIds,canonicalPredecessorIds)&&same(visibleSuccessorIds,expectedSuccessorIds)&&new Set(visiblePredecessorIds).size===canonicalPredecessorIds.length&&new Set(visibleSuccessorIds).size===expectedSuccessorIds.length,{total:visibleLessonRows.length,predecessor:predecessorRows.length,successor:successorRows.length,missingPredecessor:canonicalPredecessorIds.filter(id=>!visiblePredecessorIds.includes(id)),duplicatePredecessor:visiblePredecessorIds.filter((id,index,rows)=>rows.indexOf(id)!==index),missingSuccessor:expectedSuccessorIds.filter(id=>!visibleSuccessorIds.includes(id)),duplicateSuccessor:visibleSuccessorIds.filter((id,index,rows)=>rows.indexOf(id)!==index)});
      const overlapId=expectedSuccessorIds.find(id=>document.querySelector(`[data-phase20-21-tutorial-origin="predecessor-authoritative"] [data-phase20-21-authoritative-predecessor-replay="${id}"]`)&&document.querySelector(`[data-phase20-21-tutorial-origin="successor"] [data-phase20-21-tutorial-replay="${id}"]:not(:disabled)`)),overlapBefore=overlapId?call('read','derive')?.tutorials?.replayCountsById?.[overlapId]:null,overlapResources=call('read','derive')?.resources,overlapRaw=call('read','raw'),overlapPredecessor=overlapId&&document.querySelector(`[data-phase20-21-tutorial-origin="predecessor-authoritative"] [data-phase20-21-authoritative-predecessor-replay="${overlapId}"]`),overlapContract=predecessorReplayContract(overlapPredecessor,overlapId),overlapSuccessorControl=overlapId&&document.querySelector(`[data-phase20-21-tutorial-origin="successor"] [data-phase20-21-tutorial-replay="${overlapId}"]`);add('overlap-origin-controls-are-enabled-and-bound',Boolean(overlapId)&&Boolean(overlapContract)&&!overlapPredecessor?.disabled&&!overlapSuccessorControl?.disabled&&typeof overlapPredecessor?.onclick==='function'&&typeof overlapSuccessorControl?.onclick==='function',{overlapId,layer:overlapContract?.layer,predecessorDisabled:overlapPredecessor?.disabled,successorDisabled:overlapSuccessorControl?.disabled,predecessorBound:typeof overlapPredecessor?.onclick,successorBound:typeof overlapSuccessorControl?.onclick});overlapPredecessor?.focus();overlapPredecessor?.click();await wait(35);const overlapSurface=overlapContract?document.querySelector(overlapContract.surface):null;add('overlap-carried-origin-delegates-authoritative-predecessor-replay',Boolean(overlapPredecessor)&&Boolean(overlapContract)&&overlapSurface?.getAttribute('data-phase20-21-tutorial-replay-owner')==='predecessor-authoritative'&&call('read','derive')?.tutorials?.replayCountsById?.[overlapId]===overlapBefore&&call('read','raw')===overlapRaw&&same(call('read','derive')?.resources,overlapResources),{overlapId,layer:overlapContract?.layer,owner:overlapSurface?.getAttribute('data-phase20-21-tutorial-replay-owner'),before:overlapBefore,after:overlapId?call('read','derive')?.tutorials?.replayCountsById?.[overlapId]:null});
      if(overlapContract)await click(overlapContract.close,'close-overlap-predecessor-replay');await wait(35);add('overlap-carried-replay-focus-returns-exact-origin',document.activeElement?.getAttribute('data-phase20-21-authoritative-predecessor-replay')===overlapId&&document.activeElement?.closest('[data-phase20-21-tutorial-origin]')?.getAttribute('data-phase20-21-tutorial-origin')==='predecessor-authoritative',{overlapId,layer:overlapContract?.layer,active:document.activeElement?.getAttribute('data-phase20-21-authoritative-predecessor-replay'),origin:document.activeElement?.closest('[data-phase20-21-tutorial-origin]')?.getAttribute('data-phase20-21-tutorial-origin')});
      const overlapSuccessor=overlapId&&document.querySelector(`[data-phase20-21-tutorial-origin="successor"] [data-phase20-21-tutorial-replay="${overlapId}"]`);overlapSuccessor?.focus();overlapSuccessor?.click();await wait(35);add('overlap-successor-origin-replays-exactly-once',Boolean(overlapId)&&document.querySelector('[data-phase20-21-tutorial-replay-owner="successor"]')&&call('read','derive')?.tutorials?.replayCountsById?.[overlapId]===overlapBefore+1&&same(call('read','derive')?.resources,overlapResources),{overlapId,before:overlapBefore,after:overlapId?call('read','derive')?.tutorials?.replayCountsById?.[overlapId]:null});
      await click('[data-phase20-21-tutorial-replay-close]','close-overlap-successor-replay');await wait(35);add('overlap-successor-replay-focus-returns-exact-origin',document.activeElement?.getAttribute('data-phase20-21-tutorial-replay')===overlapId&&document.activeElement?.closest('[data-phase20-21-tutorial-origin]')?.getAttribute('data-phase20-21-tutorial-origin')==='successor',{overlapId,active:document.activeElement?.getAttribute('data-phase20-21-tutorial-replay'),origin:document.activeElement?.closest('[data-phase20-21-tutorial-origin]')?.getAttribute('data-phase20-21-tutorial-origin')});
      const projectedReplay=document.querySelector('[data-phase20-21-tutorial-origin="predecessor-projection"] [data-phase20-21-tutorial-replay]'),projectedId=projectedReplay?.getAttribute('data-phase20-21-tutorial-replay'),projectedStatus=projectedId?call('read','derive')?.tutorials?.statusById?.[projectedId]:null;add('missing-carried-projection-is-honestly-unseen-and-disabled',Boolean(projectedId)&&projectedStatus==='unseen'&&projectedReplay.disabled===true&&typeof projectedReplay.onclick==='function',{projectedId,projectedStatus,disabled:projectedReplay?.disabled,bound:typeof projectedReplay?.onclick});
      const predecessorReplay=document.querySelector('[data-phase1819-tutorial-replay]');predecessorReplay?.focus();predecessorReplay?.click();await wait(35);add('predecessor-tutorial-replay-remains-visible',Boolean(document.querySelector('[data-phase1819-tutorial-replay-sheet]')));await click('[data-phase1819-tutorial-replay-close]','close-predecessor-tutorial-replay');await wait(35);hotspotFor('facility.command-center')?.click();await wait(35);await click('[data-phase20-21-open-tutorial-log]','reopen-tutorial-log');await wait(35);
      const replay=[...document.querySelectorAll('[data-phase20-21-tutorial-origin="successor"]')].map(row=>row.querySelector('[data-phase20-21-tutorial-replay]:not(:disabled)')).find(Boolean);replay?.focus();replay?.click();await wait(35);add('successor-tutorial-replay-visible-and-reward-neutral',Boolean(document.querySelector('[data-phase20-21-tutorial-replay-sheet]'))&&call('read','validate')?.ok===true);
      await click('[data-phase20-21-tutorial-replay-close]','close-tutorial-replay');await wait(35);add('tutorial-replay-focus-returns-exact-row',document.activeElement?.getAttribute('data-phase20-21-tutorial-replay')===replay?.getAttribute('data-phase20-21-tutorial-replay')&&document.activeElement?.closest('[data-phase20-21-tutorial-origin]')?.getAttribute('data-phase20-21-tutorial-origin')==='successor',{active:document.activeElement?.getAttribute('data-phase20-21-tutorial-replay'),origin:document.activeElement?.closest('[data-phase20-21-tutorial-origin]')?.getAttribute('data-phase20-21-tutorial-origin')});
      const nav=[...document.querySelectorAll('[data-nav]')].filter(node=>getComputedStyle(node).display!=='none');add('actual-dom-exact-five-navigation',nav.length===5,nav.map(node=>node.textContent.trim()));
      add('wayfarer-never-rendered-as-participant',!document.querySelector('[data-phase20-21-actor-choice="player.wayfarer"]'));
      add('final-state-valid',call('read','validate')?.ok===true,call('read','validate'));
      add('native-storage-instrumented',window.__P2021UI_NATIVE_INSTRUMENTED__===true);
      add('zero-native-storage-accesses',window.__P2021UI_NATIVE_ACCESSES__.length===0,window.__P2021UI_NATIVE_ACCESSES__);
      add('zero-warning-error-console',window.__P2021UI_ERRORS__.length===0,window.__P2021UI_ERRORS__);
      send();
    }

    async function inactiveSuite(){
      await wait(650);const buttons=f.facilityIds.map(hotspotFor),before=buttons.map(button=>button?{facilityId:button.getAttribute('data-phase15-facility-id'),state:button.getAttribute('data-phase15-state'),aria:button.getAttribute('aria-label'),hidden:button.getAttribute('aria-hidden'),disabled:button.disabled,phase2021:button.getAttribute('data-phase20-21-board-state'),onclick:String(button.onclick)}:null);
      add('production-off-has-no-phase20-root-or-bridge',!bridge()&&!archiveBridge());
      const inactiveSaves=[...window.__P2021UI_SLOTS__.values()].map(raw=>{try{return JSON.parse(raw)}catch{return null}}).filter(Boolean);add('production-off-retains-no-successor-synthetic-state',inactiveSaves.every(value=>!value.phase2021&&!value.phase15FacilityFoundation?.successorClaimAuthorityByFacilityId&&!value.phase15FacilityFoundation?.successorFoldCheckpoint),inactiveSaves.map(value=>({phase2021:Boolean(value.phase2021),authority:Boolean(value.phase15FacilityFoundation?.successorClaimAuthorityByFacilityId),checkpoint:Boolean(value.phase15FacilityFoundation?.successorFoldCheckpoint)})));
      add('production-off-all-eight-predecessor-hotspots-present',buttons.every(Boolean),before);
      add('production-off-no-successor-board-attributes',buttons.every(button=>!button.hasAttribute('data-phase20-21-board-state')));
      add('production-off-phase15-handlers-remain-owned',buttons.every(button=>String(button.onclick).includes('phaseFifteenOpenFacility')),buttons.map(button=>String(button.onclick)));
      document.querySelector('[data-nav="village"]')?.click();await wait(50);const after=f.facilityIds.map(hotspotFor).map(button=>button?{facilityId:button.getAttribute('data-phase15-facility-id'),state:button.getAttribute('data-phase15-state'),aria:button.getAttribute('aria-label'),hidden:button.getAttribute('aria-hidden'),disabled:button.disabled,phase2021:button.getAttribute('data-phase20-21-board-state')}:null);
      add('production-off-rerender-preserves-board-dom-state',same(before.map(({onclick,...row})=>row),after),{before:before.map(({onclick,...row})=>row),after});
      const visible=f.facilityIds.map(hotspotFor).find(button=>button&&!button.disabled);visible?.click();await wait(35);add('production-off-visible-location-opens-predecessor-sheet',!visible||Boolean(document.querySelector('[data-phase15-facility-sheet]'))&&!document.querySelector('[data-phase20-21-sheet]'),{visible:visible?.getAttribute('data-phase15-facility-id')});
      add('production-off-zero-warning-error-console',window.__P2021UI_ERRORS__.length===0,window.__P2021UI_ERRORS__);send();
    }

    (config.mode==='active'?activeSuite():inactiveSuite()).catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();if(source.indexOf('<script')<0)throw new Error('Production script tag missing');const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`;source=source.replace('<head>','<head><base href="../../">');const insertion=source.indexOf('<script');source=source.slice(0,insertion)+bootstrap+source.slice(insertion).replace('</body>',suite+'</body>');document.open();document.write(source);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
