(() => {
  'use strict';
  const CHANNEL='everstead-phase-20-21-ui',byId=id=>document.getElementById(id);
  const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const row=(id,actual,detail='')=>({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)});
  async function loadJson(source){const response=await fetch(source,{cache:'no-store'});if(!response.ok)throw new Error(`${source}: HTTP ${response.status}`);return response.json()}
  function realm(fixtures,viewport,mode='active'){return new Promise((resolve,reject)=>{
    const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),config={channel:CHANNEL,nonce,viewport,fixtures,mode};frame.name=JSON.stringify(config);frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0`;
    let timer;const finish=(error,value)=>{clearTimeout(timer);removeEventListener('message',receive);frame.remove();error?reject(error):resolve(value)};
    const receive=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=(event.data.results||[]).map(item=>({...item,id:`${viewport.id}-${mode}-${item.id}`}));if(event.data.errors?.length&&!rows.some(item=>item.id.endsWith('zero-warning-error-console')&&!item.pass))rows.push(row(`${viewport.id}-${mode}-captured-errors`,false,event.data.errors.join('\n')));finish(null,rows)};
    timer=setTimeout(()=>finish(new Error(`${viewport.id} ${mode} timed out`)),240000);addEventListener('message',receive);frame.src=`./realm.html?qa=1&mode=${encodeURIComponent(mode)}&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame);
  })}
  function render(mode,rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('mode').textContent=mode;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)} · observed ${item.actual?'true':'false'} · expected true${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_20_21_UI_RESULT__={mode,passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const fixtures=await loadJson('./fixtures/ui-fixtures.json'),rows=[];rows.push(row('fixture-eight-facilities',fixtures.facilityIds.length===8&&new Set(fixtures.facilityIds).size===8));rows.push(row('fixture-six-active-realms',fixtures.viewports.length===6&&fixtures.viewports.some(item=>item.width===320)&&fixtures.viewports.some(item=>item.width===768&&item.height===1024)&&fixtures.viewports.some(item=>item.width===1024&&item.height===768)&&fixtures.viewports.some(item=>item.reducedMotion&&item.copyScale===1.3)));for(const viewport of fixtures.viewports)rows.push(...await realm(fixtures,viewport));rows.push(...await realm(fixtures,fixtures.viewports[0],'inactive'));render('PRIVATE FACILITY UI',rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render('FATAL',[row('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
