(() => {
  'use strict';
  const CHANNEL='everstead-phase-8',inlineJson=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  function installRuntime(config){
    const slots=new Map(Object.entries(config.slots)),nativeSetTimeout=window.setTimeout.bind(window),nativeClearTimeout=window.clearTimeout.bind(window);let saveIndex=0,transactionIndex=0;
    const nativeStorageAccesses=[],errors=[];let nativeStorageInstrumented=false,exactNativeStorage=null;try{const nativeStorage=window.localStorage;exactNativeStorage=nativeStorage;if(config.mode==='native-storage')for(const key of Object.values(config.keys))nativeStorage.removeItem(key);for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    const presentationTimers=[];window.__PHASE_8_CONFIG__=config;window.__PHASE_8_SLOTS__=slots;window.__PHASE_8_ERRORS__=errors;window.__PHASE_8_NATIVE_STORAGE_ACCESSES__=nativeStorageAccesses;window.__PHASE_8_NATIVE_STORAGE_INSTRUMENTED__=nativeStorageInstrumented;window.__PHASE_8_PRESENTATION_TIMERS__=presentationTimers;window.matchMedia=query=>({matches:query==='(prefers-reduced-motion: reduce)'&&config.mode==='reduced-motion',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return true}});
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>slots.set(String(key),String(value)),removeItem:key=>slots.delete(String(key))},runtime={storage:config.mode==='native-storage'?exactNativeStorage:memoryStorage,clock:{now:()=>config.now,setTimeout(callback,delay){if(delay===1100)presentationTimers.push(delay);return nativeSetTimeout(callback,delay)},clearTimeout:nativeClearTimeout},random:()=>.5,confirm:()=>true,ids:{save:()=>config.saveId??`save-p8-browser-${++saveIndex}`,transaction:()=>`tx-p8-browser-${++transactionIndex}`},qa:config.mode==='unattested'?{allowDestructive:true,isolatedStorage:false}:{allowDestructive:true,isolatedStorage:true}};
    if(config.features)runtime.features=config.features;window.__EVERSTEAD_RUNTIME__=runtime;
  }
  function runSuite(){
    const channel='everstead-phase-8',config=window.__PHASE_8_CONFIG__,slots=window.__PHASE_8_SLOTS__,results=[],add=(id,pass,detail='')=>results.push({id,pass:Boolean(pass),detail:String(detail)}),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),click=selector=>{const node=document.querySelector(selector);if(node)node.click();return node},send=()=>parent.postMessage({channel,nonce:config.nonce,results,errors:window.__PHASE_8_ERRORS__.slice(),slots:Object.fromEntries(slots)},'*');
    (async()=>{await wait(500);const bridge=window.__EVERSTEAD_QA__;if(!config.expectBridge){add('encoded-query-bridge-absent',bridge===undefined);add('encoded-query-zero-errors',window.__PHASE_8_ERRORS__.length===0,window.__PHASE_8_ERRORS__.join('\n'));send();return}
      add('bridge-present',Boolean(bridge));add('viewport-exact',innerWidth===config.viewport.width&&innerHeight===config.viewport.height,`${innerWidth}x${innerHeight}`);add('no-horizontal-overflow',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);const first=bridge.snapshot(),state=first.state,flags=bridge.flags().features;add('schema9-snapshot',first.ok&&state.schemaVersion===9);add('phase8-state-shape',state.relicProgressLedger&&state.relics&&Number.isSafeInteger(state.relicStones)&&state.fellowCampaign.runCountsByStage);add('relic-foundation',state.relicStones===0&&Object.keys(state.relics).length===6&&Object.values(state.relics).every(item=>!item.owned&&item.level===0));add('relic-slots-foundation',Object.values(state.fellows).every(item=>JSON.stringify(item.relicSlots)==='[null]'));add('retired-flags-false',['story','tower','trading','patrol','operations'].every(key=>flags[key]===false));
      if(config.mode==='schema1-seed'){add('seed-pre-v9-present',JSON.parse(slots.get(config.keys.backupV8)).schemaVersion===8);add('seed-schema9-receipt',state.saveMeta.appliedMigrations.at(-1).id==='schema-8-to-9');add('seed-eleven-slots',Object.values(config.keys).filter(key=>key!==config.keys.staging).every(key=>slots.has(key)));add('seed-no-retro-phase8',state.relicStones===0&&Object.values(state.relics).every(item=>!item.owned)&&Object.values(state.fellowCampaign.runCountsByStage).every(value=>value===0));add('seed-zero-errors',window.__PHASE_8_ERRORS__.length===0,window.__PHASE_8_ERRORS__.join('\n'));send();return}
      if(config.mode==='fresh'){add('fresh-no-checkpoints',[0,1,2,3,4,5,6,7,8].every(version=>!slots.has(config.keys[`backupV${version}`])));click('[data-nav="fellows"]');await wait(20);const relicTab=click('[data-roster="relics"]');await wait(20);const text=document.querySelector('main.screen')?.textContent||'';add('relic-fourth-tab',Boolean(relicTab));add('relic-roster-ui',text.includes('Relics · one slot per Fellow')&&text.includes('Relic Stones')&&text.includes('First-Road Lantern'));add('relic-no-new-adventure-mode',![...document.querySelectorAll('[data-adventure]')].some(node=>/relic/i.test(node.dataset.adventure||'')));const exported=bridge.recovery.export().data;add('safe-export-eleven-slots',exported.exportVersion===9&&exported.preV9BackupKey===config.keys.backupV8&&Object.keys(exported.readErrors).length===11)}
      if(config.mode==='schema8'){add('schema8-checkpoint-exact',slots.get(config.keys.backupV8)===config.originalActiveRaw);add('schema8-one-receipt',state.saveMeta.appliedMigrations.filter(item=>item.id==='schema-8-to-9').length===1);add('schema8-no-retro-rewards',state.relicStones===0&&Object.values(state.relics).every(item=>!item.owned));add('schema8-reload',bridge.recovery.reload().ok)}
      if(config.mode==='legacy'){add('legacy-v0-exact',slots.get(config.keys.backupV0)===config.originalActiveRaw);add('legacy-all-checkpoints',[1,2,3,4,5,6,7,8].every(version=>JSON.parse(slots.get(config.keys[`backupV${version}`])).schemaVersion===version));add('legacy-unicode',state.oaths.some(oath=>oath.title==='Fixture café review 🌵'));add('legacy-no-retro-phase8',state.relicStones===0&&Object.values(state.relics).every(item=>!item.owned))}
      if(config.mode==='acquisition'){const firstRun=bridge.act('campaign-run',{id:'broken-roads-1'}),secondRun=bridge.act('campaign-run',{id:'broken-roads-2'}),select=bridge.act('campaign-select',{id:'broken-roads-1'}),replay=bridge.act('campaign-run',{id:'broken-roads-1'}),afterReplay=replay.state,side=afterReplay.relicProgressLedger.lastCampaignReceipt;add('first-relic-acquired',firstRun.ok&&firstRun.state.relics['first-road-lantern'].owned&&firstRun.state.relicStones===1);add('v2-campaign-preserved',firstRun.state.fellowCampaign.lastReceipt.rewardIdentityVersion===2&&firstRun.state.fellowCampaign.lastReceipt.rewardSalt==='fellow-campaign-v2');add('paired-side-receipt',side.identityVersion===1&&side.campaignRewardIdentity===afterReplay.fellowCampaign.lastReceipt.rewardIdentity);add('duplicate-salvage',secondRun.ok&&select.ok&&replay.ok&&!side.relicAcquired&&side.totalRelicStones===3&&afterReplay.relicStones===5);for(const id of ['cael','lyra','orin','selene','rook','mira'])bridge.controls.grant({resource:'fellowExp',id,amount:1000000});let stage7=null;for(let stage=3;stage<=7;stage++)stage7=bridge.act('campaign-run',{id:`broken-roads-${stage}`});const end=bridge.snapshot().state,last=end.relicProgressLedger.lastCampaignReceipt;add('six-relic-catalogue-acquired',Object.values(end.relics).every(item=>item.owned&&item.level===1));add('stage7-stone-only',stage7.ok&&last.targetRelicId===null&&last.totalRelicStones===3&&Object.keys(end.relics).length===6);add('acquisition-reload',bridge.recovery.reload().state.relicProgressLedger.lastCampaignReceipt.identity===last.identity)}
      if(config.mode==='equipment'){bridge.act('campaign-run',{id:'broken-roads-1'});bridge.act('relic-stones-grant',{amount:4});const rawBefore=slots.get(config.keys.active),equip=bridge.act('relic-equip',{fellowId:'cael',relicId:'first-road-lantern'}),equipped=equip.state;add('equip-owned-relic',equip.ok&&equipped.fellows.cael.relicSlots[0]==='first-road-lantern');const same=bridge.act('relic-equip',{fellowId:'cael',relicId:'first-road-lantern'});add('same-equip-noop',!same.ok&&same.changed===false&&slots.get(config.keys.active)!==rawBefore);const upgrade=bridge.act('relic-upgrade',{id:'first-road-lantern'});add('upgrade-level2-exact',upgrade.ok&&upgrade.state.relics['first-road-lantern'].level===2&&upgrade.state.relicStones===0);const move=bridge.act('relic-equip',{fellowId:'lyra',relicId:'first-road-lantern'});add('move-detaches-prior',move.ok&&move.state.fellows.cael.relicSlots[0]===null&&move.state.fellows.lyra.relicSlots[0]==='first-road-lantern');const unequip=bridge.act('relic-equip',{fellowId:'lyra',relicId:null});add('unequip-retains-inventory',unequip.ok&&unequip.state.fellows.lyra.relicSlots[0]===null&&unequip.state.relics['first-road-lantern'].owned);click('[data-nav="fellows"]');await wait(20);click('[data-roster="relics"]');await wait(20);const text=document.querySelector('main.screen')?.textContent||'';add('upgrade-ui-durable',text.includes('First-Road Lantern')&&text.includes('Level 2'));add('equipment-reload',bridge.recovery.reload().state.relics['first-road-lantern'].level===2)}
      if(config.mode==='normal-motion'||config.mode==='reduced-motion'){const reduced=config.mode==='reduced-motion';click('[data-nav="adventure"]');await wait(20);click('[data-adventure="fellowCampaign"]');await wait(20);const button=document.querySelector('[data-campaign-run]');add('production-run-button',Boolean(button));button?.click();const immediate=bridge.snapshot().state,walk=document.querySelector('.campaign-walk'),overlay=document.querySelector('#overlay')?.textContent||'';add('production-relic-receipt',immediate.relicProgressLedger.lastCampaignReceipt?.targetRelicId==='first-road-lantern');if(reduced){add('reduced-result-synchronous',overlay.includes('First-Road Lantern')&&overlay.includes('Relic reward'));add('reduced-no-running-class',!walk?.classList.contains('running'));add('reduced-no-presentation-timer',window.__PHASE_8_PRESENTATION_TIMERS__.length===0)}else{add('normal-running-class',walk?.classList.contains('running'));add('normal-result-delayed',!overlay.includes('First-Road Lantern')&&window.__PHASE_8_PRESENTATION_TIMERS__.length===1);const second=bridge.act('campaign-run',{id:'broken-roads-2'});add('second-run-before-modal',second.ok&&second.state.relicProgressLedger.lastCampaignReceipt.targetRelicId==='mossbound-compass');await wait(1200);const resultText=document.querySelector('#overlay')?.textContent||'';add('immutable-first-modal-pair',resultText.includes('First-Road Lantern')&&!resultText.includes('Mossbound Compass'),resultText)}}
      if(config.mode==='disabled-override'){const before=slots.get(config.keys.active),refused=['story','tower','trade','patrol-start','operation-start'].map(name=>bridge.act(name));add('explicit-true-retired-still-false',['story','tower','trading','patrol','operations'].every(key=>flags[key]===false));add('retired-actions-refused',refused.every(value=>!value.ok));add('retired-actions-zero-write',slots.get(config.keys.active)===before)}
      if(config.mode==='unattested'){const before=slots.get(config.keys.active),revision=state.saveMeta.revision,refused=[bridge.act('campaign-run',{id:'broken-roads-1'}),bridge.act('relic-stones-grant',{amount:1}),bridge.act('relic-equip',{fellowId:'cael',relicId:null})];add('unattested-phase8-actions-refused',refused.every(item=>!item.ok));add('unattested-zero-write',slots.get(config.keys.active)===before&&bridge.snapshot().state.saveMeta.revision===revision)}
      if(config.mode==='all-disabled'){const before=slots.get(config.keys.active),revision=state.saveMeta.revision,ui=document.body.innerHTML,refused=[bridge.act('campaign-run',{id:'broken-roads-1'}),bridge.act('relic-equip',{fellowId:'cael',relicId:null})];add('all-disabled-actions-refused',refused.every(item=>!item.ok));add('all-disabled-zero-write',slots.get(config.keys.active)===before&&bridge.snapshot().state.saveMeta.revision===revision);add('all-disabled-zero-ui-mutation',document.body.innerHTML===ui)}
      if(config.mode==='native-storage'){window.__PHASE_8_NATIVE_STORAGE_ACCESSES__.length=0;const revision=state.saveMeta.revision,ui=document.body.innerHTML,refused=[bridge.act('campaign-run',{id:'broken-roads-1'}),bridge.act('relic-stones-grant',{amount:1}),bridge.act('relic-equip',{fellowId:'cael',relicId:null})];add('native-actions-refused',refused.every(item=>!item.ok));add('native-zero-state-mutation',bridge.snapshot().state.saveMeta.revision===revision);add('native-zero-ui-mutation',document.body.innerHTML===ui);add('native-zero-action-storage-calls',window.__PHASE_8_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_8_NATIVE_STORAGE_ACCESSES__.join(','));add('native-realm-zero-errors',window.__PHASE_8_ERRORS__.length===0,window.__PHASE_8_ERRORS__.join('\n'));send();return}
      const diagnostics=bridge.diagnostics().diagnostics;add('diagnostics-phase8',diagnostics.schema.current===9&&Object.hasOwn(diagnostics,'preV9Backup')&&Object.hasOwn(diagnostics,'relics')&&Object.hasOwn(diagnostics,'phaseEightCampaignEpoch'));add('native-storage-instrumented',window.__PHASE_8_NATIVE_STORAGE_INSTRUMENTED__===true);add('zero-native-storage-calls',window.__PHASE_8_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_8_NATIVE_STORAGE_ACCESSES__.join(','));add('realm-zero-errors',window.__PHASE_8_ERRORS__.length===0,window.__PHASE_8_ERRORS__.join('\n'));send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }
  let loaderNonce='unknown';(async()=>{const config=JSON.parse(window.name);loaderNonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error('index.html: HTTP '+response.status);const source=await response.text(),firstScript=source.indexOf('<script>');if(firstScript<0)throw new Error('Production script is missing');const bootstrap='<script>('+installRuntime.toString()+')('+inlineJson(config)+')<\/script>',suite='<script>('+runSuite.toString()+')()<\/script>',instrumented=source.slice(0,firstScript)+bootstrap+source.slice(firstScript).replace('</body>',suite+'</body>');document.open();document.write(instrumented);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce:loaderNonce,results:[{id:'realm-loader-fatal',pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
