(() => {
  'use strict';
  const CHANNEL='everstead-phase-8',byId=id=>document.getElementById(id),result=(id,pass,detail='')=>({id,pass:Boolean(pass),detail:String(detail)}),escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),hex=bytes=>[...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,'0')).join(''),sha256=async bytes=>hex(await crypto.subtle.digest('SHA-256',bytes)),decode=bytes=>new TextDecoder('utf-8',{fatal:true}).decode(bytes);
  async function bytes(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return new Uint8Array(await response.arrayBuffer())}
  async function loadContract(){const manifest=JSON.parse(decode(await bytes('./current-manifest.json'))),scenarioBytes=await bytes('./scenarios.json'),scenarios=JSON.parse(decode(scenarioBytes));if(await sha256(scenarioBytes)!==manifest.scenarios.sha256)throw new Error('Scenario checksum mismatch');const staticResults=[];for(const[path,expected]of Object.entries(manifest.frozenHistoricalFiles)){const actual=await sha256(await bytes('../../'+path));staticResults.push(result('frozen-'+path.replaceAll('/','-'),actual===expected,actual))}const artifactBytes=await bytes('../../index.html'),artifactHash=await sha256(artifactBytes);if(artifactHash!==manifest.artifact.sha256||artifactBytes.byteLength!==manifest.artifact.byteLength)throw new Error('Artifact checksum mismatch');staticResults.push(result('artifact-checksum',true,artifactHash));return{manifest,scenarios,schemaOneRaw:decode(await bytes('../gate-0b/fixtures/current-v1.txt')),legacyRaw:decode(await bytes('../fixtures/representative-v0.1.txt')),staticResults}}
  function executeRealm(contract,viewport,mode,{search='?qa=1',seedSlots=null}={}){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),keys=contract.scenarios.storageKeys;let slots={};if(mode==='schema1-seed')slots[keys.active]=contract.schemaOneRaw;else if(mode==='legacy')slots[keys.active]=contract.legacyRaw;else if(mode==='schema8'){slots={...seedSlots,[keys.active]:seedSlots[keys.backupV8]};delete slots[keys.staging]}const features=mode==='disabled-override'?{fellowCampaign:true,fellowExpedition:true,companionCampaign:true,companionTower:true,story:true,tower:true,trading:true,patrol:true,operations:true}:mode==='all-disabled'?{fellowCampaign:false,fellowExpedition:false,companionCampaign:false,companionTower:false,story:false,tower:false,trading:false,patrol:false,operations:false}:undefined,config={nonce,mode,expectBridge:search==='?qa=1',viewport,now:Date.parse(contract.scenarios.frozenNow),features,keys,originalActiveRaw:slots[keys.active]??null,slots};frame.name=JSON.stringify(config);frame.setAttribute('sandbox','allow-scripts allow-same-origin');frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0`;const finish=(error,value)=>{clearTimeout(timeout);removeEventListener('message',onMessage);frame.remove();error?reject(error):resolve(value)},onMessage=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=event.data.results.map(item=>({...item,id:`${viewport.id}-${mode}-${item.id}`}));if(event.data.errors?.length)rows.push(result(`${viewport.id}-${mode}-captured-errors`,false,event.data.errors.join('\n')));finish(null,{rows,slots:event.data.slots??{}})},timeout=setTimeout(()=>finish(new Error(`${viewport.id}/${mode} timed out`)),45000);addEventListener('message',onMessage);frame.src=`./realm.html${search}&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  function render(rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)}${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_8_RESULT__={passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const data=await loadContract(),rows=[...data.staticResults],seed=await executeRealm(data,data.scenarios.viewports[0],'schema1-seed');rows.push(...seed.rows);if(!seed.slots[data.scenarios.storageKeys.backupV8])throw new Error('Schema-1 seed realm did not expose the exact schema-8 checkpoint');const modes=['fresh','schema8','legacy','acquisition','equipment','normal-motion','reduced-motion','disabled-override','all-disabled','native-storage'];for(const viewport of data.scenarios.viewports)for(const mode of modes){const realm=await executeRealm(data,viewport,mode,{seedSlots:seed.slots});rows.push(...realm.rows)}const unattested=await executeRealm(data,data.scenarios.viewports[0],'unattested'),negative=await executeRealm(data,data.scenarios.viewports[0],'encoded-negative',{search:'?qa=%31'});rows.push(...unattested.rows,...negative.rows);render(rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render([result('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
