import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import vm from 'node:vm';

const repoRoot=resolve(new URL('../..',import.meta.url).pathname);
const releasedPhaseSixSource=execFileSync('git',['show','1ffa12eb73cccb4de40769ae7251937c67f69766:index.html'],{cwd:repoRoot,encoding:'utf8',maxBuffer:32*1024*1024});
const releasedPhaseSixApplicationSource=releasedPhaseSixSource.match(/<script>([\s\S]*?)<\/script>/)?.[1];
const phaseSevenManifest=JSON.parse(readFileSync(resolve(repoRoot,'qa/phase-7/current-manifest.json'),'utf8'));
const phaseSixVerifier=readFileSync(resolve(repoRoot,'qa/phase-6/verify.mjs'),'utf8');
let harness=phaseSixVerifier.split("check('artifact-source'")[0]
  .replace(/^import .*;\n/gm,'')
  .replace("setFlagsFromString('--no-opt');\n\n",'')
  .replaceAll('timeout:30000','timeout:180000')
  .replace("const qaRoot=dirname(fileURLToPath(import.meta.url));\nconst repoRoot=resolve(qaRoot,'..','..');",`const qaRoot=${JSON.stringify(resolve(repoRoot,'qa/phase-6'))};\nconst repoRoot=${JSON.stringify(repoRoot)};`)
  .replace("  preV7:'oathforge_new_world_proto_v01__raw_backup_v6',\n  staging:","  preV7:'oathforge_new_world_proto_v01__raw_backup_v6',\n  preV8:'oathforge_new_world_proto_v01__raw_backup_v7',\n  staging:")
  .replace('preV7BackupRaw:keys.preV7,stagingRaw:', 'preV7BackupRaw:keys.preV7,preV8BackupRaw:keys.preV8,stagingRaw:')
  .replace('return value?.schemaVersion===7?value:null', 'return value?.schemaVersion===8?value:null')
  .replace('vm.runInContext(instrument(source),context,{timeout:180000})','vm.runInContext(options.applicationSource??instrument(source),context,{timeout:180000})')
  .replace('    tamperClear(){',`    p7:Object.freeze({
      config:()=>clone({might:FELLOW_MIGHT_CONFIG,expedition:FELLOW_EXPEDITION_CONFIG,identity:PHASE_SEVEN_CONFIG_IDENTITY,replayCap:PHASE_SEVEN_REPLAY_COUNT_CAP}),
      stages:()=>clone(FELLOW_EXPEDITION_STAGES),requirements:()=>clone(FELLOW_EXPEDITION_REQUIREMENTS),might:fellowMightComponents,mightLevel:fellowMightLevel,
      power:effectiveFellowPowerComponents,total:totalFellowRosterPower,preview:previewFellowExpedition,resolve:fellowExpeditionResolve,view:fellowExpeditionView,adventureView:adventureScreen,rosterView:rosterScreen,
      push:pushFellowExpedition,claim:claimFellowExpedition,idle:fellowExpeditionIdlePreview,history:expeditionHistoryReplay,consume:consumeExpeditionIntervals,
      requirement:fellowExpeditionRequirement,mightPerHour:fellowExpeditionMightPerInterval,shardChance:fellowExpeditionShardChance,tick:expeditionTick,
      campaignPreview:campaignPreview,campaignRun:runFellowCampaign,grantExp:grantFellowExp,grantShards:grantFellowShards,schemaScoped:schemaScopedDefaultState,
      bestIdentity:fellowExpeditionBestReceiptIdentity,idleIdentity:fellowExpeditionIdleReceiptIdentity,pendingIdentity:fellowExpeditionPendingIdentity,
      replayUsage:phaseSevenReplayUsage,replayAllows:phaseSevenReplayAllows,runtimeCapture:()=>qaRuntimeSnapshot(),fixtureProbe:input=>{const complete={activeRaw:input?.activeRaw,backupRaw:Object.hasOwn(input||{},'backupRaw')?input.backupRaw:null,stagingRaw:Object.hasOwn(input||{},'stagingRaw')?input.stagingRaw:null};try{return{ok:true,value:qaInstallFixture(complete)}}catch(error){return{ok:false,error:String(error.message||error)}}},
      historicalSeven(raw,slotRaws){const value=JSON.parse(raw),lineage=schemaSevenCheckpointLineageForRaws(slotRaws),state=runMigrations(value,6,{source:'schema-6',now:1787853606000,preV7Raw:raw,checkpointLineage:lineage},7);return{stateRaw:JSON.stringify(state),stagingRaw:JSON.stringify(stagingEnvelope(state,raw,'schema-6-migration'))}},
      historicalSevenFresh(){const at=1787853607000,meta=newMetadata('fresh',at,[]),state=schemaScopedDefaultState(meta,7);return{stateRaw:JSON.stringify(state),stagingRaw:JSON.stringify(stagingEnvelope(state,null,'fresh'))}},
      freshEightStage(){const state=prepareFresh();return{stateRaw:JSON.stringify(state),stagingRaw:JSON.stringify(stagingEnvelope(state,null,'fresh'))}},
      historicalTarget(stateRaw,activeRaw,source){const state=JSON.parse(stateRaw);return JSON.stringify(stagingEnvelope(state,activeRaw,source))},
      historicalFresh(version){const at=1787853599000+version,meta=newMetadata('fresh',at,[]),state=schemaScopedDefaultState(meta,version);return{stateRaw:JSON.stringify(state),stagingRaw:JSON.stringify(stagingEnvelope(state,null,'fresh'))}},
      historicalCurrentFor(activeRaw){const state=JSON.parse(activeRaw),source='boot';state.ui.screen=state.ui.screen==='village'?'roster':'village';state.saveMeta.revision++;state.saveMeta.updatedAt=Math.max(state.saveMeta.updatedAt+1,1787853610000);state.saveMeta.source=source;return{stateRaw:JSON.stringify(state),stagingRaw:JSON.stringify(stagingEnvelope(state,activeRaw,source))}},
      historicalSafeReset(version,activeRaw,slotRaws){const at=1787853615000+version,meta=newMetadata('safe-reset',at,[]),state=schemaScopedDefaultState(meta,version),slots={backupRaw:slotRaws.backupRaw??null,preV2BackupRaw:slotRaws.preV2Raw??null,preV3BackupRaw:slotRaws.preV3Raw??null,preV4BackupRaw:slotRaws.preV4Raw??null,preV5BackupRaw:slotRaws.preV5Raw??null,preV6BackupRaw:slotRaws.preV6Raw??null,preV7BackupRaw:slotRaws.preV7Raw??null};state.saveMeta.retainedCheckpointLineage=retainedCheckpointLineageMarker(state,slots,activeRaw);return{stateRaw:JSON.stringify(state),stagingRaw:JSON.stringify(stagingEnvelope(state,activeRaw,'safe-reset'))}},
      campaignUsageState(total){if(!Number.isSafeInteger(total)||total<2||total>PHASE_SEVEN_REPLAY_COUNT_CAP)throw new Error('Campaign usage fixture total is invalid');const state=clone(S),first=FELLOW_CAMPAIGN_STAGES[0],stage=FELLOW_CAMPAIGN_STAGES[1],counts=campaignStageCountMap();counts[first.id]=1;counts[stage.id]=total-1;state.fellowCampaign.runCountsByStage=counts;const post=fellowCampaignV2Replay(state);state.fellowCampaign.runOrdinal=state.fellowProgressLedger.campaignBaseline.runOrdinal+post.totalRuns;state.fellowCampaign.clearedStageIds=[first.id,stage.id];state.fellowCampaign.firstClearClaimedStageIds=[first.id,stage.id];state.fellowCampaign.selectedStageId=stage.id;state.player.rankExp=state.fellowProgressLedger.campaignBaseline.playerRankExp+post.rankExp;state.player.rank=playerRankForExp(state.player.rankExp);for(const def of FELLOW_DEFS){const baseline=state.fellowProgressLedger.schema7Baseline[def.id];state.fellows[def.id].exp=baseline.exp+post.fellowExp[def.id];state.fellows[def.id].level=fellowLevelForExp(state.fellows[def.id].exp);state.fellows[def.id].shards=baseline.shards+post.fellowShards[def.id]}const stageRunSequence=counts[stage.id],preStage=stageRunSequence-1,reward=fellowCampaignV2Reward(stage,false,state.saveMeta.saveId,preStage),exp=fellowRewardMap(),shards=fellowRewardMap(),totalPower=totalFellowRosterPower(state),efficiency=campaignEfficiencyForTotal(totalPower,stage.baseCost,stage.recommendedPower);exp[stage.targetFellowId]=reward.exp;shards[stage.targetFellowId]=reward.shards;const receipt={stageId:stage.id,completedAt:state.saveMeta.updatedAt,sequence:state.fellowCampaign.runOrdinal,stageRunSequence,firstClear:false,baseCost:stage.baseCost,recommendedPower:stage.recommendedPower,totalRosterPower:totalPower,effectiveCost:efficiency.effectiveCost,rewardIdentityVersion:FELLOW_CAMPAIGN_V2_VERSION,rewardSalt:FELLOW_CAMPAIGN_V2_SALT,rewardIdentity:'',rewards:{fellowExp:exp,fellowShards:shards,rankExp:0,gifts:reward.gifts}};receipt.rewardIdentity=campaignV2Identity(state.saveMeta.saveId,receipt);state.fellowCampaign.lastReceipt=receipt;return JSON.stringify(state)},
      expeditionUsageState(total){if(!Number.isSafeInteger(total)||total<1||total>PHASE_SEVEN_REPLAY_COUNT_CAP)throw new Error('Expedition usage fixture total is invalid');if(S.fellowExpedition.highestStage===0)pushFellowExpedition({confirmed:true,present:false});const state=clone(S),idle=state.fellowExpedition.idle,counts=expeditionStageCountMap(),prefix=expeditionStageCountMap(),batch=Math.min(24,total),beforeTotal=total-batch,owned=FELLOW_DEFS.filter(def=>state.fellowProgressLedger.schema7Baseline[def.id].owned).map(def=>def.id);counts['3']=total;prefix['3']=beforeTotal;const before=expeditionHistoryReplay(state.saveMeta.saveId,prefix,owned),after=expeditionHistoryReplay(state.saveMeta.saveId,counts,owned),shards=fellowRewardMap();for(const def of FELLOW_DEFS){shards[def.id]=after.fellowShards[def.id]-before.fellowShards[def.id];state.fellows[def.id].shards=state.fellowProgressLedger.schema7Baseline[def.id].shards+after.fellowShards[def.id]}const claimedAt=idle.cursorAt,preSegments=[{stage:3,elapsedMs:batch*FELLOW_EXPEDITION_CONFIG.intervalMs}],intervalCounts=expeditionStageCountMap();intervalCounts['3']=batch;idle.claimedIntervalsByStage=counts;idle.intervalOrdinal=total;idle.pityMisses=after.pityMisses;idle.claimOrdinal=Math.ceil(total/24);idle.claimedTotals={mightNominal:after.mightNominal,fellowShards:clone(after.fellowShards)};idle.lastClaimAt=claimedAt;idle.segments=[{stage:3,elapsedMs:FELLOW_EXPEDITION_CONFIG.intervalMs}];state.fellowMight.points=Math.min(FELLOW_MIGHT_CONFIG.pointsCap,after.mightNominal);const receipt={mode:'fellowExpeditionIdle',identityVersion:1,pendingIdentity:'',receiptIdentity:'',claimedAt,sequence:idle.claimOrdinal,preClaimBestRunSequence:1,preClaimHighestStage:3,preClaimCursorAt:claimedAt,preClaimSegments:preSegments,preClaimClaimedIntervalsByStage:prefix,preClaimIntervalOrdinal:before.intervalOrdinal,preClaimPityMisses:before.pityMisses,consumedElapsedMs:batch*FELLOW_EXPEDITION_CONFIG.intervalMs,intervalOrdinalStart:before.intervalOrdinal,intervalOrdinalEnd:after.intervalOrdinal,intervalCountsByStage:intervalCounts,remainingSegments:[],mightNominal:after.mightNominal-before.mightNominal,preMightPoints:Math.min(FELLOW_MIGHT_CONFIG.pointsCap,before.mightNominal),postMightPoints:Math.min(FELLOW_MIGHT_CONFIG.pointsCap,after.mightNominal),mightAwarded:Math.min(FELLOW_MIGHT_CONFIG.pointsCap,after.mightNominal)-Math.min(FELLOW_MIGHT_CONFIG.pointsCap,before.mightNominal),fellowShards:shards,pityAfter:after.pityMisses};receipt.pendingIdentity=fellowExpeditionPendingIdentity(state.saveMeta.saveId,receipt);receipt.receiptIdentity=fellowExpeditionIdleReceiptIdentity(state.saveMeta.saveId,receipt);idle.lastReceipt=receipt;return JSON.stringify(state)},
      malformed(value){try{return validation(value)}catch(error){return{threw:String(error)}}},
      tamper(kind){const value=clone(S),idle=value.fellowExpedition?.idle,best=value.fellowExpedition?.lastBestReceipt;if(kind==='campaign-reward'){value.fellowCampaign.lastReceipt.rewards.rankExp++}if(kind==='campaign-gap'){value.fellowCampaign.runCountsByStage['broken-roads-3']=1}if(kind==='best-power'){best.rosterSnapshot[0].effectivePower++;best.identity=fellowExpeditionBestReceiptIdentity(value.saveMeta.saveId,best)}if(kind==='best-prior'){best.priorHighestStage=2;best.identity=fellowExpeditionBestReceiptIdentity(value.saveMeta.saveId,best)}if(kind==='idle-preimage'){idle.lastReceipt.preClaimPityMisses=(idle.lastReceipt.preClaimPityMisses+1)%8;idle.lastReceipt.pendingIdentity=fellowExpeditionPendingIdentity(value.saveMeta.saveId,idle.lastReceipt);idle.lastReceipt.receiptIdentity=fellowExpeditionIdleReceiptIdentity(value.saveMeta.saveId,idle.lastReceipt)}if(kind==='idle-result'){idle.lastReceipt.mightNominal++;idle.lastReceipt.receiptIdentity=fellowExpeditionIdleReceiptIdentity(value.saveMeta.saveId,idle.lastReceipt)}if(kind==='idle-missing-claim'){idle.claimOrdinal=0;idle.lastClaimAt=null;idle.lastReceipt=null}if(kind==='claim-sequence-prefix'){idle.claimOrdinal=1;idle.lastReceipt.sequence=1;idle.lastReceipt.pendingIdentity=fellowExpeditionPendingIdentity(value.saveMeta.saveId,idle.lastReceipt);idle.lastReceipt.receiptIdentity=fellowExpeditionIdleReceiptIdentity(value.saveMeta.saveId,idle.lastReceipt)}if(kind==='idle-best-pair'){idle.lastReceipt.preClaimBestRunSequence++;idle.lastReceipt.pendingIdentity=fellowExpeditionPendingIdentity(value.saveMeta.saveId,idle.lastReceipt);idle.lastReceipt.receiptIdentity=fellowExpeditionIdleReceiptIdentity(value.saveMeta.saveId,idle.lastReceipt)}return validation(value)},
      findMissSeed(stage=3,count=7){const counts=expeditionStageCountMap();counts[String(stage)]=count;const owned=FELLOW_DEFS.map(def=>def.id);for(let index=0;index<100000;index++){const saveId='p7-pity-'+index,replay=expeditionHistoryReplay(saveId,counts,owned);if(replay.pityMisses===count)return saveId}return null}
    }),
    tamperClear(){`);

const suite=String.raw`
const stateOf=run=>JSON.parse(activeRaw(run));
const slotSnapshot=run=>Object.fromEntries(Object.values(keys).map(key=>[key,run.slots.get(key)??null]));
const noUiChange=(before,after)=>before.innerHTML===after.innerHTML&&before.className===after.className;
const p7=(run,expression)=>internal(run,'p7.'+expression);
const current=(state,options={})=>runRealm({...freshOptions,activeRaw:JSON.stringify(state),...options});

check('artifact-source',Boolean(source));
check('released-phase6-schema7-boundary',releasedPhaseSixSource.includes('CURRENT_SCHEMA_VERSION=7')&&!releasedPhaseSixSource.includes('fellowExpedition')&&!releasedPhaseSixSource.includes('bestStagesBySequence'));
check('preseal-canonical-main-phase6',phaseSevenManifest.preSealReleaseEvidence.canonicalMainCommit===phaseSevenManifest.baseCommit&&phaseSevenManifest.preSealReleaseEvidence.originMainCommit===phaseSevenManifest.baseCommit);
check('preseal-public-phase6-exact',phaseSevenManifest.preSealReleaseEvidence.publicArtifactSha256===phaseSevenManifest.baseArtifact.sha256&&phaseSevenManifest.preSealReleaseEvidence.publicArtifactByteLength===phaseSevenManifest.baseArtifact.byteLength&&phaseSevenManifest.preSealReleaseEvidence.publicSchemaVersion===7&&phaseSevenManifest.preSealReleaseEvidence.phaseSevenMarkersPresent===false);
check('artifact-size',htmlBytes.length>1_000_000,htmlBytes.length);
check('schema8-static',source.includes('CURRENT_SCHEMA_VERSION=8')&&source.includes("PRE_V8_BACKUP_KEY=NS+'__raw_backup_v7'")&&source.includes("id:'schema-7-to-8'"));
check('ten-slot-static',source.includes('exportVersion:8')&&source.includes('preV8BackupRaw'));
check('phase7-feature-static',source.includes('fellowExpedition:true'));
check('four-routes-static',source.includes("['fellowExpedition','Expedition']")&&source.includes('Four distinct progression roads'));
check('might-once-static',source.includes("'globalMightMultiplier','round'")&&source.includes('afterCompanion*prior.familyBondMultiplier*globalMultiplier'));
check('village-hook-neutral-static',source.includes("fellowRoster:0")&&!source.includes('controlled Fellow contribution'));
check('campaign-v2-static',source.includes("FELLOW_CAMPAIGN_V2_VERSION=2")&&source.includes("FELLOW_CAMPAIGN_V2_SALT='fellow-campaign-v2'"));
check('idle-no-continuous-timer-static',source.includes('Claim Expedition Rewards'.toUpperCase())||source.includes('CLAIM EXPEDITION REWARDS'));
check('idle-claim-lineage-static',source.includes('fellowExpedition.idle.claimLineage')&&source.includes('(idle.intervalOrdinal===0)!==(idle.claimOrdinal===0)'));
check('might-cap-preview-static',source.includes('actual</b><span>')&&source.includes('nominal · ')&&source.includes('FELLOW_MIGHT_CONFIG.pointsCap'));
check('best-chronology-static',source.includes('bestStagesBySequence')&&source.includes('history.length!==expedition?.bestRunSequence'));
check('replay-ceiling-static',source.includes('PHASE_SEVEN_REPLAY_COUNT_CAP=100000')&&source.includes('phaseSevenReplayAllows'));

const fresh=runRealm(freshOptions),freshState=active(fresh);
if(!fresh.context.__P6__){console.error('Phase 7 instrumentation failed',fresh.thrown?.stack??'hook missing');process.exit(1)}
check('fresh-no-throw',fresh.thrown===null,fresh.thrown?.stack??'');
check('fresh-schema8',freshState?.schemaVersion===8);
check('fresh-best-history-empty',Array.isArray(freshState?.fellowExpedition?.bestStagesBySequence)&&freshState.fellowExpedition.bestStagesBySequence.length===0);
check('fresh-valid',valid(fresh).ok,valid(fresh).errors);
check('fresh-ten-slot-export',Object.keys(internal(fresh,'export().readErrors')).length===10);
check('fresh-no-native-storage',fresh.nativeCalls.length===0,JSON.stringify(fresh.nativeCalls));
check('fresh-might-zero',freshState.fellowMight.points===0&&p7(fresh,'might().level')===0&&p7(fresh,'might().multiplier')===1);
check('fresh-expedition-zero',freshState.fellowExpedition.highestStage===0&&freshState.fellowExpedition.bestRunSequence===0&&freshState.fellowExpedition.idle.intervalOrdinal===0);
check('fresh-source-ledger',freshState.fellowProgressLedger.configIdentity==='phase-7-fellow-progression-v1'&&Object.keys(freshState.fellowProgressLedger.schema7Baseline).length===6);
check('fresh-campaign-count-map',Object.values(freshState.fellowCampaign.runCountsByStage).every(value=>value===0));
check('fresh-route-preserved',freshState.ui.adventure==='fellowCampaign');

const config=p7(fresh,'config()'),stages=p7(fresh,'stages()');
check('config-might',JSON.stringify(config.might)===JSON.stringify({pointsCap:50000,levelCap:50,thresholdFactor:20,powerPerLevel:.01}));
check('config-expedition',JSON.stringify(config.expedition)===JSON.stringify({stageCap:50,requirementBase:5500,requirementGrowth:1.08,elapsedCapMs:86400000,intervalMs:3600000,pityForceAt:8}));
check('config-identity',config.identity==='phase-7-fellow-progression-v1');
check('stage-count-50',stages.length===50);
for(const stage of stages){const expected=Math.round(5500*Math.pow(1.08,stage.stage-1));check('stage-'+stage.stage+'-definition',stage.id==='fellow-expedition-'+stage.stage&&stage.minimumRosterSize===stage.stage&&stage.requirement===expected)}
for(const [points,level] of [[0,0],[19,0],[20,1],[79,1],[80,2],[49999,49],[50000,50]])check('might-level-'+points,p7(fresh,'mightLevel('+points+')')===level);
for(const stage of [1,2,3,10,25,50]){check('stage-'+stage+'-might-rate',p7(fresh,'mightPerHour('+stage+')')===1+Math.floor((stage-1)/2));check('stage-'+stage+'-shard-chance',p7(fresh,'shardChance('+stage+')')===Math.min(.30,.08+.02*(stage-1)))}
for(const [value,expected] of [[0,0],[.5,0],[1,1],[Number.MAX_SAFE_INTEGER,Number.MAX_SAFE_INTEGER],[Number.MAX_SAFE_INTEGER+1,Number.MAX_SAFE_INTEGER],[Number.MAX_VALUE,Number.MAX_SAFE_INTEGER],[-1,0]])check('tick-'+String(value),p7(fresh,'tick('+String(value)+')')===expected);

const freshPower=Object.fromEntries(['cael','lyra','orin','selene','rook','mira'].map(id=>[id,p7(fresh,"power('"+id+"').effectivePower")]));
check('fresh-power-exact',JSON.stringify(freshPower)===JSON.stringify({cael:6652,lyra:6508,orin:6348,selene:5381,rook:6247,mira:5230}),freshPower);
check('fresh-total-safe',p7(fresh,'total()')===36366);
const preview=p7(fresh,'preview()');
check('fresh-best-stage3',preview.resolution.highestStage===3&&preview.newHigh===true);
check('fresh-weakest-order',preview.rosterSnapshot.map(item=>item.fellowId).join(',')==='mira,selene,rook,orin,lyra,cael');
check('fresh-clear-order',preview.resolution.exhaustedFellowIds.join(',')==='rook,orin,lyra');
check('fresh-next-wall',preview.resolution.nextUnmetStage===4&&preview.resolution.nextRequirement===6928);
check('fresh-no-duplicate-exhaustion',new Set(preview.resolution.exhaustedFellowIds).size===preview.resolution.exhaustedFellowIds.length);
check('resolver-requirement-minus-one',p7(fresh,"resolve([{fellowId:'cael',definitionOrder:0,effectivePower:5499}])").highestStage===0);
check('resolver-requirement-exact',p7(fresh,"resolve([{fellowId:'cael',definitionOrder:0,effectivePower:5500}])").highestStage===1);
check('resolver-tie-definition-order',p7(fresh,"resolve([{fellowId:'cael',definitionOrder:0,effectivePower:7000},{fellowId:'lyra',definitionOrder:1,effectivePower:7000}])").exhaustedFellowIds[0]==='cael');
const concentrated=p7(fresh,"resolve([{fellowId:'cael',definitionOrder:0,effectivePower:18000},{fellowId:'lyra',definitionOrder:1,effectivePower:1000},{fellowId:'orin',definitionOrder:2,effectivePower:1000}])"),balanced=p7(fresh,"resolve([{fellowId:'cael',definitionOrder:0,effectivePower:7000},{fellowId:'lyra',definitionOrder:1,effectivePower:6500},{fellowId:'orin',definitionOrder:2,effectivePower:6500}])");
check('breadth-not-total',concentrated.highestStage===1&&balanced.highestStage===3);

const pushRun=runRealm(freshOptions),beforePush=clone(active(pushRun)),pushResult=p7(pushRun,'push({confirmed:true,present:false})'),afterPush=active(pushRun),pushReceipt=afterPush.fellowExpedition.lastBestReceipt;
check('push-new-high',pushResult.ok===true&&afterPush.fellowExpedition.highestStage===3&&afterPush.fellowExpedition.bestRunSequence===1);
check('push-no-direct-reward',afterPush.gold===beforePush.gold&&afterPush.gifts===beforePush.gifts&&afterPush.player.rankExp===beforePush.player.rankExp&&Object.keys(afterPush.fellows).every(id=>afterPush.fellows[id].exp===beforePush.fellows[id].exp&&afterPush.fellows[id].shards===beforePush.fellows[id].shards));
check('push-receipt-order',pushReceipt.exhaustedFellowIds.join(',')==='rook,orin,lyra'&&pushReceipt.stageResults.length===3);
check('push-best-history',JSON.stringify(afterPush.fellowExpedition.bestStagesBySequence)===JSON.stringify([{sequence:1,highestStage:3}]));
check('push-receipt-identity',pushReceipt.identity===p7(pushRun,'bestIdentity('+JSON.stringify(afterPush.saveMeta.saveId)+','+JSON.stringify(pushReceipt)+')'));
check('push-first-prior-tamper-rejected',p7(pushRun,"tamper('best-prior')").ok===false);
check('push-valid',valid(pushRun).ok,valid(pushRun).errors);
const equalRaw=activeRaw(pushRun),equalWrites=writes(pushRun),equalToast=clone(pushRun.nodes['#toast']),equal=p7(pushRun,'push({confirmed:true,present:false})');
check('push-equal-zero-write',equal===false&&activeRaw(pushRun)===equalRaw&&writes(pushRun)===equalWrites&&noUiChange(equalToast,pushRun.nodes['#toast']));
const declined=runRealm({...freshOptions,confirm:false}),declinedRaw=activeRaw(declined),declinedWrites=writes(declined),declinedToast=clone(declined.nodes['#toast']),declinedResult=p7(declined,'push({present:true})');
check('push-declined-zero-write',declinedResult===false&&activeRaw(declined)===declinedRaw&&writes(declined)===declinedWrites&&noUiChange(declinedToast,declined.nodes['#toast']));
const disabled=runRealm({...freshOptions,features:{fellowExpedition:false}}),disabledRaw=activeRaw(disabled),disabledWrites=writes(disabled),disabledToast=clone(disabled.nodes['#toast']),disabledResult=p7(disabled,'push({confirmed:true,present:true})');
check('push-disabled-pure-noop',disabledResult===false&&activeRaw(disabled)===disabledRaw&&writes(disabled)===disabledWrites&&noUiChange(disabledToast,disabled.nodes['#toast']));

const idleRun=runRealm(freshOptions);p7(idleRun,'push({confirmed:true,present:false})');const idleBase=clone(active(idleRun)),idleRaw=activeRaw(idleRun),idleWrites=writes(idleRun);idleRun.clock.value+=3599999;const short=p7(idleRun,'claim({present:false})');
check('idle-minus-one-zero-write',short===false&&activeRaw(idleRun)===idleRaw&&writes(idleRun)===idleWrites);
idleRun.clock.value+=1;const onePreview=p7(idleRun,'idle()'),oneClaim=p7(idleRun,'claim({present:false})'),oneState=active(idleRun),oneReceipt=oneState.fellowExpedition.idle.lastReceipt;
check('idle-exact-hour',onePreview.intervals===1&&onePreview.intervalCountsByStage['3']===1&&oneClaim.ok===true);
check('idle-stage3-might',oneReceipt.mightNominal===2&&oneReceipt.mightAwarded===2&&oneState.fellowMight.points===2);
check('idle-no-gold-exp',oneState.gold===idleBase.gold&&Object.keys(oneState.fellows).every(id=>oneState.fellows[id].exp===idleBase.fellows[id].exp));
check('idle-receipt-preimage',oneReceipt.preClaimHighestStage===3&&oneReceipt.preClaimBestRunSequence===1&&oneReceipt.preClaimSegments[0].elapsedMs===3600000&&oneReceipt.preClaimClaimedIntervalsByStage['3']===0);
check('idle-receipt-identities',oneReceipt.pendingIdentity===p7(idleRun,'pendingIdentity('+JSON.stringify(oneState.saveMeta.saveId)+','+JSON.stringify(oneReceipt)+')')&&oneReceipt.receiptIdentity===p7(idleRun,'idleIdentity('+JSON.stringify(oneState.saveMeta.saveId)+','+JSON.stringify(oneReceipt)+')'));
check('idle-valid',valid(idleRun).ok,valid(idleRun).errors);
check('idle-positive-history-requires-claim-lineage',p7(idleRun,"tamper('idle-missing-claim')").ok===false);
check('idle-result-fields-bound-by-pending-identity',p7(idleRun,"tamper('idle-result')").ok===false);
const doubleRaw=activeRaw(idleRun),doubleWrites=writes(idleRun),doubleClaim=p7(idleRun,'claim({present:false})');
check('idle-double-claim-zero-write',doubleClaim===false&&activeRaw(idleRun)===doubleRaw&&writes(idleRun)===doubleWrites);
const idleReload=runRealm({initialSlots:Object.fromEntries(idleRun.slots),now:idleRun.clock.value});
check('idle-reload',internal(idleReload,'runtime().blocked')===null&&valid(idleReload).ok,valid(idleReload).errors);

idleRun.clock.value+=3600000;check('idle-second-claim',p7(idleRun,'claim({present:false})').ok===true);check('idle-claim-sequence-prefix',p7(idleRun,"tamper('claim-sequence-prefix')").ok===false);

const capRun=runRealm(freshOptions);p7(capRun,'push({confirmed:true,present:false})');capRun.clock.value+=25*3600000;const capPreview=p7(capRun,'idle()');
check('idle-24h-cap',capPreview.intervals===24&&capPreview.settlement.credited===24*3600000&&capPreview.settlement.discarded===3600000);

const chrono=runRealm(freshOptions);p7(chrono,'push({confirmed:true,present:false})');chrono.clock.value+=1800000;for(const id of ['cael','lyra','orin','selene','rook','mira'])p7(chrono,"grantExp('"+id+"',1000000)");const stronger=p7(chrono,'push({confirmed:true,present:false})');chrono.clock.value+=1800000;const chronoPreview=p7(chrono,'idle()');
check('chronology-new-record',stronger.ok===true&&active(chrono).fellowExpedition.highestStage>3);
check('chronology-first-ms-pricing',chronoPreview.intervals===1&&chronoPreview.intervalCountsByStage['3']===1&&Object.entries(chronoPreview.intervalCountsByStage).filter(([,value])=>value).length===1,chronoPreview.intervalCountsByStage);

const retainedPair=runRealm(freshOptions);p7(retainedPair,'push({confirmed:true,present:false})');retainedPair.clock.value+=3600000;p7(retainedPair,'claim({present:false})');for(const id of ['cael','lyra','orin','selene','rook','mira'])p7(retainedPair,"grantExp('"+id+"',1000000)");p7(retainedPair,'push({confirmed:true,present:false})');check('idle-retained-best-pair-natural',valid(retainedPair).ok,valid(retainedPair).errors);check('idle-retained-best-pair-tamper',p7(retainedPair,"tamper('idle-best-pair')").ok===false);

check('replay-ceiling-allows-last-entry',p7(fresh,'replayAllows(99999,1)')===true);
check('replay-ceiling-refuses-overflow',p7(fresh,'replayAllows(100000,1)')===false);
const campaignNearCapRaw=p7(fresh,'campaignUsageState(99999)'),campaignNearCap=runRealm({...freshOptions,activeRaw:campaignNearCapRaw});check('campaign-near-cap-valid',valid(campaignNearCap).ok,valid(campaignNearCap).errors);check('campaign-ceiling-one-remaining-ui',p7(campaignNearCap,'adventureView()').includes('99,999 used · 1 remaining · 100,000 ceiling'));const campaignLast=p7(campaignNearCap,"campaignRun('broken-roads-2',{confirmed:true,present:false})"),campaignAtCapRaw=activeRaw(campaignNearCap),campaignAtCapWrites=writes(campaignNearCap),campaignRefused=p7(campaignNearCap,"campaignRun('broken-roads-2',{confirmed:true,present:true})");check('campaign-ceiling-last-run-commits',campaignLast.ok===true&&p7(campaignNearCap,'replayUsage().campaignRuns')===100000);check('campaign-ceiling-next-refused',campaignRefused===false&&activeRaw(campaignNearCap)===campaignAtCapRaw&&writes(campaignNearCap)===campaignAtCapWrites&&campaignNearCap.nodes['#toast'].innerHTML.includes('safety ceiling reached'));
check('campaign-ceiling-zero-remaining-ui',p7(campaignNearCap,'adventureView()').includes('100,000 used · 0 remaining · 100,000 ceiling'));
const expeditionNearCapRaw=p7(fresh,'expeditionUsageState(99999)'),expeditionNearCap=runRealm({...freshOptions,activeRaw:expeditionNearCapRaw});check('expedition-near-cap-valid',valid(expeditionNearCap).ok,valid(expeditionNearCap).errors);check('expedition-ceiling-one-remaining-ui',p7(expeditionNearCap,'view()').includes('99,999 used · 1 remaining · 100,000 ceiling'));const expeditionLast=p7(expeditionNearCap,'claim({present:true})'),expeditionCapState=active(expeditionNearCap),expeditionSuccessCopy=expeditionNearCap.nodes['#toast'].innerHTML,expeditionAtCapRaw=activeRaw(expeditionNearCap),expeditionAtCapWrites=writes(expeditionNearCap);expeditionNearCap.clock.value+=3600000;const expeditionRefused=p7(expeditionNearCap,'claim({present:true})');check('expedition-ceiling-last-claim-commits',expeditionLast.ok===true&&p7(expeditionNearCap,'replayUsage().expeditionIntervals')===100000);check('expedition-cap-nominal-vs-actual-copy',expeditionCapState.fellowExpedition.idle.lastReceipt.mightNominal>0&&expeditionCapState.fellowExpedition.idle.lastReceipt.mightAwarded===0&&expeditionSuccessCopy.includes('nominal / +0 actual'));check('expedition-ceiling-next-refused',expeditionRefused===false&&activeRaw(expeditionNearCap)===expeditionAtCapRaw&&writes(expeditionNearCap)===expeditionAtCapWrites&&expeditionNearCap.nodes['#toast'].innerHTML.includes('safety ceiling reached'));
const expeditionCapHtml=p7(expeditionNearCap,'view()');check('expedition-ceiling-zero-remaining-ui',expeditionCapHtml.includes('100,000 used · 0 remaining · 100,000 ceiling'));check('expedition-ceiling-button-disabled',expeditionCapHtml.includes('data-expedition-claim disabled'));

const mightRun=runRealm(freshOptions),villageRateBefore=internal(mightRun,'diagnostics().totalVillageGoldPerHour'),powerBefore=p7(mightRun,"power('cael')").effectivePower; p7(mightRun,'push({confirmed:true,present:false})');mightRun.clock.value+=10*3600000;p7(mightRun,'claim({present:false})');const mightState=active(mightRun),powerAfter=p7(mightRun,"power('cael')").effectivePower,villageRateAfter=internal(mightRun,'diagnostics().totalVillageGoldPerHour');
check('might-level-one',mightState.fellowMight.points===20&&p7(mightRun,'might().level')===1&&p7(mightRun,'might().multiplier')===1.01);
check('might-power-once',powerAfter===Math.round(powerBefore*1.01));
check('might-village-neutral',villageRateAfter===villageRateBefore);

const campaign=runRealm(freshOptions),first=p7(campaign,"campaignRun('broken-roads-1',{confirmed:true,present:false})"),second=p7(campaign,"campaignRun('broken-roads-2',{confirmed:true,present:false})"),replay=p7(campaign,"campaignRun('broken-roads-1',{confirmed:true,present:false})"),campaignState=active(campaign);
check('campaign-v2-first',first.ok===true&&first.value.rewardIdentityVersion===2&&first.value.stageRunSequence===1);
check('campaign-v2-second',second.ok===true&&campaignState.player.rank>=2);
check('campaign-v2-replay',replay.ok===true&&campaignState.fellowCampaign.runCountsByStage['broken-roads-1']===2&&campaignState.fellowCampaign.lastReceipt.firstClear===false);
check('campaign-v2-source-ledger',valid(campaign).ok,valid(campaign).errors);
check('campaign-forged-reward-rejected',p7(campaign,"tamper('campaign-reward')").ok===false);
check('campaign-gap-rejected',p7(campaign,"tamper('campaign-gap')").ok===false);
check('best-forged-power-rejected',p7(idleRun,"tamper('best-power')").ok===false);
check('idle-forged-preimage-rejected',p7(idleRun,"tamper('idle-preimage')").ok===false);
for(const malformed of [null,{}, {schemaVersion:8}, {schemaVersion:8,saveMeta:null}, {schemaVersion:8,fellowCampaign:null}]){const literal=JSON.stringify(malformed),result=p7(fresh,'malformed('+literal+')');check('malformed-fail-closed-'+rows.length,!Object.hasOwn(result,'threw')&&result.ok===false,result)}

const metaLiteral="{createdAt:1787853600000,updatedAt:1787853600000,revision:1,saveId:'p7-schema7',source:'fresh',appliedMigrations:[]}",v7raw=JSON.stringify(p7(fresh,'schemaScoped('+metaLiteral+',7)')),migration=runRealm({...freshOptions,activeRaw:v7raw,now:1787853601000}),migrationState=active(migration),preV8Raw=migration.slots.get(keys.preV8);
check('schema7-migrates',migrationState.schemaVersion===8&&internal(migration,'runtime().blocked')===null);
check('schema7-preV8-byte-exact',preV8Raw===v7raw);
check('schema7-receipt-attests-preV8',migrationState.saveMeta.appliedMigrations.at(-1).checkpointLineage.preV8RawIdentity===rawIdentity(v7raw));
check('schema7-migration-valid',valid(migration).ok,valid(migration).errors);
const migrationReload=runRealm({initialSlots:Object.fromEntries(migration.slots),now:1787853602000});
check('schema7-migration-reload',internal(migrationReload,'runtime().blocked')===null&&valid(migrationReload).ok,valid(migrationReload).errors);
for(const [label,raw] of [['legacy',legacyRaw],['schema1',schemaOneRaw]]){const run=runRealm({...freshOptions,activeRaw:raw,now:1787853610000}),state=active(run);check(label+'-to-schema8',state?.schemaVersion===8&&internal(run,'runtime().blocked')===null,internal(run,'runtime()'));check(label+'-preV8-valid',run.slots.has(keys.preV8)&&JSON.parse(run.slots.get(keys.preV8)).schemaVersion===7);const reload=runRealm({initialSlots:Object.fromEntries(run.slots),now:1787853611000});check(label+'-reload',internal(reload,'runtime().blocked')===null&&valid(reload).ok,internal(reload,'runtime()'))}

const origins=internal(fresh,'buildOrigins('+JSON.stringify(schemaOneRaw)+')'),historicalSix=internal(fresh,'historical('+JSON.stringify(schemaOneRaw)+')'),schemaSixSlots={backupRaw:origins[5],preV5BackupRaw:origins[4],preV6BackupRaw:origins[5]};
const predecessorSlotName={2:'preV2BackupRaw',3:'preV3BackupRaw',4:'preV4BackupRaw',5:'preV5BackupRaw'};
for(const target of [2,3,4,5]){const activeValue=origins[target-1],targetValue=origins[target],stage=p7(fresh,'historicalTarget('+JSON.stringify(targetValue)+','+JSON.stringify(activeValue)+','+JSON.stringify('schema-'+(target-1)+'-migration')+')'),slotName=predecessorSlotName[target],protectedSlots={backupRaw:activeValue,[slotName]:activeValue};for(const [position,current] of [['pending',activeValue],['committed',targetValue]]){const run=runRealm({...freshOptions,...protectedSlots,activeRaw:current,stagingRaw:stage});check('historical-schema'+target+'-migration-'+position,active(run)?.schemaVersion===8&&valid(run).ok&&!run.slots.has(keys.staging),internal(run,'runtime().blocked')?.message??'')}}
for(const target of [2,3,4,5]){const fixture=p7(fresh,'historicalFresh('+target+')');for(const [position,current] of [['pending',null],['committed',fixture.stateRaw]]){const run=runRealm({...freshOptions,activeRaw:current,stagingRaw:fixture.stagingRaw});check('historical-schema'+target+'-fresh-'+position,active(run)?.schemaVersion===8&&valid(run).ok&&!run.slots.has(keys.staging),internal(run,'runtime().blocked')?.message??'')}}
for(const target of [2,3,4,5]){const activeValue=origins[target],slotName=predecessorSlotName[target],protectedSlots={backupRaw:origins[target-1],[slotName]:origins[target-1]},fixture=p7(fresh,'historicalCurrentFor('+JSON.stringify(activeValue)+')');for(const [position,current] of [['pending',activeValue],['committed',fixture.stateRaw]]){const run=runRealm({...freshOptions,...protectedSlots,activeRaw:current,stagingRaw:fixture.stagingRaw});check('historical-schema'+target+'-current-'+position,active(run)?.schemaVersion===8&&valid(run).ok&&!run.slots.has(keys.staging),internal(run,'runtime().blocked')?.message??'')}}
for(const target of [2,3,4,5]){const activeValue=origins[target],slotName=predecessorSlotName[target],slotRaws={backupRaw:origins[target-1],[slotName.replace('Backup','')]:origins[target-1]},protectedSlots={backupRaw:slotRaws.backupRaw,[slotName]:origins[target-1]},fixture=p7(fresh,'historicalSafeReset('+target+','+JSON.stringify(activeValue)+','+JSON.stringify(slotRaws)+')');for(const [position,current] of [['pending',activeValue],['committed',fixture.stateRaw]]){const run=runRealm({...freshOptions,...protectedSlots,activeRaw:current,stagingRaw:fixture.stagingRaw}),reload=runRealm({initialSlots:Object.fromEntries(run.slots),now:run.clock.value+1});check('historical-schema'+target+'-safe-reset-'+position,active(run)?.schemaVersion===8&&valid(run).ok&&!run.slots.has(keys.staging),internal(run,'runtime().blocked')?.message??'');check('historical-schema'+target+'-safe-reset-'+position+'-reload',active(reload)?.schemaVersion===8&&valid(reload).ok&&internal(reload,'runtime().blocked')===null,internal(reload,'runtime().blocked')?.message??'')}}
for(const [position,activeValue] of [['pending',historicalSix.v5raw],['committed',historicalSix.v6raw]]){const run=runRealm({...freshOptions,...schemaSixSlots,activeRaw:activeValue,stagingRaw:historicalSix.stagingRaw});check('historical-schema6-migration-'+position,active(run)?.schemaVersion===8&&valid(run).ok&&!run.slots.has(keys.staging),internal(run,'runtime().blocked')?.message??'')}
const historicalSixCurrent=internal(fresh,'historicalCurrent('+JSON.stringify(origins[6])+')');
for(const [position,activeValue] of [['pending',origins[6]],['committed',historicalSixCurrent.stateRaw]]){const run=runRealm({...freshOptions,...schemaSixSlots,activeRaw:activeValue,stagingRaw:historicalSixCurrent.stagingRaw});check('historical-schema6-current-'+position,active(run)?.schemaVersion===8&&valid(run).ok&&!run.slots.has(keys.staging),internal(run,'runtime().blocked')?.message??'')}
const sevenLineage={backupRaw:origins[5],preV2Raw:null,preV3Raw:null,preV4Raw:null,preV5Raw:origins[4],preV6Raw:origins[5],preV7Raw:origins[6]},historicalSeven=p7(fresh,'historicalSeven('+JSON.stringify(origins[6])+','+JSON.stringify(sevenLineage)+')'),schemaSevenSlots={backupRaw:origins[5],preV5BackupRaw:origins[4],preV6BackupRaw:origins[5],preV7BackupRaw:origins[6]};
for(const [position,activeValue] of [['pending',origins[6]],['committed',historicalSeven.stateRaw]]){const run=runRealm({...freshOptions,...schemaSevenSlots,activeRaw:activeValue,stagingRaw:historicalSeven.stagingRaw});check('historical-schema7-migration-'+position,active(run)?.schemaVersion===8&&valid(run).ok&&!run.slots.has(keys.staging),internal(run,'runtime().blocked')?.message??'')}
const historicalSevenFresh=p7(fresh,'historicalSevenFresh()');
for(const [position,activeValue] of [['pending',null],['committed',historicalSevenFresh.stateRaw]]){const run=runRealm({...freshOptions,activeRaw:activeValue,stagingRaw:historicalSevenFresh.stagingRaw});check('historical-schema7-fresh-'+position,active(run)?.schemaVersion===8&&valid(run).ok&&!run.slots.has(keys.staging),internal(run,'runtime().blocked')?.message??'')}
const historicalSevenReset=p7(fresh,'historicalSafeReset(7,'+JSON.stringify(historicalSevenFresh.stateRaw)+','+JSON.stringify({backupRaw:historicalSevenFresh.stateRaw})+')');
for(const [position,activeValue] of [['pending',historicalSevenFresh.stateRaw],['committed',historicalSevenReset.stateRaw]]){const run=runRealm({...freshOptions,activeRaw:activeValue,backupRaw:historicalSevenFresh.stateRaw,stagingRaw:historicalSevenReset.stagingRaw}),reload=runRealm({initialSlots:Object.fromEntries(run.slots),now:run.clock.value+1});check('historical-schema7-safe-reset-'+position,active(run)?.schemaVersion===8&&valid(run).ok&&!run.slots.has(keys.staging),internal(run,'runtime().blocked')?.message??'');check('historical-schema7-safe-reset-'+position+'-reload',active(reload)?.schemaVersion===8&&valid(reload).ok&&internal(reload,'runtime().blocked')===null,internal(reload,'runtime().blocked')?.message??'')}
const directSevenInterrupted=runRealm({...freshOptions,activeRaw:historicalSevenFresh.stateRaw,fault:{enabled:true,operation:'setItem',step:'active-write'}}),directSevenSlots=Object.fromEntries(directSevenInterrupted.slots),directSevenStage=directSevenSlots[keys.staging],directSevenTarget=JSON.stringify(JSON.parse(directSevenStage).state);
for(const [position,mutateSlots] of [['pending',slots=>slots],['committed',slots=>({...slots,[keys.active]:directSevenTarget})],['missing-active',slots=>{const next={...slots};delete next[keys.active];return next}]]){const run=runRealm({initialSlots:mutateSlots({...directSevenSlots})}),reload=runRealm({initialSlots:Object.fromEntries(run.slots),now:run.clock.value+1});check('fresh-schema7-to8-'+position,active(run)?.schemaVersion===8&&valid(run).ok&&!run.slots.has(keys.staging),internal(run,'runtime().blocked')?.message??'');check('fresh-schema7-to8-'+position+'-reload',active(reload)?.schemaVersion===8&&valid(reload).ok&&internal(reload,'runtime().blocked')===null,internal(reload,'runtime().blocked')?.message??'')}

const releasedPhaseSixFresh=runRealm({...freshOptions,applicationSource:releasedPhaseSixApplicationSource,now:1787853620000}),releasedPhaseSixBootRaw=activeRaw(releasedPhaseSixFresh),releasedPhaseSixBoot=JSON.parse(releasedPhaseSixBootRaw);
check('released-phase6-fresh-boots-to-schema7-revision2',releasedPhaseSixFresh.thrown===null&&releasedPhaseSixBoot.schemaVersion===7&&releasedPhaseSixBoot.saveMeta.source==='boot'&&releasedPhaseSixBoot.saveMeta.revision===2&&releasedPhaseSixBoot.saveMeta.createdAt===releasedPhaseSixBoot.saveMeta.updatedAt&&releasedPhaseSixBoot.saveMeta.appliedMigrations.length===0,releasedPhaseSixFresh.thrown?.stack??JSON.stringify(releasedPhaseSixBoot.saveMeta));
const releasedBootInterrupted=runRealm({...freshOptions,activeRaw:releasedPhaseSixBootRaw,now:1787853621000,fault:{enabled:true,operation:'setItem',step:'active-write'}}),releasedBootSlots=Object.fromEntries(releasedBootInterrupted.slots),releasedBootStage=releasedBootSlots[keys.staging],releasedBootTarget=JSON.stringify(JSON.parse(releasedBootStage).state);
check('released-phase6-boot-interruption-exact-checkpoints',releasedBootSlots[keys.active]===releasedPhaseSixBootRaw&&releasedBootSlots[keys.backup]===releasedPhaseSixBootRaw&&releasedBootSlots[keys.preV8]===releasedPhaseSixBootRaw&&typeof releasedBootStage==='string');
for(const [position,mutateSlots] of [['pending',slots=>slots],['committed',slots=>({...slots,[keys.active]:releasedBootTarget})],['missing-active',slots=>{const next={...slots};delete next[keys.active];return next}]]){const run=runRealm({initialSlots:mutateSlots({...releasedBootSlots}),now:1787853622000}),reload=runRealm({initialSlots:Object.fromEntries(run.slots),now:1787853623000});check('released-phase6-boot-to8-'+position,active(run)?.schemaVersion===8&&valid(run).ok&&!run.slots.has(keys.staging),internal(run,'runtime().blocked')?.message??'');check('released-phase6-boot-to8-'+position+'-reload',active(reload)?.schemaVersion===8&&valid(reload).ok&&internal(reload,'runtime().blocked')===null,internal(reload,'runtime().blocked')?.message??'')}
for(const [label,mutate] of [['gold',state=>state.gold++],['revision',state=>state.saveMeta.revision++],['source',state=>state.saveMeta.source='navigation']]){const tampered=clone(releasedPhaseSixBoot);mutate(tampered);const raw=JSON.stringify(tampered),interrupted=runRealm({...freshOptions,activeRaw:raw,now:1787853621000,fault:{enabled:true,operation:'setItem',step:'active-write'}}),slots=Object.fromEntries(interrupted.slots);delete slots[keys.active];const run=runRealm({initialSlots:slots,now:1787853622000});check('released-phase6-boot-near-miss-'+label+'-blocked',internal(run,'runtime().blocked')!==null,internal(run,'runtime().blocked')?.message??'');check('released-phase6-boot-near-miss-'+label+'-zero-write',writes(run)===0&&activeRaw(run)===null&&run.slots.get(keys.backup)===raw&&run.slots.get(keys.preV8)===raw&&run.slots.get(keys.staging)===slots[keys.staging])}

const checkpointConflictSlots=Object.fromEntries(migration.slots);delete checkpointConflictSlots[keys.active];delete checkpointConflictSlots[keys.staging];const freshEightStage=p7(fresh,'freshEightStage()');
for(const [position,activeValue] of [['pending',null],['committed',freshEightStage.stateRaw]]){const initialSlots={...checkpointConflictSlots,[keys.staging]:freshEightStage.stagingRaw};if(activeValue!==null)initialSlots[keys.active]=activeValue;const run=runRealm({initialSlots}),beforeExpected=activeValue;check('fresh-schema8-vs-checkpoints-'+position+'-blocked',internal(run,'runtime().blocked')!==null);check('fresh-schema8-vs-checkpoints-'+position+'-zero-write',writes(run)===0&&(run.slots.get(keys.active)??null)===beforeExpected&&run.slots.get(keys.staging)===freshEightStage.stagingRaw)}

const resetReadFault=runRealm({...freshOptions,activeRaw:activeRaw(fresh),preV8BackupRaw:'foreign-checkpoint'}),resetBefore=slotSnapshot(resetReadFault),resetWrites=writes(resetReadFault);Object.assign(resetReadFault.fault,{enabled:true,operation:'getItem',key:keys.preV8,step:null,remaining:1,skip:0});internal(resetReadFault,'reset()');check('safe-reset-pre-v8-read-fault-blocked',internal(resetReadFault,'runtime().blocked')!==null);check('safe-reset-pre-v8-read-fault-zero-write',writes(resetReadFault)===resetWrites&&JSON.stringify(slotSnapshot(resetReadFault))===JSON.stringify(resetBefore));
const normalReset=runRealm(freshOptions);internal(normalReset,'reset()');const normalResetState=active(normalReset),normalResetRuntime=internal(normalReset,'runtime()'),normalResetReload=runRealm({initialSlots:Object.fromEntries(normalReset.slots),now:normalReset.clock.value+1});check('safe-reset-normal-current-commits',normalResetState?.schemaVersion===8&&normalResetState.saveMeta.source==='safe-reset'&&typeof normalReset.slots.get(keys.backup)==='string'&&normalResetRuntime.blocked===null,JSON.stringify({blocked:normalResetRuntime.blocked,stateSource:normalResetState?.saveMeta?.source,backupPresent:typeof normalReset.slots.get(keys.backup)==='string'}));check('safe-reset-normal-current-reloads',valid(normalResetReload).ok&&internal(normalResetReload,'runtime().blocked')===null,internal(normalResetReload,'runtime().blocked')?.message??'');
for(const [slotName,slotKey] of Object.entries(keys)){const run=runRealm(freshOptions),before=slotSnapshot(run),beforeWrites=writes(run);Object.assign(run.fault,{enabled:true,operation:'getItem',key:slotKey,step:null,remaining:1,skip:slotName==='active'?1:0,adapterOnly:true});internal(run,'reset()');check('safe-reset-ten-slot-read-'+slotName+'-blocked',internal(run,'runtime().blocked')?.kind==='safe-reset-lineage-read',internal(run,'runtime().blocked')?.kind??'');check('safe-reset-ten-slot-read-'+slotName+'-zero-write',writes(run)===beforeWrites&&JSON.stringify(slotSnapshot(run))===JSON.stringify(before))}
const fixtureFaultRun=runRealm(freshOptions),fixtureBeforeSlots=slotSnapshot(fixtureFaultRun),fixtureBeforeRuntime=JSON.stringify(p7(fixtureFaultRun,'runtimeCapture()')),fixtureTarget=p7(fixtureFaultRun,'historicalCurrentFor('+JSON.stringify(activeRaw(fixtureFaultRun))+').stateRaw'),fixturePayload={activeRaw:fixtureTarget,backupRaw:fixtureBeforeSlots[keys.backup],stagingRaw:fixtureBeforeSlots[keys.staging]};for(const [slotName,slotKey] of Object.entries(keys)){Object.assign(fixtureFaultRun.fault,{enabled:true,operation:'getItem',key:slotKey,step:null,remaining:1,skip:1,adapterOnly:true});const result=p7(fixtureFaultRun,'fixtureProbe('+JSON.stringify(fixturePayload)+')');check('fixture-post-write-read-'+slotName+'-refused',result.ok===false&&result.error.includes('Fixture boot failed'),result.error);check('fixture-post-write-read-'+slotName+'-exact-rollback',JSON.stringify(slotSnapshot(fixtureFaultRun))===JSON.stringify(fixtureBeforeSlots)&&JSON.stringify(p7(fixtureFaultRun,'runtimeCapture()'))===fixtureBeforeRuntime)}

const foreign=runRealm({...freshOptions,activeRaw:v7raw,preV8BackupRaw:v7raw+' ',now:1787853601000}),foreignSnapshot=slotSnapshot(foreign);
check('foreign-preV8-blocked',internal(foreign,'runtime().blocked')!==null&&activeRaw(foreign)===v7raw);
check('foreign-preV8-retained',foreign.slots.get(keys.preV8)===v7raw+' ');
const missing=runRealm({...freshOptions,activeRaw:null,preV8BackupRaw:v7raw,now:1787853601000});
check('missing-lone-evolved-preV8-fail-closed',internal(missing,'runtime().blocked')!==null&&activeRaw(missing)===null&&missing.slots.get(keys.preV8)===v7raw);

const disabledClaim=runRealm({...freshOptions,features:{fellowExpedition:false}}),disabledClaimRaw=activeRaw(disabledClaim),disabledClaimWrites=writes(disabledClaim),disabledClaimToast=clone(disabledClaim.nodes['#toast']),disabledClaimResult=p7(disabledClaim,'claim({present:true})');
check('claim-disabled-pure-noop',disabledClaimResult===false&&activeRaw(disabledClaim)===disabledClaimRaw&&writes(disabledClaim)===disabledClaimWrites&&noUiChange(disabledClaimToast,disabledClaim.nodes['#toast']));
const bridge=runRealm(freshOptions),route=internal(bridge,"action('adventure',{tab:'fellowExpedition'})"),bridgePush=internal(bridge,"action('fellow-expedition-push',{})"),diagnostics=internal(bridge,'diagnostics()');
check('qa-route',route.ok===true&&active(bridge).ui.adventure==='fellowExpedition');
check('qa-push',bridgePush.ok===true&&active(bridge).fellowExpedition.highestStage===3);
check('diagnostics-preV8',diagnostics.preV8Backup.key===keys.preV8);
check('diagnostics-expedition',diagnostics.fellowExpedition.bestPreview.mode==='fellowExpedition'&&diagnostics.fellowMight.components.multiplier===1);
check('diagnostics-replay-and-reconciliation',diagnostics.replaySafety.ceiling===100000&&diagnostics.fellowCampaignV2.rewardReplay.totalRuns===0&&diagnostics.fellowCampaignV2.sourceLedgerReconciliation.ok===true);
const storageEventRun=runRealm(freshOptions),storageEventBefore=internal(storageEventRun,'runtime().stale');for(const listener of storageEventRun.listeners.storage??[])listener({storageArea:storageEventRun.context.localStorage,key:keys.preV8});check('preV8-storage-event-marks-stale',storageEventBefore===false&&internal(storageEventRun,'runtime().stale')===true);
const adventureHtml=p7(bridge,'adventureView()'),rosterHtml=p7(bridge,'rosterView()'),expeditionHtml=p7(bridge,'view()');
check('ui-four-tabs',['Fellows','Expedition','Companions','Tower'].every(label=>adventureHtml.includes(label)));
check('ui-expedition-detail',expeditionHtml.includes('weakest unexhausted Fellow')&&expeditionHtml.includes('Current hourly'.replace('Current hourly','Idle claim'))&&expeditionHtml.includes('Durable Expedition history'));
check('ui-might-nominal-and-actual',expeditionHtml.includes('actual</b>')&&expeditionHtml.includes('nominal · 50000 cap'));
check('ui-might-roster',rosterHtml.includes('data-fellow-might-summary')&&rosterHtml.includes('Never spent'));
check('ui-no-gold-output',!expeditionHtml.includes('Gold reward')&&!expeditionHtml.includes('EXP each'));

const baseAssetLines=[12,18,24].map(line=>html.split(/\n/)[line-1]);
check('embedded-assets-present',baseAssetLines.every(line=>line.includes('data:image/')));
check('no-active-legacy-modes',!source.includes("story:true")&&!source.includes("tower:true")&&!source.includes("trading:true")&&!source.includes("patrol:true")&&!source.includes("operations:true"));

const passed=rows.filter(row=>row.pass).length,failed=rows.length-passed;
console.log(JSON.stringify({total:rows.length,passed,failed,artifactSha256:sha256(htmlBytes),artifactBytes:htmlBytes.length,failures:rows.filter(row=>!row.pass)},null,2));
if(failed)process.exitCode=1;
`;

eval(harness+suite);
