(() => {
  'use strict';
  const CHANNEL='everstead-phase-11c',json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config){
    const slots=new Map(),writes=[],errors=[],nativeStorageAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);let saveIndex=0,transactionIndex=0,nativeStorageInstrumented=false;
    window.matchMedia=query=>({matches:config.reducedMotion&&query==='(prefers-reduced-motion: reduce)',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>{key=String(key);writes.push({op:'set',key});slots.set(key,String(value))},removeItem:key=>{key=String(key);writes.push({op:'remove',key});slots.delete(key)}};
    Object.assign(window,{__PHASE_11C_CONFIG__:config,__PHASE_11C_SLOTS__:slots,__PHASE_11C_WRITES__:writes,__PHASE_11C_ERRORS__:errors,__PHASE_11C_NATIVE_STORAGE_ACCESSES__:nativeStorageAccesses,__PHASE_11C_NATIVE_STORAGE_INSTRUMENTED__:nativeStorageInstrumented});
    window.__EVERSTEAD_RUNTIME__={storage:memoryStorage,clock:{now:()=>config.now,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.5,confirm:()=>true,ids:{save:()=>`save-p11c-${++saveIndex}`,transaction:()=>`tx-p11c-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
  }

  function runSuite(){
    const config=window.__PHASE_11C_CONFIG__,writes=window.__PHASE_11C_WRITES__,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),until=async(predicate,limit=5000)=>{const started=performance.now();while(performance.now()-started<limit){if(predicate())return true;await wait(25)}return false},add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)}),qa=()=>window.__EVERSTEAD_QA__,live=()=>window.__EVERSTEAD_11C_LIVE__,state=()=>qa().snapshot().state,text=node=>node?.textContent.replace(/\s+/g,' ').trim()||'',inside=node=>{const rect=node?.getBoundingClientRect();return Boolean(rect)&&rect.left>=-1&&rect.right<=innerWidth+1&&rect.width>0},close=async()=>{document.querySelector('[data-modal-close]')?.click();await wait(40)},send=()=>parent.postMessage({channel:config.channel,nonce:config.nonce,results,errors:window.__PHASE_11C_ERRORS__.slice()},'*');
    const grant=(resource,amount,id)=>{const result=qa().controls.grant({resource,amount,...(id?{id}:{})});if(!result.ok)throw new Error(`Grant failed: ${resource}`);return result},act=(name,value={})=>{const result=qa().act(name,value);if(!result.ok)throw new Error(`${name} failed: ${result.error||'refused'}`);return result};
    (async()=>{
      await wait(650);add('bridge-present',Boolean(qa()&&live()));add('viewport-exact',innerWidth===config.viewport.width&&innerHeight===config.viewport.height,`${innerWidth}x${innerHeight}`);add('motion-realm',live().reducedMotion()===config.reducedMotion);if(document.querySelector('.modal'))await close();act('navigate',{view:'adventure'});await wait(40);const lockedCard=document.querySelector('[data-phase-11c-claim-card]'),towerLocked=document.querySelector('[data-adventure="companionTower"]'),expeditionLocked=document.querySelector('[data-adventure="fellowExpedition"]'),lockedDetail=JSON.stringify({card:text(lockedCard),towerAriaDisabled:towerLocked?.getAttribute('aria-disabled'),tower:text(towerLocked),expeditionAriaDisabled:expeditionLocked?.getAttribute('aria-disabled'),expedition:text(expeditionLocked)});add('locked-controls-visible',text(lockedCard).includes('Unlocks at Rank 3')&&text(lockedCard).includes('Unlocks at Rank 4')&&towerLocked?.getAttribute('aria-disabled')==='true'&&towerLocked?.getAttribute('data-rank-required')==='3'&&expeditionLocked?.getAttribute('aria-disabled')==='true'&&expeditionLocked?.getAttribute('data-rank-required')==='4',lockedDetail);
      grant('gold',5_000_000);for(const stage of [1,2])act('campaign-run',{id:`broken-roads-${stage}`});act('campaign-select',{id:'broken-roads-1'});await wait(80);
      let panel=document.querySelector('[data-phase-11c-repeat-panel="fellowCampaign"]'),open=document.querySelector('[data-phase-11c-repeat-open]');add('fellow-repeat-panel-visible',Boolean(panel&&open&&!open.disabled)&&text(panel).includes('30,000 Gold reserve'));add('fellow-repeat-panel-layout',inside(panel)&&inside(open)&&document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);add('repeat-primary-touch-target',open.getBoundingClientRect().height>=44,open.getBoundingClientRect().height);
      const fellowBefore=state(),onclickBound=typeof open.onclick==='function',openDataset=Object.fromEntries(Object.entries(open.dataset));open.focus();open.click();await wait(40);let modal=document.querySelector('.modal'),counts=[...document.querySelectorAll('[data-phase-11c-repeat-count]')].map(button=>Number(button.getAttribute('data-phase-11c-repeat-count'))),chooserDetail=JSON.stringify({counts,onclickBound,openDataset,overlay:text(document.querySelector('#overlay')),preview:live().repeatPreview('fellowCampaign','broken-roads-1')});add('repeat-chooser-options',JSON.stringify(counts)===JSON.stringify([1,3,5])&&inside(modal),chooserDetail);modal.focus();document.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',bubbles:true}));const firstFocus=document.activeElement;document.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true}));const lastFocus=document.activeElement;add('repeat-focus-trap-and-inert',modal.contains(firstFocus)&&modal.contains(lastFocus)&&firstFocus!==lastFocus&&document.querySelector('#app').inert===true);document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(40);add('setup-escape-closes-and-returns',!document.querySelector('.modal')&&document.activeElement?.matches('[data-phase-11c-repeat-open]'));open=document.querySelector('[data-phase-11c-repeat-open]');open.click();await wait(30);const three=document.querySelector('[data-phase-11c-repeat-count="3"]');if(!three)throw new Error(`Repeat chooser missing: ${chooserDetail}`);three.click();await wait(100);const progress=document.querySelector('[role="progressbar"]');add('repeat-progress-semantics',progress?.getAttribute('aria-valuemax')==='3'&&progress?.getAttribute('aria-valuenow')==='0'&&document.querySelector('[data-phase-11c-progress-status][role="status"]'));await until(()=>document.querySelector('[data-phase-11c-repeat-summary]'),4000);modal=document.querySelector('.modal');const fellowAfter=state();add('fellow-repeat-three-saved',fellowAfter.fellowCampaign.runOrdinal===fellowBefore.fellowCampaign.runOrdinal+3&&fellowAfter.saveMeta.revision===fellowBefore.saveMeta.revision+3);add('fellow-repeat-summary',text(modal).includes('3 / 3')&&text(modal).includes('Requested runs completed')&&text(modal).includes('Gold spent'));add('repeat-summary-layout',inside(modal)&&document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);await close();add('repeat-return-focus',document.activeElement?.matches('[data-phase-11c-repeat-open]'));

      act('adventure',{tab:'companionCampaign'});act('companion-campaign-run',{id:'companion-trail-1'});act('companion-campaign-select',{id:'companion-trail-1'});await wait(60);panel=document.querySelector('[data-phase-11c-repeat-panel="companionCampaign"]');open=document.querySelector('[data-phase-11c-repeat-open]');add('companion-repeat-panel-visible',Boolean(panel&&open&&!open.disabled));const companionBefore=state();open.click();await wait(30);document.querySelector('[data-phase-11c-repeat-count="1"]').click();await until(()=>document.querySelector('[data-phase-11c-repeat-summary]'),2500);const companionAfter=state();add('companion-repeat-one-saved',companionAfter.companionCampaign.runOrdinal===companionBefore.companionCampaign.runOrdinal+1&&companionAfter.saveMeta.revision===companionBefore.saveMeta.revision+1);add('companion-repeat-summary',text(document.querySelector('.modal')).includes('1 / 1'));await close();

      act('adventure',{tab:'fellowCampaign'});act('campaign-select',{id:'broken-roads-1'});await wait(40);document.querySelector('[data-phase-11c-repeat-open]').click();await wait(20);document.querySelector('[data-phase-11c-repeat-count="5"]').click();await until(()=>live().job()?.completed>=1,2500);document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(80);add('escape-stops-after-completed-run',text(document.querySelector('.modal')).includes('1 / 5')&&text(document.querySelector('.modal')).includes('Stopped by player'));await close();document.querySelector('[data-phase-11c-repeat-open]').click();await wait(20);document.querySelector('[data-phase-11c-repeat-count="5"]').click();await until(()=>live().job()?.completed>=1,2500);document.querySelector('[data-overlay]').click();await wait(80);add('backdrop-stops-after-completed-run',text(document.querySelector('.modal')).includes('1 / 5')&&text(document.querySelector('.modal')).includes('Stopped by player'));await close();

      for(const id of ['cael','lyra','orin','selene','rook','mira'])grant('fellowExp',1_000_000,id);for(const stage of [3,4,5,6])act('campaign-run',{id:`broken-roads-${stage}`});act('companion-tower-clear');act('fellow-expedition-push');qa().clock.freeze(config.now);qa().clock.advance(2*3600000);live().render();await wait(80);
      const card=document.querySelector('[data-phase-11c-claim-card]'),claim=document.querySelector('[data-phase-11c-claim-ready]'),navBadge=document.querySelector('.phase-11c-nav-badge');add('claim-card-three-ready',Boolean(card&&claim&&!claim.disabled)&&text(claim).includes('3 READY LANES')&&text(card).includes('Village')&&text(card).includes('Tower')&&text(card).includes('Expedition'));add('idle-nav-badge-two',text(navBadge)==='2'&&navBadge.getAttribute('aria-label')?.includes('2 idle reward lanes'));add('claim-card-layout',inside(card)&&inside(claim)&&document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);add('claim-primary-touch-target',claim.getBoundingClientRect().height>=44,claim.getBoundingClientRect().height);
      const claimBefore=state();claim.focus();claim.click();await wait(120);modal=document.querySelector('.modal');const claimAfter=state();add('claim-ready-three-independent-saves',claimAfter.saveMeta.revision===claimBefore.saveMeta.revision+3&&claimAfter.familyDrops.claimSequence===claimBefore.familyDrops.claimSequence+1&&claimAfter.companionTower.idle.claimOrdinal===claimBefore.companionTower.idle.claimOrdinal+1&&claimAfter.fellowExpedition.idle.claimOrdinal===claimBefore.fellowExpedition.idle.claimOrdinal+1);add('claim-summary-all-lanes',text(modal).includes('Village claimed')&&text(modal).includes('Tower claimed')&&text(modal).includes('Expedition claimed')&&text(modal).includes('3 lanes claimed'));add('claim-summary-layout',inside(modal)&&document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);await close();add('claim-return-focus',document.activeElement?.matches('[data-phase-11c-claim-heading]'));add('claim-consumed-once',document.querySelector('[data-phase-11c-claim-ready]')?.disabled===true&&!document.querySelector('.phase-11c-nav-badge'));

      add('final-state-valid',live().valid().ok===true,(live().valid().errors||[]).join(','));add('final-no-horizontal-overflow',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);add('native-storage-instrumented',window.__PHASE_11C_NATIVE_STORAGE_INSTRUMENTED__===true);add('zero-native-storage-accesses',window.__PHASE_11C_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_11C_NATIVE_STORAGE_ACCESSES__.join(','));add('zero-warning-error-console',window.__PHASE_11C_ERRORS__.length===0,window.__PHASE_11C_ERRORS__.join('\n'));add('bounded-write-volume',writes.length>0&&writes.length<500,writes.length);send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();const firstScript=source.indexOf('<script>'),anchor='const report=load();render();installQaBridge();if(PHASE_ELEVEN_B_TWO_BOOT_OUTCOME)runtimeSetTimeout(phaseElevenBTwoShowBootOutcome,250);else if(report)runtimeSetTimeout(()=>openOffline(report),250);';if(firstScript<0||source.split(anchor).length!==2)throw new Error('Production instrumentation anchor drift');const facade=`window.__EVERSTEAD_11C_LIVE__=Object.freeze({state:()=>clone(S),valid:()=>clone(validation(S,11)),render:()=>render(),reducedMotion:()=>runtimePrefersReducedMotion(),repeatPreview:(mode,id)=>clone(phaseElevenCRepeatPreview(mode,id,S)),openRepeat:(mode,id)=>phaseElevenCOpenRepeat(mode,id),job:()=>PHASE_ELEVEN_C_JOB?clone(PHASE_ELEVEN_C_JOB):null});`;source=source.replace(anchor,facade+anchor);const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`,instrumented=source.slice(0,firstScript)+bootstrap+source.slice(firstScript).replace('</body>',suite+'</body>');document.open();document.write(instrumented);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
