(() => {
  'use strict';
  const CHANNEL='everstead-phase-11c',byId=id=>document.getElementById(id),escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),row=(id,actual,detail='')=>({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)});
  async function text(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.text()}
  async function contract(){const [scenarioRaw,source]=await Promise.all([text('./scenarios.json'),text('../../index.html')]),scenarios=JSON.parse(scenarioRaw),rows=[],start=source.indexOf('/* Phase 11C ·'),end=source.lastIndexOf('const report=load();render();'),phase=start>=0&&end>start?source.slice(start,end):'';rows.push(row('schema-11-static',source.includes('CURRENT_SCHEMA_VERSION=11')));rows.push(row('phase-11c-static',phase.includes('Phase 11C · bounded Campaign repeat')&&phase.includes('PHASE_ELEVEN_C_REPEAT_COUNTS=Object.freeze([1,3,5])')));rows.push(row('fixed-stage-static',phase.includes('Repeat this stage'.toUpperCase())&&phase.includes('firstClear!==false')));rows.push(row('reserve-static',phase.includes('PHASE_ELEVEN_C_GOLD_RESERVE=30000')));rows.push(row('claim-order-static',phase.includes("order=['village','tower','expedition']")));rows.push(row('no-background-claim-static',(phase.match(/phaseElevenCClaimReady\(/g)||[]).length===2&&phase.includes("button.onclick=()=>phaseElevenCClaimReady(button)")&&!/runtimeSetTimeout\([^;]*phaseElevenCClaimReady|addEventListener\([^;]*phaseElevenCClaimReady|bootstrapPersistence[^;]*phaseElevenCClaimReady/.test(phase)));rows.push(row('six-live-realms',scenarios.viewports.length===6&&scenarios.viewports.filter(item=>item.reducedMotion).length===3));return{scenarios,rows}}
  function realm(contract,viewport){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),config={channel:CHANNEL,nonce,viewport,now:Date.parse(contract.scenarios.frozenNow),reducedMotion:viewport.reducedMotion};frame.name=JSON.stringify(config);frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0`;let timer;const done=(error,value)=>{clearTimeout(timer);removeEventListener('message',message);frame.remove();error?reject(error):resolve(value)},message=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=event.data.results.map(item=>({...item,id:`${viewport.id}-${item.id}`}));if(event.data.errors?.length&&!rows.some(item=>item.id.endsWith('zero-warning-error-console')&&!item.pass))rows.push(row(`${viewport.id}-captured-errors`,false,event.data.errors.join('\n')));done(null,rows)};timer=setTimeout(()=>done(new Error(`${viewport.id} timed out`)),180000);addEventListener('message',message);frame.src=`./realm.html?qa=1&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  function render(mode,rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('mode').textContent=mode;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)} · observed ${item.actual?'true':'false'} · expected true${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_11C_RESULT__={mode,passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const data=await contract(),rows=[...data.rows];for(const viewport of data.scenarios.viewports)rows.push(...await realm(data,viewport));render('CANDIDATE',rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render('FATAL',[row('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
