import {createHash} from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
import {existsSync,readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';

const ROOT=resolve(new URL('../..',import.meta.url).pathname),QA=resolve(ROOT,'qa/phase-11d'),NODE=process.execPath;
const EXPECTED=['README.md','build-contract.mjs','checksums.sha256','current-manifest.json','index.html','probe.mjs','realm.html','realm.js','runner.js','scenarios.json','verify.mjs'];
const SOURCE=EXPECTED.filter(name=>!['checksums.sha256','current-manifest.json'].includes(name)).map(name=>`qa/phase-11d/${name}`);
const results=[],record=(id,pass,detail='')=>results.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),sha=value=>createHash('sha256').update(value).digest('hex'),read=path=>readFileSync(resolve(ROOT,path)),identity=raw=>({sha256:sha(raw),byteLength:raw.length}),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),git=args=>execFileSync('git',args,{cwd:ROOT,encoding:'utf8',maxBuffer:64*1024*1024});
const scenarios=JSON.parse(read('qa/phase-11d/scenarios.json')),artifact=identity(read('index.html')),source=read('index.html').toString('utf8'),expectedArtifact={sha256:scenarios.artifact.sha256,byteLength:scenarios.artifact.byteLength};
record('base-commit-reachable',git(['merge-base','--is-ancestor',scenarios.authority.baseCommit,'HEAD'])==='');
record('contract-commit-reachable',git(['merge-base','--is-ancestor',scenarios.authority.contractCommit,'HEAD'])==='');
record('production-commit-reachable',git(['merge-base','--is-ancestor',scenarios.authority.productionCommit,'HEAD'])==='');
record('production-last-index-change',git(['log','-1','--format=%H','--','index.html']).trim()===scenarios.authority.productionCommit);
record('exact-production-artifact',same(artifact,expectedArtifact),artifact);
const assets=[...source.matchAll(/data:image\/[^;]+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]),assetSha=sha(Buffer.from(assets.join('\n')));record('embedded-assets-byte-frozen',assets.length===scenarios.artifact.assetCount&&assetSha===scenarios.artifact.assetAggregateSha256,`${assets.length} · ${assetSha}`);
record('schema-unchanged',source.includes('CURRENT_SCHEMA_VERSION=11')&&!source.slice(source.indexOf('/* Phase 11D ·'),source.lastIndexOf('const report=load();render();')).includes('CURRENT_SCHEMA_VERSION='));
record('phase11d-contract-static',source.includes('PHASE_ELEVEN_D_ROSTER_UI')&&source.includes('phaseElevenDFamilyAssignmentPreview')&&source.includes('phaseElevenDCodexSnapshot')&&source.includes('Prosperity is not spendable and currently changes neither Gold nor Power')&&!source.includes('.dataset.phase11d'));
record('six-browser-realms',scenarios.viewports.length===6&&scenarios.viewports.filter(item=>item.reducedMotion).length===3&&new Set(scenarios.viewports.map(item=>`${item.width}x${item.height}`)).size===3);
record('package-topology',same(readdirSync(QA).sort(),EXPECTED),readdirSync(QA).sort());
const changed=git(['diff','--name-only',scenarios.authority.productionCommit,'--']).trim().split('\n').filter(Boolean),owned=path=>path.startsWith('qa/phase-11d/')||['README.md','docs/PHASE_11D_ROSTER_CODEX_RESULT.md'].includes(path);record('post-production-owned-paths-only',changed.length>0&&changed.every(owned),changed);
function focused(path,label,total){const run=spawnSync(NODE,[path],{cwd:ROOT,encoding:'utf8',maxBuffer:192*1024*1024}),pattern=new RegExp(`${label}: ${total}\\/${total}`);return{pass:run.status===0&&pattern.test(run.stdout),status:run.status,tail:run.stdout.trim().split('\n').slice(-1)[0],stderr:run.stderr.trim().slice(-500)}}
const p11d=focused('qa/phase-11d/probe.mjs','Phase 11D focused probe',103),p11c=focused('qa/phase-11c/probe.mjs','Phase 11C focused probe',83),inspect=focused('qa/phase-11b2a/probe.mjs','Phase 11B-2a probe',42),idle=focused('qa/phase-11b2a/idle-probe.mjs','Phase 11B idle prerequisite probe',8),engine=focused('qa/phase-11b2b/engine-probe.mjs','Phase 11B-2b engine probe',103),recovery=focused('qa/phase-11b2c/final-probe.mjs','Phase 11B-2c final recovery probe',133);
record('focused-phase11d-103-of-103',p11d.pass,p11d);record('inherited-phase11c-83-of-83',p11c.pass,p11c);record('inherited-phase11b-286-of-286',[inspect,idle,engine,recovery].every(item=>item.pass),{inspect,idle,engine,recovery});
for(const file of ['build-contract.mjs','probe.mjs','realm.js','runner.js','verify.mjs']){const run=spawnSync(NODE,['--check',`qa/phase-11d/${file}`],{cwd:ROOT,encoding:'utf8'});record(`syntax-${file}`,run.status===0,run.stderr.trim())}
const p11cFrozen=['docs/PHASE_11C_AUTOMATION_CONTRACT.md','docs/PHASE_11C_AUTOMATION_RESULT.md','qa/phase-11c/README.md','qa/phase-11c/build-contract.mjs','qa/phase-11c/checksums.sha256','qa/phase-11c/current-manifest.json','qa/phase-11c/index.html','qa/phase-11c/probe.mjs','qa/phase-11c/realm.html','qa/phase-11c/realm.js','qa/phase-11c/runner.js','qa/phase-11c/scenarios.json','qa/phase-11c/verify.mjs'],p11cFailures=p11cFrozen.filter(path=>{if(!existsSync(resolve(ROOT,path)))return true;const base=execFileSync('git',['show',`${scenarios.authority.baseCommit}:${path}`],{cwd:ROOT,maxBuffer:64*1024*1024});return!read(path).equals(base)});record('phase11c-package-and-docs-byte-frozen-to-base',p11cFrozen.length===13&&p11cFailures.length===0,{baseCommit:scenarios.authority.baseCommit,count:p11cFrozen.length,failures:p11cFailures});
const manifestPath='qa/phase-11d/current-manifest.json',checksumPath='qa/phase-11d/checksums.sha256';let manifest=null;try{manifest=JSON.parse(read(manifestPath))}catch{}record('manifest-present',Boolean(manifest));if(manifest){record('manifest-authority',manifest.phase==='11D'&&manifest.status==='PASS_LOCAL'&&manifest.productionCommit===scenarios.authority.productionCommit&&git(['merge-base','--is-ancestor',manifest.packageCommit,'HEAD'])===''&&same(manifest.artifact,expectedArtifact)&&manifest.focusedRows.phase11d===103&&manifest.focusedRows.phase11c===83&&manifest.focusedRows.phase11b===286&&manifest.liveRows.total===385&&manifest.liveRows.runs===2&&manifest.liveRows.failed===0&&manifest.reviews.length===3&&manifest.reviews.every(review=>review.status==='PASS'),manifest);const failures=Object.entries(manifest.packageFiles).filter(([path,value])=>!existsSync(resolve(ROOT,path))||!same(identity(read(path)),value)).map(([path])=>path);record('manifest-package-identities',Object.keys(manifest.packageFiles).length===SOURCE.length&&failures.length===0,failures)}
let checksumRows=[];try{checksumRows=read(checksumPath).toString('utf8').trim().split('\n').filter(Boolean)}catch{}const checksumFailures=checksumRows.filter(line=>{const match=line.match(/^([0-9a-f]{64})  (.+)$/);return!match||!existsSync(resolve(ROOT,match[2]))||sha(read(match[2]))!==match[1]});record('phase11d-checksums',checksumRows.length===SOURCE.length+4&&checksumFailures.length===0,{count:checksumRows.length,failures:checksumFailures});
try{const built=JSON.parse(execFileSync(NODE,['qa/phase-11d/build-contract.mjs'],{cwd:ROOT,encoding:'utf8'}));record('builder-read-only',built.writes===0&&same(built.artifact,expectedArtifact)&&built.embeddedAssets.count===5&&Object.keys(built.files).length===13,built)}catch(error){record('builder-read-only',false,error.stderr||error.message)}
record('clean-worktree',git(['status','--porcelain']).trim()==='',git(['status','--porcelain']).trim());
const passed=results.filter(row=>row.pass).length,failed=results.length-passed;console.log(JSON.stringify({phase:'11D',status:failed?'FAIL':'PASS',productionCommit:scenarios.authority.productionCommit,artifact:expectedArtifact,focused:{phase11d:103,phase11c:83,phase11b:286},total:results.length,passed,failed,results},null,2));if(failed)process.exitCode=1;
