(() => {
  'use strict';
  const CHANNEL='everstead-phase-4',inlineJson=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  function installRuntime(config){
    const slots=new Map(Object.entries(config.slots)),nativeSetTimeout=window.setTimeout.bind(window),nativeClearTimeout=window.clearTimeout.bind(window);let saveIndex=0,transactionIndex=0;
    const nativeStorageAccesses=[],errors=[];let nativeStorageInstrumented=false;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    window.__PHASE_4_CONFIG__=config;window.__PHASE_4_SLOTS__=slots;window.__PHASE_4_ERRORS__=errors;window.__PHASE_4_NATIVE_STORAGE_ACCESSES__=nativeStorageAccesses;window.__PHASE_4_NATIVE_STORAGE_INSTRUMENTED__=nativeStorageInstrumented;
    window.addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));window.addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const runtime={storage:{getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>slots.set(String(key),String(value)),removeItem:key=>slots.delete(String(key))},clock:{now:()=>config.now,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.5,confirm:()=>true,ids:{save:()=>`save-p4-browser-${++saveIndex}`,transaction:()=>`tx-p4-browser-${++transactionIndex}`},qa:config.mode==='unattested'?{allowDestructive:true,isolatedStorage:false}:{allowDestructive:true,isolatedStorage:true}};if(config.features)runtime.features=config.features;window.__EVERSTEAD_RUNTIME__=runtime;
  }
  function runSuite(){
    const channel='everstead-phase-4',config=window.__PHASE_4_CONFIG__,slots=window.__PHASE_4_SLOTS__,results=[],add=(id,pass,detail='')=>results.push({id,pass:Boolean(pass),detail:String(detail)}),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),click=selector=>{const node=document.querySelector(selector);if(node)node.click();return node},send=()=>parent.postMessage({channel,nonce:config.nonce,results,errors:window.__PHASE_4_ERRORS__.slice(),checkpointRaw:slots.get(config.keys.backupV4)??null},'*');
    (async()=>{await wait(500);const bridge=window.__EVERSTEAD_QA__;if(!config.expectBridge){add('encoded-query-bridge-absent',bridge===undefined);add('encoded-query-zero-errors',window.__PHASE_4_ERRORS__.length===0,window.__PHASE_4_ERRORS__.join('\n'));send();return}
      add('bridge-present',Boolean(bridge));add('viewport-exact',innerWidth===config.viewport.width&&innerHeight===config.viewport.height,`${innerWidth}x${innerHeight}`);add('no-horizontal-overflow',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);const first=bridge.snapshot(),state=first.state;add('schema5-snapshot',first.ok&&state.schemaVersion===5);add('canonical-companion-shape',Object.keys(state.companions).sort().join(',')==='bramble,cinderwing'&&Object.values(state.companions).every(item=>Object.keys(item).sort().join(',')==='assignedFellowId,exp,level,owned,rarity,shards'&&item.owned===true&&!Object.hasOwn(item,'bound')));const firstDiagnostics=bridge.diagnostics().diagnostics;add('companion-power-live',firstDiagnostics.totalCompanionRosterPower===2200&&firstDiagnostics.companionPowerComponents.bramble.effectivePower===1000&&firstDiagnostics.companionPowerComponents.cinderwing.effectivePower===1200);add('mastery-hook-neutral',Object.values(firstDiagnostics.companionPowerComponents).every(item=>item.masteryMultiplier===1));
      if(config.mode==='schema3-seed'){add('seed-schema3-checkpoint-exact',slots.get(config.keys.backupV3)===config.originalActiveRaw);add('seed-schema4-checkpoint-present',JSON.parse(slots.get(config.keys.backupV4)).schemaVersion===4);add('seed-receipt-order',state.saveMeta.appliedMigrations.at(-1).id==='schema-4-to-5');add('seed-zero-errors',window.__PHASE_4_ERRORS__.length===0,window.__PHASE_4_ERRORS__.join('\n'));send();return}
      if(config.mode==='fresh'){add('fresh-default-pairings',state.companions.bramble.assignedFellowId==='orin'&&state.companions.cinderwing.assignedFellowId==='cael');add('fresh-checkpoints-empty',![0,1,2,3,4].some(version=>slots.has(config.keys[`backupV${version}`])))}
      if(config.mode==='schema4'){add('schema4-checkpoint-exact',slots.get(config.keys.backupV4)===config.originalActiveRaw);add('schema4-assignment-migration',state.companions.bramble.assignedFellowId==='orin'&&state.companions.cinderwing.assignedFellowId==='selene');add('schema4-one-receipt',state.saveMeta.appliedMigrations.filter(item=>item.id==='schema-4-to-5').length===1)}
      if(config.mode==='legacy'){add('legacy-v0-exact',slots.get(config.keys.backupV0)===config.originalActiveRaw);add('legacy-all-checkpoints',[1,2,3,4].every(version=>JSON.parse(slots.get(config.keys[`backupV${version}`])).schemaVersion===version));add('legacy-unicode',state.oaths.some(oath=>oath.title==='Fixture café review 🌵'));add('legacy-companion-pairings',state.companions.bramble.assignedFellowId==='orin'&&state.companions.cinderwing.assignedFellowId==='selene')}
      if(config.mode==='collision'){const collisions=firstDiagnostics.companionMigrationCollisions;add('collision-ordered',state.companions.bramble.assignedFellowId==='cael'&&state.companions.cinderwing.assignedFellowId===null&&collisions.length===1&&collisions[0].companionId==='cinderwing');click('[data-nav="fellows"]');click('[data-roster="companions"]');const text=document.querySelector('main.screen')?.textContent||'';add('collision-notice-visible',text.includes('Companion assignment collision resolved')&&text.includes('Cinderwing became Unassigned'))}
      if(config.mode==='disabled'){const flags=bridge.flags();add('all-disabled',flags.ok&&Object.values(flags.features).every(value=>value===false));const before=slots.get(config.keys.active),refused=['story','tower','trade','patrol-start','operation-start'].map(name=>bridge.act(name));add('disabled-actions-refused',refused.every(value=>!value.ok));add('disabled-zero-write',slots.get(config.keys.active)===before)}
      if(config.mode==='unattested'){const before=slots.get(config.keys.active),revision=state.saveMeta.revision,refused=[bridge.act('companion-exp',{id:'bramble',amount:80}),bridge.act('companion-shards',{id:'bramble',amount:20}),bridge.act('companion-assign',{id:'bramble',fellowId:null}),bridge.act('companion-ascend',{id:'bramble'})];add('unattested-destructive-actions-refused',refused.every(item=>!item.ok));add('unattested-zero-write',slots.get(config.keys.active)===before&&bridge.snapshot().state.saveMeta.revision===revision)}
      if(config.mode==='fresh'){
        click('[data-nav="fellows"]');click('[data-roster="companions"]');let text=document.querySelector('main.screen')?.textContent||'';add('two-live-companion-cards',document.querySelectorAll('[data-companion].char-card').length===2&&text.includes('Level 1')&&text.includes('Power')&&text.includes('shards')&&text.includes('Assigned to'));
        click('[data-companion="bramble"]');text=document.querySelector('#overlay')?.textContent||'';add('bramble-profile-live',text.includes('COMPANION POWER')&&text.includes('EXP progress')&&text.includes('Power components')&&text.includes('Free Fellow assignment')&&text.includes('Power sent')&&!/Phase 4 preview|Bind to Fellow|static \+6%/.test(text));click('[data-modal-close]');click('[data-companion="cinderwing"]');text=document.querySelector('#overlay')?.textContent||'';add('cinderwing-profile-live',text.includes('Cinderwing')&&text.includes('COMPANION POWER')&&text.includes('Assigned to Cael'));click('[data-modal-close]');
        const ratesBefore=JSON.stringify(bridge.diagnostics().diagnostics.buildingRateComponents),caelBefore=bridge.diagnostics().diagnostics.fellowPowerComponents.cael.effectivePower;bridge.act('companion-exp',{id:'bramble',amount:79});const levelUp=bridge.act('companion-exp',{id:'bramble',amount:1});add('exp-level-boundary-live',levelUp.ok&&levelUp.state.companions.bramble.exp===80&&levelUp.state.companions.bramble.level===2);const refusedAscend=bridge.act('companion-ascend',{id:'bramble'});add('ascend-refusal-live',!refusedAscend.ok);bridge.act('companion-shards',{id:'bramble',amount:20});const ascended=bridge.act('companion-ascend',{id:'bramble'});add('ascend-success-live',ascended.ok&&ascended.state.companions.bramble.rarity===2&&ascended.state.companions.bramble.shards===0);
        click('[data-companion="bramble"]');const selector=document.querySelector('[data-companion-assignment]');selector.value='cael';selector.dispatchEvent(new Event('change',{bubbles:true}));text=document.querySelector('[data-companion-assignment-preview]')?.textContent||'';add('assignment-preview-displacement-live',text.includes('Current')&&text.includes('Projected')&&text.includes('Cinderwing')&&text.includes('displaced'));click('[data-companion-assignment-save]');let assigned=bridge.snapshot().state;add('assignment-displacement-live',assigned.companions.bramble.assignedFellowId==='cael'&&assigned.companions.cinderwing.assignedFellowId===null);const caelAfter=bridge.diagnostics().diagnostics.fellowPowerComponents.cael.effectivePower;add('fellow-power-changes-live',caelAfter!==caelBefore,`${caelBefore}->${caelAfter}`);
        const none=document.querySelector('[data-companion-assignment]');none.value='';none.dispatchEvent(new Event('change',{bubbles:true}));click('[data-companion-assignment-save]');assigned=bridge.snapshot().state;add('unassign-live',assigned.companions.bramble.assignedFellowId===null);bridge.act('companion-assign',{id:'cinderwing',fellowId:'orin'});const displaced=bridge.act('companion-assign',{id:'bramble',fellowId:'orin'});add('atomic-reassign-live',displaced.ok&&displaced.state.companions.bramble.assignedFellowId==='orin'&&displaced.state.companions.cinderwing.assignedFellowId===null);bridge.act('companion-assign',{id:'cinderwing',fellowId:'cael'});
        const ratesAfter=JSON.stringify(bridge.diagnostics().diagnostics.buildingRateComponents);add('companion-no-building-rate-change-live',ratesAfter===ratesBefore);click('[data-modal-close]');click('[data-roster="fellows"]');click('[data-fellow="cael"]');text=document.querySelector('#overlay')?.textContent||'';add('fellow-profile-transfer-live',text.includes('Assigned Companion')&&text.includes('Cinderwing')&&text.includes('40%')&&text.includes('Power transferred'));
        const diagnostic=bridge.diagnostics();add('diagnostics-companion-complete',diagnostic.ok&&Object.hasOwn(diagnostic.diagnostics,'preV5Backup')&&diagnostic.diagnostics.companionAssignments.bramble==='orin'&&diagnostic.diagnostics.companionTransfers.cael.assignedCompanionId==='cinderwing');const exported=bridge.recovery.export().data;add('safe-export-seven-slots',exported.exportVersion===5&&exported.preV5BackupKey===config.keys.backupV4);const reload=bridge.recovery.reload();add('reload-persists-companions',reload.ok&&reload.state.companions.bramble.level===2&&reload.state.companions.bramble.rarity===2&&reload.state.companions.bramble.assignedFellowId==='orin'&&reload.state.companions.cinderwing.assignedFellowId==='cael')
      }
      add('native-storage-instrumented',window.__PHASE_4_NATIVE_STORAGE_INSTRUMENTED__===true);add('zero-native-storage-calls',window.__PHASE_4_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_4_NATIVE_STORAGE_ACCESSES__.join(','));add('realm-zero-errors',window.__PHASE_4_ERRORS__.length===0,window.__PHASE_4_ERRORS__.join('\n'));send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }
  (async()=>{const config=JSON.parse(window.name);window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error('index.html: HTTP '+response.status);const source=await response.text(),firstScript=source.indexOf('<script>');if(firstScript<0)throw new Error('Production script is missing');const bootstrap='<script>('+installRuntime.toString()+')('+inlineJson(config)+')<\/script>',suite='<script>('+runSuite.toString()+')()<\/script>',instrumented=source.slice(0,firstScript)+bootstrap+source.slice(firstScript).replace('</body>',suite+'</body>');document.open();document.write(instrumented);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce:'unknown',results:[{id:'realm-loader-fatal',pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
