(() => {
  'use strict';
  const CHANNEL='everstead-phase-4',byId=id=>document.getElementById(id),result=(id,pass,detail='')=>({id,pass:Boolean(pass),detail:String(detail)}),escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),hex=bytes=>[...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,'0')).join(''),sha256=async bytes=>hex(await crypto.subtle.digest('SHA-256',bytes)),decode=bytes=>new TextDecoder('utf-8',{fatal:true}).decode(bytes);
  async function bytes(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return new Uint8Array(await response.arrayBuffer())}
  function makeSchemaTwo(raw,now){const value=JSON.parse(raw);for(const building of Object.values(value.buildings))delete building.operators;value.schemaVersion=2;value.saveMeta.appliedMigrations.push({id:'schema-1-to-2',from:1,to:2,appliedAt:now});value.saveMeta.revision++;value.saveMeta.updatedAt=now;value.saveMeta.source='schema-1';return value}
  function fellowExpThreshold(level){let total=0;for(let current=1;current<level;current++)total+=Math.round(100*Math.pow(1.12,current-1));return total}
  function makeSchemaThree(schemaTwo,now){const value=JSON.parse(JSON.stringify(schemaTwo));for(const fellow of Object.values(value.fellows)){const level=Math.max(1,Math.min(120,Math.floor(Number.isFinite(fellow.training)?fellow.training:1))),bond=Number.isFinite(fellow.bond)?fellow.bond:35;Object.assign(fellow,{owned:true,exp:fellowExpThreshold(level),level,rarity:1,shards:0,bond,relicSlots:[]});for(const key of ['training','calculatedPower','effectivePower','totalPower','prestige','assignedCompanionId','familyBondBonus','relicBonus','companionBonus','globalMultiplier'])delete fellow[key]}value.schemaVersion=3;value.saveMeta.appliedMigrations.push({id:'schema-2-to-3',from:2,to:3,appliedAt:now});value.saveMeta.revision++;value.saveMeta.updatedAt=now;value.saveMeta.source='schema-2';return JSON.stringify(value)}
  async function loadContract(){const manifest=JSON.parse(decode(await bytes('./current-manifest.json'))),scenarioBytes=await bytes('./scenarios.json'),scenarios=JSON.parse(decode(scenarioBytes));if(await sha256(scenarioBytes)!==manifest.scenarios.sha256)throw new Error('Scenario checksum mismatch');const staticResults=[];for(const [path,expected]of Object.entries(manifest.frozenHistoricalFiles)){const actual=await sha256(await bytes('../../'+path));staticResults.push(result('frozen-'+path.replaceAll('/','-'),actual===expected,actual))}const artifactBytes=await bytes('../../index.html'),artifactHash=await sha256(artifactBytes);if(artifactHash!==manifest.artifact.sha256||artifactBytes.byteLength!==manifest.artifact.byteLength)throw new Error('Artifact checksum mismatch');staticResults.push(result('artifact-checksum',true,artifactHash));const schemaOneRaw=decode(await bytes('../gate-0b/fixtures/current-v1.txt')),legacyRaw=decode(await bytes('../fixtures/representative-v0.1.txt')),now=Date.parse(scenarios.frozenNow),schemaThreeRaw=makeSchemaThree(makeSchemaTwo(schemaOneRaw,now),now);return{manifest,scenarios,legacyRaw,schemaThreeRaw,staticResults}}
  function executeRealm(contract,viewport,mode,{search='?qa=1',schemaFourRaw=null}={}){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),now=Date.parse(contract.scenarios.frozenNow);let activeRaw=mode==='fresh'||mode==='disabled'?null:mode==='legacy'?contract.legacyRaw:mode==='schema3-seed'?contract.schemaThreeRaw:schemaFourRaw;if(mode==='collision'){const collision=JSON.parse(schemaFourRaw);collision.companions.bramble.bound='cael';collision.companions.cinderwing.bound='cael';activeRaw=JSON.stringify(collision)}if(activeRaw!==null){const value=JSON.parse(activeRaw);value.lastGoldAt=now;value.lastSeen=now;activeRaw=JSON.stringify(value)}const features=mode==='disabled'?{story:false,tower:false,trading:false,patrol:false,operations:false}:undefined,config={nonce,mode,expectBridge:search==='?qa=1',viewport,now,features,keys:contract.scenarios.storageKeys,originalActiveRaw:activeRaw,slots:activeRaw===null?{}:{[contract.scenarios.storageKeys.active]:activeRaw}};frame.name=JSON.stringify(config);frame.setAttribute('sandbox','allow-scripts allow-same-origin');frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0`;const finish=(error,value)=>{clearTimeout(timeout);removeEventListener('message',onMessage);frame.remove();error?reject(error):resolve(value)},onMessage=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=event.data.results.map(item=>({...item,id:`${viewport.id}-${mode}-${item.id}`}));if(event.data.errors?.length)rows.push(result(`${viewport.id}-${mode}-captured-errors`,false,event.data.errors.join('\n')));finish(null,{rows,checkpointRaw:event.data.checkpointRaw??null})},timeout=setTimeout(()=>finish(new Error(`${viewport.id}/${mode} timed out`)),30000);addEventListener('message',onMessage);frame.src=`./realm.html${search}&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  function render(rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)}${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_4_RESULT__={passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const data=await loadContract(),rows=[...data.staticResults],seed=await executeRealm(data,data.scenarios.viewports[0],'schema3-seed');rows.push(...seed.rows);if(!seed.checkpointRaw)throw new Error('Schema-3 seed realm did not expose the exact schema-4 checkpoint');for(const viewport of data.scenarios.viewports)for(const mode of ['fresh','schema4','legacy','collision','disabled']){const realm=await executeRealm(data,viewport,mode,{schemaFourRaw:seed.checkpointRaw});rows.push(...realm.rows)}const unattested=await executeRealm(data,data.scenarios.viewports[0],'unattested',{schemaFourRaw:seed.checkpointRaw}),negative=await executeRealm(data,data.scenarios.viewports[0],'encoded-negative',{search:'?qa=%31',schemaFourRaw:seed.checkpointRaw});rows.push(...unattested.rows,...negative.rows);render(rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render([result('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
