(() => {
  'use strict';
  const inlineJson=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  function installRuntime(config){
    const slots=new Map(Object.entries(config.slots)),nativeSetTimeout=window.setTimeout.bind(window),nativeClearTimeout=window.clearTimeout.bind(window),randomValues=config.randomSequence.slice();
    let randomIndex=0,saveIndex=0,transactionIndex=0;
    const nativeStorageAccesses=[],errors=[];
    let nativeStorageInstrumented=false;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    window.__PHASE_2_CONFIG__=config;window.__PHASE_2_SLOTS__=slots;window.__PHASE_2_ERRORS__=errors;window.__PHASE_2_NATIVE_STORAGE_ACCESSES__=nativeStorageAccesses;window.__PHASE_2_NATIVE_STORAGE_INSTRUMENTED__=nativeStorageInstrumented;
    window.addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));window.addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));
    const nativeWarn=console.warn.bind(console),nativeError=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));nativeWarn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));nativeError(...args)};
    const runtime={storage:{getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>slots.set(String(key),String(value)),removeItem:key=>slots.delete(String(key))},clock:{now:()=>config.now,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random(){if(randomIndex>=randomValues.length)throw new Error('browser runtime random exhausted');return randomValues[randomIndex++]},confirm:()=>true,ids:{save:()=>`save-phase-2-browser-${++saveIndex}`,transaction:()=>`tx-phase-2-browser-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
    if(config.features)runtime.features=config.features;window.__EVERSTEAD_RUNTIME__=runtime;
  }
  function runSuite(){
    const config=window.__PHASE_2_CONFIG__,slots=window.__PHASE_2_SLOTS__,results=[];
    const add=(id,pass,detail='')=>results.push({id,pass:Boolean(pass),detail:String(detail)}),wait=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds)),click=selector=>{const node=document.querySelector(selector);if(node)node.click();return node},send=()=>parent.postMessage({channel:'everstead-phase-2',nonce:config.nonce,results,errors:window.__PHASE_2_ERRORS__.slice()},'*');
    const current=raw=>{try{const value=JSON.parse(raw);return value?.schemaVersion===3?value:null}catch{return null}};
    (async()=>{
      await wait(420);
      const bridge=window.__EVERSTEAD_QA__;
      if(!config.expectBridge){add('bridge-absent-for-encoded-query',bridge===undefined);add('negative-realm-zero-errors',window.__PHASE_2_ERRORS__.length===0,window.__PHASE_2_ERRORS__.join('\n'));send();return}
      add('bridge-present',Boolean(bridge));add('viewport-width',innerWidth===config.viewport.width,`${innerWidth}x${innerHeight}`);add('viewport-height',innerHeight===config.viewport.height,`${innerWidth}x${innerHeight}`);add('phone-no-horizontal-overflow',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);
      const visibleBody=document.body.cloneNode(true);visibleBody.querySelectorAll('script,style,template,noscript').forEach(node=>node.remove());const bodyText=visibleBody.textContent;
      add('everstead-brand-rendered',bodyText.includes('EVERSTEAD'));add('ordinary-debug-controls-absent',!/SIMULATE 2H|\+1 PATROL|RESET PROTOTYPE/i.test(bodyText));
      const first=bridge.snapshot();add('schema-3-snapshot',first.ok&&first.state.schemaVersion===3);add('canonical-fellow-shape',first.ok&&Object.values(first.state.fellows).every(item=>item.owned===true&&Number.isInteger(item.exp)&&Number.isInteger(item.level)&&Number.isInteger(item.rarity)&&Number.isInteger(item.shards)&&Array.isArray(item.relicSlots)&&!Object.hasOwn(item,'training')));
      if(config.mode==='fresh'){add('fresh-active-created',current(slots.get(config.keys.active))?.schemaVersion===3);add('fresh-checkpoints-empty',!slots.has(config.keys.backupV1)&&!slots.has(config.keys.backupV2));add('fresh-offline-modal-absent',!document.querySelector('#overlay .offline-list'))}else add('offline-2h-modal',Boolean(document.querySelector('#overlay .offline-list')));
      if(config.mode==='schema2')add('schema2-checkpoint-exact',slots.get(config.keys.backupV2)===config.originalActiveRaw);
      if(config.mode==='legacy'){add('legacy-v0-backup-exact',slots.get(config.keys.backupV0)===config.originalActiveRaw);add('legacy-v1-checkpoint',JSON.parse(slots.get(config.keys.backupV1)).schemaVersion===1);add('legacy-v2-checkpoint',JSON.parse(slots.get(config.keys.backupV2)).schemaVersion===2);add('legacy-unicode-preserved',first.state.oaths.some(oath=>oath.title==='Fixture café review 🌵'))}
      if(config.mode==='disabled'){
        const flags=bridge.flags();add('all-disabled-flags',flags.ok&&Object.values(flags.features).every(value=>value===false));const before=slots.get(config.keys.active),refused=['story','tower','trade','optimize-trade','optimize-story','patrol-start','operation-start','operation-claim'].map(name=>bridge.act(name));add('disabled-actions-refused',refused.every(value=>value.ok===false));add('disabled-actions-no-write',slots.get(config.keys.active)===before);
      }else{
        const navigation=[];for(const view of ['village','oaths','fellows','adventure','more']){click(`[data-nav="${view}"]`);navigation.push(Boolean(document.querySelector(`[data-nav="${view}"].on`)))}add('navigation-renders-all-five-views',navigation.every(Boolean));
        click('[data-nav="fellows"]');click('[data-roster="fellows"]');add('six-fellow-cards',document.querySelectorAll('[data-fellow].char-card').length===6);const cardText=document.querySelector('main.screen')?.textContent||'';add('cards-level-rarity-power',/Level \d+/.test(cardText)&&/Power/.test(cardText)&&/★1/.test(cardText));click('[data-fellow="mira"]');let modalText=document.querySelector('#overlay')?.textContent||'';add('fellow-profile-type-role',modalText.includes('Type Storm')&&modalText.includes('Role Support'));add('fellow-profile-exp-rarity-shards-bond',/EXP progress/.test(modalText)&&/Rarity/.test(modalText)&&/Shards/.test(modalText)&&/Bond/.test(modalText));add('legacy-fellow-copy-absent',!/Train|Prestige|active Blessing|\+6%/.test(modalText));add('component-breakdown-visible',modalText.includes('Power components')&&modalText.includes('rounded once'));
        const beforeTotal=bridge.diagnostics().diagnostics.totalFellowRosterPower,miraBefore=bridge.snapshot().state.fellows.mira,nextLevel=Math.min(120,miraBefore.level+1),nextThreshold=Array.from({length:nextLevel-1},(_,index)=>Math.round(100*Math.pow(1.12,index))).reduce((sum,value)=>sum+value,0),expDelta=nextThreshold-miraBefore.exp,grantExp=bridge.controls.grant({resource:'fellowExp',id:'mira',amount:expDelta});add('isolated-exp-grant',grantExp.ok&&grantExp.state.fellows.mira.level===nextLevel);const afterTotal=bridge.diagnostics().diagnostics.totalFellowRosterPower;add('non-squad-level-changes-total',afterTotal>beforeTotal);const grantShards=bridge.controls.grant({resource:'fellowShards',id:'mira',amount:20});add('isolated-shard-grant',grantShards.ok&&grantShards.state.fellows.mira.shards===20&&grantShards.state.fellows.mira.rarity===1);const ascend=bridge.act('fellow-ascend',{id:'mira'});add('ascension-persists',ascend.ok&&ascend.state.fellows.mira.rarity===2&&ascend.state.fellows.mira.shards===0&&ascend.state.fellows.mira.level===nextLevel);
        click('[data-nav="more"]');const moreText=document.querySelector('main.screen')?.textContent||'';add('campaign-preview-visible',moreText.includes('Phase 5 preview')&&moreText.includes('Campaign Stage Efficiency')&&moreText.includes('Total roster Power'));const diagnostic=bridge.diagnostics();add('diagnostics-power-and-efficiency',diagnostic.ok&&Object.keys(diagnostic.diagnostics.fellowPowerComponents).length===6&&diagnostic.diagnostics.totalFellowRosterPower>0&&diagnostic.diagnostics.campaignEfficiencyPreview.effectiveCost>0);add('diagnostics-v2-checkpoint',diagnostic.ok&&Object.hasOwn(diagnostic.diagnostics,'preV3Backup'));
        click('[data-nav="fellows"]');click('[data-roster="family"]');click('[data-family="elara"]');modalText=document.querySelector('#overlay')?.textContent||'';add('family-power-quarantined',modalText.includes('Phase 3')&&modalText.includes('no Gold-funded progression')&&!modalText.includes('Blessing'));click('[data-modal-close]');click('[data-roster="companions"]');click('[data-companion="cinderwing"]');modalText=document.querySelector('#overlay')?.textContent||'';add('companion-transfer-neutral',modalText.includes('Phase 4')&&modalText.includes('×1.00')&&!modalText.includes('+6%'));
        const beforeReload=bridge.snapshot().state,rawBeforeReload=slots.get(config.keys.active),reload=bridge.recovery.reload();add('persistence-reload',reload.ok&&reload.state.fellows.mira.level===beforeReload.fellows.mira.level&&slots.get(config.keys.active)!==undefined);add('safe-export-five-slots',bridge.recovery.export().data.preV3BackupKey===config.keys.backupV2);add('reload-keeps-active',typeof rawBeforeReload==='string'&&current(slots.get(config.keys.active))?.schemaVersion===3);
      }
      add('native-storage-instrumented',window.__PHASE_2_NATIVE_STORAGE_INSTRUMENTED__===true);add('no-native-storage-calls',window.__PHASE_2_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_2_NATIVE_STORAGE_ACCESSES__.join(','));add('realm-zero-errors',window.__PHASE_2_ERRORS__.length===0,window.__PHASE_2_ERRORS__.join('\n'));send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }
  (async()=>{const config=JSON.parse(window.name);window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error('index.html: HTTP '+response.status);const source=await response.text(),firstScript=source.indexOf('<script>');if(firstScript<0)throw new Error('Production script is missing');const bootstrap='<script>('+installRuntime.toString()+')('+inlineJson(config)+')<\/script>',suite='<script>('+runSuite.toString()+')()<\/script>',instrumented=source.slice(0,firstScript)+bootstrap+source.slice(firstScript).replace('</body>',suite+'</body>');document.open();document.write(instrumented);document.close()})().catch(error=>parent.postMessage({channel:'everstead-phase-2',nonce:'unknown',results:[{id:'realm-loader-fatal',pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
