(()=>{
  'use strict';
  const CHANNEL='everstead-phase-20-21-independent',json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config){
    const slots=new Map(),writes=[],errors=[],nativeStorageAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);let saveIndex=0,transactionIndex=0,nativeStorageInstrumented=false;
    window.matchMedia=query=>({matches:config.viewport.reducedMotion&&query==='(prefers-reduced-motion: reduce)',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});document.documentElement.style.fontSize=`${config.viewport.copyScale||1}em`;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>{key=String(key);writes.push({op:'set',key,value:String(value)});slots.set(key,String(value))},removeItem:key=>{key=String(key);writes.push({op:'remove',key});slots.delete(key)}};
    Object.assign(window,{__P2021I_CONFIG__:config,__P2021I_SLOTS__:slots,__P2021I_WRITES__:writes,__P2021I_ERRORS__:errors,__P2021I_NATIVE_ACCESSES__:nativeStorageAccesses,__P2021I_NATIVE_INSTRUMENTED__:nativeStorageInstrumented});window.__EVERSTEAD_RUNTIME__={storage:memoryStorage,clock:{now:()=>config.fixtures.frozenNow,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.4375,confirm:()=>true,ids:{save:()=>`save-p2021i-${++saveIndex}`,transaction:()=>`tx-p2021i-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
  }

  function runSuite(){
    const config=window.__P2021I_CONFIG__,f=config.fixtures,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),until=async(predicate,limit=8000)=>{const started=performance.now();while(performance.now()-started<limit){if(predicate())return true;await wait(25)}return false},same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),unique=values=>new Set(values).size===values.length,sorted=values=>[...new Set(values)].sort();
    const add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),send=()=>parent.postMessage({channel:config.channel,nonce:config.nonce,results,errors:window.__P2021I_ERRORS__.slice()},'*'),bridge=()=>window.__EVERSTEAD_PHASE_20_21_QA__,safe=(label,fn)=>{try{return fn()}catch(error){add(label,false,error.stack||error.message);return null}},call=(group,name,...args)=>safe(`${name}-call`,()=>bridge()[group][name](...args));
    const state=value=>value?.state||value,revision=value=>state(value)?.saveMeta?.revision,facilityState=(data,id)=>data?.facilities?.[id]||{},bank=(data,id)=>facilityState(data,id).opportunities||[],offers=data=>data?.claims?.pendingOffers||data?.offers||[],resources=data=>data?.resources||{},receipts=data=>data?.claimArchive?.recentReceipts||data?.claims?.archive?.recentReceipts||[];
    (async()=>{
      await until(()=>bridge(),5000);const qa=bridge();add('bridge-present',Boolean(qa));if(!qa){add('phase20-21-contract-unavailable',false,'Expected before Phases 20–21 implementation: window.__EVERSTEAD_PHASE_20_21_QA__ is absent.');send();return}
      add('bridge-version',qa.version===f.bridgeVersion,qa.version);const requiredRead=['definitions','snapshot','validate','derive','raw','exportSave','passiveBaseline','policyReport','boardModel','forbiddenSystemReport'],requiredDestructive=['resetFixture','reload','importFixture','migrate','advanceOffline','settle','openFacility','begin','choose','commitEngagement','cancelEngagement','advanceGrowth','resolve','claim','tutorial','simulateConcurrent','mutateInvalid','probeFinalizerFailure'];add('bridge-read-surface',requiredRead.every(name=>typeof qa.read?.[name]==='function'),Object.keys(qa.read||{}));add('bridge-destructive-surface',requiredDestructive.every(name=>typeof qa.destructive?.[name]==='function'),Object.keys(qa.destructive||{}));if(!requiredRead.every(name=>typeof qa.read?.[name]==='function')||!requiredDestructive.every(name=>typeof qa.destructive?.[name]==='function')){send();return}

      const defs=call('read','definitions');if(!defs){send();return}const definitionFacilities=defs.facilities||[],definitionOpportunities=defs.opportunities||[],definitionFinalizers=defs.finalizers||[];
      add('predecessor-finalizer-v2-seams',defs.predecessor?.facilityFrameworkConfigId===f.predecessor.facilityFrameworkConfigId&&defs.predecessor?.archiveConfigId===f.predecessor.archiveConfigId&&defs.predecessor?.offerVersion===2&&defs.predecessor?.receiptVersion===2&&defs.predecessor?.storyRegistryId===f.predecessor.storyRegistryId&&defs.predecessor?.phase19MigrationId===f.predecessor.phase19MigrationId,defs.predecessor);
      add('eight-configs-registries-exact',defs.configs?.phase20===f.configs.phase20&&defs.configs?.phase20Definitions===f.configs.phase20Definitions&&defs.configs?.phase21===f.configs.phase21&&defs.configs?.phase21Definitions===f.configs.phase21Definitions&&defs.configs?.integration===f.configs.integration&&defs.configs?.integrationDefinitions===f.configs.integrationDefinitions,defs.configs);
      add('eight-facility-identities-exact',same(definitionFacilities.map(item=>({phase:item.phase,facilityId:item.facilityId,activityId:item.activityId,opportunityId:item.opportunityId,anchor:item.anchor,capabilityId:item.capabilityId,discoveryId:item.discoveryId,openingId:item.openingId,progressId:item.progressId,interaction:item.interaction,finalizerId:item.finalizerId,passivePolicy:item.passivePolicy})),f.facilities),definitionFacilities);
      add('eight-manual-nonexpiring-opportunities',definitionOpportunities.length===8&&definitionOpportunities.every(item=>item.expires===false&&item.claimMode==='manual'&&f.facilities.some(facility=>facility.opportunityId===item.id&&facility.activityId===item.activityId)),definitionOpportunities);
      add('eight-immutable-shared-finalizers',definitionFinalizers.length===8&&f.facilities.every(facility=>definitionFinalizers.some(item=>item.sourceId===facility.activityId&&item.finalizerId===facility.finalizerId&&item.immutable===true&&item.callerSupplied===false&&item.offerVersion===2&&item.receiptVersion===2)),definitionFinalizers);
      add('distinct-domain-content-exact',f.facilities.every(facility=>{const actual=defs.activityContent?.[facility.facilityId],expected=f.activityContent[facility.facilityId];return actual&&same(actual.templateIds,expected.templateIds)&&actual.choiceCount===expected.choiceCount&&same(actual.outcomeIds,expected.outcomeIds)}),defs.activityContent);
      add('story-capability-opening-authority',definitionFacilities.every(item=>item.storyAuthority==='phase-17'&&item.replayGrants===false&&item.grandfatherNeverRelocks===true),definitionFacilities);
      add('tutorials-gradual-nonblocking-exact',same((defs.tutorials||[]).map(item=>item.id),f.tutorialIds)&&(defs.tutorials||[]).every(item=>item.blocking===false&&item.reward==null&&item.skippable===true&&item.replayable===true&&item.contextual===true)&&defs.tutorialPolicy?.maxAutoPerSafeVisit===1,defs.tutorials);
      add('all-38-continuing-cast-28-facility-subset',same(sorted(defs.castCoverage?.allRosterActorIds||[]),sorted(f.allRosterActorIds))&&same(sorted(defs.castCoverage?.phase20_21ActorIds||[]),sorted(f.phase20_21ActorIds))&&defs.castCoverage?.hookCount===f.hookCount&&(defs.castCoverage?.allRoster||[]).every(item=>item.profileQuote===true&&item.ambientComment===true&&item.scheduledRole===true),defs.castCoverage);
      const expectedMotion=config.viewport.reducedMotion?'reduce':'no-preference',motionMarker=document.documentElement.getAttribute('data-everstead-reduced-motion'),motionCss=config.candidateReducedCssContract||{};add('original-everstead-visual-and-reduced-motion-contract',defs.presentation?.originalEversteadOnly===true&&defs.presentation?.referenceAssetsIngested===false&&defs.presentation?.referenceTradeDressCopied===false&&defs.presentation?.unframedFullBackgroundDialogueCount===0&&motionMarker===expectedMotion&&defs.runtime?.reducedMotionMarker===expectedMotion&&motionCss.hasMediaRule&&motionCss.globalAnimationNone&&motionCss.globalTransitionNone,{presentation:defs.presentation,motionMarker,motionCss});
      const policy=call('read','policyReport');add('null-policy-fails-closed',policy?.productionEnabled===false&&policy?.qaFallbackUsed===false&&policy?.integrationEnabled===false&&f.facilities.every(item=>policy?.facilities?.[item.facilityId]?.generationEnabled===false&&policy?.facilities?.[item.facilityId]?.resolutionEnabled===false&&policy?.facilities?.[item.facilityId]?.claimEnabled===false),policy);
      const forbidden=call('read','forbiddenSystemReport');add('forbidden-systems-absent',f.forbiddenSystems.every(id=>forbidden?.[id]===false)&&forbidden?.bottomNavigationCount===5&&forbidden?.physicalVillageBoard===true,forbidden);

      const passiveAt=f.frozenNow,passiveBefore=call('read','passiveBaseline',passiveAt);add('original-four-passive-same-time-normalized',passiveBefore?.capturedAt===passiveAt&&passiveBefore?.buildingSemantics?.length===4&&same(passiveBefore.buildingSemantics.map(item=>item.facilityId),f.originalPassiveFacilityIds)&&passiveBefore.buildingSemantics.every(item=>item.passiveGoldPreserved===true&&item.oathMultiplierPreserved===true&&item.familyAssignmentPreserved===true&&item.fellowStaffing===false)&&passiveBefore?.offlineCapMs===f.offlineCapMs&&!JSON.stringify(passiveBefore).includes('"boostDay"'),passiveBefore);
      const migrated20=call('destructive','migrate',f.saveFixtures.migrated20),migrated21=call('destructive','migrate',f.saveFixtures.migrated21);add('ordered-additive-idempotent-migrations',migrated20?.ok===true&&migrated21?.ok===true&&same(migrated21?.migrationIds?.slice(-2),f.migrations)&&migrated21?.createdOpportunityCount===0&&migrated21?.createdRewardCount===0&&migrated21?.passiveBytesPreserved===true&&call('destructive','migrate',f.saveFixtures.migrated21)?.writes===0,{migrated20,migrated21});

      call('destructive','resetFixture',f.saveFixtures.allUnlocked);for(const facility of f.facilities){const before=call('read','derive'),partial=call('destructive','settle',facility.facilityId,f.frozenNow+f.syntheticPolicy.intervalMsByFacility[facility.facilityId]-1),afterPartial=call('read','derive');add(`${facility.facilityId}-partial-carry-zero-credit`,partial?.ok===true&&partial?.createdCount===0&&bank(afterPartial,facility.facilityId).length===bank(before,facility.facilityId).length&&same(resources(afterPartial),resources(before)),partial);const settled=call('destructive','settle',facility.facilityId,f.frozenNow+2*f.syntheticPolicy.intervalMsByFacility[facility.facilityId]),items=bank(call('read','derive'),facility.facilityId);add(`${facility.facilityId}-bank-nonexpiring-deterministic`,settled?.ok===true&&settled?.createdCount===2&&items.slice(-2).every(item=>item.expiresAt==null&&item.status==='banked')&&unique(items.map(item=>item.identity)),{settled,items})}

      const flow=async(facilityId,fixtureId,choiceMode='valid')=>{call('destructive','resetFixture',fixtureId);const before=call('read','derive'),item=bank(before,facilityId)[0],begun=call('destructive','begin',facilityId,item.id,item.identity),chosen=call('destructive','choose',facilityId,item.id,item.identity,choiceMode),committed=call('destructive','commitEngagement',facilityId,item.id,item.identity),raw=call('read','raw');call('destructive','reload');const resumed=call('read','raw')===raw,resolved=call('destructive','resolve',facilityId,item.id,item.identity),ready=call('read','derive'),offer=offers(ready).find(value=>value.sourceId===f.facilities.find(entry=>entry.facilityId===facilityId).activityId);return{item,begun,chosen,committed,resumed,resolved,ready,offer}};
      const command=await flow('facility.command-center',f.saveFixtures.commandBanked);add('command-petition-choice-recorded-manual',command.begun?.ok&&command.chosen?.ok&&command.resumed&&command.resolved?.outcomeId==='command.outcome.recorded'&&command.offer&&!command.resolved?.hiddenPermanentBranch&&command.resolved?.rewardApplications===0,command);
      call('destructive','resetFixture',f.saveFixtures.archivesBanked);let archiveItem=bank(call('read','derive'),'facility.archives')[0];call('destructive','begin','facility.archives',archiveItem.id,archiveItem.identity);call('destructive','choose','facility.archives',archiveItem.id,archiveItem.identity,'invalid-evidence');const archiveInvalid=call('destructive','resolve','facility.archives',archiveItem.id,archiveItem.identity);add('archives-invalid-reconstruction-returns-unconsumed',archiveInvalid?.ok===true&&archiveInvalid?.returnsTo==='reconstruct'&&archiveInvalid?.consumed===false&&archiveInvalid?.rewardApplications===0&&offers(call('read','derive')).length===0,archiveInvalid);const archives=await flow('facility.archives',f.saveFixtures.archivesBanked);add('archives-valid-research-manual',archives.resumed&&f.activityContent['facility.archives'].outcomeIds.includes(archives.resolved?.outcomeId)&&archives.offer&&archives.resolved?.equippedRelicMutations===0,archives);
      const training=await flow('facility.training-grounds',f.saveFixtures.trainingBanked);add('training-unique-presentation-participants-only',training.resumed&&f.activityContent['facility.training-grounds'].outcomeIds.includes(training.resolved?.outcomeId)&&training.offer&&training.resolved?.participantIds?.length===new Set(training.resolved?.participantIds||[]).size&&training.resolved?.actorAvailabilityMutations===0&&training.resolved?.campaignPowerMutations===0,training);
      const hearth=await flow('facility.hearth',f.saveFixtures.hearthBanked);add('hearth-positive-manual-no-preclaim-relationship',hearth.resumed&&f.activityContent['facility.hearth'].outcomeIds.includes(hearth.resolved?.outcomeId)&&hearth.offer&&hearth.resolved?.relationshipApplications===0&&hearth.resolved?.giftApplications===0&&hearth.resolved?.forcedPairing===false,hearth);
      call('destructive','resetFixture',f.saveFixtures.gatehouseBanked);let caravan=bank(call('read','derive'),'facility.gatehouse')[0];call('destructive','begin','facility.gatehouse',caravan.id,caravan.identity);call('destructive','choose','facility.gatehouse',caravan.id,caravan.identity,'incompatible-reception');const reassess=call('destructive','resolve','facility.gatehouse',caravan.id,caravan.identity);add('gatehouse-incompatible-returns-assessment',reassess?.ok===true&&reassess?.returnsTo==='assessment'&&reassess?.consumed===false&&reassess?.rewardApplications===0&&offers(call('read','derive')).length===0,reassess);const gatehouse=await flow('facility.gatehouse',f.saveFixtures.gatehouseBanked);add('gatehouse-valid-caravan-manual',gatehouse.resumed&&f.activityContent['facility.gatehouse'].outcomeIds.includes(gatehouse.resolved?.outcomeId)&&gatehouse.offer,gatehouse);
      call('destructive','resetFixture',f.saveFixtures.workshopBanked);let order=bank(call('read','derive'),'facility.market-workshop')[0],stockBefore=facilityState(call('read','derive'),'facility.market-workshop').stock;call('destructive','begin','facility.market-workshop',order.id,order.identity);const cancel=call('destructive','cancelEngagement','facility.market-workshop',order.id,order.identity),stockAfterCancel=facilityState(call('read','derive'),'facility.market-workshop').stock;add('workshop-cancel-before-commit-restores-stock',cancel?.ok===true&&same(stockBefore,stockAfterCancel)&&cancel?.reservationCount===0,{cancel,stockBefore,stockAfterCancel});const workshop=await flow('facility.market-workshop',f.saveFixtures.workshopBanked);add('workshop-committed-reservation-resumes',workshop.committed?.reservationCount===1&&workshop.resumed&&workshop.offer&&workshop.resolved?.callerQuantityAccepted===false,workshop);
      call('destructive','resetFixture',f.saveFixtures.gardenGrowing);const gardenBefore=call('read','derive'),advanced=call('destructive','advanceGrowth',f.frozenNow+f.syntheticPolicy.gardenGrowthMs),gardenReady=call('read','derive');add('gardens-growth-ready-no-auto-claim-replant',advanced?.ok===true&&advanced?.readyCount===1&&advanced?.claimCount===0&&advanced?.replantCount===0&&advanced?.spoilCount===0&&offers(gardenReady).length===1&&Number(resources(gardenReady).gold||0)===Number(resources(gardenBefore).gold||0),advanced);
      const forge=await flow('facility.forge',f.saveFixtures.forgeBanked);add('forge-existing-relic-stone-adapter-no-advanced-systems',forge.committed?.reservationCount===1&&forge.resumed&&forge.offer&&forge.resolved?.duplicateRelicStoneBalance===false&&forge.resolved?.affixMutations===0&&forge.resolved?.reforgeMutations===0&&forge.resolved?.advancedSetMutations===0,forge);

      call('destructive','resetFixture',f.saveFixtures.claimReadyEach);for(const facility of f.facilities){const current=call('read','derive'),offer=offers(current).find(item=>item.sourceId===facility.activityId),beforeSnapshot=call('read','snapshot'),claim=call('destructive','claim',offer.id,offer.identity),after=call('read','derive'),raw=call('read','raw'),again=call('destructive','claim',offer.id,offer.identity);add(`${facility.facilityId}-finalizer-exact-once`,claim?.ok===true&&revision(call('read','snapshot'))===revision(beforeSnapshot)+1&&claim?.globalApplications===1&&claim?.localApplications===1&&claim?.receiptApplications===1&&again?.ok===false&&again?.writes===0&&call('read','raw')===raw&&receipts(after).at(-1)?.sourceId===facility.activityId,{claim,again})}
      for(const facility of f.facilities)for(const mode of ['missing','throw','local','global','receipt','archive']){const failure=call('destructive','probeFinalizerFailure',facility.activityId,mode);add(`${facility.facilityId}-finalizer-${mode}-atomic-refusal`,failure?.ok===false&&failure?.writes===0&&failure?.partialApplications===0,failure)}
      for(const kind of f.concurrencyKinds){const race=call('destructive','simulateConcurrent',kind);add(`two-client-${kind}-one-winner`,race?.ok===true&&race?.winnerCount===1&&race?.loserCount===1&&race?.losingWrites===0&&race?.duplicateCount===0&&race?.finalValid===true,race)}

      call('destructive','resetFixture',f.saveFixtures.offline);const offline=call('destructive','advanceOffline',{elapsedMs:f.offlineCapMs*2,includeMidnight:true,includeDst:true});add('offline-cap-banks-only-gardens-maturity-only',offline?.ok===true&&offline?.appliedMs===f.offlineCapMs&&offline?.chosenCount===0&&offline?.resolvedCount===0&&offline?.claimedCount===0&&offline?.tutorialCount===0&&offline?.gardenMaturedCount>=0&&offline?.gardenClaimedCount===0&&offline?.gardenReplantedCount===0,offline);
      call('destructive','resetFixture',f.saveFixtures.recovery);const exported=call('read','exportSave'),recovered=call('destructive','reload'),imported=call('destructive','importFixture',exported);add('reload-export-import-recovery-one-authority',recovered?.ok===true&&imported?.ok===true&&call('read','validate')?.ok===true&&imported?.duplicateCount===0,{recovered,imported});
      call('destructive','resetFixture',f.saveFixtures.freshNullPolicy);const invalidRaw=call('read','raw'),invalid=f.invalidMutationKinds.map(kind=>call('destructive','mutateInvalid',kind));add('invalid-and-forbidden-mutations-fail-before-write',invalid.every((item,index)=>item?.ok===false&&item?.check===f.invalidMutationKinds[index]&&item?.writes===0)&&call('read','raw')===invalidRaw,invalid);
      const tutorialRaw=call('read','raw'),tutorial=call('destructive','tutorial',f.tutorialIds[3],'open'),replayed=call('destructive','tutorial',f.tutorialIds[3],'replay');add('tutorial-contextual-nonblocking-neutral',tutorial?.ok===true&&tutorial?.blocking===false&&replayed?.ok===true&&call('read','raw')===tutorialRaw,{tutorial,replayed});
      call('destructive','resetFixture',f.saveFixtures.lockedRoster);const dialogue=call('read','derive')?.dialogue||{},joined=call('read','derive')?.roster?.joinedFellowIds||[];add('locked-fellows-never-speak-and-all-cast-registered',same(sorted(dialogue.allRosterActorIds||[]),sorted(f.allRosterActorIds))&&same(sorted(dialogue.phase20_21ActorIds||[]),sorted(f.phase20_21ActorIds))&&(dialogue.selectedSpeakers||[]).every(id=>!id.startsWith('fellow.')||joined.includes(id)),dialogue);add('dialogue-visual-fallback-only',(dialogue.presentations||[]).every(item=>f.approvedVisualFallbacks.includes(item.mode)&&item.unframedFullPortrait!==true),dialogue.presentations);

      await wait(50);const nav=[...document.querySelectorAll('[data-tab],nav button,[role="navigation"] button')].filter(node=>{const style=getComputedStyle(node);return style.display!=='none'&&style.visibility!=='hidden'}),board=document.querySelector('[data-phase15-facility-board]'),hotspots=f.facilities.map(item=>document.querySelector(`[data-phase15-facility-id="${item.facilityId}"]`)),detached=document.querySelector('[data-detached-building-grid],[data-facility-management-grid]');add('actual-dom-physical-board-eight-hotspots-five-nav',nav.length===5&&Boolean(board)&&hotspots.every(Boolean)&&!detached,{nav:nav.map(node=>node.textContent.trim()),board:Boolean(board),hotspots:hotspots.filter(Boolean).length,detached:Boolean(detached)});
      const targetOk=node=>{const rect=node?.getBoundingClientRect();return Boolean(rect&&rect.width>=44&&rect.height>=44&&rect.left>=0&&rect.right<=innerWidth+1&&rect.top>=0&&rect.bottom<=innerHeight+1)},beforeDomRaw=call('read','raw'),surfaceResults=[];for(let index=0;index<f.facilities.length;index++){const facility=f.facilities[index],hotspot=hotspots[index];if(!hotspot){surfaceResults.push({facilityId:facility.facilityId,ok:false});continue}call('destructive','openFacility',facility.facilityId);hotspot.focus();hotspot.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));hotspot.click();await wait(20);const sheet=document.querySelector(`[data-phase20-21-sheet][data-facility-id="${facility.facilityId}"]`),heading=sheet?.querySelector('h1,h2,[role="heading"]'),controls=[...sheet?.querySelectorAll('button,[role="button"],input,select')||[]],statusText=sheet?.querySelector('[data-facility-status],[role="status"]')?.textContent?.trim();document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(20);surfaceResults.push({facilityId:facility.facilityId,ok:targetOk(hotspot)&&Boolean(sheet)&&Boolean(heading)&&controls.length>=2&&controls.every(node=>node.matches(':disabled')||node.tabIndex>=0)&&Boolean(statusText)&&document.activeElement===hotspot})}add('actual-dom-eight-focused-sheets-keyboard-focus-status',surfaceResults.every(item=>item.ok),surfaceResults);add('actual-dom-open-close-write-neutral',call('read','raw')===beforeDomRaw);add('actual-dom-no-horizontal-overflow',document.documentElement.scrollWidth<=document.documentElement.clientWidth+1&&document.body.scrollWidth<=document.body.clientWidth+1,{viewport:[innerWidth,innerHeight],document:[document.documentElement.clientWidth,document.documentElement.scrollWidth]});
      const passiveAfter=call('read','passiveBaseline',passiveAt);add('original-four-passive-semantics-preserved-after-all-flows',same(passiveAfter,passiveBefore),{before:passiveBefore,after:passiveAfter});add('expansion-remains-opportunity-only',call('read','boardModel')?.facilities?.filter(item=>f.expansionFacilityIds.includes(item.facilityId)).every(item=>item.passiveGold===false&&item.buildingLevel===false&&item.familyAssignment===false),call('read','boardModel'));add('final-state-valid',call('read','validate')?.ok===true,call('read','validate'));add('native-storage-instrumented',window.__P2021I_NATIVE_INSTRUMENTED__===true);add('zero-native-storage-accesses',window.__P2021I_NATIVE_ACCESSES__.length===0,window.__P2021I_NATIVE_ACCESSES__);add('zero-warning-error-console',window.__P2021I_ERRORS__.length===0,window.__P2021I_ERRORS__);send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();if(source.indexOf('<script')<0)throw new Error('Production script tag missing');const styleText=[...source.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)].map(match=>match[1]).join('\n');config.candidateReducedCssContract={hasMediaRule:/@media\s*\(\s*prefers-reduced-motion\s*:\s*reduce\s*\)/i.test(styleText),globalAnimationNone:/\*,\s*\*::?before,\s*\*::?after\s*\{[^}]*animation\s*:\s*none\s*!important/i.test(styleText),globalTransitionNone:/\*,\s*\*::?before,\s*\*::?after\s*\{[^}]*transition\s*:\s*none\s*!important/i.test(styleText)};const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`;source=source.replace('<head>','<head><base href="../../">');const insertion=source.indexOf('<script');source=source.slice(0,insertion)+bootstrap+source.slice(insertion).replace('</body>',suite+'</body>');document.open();document.write(source);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
