import {createHash} from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
import {existsSync,readFileSync,readdirSync,statSync} from 'node:fs';
import {resolve} from 'node:path';

const ROOT=resolve(new URL('../..',import.meta.url).pathname),QA=resolve(ROOT,'qa/phase-20-21-independent'),BASE='fa004195a36dcbcd5be4ad9d73357a63cf50f3f7',PACKAGE_ONLY=process.argv.includes('--package-only');
const EXPECTED=['README.md','checksums.sha256','fixtures/contract-fixtures.json','fixtures/inherited-hashes.json','index.html','realm.html','realm.js','runner.js','verify.mjs'],rows=[],record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),read=item=>readFileSync(resolve(ROOT,item)),text=item=>read(item).toString('utf8'),json=item=>JSON.parse(text(item)),sha=value=>createHash('sha256').update(value).digest('hex'),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),unique=values=>new Set(values).size===values.length,sorted=values=>[...new Set(values)].sort();
const git=args=>execFileSync('/usr/bin/git',args,{cwd:ROOT,encoding:'utf8',maxBuffer:128*1024*1024});
const f=json('qa/phase-20-21-independent/fixtures/contract-fixtures.json'),inherited=json('qa/phase-20-21-independent/fixtures/inherited-hashes.json'),p20=json('design/phase-20-21/phase20-definitions.json'),p21=json('design/phase-20-21/phase21-definitions.json'),integration=json('design/phase-20-21/cross-facility-integration.json'),tutorials=json('design/phase-20-21/tutorial-bindings.json'),cast=json('design/phase-20-21/cast-bindings.json'),designFixtures=json('design/phase-20-21/fixtures.json'),release=json('design/phase-20-21/release-gate.json'),phase14=json('design/phase-14/facility-definitions.json'),unlocks=json('design/phase-17/facility-unlocks.json'),castPlan=json('design/phase-13/cast-plan.json'),tutorialLedger=json('design/phase-13/tutorial-matrix.json');
const ids=items=>items.map(item=>item.id);
function filesBelow(directory,prefix=''){const paths=[];for(const name of readdirSync(directory)){const absolute=resolve(directory,name),item=prefix?`${prefix}/${name}`:name;if(statSync(absolute).isDirectory())paths.push(...filesBelow(absolute,item));else paths.push(item)}return paths.sort()}
function productionSources(){const files=['index.html'];function visit(directory,prefix='src'){for(const entry of readdirSync(directory,{withFileTypes:true})){const item=`${prefix}/${entry.name}`,absolute=resolve(directory,entry.name);if(entry.isDirectory())visit(absolute,item);else if(/\.(?:html|m?js|json)$/.test(item))files.push(item)}}visit(resolve(ROOT,'src'));return files.sort()}
function nullOperational(facility){return Object.values(facility.operational).every(value=>value===null)}

record('base-commit-reachable',git(['merge-base','--is-ancestor',BASE,'HEAD'])==='');
record('package-topology',same(filesBelow(QA),EXPECTED),filesBelow(QA));
const checksumRows=existsSync(resolve(QA,'checksums.sha256'))?text('qa/phase-20-21-independent/checksums.sha256').trim().split('\n').filter(Boolean).map(line=>{const match=line.match(/^([0-9a-f]{64})  (.+)$/);return match?{expected:match[1],item:match[2]}:null}):[],checksumFailures=checksumRows.filter(item=>!item||!existsSync(resolve(ROOT,item.item))||sha(read(item.item))!==item.expected).map(item=>item?.item||'malformed');record('package-checksums',checksumRows.length===10&&checksumFailures.length===0,{count:checksumRows.length,failures:checksumFailures});
record('contract-and-result-documents',['docs/PHASE_20_21_INDEPENDENT_QA_CONTRACT.md','docs/PHASE_20_21_INDEPENDENT_QA_RESULT.md'].every(item=>existsSync(resolve(ROOT,item))));
const contract=text('docs/PHASE_20_21_INDEPENDENT_QA_CONTRACT.md'),contractLower=contract.toLowerCase();
record('contract-qa-only-real-candidate',['does not implement or emulate a production facility engine','exact base intentionally has no Phase 20/21 runtime','never installs a fake facility runtime'].every(value=>contract.includes(value)));
record('contract-phase20-four-distinct',['Command Center','Archives','Training Grounds','Hearth','commandPetitionFinalizerV1','archivesResearchFinalizerV1','trainingDrillFinalizerV1','hearthGatheringFinalizerV1'].every(value=>contract.includes(value)));
record('contract-phase21-four-distinct',['Gatehouse','Market/Workshop','Gardens','Forge','gatehouseCaravanFinalizerV1','workshopOrderFinalizerV1','gardensHarvestFinalizerV1','forgeCommissionFinalizerV1'].every(value=>contract.includes(value)));
record('contract-passive-and-expansion-boundary',['passive Gold production','Family assignment','Fellows never staff Buildings','opportunity-only expansion','not passive Buildings'].every(value=>contract.includes(value)));
record('contract-bank-offline-claim',['banks deterministically','never expires','manual offer','Gardens alone may advance','may not harvest, claim, replant, or spoil','zero partial effects'].every(value=>contract.includes(value)));
record('contract-story-tutorial-cast',['exactly 19 existing ids','45 accepted hooks across 28 current actors','all 18 fellows and 20 family','locked fellows never speak','profile quote and ambient village-comment role'].every(value=>contractLower.includes(value)));
record('contract-physical-mobile-original',['no detached building-management grid','bottom navigation remains exactly five items','320×568','390×844','original everstead writing','may not ingest or imitate reference-game assets'].every(value=>contractLower.includes(value)));
record('contract-forbidden-complete',['facility stamina','new global facility currency','Family Blessing track','Fellow Building staffing','duplicate Relic Stone balance','Garden spoilage/auto-replant','advanced Forge affixes/reforging/sets','copied reference-game assets or trade dress'].every(value=>contract.includes(value)));

record('fixture-provenance',f.contractVersion===1&&f.bridgeVersion==='phase-20-21-independent-qa-v1'&&f.baseCommit===BASE&&f.schemaVersion===12);
record('fixture-eight-facilities-exact',f.facilities.length===8&&f.facilities.filter(item=>item.phase===20).length===4&&f.facilities.filter(item=>item.phase===21).length===4&&unique(f.facilities.map(item=>item.facilityId))&&unique(f.facilities.map(item=>item.activityId))&&unique(f.facilities.map(item=>item.opportunityId))&&unique(f.facilities.map(item=>item.finalizerId)));
record('fixture-eight-domain-content-sets',Object.keys(f.activityContent).length===8&&f.facilities.every(item=>f.activityContent[item.facilityId]?.templateIds.length===3&&f.activityContent[item.facilityId]?.choiceCount>=3&&f.activityContent[item.facilityId]?.outcomeIds.length>=1));
record('fixture-phase20-vs-phase21-policy',f.facilities.filter(item=>item.phase===20).every(item=>item.passivePolicy==='preserve-existing-building-production-and-family-assignment')&&f.facilities.filter(item=>item.phase===21).every(item=>item.passivePolicy==='opportunity-only-acceleration'));
record('fixture-tutorial-and-cast-cardinality',f.tutorialIds.length===19&&f.phase20_21ActorIds.length===28&&f.allRosterActorIds.length===38&&f.hookCount===45&&f.integrationHookCount===10&&unique(f.tutorialIds)&&unique(f.allRosterActorIds));
record('fixture-qa-only-policy',f.syntheticPolicy.qaOnly===true&&f.syntheticPolicy.requiresIsolatedStorage===true&&f.syntheticPolicy.neverProductionFallback===true&&unique(Object.values(f.syntheticPolicy.intervalMsByFacility))&&unique(Object.values(f.syntheticPolicy.baseRewardGoldByFacility)));
record('fixture-risk-and-forbidden-matrices',Object.keys(f.saveFixtures).length===21&&f.concurrencyKinds.length===21&&f.invalidMutationKinds.length===29&&f.forbiddenSystems.length===17&&unique(f.concurrencyKinds)&&unique(f.invalidMutationKinds)&&unique(f.forbiddenSystems));
record('fixture-migration-archive-offline',same(f.migrations,['migration.phase-20.original-four-active.v1','migration.phase-21.expansion-facilities.v1'])&&same(f.archivePolicy,{configId:'claim-archive.phase-15.v1',recentReceiptLimit:512,foldBatchSize:128,expectedRecentAfterNextClaim:385,expectedThroughAfterNextClaim:128})&&f.offlineCapMs===86400000);
record('fixture-five-realms-and-fifteen-boundaries',f.viewports.length===5&&f.viewports.some(item=>item.width===320&&item.height===568)&&f.viewports.some(item=>item.width===390&&item.height===844)&&f.viewports.some(item=>item.width===1024&&item.height===768)&&f.viewports.some(item=>item.copyScale===1.3)&&f.viewports.some(item=>item.reducedMotion)&&f.expectedCandidateFailureIds.length===15&&unique(f.expectedCandidateFailureIds));

const p20ById=new Map(p20.facilities.map(item=>[item.id,item])),p21ById=new Map(p21.facilities.map(item=>[item.id,item])),p20Opp=new Map(p20.opportunityDefinitions.map(item=>[item.id,item])),p21Opp=new Map(p21.opportunityDefinitions.map(item=>[item.id,item]));
record('design-config-identities',p20.configId===f.configs.phase20&&p20.definitionSetId===f.configs.phase20Definitions&&p21.configId===f.configs.phase21&&p21.definitionSetId===f.configs.phase21Definitions&&integration.configId===f.configs.integration&&integration.definitionSetId===f.configs.integrationDefinitions);
record('design-exact-eight-facility-references',f.facilities.every(item=>{const actual=(item.phase===20?p20ById:p21ById).get(item.facilityId),opp=(item.phase===20?p20Opp:p21Opp).get(item.opportunityId);return actual?.activityId===item.activityId&&actual?.opportunityDefinitionId===item.opportunityId&&actual?.mapAnchor===item.anchor&&actual?.capabilityId===item.capabilityId&&actual?.storyDiscoveryContentId===item.discoveryId&&actual?.openingContentId===item.openingId&&actual?.localProgressTrackId===item.progressId&&opp?.activityId===item.activityId&&opp?.interactionKind===item.interaction&&opp?.expires===false&&opp?.claimMode==='manual'}));
record('design-original-four-passive-exact',p20.passiveBoundary.policy==='Active facility state is additive and cannot gate or mutate the released passive Building system.'&&p20.facilities.every(item=>item.passivePolicy==='preserve-existing-building-production-and-family-assignment')&&f.originalPassiveFacilityIds.every(id=>p20ById.has(id)));
record('design-expansion-opportunity-only',f.expansionFacilityIds.every(id=>p21ById.has(id)&&unlocks.facilityUnlocks.find(item=>item.facilityId===id)?.passivePolicy==='facility-opportunity-only'));
record('design-all-operational-null-disabled',p20.productionEnabled===false&&p21.productionEnabled===false&&p20.facilities.every(nullOperational)&&p21.facilities.every(nullOperational)&&p20.presentationPolicy.enablementStatus==='blocked-art'&&p21.presentationPolicy.enablementStatus==='blocked-art');
record('design-command-bounded-choice',ids(p20.commandCenter.petitionTemplates).length===3&&p20.commandCenter.choicePolicy.hiddenPermanentBranches===false&&p20.commandCenter.choicePolicy.mechanicalDivergence===null&&p20.commandCenter.choicePolicy.rewardByChoiceId===null);
record('design-archives-reconstruction-safe',ids(p20.archives.researchLeads).length===3&&p20.archives.reconstructionPolicy.invalidSelectionReturnsToResearch===true&&p20.archives.reconstructionPolicy.relicMutationAllowed===false);
record('design-training-presentation-only',ids(p20.trainingGrounds.drills).length===3&&p20.trainingGrounds.participantPolicy.duplicateActorAllowed===false&&p20.trainingGrounds.participantPolicy.consumesActorAvailability===false&&p20.trainingGrounds.participantPolicy.campaignOrTowerPowerMutation===false&&p20.trainingGrounds.participantPolicy.presentationSquadOnly===true);
record('design-hearth-relationship-safe',ids(p20.hearth.gatherings).length===3&&p20.hearth.attendeePolicy.duplicateActorAllowed===false&&p20.hearth.attendeePolicy.romanceChecklist===false&&p20.hearth.attendeePolicy.forcedPairing===false&&p20.hearth.attendeePolicy.consumesRelationship===false&&p20.hearth.relationshipPolicy.claimTimeDeterministicRoll===true);
record('design-gatehouse-forgiving',ids(p21.gatehouse.caravanTemplates).length===3&&p21.gatehouse.resolutionPolicy.invalidCombinationReturnsToAssessment===true&&p21.gatehouse.resolutionPolicy.hiddenPermanentBranch===false);
record('design-workshop-reservation-safe',ids(p21.marketWorkshop.orders).length===3&&p21.marketWorkshop.reservationPolicy.reserveAtEngagement===true&&p21.marketWorkshop.reservationPolicy.cancelBeforeCommitRestoresStock===true&&p21.marketWorkshop.reservationPolicy.closeAfterCommitPreservesEngagement===true&&p21.marketWorkshop.reservationPolicy.callerSuppliedQuantityAllowed===false);
record('design-gardens-nonspoiling-manual',ids(p21.gardens.crops).length===3&&p21.gardens.growthPolicy.offlineMayAdvanceToReady===true&&p21.gardens.growthPolicy.offlineMayClaim===false&&p21.gardens.growthPolicy.harvestExpires===false&&p21.gardens.growthPolicy.spoilage===false&&p21.gardens.growthPolicy.autoReplant===false);
record('design-forge-existing-system-only',ids(p21.forge.commissions).length===3&&p21.forge.reservationPolicy.callerSuppliedQuantityAllowed===false&&p21.forge.masteryPolicy.advancedAffixes===false&&p21.forge.masteryPolicy.reforging===false&&p21.forge.masteryPolicy.advancedRelicSets===false);
record('design-integrations-ten-disabled-positive',integration.productionEnabled===false&&integration.hooks.length===10&&unique(ids(integration.hooks))&&integration.globalRules.positiveOnly===true&&integration.globalRules.offlineAutoConsumption===false&&integration.globalRules.autoClaim===false&&integration.globalRules.crossFacilityFormula===null&&integration.globalRules.crossFacilityCap===null);
record('design-nineteen-tutorials-ledger-resolve',tutorials.sourceLedgerCount===79&&same(tutorials.bindings.map(item=>item.tutorialId),f.tutorialIds)&&f.tutorialIds.every(id=>tutorialLedger.tutorials.some(item=>item.id===id))&&tutorials.bindings.every(item=>item.stepSegments.length>=1));
const rosterLookup=new Map([...castPlan.fellows.map(item=>[item.id,`fellow.${item.id}`]),...castPlan.family.map(item=>[item.id,`family.${item.id}`])]),facilityActorIds=sorted(cast.facilityBindings.flatMap(binding=>binding.hookIds.map(id=>rosterLookup.get(id.split('.')[3]))));
record('design-cast-45-hooks-28-actors',cast.facilityBindings.length===8&&cast.facilityBindings.reduce((sum,item)=>sum+item.hookIds.length,0)===45&&same(facilityActorIds,sorted(f.phase20_21ActorIds))&&cast.presentationPolicy.includes('unframed full-background profile art is forbidden'));
record('design-all-38-primary-roster-preserved',castPlan.fellows.length===18&&castPlan.family.length===20&&same([...castPlan.fellows.map(item=>`fellow.${item.id}`),...castPlan.family.map(item=>`family.${item.id}`)],f.allRosterActorIds));
record('design-release-gates-all-blocked',release.productionReleaseAllowed===false&&release.gates.length===27&&unique(ids(release.gates))&&release.gates.every(item=>item.required===true&&item.status==='blocked'&&item.evidence===null));
record('design-72-risk-fixtures',designFixtures.productionEnabled===false&&designFixtures.fixtures.length===72&&unique(ids(designFixtures.fixtures))&&['migration','non-expiry','offline','multi-tab','mobile','reduced-motion','corruption','claim'].every(category=>designFixtures.fixtures.some(item=>item.category===category)));
record('phase14-no-stamina-currency-daily-reset',text('design/phase-14/PHASE_14_FACILITY_CONTRACT.md').includes('Do not add facility stamina, expiring tickets, daily resets, or a global facility currency.'));
const designRun=spawnSync('/usr/bin/python3',['design/phase-20-21/validate.py'],{cwd:ROOT,encoding:'utf8'});record('accepted-design-validator-41-of-41',designRun.status===0&&designRun.stdout.includes('SUMMARY 41/41 checks; 8 facilities; 8 opportunity definitions; 10 integrations; 19 tutorials; 45 hooks/28 actors; 27 release gates; 72 fixtures'),designRun.stdout.trim().split('\n').at(-1));
const frozenDesignFailures=Object.entries(inherited.files).filter(([item,expected])=>!item.startsWith('index.html')&&!item.startsWith('src/')&&sha(read(item))!==expected).map(([item])=>item);record('accepted-design-and-predecessor-qa-byte-frozen',inherited.baseCommit===BASE&&Object.keys(inherited.files).length===18&&frozenDesignFailures.length===0,{count:Object.keys(inherited.files).length,failures:frozenDesignFailures});

const realmSource=text('qa/phase-20-21-independent/realm.js');record('runner-isolated-fail-closed',realmSource.includes('allowDestructive:true')&&realmSource.includes('isolatedStorage:true')&&realmSource.includes('phase20-21-contract-unavailable')&&realmSource.includes('if(!qa){')&&!realmSource.includes('fakeEngine'));record('runner-loads-real-candidate',realmSource.includes("fetch('../../index.html'")&&realmSource.includes('document.write(source)')&&realmSource.includes('__EVERSTEAD_PHASE_20_21_QA__'));record('runner-actual-dom-nontautological-motion',['document.querySelector','getBoundingClientRect','getComputedStyle','document.activeElement','sheet?.contains(document.activeElement)','actual-dom-eight-single-hotspot-activation-focus-entry-return','scrollWidth','candidateReducedCssContract','data-everstead-reduced-motion'].every(value=>realmSource.includes(value))&&!realmSource.includes("call('destructive','openFacility'"));record('runner-phase20-behavior-coverage',['command-petition-choice-recorded-manual','archives-invalid-reconstruction-returns-unconsumed','training-unique-presentation-participants-only','hearth-positive-manual-no-preclaim-relationship'].every(value=>realmSource.includes(value)));record('runner-phase21-behavior-coverage',['gatehouse-incompatible-returns-assessment','workshop-cancel-before-commit-restores-stock','gardens-growth-ready-no-auto-claim-replant','forge-existing-relic-stone-adapter-no-advanced-systems'].every(value=>realmSource.includes(value)));record('runner-shared-risk-coverage',['finalizer-${mode}-atomic-refusal','two-client-${kind}-one-winner','offline-cap-banks-only-gardens-maturity-only','invalid-and-forbidden-mutations-fail-before-write','representative-active-flows-preserve-passive-within-fixture','tutorial-contextual-nonblocking-mechanically-neutral','tutorialChanges.every','expansion-remains-opportunity-only','actual-dom-physical-board-eight-hotspots-five-nav'].every(value=>realmSource.includes(value)));
for(const item of ['verify.mjs','runner.js','realm.js']){const run=spawnSync(process.execPath,['--check',`qa/phase-20-21-independent/${item}`],{cwd:ROOT,encoding:'utf8'});record(`syntax-${item}`,run.status===0,run.stderr.trim())}

if(PACKAGE_ONLY){const artifact=read('index.html');record('exact-frozen-base-artifact',sha(artifact)===inherited.files['index.html']&&artifact.length===1213721,{sha256:sha(artifact),byteLength:artifact.length});record('base-has-phase15-no-phase20-21',artifact.includes(Buffer.from('__EVERSTEAD_PHASE_15_QA__'))&&!artifact.includes(Buffer.from('__EVERSTEAD_PHASE_20_21_QA__')))}else{
  const paths=productionSources(),combined=paths.map(item=>text(item)).join('\n'),hasBridge=combined.includes('__EVERSTEAD_PHASE_20_21_QA__')&&combined.includes(f.bridgeVersion),candidate=[];
  candidate.push(['candidate-phase20-21-bridge-contract',hasBridge&&combined.includes('allowDestructive')&&combined.includes('isolatedStorage')&&combined.includes('NATIVE_STORAGE')]);
  candidate.push(['candidate-predecessor-finalizer-v2-seams',hasBridge&&combined.includes(f.predecessor.facilityFrameworkConfigId)&&combined.includes(f.predecessor.archiveConfigId)&&combined.includes(f.predecessor.storyRegistryId)&&combined.includes('immutableFinalizer')]);
  candidate.push(['candidate-eight-config-registry-runtime',hasBridge&&Object.values(f.configs).every(id=>combined.includes(id))&&f.facilities.every(item=>combined.includes(item.facilityId)&&combined.includes(item.activityId)&&combined.includes(item.opportunityId)&&combined.includes(item.finalizerId))]);
  candidate.push(['candidate-command-petition-runtime',hasBridge&&['command.petition.shared-road-use','command.choice.shared-road.scheduled','command.outcome.recorded','chooseResolution'].every(value=>combined.includes(value))]);
  candidate.push(['candidate-archives-research-runtime',hasBridge&&['archives.lead.faded-road-map','archives.outcome.documented','invalidSelectionReturnsToResearch','reconstructEvidence'].every(value=>combined.includes(value))]);
  candidate.push(['candidate-training-drill-runtime',hasBridge&&['training.drill.controlled-spar','training.outcome.completed','presentationSquadOnly','campaignOrTowerPowerMutation'].every(value=>combined.includes(value))]);
  candidate.push(['candidate-hearth-gathering-runtime',hasBridge&&['hearth.gathering.shared-table','hearth.outcome.warm','claimTimeDeterministicRoll','forcedPairing'].every(value=>combined.includes(value))]);
  candidate.push(['candidate-gatehouse-event-runtime',hasBridge&&['gatehouse.caravan.river-merchants','gatehouse.outcome.welcomed','invalidCombinationReturnsToAssessment'].every(value=>combined.includes(value))]);
  candidate.push(['candidate-workshop-order-runtime',hasBridge&&['workshop.order.road-repair-kit','workshop.outcome.fulfilled','reserveAtEngagement','cancelBeforeCommitRestoresStock'].every(value=>combined.includes(value))]);
  candidate.push(['candidate-gardens-cultivation-runtime',hasBridge&&['gardens.crop.road-herbs','gardens.outcome.harvest','offlineMayAdvanceToReady','autoReplant'].every(value=>combined.includes(value))]);
  candidate.push(['candidate-forge-commission-runtime',hasBridge&&['forge.commission.village-toolwork','forge.outcome.completed','forge.stock.relic-stones','duplicateRelicStoneBalance'].every(value=>combined.includes(value))]);
  candidate.push(['candidate-migration-offline-concurrency-archive-runtime',hasBridge&&f.migrations.every(id=>combined.includes(id))&&combined.includes('simulateConcurrent')&&combined.includes('advanceOffline')&&combined.includes(f.archivePolicy.configId)]);
  candidate.push(['candidate-story-tutorial-cast-runtime',hasBridge&&f.tutorialIds.every(id=>combined.includes(id))&&f.phase20_21ActorIds.every(id=>combined.includes(id))&&combined.includes('allRosterActorIds')&&combined.includes('lockedFellowsExcluded')]);
  candidate.push(['candidate-physical-board-dom-runtime',hasBridge&&f.facilities.every(item=>combined.includes(`data-phase15-facility-id="${item.facilityId}"`)||combined.includes(item.facilityId))&&combined.includes('data-phase20-21-sheet')&&combined.includes('data-everstead-reduced-motion')&&combined.includes('bottomNavigationCount')]);
  candidate.push(['candidate-forbidden-systems-runtime',hasBridge&&combined.includes('forbiddenSystemReport')&&f.forbiddenSystems.every(id=>combined.includes(id))&&combined.includes('originalEversteadOnly')&&combined.includes('referenceTradeDressCopied')]);
  for(const [id,pass] of candidate)record(id,pass,paths);record('candidate-failure-boundaries-exact',same(candidate.filter(([,pass])=>!pass).map(([id])=>id),f.expectedCandidateFailureIds),candidate.filter(([,pass])=>!pass).map(([id])=>id));
}

const owned=item=>['docs/PHASE_20_21_INDEPENDENT_QA_CONTRACT.md','docs/PHASE_20_21_INDEPENDENT_QA_RESULT.md'].includes(item)||item.startsWith('qa/phase-20-21-independent/'),commits=git(['log','--format=%H',`${BASE}..HEAD`,'--','docs/PHASE_20_21_INDEPENDENT_QA_CONTRACT.md','docs/PHASE_20_21_INDEPENDENT_QA_RESULT.md','qa/phase-20-21-independent']).trim().split('\n').filter(Boolean),violations=[];for(const commit of commits)for(const item of git(['diff-tree','--root','--no-commit-id','--name-only','-r',commit]).trim().split('\n').filter(Boolean))if(!owned(item))violations.push({commit,item});record('committed-qa-paths-owned',commits.length>=1&&violations.length===0,{commits,violations});
const passed=rows.filter(row=>row.pass).length,failed=rows.length-passed;for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` — ${row.detail}`:''}`);console.log(`RESULT ${passed} passed, ${failed} failed`);process.exitCode=failed?1:0;
