(()=>{
  'use strict';
  const CHANNEL='everstead-phase-24a-scaling-authority-v1',byId=id=>document.getElementById(id),escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),row=(id,actual,detail='')=>({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)});
  async function loadJson(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.json()}
  function realm(contract,viewport){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),config={channel:CHANNEL,nonce,contract,viewport};frame.name=JSON.stringify(config);frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0`;let timer;const finish=(error,value)=>{clearTimeout(timer);removeEventListener('message',receive);frame.remove();error?reject(error):resolve(value)},receive=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=(event.data.results||[]).map(item=>({...item,id:`${viewport.id}-${item.id}`}));if(event.data.errors?.length)rows.push(row(`${viewport.id}-captured-errors`,false,event.data.errors.join('\n')));finish(null,rows)};timer=setTimeout(()=>finish(new Error(`${viewport.id} realm timed out`)),120000);addEventListener('message',receive);frame.src=`./realm.html?qa=1&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  function render(mode,rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('mode').textContent=mode;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)} · observed ${item.actual?'true':'false'} · expected true${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_24A_RESULT__={mode,passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const contract=await loadJson('./fixtures/contract.json'),rows=[];rows.push(row('fixture-contract-v1',contract.contractVersion===1&&contract.phase==='24A'&&contract.schemaVersion===13));rows.push(row('fixture-exact-authority-identity',contract.authority.version===1&&contract.authority.configId==='everstead-scaling-live-baseline.phase-24a.v1'&&contract.authority.status==='live-baseline-only'));rows.push(row('fixture-exact-three-profile-order',contract.profiles.map(item=>item.id).join(',')==='phase24a.fresh.schema13.v1,phase24a.migrated-established.schema13.v1,phase24a.true-high-investment.schema13.v1'));rows.push(row('fixture-exact-fresh-phase23-baseline',contract.fresh.fellowEconomyPower===35150&&contract.fresh.fellowCombatPower===35565&&contract.fresh.companionActualRosterPower===2200&&contract.fresh.totalGoldPerHour===27320.8092192));rows.push(row('fixture-migrated-historical-anchor',contract.historicalAnchors.freshlyMigratedSchema12.fellowCombatPower===36366&&contract.historicalAnchors.freshlyMigratedSchema12.migrationProtectionDelta===801));rows.push(row('fixture-collection-reserved-inactive',contract.authority.collectionEffect==='reserved-inactive'));rows.push(row('fixture-four-accessibility-realms',contract.viewports.length===4&&contract.viewports.some(item=>item.copyScale===1.3)&&contract.viewports.some(item=>item.reducedMotion===true)));for(const viewport of contract.viewports)rows.push(...await realm(contract,viewport));render('CANDIDATE',rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render('FATAL',[row('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
