import {readFileSync,existsSync,readdirSync,statSync} from 'node:fs';
import {resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';

const ROOT=resolve(fileURLToPath(new URL('../../',import.meta.url))),PACKAGE_ONLY=process.argv.includes('--package-only'),rows=[];
const rel=path=>resolve(ROOT,path),text=path=>readFileSync(rel(path),'utf8'),json=path=>JSON.parse(text(path)),record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail}),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),sha=path=>createHash('sha256').update(readFileSync(rel(path))).digest('hex');
const checksumFailures=path=>text(path).trim().split(/\r?\n/).filter(Boolean).flatMap(line=>{const match=/^([0-9a-f]{64})  (.+)$/.exec(line);return!match||!existsSync(rel(match?.[2]||''))||sha(match[2])!==match[1]?[match?.[2]||line]:[]});
const f=json('qa/phase-24a-scaling-authority/fixtures/contract.json'),realm=text('qa/phase-24a-scaling-authority/realm.js'),runner=text('qa/phase-24a-scaling-authority/runner.js'),index=text('qa/phase-24a-scaling-authority/index.html');

record('contract-phase24a-schema13-baseline-only',f.contractVersion===1&&f.phase==='24A'&&f.schemaVersion===13&&f.authority.configId==='everstead-scaling-live-baseline.phase-24a.v1'&&f.authority.status==='live-baseline-only');
record('contract-exact-three-profile-order',same(f.profiles.map(item=>item.id),['phase24a.fresh.schema13.v1','phase24a.migrated-established.schema13.v1','phase24a.true-high-investment.schema13.v1'])&&same(f.profiles.map(item=>item.kind),['canonical-fresh','canonical-migrated-established','canonical-true-high-investment'])&&same(f.profiles.map(item=>item.migrationFloorApplied),[false,true,false]));
record('contract-exact-true-fresh-and-migrated-anchor',f.fresh.fellowEconomyPower===35150&&f.fresh.fellowCombatPower===35565&&f.fresh.companionActualRosterPower===2200&&f.fresh.companionEffectiveThresholdRosterPower===2200&&f.fresh.fellowRosterBps===390&&f.fresh.companionRosterBps===80&&f.fresh.totalGoldPerHour===27320.8092192&&Object.values(f.fresh.buildings).reduce((sum,row)=>sum+row.rate,0)===f.fresh.totalGoldPerHour&&same(f.historicalAnchors.freshlyMigratedSchema12,{fellowCombatPower:36366,trueFreshFellowCombatPower:35565,migrationProtectionDelta:801,companionActualRosterPower:2200,protectedFellowIds:['cael','orin']}));
record('contract-true-high-member-rounding-is-output-preserving',f.trueHigh.companionActualRosterPower===50355&&f.trueHigh.companionAggregateUnroundedPower===50358&&f.trueHigh.memberLevel===100&&f.trueHigh.memberRarity===5&&f.trueHigh.masteryLevel===50&&f.trueHigh.persisted===false);
record('contract-true-high-exact-offline-and-claim-authority',f.trueHigh.pendingOffline.villageGold.pendingAfter===923019963.6103376&&f.trueHigh.pendingOffline.companionTower.intervals===24&&f.trueHigh.pendingOffline.fellowExpedition.intervals===24&&f.trueHigh.pendingOffline.restaurant.intervals===12&&f.trueHigh.pendingOffline.apothecary.intervals===8&&f.trueHigh.pendingOffline.schoolhouse.intervals===8&&f.trueHigh.claimState.readyClaimCount===6&&f.trueHigh.claimState.pendingOpportunityCount===28&&f.trueHigh.claimState.byLane.villageGold.claimableGold===923019963&&f.trueHigh.claimState.byLane.companionTower.masteryNominal===120&&f.trueHigh.claimState.byLane.companionTower.masteryAwarded===0&&f.trueHigh.claimState.byLane.fellowExpedition.mightNominal===600&&f.trueHigh.claimState.byLane.fellowExpedition.mightAwarded===0);
record('contract-pure-facility-preview-exact-full-bank',f.trueHigh.facilityPreview.apothecary.settlement.createdCount===8&&f.trueHigh.facilityPreview.apothecary.settlement.appliedMs===86400000&&f.trueHigh.facilityPreview.apothecary.intervalMs===3600000&&f.trueHigh.facilityPreview.schoolhouse.settlement.createdCount===8&&f.trueHigh.facilityPreview.schoolhouse.settlement.appliedMs===86400000&&f.trueHigh.facilityPreview.schoolhouse.intervalMs===5400000);
record('contract-exact-active-baseline-values',same(f.active.building,{baseRates:{training:7200,command:6500,archives:5600,hearth:6100},levelMultiplier:1.15,levelCap:52,upgradeBase:15000,upgradeGrowth:1.24,oathDailyCapBps:3000})&&f.active.fellow.levelPowerGrowthBps===1150&&f.active.fellow.rarityPowerGrowthBps===800&&f.active.companion.levelPowerGrowthBps===1000&&f.active.companion.rarityPowerGrowthBps===1000&&f.active.companion.transferBps===4000&&f.active.economyRoster.fellow.kneePower===100000&&f.active.economyRoster.companion.kneePower===25000);
record('contract-exact-formula-order-separation',f.formulaOrder.fellowEconomy.join(',')==='basePower,levelMultiplier,rarityMultiplier,relicMultiplier,globalMightMultiplier,round'&&f.formulaOrder.fellowCombat.includes('migrationTransferFloor')&&f.formulaOrder.fellowCombatMemberBase.join(',')==='basePower,levelMultiplier,rarityMultiplier,bondMilestoneMultiplier,relicMultiplier,companionPowerTransfer,familyBondMultiplier,globalMightMultiplier,round'&&f.formulaOrder.fellowCombatMemberMigrated.at(-2)==='migrationTransferFloor'&&!f.formulaOrder.fellowEconomy.includes('companionPowerTransfer')&&!f.formulaOrder.fellowEconomy.includes('familyBondMultiplier')&&f.formulaOrder.companionActual.at(-1)==='sum-rounded-members'&&f.formulaOrder.companionThreshold.join(',')==='actualRosterPower,migrationFloorRosterPower,max');
record('contract-legacy-only-values-and-collection-inactive',same(f.legacyOnly,[{id:'legacy-building-upgrade-growth',value:1.7,active:false,appliesToReports:false,scope:'schema-0-through-10-predecessor-only'},{id:'legacy-companion-base-power',value:{bramble:1000,cinderwing:1200},active:false,appliesToReports:false,scope:'schema-12-migration-predecessor-only'}])&&f.authority.collectionEffect==='reserved-inactive');
record('contract-four-mobile-accessibility-realms',f.viewports.length===4&&f.viewports.some(item=>item.width===320&&item.height===568)&&f.viewports.some(item=>item.copyScale===1.3)&&f.viewports.some(item=>item.reducedMotion===true)&&f.minimumTouchTargetPx===44);
record('contract-frozen-generated-artifact-authority',/^[0-9a-f]{64}$/.test(f.generatedArtifacts.balanceReportJsonSha256)&&/^[0-9a-f]{64}$/.test(f.generatedArtifacts.balanceReportMarkdownSha256)&&/^[0-9a-f]{64}$/.test(f.generatedArtifacts.recipeSha256)&&same(Object.keys(f.generatedArtifacts.productionSourceSha256),['index.html','src/phase18-19-runtime.js','src/phase23-companion-runtime.js','src/phase24-scaling-authority.js']));
record('runner-real-isolated-candidate-and-read-only-bridge',realm.includes("fetch('../../index.html'")&&realm.includes('__EVERSTEAD_PHASE_23_QA__')&&realm.includes('EVERSTEAD_PHASE24_SCALING')&&realm.includes("read('scalingDefinitions')")&&realm.includes("read('scalingReport'")&&realm.includes("read('scalingProfileState'")&&realm.includes("read('scalingPreviewSettlement'")&&!realm.includes("destructive','")&&!realm.includes('fakeEngine'));
record('runner-independent-formula-recalculation',['basePower*row.levelMultiplier*row.rarityMultiplier*row.masteryMultiplier','basePower*row.levelMultiplier*row.rarityMultiplier*row.relicMultiplier*row.globalMightMultiplier','row.companionPowerTransfer','row.familyBondMultiplier','row.base*row.levelMultiplier*row.familyAssignmentMultiplier','Math.max(report?.companion?.actualRosterPower','BigInt(config.numeratorBps)*BigInt(power)'].every(value=>realm.includes(value)));
record('runner-exact-profile-floor-collection-safe-contracts',['fresh-exact-phase23-output-preserved','migrated-floor-and-true-high-are-distinct-real-profiles','historicalAnchors','migrationComparison','floor-collection-safe','collections-reserved-inactive-in-authority','unknown-profile-fails-closed'].every(value=>realm.includes(value)));
record('runner-exact-pending-claim-pure-preview-contracts',['fresh-detached-schema13-state-validates','migrated-established-detached-schema13-state-authenticated-and-valid','true-high-is-explicit-detached-nonimportable-report-state','true-high-exact-pending-offline-policy-and-conservation','true-high-exact-manual-claim-state-including-cap-awards','pure-preview-apothecary-exact-full-bank','pure-preview-schoolhouse-exact-full-bank','pure-previews-do-not-mutate-supplied-detached-state','pure-preview-invalid-id-time-fails-closed'].every(value=>realm.includes(value)));
record('runner-zero-state-save-write-native-drift',['all-read-calls-zero-gameplay-save-write-drift','diagnostic-traversal-zero-gameplay-save-write-drift','zero-native-storage-accesses','zero-warning-error-console','__P24A_WRITES__'].every(value=>realm.includes(value)));
record('runner-visible-mobile-accessible-diagnostics',['data-phase24-scaling-open','data-phase24-scaling-dialog','data-phase24-profile-id','data-phase24-scaling-report','data-phase24-formula','data-phase24-scaling-close','diagnostic-mobile-copy-motion-overflow-safe','diagnostic-escape-returns-focus'].every(value=>realm.includes(value)));
record('browser-page-autostarts-and-publishes',runner.includes('run();')&&runner.includes('__EVERSTEAD_PHASE_24A_RESULT__')&&index.includes('Phase 24A · Scaling-authority gate'));
for(const file of ['runner.js','realm.js','verify.mjs']){const checked=spawnSync(process.execPath,['--check',`qa/phase-24a-scaling-authority/${file}`],{cwd:ROOT,encoding:'utf8'});record(`syntax-${file}`,checked.status===0,checked.stderr.trim())}

const checksumPath='qa/phase-24a-scaling-authority/checksums.sha256';if(existsSync(rel(checksumPath))){const checksumRows=text(checksumPath).trim().split(/\r?\n/).filter(Boolean),bad=[];for(const line of checksumRows){const match=/^([0-9a-f]{64})  (.+)$/.exec(line);if(!match||!existsSync(rel(match?.[2]||''))||sha(match[2])!==match[1])bad.push(line)}record('package-checksums-exact',bad.length===0&&checksumRows.length===7,bad)}else record('package-checksums-exact',false,'checksums.sha256 missing');
record('contract-and-result-documents-present',existsSync(rel('docs/PHASE_24A_SCALING_AUTHORITY_QA_CONTRACT.md'))&&existsSync(rel('docs/PHASE_24A_SCALING_AUTHORITY_QA_RESULT.md')));

if(!PACKAGE_ONLY){
  const sourcePath='src/phase24-scaling-authority.js',source=existsSync(rel(sourcePath))?text(sourcePath):'',candidate=text('index.html'),phase1819=text('src/phase18-19-runtime.js'),phase23Runtime=text('src/phase23-companion-runtime.js'),previewStart=phase1819.indexOf('function previewSettlement'),previewEnd=phase1819.indexOf('function definitions',previewStart),previewBody=previewStart<0||previewEnd<0?'':phase1819.slice(previewStart,previewEnd);
  record('candidate-source-present-loaded-before-inline-runtime',source.length>0&&candidate.includes('src/phase24-scaling-authority.js')&&candidate.indexOf('src/phase24-scaling-authority.js')<candidate.indexOf('<script>'));
  record('candidate-exact-versioned-immutable-authority',source.includes('EVERSTEAD_PHASE24_SCALING')&&source.includes('everstead-scaling-live-baseline.phase-24a.v1')&&source.includes('live-baseline-only')&&source.includes('Object.freeze')&&source.includes('historicalAnchors')&&source.includes('36366')&&source.includes('35565')&&source.includes('801'));
  record('candidate-three-canonical-profile-definitions',f.profiles.every(profile=>source.includes(profile.id)));
  record('candidate-active-and-legacy-only-authorities',source.includes('buildingUpgradeGrowth:1.24')&&source.includes('buildingUpgradeGrowth:{value:1.70,active:false')&&source.includes('companionBasePower:{bramble:1000,cinderwing:1200,active:false')&&source.includes("scope:'schema-12-migration-predecessor-only'"));
  record('candidate-collection-reserved-inactive-zero',source.includes('reserved-inactive')&&/contributionBps\s*:\s*0/.test(source)&&/multiplier\s*:\s*1/.test(source));
  record('candidate-pure-source-no-storage-or-gameplay-mutation',!/(?:localStorage|sessionStorage|indexedDB|\.setItem\s*\(|\.removeItem\s*\(|mutatePersisted|commitPrepared|PERSISTED_RAW|saveMeta|schemaVersion\s*=\s*14)/.test(source));
  record('candidate-source-syntax',spawnSync(process.execPath,['--check',sourcePath],{cwd:ROOT,encoding:'utf8'}).status===0);
  record('candidate-frozen-production-source-hashes-exact',Object.entries(f.generatedArtifacts.productionSourceSha256).every(([path,expected])=>sha(path)===expected),Object.fromEntries(Object.keys(f.generatedArtifacts.productionSourceSha256).map(path=>[path,sha(path)])));
  record('candidate-generated-balance-artifacts-exact',sha('qa/phase-24-baseline/reports/phase24a-balance-report.json')===f.generatedArtifacts.balanceReportJsonSha256&&sha('qa/phase-24-baseline/reports/phase24a-balance-report.md')===f.generatedArtifacts.balanceReportMarkdownSha256&&sha('qa/phase-24-baseline/fixtures/recipes.json')===f.generatedArtifacts.recipeSha256);
  const generatedCheck=spawnSync(process.execPath,['scripts/phase24-generate-balance-report.mjs','--check'],{cwd:ROOT,encoding:'utf8',timeout:120000});record('candidate-generated-balance-report-reproduces-exactly',generatedCheck.status===0,generatedCheck.stdout+generatedCheck.stderr);
  const bridgeStart=candidate.indexOf('function phase23InstallQaBridge'),bridgeBody=bridgeStart<0?'':candidate.slice(bridgeStart,bridgeStart+8000);
  record('candidate-genuine-read-only-bridge-interface',['scalingDefinitions','scalingReport','scalingProfileState','scalingPreviewSettlement'].every(value=>candidate.includes(value)&&candidate.includes(`'${value}'`))&&['scalingDefinitions','scalingReport','scalingProfileState','scalingPreviewSettlement'].every(value=>phase23Runtime.includes(`'${value}'`))&&!/destructive=Object\.freeze\([^)]*scaling(?:Definitions|Report|ProfileState|PreviewSettlement)/s.test(bridgeBody));
  record('candidate-pure-phase1819-preview-clones-and-uses-real-settlement',previewBody.includes("['facility.apothecary','facility.schoolhouse'].includes(facilityId)")&&previewBody.includes('Number.isSafeInteger(at)')&&previewBody.includes('const draft=clone(state)')&&previewBody.includes('profile(draft)')&&previewBody.includes('settleInState(draft,facilityId,at)')&&previewBody.includes('derive(draft)')&&previewBody.includes('return clone({facilityId')&&phase1819.includes('settleOffline,previewSettlement,beginApothecary'));
  record('candidate-pure-phase1819-preview-has-no-live-storage-mutation-authority',previewBody.length>0&&!/(?:current\s*\(|localStorage|sessionStorage|indexedDB|\.setItem\s*\(|\.removeItem\s*\(|a\.mutate\s*\(|render\s*\(|commit|coordinator)/.test(previewBody));
  record('candidate-visible-diagnostic-hooks',['data-phase24-scaling-open','data-phase24-scaling-dialog','data-phase24-profile-id','data-phase24-scaling-report','data-phase24-formula','data-phase24-scaling-close'].every(value=>candidate.includes(value)));
  record('candidate-phase23-baseline-authority-still-active',candidate.includes('function phaseTenCTwoProfileActive(state=S){return [11,12,13].includes')&&candidate.includes("effectiveFellowPowerComponents=function(id,state=S){if(![10,11,12,13].includes")&&candidate.includes("settleFellowExpeditionElapsed=function(at,state=S){if(![11,12,13].includes"));
  record('prior-phase23-package-checksum-files-exact',sha('qa/phase-23-independent/checksums.sha256')===f.historical.phase23ChecksumFileSha256&&sha('qa/phase-23-successor-compatibility/checksums.sha256')===f.historical.phase23SuccessorChecksumFileSha256);
  for(const [id,path] of [['phase23','qa/phase-23-independent/checksums.sha256'],['phase23-successor','qa/phase-23-successor-compatibility/checksums.sha256']]){const check=spawnSync('shasum',['-a','256','-c',path],{cwd:ROOT,encoding:'utf8'});record(`prior-${id}-package-remains-frozen`,check.status===0,check.stdout+check.stderr)}
  for(const [id,path] of [['phase23','qa/phase-23-independent/verify.mjs'],['phase23-successor','qa/phase-23-successor-compatibility/verify.mjs']]){const check=spawnSync(process.execPath,[path],{cwd:ROOT,encoding:'utf8'});record(`inherited-${id}-full-static-green`,check.status===0,check.stdout+check.stderr)}
  record('prior-phase1819-checksum-authorities-unchanged',sha('qa/phase-18-19-independent/checksums.sha256')===f.historical.phase1819IndependentChecksumFileSha256&&sha('qa/phase-18-19-runtime/checksums.sha256')===f.historical.phase1819RuntimeChecksumFileSha256);
  record('prior-phase1819-independent-package-remains-frozen',checksumFailures('qa/phase-18-19-independent/checksums.sha256').length===0,checksumFailures('qa/phase-18-19-independent/checksums.sha256'));
  const phase1819RuntimeIdentityDeltas=checksumFailures('qa/phase-18-19-runtime/checksums.sha256').sort();record('prior-phase1819-runtime-identity-deltas-are-exactly-approved-successor-files',same(phase1819RuntimeIdentityDeltas,[...f.historical.phase1819ExpectedSupersededIdentityPaths].sort()),phase1819RuntimeIdentityDeltas);
  for(const [id,path] of [['phase18-19-independent','qa/phase-18-19-independent/verify.mjs'],['phase18-19-runtime','qa/phase-18-19-runtime/verify.mjs']]){const check=spawnSync(process.execPath,[path],{cwd:ROOT,encoding:'utf8'});record(`inherited-${id}-behavioral-static-green`,check.status===0,check.stdout+check.stderr)}
}

const passed=rows.filter(row=>row.pass).length,failed=rows.length-passed;for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` — ${typeof row.detail==='string'?row.detail:JSON.stringify(row.detail)}`:''}`);console.log(`RESULT ${passed} passed, ${failed} failed${PACKAGE_ONLY?' (package only)':''}`);process.exitCode=failed?1:0;
