import {readFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import vm from 'node:vm';

const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const QA=resolve(ROOT,'qa/phase-10b2');
const ARTIFACT_PATH=resolve(ROOT,'index.html');
const BASE_COMMIT='fff84f7dfe87b23040edaa31f07f5f3c9181babf';
const PREIMAGE_SHA='717160cdddc5fa540532cdebd29f30d127ded2f761edd677684a2609fde9a4ed';
const PREIMAGE_BYTES=18916682;
// Deliberately empty until the production-only extraction has a reviewed SHA/bytes.
// A marker-bearing artifact that is not in this table is always refused.
const REVIEWED_CANDIDATES=Object.freeze([]);
const BOOT='const report=load();render();installQaBridge();if(report)runtimeSetTimeout(()=>openOffline(report),250);';
const RUNTIME_ANCHOR='const RUNTIME_INPUT=';
const CORE_NAME='PHASE_TEN_B_TWO_GOLD_CORE';
const CORE_MARKER=`const ${CORE_NAME}=`;
const METHOD_ORDER=Object.freeze(['familyBuildingBonus','neutralHookBonus','buildingUpgradeCost','buildingRateComponents','durationGold','totalRate','offlineTotals']);
const WRAPPER_NAMES=Object.freeze(['familyBuildingBonusComponents','economyHookBonus','buildingUpgradeCost','buildingRateComponents','totalRate','offlineClaimPreview']);
const UNCHANGED_WRAPPERS=Object.freeze(['familyBuildingAssignment','buildingRate','nextLocalMidnight']);
const sha=value=>createHash('sha256').update(value).digest('hex');
const own=(value,key)=>Object.prototype.hasOwnProperty.call(value,key);
const asBuffer=value=>Buffer.isBuffer(value)?value:Buffer.from(value);
const artifactBytes=readFileSync(ARTIFACT_PATH);
const artifactIdentity=Object.freeze({sha256:sha(artifactBytes),byteLength:artifactBytes.length});
const hasCoreMarker=artifactBytes.indexOf(Buffer.from(CORE_MARKER))>=0;
const reviewedCandidate=REVIEWED_CANDIDATES.find(item=>item.sha256===artifactIdentity.sha256&&item.byteLength===artifactIdentity.byteLength)??null;
const mode=artifactIdentity.sha256===PREIMAGE_SHA&&artifactIdentity.byteLength===PREIMAGE_BYTES&&!hasCoreMarker?'preimage':reviewedCandidate&&hasCoreMarker?'candidate':'refused';
if(mode==='refused')throw new Error(`Phase 10B-2 probe refuses unknown production artifact ${artifactIdentity.sha256} (${artifactIdentity.byteLength} bytes)`);

function occurrences(buffer,needle){const token=asBuffer(needle),found=[];let offset=0;while((offset=buffer.indexOf(token,offset))>=0){found.push(offset);offset+=Math.max(1,token.length)}return found}
function uniqueOffset(buffer,needle,label){const found=occurrences(buffer,needle);if(found.length!==1)throw new Error(`${label} must occur exactly once; found ${found.length}`);return found[0]}
function skipQuoted(buffer,index,quote){for(let cursor=index+1;cursor<buffer.length;cursor++){const value=buffer[cursor];if(value===92){cursor++;continue}if(value===quote)return cursor}throw new Error('Unterminated quoted source anchor')}
function skipLineComment(buffer,index){let cursor=index+2;while(cursor<buffer.length&&buffer[cursor]!==10&&buffer[cursor]!==13)cursor++;return cursor-1}
function skipBlockComment(buffer,index){for(let cursor=index+2;cursor<buffer.length-1;cursor++)if(buffer[cursor]===42&&buffer[cursor+1]===47)return cursor+1;throw new Error('Unterminated block comment')}
function balancedClose(buffer,open,openByte,closeByte,label){
  if(buffer[open]!==openByte)throw new Error(`${label} opening token mismatch`);let depth=1;
  for(let cursor=open+1;cursor<buffer.length;cursor++){
    const value=buffer[cursor],next=buffer[cursor+1];
    if(value===39||value===34||value===96){cursor=skipQuoted(buffer,cursor,value);continue}
    if(value===47&&next===47){cursor=skipLineComment(buffer,cursor);continue}
    if(value===47&&next===42){cursor=skipBlockComment(buffer,cursor);continue}
    if(value===openByte)depth++;else if(value===closeByte&&--depth===0)return cursor;
  }
  throw new Error(`${label} is not balanced`);
}
function functionWindow(buffer,name){
  const declaration=Buffer.from(`function ${name}(`),start=uniqueOffset(buffer,declaration,`${name} declaration`),openParen=start+declaration.length-1,closeParen=balancedClose(buffer,openParen,40,41,`${name} parameters`);let brace=closeParen+1;
  while(brace<buffer.length&&[9,10,13,32].includes(buffer[brace]))brace++;
  if(buffer[brace]!==123)throw new Error(`${name} body opening brace is missing`);const close=balancedClose(buffer,brace,123,125,`${name} body`);
  return Object.freeze({name:`wrapper:${name}`,declarationStart:start,signatureStart:start,signatureEnd:brace+1,start:brace+1,end:close,closeEnd:close+1});
}
function methodWindow(buffer,kernel,name){
  const anchor=Buffer.from(`const ${name}=input=>{`),relative=occurrences(buffer.subarray(kernel.start,kernel.end),anchor);
  if(relative.length!==1)throw new Error(`${name} canonical method-body anchor must occur exactly once; found ${relative.length}`);
  const declarationStart=kernel.start+relative[0],brace=declarationStart+anchor.length-1,close=balancedClose(buffer,brace,123,125,`${name} method body`);if(close>=kernel.end)throw new Error(`${name} method body escapes the kernel window`);
  return Object.freeze({name:`method:${name}`,declarationStart,start:brace+1,end:close,closeEnd:close+1});
}
function sourceWindows(buffer,kind){
  const runtime=uniqueOffset(buffer,RUNTIME_ANCHOR,'RUNTIME_INPUT anchor'),wrappers=WRAPPER_NAMES.map(name=>functionWindow(buffer,name));let kernel;
  if(kind==='base')kernel=Object.freeze({name:'kernel-insertion',start:runtime,end:runtime});
  else{const start=uniqueOffset(buffer,CORE_MARKER,'private-kernel insertion');if(start>=runtime)throw new Error('Private kernel is not immediately before RUNTIME_INPUT');kernel=Object.freeze({name:'kernel-insertion',start,end:runtime})}
  const windows=[kernel,...wrappers].sort((left,right)=>left.start-right.start);for(let index=1;index<windows.length;index++)if(windows[index-1].end>windows[index].start)throw new Error('Authorized source windows overlap');
  return Object.freeze({kernel,wrappers:Object.freeze(wrappers),ordered:Object.freeze(windows),methods:kind==='candidate'?Object.freeze(Object.fromEntries(METHOD_ORDER.map(name=>[name,methodWindow(buffer,kernel,name)]))):null});
}
function segments(buffer,windows){const result=[];let cursor=0;for(const window of windows){result.push(buffer.subarray(cursor,window.start));cursor=window.end}result.push(buffer.subarray(cursor));return result}
function applySimple(buffer,replacements){let result=Buffer.from(buffer);for(const item of [...replacements].sort((left,right)=>right.start-left.start))result=Buffer.concat([result.subarray(0,item.start),asBuffer(item.replacement),result.subarray(item.end)]);return result}
function applyReplacements(buffer,replacements,label){
  const ordered=[...replacements].sort((left,right)=>left.start-right.start);for(let index=0;index<ordered.length;index++){const item=ordered[index];if(!Number.isInteger(item.start)||!Number.isInteger(item.end)||item.start<0||item.end<item.start||item.end>buffer.length)throw new Error(`${label} replacement range is invalid`);if(index&&ordered[index-1].end>item.start)throw new Error(`${label} replacements overlap`)}
  const chunks=[],applied=[];let cursor=0,length=0;
  for(const item of ordered){const prefix=buffer.subarray(cursor,item.start);chunks.push(prefix);length+=prefix.length;const replacement=asBuffer(item.replacement),original=buffer.subarray(item.start,item.end),transformedStart=length;chunks.push(replacement);length+=replacement.length;applied.push(Object.freeze({...item,original:Buffer.from(original),replacement:Buffer.from(replacement),transformedStart,transformedEnd:length}));cursor=item.end}
  chunks.push(buffer.subarray(cursor));const transformed=Buffer.concat(chunks),inverse=[...applied].reverse().map(item=>({start:item.transformedStart,end:item.transformedEnd,replacement:item.original})),restored=applySimple(transformed,inverse);if(!restored.equals(buffer))throw new Error(`${label} inverse restoration mismatch`);
  return Object.freeze({buffer:transformed,applied:Object.freeze(applied),restored});
}
function baseArtifact(){
  if(mode==='preimage')return artifactBytes;
  const bytes=execFileSync('git',['show',`${BASE_COMMIT}:index.html`],{cwd:ROOT,encoding:null,maxBuffer:64*1024*1024});if(bytes.length!==PREIMAGE_BYTES||sha(bytes)!==PREIMAGE_SHA)throw new Error('Phase 10B-2 base Git object identity mismatch');return bytes;
}
const baseBytes=baseArtifact(),baseWindows=sourceWindows(baseBytes,'base'),currentWindows=sourceWindows(artifactBytes,mode==='candidate'?'candidate':'base');
function computeBoundary(){
  const baseSegments=segments(baseBytes,baseWindows.ordered),candidateSegments=segments(artifactBytes,currentWindows.ordered);if(baseSegments.length!==8||candidateSegments.length!==8)throw new Error('Seven-window segment allocation mismatch');for(let index=0;index<8;index++)if(!baseSegments[index].equals(candidateSegments[index]))throw new Error(`Changed byte outside authorized source window ${index}`);
  const sentinels=currentWindows.ordered.map((window,index)=>Buffer.from(`\n/*__P10B2_WINDOW_${index+1}_${window.name}__*/\n`)),maskedCandidate=applySimple(artifactBytes,currentWindows.ordered.map((window,index)=>({start:window.start,end:window.end,replacement:sentinels[index]}))),maskedBase=applySimple(baseBytes,baseWindows.ordered.map((window,index)=>({start:window.start,end:window.end,replacement:sentinels[index]})));if(!maskedCandidate.equals(maskedBase))throw new Error('Masked seven-window buffers differ');
  const restoreRanges=currentWindows.ordered.map((window,index)=>({start:window.start,end:window.end,replacement:baseBytes.subarray(baseWindows.ordered[index].start,baseWindows.ordered[index].end)})),restored=applyReplacements(artifactBytes,restoreRanges,'candidate-to-base restoration').buffer;if(!restored.equals(baseBytes)||sha(restored)!==PREIMAGE_SHA||restored.length!==PREIMAGE_BYTES)throw new Error('Seven-window restoration does not reproduce the accepted base');
  const kernelText=mode==='candidate'?artifactBytes.subarray(currentWindows.kernel.start,currentWindows.kernel.end).toString('utf8'):'';
  return Object.freeze({mode,preimageExact:mode==='preimage',candidateMarker:mode==='candidate',candidateReviewed:Boolean(reviewedCandidate),restorationExact:true,allowedWindows:7,wrapperBodies:6,kernelInsertion:1,kernelWindow:mode==='candidate'?Object.freeze({start:currentWindows.kernel.start,end:currentWindows.kernel.end,sha256:sha(artifactBytes.subarray(currentWindows.kernel.start,currentWindows.kernel.end))}):null,unchangedWrapperNames:UNCHANGED_WRAPPERS,familyAssignmentExact:true,buildingRateExact:true,nextLocalMidnightExact:true,shapeGuardLocated:mode==='candidate'&&kernelText.includes('p10b2AssertSurface(PHASE_TEN_B_TWO_GOLD_CORE);'),shapeGuardBeforeRuntime:mode==='candidate'&&kernelText.endsWith('p10b2AssertSurface(PHASE_TEN_B_TWO_GOLD_CORE);'),maskedSha256:sha(maskedCandidate),protectedSegmentSha256:Object.freeze(candidateSegments.map(sha)),windows:Object.freeze(currentWindows.ordered.map((window,index)=>Object.freeze({name:window.name,baseByteLength:baseWindows.ordered[index].end-baseWindows.ordered[index].start,candidateByteLength:window.end-window.start})))});
}
const BOUNDARY=computeBoundary();

function numberBits(value){const bytes=Buffer.alloc(8);bytes.writeDoubleBE(value);return bytes.toString('hex')}
function numberFromBits(bits){return Buffer.from(bits,'hex').readDoubleBE()}
function transportValue(value,seen=new Map()){
  if(value===undefined)return{kind:'undefined'};if(value===null)return{kind:'null'};if(typeof value==='number')return{kind:'number',bits:numberBits(value)};if(typeof value==='string'||typeof value==='boolean')return{kind:typeof value,value};if(typeof value==='bigint')return{kind:'bigint',value:String(value)};if(typeof value==='symbol')return{kind:'symbol',description:value.description??null};if(typeof value==='function')return{kind:'function',name:value.name,length:value.length};
  if(seen.has(value))return{kind:'reference',id:seen.get(value)};const id=seen.size+1;seen.set(value,id);const prototype=Object.getPrototypeOf(value),prototypeKind=Array.isArray(value)&&prototype===Array.prototype?'array':prototype===Object.prototype?'ordinary':prototype===null?'null':'custom',properties=[];
  for(const key of Reflect.ownKeys(value)){const descriptor=Object.getOwnPropertyDescriptor(value,key),encodedKey=typeof key==='symbol'?{kind:'symbol',description:key.description??null}:{kind:'string',value:key};if(own(descriptor,'value'))properties.push({key:encodedKey,descriptor:'data',enumerable:descriptor.enumerable,writable:descriptor.writable,configurable:descriptor.configurable,value:transportValue(descriptor.value,seen)});else properties.push({key:encodedKey,descriptor:'accessor',enumerable:descriptor.enumerable,configurable:descriptor.configurable,get:Boolean(descriptor.get),set:Boolean(descriptor.set)})}return{kind:'object',id,prototype:prototypeKind,properties};
}
function materializeTransport(node,seen=new Map()){
  if(node.kind==='undefined')return undefined;if(node.kind==='null')return null;if(node.kind==='number')return numberFromBits(node.bits);if(node.kind==='string'||node.kind==='boolean')return node.value;if(node.kind==='bigint')return BigInt(node.value);if(node.kind==='symbol')return Symbol(node.description??undefined);if(node.kind==='function')return Object.freeze(function p10b2InputFunction(){});if(node.kind==='reference'){if(!seen.has(node.id))throw new Error('Forward transport reference');return seen.get(node.id)}if(node.kind!=='object')throw new Error('Unknown transport node');
  let value;if(node.prototype==='array')value=[];else if(node.prototype==='ordinary')value={};else if(node.prototype==='null')value=Object.create(null);else if(node.prototype==='custom')value=Object.create(Object.freeze({p10b2CustomPrototype:true}));else throw new Error('Unknown transport prototype');seen.set(node.id,value);
  for(const property of node.properties){const key=property.key.kind==='symbol'?Symbol(property.key.description??undefined):property.key.value;if(property.descriptor==='data')Object.defineProperty(value,key,{value:materializeTransport(property.value,seen),enumerable:property.enumerable,writable:property.writable,configurable:property.configurable});else Object.defineProperty(value,key,{get:property.get?function p10b2Accessor(){return undefined}:undefined,set:property.set?function p10b2Setter(){}:undefined,enumerable:property.enumerable,configurable:property.configurable})}return value;
}
function decodeAuthority(value){
  if(value===null||typeof value==='string'||typeof value==='boolean'||typeof value==='number')return value;if(Array.isArray(value))return value.map(decodeAuthority);if(value&&typeof value==='object'&&Reflect.ownKeys(value).length===1&&value.$undefined===true)return undefined;if(value&&typeof value==='object'&&Reflect.ownKeys(value).join('|')==='$float64|decimal')return numberFromBits(value.$float64);if(value&&typeof value==='object'&&Reflect.ownKeys(value).length===1&&Array.isArray(value.$object)){const result={};for(const pair of value.$object)Object.defineProperty(result,pair[0],{value:decodeAuthority(pair[1]),enumerable:true,writable:true,configurable:true});return result}throw new Error('Malformed canonical authority value');
}
function exactValue(left,right){
  if(typeof left==='number'||typeof right==='number')return typeof left==='number'&&typeof right==='number'&&Object.is(left,right);if(left===null||right===null||typeof left!=='object'||typeof right!=='object')return left===right;if(Array.isArray(left)!==Array.isArray(right)||Object.getPrototypeOf(left)!==Object.getPrototypeOf(right))return false;const leftKeys=Reflect.ownKeys(left),rightKeys=Reflect.ownKeys(right);if(leftKeys.length!==rightKeys.length||!leftKeys.every((key,index)=>key===rightKeys[index]))return false;
  for(const key of leftKeys){const a=Object.getOwnPropertyDescriptor(left,key),b=Object.getOwnPropertyDescriptor(right,key);if(!a||!b||a.enumerable!==b.enumerable||a.configurable!==b.configurable||own(a,'value')!==own(b,'value'))return false;if(own(a,'value')){if(a.writable!==b.writable||!exactValue(a.value,b.value))return false}else if(Boolean(a.get)!==Boolean(b.get)||Boolean(a.set)!==Boolean(b.set))return false}return true;
}
function firstDifference(left,right,path='$output'){if(exactValue(left,right))return null;if(typeof left==='number'||typeof right==='number'||left===null||right===null||typeof left!=='object'||typeof right!=='object'||Array.isArray(left)!==Array.isArray(right)||Object.getPrototypeOf(left)!==Object.getPrototypeOf(right))return path;const a=Reflect.ownKeys(left),b=Reflect.ownKeys(right);if(a.length!==b.length||!a.every((key,index)=>key===b[index]))return path;for(const key of a){const delta=firstDifference(left[key],right[key],`${path}.${String(key)}`);if(delta)return delta}return path}

const REALM_HELPERS=String.raw`
const __p10b2Own=(value,key)=>Object.prototype.hasOwnProperty.call(value,key);
const __p10b2Number=bits=>{const bytes=new Uint8Array(8);for(let index=0;index<8;index++)bytes[index]=parseInt(bits.slice(index*2,index*2+2),16);return new DataView(bytes.buffer).getFloat64(0,false)};
const __p10b2Bits=value=>{const bytes=new Uint8Array(8);new DataView(bytes.buffer).setFloat64(0,value,false);let text='';for(const item of bytes)text+=item.toString(16).padStart(2,'0');return text};
const __p10b2Materialize=(node,seen=new Map())=>{if(node.kind==='undefined')return undefined;if(node.kind==='null')return null;if(node.kind==='number')return __p10b2Number(node.bits);if(node.kind==='string'||node.kind==='boolean')return node.value;if(node.kind==='bigint')return BigInt(node.value);if(node.kind==='symbol')return Symbol(node.description??undefined);if(node.kind==='function')return function p10b2InputFunction(){};if(node.kind==='reference'){if(!seen.has(node.id))throw new Error('Forward transport reference');return seen.get(node.id)}if(node.kind!=='object')throw new Error('Unknown transport node');let value;if(node.prototype==='array')value=[];else if(node.prototype==='ordinary')value={};else if(node.prototype==='null')value=Object.create(null);else if(node.prototype==='custom')value=Object.create(Object.freeze({p10b2CustomPrototype:true}));else throw new Error('Unknown transport prototype');seen.set(node.id,value);for(const property of node.properties){const key=property.key.kind==='symbol'?Symbol(property.key.description??undefined):property.key.value;if(property.descriptor==='data')Object.defineProperty(value,key,{value:__p10b2Materialize(property.value,seen),enumerable:property.enumerable,writable:property.writable,configurable:property.configurable});else Object.defineProperty(value,key,{get:property.get?function p10b2Accessor(){return undefined}:undefined,set:property.set?function p10b2Setter(){}:undefined,enumerable:property.enumerable,configurable:property.configurable})}return value};
const __p10b2Freeze=(value,seen=new Set())=>{if(value===null||typeof value!=='object'&&typeof value!=='function'||seen.has(value))return value;seen.add(value);for(const key of Reflect.ownKeys(value)){const descriptor=Object.getOwnPropertyDescriptor(value,key);if(descriptor&&__p10b2Own(descriptor,'value'))__p10b2Freeze(descriptor.value,seen)}return Object.freeze(value)};
const __p10b2Transport=(value,seen=new Map())=>{if(value===undefined)return{kind:'undefined'};if(value===null)return{kind:'null'};if(typeof value==='number')return{kind:'number',bits:__p10b2Bits(value)};if(typeof value==='string'||typeof value==='boolean')return{kind:typeof value,value};if(typeof value==='bigint')return{kind:'bigint',value:String(value)};if(typeof value==='symbol')return{kind:'symbol',description:value.description??null};if(typeof value==='function')return{kind:'function',name:value.name,length:value.length};if(seen.has(value))return{kind:'reference',id:seen.get(value)};const id=seen.size+1;seen.set(value,id);const prototype=Object.getPrototypeOf(value),prototypeKind=Array.isArray(value)&&prototype===Array.prototype?'array':prototype===Object.prototype?'ordinary':prototype===null?'null':'custom',properties=[];for(const key of Reflect.ownKeys(value)){const descriptor=Object.getOwnPropertyDescriptor(value,key),encodedKey=typeof key==='symbol'?{kind:'symbol',description:key.description??null}:{kind:'string',value:key};if(__p10b2Own(descriptor,'value'))properties.push({key:encodedKey,descriptor:'data',enumerable:descriptor.enumerable,writable:descriptor.writable,configurable:descriptor.configurable,value:__p10b2Transport(descriptor.value,seen)});else properties.push({key:encodedKey,descriptor:'accessor',enumerable:descriptor.enumerable,configurable:descriptor.configurable,get:Boolean(descriptor.get),set:Boolean(descriptor.set)})}return{kind:'object',id,prototype:prototypeKind,properties}};
const __p10b2Outcome=action=>{try{return JSON.stringify({ok:true,value:__p10b2Transport(action())})}catch(error){return JSON.stringify({ok:false,error:{name:String(error?.name??'Error'),message:String(error?.message??error)}})}};
const __p10b2Resolve=(fixture,path)=>{if(typeof path!=='string'||!path.startsWith('$.'))throw new TypeError('Invalid wrapper argument path');let value=fixture;for(const key of path.slice(2).split('.')){if(value===null||typeof value!=='object'||!__p10b2Own(value,key))throw new TypeError('Unresolved wrapper argument path '+path);value=value[key]}return value};
const __p10b2TraceRecords=[],__p10b2TraceCounts=Object.fromEntries(${JSON.stringify(METHOD_ORDER)}.map(name=>[name,0]));
const __p10b2Record=(method,input)=>{if(!__p10b2Own(__p10b2TraceCounts,method))throw new Error('Unknown traced method');__p10b2TraceCounts[method]++;__p10b2TraceRecords.push({ordinal:__p10b2TraceRecords.length+1,method,argument:__p10b2Transport(input)})};
`;
function facadeSource(kind){return `${REALM_HELPERS}
const __p10b2Core=typeof ${CORE_NAME}==='object'&&${CORE_NAME}!==null?${CORE_NAME}:null;
const __p10b2Wrappers=Object.freeze({family:(id,state)=>familyBuildingBonusComponents(id,state),hook:name=>economyHookBonus(name),upgrade:level=>buildingUpgradeCost(level),rate:(id,state,at)=>buildingRateComponents(id,state,at),total:(state,at)=>totalRate(state,at),offline:(at,state)=>offlineClaimPreview(at,state)});
const __p10b2InvokeCore=(method,transportJson)=>__p10b2Outcome(()=>{if(!__p10b2Core||!Object.prototype.hasOwnProperty.call(__p10b2Core,method))throw new TypeError('Unknown kernel method');const input=__p10b2Freeze(__p10b2Materialize(JSON.parse(transportJson)));return __p10b2Core[method](input)});
const __p10b2InvokeWrapper=(selector,pathsJson,transportJson)=>__p10b2Outcome(()=>{const fixture=__p10b2Freeze(__p10b2Materialize(JSON.parse(transportJson))),args=JSON.parse(pathsJson).map(path=>__p10b2Resolve(fixture,path));if(selector==='familyBuildingBonusComponents')return __p10b2Wrappers.family(...args);if(selector==='economyHookBonus')return __p10b2Wrappers.hook(...args);if(selector==='buildingUpgradeCost')return __p10b2Wrappers.upgrade(...args);if(selector==='buildingRateComponents')return __p10b2Wrappers.rate(...args);if(selector==='totalRate')return __p10b2Wrappers.total(...args);if(selector==='offlineClaimPreview')return __p10b2Wrappers.offline(...args);throw new TypeError('Unknown wrapper selector')});
Object.defineProperty(window,'__P10B2_PROBE__',{value:Object.freeze({kind:${JSON.stringify(kind)},mode:${JSON.stringify(mode)},core:__p10b2Core,wrappers:__p10b2Wrappers,invokeCore:__p10b2InvokeCore,invokeWrapper:__p10b2InvokeWrapper,takeTrace:()=>JSON.stringify({records:__p10b2TraceRecords,counts:__p10b2TraceCounts})}),enumerable:false,writable:false,configurable:false});`}
function contextFor(kind){
  const effects={storage:[],ui:[],timer:[],network:[],listeners:[]},blocked=(bucket,name)=>(...args)=>{effects[bucket].push([name,args.length]);throw new Error(`prohibited ${name}`)},listener=scope=>(name,handler)=>effects.listeners.push([scope,name,typeof handler]);
  const storage=Object.freeze({getItem:blocked('storage','getItem'),setItem:blocked('storage','setItem'),removeItem:blocked('storage','removeItem')}),window={__EVERSTEAD_RUNTIME__:Object.freeze({storage,clock:Object.freeze({now:()=>1788026400000,setTimeout:blocked('timer','runtimeSetTimeout'),clearTimeout:blocked('timer','runtimeClearTimeout')})}),localStorage:Object.freeze({native:true}),location:Object.freeze({protocol:'https:',hostname:'invalid.example',search:''}),URLSearchParams,addEventListener:listener('window'),confirm:blocked('ui','confirm'),open:blocked('ui','open'),fetch:blocked('network','fetch'),XMLHttpRequest:blocked('network','XMLHttpRequest'),WebSocket:blocked('network','WebSocket')};
  const document=new Proxy(Object.freeze({addEventListener:listener('document')}),{get(target,key){if(key in target)return target[key];return blocked('ui',`document.${String(key)}`)}}),context={window,document,globalThis:null,URLSearchParams,console:Object.freeze({log(){},warn:blocked('ui','warn'),error:blocked('ui','error')}),addEventListener:window.addEventListener,setTimeout:blocked('timer','setTimeout'),clearTimeout:blocked('timer','clearTimeout'),fetch:window.fetch,XMLHttpRequest:window.XMLHttpRequest,WebSocket:window.WebSocket};context.globalThis=context;window.window=window;window.document=document;return{context,effects};
}
function instrumentReplacements(){if(mode!=='candidate')return[];return METHOD_ORDER.map(name=>{const window=currentWindows.methods[name];return{start:window.start,end:window.start,replacement:`__p10b2Record(${JSON.stringify(name)},input);`,name:`trace:${name}`}})}
function realm(kind,{mutation=null,trace=false}={}){
  if(!['output','call-trace','mutation'].includes(kind))throw new Error('Unknown Phase 10B-2 realm kind');const bootStart=uniqueOffset(artifactBytes,BOOT,'boot tail'),replacements=[{start:bootStart,end:bootStart+Buffer.byteLength(BOOT),replacement:facadeSource(kind),name:'boot-facade'}];if(trace&&mode==='candidate')replacements.push(...instrumentReplacements());if(mutation)replacements.push(mutation);
  const transformed=applyReplacements(artifactBytes,replacements,`${kind} realm`);if(sha(transformed.restored)!==artifactIdentity.sha256||transformed.restored.length!==artifactIdentity.byteLength)throw new Error(`${kind} realm restoration identity mismatch`);const start=uniqueOffset(transformed.buffer,'<script>','production script start'),ends=occurrences(transformed.buffer,'</script>'),end=ends.at(-1);if(end===undefined||end<=start)throw new Error('Production script boundary missing');const script=transformed.buffer.subarray(start+8,end).toString('utf8'),{context,effects}=contextFor(kind);vm.createContext(context,{codeGeneration:{strings:false,wasm:false}});new vm.Script(script,{filename:`phase10b2-${kind}.js`}).runInContext(context,{timeout:30000});
  const inherited=['__EVERSTEAD_QA__','__EVERSTEAD_PHASE6_QA__','__EVERSTEAD_PHASE7_QA__','__EVERSTEAD_PHASE9_QA__'].filter(key=>Reflect.has(context.window,key));if(effects.storage.length||effects.ui.length||effects.timer.length||effects.network.length||inherited.length)throw new Error(`Phase 10B-2 ${kind} realm side effect or inherited hook`);const expectedListeners=[['window','storage','function'],['window','storage','function'],['window','storage','function']];if(JSON.stringify(effects.listeners)!==JSON.stringify(expectedListeners))throw new Error(`Phase 10B-2 ${kind} listener capture drift`);
  const probe=context.window.__P10B2_PROBE__;if(!probe||probe.kind!==kind)throw new Error(`${kind} facade missing`);const parseOutcome=text=>{const result=JSON.parse(text);if(result.ok)return{ok:true,value:materializeTransport(result.value)};return{ok:false,error:Object.freeze(result.error)}};
  const transformedText=transformed.buffer.toString('utf8'),guard='p10b2AssertSurface(PHASE_TEN_B_TWO_GOLD_CORE);',surface=Object.freeze({corePresent:Boolean(probe.core),coreFrozen:Boolean(probe.core)&&Object.isFrozen(probe.core),methodsFrozen:Boolean(probe.core)&&METHOD_ORDER.every(name=>typeof probe.core[name]==='function'&&Object.isFrozen(probe.core[name])),forbiddenExport:Reflect.has(context,'__P10B2_FORBIDDEN_EXPORT__')||Reflect.has(context.window,'__P10B2_FORBIDDEN_EXPORT__')}),sourceEvidence=Object.freeze({guardCount:occurrences(transformed.buffer,guard).length,ambientStateReferenceCount:occurrences(transformed.buffer,'void S;').length,forbiddenExportCount:occurrences(transformed.buffer,'globalThis.__P10B2_FORBIDDEN_EXPORT__=').length,kernelMarkerCount:occurrences(transformed.buffer,CORE_MARKER).length,guardBeforeRuntime:transformedText.indexOf(guard)>=0&&transformedText.indexOf(guard)<transformedText.indexOf(RUNTIME_ANCHOR)});
  return Object.freeze({probe,surface,sourceEvidence,effects:Object.freeze(Object.fromEntries(Object.entries(effects).map(([key,value])=>[key,Object.freeze(value.map(item=>Object.freeze([...item])))]))),restoredSha256:sha(transformed.restored),restoredByteLength:transformed.restored.length,replacements:Object.freeze(transformed.applied.map(item=>Object.freeze({name:item.name,start:item.start,end:item.end,originalSha256:sha(item.original),replacementSha256:sha(item.replacement)}))),invokeCore:(method,input)=>parseOutcome(probe.invokeCore(method,JSON.stringify(transportValue(input)))),invokeWrapper:(trace,fixture)=>parseOutcome(probe.invokeWrapper(trace.wrapper.selector,JSON.stringify(trace.wrapper.argumentPaths),JSON.stringify(transportValue(fixture)))),takeTrace:()=>JSON.parse(probe.takeTrace())});
}
function outcomeValue(outcome){if(outcome.ok)return outcome.value;const error=outcome.error.name==='TypeError'?new TypeError(outcome.error.message):new Error(outcome.error.message);error.name=outcome.error.name;throw error}

const scenarios=JSON.parse(readFileSync(resolve(QA,'scenarios.json'),'utf8')),traces=JSON.parse(readFileSync(resolve(QA,'predecessor-traces.json'),'utf8'));
const vectorById=new Map(scenarios.numericVectors.map(vector=>[vector.id,vector])),traceById=new Map(traces.traces.map(trace=>[trace.id,trace]));
const mutation=(id,target,discriminator,needle,replacement,failurePath,extra={})=>Object.freeze({id,name:scenarios.mutationRows[id-1]?.name,target,discriminator,needle,replacement,failurePath,...extra});
const MUTATIONS=Object.freeze([
  mutation(1,'familyBuildingBonus','numeric-003-familyBuildingBonus-3','const baseBonus=input.base','const baseBonus=0','$output.baseBonus'),
  mutation(2,'familyBuildingBonus','numeric-005-familyBuildingBonus-5','input.intimacy*input.intimacyRate','input.intimacy*(input.intimacyRate*2)','$output.intimacyBonus'),
  mutation(3,'familyBuildingBonus','numeric-008-familyBuildingBonus-8','Math.min(input.intimacyCap,intimacyProduct)','intimacyProduct','$output.intimacyBonus'),
  mutation(4,'familyBuildingBonus','numeric-007-familyBuildingBonus-7','Math.min(input.intimacyCap,intimacyProduct)','Math.min(input.intimacyCap,input.intimacy)*input.intimacyRate','$output.intimacyBonus'),
  mutation(5,'familyBuildingBonus','numeric-009-familyBuildingBonus-9','input.rarityRate*(input.rarity-1)','input.rarityRate*input.rarity','$output.rarityBonus'),
  mutation(6,'familyBuildingBonus','numeric-010-familyBuildingBonus-10','input.rarityRate*(input.rarity-1)','(input.rarityRate*2)*(input.rarity-1)','$output.rarityBonus'),
  mutation(7,'familyBuildingBonus','numeric-013-familyBuildingBonus-13','input.specialtyMatch?input.specialtyAmount:0','!input.specialtyMatch?input.specialtyAmount:0','$output.specialtyBonus'),
  mutation(8,'familyBuildingBonus','numeric-020-familyBuildingBonus-20','input.specialtyMatch?input.specialtyAmount:0','input.specialtyMatch?input.specialtyAmount*2:0','$output.specialtyBonus'),
  mutation(9,'familyBuildingBonus','numeric-010-familyBuildingBonus-10','withRarity+specialtyBonus','baseBonus+(intimacyBonus+(rarityBonus+specialtyBonus))','$output.uncappedBonus'),
  mutation(10,'familyBuildingBonus','numeric-017-familyBuildingBonus-17','Math.min(input.cap,uncappedBonus)','uncappedBonus','$output.bonus'),
  mutation(11,'familyBuildingBonus','numeric-003-familyBuildingBonus-3','1+bonus','bonus','$output.multiplier'),
  mutation(12,'familyBuildingBonus','numeric-001-familyBuildingBonus-1','if(!input.assigned)return{baseBonus:0','if(!input.assigned)return{baseBonus:input.base','$output.baseBonus'),
  mutation(13,'neutralHookBonus','numeric-023-neutralHookBonus-3','input>0?input:0','input>=0?input:0','$output'),
  mutation(14,'neutralHookBonus','numeric-025-neutralHookBonus-5',"typeof input==='number'&&Number.isFinite(input)&&input>0?input:0","typeof input==='number'&&Number.isFinite(input)?input:0",'$output'),
  mutation(15,'neutralHookBonus',{factory:'positive-infinity'},"typeof input==='number'&&Number.isFinite(input)&&input>0?input:0","typeof input==='number'&&input>0?input:0",'$output'),
  mutation(16,'neutralHookBonus','numeric-027-neutralHookBonus-7','input>0?input:0','input>0?0:0','$output'),
  mutation(17,'buildingUpgradeCost','numeric-029-buildingUpgradeCost-1','input.base*power','(input.base+1)*power','$output'),
  mutation(18,'buildingUpgradeCost','numeric-030-buildingUpgradeCost-2','Math.pow(input.growth,input.level-1)','Math.pow(input.growth+.01,input.level-1)','$output'),
  mutation(19,'buildingUpgradeCost','numeric-030-buildingUpgradeCost-2','Math.pow(input.growth,input.level-1)','Math.pow(input.growth,input.level)','$output'),
  mutation(20,'buildingUpgradeCost','numeric-030-buildingUpgradeCost-2','Math.round(unroundedCost)','Math.round(input.base*Math.pow(input.growth,input.level)-1)','$output'),
  mutation(21,'buildingUpgradeCost','numeric-033-buildingUpgradeCost-5','Math.round(unroundedCost)','Math.floor(unroundedCost)','$output'),
  mutation(22,'buildingRateComponents','numeric-042-buildingRateComponents-2','Math.pow(input.levelGrowth,input.level-1)','Math.pow(input.levelGrowth+.01,input.level-1)','$output.levelMultiplier'),
  mutation(23,'buildingRateComponents','numeric-042-buildingRateComponents-2','Math.pow(input.levelGrowth,input.level-1)','Math.pow(input.levelGrowth,input.level)','$output.levelMultiplier'),
  mutation(24,'buildingRateComponents','numeric-052-buildingRateComponents-12','1+input.fellowRosterBonus','input.fellowRosterBonus','$output.fellowRosterMultiplier'),
  mutation(25,'buildingRateComponents','numeric-053-buildingRateComponents-13','1+input.companionRosterBonus','input.companionRosterBonus','$output.companionRosterMultiplier'),
  mutation(26,'buildingRateComponents','numeric-054-buildingRateComponents-14','1+input.overallDayBonus','input.overallDayBonus','$output.overallDayMultiplier'),
  mutation(27,'buildingRateComponents','numeric-056-buildingRateComponents-16','input.familyAssignmentMultiplier*fellowRosterMultiplier','input.familyAssignmentMultiplier*input.familyAssignmentMultiplier*fellowRosterMultiplier','$output.characterEconomyMultiplier'),
  mutation(28,'buildingRateComponents','numeric-059-buildingRateComponents-19','afterCompanion*overallDayMultiplier','input.familyAssignmentMultiplier*(fellowRosterMultiplier*(companionRosterMultiplier*overallDayMultiplier))','$output.characterEconomyMultiplier'),
  mutation(29,'buildingRateComponents','numeric-055-buildingRateComponents-15','1+input.oathBoost','input.oathBoost','$output.oathMultiplier'),
  mutation(30,'buildingRateComponents','numeric-046-buildingRateComponents-6','withCharacters*oathMultiplier','(withLevel*oathMultiplier)*characterEconomyMultiplier','$output.rate'),
  mutation(31,'buildingRateComponents','numeric-041-buildingRateComponents-1','input.base*levelMultiplier','levelMultiplier','$output.rate'),
  mutation(32,'buildingRateComponents','numeric-046-buildingRateComponents-6','withCharacters*oathMultiplier','Math.round(withCharacters*oathMultiplier)','$output.rate'),
  mutation(33,'durationGold','numeric-066-durationGold-2','product/3600000','product/3600001','$output'),
  mutation(34,'durationGold','numeric-069-durationGold-5','product/3600000','input.rate*(input.durationMs/3600000)','$output'),
  mutation(35,'durationGold','numeric-066-durationGold-2','product/3600000','Math.round(product/3600000)','$output'),
  mutation(36,'durationGold','numeric-065-durationGold-1','return value','return input.durationMs===0?1:value','$output'),
  mutation(37,'totalRate','numeric-073-totalRate-1','let total=0','let total=1','$output'),
  mutation(38,'totalRate','numeric-076-totalRate-4','for(let index=0;index<4;index++)','for(let index=3;index>=0;index--)','$output'),
  mutation(39,'totalRate','numeric-073-totalRate-1','total+value','index===3?total:total+value','$output'),
  mutation(40,'totalRate','numeric-076-totalRate-4','return total','return Math.round(total)','$output'),
  mutation(41,'wrapper:offlineClaimPreview','offline-one-ulp-discriminator','pendingBefore','pendingBefore+lines.reduce((sum,line)=>sum+line.value,0)','$output.pendingAfter',{occurrence:'last'}),
  mutation(42,'wrapper:offlineClaimPreview','offline-cross-midnight-fractional','for(const line of lines)','for(const line of [...lines].reverse())','$calls.ordinal',{trace:true}),
  mutation(43,'offlineTotals','numeric-084-offlineTotals-4','for(let index=0;index<4;index++)','for(let index=3;index>=0;index--)','$output.total'),
  mutation(44,'offlineTotals','numeric-081-offlineTotals-1','total+value','index===3?total:total+value','$output.total'),
  mutation(45,'offlineTotals','numeric-087-offlineTotals-7','let total=0','let total=input.pendingBefore','$output.total'),
  mutation(46,'offlineTotals','numeric-083-offlineTotals-3',"const pendingAfter=output(method,'pendingAfter',input.pendingBefore+total)","const pendingAfter=output(method,'pendingAfter',Math.round(input.pendingBefore+total))",'$output.pendingAfter'),
  mutation(47,'wrapper:totalRate','total-rate-mixed','PHASE_TEN_B_TWO_GOLD_CORE.totalRate','BUILDING_DEFS.reduce((sum,item)=>sum+buildingRateComponents(item.id,state,at).rate,0)','$calls.ordinal',{trace:true}),
  mutation(48,'kernel','structural',null,null,'$surface',{subcases:Object.freeze(['surface-export','surface-mutability','ambient-state','guard-relocation'])})
]);
function validateMutationDefinitions(){
  if(MUTATIONS.length!==48||new Set(MUTATIONS.map(item=>item.id)).size!==48)throw new Error('Mutation definition allocation mismatch');let subcases=0;
  for(const item of MUTATIONS){if(!item.name||item.name!==scenarios.mutationRows[item.id-1]?.name)throw new Error(`Mutation ${item.id} name drift`);const expected=item.id===48?item.subcases:['ordinary-one-defect'];if(JSON.stringify(expected)!==JSON.stringify(scenarios.mutationRows[item.id-1].subcases))throw new Error(`Mutation ${item.id} subcase drift`);subcases+=expected.length;if(item.id<48&&(!item.needle||!item.replacement)||!item.failurePath)throw new Error(`Mutation ${item.id} transform is incomplete`);if(item.id<48&&typeof item.discriminator==='string'&&!vectorById.has(item.discriminator)&&!traceById.has(item.discriminator))throw new Error(`Mutation ${item.id} discriminator is missing`)}if(subcases!==51)throw new Error('Mutation subcase allocation mismatch');
}
validateMutationDefinitions();
function kernelInputFactory(name){if(name==='positive-infinity')return Infinity;if(name==='negative-infinity')return-Infinity;if(name==='nan')return NaN;if(name==='symbol')return Symbol('phase10b2');if(name==='function')return function phase10b2Input(){};if(name==='custom-prototype')return Object.create({foreign:true});if(name==='accessor'){const value={};Object.defineProperty(value,'base',{get(){return 15000},enumerable:true});return value}if(name==='sparse-four'){const value=[1,2,,4];return value}if(name==='symbol-key'){const value={base:15000,growth:1.7,level:1};value[Symbol('foreign')]=true;return value}throw new TypeError('Unknown Phase 10B-2 kernel input factory')}
function targetWindow(spec){if(spec.target==='kernel')return currentWindows.kernel;if(spec.target.startsWith('wrapper:'))return currentWindows.wrappers.find(item=>item.name===spec.target);return currentWindows.methods?.[spec.target]??null}
function mutationReplacement(spec,subcase){
  const window=targetWindow(spec);if(!window)throw new Error(`Mutation ${spec.id} target window is unavailable`);
  if(spec.id===48){if(subcase==='surface-export')return{start:window.end,end:window.end,replacement:`globalThis.__P10B2_FORBIDDEN_EXPORT__=${CORE_NAME};`,name:'mutation-48-surface-export'};if(subcase==='ambient-state'){const method=currentWindows.methods.familyBuildingBonus;return{start:method.start,end:method.start,replacement:'void S;',name:'mutation-48-ambient-state'}}const body=artifactBytes.subarray(window.start,window.end);if(subcase==='surface-mutability'){const needle='Object.freeze(familyBuildingBonus)',found=occurrences(body,needle);if(found.length!==1)throw new Error('Mutation 48 mutability anchor must occur exactly once');return{start:window.start+found[0],end:window.start+found[0]+Buffer.byteLength(needle),replacement:'familyBuildingBonus',name:'mutation-48-surface-mutability'}}if(subcase==='guard-relocation'){const needle='p10b2AssertSurface(PHASE_TEN_B_TWO_GOLD_CORE);',found=occurrences(body,needle);if(found.length!==1)throw new Error('Mutation 48 guard anchor must occur exactly once');return{start:window.start+found[0],end:window.start+found[0]+Buffer.byteLength(needle),replacement:'void 0;',name:'mutation-48-guard-relocation'}}throw new Error('Unknown structural mutation subcase')}
  const content=artifactBytes.subarray(window.start,window.end),found=occurrences(content,spec.needle);if(found.length<1)throw new Error(`Mutation ${spec.id} anchor is missing`);let relative;if(spec.occurrence==='last')relative=found.at(-1);else{if(found.length!==1)throw new Error(`Mutation ${spec.id} anchor must occur exactly once; found ${found.length}`);relative=found[0]}return{start:window.start+relative,end:window.start+relative+Buffer.byteLength(spec.needle),replacement:spec.replacement,name:`mutation-${spec.id}`};
}
function discriminator(spec){if(typeof spec.discriminator==='object'&&spec.discriminator.factory)return{kind:'kernel',method:spec.target,input:kernelInputFactory(spec.discriminator.factory),expected:0};const vector=vectorById.get(spec.discriminator);if(vector)return{kind:'kernel',method:vector.method,input:decodeAuthority(vector.input),expected:decodeAuthority(vector.expected)};const trace=traceById.get(spec.discriminator);if(trace)return{kind:'wrapper',trace,input:decodeAuthority(trace.fixture),expected:decodeAuthority(trace.predecessor.fullReturn)};throw new Error(`Mutation ${spec.id} discriminator cannot be resolved`)}
function normalizedTrace(captured){return Object.freeze({records:Object.freeze(captured.records.map(record=>Object.freeze({ordinal:record.ordinal,method:record.method,argument:materializeTransport(record.argument)}))),counts:Object.freeze({...captured.counts})})}
function expectedTrace(trace){return Object.freeze({records:Object.freeze(trace.expectedKernelCalls.map(record=>Object.freeze({ordinal:record.ordinal,method:record.method,argument:decodeAuthority(record.argument)}))),counts:Object.freeze({...trace.aggregateCallCounts})})}

export function probeIdentity(){return Object.freeze({mode,artifactSha256:artifactIdentity.sha256,artifactByteLength:artifactIdentity.byteLength,preimageSha256:PREIMAGE_SHA,preimageByteLength:PREIMAGE_BYTES,corePresent:mode==='candidate',candidateReviewed:Boolean(reviewedCandidate),bootAnchorCount:occurrences(artifactBytes,BOOT).length,wrapperAnchorCount:WRAPPER_NAMES.reduce((sum,name)=>sum+occurrences(artifactBytes,`function ${name}(`).length,0),methodOrder:METHOD_ORDER,mutationRows:MUTATIONS.length,mutationSubcases:MUTATIONS.reduce((sum,item)=>sum+(item.subcases?.length??1),0)})}
export function createOutputRealm(){return realm('output')}
export function createCallTraceRealm(){if(mode==='preimage'){const result=realm('call-trace');return Object.freeze({...result,status:'PENDING',reason:'private kernel is intentionally absent from accepted preimage'})}const result=realm('call-trace',{trace:true});return Object.freeze({...result,status:'READY',reason:null})}
export function evaluateWrapperTrace(trace,fixture){return outcomeValue(realm('output').invokeWrapper(trace,fixture))}
export function evaluateCallTrace(trace,fixture){if(mode==='preimage')return Object.freeze({status:'PENDING',reason:'private kernel is intentionally absent from accepted preimage',records:Object.freeze([]),counts:Object.freeze(Object.fromEntries(METHOD_ORDER.map(name=>[name,0])))});const traced=realm('call-trace',{trace:true}),output=outcomeValue(traced.invokeWrapper(trace,fixture)),captured=traced.takeTrace();return Object.freeze({status:'READY',output,records:Object.freeze(captured.records.map(record=>Object.freeze({ordinal:record.ordinal,method:record.method,argument:materializeTransport(record.argument)}))),counts:Object.freeze({...captured.counts}),restoredSha256:traced.restoredSha256})}
export function evaluateKernelOutcome(method,input){if(!METHOD_ORDER.includes(method))throw new TypeError('Unknown kernel method');if(mode==='preimage')return Object.freeze({status:'PENDING',reason:'private kernel is intentionally absent from accepted preimage'});return realm('output').invokeCore(method,input)}
export function evaluateKernel(method,input){const outcome=evaluateKernelOutcome(method,input);return outcome.status==='PENDING'?outcome:outcomeValue(outcome)}
export function createKernelInput(name){return kernelInputFactory(name)}
export function kernelInputFactories(){return Object.freeze(['positive-infinity','negative-infinity','nan','symbol','function','custom-prototype','accessor','sparse-four','symbol-key'])}
export function evaluateKernelCase({method,input,factory=null}={}){if(typeof method!=='string'||(factory!==null&&typeof factory!=='string')||(factory!==null&&input!==undefined))throw new TypeError('Invalid Phase 10B-2 kernel case');const value=factory===null?input:kernelInputFactory(factory);if(mode==='preimage')return Object.freeze({status:'PENDING',ok:false,reason:'private kernel is intentionally absent from accepted preimage',effects:Object.freeze({storage:Object.freeze([]),ui:Object.freeze([]),timer:Object.freeze([]),network:Object.freeze([])})});const evaluation=realm('output'),outcome=evaluation.invokeCore(method,value);return Object.freeze({status:'READY',...outcome,effects:evaluation.effects,restoredSha256:evaluation.restoredSha256,restoredByteLength:evaluation.restoredByteLength})}
export function createMutationRealm(mutationId,subcase='ordinary-one-defect'){
  if(!Number.isInteger(mutationId)||mutationId<1||mutationId>48)throw new TypeError('Invalid mutation row');const spec=MUTATIONS[mutationId-1],allowed=spec.subcases??['ordinary-one-defect'];if(!allowed.includes(subcase))throw new TypeError('Invalid mutation subcase');if(mode==='preimage'){const pending=realm('mutation');return Object.freeze({...pending,status:'PENDING',mutationId,subcase,executed:false,controlPassed:false,mutantFailed:false,target:spec.target,discriminator:spec.discriminator,failurePath:spec.failurePath,reason:'candidate mutation window is intentionally absent from accepted preimage'})}
  const replacement=mutationReplacement(spec,subcase),control=realm(spec.trace?'call-trace':'output',{trace:Boolean(spec.trace)});let mutant=null,mutantError=null;
  try{mutant=realm('mutation',{mutation:replacement,trace:Boolean(spec.trace)})}catch(error){if(spec.id!==48)throw error;mutantError=Object.freeze({name:String(error?.name??'Error'),message:String(error?.message??error)})}
  let controlPassed=false,mutantFailed=false,actualFailurePath=spec.failurePath,failureEvidence=null;
  if(spec.id===48){
    controlPassed=control.surface.corePresent&&control.surface.coreFrozen&&control.surface.methodsFrozen&&!control.surface.forbiddenExport&&control.sourceEvidence.guardCount===1&&control.sourceEvidence.guardBeforeRuntime;
    const vector=vectorById.get('numeric-001-familyBuildingBonus-1'),input=decodeAuthority(vector.input),expected=decodeAuthority(vector.expected),controlOutcome=control.invokeCore('familyBuildingBonus',input);controlPassed=controlPassed&&controlOutcome.ok&&exactValue(controlOutcome.value,expected);
    if(subcase==='surface-export'){const mutantOutcome=mutant?.invokeCore('familyBuildingBonus',input);mutantFailed=Boolean(mutant)&&mutant.surface.forbiddenExport&&mutant.sourceEvidence.forbiddenExportCount===1&&Boolean(mutantOutcome?.ok)&&exactValue(mutantOutcome.value,expected);failureEvidence=mutant?Object.freeze({surface:mutant.surface,source:mutant.sourceEvidence}):mutantError}
    else if(subcase==='surface-mutability'){mutantFailed=Boolean(mutantError)||Boolean(mutant)&&!mutant.surface.methodsFrozen;failureEvidence=mutantError??Object.freeze({surface:mutant.surface,source:mutant.sourceEvidence})}
    else if(subcase==='ambient-state'){const mutantOutcome=mutant?.invokeCore('familyBuildingBonus',input);mutantFailed=Boolean(mutant)&&mutant.sourceEvidence.ambientStateReferenceCount===1&&Boolean(mutantOutcome?.ok)&&exactValue(mutantOutcome.value,expected);failureEvidence=mutant?Object.freeze({surface:mutant.surface,source:mutant.sourceEvidence}):mutantError}
    else{mutantFailed=Boolean(mutantError)||Boolean(mutant)&&mutant.sourceEvidence.guardCount===0;failureEvidence=mutantError??Object.freeze({surface:mutant.surface,source:mutant.sourceEvidence})}
  }else{
    const item=discriminator(spec);if(item.kind==='kernel'){const controlOutcome=control.invokeCore(item.method,item.input),mutantOutcome=mutant.invokeCore(item.method,item.input);controlPassed=controlOutcome.ok&&exactValue(controlOutcome.value,item.expected);mutantFailed=mutantOutcome.ok&&!exactValue(mutantOutcome.value,item.expected);if(mutantOutcome.ok)actualFailurePath=firstDifference(mutantOutcome.value,item.expected)??spec.failurePath;failureEvidence=Object.freeze({control:controlOutcome,mutant:mutantOutcome})}
    else{const controlOutcome=control.invokeWrapper(item.trace,item.input),mutantOutcome=mutant.invokeWrapper(item.trace,item.input);controlPassed=controlOutcome.ok&&exactValue(controlOutcome.value,item.expected);if(spec.trace){const controlTrace=normalizedTrace(control.takeTrace()),mutantTrace=normalizedTrace(mutant.takeTrace()),authority=expectedTrace(item.trace);controlPassed=controlPassed&&exactValue(controlTrace,authority);mutantFailed=mutantOutcome.ok&&exactValue(mutantOutcome.value,item.expected)&&!exactValue(mutantTrace,authority);actualFailurePath='$calls.ordinal';failureEvidence=Object.freeze({controlTrace,mutantTrace,authority})}else{mutantFailed=mutantOutcome.ok&&!exactValue(mutantOutcome.value,item.expected);if(mutantOutcome.ok)actualFailurePath=firstDifference(mutantOutcome.value,item.expected)??spec.failurePath;failureEvidence=Object.freeze({control:controlOutcome,mutant:mutantOutcome})}}
  }
  return Object.freeze({status:'READY',mutationId,subcase,executed:true,controlPassed,mutantFailed,failurePath:actualFailurePath,expectedFailurePath:spec.failurePath,target:spec.target,discriminator:spec.discriminator,restoredSha256:mutant?.restoredSha256??artifactIdentity.sha256,replacements:mutant?.replacements??Object.freeze([{name:replacement.name,initError:mutantError}]),failureEvidence});
}
export function mutationDefinitions(){return Object.freeze(MUTATIONS.map(item=>Object.freeze({id:item.id,name:item.name,target:item.target,discriminator:item.discriminator,failurePath:item.failurePath,subcases:item.subcases??Object.freeze(['ordinary-one-defect'])})))}
export function sourceBoundary(){return BOUNDARY}
export function probeSelfTest(){const output=realm('output'),call=mode==='preimage'?realm('call-trace'):realm('call-trace',{trace:true}),mutationPending=MUTATIONS.map(item=>createMutationRealm(item.id,item.subcases?.[0]??'ordinary-one-defect')),restored=output.restoredSha256===artifactIdentity.sha256&&call.restoredSha256===artifactIdentity.sha256,definitions=mutationPending.length===48&&mutationPending.reduce((sum,item)=>sum+(MUTATIONS[item.mutationId-1].subcases?.length??1),0)===51;return Object.freeze({mode,boundary:BOUNDARY.restorationExact&&BOUNDARY.allowedWindows===7,restored,realmSeparation:output.probe!==call.probe,definitions,mutationStatus:mode==='preimage'?'PENDING':'READY',writes:0})}
