(()=>{'use strict';
const PREIMAGE_SHA='717160cdddc5fa540532cdebd29f30d127ded2f761edd677684a2609fde9a4ed',PREIMAGE_BYTES=18916682,params=new URLSearchParams(location.search),realmId=params.get('realm')||'unknown',allowed=new Set(['../../index.html','scenarios.json','row-registry.json','predecessor-traces.json']),calls={storage:0,save:0,network:0,prohibited:0},trapFailures=[];
const hex=bytes=>Array.from(new Uint8Array(bytes),value=>value.toString(16).padStart(2,'0')).join(''),hash=async bytes=>hex(await crypto.subtle.digest('SHA-256',bytes));
const guardedFetch=async path=>{const url=new URL(path,location.href);if(url.origin!==location.origin||!allowed.has(path)||url.search||url.hash||url.protocol!==location.protocol)throw new Error('GET allowlist refusal');calls.network++;const response=await fetch(url,{method:'GET',credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer'});if(!response.ok)throw new Error('GET '+path+' '+response.status);return response};
function trap(object,key,value){try{const descriptor=Object.getOwnPropertyDescriptor(object,key);if(descriptor&&!descriptor.configurable)throw new Error('nonconfigurable');Object.defineProperty(object,key,{value,configurable:true,writable:false})}catch(error){trapFailures.push(key+': '+error.message)}}
const forbidden=name=>(...args)=>{calls.prohibited++;throw new Error('prohibited '+name+' '+args.length)};
async function run(token){calls.storage=0;calls.save=0;calls.network=0;calls.prohibited=0;trapFailures.length=0;
  const [artifactResponse,scenarioResponse,registryResponse,traceResponse]=await Promise.all([...allowed].map(guardedFetch)),artifactBytes=await artifactResponse.arrayBuffer(),artifactText=new TextDecoder().decode(artifactBytes),scenarios=await scenarioResponse.json(),registry=await registryResponse.json(),traces=await traceResponse.json(),artifactSha=await hash(artifactBytes),preimage=artifactSha===PREIMAGE_SHA&&artifactBytes.byteLength===PREIMAGE_BYTES,candidate=!preimage&&artifactText.includes('const PHASE_TEN_B_TWO_GOLD_CORE=');
  trap(window,'WebSocket',forbidden('WebSocket'));trap(window,'EventSource',forbidden('EventSource'));trap(navigator,'sendBeacon',forbidden('sendBeacon'));trap(window,'indexedDB',{open:forbidden('indexedDB.open')});trap(window,'caches',{open:forbidden('caches.open')});if(navigator.serviceWorker)trap(navigator.serviceWorker,'register',forbidden('serviceWorker.register'));try{const cookie=Object.getOwnPropertyDescriptor(Document.prototype,'cookie');if(cookie?.configurable)Object.defineProperty(document,'cookie',{get(){return''},set(){calls.prohibited++;throw new Error('prohibited cookie')},configurable:true});else trapFailures.push('cookie: nonconfigurable')}catch(error){trapFailures.push('cookie: '+error.message)}
  const rows=[],add=(id,status,evidence)=>rows.push({id:`${realmId}:${id}`,status,evidence});
  const controls=[registry.total===400,registry.rows.length===400,new Set(registry.rows.map(row=>row.id)).size===400,scenarios.numericVectors.length===96,scenarios.mutationRows.length===48,traces.traceCount===32,traces.traces.length===32,artifactBytes.byteLength>0,preimage||candidate,artifactText.includes('function familyBuildingBonusComponents'),artifactText.includes('function economyHookBonus'),artifactText.includes('function buildingUpgradeCost'),artifactText.includes('function buildingRateComponents'),artifactText.includes('function totalRate'),artifactText.includes('function offlineClaimPreview'),calls.storage===0,calls.save===0,calls.prohibited===0,calls.network===4,document.documentElement.scrollWidth<=document.documentElement.clientWidth&&trapFailures.length===0];
  controls.forEach((ok,index)=>add(`control-${String(index+1).padStart(2,'0')}`,ok?'PASS':'FAIL',index===19?trapFailures.join('; ')||'all prohibited API traps installed':'read-only authority/control'));
  for(let index=1;index<=36;index++)add(`candidate-${String(index).padStart(2,'0')}`,preimage?'PENDING':'PENDING',preimage?'candidate-only private-kernel browser assertion':'candidate executable browser assertion awaits post-extraction freeze');
  document.getElementById('status').textContent=`${rows.filter(row=>row.status==='PASS').length} pass / ${rows.filter(row=>row.status==='PENDING').length} pending / ${rows.filter(row=>row.status==='FAIL').length} fail`;
  parent.postMessage({type:'phase10b2-realm',realmId,token,rows,artifactSha,artifactBytes:artifactBytes.byteLength,calls:{...calls},trapFailures:[...trapFailures]},location.origin);
}
addEventListener('message',event=>{if(event.origin!==location.origin)return;if(event.data?.type==='phase10b2-ping'){parent.postMessage({type:'phase10b2-ready',realmId},location.origin);return}if(event.data?.type!=='phase10b2-start'||typeof event.data.token!=='string')return;run(event.data.token).catch(error=>parent.postMessage({type:'phase10b2-realm-fatal',realmId,token:event.data.token,error:String(error.stack||error)},location.origin))});parent.postMessage({type:'phase10b2-ready',realmId},location.origin);
})();
