const METHOD_ORDER=Object.freeze(['familyBuildingBonus','neutralHookBonus','buildingUpgradeCost','buildingRateComponents','durationGold','totalRate','offlineTotals']);
const own=(value,key)=>Object.prototype.hasOwnProperty.call(value,key);
const ordinary=value=>value!==null&&typeof value==='object'&&!Array.isArray(value)&&Object.getPrototypeOf(value)===Object.prototype;
const keysExact=(value,keys)=>ordinary(value)&&Reflect.ownKeys(value).length===keys.length&&Reflect.ownKeys(value).every((key,index)=>key===keys[index]);
const dataProperty=(value,key,{canonicalFlags=false,enumerable=true}={})=>{const descriptor=Object.getOwnPropertyDescriptor(value,key);return Boolean(descriptor)&&own(descriptor,'value')&&!own(descriptor,'get')&&!own(descriptor,'set')&&descriptor.enumerable===enumerable&&(!canonicalFlags||descriptor.writable===true&&descriptor.configurable===true)};
const dataFields=(value,keys)=>keysExact(value,keys)&&keys.every(key=>dataProperty(value,key));
const denseArray=(value,{length=null,canonicalFlags=false}={})=>{if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype||length!==null&&value.length!==length)return false;const expected=[...Array(value.length).keys()].map(String).concat('length'),keys=Reflect.ownKeys(value);if(keys.length!==expected.length||!keys.every((key,index)=>key===expected[index]))return false;for(let index=0;index<value.length;index++)if(!dataProperty(value,String(index),{canonicalFlags}))return false;const descriptor=Object.getOwnPropertyDescriptor(value,'length');return Boolean(descriptor)&&own(descriptor,'value')&&!own(descriptor,'get')&&!own(descriptor,'set')&&descriptor.enumerable===false&&descriptor.configurable===false&&(!canonicalFlags||descriptor.writable===true)};
const denseFour=value=>denseArray(value,{length:4});
const fail=(method,path)=>{throw new TypeError(`PHASE_TEN_B_TWO_GOLD_CORE.${method}: invalid ${path}`)};
const finite=value=>typeof value==='number'&&Number.isFinite(value),nonnegative=value=>finite(value)&&value>=0&&!Object.is(value,-0),bounded=(value,max)=>nonnegative(value)&&value<=max;
const output=(method,path,value,{safe=false}={})=>{if(!finite(value)||value<0||safe&&!Number.isSafeInteger(value))fail(method,`$output.${path}`);return value};

function familyBuildingBonus(input){
  const method='familyBuildingBonus',keys=['assigned','intimacy','rarity','specialtyMatch','base','intimacyRate','intimacyCap','rarityRate','specialtyAmount','cap'];
  if(!dataFields(input,keys))fail(method,'$input');
  const {assigned,intimacy,rarity,specialtyMatch,base,intimacyRate,intimacyCap,rarityRate,specialtyAmount,cap}=input;
  if(typeof assigned!=='boolean')fail(method,'$input.assigned');if(!finite(intimacy)||intimacy<0||intimacy>Number.MAX_SAFE_INTEGER)fail(method,'$input.intimacy');
  if(!Number.isInteger(rarity)||assigned&&(rarity<1||rarity>5)||!assigned&&rarity!==0)fail(method,'$input.rarity');if(typeof specialtyMatch!=='boolean')fail(method,'$input.specialtyMatch');
  for(const [name,value]of [['base',base],['intimacyRate',intimacyRate],['intimacyCap',intimacyCap],['rarityRate',rarityRate],['specialtyAmount',specialtyAmount],['cap',cap]])if(!bounded(value,1))fail(method,`$input.${name}`);
  if(base>cap)fail(method,'$input.base');if(intimacyCap>cap)fail(method,'$input.intimacyCap');if(rarityRate>cap)fail(method,'$input.rarityRate');if(specialtyAmount>cap)fail(method,'$input.specialtyAmount');
  if(!assigned&&(intimacy!==0||specialtyMatch))fail(method,'$input.assigned');
  if(!assigned)return{baseBonus:0,intimacyBonus:0,rarityBonus:0,specialtyBonus:0,uncappedBonus:0,bonus:0,multiplier:1};
  const baseBonus=base,intimacyProduct=output(method,'intimacyBonus',intimacy*intimacyRate),intimacyBonus=output(method,'intimacyBonus',Math.min(intimacyCap,intimacyProduct)),rarityBonus=output(method,'rarityBonus',rarityRate*(rarity-1)),specialtyBonus=output(method,'specialtyBonus',specialtyMatch?specialtyAmount:0),withIntimacy=output(method,'uncappedBonus',baseBonus+intimacyBonus),withRarity=output(method,'uncappedBonus',withIntimacy+rarityBonus),uncappedBonus=output(method,'uncappedBonus',withRarity+specialtyBonus),bonus=output(method,'bonus',Math.min(cap,uncappedBonus)),multiplier=output(method,'multiplier',1+bonus);
  return{baseBonus,intimacyBonus,rarityBonus,specialtyBonus,uncappedBonus,bonus,multiplier};
}
function neutralHookBonus(value){return typeof value==='number'&&Number.isFinite(value)&&value>0?value:0}
function buildingUpgradeCost(input){
  const method='buildingUpgradeCost',keys=['base','growth','level'];if(!dataFields(input,keys))fail(method,'$input');
  if(!finite(input.base)||input.base<=0||input.base>Number.MAX_SAFE_INTEGER)fail(method,'$input.base');if(!finite(input.growth)||input.growth<=0)fail(method,'$input.growth');if(!finite(input.level)||input.level<1||input.level>52||Object.is(input.level,-0))fail(method,'$input.level');
  const power=Math.pow(input.growth,input.level-1);output(method,'power',power);const unroundedCost=input.base*power;output(method,'unroundedCost',unroundedCost);const cost=Math.round(unroundedCost);output(method,'cost',cost,{safe:true});return cost;
}
function buildingRateComponents(input){
  const method='buildingRateComponents',keys=['base','level','levelGrowth','familyAssignmentMultiplier','fellowRosterBonus','companionRosterBonus','overallDayBonus','oathBoost'];if(!dataFields(input,keys))fail(method,'$input');
  const rules={base:value=>bounded(value,Number.MAX_SAFE_INTEGER),level:value=>finite(value)&&value>=1&&value<=52&&!Object.is(value,-0),levelGrowth:value=>finite(value)&&value>0,familyAssignmentMultiplier:value=>finite(value)&&value>=1&&!Object.is(value,-0),fellowRosterBonus:value=>nonnegative(value),companionRosterBonus:value=>nonnegative(value),overallDayBonus:value=>nonnegative(value),oathBoost:value=>bounded(value,.30)};
  for(const key of keys)if(!rules[key](input[key]))fail(method,`$input.${key}`);
  const levelMultiplier=output(method,'levelMultiplier',Math.pow(input.levelGrowth,input.level-1)),fellowRosterMultiplier=output(method,'fellowRosterMultiplier',1+input.fellowRosterBonus),companionRosterMultiplier=output(method,'companionRosterMultiplier',1+input.companionRosterBonus),overallDayMultiplier=output(method,'overallDayMultiplier',1+input.overallDayBonus),afterFamily=output(method,'characterEconomyMultiplier',input.familyAssignmentMultiplier*fellowRosterMultiplier),afterCompanion=output(method,'characterEconomyMultiplier',afterFamily*companionRosterMultiplier),characterEconomyMultiplier=output(method,'characterEconomyMultiplier',afterCompanion*overallDayMultiplier),oathMultiplier=output(method,'oathMultiplier',1+input.oathBoost),withLevel=output(method,'rate',input.base*levelMultiplier),withCharacters=output(method,'rate',withLevel*characterEconomyMultiplier),rate=output(method,'rate',withCharacters*oathMultiplier);if(rate>Number.MAX_SAFE_INTEGER)fail(method,'$output.rate');return{levelMultiplier,fellowRosterMultiplier,companionRosterMultiplier,overallDayMultiplier,characterEconomyMultiplier,oathMultiplier,rate};
}
function durationGold(input){const method='durationGold',keys=['rate','durationMs'];if(!dataFields(input,keys))fail(method,'$input');if(!bounded(input.rate,Number.MAX_SAFE_INTEGER))fail(method,'$input.rate');if(!bounded(input.durationMs,86400000))fail(method,'$input.durationMs');const product=output(method,'product',input.rate*input.durationMs),value=output(method,'value',product/3600000);return value}
function totalRate(input){const method='totalRate';if(!dataFields(input,['orderedRates']))fail(method,'$input');if(!denseFour(input.orderedRates))fail(method,'$input.orderedRates');let total=0;for(let index=0;index<4;index++){const value=input.orderedRates[index];if(!bounded(value,Number.MAX_SAFE_INTEGER))fail(method,`$input.orderedRates[${index}]`);total=output(method,'total',total+value)}return total}
function offlineTotals(input){const method='offlineTotals';if(!dataFields(input,['orderedLineTotals','pendingBefore']))fail(method,'$input');if(!denseFour(input.orderedLineTotals))fail(method,'$input.orderedLineTotals');let total=0;for(let index=0;index<4;index++){const value=input.orderedLineTotals[index];if(!finite(value)||value<0||Object.is(value,-0))fail(method,`$input.orderedLineTotals[${index}]`);total=output(method,'total',total+value)}if(!finite(input.pendingBefore)||input.pendingBefore<0)fail(method,'$input.pendingBefore');const pendingAfter=output(method,'pendingAfter',input.pendingBefore+total);return{total,pendingAfter}}

export const REFERENCE_CORE=Object.freeze({familyBuildingBonus,neutralHookBonus,buildingUpgradeCost,buildingRateComponents,durationGold,totalRate,offlineTotals});
export const REFERENCE_METHOD_ORDER=METHOD_ORDER;
export function evaluateReference(method,input){if(!METHOD_ORDER.includes(method))throw new Error('Unknown Phase 10B-2 reference method '+String(method));return REFERENCE_CORE[method](input)}

const floatBits=value=>{const bytes=Buffer.alloc(8);bytes.writeDoubleBE(value);return bytes.toString('hex')},decimal=value=>Object.is(value,-0)?'-0':String(value);
export function encodeValue(value,path='$'){
  if(value===undefined)return{'$undefined':true};if(typeof value==='number'){if(!Number.isFinite(value))throw new Error(path+' non-finite encoded value');if(!Number.isInteger(value)||Object.is(value,-0))return{'$float64':floatBits(value),decimal:decimal(value)};return value}if(value===null||typeof value==='string'||typeof value==='boolean')return value;
  if(Array.isArray(value)){if(!denseArray(value))throw new Error(path+' invalid encoded array');return value.map((item,index)=>encodeValue(item,`${path}[${index}]`))}
  if(!ordinary(value))throw new Error(path+' invalid encoded object');const pairs=[];for(const key of Reflect.ownKeys(value)){if(typeof key!=='string')throw new Error(path+' symbol key');const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor||!own(descriptor,'value')||!descriptor.enumerable)throw new Error(path+' accessor/non-enumerable');pairs.push([key,encodeValue(descriptor.value,`${path}.${key}`)])}return{'$object':pairs};
}
const canonicalRecord=(value,keys)=>keysExact(value,keys)&&keys.every(key=>dataProperty(value,key,{canonicalFlags:true}));
const canonicalArray=value=>denseArray(value,{canonicalFlags:true});
export function decodeValue(value,path='$'){
  if(value===null||typeof value==='string'||typeof value==='boolean')return value;if(typeof value==='number'){if(!Number.isInteger(value)||Object.is(value,-0))throw new Error(path+' raw noninteger');return value}if(Array.isArray(value)){if(!canonicalArray(value))throw new Error(path+' invalid encoded array');return value.map((item,index)=>decodeValue(item,`${path}[${index}]`))}if(!ordinary(value))throw new Error(path+' invalid encoded wrapper');
  if(keysExact(value,['$undefined'])){if(!canonicalRecord(value,['$undefined'])||value.$undefined!==true)throw new Error(path+' invalid undefined tag');return undefined}if(keysExact(value,['$float64','decimal'])){if(!canonicalRecord(value,['$float64','decimal'])||typeof value.$float64!=='string'||!/^[0-9a-f]{16}$/.test(value.$float64)||typeof value.decimal!=='string')throw new Error(path+' invalid Float64');const number=Buffer.from(value.$float64,'hex').readDoubleBE();if(!finite(number)||decimal(number)!==value.decimal||Number.isInteger(number)&&!Object.is(number,-0)&&!Object.is(number,0))throw new Error(path+' invalid Float64 text');return number}if(keysExact(value,['$object'])){if(!canonicalRecord(value,['$object'])||!canonicalArray(value.$object))throw new Error(path+' invalid object tag');const result={};for(const pair of value.$object){if(!canonicalArray(pair)||pair.length!==2||typeof pair[0]!=='string'||own(result,pair[0]))throw new Error(path+' invalid object pair');Object.defineProperty(result,pair[0],{value:decodeValue(pair[1],`${path}.${pair[0]}`),writable:true,enumerable:true,configurable:true})}return result}throw new Error(path+' ambiguous encoded wrapper');
}
const protoKind=value=>Array.isArray(value)&&Object.getPrototypeOf(value)===Array.prototype?'array':ordinary(value)?'object':'other';
export function exactValue(left,right){if(typeof left==='number'||typeof right==='number')return typeof left==='number'&&typeof right==='number'&&Object.is(left,right);if(left===null||right===null||typeof left!=='object'||typeof right!=='object')return left===right;const kind=protoKind(left);if(kind!==protoKind(right)||kind==='other'||kind==='array'&&(!denseArray(left)||!denseArray(right)))return false;const a=Reflect.ownKeys(left),b=Reflect.ownKeys(right);if(a.length!==b.length||!a.every((key,index)=>key===b[index]))return false;for(const key of a){const x=Object.getOwnPropertyDescriptor(left,key),y=Object.getOwnPropertyDescriptor(right,key);if(!x||!y||x.enumerable!==y.enumerable||x.configurable!==y.configurable||own(x,'value')!==own(y,'value'))return false;if(own(x,'value')){if(x.writable!==y.writable||!exactValue(x.value,y.value))return false}else if(x.get!==y.get||x.set!==y.set)return false}return true}
export function deepFreeze(value,seen=new Set(),path='$'){if(value===null||typeof value!=='object')return value;if(seen.has(value))throw new Error(path+' cyclic authority');if(Array.isArray(value)){if(!denseArray(value))throw new Error(path+' malformed authority array')}else if(!ordinary(value))throw new Error(path+' malformed authority object');seen.add(value);for(const key of Reflect.ownKeys(value)){if(Array.isArray(value)&&key==='length')continue;if(typeof key!=='string'||!dataProperty(value,key))throw new Error(path+' malformed authority property');deepFreeze(Object.getOwnPropertyDescriptor(value,key).value,seen,`${path}.${key}`)}seen.delete(value);return Object.freeze(value)}
export const referenceIdentity=Object.freeze({name:'phase-10b2-independent-gold-reference-v1',methodOrder:METHOD_ORDER,formulaOwner:'qa-only-independent-literals',productionImports:false});
