import {readFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import vm from 'node:vm';

const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const TRACE_PATH=resolve(ROOT,'qa/phase-10b2/predecessor-traces.json');
const ARTIFACT_PATH=resolve(ROOT,'index.html');
const ARTIFACT_SHA='717160cdddc5fa540532cdebd29f30d127ded2f761edd677684a2609fde9a4ed',ARTIFACT_BYTES=18916682;
const TRACE_SHA='74feec74ff6f9efe07ca47cb2b0fcaaca8ab80dab71961fd2f1625f270209136',TRACE_BYTES=557500;
const SOURCE_BASE='fff84f7dfe87b23040edaa31f07f5f3c9181babf',CONTRACT_COMMIT='84554b03526b00dde3b106f17d724578a19da95a';
const METHODS=['familyBuildingBonus','neutralHookBonus','buildingUpgradeCost','buildingRateComponents','durationGold','totalRate','offlineTotals'];
const BUILDINGS=['training','command','archives','hearth'],FAMILIES=['elara','tamsin','isolde'];
const BASE={training:7200,command:6500,archives:5600,hearth:6100},SPECIALTY={elara:'hearth',tamsin:'training',isolde:'archives'};
const CONFIG=Object.freeze({levelGrowth:1.15,upgradeBase:15000,upgradeGrowth:1.7,oathCap:.30,family:{base:.01,intimacyRate:.0002,intimacyCap:.10,rarityRate:.02,specialtyAmount:.01,cap:.20}});
const ALLOCATION={family:6,neutral:2,upgrade:4,'building-rate':8,'duration-gold':4,'total-rate':3,'offline-totals':5};
const ARGUMENT_PATHS={family:['$.buildingId','$.state'],neutral:['$.name'],upgrade:['$.level'],'building-rate':['$.buildingId','$.state','$.at'],'duration-gold':['$.at','$.state'],'total-rate':['$.state','$.at'],'offline-totals':['$.at','$.state']};
const SELECTORS={family:'familyBuildingBonusComponents',neutral:'economyHookBonus',upgrade:'buildingUpgradeCost','building-rate':'buildingRateComponents','duration-gold':'offlineClaimPreview','total-rate':'totalRate','offline-totals':'offlineClaimPreview'};
const sha=value=>createHash('sha256').update(value).digest('hex'),own=(value,key)=>Object.prototype.hasOwnProperty.call(value,key);
const ordinary=value=>{if(value===null||Object.prototype.toString.call(value)!=='[object Object]')return false;const prototype=Object.getPrototypeOf(value);return prototype!==null&&Object.getPrototypeOf(prototype)===null&&own(prototype,'constructor')&&typeof prototype.constructor==='function'&&prototype.constructor.name==='Object'&&prototype.constructor.prototype===prototype};
const exactKeys=(value,keys)=>{const actual=Reflect.ownKeys(value);return actual.length===keys.length&&actual.every((key,index)=>key===keys[index])};
const dataDescriptor=(value,key,{enumerable,writable,configurable})=>{const descriptor=Object.getOwnPropertyDescriptor(value,key);return Boolean(descriptor)&&own(descriptor,'value')&&!own(descriptor,'get')&&!own(descriptor,'set')&&descriptor.enumerable===enumerable&&descriptor.writable===writable&&descriptor.configurable===configurable};
const denseArray=value=>{if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype)return false;const keys=[...value.keys()].map(String).concat('length');if(!exactKeys(value,keys))return false;for(let index=0;index<value.length;index++){const descriptor=Object.getOwnPropertyDescriptor(value,String(index));if(!descriptor||!own(descriptor,'value')||!descriptor.enumerable||own(descriptor,'get')||own(descriptor,'set'))return false}const length=Object.getOwnPropertyDescriptor(value,'length');return Boolean(length)&&own(length,'value')&&!length.enumerable&&!length.configurable&&own(length,'writable')};
const canonicalRecord=(value,keys)=>ordinary(value)&&exactKeys(value,keys)&&keys.every(key=>dataDescriptor(value,key,{enumerable:true,writable:true,configurable:true}));
const canonicalArray=(value,length=null)=>{if(!denseArray(value)||length!==null&&value.length!==length)return false;for(let index=0;index<value.length;index++)if(!dataDescriptor(value,String(index),{enumerable:true,writable:true,configurable:true}))return false;return dataDescriptor(value,'length',{enumerable:false,writable:true,configurable:false})};
const floatBits=value=>{const bytes=Buffer.alloc(8);bytes.writeDoubleBE(value);return bytes.toString('hex')},decimal=value=>Object.is(value,-0)?'-0':String(value);

function encode(value,path='$'){
  if(value===undefined)return{'$undefined':true};
  if(typeof value==='number'){if(!Number.isFinite(value))throw new Error(path+' non-finite number');if(!Number.isInteger(value)||Object.is(value,-0))return{'$float64':floatBits(value),decimal:decimal(value)};return value}
  if(value===null||typeof value==='string'||typeof value==='boolean')return value;
  if(Array.isArray(value)){if(!denseArray(value))throw new Error(path+' noncanonical source array');return value.map((item,index)=>encode(item,`${path}[${index}]`))}
  if(!ordinary(value))throw new Error(path+' non-ordinary source object');
  const pairs=[];for(const key of Reflect.ownKeys(value)){if(typeof key!=='string')throw new Error(path+' symbol key');const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor||!own(descriptor,'value')||!descriptor.enumerable||own(descriptor,'get')||own(descriptor,'set'))throw new Error(path+' invalid source property '+String(key));pairs.push([key,encode(descriptor.value,`${path}.${key}`)])}return{'$object':pairs};
}
function decode(value,path='$'){
  if(value===null||typeof value==='string'||typeof value==='boolean')return value;
  if(typeof value==='number'){if(!Number.isInteger(value)||Object.is(value,-0))throw new Error(path+' raw number is not a canonical integer');return value}
  if(Array.isArray(value)){if(!canonicalArray(value))throw new Error(path+' malformed encoded array');const result=[];for(let index=0;index<value.length;index++)result.push(decode(value[index],`${path}[${index}]`));return result}
  if(!ordinary(value))throw new Error(path+' encoded wrapper is not ordinary');
  if(exactKeys(value,['$undefined'])){if(!canonicalRecord(value,['$undefined'])||value.$undefined!==true)throw new Error(path+' invalid undefined tag');return undefined}
  if(exactKeys(value,['$float64','decimal'])){if(!canonicalRecord(value,['$float64','decimal'])||typeof value.$float64!=='string'||!/^[0-9a-f]{16}$/.test(value.$float64)||typeof value.decimal!=='string')throw new Error(path+' invalid Float64 wrapper');const number=Buffer.from(value.$float64,'hex').readDoubleBE();if(!Number.isFinite(number)||value.decimal!==decimal(number)||Number.isInteger(number)&&!Object.is(number,-0)&&!Object.is(number,0))throw new Error(path+' noncanonical Float64 wrapper');return number}
  if(exactKeys(value,['$object'])){if(!canonicalRecord(value,['$object'])||!canonicalArray(value.$object))throw new Error(path+' invalid object wrapper');const result={};for(let index=0;index<value.$object.length;index++){const pair=value.$object[index];if(!canonicalArray(pair,2)||typeof pair[0]!=='string'||own(result,pair[0]))throw new Error(path+' invalid object pair');Object.defineProperty(result,pair[0],{value:decode(pair[1],`${path}.${pair[0]}`),writable:true,enumerable:true,configurable:true})}return result}
  throw new Error(path+' ambiguous or malformed encoded wrapper');
}
const canonicalClone=value=>JSON.parse(JSON.stringify(value));
const canonicalEncoded=value=>{try{return JSON.stringify(encode(decode(value)))===JSON.stringify(value)}catch{return false}};

function prototypeKind(value){if(Array.isArray(value)){const prototype=Object.getPrototypeOf(value);return prototype&&Object.getPrototypeOf(prototype)&&prototype.constructor?.name==='Array'&&prototype.constructor.prototype===prototype?'array':'invalid-array'}return ordinary(value)?'ordinary':'other'}
function exact(left,right){
  if(typeof left==='number'||typeof right==='number')return typeof left==='number'&&typeof right==='number'&&Object.is(left,right);
  if(left===null||right===null||typeof left!=='object'||typeof right!=='object')return left===right;
  const leftKind=prototypeKind(left),rightKind=prototypeKind(right);if(leftKind!==rightKind||!['array','ordinary'].includes(leftKind))return false;
  const leftKeys=Reflect.ownKeys(left),rightKeys=Reflect.ownKeys(right);if(leftKeys.length!==rightKeys.length||!leftKeys.every((key,index)=>key===rightKeys[index]))return false;
  for(const key of leftKeys){const a=Object.getOwnPropertyDescriptor(left,key),b=Object.getOwnPropertyDescriptor(right,key);if(!a||!b||a.enumerable!==b.enumerable||a.configurable!==b.configurable)return false;const aData=own(a,'value'),bData=own(b,'value');if(aData!==bData)return false;if(aData){if(a.writable!==b.writable||!exact(a.value,b.value))return false}else if(a.get!==b.get||a.set!==b.set)return false}
  return true;
}
function deepFreeze(value,seen=new Set()){if(value===null||typeof value!=='object'||seen.has(value))return value;if(!Array.isArray(value)&&!ordinary(value)||Array.isArray(value)&&!denseArray(value))throw new Error('Cannot freeze malformed authority');seen.add(value);for(const key of Reflect.ownKeys(value)){const descriptor=Object.getOwnPropertyDescriptor(value,key);if(descriptor&&own(descriptor,'value'))deepFreeze(descriptor.value,seen)}return Object.freeze(value)}
const fingerprint=value=>sha(Buffer.from(JSON.stringify(encode(value))));
const throws=fn=>{try{fn();return false}catch{return true}};

// Identity refusal is deliberately before JSON.parse and before any VM/source evaluation.
const artifact=readFileSync(ARTIFACT_PATH);if(artifact.length!==ARTIFACT_BYTES||sha(artifact)!==ARTIFACT_SHA)throw new Error('Phase 10B-2 verifier refuses unaccepted production bytes');
const traceRaw=readFileSync(TRACE_PATH);if(traceRaw.length!==TRACE_BYTES||sha(traceRaw)!==TRACE_SHA)throw new Error('Phase 10B-2 verifier refuses altered predecessor trace bytes');
const traceFile=JSON.parse(traceRaw);

let passed=0;const failures=[];function check(ok,label){if(ok)passed++;else failures.push(label)}
check(artifact.length===ARTIFACT_BYTES&&sha(artifact)===ARTIFACT_SHA&&traceRaw.length===TRACE_BYTES&&sha(traceRaw)===TRACE_SHA,'hard identity refusal precedes parse/evaluation');
const topologyExact=canonicalRecord(traceFile,['traceSchemaVersion','phase','status','source','encoding','methodOrder','allocation','traceCount','traces'])&&canonicalRecord(traceFile.source,['baseCommit','artifactSha256','artifactByteLength','contractCommit','timeZone','fixedClock'])&&canonicalRecord(traceFile.encoding,['nonintegerAndSignedZero','undefined','null','array','ordinaryObject','objectOrder'])&&canonicalRecord(traceFile.allocation,Object.keys(ALLOCATION))&&canonicalArray(traceFile.methodOrder,7)&&canonicalArray(traceFile.traces,32);
check(topologyExact&&traceFile.traceSchemaVersion===1&&traceFile.phase==='10B-2'&&traceFile.status==='FROZEN PREDECESSOR AUTHORITY'&&traceFile.source.baseCommit===SOURCE_BASE&&traceFile.source.artifactSha256===ARTIFACT_SHA&&traceFile.source.artifactByteLength===ARTIFACT_BYTES&&traceFile.source.contractCommit===CONTRACT_COMMIT&&traceFile.source.timeZone==='America/Phoenix'&&traceFile.source.fixedClock===1788026400000,'trace authority metadata and exact topology');
const derivedAllocation=Object.fromEntries(Object.keys(ALLOCATION).map(key=>[key,0]));for(const trace of traceFile.traces)if(own(derivedAllocation,trace.operation))derivedAllocation[trace.operation]++;
check(exact(traceFile.methodOrder,METHODS)&&exact(traceFile.allocation,ALLOCATION)&&exact(derivedAllocation,ALLOCATION)&&traceFile.traceCount===32&&traceFile.traces.length===32,'declared and trace-derived allocation/method order');
check(new Set(traceFile.traces.map(trace=>trace.id)).size===32&&traceFile.traces.every((trace,index)=>trace.ordinal===index+1),'trace IDs and ordinals');
const traceShapeById=new Map(traceFile.traces.map(trace=>[trace.id,canonicalRecord(trace,['id','ordinal','operation','source','fixture','wrapper','predecessor','arithmetic','expectedKernelCalls','aggregateCallCounts','numericEncoding','formulaNote'])&&canonicalRecord(trace.source,['baseCommit','artifactSha256','artifactByteLength','contractCommit'])&&canonicalRecord(trace.wrapper,['selector','argumentPaths','fixedClock'])&&canonicalArray(trace.wrapper.argumentPaths)&&canonicalRecord(trace.predecessor,['outcome','fullReturn'])&&canonicalRecord(trace.arithmetic,['method','input','projection'])&&canonicalArray(trace.expectedKernelCalls)&&trace.expectedKernelCalls.every(call=>canonicalRecord(call,['ordinal','method','argument']))&&canonicalRecord(trace.aggregateCallCounts,METHODS)]));
const encodedCanonicalById=new Map(traceFile.traces.map(trace=>[trace.id,[trace.fixture,trace.predecessor.fullReturn,trace.arithmetic.input,trace.arithmetic.projection,...trace.expectedKernelCalls.map(call=>call.argument)].every(canonicalEncoded)]));

const roundTripSource=[undefined,null,[],[undefined,null],{'0':'a'},['a'],{'$undefined':true}],roundTripEncoded=encode(roundTripSource),roundTripA=decode(canonicalClone(roundTripEncoded)),roundTripB=decode(canonicalClone(roundTripEncoded));
check(canonicalEncoded(roundTripEncoded)&&roundTripA!==roundTripB&&roundTripA[2]!==roundTripB[2]&&roundTripA[4]!==roundTripB[4]&&!Array.isArray(roundTripA[4])&&Array.isArray(roundTripA[5])&&exact(roundTripA,roundTripB)&&Object.getPrototypeOf(roundTripA[4])===Object.prototype&&Object.getPrototypeOf(roundTripA[5])===Array.prototype&&roundTripA[6].$undefined===true,'canonical disjoint encodedValue round trips');
const sparse=[];sparse.length=1;const extra=[1];extra.extra=true;const accessorArray=[1];Object.defineProperty(accessorArray,'0',{get(){return 1},enumerable:true,configurable:true});const customArray=[1];Object.setPrototypeOf(customArray,{});class Custom{constructor(){this.value=1}}const nullPrototype=Object.create(null),customPrototype=Object.create({});customPrototype.value=1;const symbolObject={value:1};symbolObject[Symbol('x')]=2;const accessorObject={};Object.defineProperty(accessorObject,'value',{get(){return 1},enumerable:true,configurable:true});const hiddenObject={};Object.defineProperty(hiddenObject,'value',{value:1,enumerable:false,writable:true,configurable:true});const badUndefined=Object.create({});badUndefined.$undefined=true;const reorderedFloat={decimal:'0.5','$float64':'3fe0000000000000'};const extraTag={'$undefined':true,extra:true};const badPair={'$object':[['a',1,,]]};
check([()=>encode(sparse),()=>encode(extra),()=>encode(accessorArray),()=>encode(customArray),()=>encode(new Custom()),()=>encode(nullPrototype),()=>encode(customPrototype),()=>encode(symbolObject),()=>encode(accessorObject),()=>encode(hiddenObject),()=>decode(badUndefined),()=>decode(reorderedFloat),()=>decode(extraTag),()=>decode(badPair)].every(throws),'malformed encodedValue shapes fail closed');
const descriptorLeft={a:1,b:[2]},descriptorReordered={b:[2],a:1},descriptorCustom=Object.create({});descriptorCustom.a=1;descriptorCustom.b=[2];const descriptorAccessor={b:[2]};Object.defineProperty(descriptorAccessor,'a',{get(){return 1},enumerable:true,configurable:true});const descriptorFlags={a:1,b:[2]};Object.defineProperty(descriptorFlags,'a',{value:1,enumerable:true,writable:false,configurable:true});const descriptorSparse={a:1,b:[]};descriptorSparse.b.length=1;const descriptorExtra={a:1,b:[2]};descriptorExtra.b.extra=3;
check(!exact({z:+0},{z:-0})&&!exact(descriptorLeft,descriptorReordered)&&!exact(descriptorLeft,descriptorCustom)&&!exact(descriptorLeft,descriptorAccessor)&&!exact(descriptorLeft,descriptorFlags)&&!exact(descriptorLeft,descriptorSparse)&&!exact(descriptorLeft,descriptorExtra),'exact comparator rejects prototype/key/descriptor/array/Float64 drift');
const frozenControl=deepFreeze({a:[{b:-0}],tag:{'$undefined':true}}),frozenBefore=fingerprint(frozenControl),mutationThrows=throws(()=>{frozenControl.a[0].b=0})&&throws(()=>{frozenControl.a.push(2)})&&throws(()=>{frozenControl.tag.extra=true});const mutatedObservation={a:[{b:0}],tag:{'$undefined':true}};
check(mutationThrows&&Object.isFrozen(frozenControl)&&Object.isFrozen(frozenControl.a)&&Object.isFrozen(frozenControl.a[0])&&frozenBefore===fingerprint(frozenControl)&&!exact(canonicalClone(encode(frozenControl)),canonicalClone(encode(mutatedObservation))),'deep-freeze fingerprints and mutation negative control');
deepFreeze(traceFile);

const BOOT='const report=load();render();installQaBridge();if(report)runtimeSetTimeout(()=>openOffline(report),250);';
const FACADE=`Object.defineProperty(window,'__P10B2_PREDECESSOR__',{value:Object.freeze({family:(id,state)=>familyBuildingBonusComponents(id,state),hook:name=>economyHookBonus(name),upgrade:level=>buildingUpgradeCost(level),rate:(id,state,at)=>buildingRateComponents(id,state,at),total:(state,at)=>totalRate(state,at),offline:(at,state)=>offlineClaimPreview(at,state)}),enumerable:false,writable:false,configurable:false});`;
const html=artifact.toString('utf8');if(html.split(BOOT).length-1!==1)throw new Error('Predecessor boot anchor is not exact-once');const transformed=html.replace(BOOT,FACADE),restored=Buffer.from(transformed.replace(FACADE,BOOT));if(!restored.equals(artifact))throw new Error('Predecessor transform did not restore exact bytes');
const scriptOpen=transformed.indexOf('<script>'),scriptClose=transformed.lastIndexOf('</script>');if(scriptOpen<0||scriptClose<scriptOpen)throw new Error('Production script boundary is invalid');const script=transformed.slice(scriptOpen+8,scriptClose);
const effects={storage:[],ui:[],timer:[],network:[],listeners:[]},deny=(bucket,name)=>(...args)=>{effects[bucket].push([name,args.length]);throw new Error('prohibited '+name)},captureListener=scope=>(name,handler)=>{effects.listeners.push([scope,name,typeof handler])};
const storage=Object.freeze({getItem:deny('storage','getItem'),setItem:deny('storage','setItem'),removeItem:deny('storage','removeItem')}),window={__EVERSTEAD_RUNTIME__:Object.freeze({storage,clock:Object.freeze({now:()=>traceFile.source.fixedClock,setTimeout:deny('timer','runtime-setTimeout'),clearTimeout:deny('timer','runtime-clearTimeout')})}),localStorage:Object.freeze({native:true}),location:Object.freeze({protocol:'https:',hostname:'invalid.example',search:''}),URLSearchParams,addEventListener:captureListener('window'),confirm:deny('ui','confirm'),open:deny('ui','open'),fetch:deny('network','fetch'),XMLHttpRequest:deny('network','XMLHttpRequest'),WebSocket:deny('network','WebSocket')};
const document=new Proxy(Object.freeze({addEventListener:captureListener('document')}),{get(target,key){if(key in target)return target[key];return deny('ui','document.'+String(key))}}),context={window,document,globalThis:null,URLSearchParams,console:Object.freeze({log(){},warn:deny('ui','warn'),error:deny('ui','error')}),addEventListener:window.addEventListener,setTimeout:deny('timer','setTimeout'),clearTimeout:deny('timer','clearTimeout'),fetch:window.fetch,XMLHttpRequest:window.XMLHttpRequest,WebSocket:window.WebSocket};
context.globalThis=context;window.window=window;window.document=document;vm.createContext(context,{codeGeneration:{strings:false,wasm:false}});new vm.Script(script,{filename:'accepted-index.phase10b2-trace-verify.js'}).runInContext(context,{timeout:30000});const production=window.__P10B2_PREDECESSOR__,inheritedHooks=['__EVERSTEAD_QA__','__EVERSTEAD_PHASE6_QA__','__EVERSTEAD_PHASE7_QA__','__EVERSTEAD_PHASE9_QA__'].filter(key=>Reflect.has(window,key));
const realmOkay=Boolean(production)&&!Object.keys(window).includes('__P10B2_PREDECESSOR__')&&Object.values(effects).slice(0,4).every(list=>list.length===0)&&exact(effects.listeners,[['window','storage','function'],['window','storage','function'],['window','storage','function']])&&inheritedHooks.length===0&&restored.length===artifact.length&&sha(restored)===ARTIFACT_SHA;if(!realmOkay)console.error('Realm diagnostic '+JSON.stringify({effects,inheritedHooks,facade:Boolean(production),facadeEnumerable:Object.keys(window).includes('__P10B2_PREDECESSOR__'),restored:restored.length===artifact.length&&sha(restored)===ARTIFACT_SHA}));
check(realmOkay,'isolated realm captures/refuses side effects, listeners, inherited hooks, and restores bytes');

function familyInput(id,state){const assigned=FAMILIES.find(familyId=>state.family[familyId].assignedBuildingId===id),config=CONFIG.family;if(!assigned)return{assigned:false,intimacy:0,rarity:0,specialtyMatch:false,base:config.base,intimacyRate:config.intimacyRate,intimacyCap:config.intimacyCap,rarityRate:config.rarityRate,specialtyAmount:config.specialtyAmount,cap:config.cap};const item=state.family[assigned];return{assigned:true,intimacy:item.intimacy,rarity:item.rarity,specialtyMatch:SPECIALTY[assigned]===id,base:config.base,intimacyRate:config.intimacyRate,intimacyCap:config.intimacyCap,rarityRate:config.rarityRate,specialtyAmount:config.specialtyAmount,cap:config.cap}}
function familyReference(input){if(!input.assigned)return{baseBonus:0,intimacyBonus:0,rarityBonus:0,specialtyBonus:0,uncappedBonus:0,bonus:0,multiplier:1};const baseBonus=input.base,intimacyBonus=Math.min(input.intimacyCap,input.intimacy*input.intimacyRate),rarityBonus=input.rarityRate*(input.rarity-1),specialtyBonus=input.specialtyMatch?input.specialtyAmount:0,uncappedBonus=baseBonus+intimacyBonus+rarityBonus+specialtyBonus,bonus=Math.min(input.cap,uncappedBonus);return{baseBonus,intimacyBonus,rarityBonus,specialtyBonus,uncappedBonus,bonus,multiplier:1+bonus}}
const upgradeInput=level=>({base:CONFIG.upgradeBase,growth:CONFIG.upgradeGrowth,level}),upgradeReference=input=>Math.round(input.base*Math.pow(input.growth,input.level-1));
function dayKey(at){const date=new Date(at);return `D${date.getFullYear()}-${date.getMonth()+1}-${date.getDate()}`}
function nextMidnight(at){const next=new Date(at);next.setHours(24,0,0,0);const value=next.getTime();return value>at?value:at+86400000}
function rateInput(id,state,at){const family=familyReference(familyInput(id,state)),building=state.buildings[id],oathBoost=building.boostDay===dayKey(at)?Math.min(CONFIG.oathCap,Math.max(0,building.boost)):0;return{base:BASE[id],level:building.level,levelGrowth:CONFIG.levelGrowth,familyAssignmentMultiplier:family.multiplier,fellowRosterBonus:0,companionRosterBonus:0,overallDayBonus:0,oathBoost}}
function rateReference(input){const levelMultiplier=Math.pow(input.levelGrowth,input.level-1),fellowRosterMultiplier=1+input.fellowRosterBonus,companionRosterMultiplier=1+input.companionRosterBonus,overallDayMultiplier=1+input.overallDayBonus,characterEconomyMultiplier=input.familyAssignmentMultiplier*fellowRosterMultiplier*companionRosterMultiplier*overallDayMultiplier,oathMultiplier=1+input.oathBoost,rate=input.base*levelMultiplier*characterEconomyMultiplier*oathMultiplier;return{levelMultiplier,fellowRosterMultiplier,companionRosterMultiplier,overallDayMultiplier,characterEconomyMultiplier,oathMultiplier,rate}}
const durationReference=input=>input.rate*input.durationMs/3600000,totalReference=input=>input.orderedRates.reduce((sum,value)=>sum+value,0),offlineReference=input=>{const total=input.orderedLineTotals.reduce((sum,value)=>sum+value,0);return{total,pendingAfter:input.pendingBefore+total}};
const addCall=(list,method,argument)=>list.push({ordinal:list.length+1,method,argument});
function buildingCalls(list,id,state,at,durationMs=null){addCall(list,'familyBuildingBonus',familyInput(id,state));for(const ignored of ['fellowRoster','companionRoster','overallDay'])addCall(list,'neutralHookBonus',0);const rate=rateInput(id,state,at);addCall(list,'buildingRateComponents',rate);addCall(list,'buildingUpgradeCost',upgradeInput(state.buildings[id].level));if(durationMs!==null)addCall(list,'durationGold',{rate:rateReference(rate).rate,durationMs})}
function segmentsFor(start,end){const segments=[];let cursor=start;while(cursor<end){const next=Math.min(end,nextMidnight(cursor));segments.push({start:cursor,end:next,durationMs:next-cursor});cursor=next}return segments}
function offlineCalls(state,at){if(at<=state.lastGoldAt)return[];const end=Math.min(at,state.lastGoldAt+86400000),calls=[],lines=Object.fromEntries(BUILDINGS.map(id=>[id,0]));for(const segment of segmentsFor(state.lastGoldAt,end))for(const id of BUILDINGS){buildingCalls(calls,id,state,segment.start,segment.durationMs);lines[id]+=durationReference({rate:rateReference(rateInput(id,state,segment.start)).rate,durationMs:segment.durationMs})}addCall(calls,'offlineTotals',{orderedLineTotals:BUILDINGS.map(id=>lines[id]),pendingBefore:state.pendingGold});return calls}
function expectedCalls(trace,fixture){if(trace.operation==='family'){const calls=[];addCall(calls,'familyBuildingBonus',familyInput(fixture.buildingId,fixture.state));return calls}if(trace.operation==='neutral'){const calls=[];addCall(calls,'neutralHookBonus',fixture.name==='fellowRoster'?0:undefined);return calls}if(trace.operation==='upgrade'){const calls=[];addCall(calls,'buildingUpgradeCost',upgradeInput(fixture.level));return calls}if(trace.operation==='building-rate'){const calls=[];buildingCalls(calls,fixture.buildingId,fixture.state,fixture.at);return calls}if(trace.operation==='duration-gold')return fixture.zeroDuration?[]:offlineCalls(fixture.state,fixture.at);if(trace.operation==='total-rate'){const calls=[];for(const id of BUILDINGS)buildingCalls(calls,id,fixture.state,fixture.at);addCall(calls,'totalRate',{orderedRates:BUILDINGS.map(id=>rateReference(rateInput(id,fixture.state,fixture.at)).rate)});return calls}if(trace.operation==='offline-totals')return offlineCalls(fixture.state,fixture.at);throw new Error('Unknown operation '+trace.operation)}
function resolvePath(fixture,path){if(typeof path!=='string'||!path.startsWith('$.'))throw new Error('Invalid literal wrapper path');let value=fixture;for(const key of path.slice(2).split('.')){if(!ordinary(value)||!own(value,key))throw new Error('Wrapper path does not resolve: '+path);value=value[key]}return value}
function invoke(trace,fixture){const args=trace.wrapper.argumentPaths.map(path=>resolvePath(fixture,path));if(trace.wrapper.selector==='familyBuildingBonusComponents')return production.family(...args);if(trace.wrapper.selector==='economyHookBonus')return production.hook(...args);if(trace.wrapper.selector==='buildingUpgradeCost')return production.upgrade(...args);if(trace.wrapper.selector==='buildingRateComponents')return production.rate(...args);if(trace.wrapper.selector==='totalRate')return production.total(...args);if(trace.wrapper.selector==='offlineClaimPreview')return production.offline(...args);throw new Error('Unknown selector '+trace.wrapper.selector)}
function projection(trace,fixture,full){if(trace.operation==='family')return Object.fromEntries(['baseBonus','intimacyBonus','rarityBonus','specialtyBonus','uncappedBonus','bonus','multiplier'].map(key=>[key,full[key]]));if(['neutral','upgrade','total-rate'].includes(trace.operation))return full;if(trace.operation==='building-rate')return Object.fromEntries(['levelMultiplier','fellowRosterMultiplier','companionRosterMultiplier','overallDayMultiplier','characterEconomyMultiplier','oathMultiplier','rate'].map(key=>[key,full[key]]));if(trace.operation==='duration-gold')return fixture.zeroDuration?0:full.segments[fixture.segmentIndex].values[fixture.buildingId];return{total:full.total,pendingAfter:full.pendingAfter}}
function independent(method,input){if(method==='familyBuildingBonus')return familyReference(input);if(method==='neutralHookBonus')return typeof input==='number'&&Number.isFinite(input)&&input>0?input:0;if(method==='buildingUpgradeCost')return upgradeReference(input);if(method==='buildingRateComponents')return rateReference(input);if(method==='durationGold')return durationReference(input);if(method==='totalRate')return totalReference(input);return offlineReference(input)}
function callsAggregate(calls){const aggregate=Object.fromEntries(METHODS.map(method=>[method,0]));for(const call of calls)aggregate[call.method]++;return aggregate}
function boundCall(trace,fixture,calls){if(trace.operation==='duration-gold'&&fixture.zeroDuration)return null;if(trace.operation==='duration-gold'){const buildingIndex=BUILDINGS.indexOf(fixture.buildingId),index=fixture.segmentIndex*BUILDINGS.length*7+buildingIndex*7+6;return calls[index]}if(trace.operation==='total-rate'||trace.operation==='offline-totals')return calls.at(-1);return calls.find(call=>call.method===trace.arithmetic.method)}
const authorityFingerprint=authority=>sha(Buffer.from(JSON.stringify(authority.map(value=>encode(value)))));

for(const trace of traceFile.traces){
  const pathsExact=exact(canonicalClone(trace.wrapper.argumentPaths),ARGUMENT_PATHS[trace.operation])&&trace.wrapper.fixedClock===traceFile.source.fixedClock;
  check(traceShapeById.get(trace.id)&&encodedCanonicalById.get(trace.id)&&pathsExact&&trace.wrapper.selector===SELECTORS[trace.operation]&&trace.predecessor.outcome==='return'&&trace.numericEncoding==='inline-float64-bits-and-decimal'&&typeof trace.formulaNote==='string'&&trace.formulaNote.length>0&&trace.source.baseCommit===SOURCE_BASE&&trace.source.artifactSha256===ARTIFACT_SHA&&trace.source.artifactByteLength===ARTIFACT_BYTES&&trace.source.contractCommit===CONTRACT_COMMIT,trace.id+' canonical topology/encoding/source/selector paths/clock');
  const candidateFixture=deepFreeze(decode(canonicalClone(trace.fixture))),referenceFixture=deepFreeze(decode(canonicalClone(trace.fixture))),arithmeticInput=deepFreeze(decode(canonicalClone(trace.arithmetic.input))),expectedEncoded=deepFreeze(canonicalClone(trace.predecessor.fullReturn)),projectionEncoded=deepFreeze(canonicalClone(trace.arithmetic.projection)),frozenCalls=deepFreeze(trace.expectedKernelCalls.map(call=>({ordinal:call.ordinal,method:call.method,argument:decode(canonicalClone(call.argument))})));
  if(candidateFixture===referenceFixture||candidateFixture.state&&candidateFixture.state===referenceFixture.state)throw new Error(trace.id+' candidate/reference fixture alias');
  const planned=deepFreeze(expectedCalls(trace,referenceFixture)),binding=boundCall(trace,referenceFixture,planned),zeroException=trace.operation==='duration-gold'&&referenceFixture.zeroDuration,zeroInput=deepFreeze({rate:7200,durationMs:0}),binds=zeroException?planned.length===0&&exact(arithmeticInput,zeroInput):Boolean(binding)&&binding.method===trace.arithmetic.method&&exact(binding.argument,arithmeticInput),reference=deepFreeze(independent(trace.arithmetic.method,arithmeticInput)),referenceProjection=deepFreeze(decode(canonicalClone(projectionEncoded)));
  const authority=[candidateFixture,referenceFixture,arithmeticInput,expectedEncoded,projectionEncoded,frozenCalls,planned,reference,referenceProjection,deepFreeze(canonicalClone(trace.wrapper.argumentPaths))],before=authorityFingerprint(authority),observed=invoke(trace,candidateFixture),afterCandidate=authorityFingerprint(authority),frozenExpected=decode(canonicalClone(expectedEncoded)),candidateProjection=decode(canonicalClone(projectionEncoded));
  check(before===afterCandidate&&exact(observed,frozenExpected)&&exact(projection(trace,candidateFixture,observed),candidateProjection),trace.id+' immutable predecessor full return/projection');
  check(binds&&exact(reference,referenceProjection),trace.id+' independently bound arithmetic input/projection');
  const finalFingerprint=authorityFingerprint(authority);
  check(before===finalFingerprint&&exact(planned,frozenCalls)&&exact(callsAggregate(planned),canonicalClone(trace.aggregateCallCounts)),trace.id+' immutable ordered call record/count');
}

const expectedChecks=137,total=passed+failures.length;
if(total!==expectedChecks)failures.push(`internal check total ${total}/${expectedChecks}`);
if(failures.length){console.error(`Phase 10B-2 predecessor trace freeze: ${passed}/${expectedChecks} passed, ${failures.length} failed`);for(const failure of failures)console.error('FAIL '+failure);process.exit(1)}
console.log(`Phase 10B-2 predecessor trace freeze: ${passed}/${expectedChecks} passed, 0 failed`);
console.log(`Traces: ${traceFile.traceCount}; allocation: ${JSON.stringify(derivedAllocation)}`);
console.log(`Trace SHA-256: ${TRACE_SHA}; bytes: ${TRACE_BYTES}`);
console.log(`Production SHA-256: ${ARTIFACT_SHA}; bytes: ${ARTIFACT_BYTES}`);
