import {readFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {evaluateReference,encodeValue,decodeValue,exactValue,deepFreeze} from './reference-model.mjs';
import {probeIdentity,createOutputRealm,createCallTraceRealm,createMutationRealm,evaluateWrapperTrace,evaluateKernel,sourceBoundary} from './production-probe.mjs';

const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),QA=resolve(ROOT,'qa/phase-10b2');
const sha=value=>createHash('sha256').update(value).digest('hex'),read=name=>readFileSync(resolve(QA,name)),json=name=>JSON.parse(read(name));
const EXPECTED={index:['717160cdddc5fa540532cdebd29f30d127ded2f761edd677684a2609fde9a4ed',18916682],traces:['74feec74ff6f9efe07ca47cb2b0fcaaca8ab80dab71961fd2f1625f270209136',557500],scenarios:['b66220150b3442fc9589655d197d1919274468f01d7e0605b56a7b9038f02245',126224],registry:['230ee234ecc5d13d5f8c834ee8df0542968c84e683f11a6a21b6a834d3b0c8da',96777]};
for(const [name,file]of [['traces','predecessor-traces.json'],['scenarios','scenarios.json'],['registry','row-registry.json']]){const raw=read(file);if(raw.length!==EXPECTED[name][1]||sha(raw)!==EXPECTED[name][0])throw new Error(`Phase 10B-2 focused verifier refuses altered ${name}`)}
const index=readFileSync(resolve(ROOT,'index.html')),traces=json('predecessor-traces.json'),scenarios=json('scenarios.json'),registry=json('row-registry.json'),identity=probeIdentity(),preimage=identity.mode==='preimage';
if(preimage&&(index.length!==EXPECTED.index[1]||sha(index)!==EXPECTED.index[0]))throw new Error('Phase 10B-2 preimage identity mismatch');
const protectedFiles=['index.html','predecessor-traces.json','scenarios.json','row-registry.json'],pathFor=name=>name==='index.html'?resolve(ROOT,name):resolve(QA,name),before=new Map(protectedFiles.map(name=>[name,sha(readFileSync(pathFor(name))) ]));
const results=new Map(),record=(id,status,evidence)=>{if(results.has(id))throw new Error('Duplicate focused row '+id);results.set(id,{id,status,evidence})};
const methodOrder=['familyBuildingBonus','neutralHookBonus','buildingUpgradeCost','buildingRateComponents','durationGold','totalRate','offlineTotals'],encoded=value=>decodeValue(structuredClone(value)),frozen=value=>deepFreeze(encoded(value));
const canonicalEncoded=value=>{try{return JSON.stringify(encodeValue(decodeValue(structuredClone(value))))===JSON.stringify(value)}catch{return false}},fingerprint=value=>sha(Buffer.from(JSON.stringify(encodeValue(value))));
if(registry.total!==400||registry.rows.length!==400||new Set(registry.rows.map(row=>row.id)).size!==400)throw new Error('Focused row registry total/uniqueness mismatch');
if(JSON.stringify(registry.categoryAllocation)!==JSON.stringify({'static/startup':32,'numeric/operator':96,'frozen predecessor traces':128,'fail-closed/persistence':96,'mutation sensitivity':48}))throw new Error('Focused category allocation mismatch');
if(scenarios.numericVectors.length!==96||scenarios.mutationRows.length!==48||traces.traces.length!==32)throw new Error('Focused authority allocation mismatch');

const operationAllocation={family:6,neutral:2,upgrade:4,'building-rate':8,'duration-gold':4,'total-rate':3,'offline-totals':5},argumentPaths={family:['$.buildingId','$.state'],neutral:['$.name'],upgrade:['$.level'],'building-rate':['$.buildingId','$.state','$.at'],'duration-gold':['$.at','$.state'],'total-rate':['$.state','$.at'],'offline-totals':['$.at','$.state']},selectors={family:'familyBuildingBonusComponents',neutral:'economyHookBonus',upgrade:'buildingUpgradeCost','building-rate':'buildingRateComponents','duration-gold':'offlineClaimPreview','total-rate':'totalRate','offline-totals':'offlineClaimPreview'},derived=Object.fromEntries(Object.keys(operationAllocation).map(key=>[key,0]));
for(const trace of traces.traces){
  if(!Object.hasOwn(derived,trace.operation))throw new Error('Unknown predecessor trace operation');derived[trace.operation]++;
  if(trace.wrapper.selector!==selectors[trace.operation]||trace.wrapper.fixedClock!==traces.source.fixedClock||JSON.stringify(trace.wrapper.argumentPaths)!==JSON.stringify(argumentPaths[trace.operation]))throw new Error(trace.id+' wrapper selector/path/clock drift');
  const encodedLeaves=[trace.fixture,trace.predecessor.fullReturn,trace.arithmetic.input,trace.arithmetic.projection,...trace.expectedKernelCalls.map(call=>call.argument)];if(!encodedLeaves.every(canonicalEncoded))throw new Error(trace.id+' malformed encoded authority');
  if(trace.expectedKernelCalls.some((call,index)=>call.ordinal!==index+1||!methodOrder.includes(call.method)))throw new Error(trace.id+' call record order/method drift');
  const counts=Object.fromEntries(methodOrder.map(method=>[method,0]));for(const call of trace.expectedKernelCalls)counts[call.method]++;if(JSON.stringify(counts)!==JSON.stringify(trace.aggregateCallCounts))throw new Error(trace.id+' aggregate call count drift');
  const input=encoded(trace.arithmetic.input),matching=trace.expectedKernelCalls.filter(call=>call.method===trace.arithmetic.method&&exactValue(encoded(call.argument),input)),zero=trace.id==='duration-zero-neutral';if(zero?trace.expectedKernelCalls.length!==0||!exactValue(input,{rate:7200,durationMs:0}):matching.length<1)throw new Error(trace.id+' arithmetic input is not bound to the frozen call record');
  const fixtureA=frozen(trace.fixture),fixtureB=frozen(trace.fixture),expectedAuthority=frozen(trace.predecessor.fullReturn);if(fixtureA===fixtureB||fixtureA.state&&fixtureA.state===fixtureB.state)throw new Error(trace.id+' fixture clone alias');const beforeFingerprint=fingerprint({fixtureA,fixtureB,expectedAuthority}),observed=evaluateWrapperTrace(trace,fixtureA),afterFingerprint=fingerprint({fixtureA,fixtureB,expectedAuthority});if(beforeFingerprint!==afterFingerprint||!exactValue(observed,encoded(trace.predecessor.fullReturn)))throw new Error(trace.id+' candidate mutation or predecessor wrapper drift');
}
if(JSON.stringify(derived)!==JSON.stringify(operationAllocation))throw new Error('Predecessor trace allocation drift');
const codec=[undefined,null,[],[undefined,null],{'0':'a'},['a'],{'$undefined':true}],roundA=encoded(encodeValue(codec)),roundB=encoded(encodeValue(codec));if(!exactValue(roundA,roundB)||roundA===roundB||Array.isArray(roundA[4])||!Array.isArray(roundA[5])||roundA[6].$undefined!==true)throw new Error('encodedValue round-trip/type/no-alias control failed');
const malformed=[()=>decodeValue({'$undefined':true,extra:true}),()=>decodeValue({decimal:'0.5','$float64':'3fe0000000000000'}),()=>decodeValue({'$object':[['a',1],['a',2]]})];if(malformed.some(test=>{try{test();return true}catch{return false}})||exactValue({z:+0},{z:-0})||exactValue({a:1,b:2},{b:2,a:1})||exactValue([1],[1,,]))throw new Error('codec/comparator negative control failed');

const boundary=sourceBoundary(),realm=createOutputRealm(),core=realm.probe.core;
const staticChecks=[sha(read('row-registry.json'))===EXPECTED.registry[0],sha(read('scenarios.json'))===EXPECTED.scenarios[0],sha(read('predecessor-traces.json'))===EXPECTED.traces[0],preimage?sha(index)===EXPECTED.index[0]:identity.corePresent,/data:image\//.test(index.toString()),scenarios.source.contractCommit==='fc7553c6960080c596d0b4f6da3dd262dff2e31d',traces.source.baseCommit==='fff84f7dfe87b23040edaa31f07f5f3c9181babf',true,core!==null,boundary.allowedWindows===7,boundary.unchangedWrapperNames[0]==='familyBuildingAssignment',boundary.unchangedWrapperNames[1]==='buildingRate',boundary.unchangedWrapperNames[2]==='nextLocalMidnight',index.includes(Buffer.from('schema:10')),index.includes(Buffer.from('STORAGE_SLOTS=Object.freeze')),!index.includes(Buffer.from('<script src=')),!index.includes(Buffer.from('type="module"')),!index.includes(Buffer.from('npm ')),core!==null,core&&Reflect.ownKeys(core).join('|')===methodOrder.join('|'),core&&methodOrder.every(name=>typeof core[name]==='function'),core&&methodOrder.every(name=>core[name].name===name),core&&methodOrder.every(name=>core[name].length===1),core&&methodOrder.every(name=>!Object.prototype.hasOwnProperty.call(core[name],'prototype')),core&&Object.isFrozen(core),core&&Object.isFrozen(core)&&methodOrder.every(name=>Object.isFrozen(core[name])),identity.bootAnchorCount===1,boundary.restorationExact,realm.effects.storage.length===0&&realm.effects.ui.length===0,realm.effects.network.length===0,realm.effects.timer.length===0,identity.wrapperAnchorCount===6,preimage?!identity.corePresent:identity.corePresent];
for(let i=0;i<32;i++){const authority=registry.rows[i],pending=preimage&&authority.preimageExpectation==='PENDING';record(authority.id,pending?'PENDING':staticChecks[i]?'PASS':'FAIL',pending?'candidate-only source/surface assertion':'static assertion')}

for(const vector of scenarios.numericVectors){const input=frozen(vector.input),expected=encoded(vector.expected),reference=evaluateReference(vector.method,input);let ok=exactValue(reference,expected),evidence='literal expected equals independent reference';if(!preimage){ok=ok&&exactValue(evaluateKernel(vector.method,input),expected);evidence+=' and candidate kernel'}record(vector.id,ok?'PASS':'FAIL',evidence)}

for(const trace of traces.traces){const fixture=frozen(trace.fixture),input=frozen(trace.arithmetic.input),expected=encoded(trace.predecessor.fullReturn),projection=encoded(trace.arithmetic.projection),observed=evaluateWrapperTrace(trace,fixture),reference=evaluateReference(trace.arithmetic.method,input),prefix=`trace-${String(trace.ordinal).padStart(2,'0')}`;record(prefix+'-frozen',trace.ordinal>=1&&trace.ordinal<=32&&trace.predecessor.outcome==='return'?'PASS':'FAIL','frozen literal predecessor authority');record(prefix+'-reference',exactValue(reference,projection)?'PASS':'FAIL','independent arithmetic projection');record(prefix+'-wrapper',exactValue(observed,expected)?'PASS':'FAIL','full wrapper result');record(prefix+'-kernel',preimage?'PENDING':exactValue(evaluateKernel(trace.arithmetic.method,input),projection)?'PASS':'FAIL',preimage?'private candidate kernel intentionally absent':'direct candidate kernel projection')}

const refusalInputs=[['familyBuildingBonus',null],['familyBuildingBonus',{}],['familyBuildingBonus',{assigned:true}],['familyBuildingBonus',{assigned:true,intimacy:-1,rarity:1,specialtyMatch:false,base:.01,intimacyRate:.0002,intimacyCap:.1,rarityRate:.02,specialtyAmount:.01,cap:.2}],['neutralHookBonus',undefined],['neutralHookBonus',-0],['neutralHookBonus',-1],['neutralHookBonus',Infinity],['buildingUpgradeCost',null],['buildingUpgradeCost',{base:15000,growth:1.7,level:0}],['buildingUpgradeCost',{base:15000,growth:1.7,level:53}],['buildingUpgradeCost',{base:15000,growth:Infinity,level:1}],['buildingRateComponents',null],['buildingRateComponents',{base:7200}],['buildingRateComponents',{base:7200,level:1,levelGrowth:1.15,familyAssignmentMultiplier:1,fellowRosterBonus:0,companionRosterBonus:0,overallDayBonus:0,oathBoost:.31}],['buildingRateComponents',{base:7200,level:53,levelGrowth:1.15,familyAssignmentMultiplier:1,fellowRosterBonus:0,companionRosterBonus:0,overallDayBonus:0,oathBoost:0}],['durationGold',null],['durationGold',{rate:1,durationMs:-1}],['durationGold',{rate:1,durationMs:86400001}],['durationGold',{rate:Infinity,durationMs:1}],['totalRate',null],['totalRate',{orderedRates:[1,2,3]}],['totalRate',{orderedRates:[1,2,3,4,5]}],['totalRate',{orderedRates:[1,2,-1,4]}],['offlineTotals',null],['offlineTotals',{orderedLineTotals:[1,2,3,4]}],['offlineTotals',{orderedLineTotals:[1,2,3],pendingBefore:0}],['offlineTotals',{orderedLineTotals:[1,2,3,-0],pendingBefore:0}],['offlineTotals',{orderedLineTotals:[1,2,3,4],pendingBefore:-1}],['offlineTotals',{orderedLineTotals:[1,2,3,Infinity],pendingBefore:0}],['totalRate',{orderedRates:[1,2,3,-0]}],['durationGold',{rate:-0,durationMs:1}]];
const failRows=registry.rows.filter(row=>row.category==='fail-closed/persistence');
for(let i=0;i<32;i++){const row=failRows[i];if(preimage)record(row.id,'PENDING','direct private-kernel refusal is candidate-only');else{const [method,input]=refusalInputs[i];let threw=false;try{evaluateKernel(method,input)}catch(error){threw=error instanceof TypeError||error?.name==='TypeError'}record(row.id,threw?'PASS':'FAIL','candidate kernel exact refusal')}}
for(let i=32;i<48;i++){const row=failRows[i];if(preimage)record(row.id,'PENDING','pre-runtime candidate surface guard is candidate-only');else{const ok=Boolean(core)&&Object.isFrozen(core)&&realm.effects.storage.length===0&&realm.effects.ui.length===0&&realm.effects.timer.length===0&&realm.effects.network.length===0;record(row.id,ok?'PASS':'FAIL','surface guard and zero startup side effects')}}
for(let i=48;i<64;i++){const row=failRows[i],trace=traces.traces[i-48],ok=exactValue(evaluateWrapperTrace(trace,frozen(trace.fixture)),encoded(trace.predecessor.fullReturn));record(row.id,ok?'PASS':'FAIL','preserved wrapper signature/default/result control')}
const text=index.toString('utf8'),persist=['CURRENT_SCHEMA_VERSION=10',"const NS='oathforge_new_world_proto_v01'",'RAW_BACKUP_KEY','PRE_V2_BACKUP_KEY','PRE_V3_BACKUP_KEY','PRE_V4_BACKUP_KEY','PRE_V5_BACKUP_KEY','PRE_V6_BACKUP_KEY','PRE_V7_BACKUP_KEY','PRE_V8_BACKUP_KEY','PRE_V9_BACKUP_KEY','PRE_V10_BACKUP_KEY','STAGING_KEY','function validation','function commitPrepared','function safePersistenceExport'].map(anchor=>text.includes(anchor));for(let i=64;i<80;i++)record(failRows[i].id,persist[i-64]?'PASS':'FAIL','schema-10/twelve-slot/export/persistence source control');
const callRealm=createCallTraceRealm();for(let i=80;i<96;i++){const ok=realm.effects.storage.length===0&&realm.effects.ui.length===0&&realm.effects.timer.length===0&&realm.effects.network.length===0&&callRealm.restoredSha256===identity.artifactSha256;record(failRows[i].id,ok?'PASS':'FAIL','read-only isolated probe/build/browser control')}

for(const mutation of scenarios.mutationRows){const row=registry.rows.find(item=>item.id.startsWith(`mutation-${String(mutation.id).padStart(2,'0')}-`));if(preimage)record(row.id,'PENDING','one-defect source window intentionally absent from preimage');else{const outcomes=mutation.subcases.map(subcase=>createMutationRealm(mutation.id,subcase)),ok=outcomes.length===mutation.subcases.length&&outcomes.every(result=>result.executed===true&&result.controlPassed===true&&result.mutantFailed===true);record(row.id,ok?'PASS':'FAIL','isolated genuine mutation executions')}}

const ordered=registry.rows.map(authority=>results.get(authority.id)??{id:authority.id,status:'FAIL',evidence:'missing result'});
for(let index=0;index<registry.rows.length;index++){const authority=registry.rows[index],result=ordered[index],expected=preimage?authority.preimageExpectation:authority.candidateExpectation;if(authority.ordinal!==index+1||result.status!==expected){result.status='FAIL';result.evidence+=`; expected ${expected} at ordinal ${index+1}`}}
const after=new Map(protectedFiles.map(name=>[name,sha(readFileSync(pathFor(name))) ]));if([...before].some(([name,value])=>after.get(name)!==value))ordered.push({id:'internal-no-write',status:'FAIL',evidence:'verifier changed authority bytes'});
const counts=ordered.reduce((sum,row)=>(sum[row.status]=(sum[row.status]||0)+1,sum),{PASS:0,PENDING:0,FAIL:0});
console.log(`Phase 10B-2 focused ${preimage?'PREIMAGE_READY':'candidate'}: ${counts.PASS} passed, ${counts.PENDING} pending, ${counts.FAIL} failed (${registry.rows.length} registered rows)`);console.log(`Categories: ${JSON.stringify(registry.categoryAllocation)}`);console.log(`Artifact: ${identity.artifactSha256} (${identity.artifactByteLength} bytes)`);
if(counts.FAIL){for(const row of ordered.filter(row=>row.status==='FAIL').slice(0,30))console.error('FAIL '+row.id+': '+row.evidence);process.exit(1)}
if(process.argv.includes('--release')&&preimage){console.error('FAIL release mode refuses PREIMAGE_READY; executable candidate is required');process.exit(2)}
