import {readFileSync,existsSync,readdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {evaluateReference,encodeValue,decodeValue,exactValue,deepFreeze} from './reference-model.mjs';
import {probeIdentity,createOutputRealm,createCallTraceRealm,createMutationRealm,evaluateWrapperTrace,evaluateCallTrace,evaluateKernel,evaluateKernelOutcome,sourceBoundary,probeSelfTest} from './production-probe.mjs';

const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),QA=resolve(ROOT,'qa/phase-10b2');
const sha=value=>createHash('sha256').update(value).digest('hex'),read=name=>readFileSync(resolve(QA,name)),json=name=>JSON.parse(read(name));
const EXPECTED={index:['717160cdddc5fa540532cdebd29f30d127ded2f761edd677684a2609fde9a4ed',18916682],traces:['74feec74ff6f9efe07ca47cb2b0fcaaca8ab80dab71961fd2f1625f270209136',557500],scenarios:['d3dd215cbfd229d58ed4f7d5264a79cc64d3224860be430d324ec0b7d893a8dd',126405],registry:['9e6282b2374e7ec263c3e4c9cc64873458b6e74fc356c470aabe23aac6ca394e',96921],successor:['c3607a47e0c0c5831eb7fb4d0af9e98e9e51bde31c465131f06b62936e76cb67',23717]};
for(const [name,file]of [['traces','predecessor-traces.json'],['scenarios','scenarios.json'],['registry','row-registry.json'],['successor','phase10b1-successor-hashes.json']]){const raw=read(file);if(raw.length!==EXPECTED[name][1]||sha(raw)!==EXPECTED[name][0])throw new Error(`Phase 10B-2 focused verifier refuses altered ${name}`)}
const index=readFileSync(resolve(ROOT,'index.html')),traces=json('predecessor-traces.json'),scenarios=json('scenarios.json'),registry=json('row-registry.json'),successor=json('phase10b1-successor-hashes.json'),identity=probeIdentity(),preimage=identity.mode==='preimage';
if(preimage&&(index.length!==EXPECTED.index[1]||sha(index)!==EXPECTED.index[0]))throw new Error('Phase 10B-2 preimage identity mismatch');
const ownedPaths=['docs/PHASE_10B2_GOLD_CORE_EXTRACTION_CONTRACT.md','docs/PHASE_10B2_EXECUTION.md','docs/PHASE_10B2_RESULT.md','index.html','qa/phase-10b2/README.md','qa/phase-10b2/build-contract.mjs','qa/phase-10b2/current-manifest.json','qa/phase-10b2/checksums.sha256','qa/phase-10b2/index.html','qa/phase-10b2/realm.html','qa/phase-10b2/realm.js','qa/phase-10b2/runner.js','qa/phase-10b2/scenarios.json','qa/phase-10b2/predecessor-traces.json','qa/phase-10b2/row-registry.json','qa/phase-10b2/reference-model.mjs','qa/phase-10b2/production-probe.mjs','qa/phase-10b2/verify.mjs','qa/phase-10b2/regress-phase-10b1.mjs','qa/phase-10b2/phase10b1-successor-hashes.json'],protectedFiles=[...new Set([...Object.keys(successor.files),...ownedPaths])].sort(),snapshot=()=>new Map(protectedFiles.map(path=>{const target=resolve(ROOT,path);if(!existsSync(target))return[path,{exists:false}];const raw=readFileSync(target);return[path,{exists:true,sha256:sha(raw),byteLength:raw.length}]})),before=snapshot();
const results=new Map(),record=(id,status,evidence)=>{if(results.has(id))throw new Error('Duplicate focused row '+id);results.set(id,{id,status,evidence})};
const methodOrder=['familyBuildingBonus','neutralHookBonus','buildingUpgradeCost','buildingRateComponents','durationGold','totalRate','offlineTotals'],encoded=value=>decodeValue(structuredClone(value)),frozen=value=>deepFreeze(encoded(value));
const canonicalEncoded=value=>{try{return JSON.stringify(encodeValue(decodeValue(structuredClone(value))))===JSON.stringify(value)}catch{return false}},fingerprint=value=>sha(Buffer.from(JSON.stringify(encodeValue(value))));
if(registry.total!==400||registry.rows.length!==400||new Set(registry.rows.map(row=>row.id)).size!==400)throw new Error('Focused row registry total/uniqueness mismatch');
if(JSON.stringify(registry.categoryAllocation)!==JSON.stringify({'static/startup':32,'numeric/operator':96,'frozen predecessor traces':128,'fail-closed/persistence':96,'mutation sensitivity':48}))throw new Error('Focused category allocation mismatch');
if(scenarios.numericVectors.length!==96||scenarios.mutationRows.length!==48||traces.traces.length!==32)throw new Error('Focused authority allocation mismatch');

const operationAllocation={family:6,neutral:2,upgrade:4,'building-rate':8,'duration-gold':4,'total-rate':3,'offline-totals':5},argumentPaths={family:['$.buildingId','$.state'],neutral:['$.name'],upgrade:['$.level'],'building-rate':['$.buildingId','$.state','$.at'],'duration-gold':['$.at','$.state'],'total-rate':['$.state','$.at'],'offline-totals':['$.at','$.state']},selectors={family:'familyBuildingBonusComponents',neutral:'economyHookBonus',upgrade:'buildingUpgradeCost','building-rate':'buildingRateComponents','duration-gold':'offlineClaimPreview','total-rate':'totalRate','offline-totals':'offlineClaimPreview'},derived=Object.fromEntries(Object.keys(operationAllocation).map(key=>[key,0]));
const BUILDINGS=['training','command','archives','hearth'],FAMILIES=['elara','tamsin','isolde'],BASE={training:7200,command:6500,archives:5600,hearth:6100},SPECIALTY={elara:'hearth',tamsin:'training',isolde:'archives'},CONFIG={levelGrowth:1.15,upgradeBase:15000,upgradeGrowth:1.7,oathCap:.30,family:{base:.01,intimacyRate:.0002,intimacyCap:.10,rarityRate:.02,specialtyAmount:.01,cap:.20}};
function familyInput(id,state){const assigned=FAMILIES.find(familyId=>state.family[familyId].assignedBuildingId===id),config=CONFIG.family;if(!assigned)return{assigned:false,intimacy:0,rarity:0,specialtyMatch:false,base:config.base,intimacyRate:config.intimacyRate,intimacyCap:config.intimacyCap,rarityRate:config.rarityRate,specialtyAmount:config.specialtyAmount,cap:config.cap};const item=state.family[assigned];return{assigned:true,intimacy:item.intimacy,rarity:item.rarity,specialtyMatch:SPECIALTY[assigned]===id,base:config.base,intimacyRate:config.intimacyRate,intimacyCap:config.intimacyCap,rarityRate:config.rarityRate,specialtyAmount:config.specialtyAmount,cap:config.cap}}
function familyExpected(input){if(!input.assigned)return{baseBonus:0,intimacyBonus:0,rarityBonus:0,specialtyBonus:0,uncappedBonus:0,bonus:0,multiplier:1};const baseBonus=input.base,intimacyBonus=Math.min(input.intimacyCap,input.intimacy*input.intimacyRate),rarityBonus=input.rarityRate*(input.rarity-1),specialtyBonus=input.specialtyMatch?input.specialtyAmount:0,uncappedBonus=baseBonus+intimacyBonus+rarityBonus+specialtyBonus,bonus=Math.min(input.cap,uncappedBonus);return{baseBonus,intimacyBonus,rarityBonus,specialtyBonus,uncappedBonus,bonus,multiplier:1+bonus}}
const upgradeInput=level=>({base:CONFIG.upgradeBase,growth:CONFIG.upgradeGrowth,level});
function dayKey(at){const date=new Date(at);return `D${date.getFullYear()}-${date.getMonth()+1}-${date.getDate()}`}
function nextMidnight(at){const next=new Date(at);next.setHours(24,0,0,0);const value=next.getTime();return value>at?value:at+86400000}
function rateInput(id,state,at){const family=familyExpected(familyInput(id,state)),building=state.buildings[id],oathBoost=building.boostDay===dayKey(at)?Math.min(CONFIG.oathCap,Math.max(0,building.boost)):0;return{base:BASE[id],level:building.level,levelGrowth:CONFIG.levelGrowth,familyAssignmentMultiplier:family.multiplier,fellowRosterBonus:0,companionRosterBonus:0,overallDayBonus:0,oathBoost}}
function rateExpected(input){const levelMultiplier=Math.pow(input.levelGrowth,input.level-1),fellowRosterMultiplier=1+input.fellowRosterBonus,companionRosterMultiplier=1+input.companionRosterBonus,overallDayMultiplier=1+input.overallDayBonus,characterEconomyMultiplier=input.familyAssignmentMultiplier*fellowRosterMultiplier*companionRosterMultiplier*overallDayMultiplier,oathMultiplier=1+input.oathBoost,rate=input.base*levelMultiplier*characterEconomyMultiplier*oathMultiplier;return{levelMultiplier,fellowRosterMultiplier,companionRosterMultiplier,overallDayMultiplier,characterEconomyMultiplier,oathMultiplier,rate}}
const durationExpected=input=>input.rate*input.durationMs/3600000,addCall=(list,method,argument)=>list.push({ordinal:list.length+1,method,argument});
function buildingCalls(list,id,state,at,durationMs=null){addCall(list,'familyBuildingBonus',familyInput(id,state));for(const ignored of ['fellowRoster','companionRoster','overallDay'])addCall(list,'neutralHookBonus',0);const rate=rateInput(id,state,at);addCall(list,'buildingRateComponents',rate);addCall(list,'buildingUpgradeCost',upgradeInput(state.buildings[id].level));if(durationMs!==null)addCall(list,'durationGold',{rate:rateExpected(rate).rate,durationMs})}
function segmentsFor(start,end){const segments=[];let cursor=start;while(cursor<end){const next=Math.min(end,nextMidnight(cursor));segments.push({start:cursor,end:next,durationMs:next-cursor});cursor=next}return segments}
function offlineCalls(state,at){if(at<=state.lastGoldAt)return[];const end=Math.min(at,state.lastGoldAt+86400000),calls=[],lines=Object.fromEntries(BUILDINGS.map(id=>[id,0]));for(const segment of segmentsFor(state.lastGoldAt,end))for(const id of BUILDINGS){buildingCalls(calls,id,state,segment.start,segment.durationMs);lines[id]+=durationExpected({rate:rateExpected(rateInput(id,state,segment.start)).rate,durationMs:segment.durationMs})}addCall(calls,'offlineTotals',{orderedLineTotals:BUILDINGS.map(id=>lines[id]),pendingBefore:state.pendingGold});return calls}
function expectedCalls(trace,fixture){if(trace.operation==='family'){const calls=[];addCall(calls,'familyBuildingBonus',familyInput(fixture.buildingId,fixture.state));return calls}if(trace.operation==='neutral'){const calls=[];addCall(calls,'neutralHookBonus',fixture.name==='fellowRoster'?0:undefined);return calls}if(trace.operation==='upgrade'){const calls=[];addCall(calls,'buildingUpgradeCost',upgradeInput(fixture.level));return calls}if(trace.operation==='building-rate'){const calls=[];buildingCalls(calls,fixture.buildingId,fixture.state,fixture.at);return calls}if(trace.operation==='duration-gold')return fixture.zeroDuration?[]:offlineCalls(fixture.state,fixture.at);if(trace.operation==='total-rate'){const calls=[];for(const id of BUILDINGS)buildingCalls(calls,id,fixture.state,fixture.at);addCall(calls,'totalRate',{orderedRates:BUILDINGS.map(id=>rateExpected(rateInput(id,fixture.state,fixture.at)).rate)});return calls}if(trace.operation==='offline-totals')return offlineCalls(fixture.state,fixture.at);throw new Error('Unknown operation '+trace.operation)}
function boundCall(trace,fixture,calls){if(trace.operation==='duration-gold'&&fixture.zeroDuration)return null;if(trace.operation==='duration-gold'){const buildingIndex=BUILDINGS.indexOf(fixture.buildingId),index=fixture.segmentIndex*BUILDINGS.length*7+buildingIndex*7+6;return calls[index]}if(trace.operation==='total-rate'||trace.operation==='offline-totals')return calls.at(-1);return calls.find(call=>call.method===trace.arithmetic.method)}
for(const trace of traces.traces){
  if(!Object.hasOwn(derived,trace.operation))throw new Error('Unknown predecessor trace operation');derived[trace.operation]++;
  if(trace.wrapper.selector!==selectors[trace.operation]||trace.wrapper.fixedClock!==traces.source.fixedClock||JSON.stringify(trace.wrapper.argumentPaths)!==JSON.stringify(argumentPaths[trace.operation]))throw new Error(trace.id+' wrapper selector/path/clock drift');
  const encodedLeaves=[trace.fixture,trace.predecessor.fullReturn,trace.arithmetic.input,trace.arithmetic.projection,...trace.expectedKernelCalls.map(call=>call.argument)];if(!encodedLeaves.every(canonicalEncoded))throw new Error(trace.id+' malformed encoded authority');
  if(trace.expectedKernelCalls.some((call,index)=>call.ordinal!==index+1||!methodOrder.includes(call.method)))throw new Error(trace.id+' call record order/method drift');
  const counts=Object.fromEntries(methodOrder.map(method=>[method,0]));for(const call of trace.expectedKernelCalls)counts[call.method]++;if(JSON.stringify(counts)!==JSON.stringify(trace.aggregateCallCounts))throw new Error(trace.id+' aggregate call count drift');
  const fixtureA=frozen(trace.fixture),fixtureB=frozen(trace.fixture),input=frozen(trace.arithmetic.input),expectedAuthority=frozen(trace.predecessor.fullReturn),planned=deepFreeze(expectedCalls(trace,fixtureB)),frozenCalls=deepFreeze(trace.expectedKernelCalls.map(call=>({ordinal:call.ordinal,method:call.method,argument:encoded(call.argument)}))),binding=boundCall(trace,fixtureB,planned),zero=trace.operation==='duration-gold'&&fixtureB.zeroDuration,zeroInput=deepFreeze({rate:7200,durationMs:0}),binds=zero?planned.length===0&&exactValue(input,zeroInput):Boolean(binding)&&binding.method===trace.arithmetic.method&&exactValue(binding.argument,input);if(!binds||!exactValue(planned,frozenCalls))throw new Error(trace.id+' exact independent planned-call binding drift');
  if(fixtureA===fixtureB||fixtureA.state&&fixtureA.state===fixtureB.state)throw new Error(trace.id+' fixture clone alias');const beforeFingerprint=fingerprint({fixtureA,fixtureB,input,expectedAuthority,planned,frozenCalls}),observed=evaluateWrapperTrace(trace,fixtureA),afterFingerprint=fingerprint({fixtureA,fixtureB,input,expectedAuthority,planned,frozenCalls});if(beforeFingerprint!==afterFingerprint||!exactValue(observed,encoded(trace.predecessor.fullReturn)))throw new Error(trace.id+' candidate mutation or predecessor wrapper drift');
}
if(JSON.stringify(derived)!==JSON.stringify(operationAllocation))throw new Error('Predecessor trace allocation drift');
const codec=[undefined,null,[],[undefined,null],{'0':'a'},['a'],{'$undefined':true}],roundA=encoded(encodeValue(codec)),roundB=encoded(encodeValue(codec));if(!exactValue(roundA,roundB)||roundA===roundB||roundA[2]===roundB[2]||roundA[4]===roundB[4]||Array.isArray(roundA[4])||!Array.isArray(roundA[5])||roundA[6].$undefined!==true)throw new Error('encodedValue round-trip/type/no-alias control failed');
const throws=test=>{try{test();return false}catch{return true}},accessorArrays=[1,2,4,5].map(length=>{const value=Array.from({length},(_,index)=>index);Object.defineProperty(value,String(length-1),{get(){return length-1},enumerable:true,configurable:true});return value}),sparse=[];sparse.length=3;sparse[0]=1;sparse[2]=3;const extra=[1];extra.extra=true;const symbolArray=[1];symbolArray[Symbol('x')]=2;const customArray=[1];Object.setPrototypeOf(customArray,{});const accessorObject={};Object.defineProperty(accessorObject,'x',{get(){return 1},enumerable:true,configurable:true});const hiddenObject={};Object.defineProperty(hiddenObject,'x',{value:1,enumerable:false,writable:true,configurable:true});const symbolObject={x:1};symbolObject[Symbol('x')]=2;class CustomObject{constructor(){this.x=1}}const nullObject=Object.create(null),customObject=Object.create({});customObject.x=1;
const badUndefined=Object.create({});badUndefined.$undefined=true;const reorderedFloat={decimal:'0.5','$float64':'3fe0000000000000'},integerFloat={'$float64':'3ff0000000000000',decimal:'1'},extraTag={'$undefined':true,extra:true},badPair={'$object':[['a',1,,]]},badDescriptor={'$undefined':true};Object.defineProperty(badDescriptor,'$undefined',{value:true,enumerable:true,writable:false,configurable:true});
const malformed=[...accessorArrays.map(value=>()=>encodeValue(value)),()=>encodeValue(sparse),()=>encodeValue(extra),()=>encodeValue(symbolArray),()=>encodeValue(customArray),()=>encodeValue(accessorObject),()=>encodeValue(hiddenObject),()=>encodeValue(symbolObject),()=>encodeValue(new CustomObject()),()=>encodeValue(nullObject),()=>encodeValue(customObject),()=>decodeValue(badUndefined),()=>decodeValue(reorderedFloat),()=>decodeValue(integerFloat),()=>decodeValue(extraTag),()=>decodeValue(badPair),()=>decodeValue(badDescriptor)];if(!malformed.every(throws))throw new Error('codec malformed-shape controls failed');
const descriptorLeft={a:1,b:[2]},descriptorMissing={a:1},descriptorExtra={a:1,b:[2],c:3},descriptorReordered={b:[2],a:1},descriptorCustom=Object.create({});descriptorCustom.a=1;descriptorCustom.b=[2];const descriptorAccessor={b:[2]};Object.defineProperty(descriptorAccessor,'a',{get(){return 1},enumerable:true,configurable:true});const descriptorFlags={a:1,b:[2]};Object.defineProperty(descriptorFlags,'a',{value:1,enumerable:true,writable:false,configurable:true});const descriptorSparse={a:1,b:[]};descriptorSparse.b.length=1;const descriptorArrayExtra={a:1,b:[2]};descriptorArrayExtra.b.extra=3;const descriptorArrayAccessor={a:1,b:[2]};Object.defineProperty(descriptorArrayAccessor.b,'0',{get(){return 2},enumerable:true,configurable:true});const floatFromBits=bits=>Buffer.from(bits,'hex').readDoubleBE(),acceptedGrouping=floatFromBits('4124a3aeef9db22b'),rejectedGrouping=floatFromBits('4124a3aeef9db22a');if([descriptorMissing,descriptorExtra,descriptorReordered,descriptorCustom,descriptorAccessor,descriptorFlags,descriptorSparse,descriptorArrayExtra,descriptorArrayAccessor].some(value=>exactValue(descriptorLeft,value))||exactValue({z:+0},{z:-0})||exactValue({z:-0},{z:+0})||exactValue({gold:acceptedGrouping},{gold:rejectedGrouping}))throw new Error('exact comparator negative controls failed');
const cyclic={};cyclic.self=cyclic;const freezeMalformed=[()=>deepFreeze(sparse),()=>deepFreeze(accessorArrays[0]),()=>deepFreeze(customArray),()=>deepFreeze(new CustomObject()),()=>deepFreeze(cyclic)];if(!freezeMalformed.every(throws))throw new Error('deepFreeze malformed authority controls failed');const frozenControl=deepFreeze({a:[{b:-0}],tag:{'$undefined':true}}),frozenBefore=fingerprint(frozenControl),mutationBlocked=throws(()=>{frozenControl.a[0].b=0})&&throws(()=>{frozenControl.a.push(2)})&&throws(()=>{frozenControl.tag.extra=true});if(!mutationBlocked||frozenBefore!==fingerprint(frozenControl)||exactValue(encoded(encodeValue(frozenControl)),{a:[{b:0}],tag:{'$undefined':true}}))throw new Error('deepFreeze mutation/fingerprint controls failed');

const boundary=sourceBoundary(),realm=createOutputRealm(),core=realm.probe.core,sourceText=index.toString('utf8'),assetMatches=[...sourceText.matchAll(/data:image\/[^;]+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]),assetAggregate=sha(Buffer.from(assetMatches.join('\n'))),allowedQaFiles=new Set(['README.md','build-contract.mjs','current-manifest.json','checksums.sha256','index.html','realm.html','realm.js','runner.js','scenarios.json','predecessor-traces.json','row-registry.json','reference-model.mjs','production-probe.mjs','verify.mjs','regress-phase-10b1.mjs','phase10b1-successor-hashes.json']),qaTopology=readdirSync(QA).every(name=>allowedQaFiles.has(name)),slotNames=['NS','RAW_BACKUP_KEY','PRE_V2_BACKUP_KEY','PRE_V3_BACKUP_KEY','PRE_V4_BACKUP_KEY','PRE_V5_BACKUP_KEY','PRE_V6_BACKUP_KEY','PRE_V7_BACKUP_KEY','PRE_V8_BACKUP_KEY','PRE_V9_BACKUP_KEY','PRE_V10_BACKUP_KEY','STAGING_KEY'],nonconstructible=fn=>{try{Reflect.construct(fn,[]);return false}catch{return true}},surfaceDescriptors=Boolean(core)&&Object.isFrozen(core)&&Reflect.ownKeys(core).every(name=>{const descriptor=Object.getOwnPropertyDescriptor(core,name);return descriptor&&descriptor.enumerable===true&&descriptor.writable===false&&descriptor.configurable===false&&typeof descriptor.value==='function'}),callTraceControl=createCallTraceRealm(),mutationControl=createMutationRealm(1);
const staticChecks=[
  sha(read('row-registry.json'))===EXPECTED.registry[0],
  sha(read('scenarios.json'))===EXPECTED.scenarios[0],
  sha(read('predecessor-traces.json'))===EXPECTED.traces[0],
  preimage?sha(index)===EXPECTED.index[0]&&index.length===EXPECTED.index[1]:identity.corePresent&&identity.artifactSha256!==EXPECTED.index[0],
  assetMatches.length===5&&assetAggregate==='26d0c15d43ab9f7f98467f22f51aab8336f78ae84a016abc981733f7d5df5e7a',
  sha(readFileSync(resolve(ROOT,'docs/PHASE_10B2_GOLD_CORE_EXTRACTION_CONTRACT.md')))==='b458fac750ac92db4e1791e061277d88452c62daef9caae1f979c09e5e0b453b',
  traces.source.baseCommit==='fff84f7dfe87b23040edaa31f07f5f3c9181babf',
  qaTopology,
  preimage?!identity.corePresent:Boolean(boundary.kernelWindow),
  boundary.allowedWindows===7&&boundary.restorationExact===true,
  boundary.unchangedWrapperNames?.includes('familyBuildingAssignment')&&boundary.familyAssignmentExact!==false,
  boundary.unchangedWrapperNames?.includes('buildingRate')&&boundary.buildingRateExact!==false,
  boundary.unchangedWrapperNames?.includes('nextLocalMidnight')&&boundary.nextLocalMidnightExact!==false,
  sourceText.includes('CURRENT_SCHEMA_VERSION=10'),
  slotNames.every(name=>sourceText.includes(name)),
  !sourceText.includes('<script src='),
  !sourceText.includes('type="module"')&&!sourceText.includes('import('),
  !sourceText.includes('npm ')&&!sourceText.includes('node_modules'),
  Boolean(core)&&!Object.hasOwn(globalThis,'PHASE_TEN_B_TWO_GOLD_CORE')&&!Object.hasOwn(realm,'PHASE_TEN_B_TWO_GOLD_CORE'),
  Boolean(core)&&Reflect.ownKeys(core).join('|')===methodOrder.join('|'),
  surfaceDescriptors,
  Boolean(core)&&methodOrder.every(name=>typeof core[name]==='function'&&!/^function\b/.test(Function.prototype.toString.call(core[name]))),
  Boolean(core)&&methodOrder.every(name=>nonconstructible(core[name])),
  Boolean(core)&&methodOrder.every(name=>!Object.prototype.hasOwnProperty.call(core[name],'prototype')),
  Boolean(core)&&boundary.shapeGuardLocated===true,
  Boolean(core)&&boundary.shapeGuardBeforeRuntime===true,
  identity.bootAnchorCount===1,
  boundary.restorationExact===true,
  realm.effects.storage.length===0&&realm.effects.ui.length===0&&realm.effects.network.length===0&&realm.effects.timer.length===0,
  callTraceControl.restoredSha256===identity.artifactSha256&&callTraceControl.effects.storage.length===0&&callTraceControl.effects.ui.length===0&&callTraceControl.effects.timer.length===0&&callTraceControl.effects.network.length===0,
  mutationControl.restoredSha256===identity.artifactSha256&&mutationControl.effects.storage.length===0&&mutationControl.effects.ui.length===0&&mutationControl.effects.timer.length===0&&mutationControl.effects.network.length===0,
  preimage&&!identity.corePresent&&registry.preimageTotals.PASS===206&&registry.preimageTotals.PENDING===194
];if(staticChecks.length!==32)throw new Error('Static implementation count drift');
for(let i=0;i<32;i++){const authority=registry.rows[i],pending=preimage&&authority.preimageExpectation==='PENDING';record(authority.id,pending?'PENDING':staticChecks[i]?'PASS':'FAIL',pending?'candidate-only source/surface assertion':'static assertion')}

for(const vector of scenarios.numericVectors){const input=frozen(vector.input),expected=encoded(vector.expected),reference=evaluateReference(vector.method,input);let ok=exactValue(reference,expected),evidence='literal expected equals independent reference';if(!preimage){ok=ok&&exactValue(evaluateKernel(vector.method,input),expected);evidence+=' and candidate kernel'}record(vector.id,ok?'PASS':'FAIL',evidence)}

const traceEvidence=new Map();for(const trace of traces.traces){const fixture=frozen(trace.fixture),input=frozen(trace.arithmetic.input),expected=encoded(trace.predecessor.fullReturn),projection=encoded(trace.arithmetic.projection),observed=evaluateWrapperTrace(trace,fixture),reference=evaluateReference(trace.arithmetic.method,input),prefix=`trace-${String(trace.ordinal).padStart(2,'0')}`,callEvidence=preimage?null:evaluateCallTrace(trace,frozen(trace.fixture)),expectedRecords=deepFreeze(trace.expectedKernelCalls.map(call=>({ordinal:call.ordinal,method:call.method,argument:encoded(call.argument)}))),expectedCounts=deepFreeze(structuredClone(trace.aggregateCallCounts)),actualCounts=callEvidence?.counts??{},callExact=!preimage&&callEvidence.status==='READY'&&exactValue(callEvidence.output,expected)&&exactValue(callEvidence.records,expectedRecords)&&exactValue(actualCounts,expectedCounts)&&callEvidence.restoredSha256===identity.artifactSha256,predecessorExact=exactValue(observed,expected);traceEvidence.set(trace.id,{observed,expected,callEvidence,callExact,predecessorExact});record(prefix+'-frozen',trace.ordinal>=1&&trace.ordinal<=32&&trace.predecessor.outcome==='return'?'PASS':'FAIL','frozen literal predecessor authority');record(prefix+'-reference',exactValue(reference,projection)?'PASS':'FAIL','independent arithmetic projection');record(prefix+'-wrapper',preimage?'PENDING':predecessorExact&&callExact?'PASS':'FAIL',preimage?'candidate wrapper/call-record observation intentionally absent':'full wrapper plus exact actual method/argument/global ordinal/count records');record(prefix+'-kernel',preimage?'PENDING':exactValue(evaluateKernel(trace.arithmetic.method,input),projection)?'PASS':'FAIL',preimage?'private candidate kernel intentionally absent':'direct candidate kernel projection')}

const failRows=registry.rows.filter(row=>row.category==='fail-closed/persistence');
const familyValid=()=>({assigned:true,intimacy:250,rarity:3,specialtyMatch:true,base:.01,intimacyRate:.0002,intimacyCap:.1,rarityRate:.02,specialtyAmount:.01,cap:.2}),rateValid=()=>({base:7200,level:2.5,levelGrowth:1.15,familyAssignmentMultiplier:1.1,fellowRosterBonus:.02,companionRosterBonus:.03,overallDayBonus:.04,oathBoost:.05}),upgradeValid=()=>({base:15000,growth:1.7,level:2.5}),durationValid=()=>({rate:7200,durationMs:3600000}),totalValid=()=>({orderedRates:[7200,6500,5600,6100]}),offlineValid=()=>({orderedLineTotals:[7200,6500,5600,6100],pendingBefore:.5}),error=(method,path)=>({kind:'error',name:'TypeError',message:`PHASE_TEN_B_TWO_GOLD_CORE.${method}: invalid ${path}`}),returns=value=>({kind:'return',value}),caseOf=(method,make,expected)=>({method,make,expected}),reorder=(value,keys)=>Object.fromEntries(keys.map(key=>[key,value[key]])),withAccessor=(value,key)=>{const copy={...value};Object.defineProperty(copy,key,{get(){return value[key]},enumerable:true,configurable:true});return copy},withSymbol=value=>{const copy={...value};copy[Symbol('foreign')]=true;return copy},withCustomPrototype=value=>Object.assign(Object.create({foreign:true}),value),refusalSparseFour=()=>{const value=[1,2,,4];return value},refusalExtraArray=()=>{const value=[1,2,3,4];value.extra=true;return value},refusalSymbolArray=()=>{const value=[1,2,3,4];value[Symbol('foreign')]=true;return value},refusalAccessorArray=()=>{const value=[1,2,3,4];Object.defineProperty(value,'2',{get(){return 3},enumerable:true,configurable:true});return value},refusalCustomArray=()=>{const value=[1,2,3,4];Object.setPrototypeOf(value,{});return value};
const refusalGroups=[
 [caseOf('familyBuildingBonus',()=>null,error('familyBuildingBonus','$input')),caseOf('familyBuildingBonus',()=>[],error('familyBuildingBonus','$input')),caseOf('familyBuildingBonus',()=>withCustomPrototype(familyValid()),error('familyBuildingBonus','$input'))],
 [caseOf('familyBuildingBonus',()=>({}),error('familyBuildingBonus','$input')),caseOf('familyBuildingBonus',()=>({...familyValid(),foreign:true}),error('familyBuildingBonus','$input')),caseOf('familyBuildingBonus',()=>reorder(familyValid(),['intimacy','assigned','rarity','specialtyMatch','base','intimacyRate','intimacyCap','rarityRate','specialtyAmount','cap']),error('familyBuildingBonus','$input'))],
 [caseOf('familyBuildingBonus',()=>withAccessor(familyValid(),'intimacy'),error('familyBuildingBonus','$input')),caseOf('familyBuildingBonus',()=>withSymbol(familyValid()),error('familyBuildingBonus','$input'))],
 [caseOf('familyBuildingBonus',()=>({...familyValid(),assigned:1}),error('familyBuildingBonus','$input.assigned')),caseOf('familyBuildingBonus',()=>({...familyValid(),assigned:false,intimacy:1,rarity:0,specialtyMatch:false}),error('familyBuildingBonus','$input.assigned')),caseOf('familyBuildingBonus',()=>({...familyValid(),assigned:false,intimacy:0,rarity:0,specialtyMatch:true}),error('familyBuildingBonus','$input.assigned'))],
 [caseOf('familyBuildingBonus',()=>({...familyValid(),intimacy:-1}),error('familyBuildingBonus','$input.intimacy')),caseOf('familyBuildingBonus',()=>({...familyValid(),intimacy:Number.MAX_SAFE_INTEGER+1}),error('familyBuildingBonus','$input.intimacy')),caseOf('familyBuildingBonus',()=>({...familyValid(),intimacy:NaN}),error('familyBuildingBonus','$input.intimacy')),caseOf('familyBuildingBonus',()=>({...familyValid(),intimacy:Infinity}),error('familyBuildingBonus','$input.intimacy')),caseOf('familyBuildingBonus',()=>({...familyValid(),intimacy:-0}),returns(evaluateReference('familyBuildingBonus',{...familyValid(),intimacy:-0})))],
 [caseOf('familyBuildingBonus',()=>({...familyValid(),rarity:0}),error('familyBuildingBonus','$input.rarity')),caseOf('familyBuildingBonus',()=>({...familyValid(),rarity:6}),error('familyBuildingBonus','$input.rarity')),caseOf('familyBuildingBonus',()=>({...familyValid(),rarity:2.5}),error('familyBuildingBonus','$input.rarity')),caseOf('familyBuildingBonus',()=>({...familyValid(),rarity:0,specialtyMatch:'combined-invalid'}),error('familyBuildingBonus','$input.rarity')),caseOf('familyBuildingBonus',()=>({...familyValid(),assigned:false,intimacy:0,rarity:1,specialtyMatch:false}),error('familyBuildingBonus','$input.rarity'))],
 [caseOf('familyBuildingBonus',()=>({...familyValid(),specialtyMatch:'yes'}),error('familyBuildingBonus','$input.specialtyMatch')),caseOf('familyBuildingBonus',()=>({...familyValid(),specialtyMatch:false}),returns(evaluateReference('familyBuildingBonus',{...familyValid(),specialtyMatch:false})))],
 [['base','intimacyRate','intimacyCap','rarityRate','specialtyAmount','cap'].flatMap(field=>[caseOf('familyBuildingBonus',()=>({...familyValid(),[field]:-0}),error('familyBuildingBonus',`$input.${field}`)),caseOf('familyBuildingBonus',()=>({...familyValid(),[field]:-1}),error('familyBuildingBonus',`$input.${field}`)),caseOf('familyBuildingBonus',()=>({...familyValid(),[field]:NaN}),error('familyBuildingBonus',`$input.${field}`)),caseOf('familyBuildingBonus',()=>({...familyValid(),[field]:Infinity}),error('familyBuildingBonus',`$input.${field}`)),caseOf('familyBuildingBonus',()=>({...familyValid(),[field]:1.01}),error('familyBuildingBonus',`$input.${field}`))]),caseOf('familyBuildingBonus',()=>({...familyValid(),base:.21}),error('familyBuildingBonus','$input.base')),caseOf('familyBuildingBonus',()=>({...familyValid(),intimacyCap:.21}),error('familyBuildingBonus','$input.intimacyCap')),caseOf('familyBuildingBonus',()=>({...familyValid(),rarityRate:.21}),error('familyBuildingBonus','$input.rarityRate')),caseOf('familyBuildingBonus',()=>({...familyValid(),specialtyAmount:.21}),error('familyBuildingBonus','$input.specialtyAmount'))],
 [caseOf('familyBuildingBonus',()=>({assigned:false,intimacy:-0,rarity:0,specialtyMatch:false,base:.01,intimacyRate:.0002,intimacyCap:.1,rarityRate:.02,specialtyAmount:.01,cap:.2}),returns({baseBonus:0,intimacyBonus:0,rarityBonus:0,specialtyBonus:0,uncappedBonus:0,bonus:0,multiplier:1})),caseOf('familyBuildingBonus',familyValid,returns(evaluateReference('familyBuildingBonus',familyValid())))],
 [[undefined,null,false,'phase10b2',Symbol('phase10b2'),{},function phase10b2Input(){},NaN,Infinity,-Infinity,-1,-0,+0].map(value=>caseOf('neutralHookBonus',()=>value,returns(+0)))],
 [caseOf('neutralHookBonus',()=>Number.MIN_VALUE,returns(Number.MIN_VALUE)),caseOf('neutralHookBonus',()=>.25,returns(.25))],
 [caseOf('buildingUpgradeCost',()=>null,error('buildingUpgradeCost','$input')),caseOf('buildingUpgradeCost',()=>withCustomPrototype(upgradeValid()),error('buildingUpgradeCost','$input')),caseOf('buildingUpgradeCost',()=>({...upgradeValid(),foreign:true}),error('buildingUpgradeCost','$input'))],
 [caseOf('buildingUpgradeCost',()=>withAccessor(upgradeValid(),'base'),error('buildingUpgradeCost','$input')),caseOf('buildingUpgradeCost',()=>withSymbol(upgradeValid()),error('buildingUpgradeCost','$input')),caseOf('buildingUpgradeCost',()=>reorder(upgradeValid(),['growth','base','level']),error('buildingUpgradeCost','$input'))],
 [caseOf('buildingUpgradeCost',()=>({...upgradeValid(),base:0}),error('buildingUpgradeCost','$input.base')),caseOf('buildingUpgradeCost',()=>({...upgradeValid(),base:Infinity}),error('buildingUpgradeCost','$input.base')),caseOf('buildingUpgradeCost',()=>({...upgradeValid(),base:Number.MAX_SAFE_INTEGER+1}),error('buildingUpgradeCost','$input.base'))],
 [caseOf('buildingUpgradeCost',()=>({...upgradeValid(),growth:0}),error('buildingUpgradeCost','$input.growth')),caseOf('buildingUpgradeCost',()=>({...upgradeValid(),growth:Infinity}),error('buildingUpgradeCost','$input.growth'))],
 [caseOf('buildingUpgradeCost',()=>({...upgradeValid(),level:0}),error('buildingUpgradeCost','$input.level')),caseOf('buildingUpgradeCost',()=>({...upgradeValid(),level:53}),error('buildingUpgradeCost','$input.level')),caseOf('buildingUpgradeCost',()=>({...upgradeValid(),level:-0}),error('buildingUpgradeCost','$input.level'))],
 [caseOf('buildingUpgradeCost',upgradeValid,returns(evaluateReference('buildingUpgradeCost',upgradeValid()))),caseOf('buildingUpgradeCost',()=>({base:1,growth:1,level:1}),returns(1)),caseOf('buildingUpgradeCost',()=>({base:1,growth:1.5,level:2.5}),returns(Math.round(Math.pow(1.5,1.5))))],
 [caseOf('buildingUpgradeCost',()=>({base:1,growth:Number.MAX_VALUE,level:3}),error('buildingUpgradeCost','$output.power')),caseOf('buildingUpgradeCost',()=>({base:Number.MAX_SAFE_INTEGER,growth:Number.MAX_VALUE,level:2}),error('buildingUpgradeCost','$output.unroundedCost'))],
 [caseOf('buildingUpgradeCost',()=>({base:Number.MAX_SAFE_INTEGER,growth:1.1,level:2}),error('buildingUpgradeCost','$output.cost'))],
 [caseOf('buildingRateComponents',()=>null,error('buildingRateComponents','$input')),caseOf('buildingRateComponents',()=>withCustomPrototype(rateValid()),error('buildingRateComponents','$input')),caseOf('buildingRateComponents',()=>withAccessor(rateValid(),'base'),error('buildingRateComponents','$input')),caseOf('buildingRateComponents',()=>withSymbol(rateValid()),error('buildingRateComponents','$input')),caseOf('buildingRateComponents',()=>reorder(rateValid(),['level','base','levelGrowth','familyAssignmentMultiplier','fellowRosterBonus','companionRosterBonus','overallDayBonus','oathBoost']),error('buildingRateComponents','$input'))],
 [['base','fellowRosterBonus','companionRosterBonus','overallDayBonus','oathBoost'].flatMap(field=>[caseOf('buildingRateComponents',()=>({...rateValid(),[field]:-0}),error('buildingRateComponents',`$input.${field}`)),caseOf('buildingRateComponents',()=>({...rateValid(),[field]:NaN}),error('buildingRateComponents',`$input.${field}`)),caseOf('buildingRateComponents',()=>({...rateValid(),[field]:Infinity}),error('buildingRateComponents',`$input.${field}`))]),caseOf('buildingRateComponents',()=>({...rateValid(),level:0}),error('buildingRateComponents','$input.level')),caseOf('buildingRateComponents',()=>({...rateValid(),level:53}),error('buildingRateComponents','$input.level')),caseOf('buildingRateComponents',()=>({...rateValid(),level:Infinity}),error('buildingRateComponents','$input.level')),caseOf('buildingRateComponents',()=>({...rateValid(),levelGrowth:0}),error('buildingRateComponents','$input.levelGrowth')),caseOf('buildingRateComponents',()=>({...rateValid(),levelGrowth:Infinity}),error('buildingRateComponents','$input.levelGrowth'))],
 [caseOf('buildingRateComponents',()=>({...rateValid(),familyAssignmentMultiplier:.99}),error('buildingRateComponents','$input.familyAssignmentMultiplier')),caseOf('buildingRateComponents',()=>({...rateValid(),familyAssignmentMultiplier:-0}),error('buildingRateComponents','$input.familyAssignmentMultiplier')),caseOf('buildingRateComponents',()=>({...rateValid(),fellowRosterBonus:-1}),error('buildingRateComponents','$input.fellowRosterBonus')),caseOf('buildingRateComponents',()=>({...rateValid(),companionRosterBonus:-1}),error('buildingRateComponents','$input.companionRosterBonus')),caseOf('buildingRateComponents',()=>({...rateValid(),overallDayBonus:-1}),error('buildingRateComponents','$input.overallDayBonus'))],
 [caseOf('buildingRateComponents',()=>({...rateValid(),oathBoost:.31}),error('buildingRateComponents','$input.oathBoost')),caseOf('buildingRateComponents',()=>({...rateValid(),oathBoost:-1}),error('buildingRateComponents','$input.oathBoost')),caseOf('buildingRateComponents',rateValid,returns(evaluateReference('buildingRateComponents',rateValid()))),caseOf('buildingRateComponents',()=>({...rateValid(),base:0,level:1,levelGrowth:1,familyAssignmentMultiplier:1,fellowRosterBonus:0,companionRosterBonus:0,overallDayBonus:0,oathBoost:0}),returns(evaluateReference('buildingRateComponents',{...rateValid(),base:0,level:1,levelGrowth:1,familyAssignmentMultiplier:1,fellowRosterBonus:0,companionRosterBonus:0,overallDayBonus:0,oathBoost:0})))],
 [caseOf('buildingRateComponents',()=>({base:1,level:52,levelGrowth:Number.MAX_VALUE,familyAssignmentMultiplier:1,fellowRosterBonus:0,companionRosterBonus:0,overallDayBonus:0,oathBoost:0}),error('buildingRateComponents','$output.levelMultiplier')),caseOf('buildingRateComponents',()=>({base:1,level:1,levelGrowth:1,familyAssignmentMultiplier:Number.MAX_VALUE,fellowRosterBonus:Number.MAX_VALUE,companionRosterBonus:0,overallDayBonus:0,oathBoost:0}),error('buildingRateComponents','$output.characterEconomyMultiplier')),caseOf('buildingRateComponents',()=>({base:Number.MAX_SAFE_INTEGER,level:1,levelGrowth:1,familyAssignmentMultiplier:1,fellowRosterBonus:0,companionRosterBonus:0,overallDayBonus:0,oathBoost:.3}),error('buildingRateComponents','$output.rate')),caseOf('buildingRateComponents',()=>({base:Number.MAX_SAFE_INTEGER,level:2,levelGrowth:Number.MAX_VALUE,familyAssignmentMultiplier:1,fellowRosterBonus:0,companionRosterBonus:0,overallDayBonus:0,oathBoost:0}),error('buildingRateComponents','$output.rate'))],
 [caseOf('durationGold',()=>null,error('durationGold','$input')),caseOf('durationGold',()=>withCustomPrototype(durationValid()),error('durationGold','$input')),caseOf('durationGold',()=>withAccessor(durationValid(),'rate'),error('durationGold','$input')),caseOf('durationGold',()=>withSymbol(durationValid()),error('durationGold','$input')),caseOf('durationGold',()=>reorder(durationValid(),['durationMs','rate']),error('durationGold','$input'))],
 [caseOf('durationGold',()=>({...durationValid(),rate:-0}),error('durationGold','$input.rate')),caseOf('durationGold',()=>({...durationValid(),rate:-1}),error('durationGold','$input.rate')),caseOf('durationGold',()=>({...durationValid(),rate:NaN}),error('durationGold','$input.rate')),caseOf('durationGold',()=>({...durationValid(),rate:Number.MAX_SAFE_INTEGER+1}),error('durationGold','$input.rate')),caseOf('durationGold',()=>({...durationValid(),durationMs:-0}),error('durationGold','$input.durationMs')),caseOf('durationGold',()=>({...durationValid(),durationMs:-1}),error('durationGold','$input.durationMs')),caseOf('durationGold',()=>({...durationValid(),durationMs:NaN}),error('durationGold','$input.durationMs')),caseOf('durationGold',()=>({...durationValid(),durationMs:86400001}),error('durationGold','$input.durationMs')),caseOf('durationGold',()=>({rate:0,durationMs:0}),returns(0)),caseOf('durationGold',()=>({rate:Number.MAX_SAFE_INTEGER,durationMs:86400000}),returns(Number.MAX_SAFE_INTEGER*24)),caseOf('durationGold',durationValid,returns(evaluateReference('durationGold',durationValid())))],
 [caseOf('totalRate',()=>null,error('totalRate','$input')),caseOf('totalRate',()=>withCustomPrototype(totalValid()),error('totalRate','$input')),caseOf('totalRate',()=>withAccessor(totalValid(),'orderedRates'),error('totalRate','$input')),caseOf('totalRate',()=>withSymbol(totalValid()),error('totalRate','$input')),caseOf('totalRate',()=>({orderedRates:[1,2,3]}),error('totalRate','$input.orderedRates')),caseOf('totalRate',()=>({orderedRates:[1,2,3,4,5]}),error('totalRate','$input.orderedRates')),caseOf('totalRate',()=>({orderedRates:refusalSparseFour()}),error('totalRate','$input.orderedRates')),caseOf('totalRate',()=>({orderedRates:refusalExtraArray()}),error('totalRate','$input.orderedRates')),caseOf('totalRate',()=>({orderedRates:refusalSymbolArray()}),error('totalRate','$input.orderedRates')),caseOf('totalRate',()=>({orderedRates:refusalAccessorArray()}),error('totalRate','$input.orderedRates')),caseOf('totalRate',()=>({orderedRates:refusalCustomArray()}),error('totalRate','$input.orderedRates'))],
 [caseOf('totalRate',()=>({orderedRates:[1,2,-0,4]}),error('totalRate','$input.orderedRates[2]')),caseOf('totalRate',()=>({orderedRates:[1,2,-1,4]}),error('totalRate','$input.orderedRates[2]')),caseOf('totalRate',()=>({orderedRates:[1,2,NaN,4]}),error('totalRate','$input.orderedRates[2]')),caseOf('totalRate',()=>({orderedRates:[1,2,Infinity,4]}),error('totalRate','$input.orderedRates[2]')),caseOf('totalRate',()=>({orderedRates:[1,2,Number.MAX_SAFE_INTEGER+1,4]}),error('totalRate','$input.orderedRates[2]')),caseOf('totalRate',()=>({orderedRates:[0,0,0,0]}),returns(0)),caseOf('totalRate',totalValid,returns(evaluateReference('totalRate',totalValid()))),caseOf('totalRate',()=>({orderedRates:[Number.MAX_SAFE_INTEGER,Number.MAX_SAFE_INTEGER,Number.MAX_SAFE_INTEGER,Number.MAX_SAFE_INTEGER]}),returns(Number.MAX_SAFE_INTEGER*4))],
 [caseOf('offlineTotals',()=>null,error('offlineTotals','$input')),caseOf('offlineTotals',()=>withCustomPrototype(offlineValid()),error('offlineTotals','$input')),caseOf('offlineTotals',()=>withAccessor(offlineValid(),'orderedLineTotals'),error('offlineTotals','$input')),caseOf('offlineTotals',()=>withSymbol(offlineValid()),error('offlineTotals','$input')),caseOf('offlineTotals',()=>reorder(offlineValid(),['pendingBefore','orderedLineTotals']),error('offlineTotals','$input')),caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,3,4]}),error('offlineTotals','$input')),caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,3],pendingBefore:0}),error('offlineTotals','$input.orderedLineTotals')),caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,3,4,5],pendingBefore:0}),error('offlineTotals','$input.orderedLineTotals')),caseOf('offlineTotals',()=>({orderedLineTotals:refusalSparseFour(),pendingBefore:0}),error('offlineTotals','$input.orderedLineTotals')),caseOf('offlineTotals',()=>({orderedLineTotals:refusalAccessorArray(),pendingBefore:0}),error('offlineTotals','$input.orderedLineTotals')),caseOf('offlineTotals',()=>({orderedLineTotals:refusalSymbolArray(),pendingBefore:0}),error('offlineTotals','$input.orderedLineTotals')),caseOf('offlineTotals',()=>({orderedLineTotals:refusalExtraArray(),pendingBefore:0}),error('offlineTotals','$input.orderedLineTotals')),caseOf('offlineTotals',()=>({orderedLineTotals:refusalCustomArray(),pendingBefore:0}),error('offlineTotals','$input.orderedLineTotals'))],
 [caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,3,-0],pendingBefore:0}),error('offlineTotals','$input.orderedLineTotals[3]')),caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,-1,4],pendingBefore:0}),error('offlineTotals','$input.orderedLineTotals[2]')),caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,NaN,4],pendingBefore:0}),error('offlineTotals','$input.orderedLineTotals[2]')),caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,Infinity,4],pendingBefore:0}),error('offlineTotals','$input.orderedLineTotals[2]')),caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,3,4],pendingBefore:-1}),error('offlineTotals','$input.pendingBefore')),caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,3,4],pendingBefore:NaN}),error('offlineTotals','$input.pendingBefore')),caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,3,4],pendingBefore:Infinity}),error('offlineTotals','$input.pendingBefore')),caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,3,4],pendingBefore:-Infinity}),error('offlineTotals','$input.pendingBefore')),caseOf('offlineTotals',()=>({orderedLineTotals:[1,2,3,-0],pendingBefore:Infinity}),error('offlineTotals','$input.orderedLineTotals[3]'))],
 [caseOf('offlineTotals',()=>({orderedLineTotals:[0,0,0,0],pendingBefore:-0}),returns({total:0,pendingAfter:+0})),caseOf('offlineTotals',()=>({orderedLineTotals:[0,0,0,0],pendingBefore:Number.MAX_SAFE_INTEGER+2}),returns({total:0,pendingAfter:Number.MAX_SAFE_INTEGER+2})),caseOf('offlineTotals',()=>({orderedLineTotals:[Number.MAX_VALUE,0,0,0],pendingBefore:0}),returns({total:Number.MAX_VALUE,pendingAfter:Number.MAX_VALUE}))],
 [caseOf('offlineTotals',()=>({orderedLineTotals:[Number.MAX_VALUE,Number.MAX_VALUE,0,0],pendingBefore:0}),error('offlineTotals','$output.total')),caseOf('offlineTotals',()=>({orderedLineTotals:[Number.MAX_VALUE,0,0,0],pendingBefore:Number.MAX_VALUE}),error('offlineTotals','$output.pendingAfter')),caseOf('offlineTotals',offlineValid,returns(evaluateReference('offlineTotals',offlineValid())))]
];
const outcomeMatches=(outcome,expected)=>expected.kind==='error'?outcome?.ok===false&&outcome.error?.name===expected.name&&outcome.error?.message===expected.message:outcome?.ok===true&&exactValue(outcome.value,expected.value),referenceOutcome=test=>{try{return{ok:true,value:evaluateReference(test.method,test.make())}}catch(thrown){return{ok:false,error:{name:thrown?.name??'',message:thrown?.message??String(thrown)}}}};if(refusalGroups.length!==32)throw new Error('Kernel refusal/control allocation drift');if(!refusalGroups.flat(2).every(test=>outcomeMatches(referenceOutcome(test),test.expected)))throw new Error('Kernel refusal/control expected authority disagrees with independent reference');for(let i=0;i<32;i++){const row=failRows[i];if(preimage)record(row.id,'PENDING','direct private-kernel refusal/control is candidate-only; independent reference authority passed');else{const outcomes=refusalGroups[i].flat().map(test=>({test,outcome:evaluateKernelOutcome(test.method,test.make())})),ok=outcomes.every(({test,outcome})=>outcomeMatches(outcome,test.expected));record(row.id,ok?'PASS':'FAIL',`realm-native exact refusal/control group ${i+1}; ${outcomes.length} subcases`)}}
const probeControl=probeSelfTest(),expectedListeners=[['window','storage','function'],['window','storage','function'],['window','storage','function']],startupChecks=[
  [Boolean(core)&&Object.isFrozen(core),'private core exists frozen'],
  [Boolean(core)&&Reflect.ownKeys(core).join('|')===methodOrder.join('|'),'surface order exact'],
  [surfaceDescriptors,'surface data descriptors exact'],
  [Boolean(core)&&methodOrder.every(name=>Object.isFrozen(core[name])),'all seven functions frozen'],
  [Boolean(core)&&methodOrder.every(name=>core[name].name===name),'inferred method names exact'],
  [Boolean(core)&&methodOrder.every(name=>core[name].length===1),'method lengths exact'],
  [Boolean(core)&&methodOrder.every(name=>nonconstructible(core[name])),'methods nonconstructible'],
  [Boolean(core)&&methodOrder.every(name=>!Object.hasOwn(core[name],'prototype')),'methods have no prototype'],
  [boundary.shapeGuardLocated===true&&boundary.shapeGuardBeforeRuntime===true,'surface guard precedes runtime'],
  [realm.effects.storage.length===0,'output realm zero storage'],
  [realm.effects.ui.length===0,'output realm zero UI'],
  [realm.effects.timer.length===0,'output realm zero timer'],
  [realm.effects.network.length===0,'output realm zero network'],
  [JSON.stringify(realm.effects.listeners)===JSON.stringify(expectedListeners),'exact inherited listener registration only'],
  [probeControl.boundary===true&&probeControl.restored===true&&probeControl.realmSeparation===true,'realms isolated and inverse-restored'],
  [probeControl.definitions===true&&probeControl.mutationStatus==='READY'&&probeControl.writes===0,'51 mutation executions defined with zero build writes']
];if(startupChecks.length!==16)throw new Error('Startup guard allocation drift');for(let i=32;i<48;i++){const row=failRows[i],check=startupChecks[i-32];record(row.id,preimage?'PENDING':check[0]?'PASS':'FAIL',preimage?'pre-runtime candidate surface guard is candidate-only':check[1])}
const baseSource=baseHtml=>baseHtml.match(/<script>([\s\S]*?)<\/script>/)?.[1],acceptedBaseSource=baseSource(execFileSync('git',['show','fff84f7dfe87b23040edaa31f07f5f3c9181babf:index.html'],{cwd:ROOT,encoding:'utf8',maxBuffer:32*1024*1024,timeout:30000})),candidateSource=sourceText,signatureAnchors=['function familyBuildingBonusComponents(id,state=S){','function economyHookBonus(name){','function buildingUpgradeCost(level){','function buildingRateComponents(id,state=S,at=runtimeNow()){','function totalRate(state=S,at=runtimeNow()){','function offlineClaimPreview(at=runtimeNow(),state=S){'],signatureChecks=signatureAnchors.map(anchor=>acceptedBaseSource.split(anchor).length===2&&candidateSource.split(anchor).length===2),traceOk=id=>{const evidence=traceEvidence.get(id);return Boolean(evidence)&&evidence.predecessorExact},wrapperCases=[
  ...signatureChecks.map((ok,index)=>[ok,`wrapper signature/default ${index+1} byte-exact`]),
  [traceOk('family-unassigned-command'),'Family return order/result exact'],
  [traceOk('rate-training-l1-neutral'),'Building-rate return order/result exact'],
  [traceOk('offline-one-hour-zero-pending'),'offline return/line/segment order exact'],
  [traceOk('family-elara-hearth-negative-zero'),'Family accepted -0 path exact'],
  [traceOk('neutral-missing-undefined'),'missing neutral hook default exact'],
  [traceOk('upgrade-level-52'),'upgrade high-level result exact'],
  [traceOk('total-rate-mixed'),'total-rate canonical wrapper order exact'],
  [traceOk('duration-zero-neutral'),'offline zero-duration branch/default exact'],
  [(()=>{const authority=traces.traces.find(trace=>trace.id==='duration-zero-neutral'),fixture=encoded(authority.fixture);fixture.at=Infinity;try{evaluateWrapperTrace(authority,fixture);return false}catch(error){return error?.name==='Error'&&error?.message==='Offline preview requires a finite timestamp'}})(),'offline wrapper exact invalid-clock error'],
  [traces.traces.every(trace=>traceOk(trace.id)),'all 32 predecessor wrapper signatures/defaults/errors/output shapes exact']
];if(wrapperCases.length!==16)throw new Error('Wrapper contract allocation drift');for(let i=48;i<64;i++){const [ok,evidence]=wrapperCases[i-48];record(failRows[i].id,ok?'PASS':'FAIL',evidence)}
const phaseNineVerifier=readFileSync(resolve(ROOT,'qa/phase-9/verify.mjs'),'utf8'),phaseNinePrefixEnd=phaseNineVerifier.lastIndexOf('\nconst suite=String.raw`');if(phaseNinePrefixEnd<0)throw new Error('Phase 9 persistence harness boundary missing');const phaseNinePrefix=phaseNineVerifier.slice(0,phaseNinePrefixEnd).replace("const repoRoot=resolve(new URL('../..',import.meta.url).pathname);",`const repoRoot=${JSON.stringify(ROOT)};`)+"\nexport {harness};\n",{harness:persistenceHarness}=await import('data:text/javascript;base64,'+Buffer.from(phaseNinePrefix).toString('base64')),persistenceModule=`import {createHash} from 'node:crypto';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import vm from 'node:vm';${persistenceHarness}\nexport {runRealm,instrument,freshOptions,keys,activeRaw,internal};`,persistenceTools=await import('data:text/javascript;base64,'+Buffer.from(persistenceModule).toString('base64'));
const applicationSource=html=>html.match(/<script>([\s\S]*?)<\/script>/)?.[1],baseHtml=execFileSync('git',['show','fff84f7dfe87b23040edaa31f07f5f3c9181babf:index.html'],{cwd:ROOT,encoding:'utf8',maxBuffer:32*1024*1024,timeout:30000}),baseApplication=applicationSource(baseHtml),candidateApplication=applicationSource(index.toString('utf8'));if(!baseApplication||!candidateApplication)throw new Error('Persistence application script boundary missing');const instrumentedBase=persistenceTools.instrument(baseApplication),instrumentedCandidate=persistenceTools.instrument(candidateApplication),bootPersistence=(application,options={})=>persistenceTools.runRealm({...persistenceTools.freshOptions,...options,applicationSource:application}),baseFresh=bootPersistence(instrumentedBase),schema10Raw=persistenceTools.activeRaw(baseFresh),schema9Raw=persistenceTools.internal(baseFresh,'p9.schemaNineDefault()'),legacyRaw=readFileSync(resolve(ROOT,'qa/fixtures/representative-v0.1.txt'),'utf8'),migratedBase=bootPersistence(instrumentedBase,{activeRaw:schema9Raw,now:1787853601000}),migratedSlots=Object.fromEntries(migratedBase.slots),interruptedPending=bootPersistence(instrumentedBase,{activeRaw:schema9Raw,now:1787853604200,fault:{enabled:true,operation:'setItem',step:'active-write'}}),pendingSlots=Object.fromEntries(interruptedPending.slots),interruptedCommitted=bootPersistence(instrumentedBase,{activeRaw:schema9Raw,now:1787853604300,fault:{enabled:true,operation:'getItem',step:'active-verify'}}),committedSlots=Object.fromEntries(interruptedCommitted.slots);
const stateVariant=(raw,mutate)=>{const state=JSON.parse(raw);mutate(state);return JSON.stringify(state)},maximumStateRaw=stateVariant(schema10Raw,state=>{state.pendingGold=Number.MAX_VALUE;for(const building of Object.values(state.buildings))building.level=52;for(const member of Object.values(state.family)){member.intimacy=Number.MAX_SAFE_INTEGER;member.rarity=5}for(const roll of Object.values(state.familyDrops.buildings))roll.carryContext.buildingLevel=52}),cappedStateRaw=stateVariant(schema10Raw,state=>{state.pendingGold=0;state.lastGoldAt=1787853600000;state.lastSeen=1787853600000}),fractionalStateRaw=stateVariant(schema10Raw,state=>{state.pendingGold=.5;state.lastGoldAt=1787853600000;state.lastSeen=1787853600000});
const persistenceFixtures=[
  {id:'fresh',options:{}},
  {id:'current-schema10',options:{activeRaw:schema10Raw,now:1787853600100}},
  {id:'maximum-valid',options:{activeRaw:maximumStateRaw,now:JSON.parse(maximumStateRaw).lastGoldAt}},
  {id:'schema9-to10',options:{activeRaw:schema9Raw,now:1787853601000}},
  {id:'older-lineage',options:{activeRaw:legacyRaw,now:1787853610000}},
  {id:'evolved-checkpoints',options:{activeRaw:schema9Raw,backupRaw:schema9Raw,preV10BackupRaw:schema9Raw,now:1787853603000}},
  {id:'safe-reset-marker',options:{initialSlots:migratedSlots,now:1787853620000},action:run=>persistenceTools.internal(run,'p9.reset()')},
  {id:'missing-active',options:{activeRaw:null,backupRaw:schema9Raw,preV10BackupRaw:schema9Raw,now:1787853603000}},
  {id:'pending-stage',options:{initialSlots:pendingSlots,now:1787853606000}},
  {id:'committed-cleanup',options:{initialSlots:committedSlots,now:1787853606500}},
  {id:'foreign-checkpoint',options:{activeRaw:schema9Raw,preV10BackupRaw:schema9Raw+' ',now:1787853601000}},
  {id:'corrupt-active',options:{activeRaw:'{',now:1787853601000}},
  {id:'zero-settlement',options:{activeRaw:schema10Raw,now:1787853600000},action:run=>persistenceTools.internal(run,'diagnostics()')},
  {id:'fractional-pending',options:{activeRaw:fractionalStateRaw,now:1787857200000},action:run=>persistenceTools.internal(run,'diagnostics()')},
  {id:'midnight-settlement',options:{activeRaw:schema10Raw,now:1787938200000},action:run=>persistenceTools.internal(run,'diagnostics()')},
  {id:'capped-24h',options:{activeRaw:cappedStateRaw,now:1787961600000},action:run=>persistenceTools.internal(run,'diagnostics()')},
  {id:'staging-write-fault',options:{activeRaw:schema10Raw,now:1787853601000,fault:{enabled:true,operation:'setItem',step:'staging-write'}},action:run=>persistenceTools.internal(run,"p9.grant('gold',1)")},
  {id:'cleanup-fault',options:{activeRaw:schema10Raw,now:1787853601000,fault:{enabled:true,operation:'removeItem',step:'staging-cleanup'}},action:run=>persistenceTools.internal(run,"p9.grant('gold',1)")},
  {id:'twelve-slot-export-read-fault',options:{activeRaw:schema10Raw,now:1787853601000},setup:run=>Object.assign(run.fault,{enabled:true,operation:'getItem',key:persistenceTools.keys.active,step:null,remaining:1,skip:0,adapterOnly:true}),action:run=>persistenceTools.internal(run,'p9.export()')}
];
const numberBits=value=>{const bytes=Buffer.allocUnsafe(8);bytes.writeDoubleBE(value);return bytes.toString('hex')},captureExact=(value,seen=new Map())=>{const type=typeof value;if(type==='number')return{type:'number',bits:numberBits(value)};if(value===null||type==='string'||type==='boolean')return{type,value};if(type==='undefined')return{type:'undefined'};if(type==='bigint')return{type:'bigint',value:String(value)};if(type==='symbol')return{type:'symbol',global:Symbol.keyFor(value)??null,description:value.description??null};if(type==='function')return{type:'function',source:Function.prototype.toString.call(value)};if(seen.has(value))return{type:'reference',ordinal:seen.get(value)};const ordinal=seen.size+1;seen.set(value,ordinal);const prototype=Object.getPrototypeOf(value),prototypeKind=Array.isArray(value)?'Array':prototype===null?'null':Object.getPrototypeOf(prototype)===null?'Object':String(prototype?.constructor?.name??'custom'),properties=Reflect.ownKeys(value).map(key=>{const descriptor=Object.getOwnPropertyDescriptor(value,key),name=typeof key==='symbol'?{symbol:true,global:Symbol.keyFor(key)??null,description:key.description??null}:{symbol:false,value:key};return{name,enumerable:descriptor.enumerable,configurable:descriptor.configurable,...Object.hasOwn(descriptor,'value')?{kind:'data',writable:descriptor.writable,value:captureExact(descriptor.value,seen)}:{kind:'accessor',get:descriptor.get?Function.prototype.toString.call(descriptor.get):null,set:descriptor.set?Function.prototype.toString.call(descriptor.set):null}}});return{type:'object',ordinal,prototypeKind,properties}},persistenceObservation=(application,fixture)=>{const run=bootPersistence(application,fixture.options);fixture.setup?.(run);let result=null,error=null;try{result=fixture.action?.(run)??null}catch(thrown){error={name:thrown?.name??'',message:thrown?.message??String(thrown)}}const activeRaw=persistenceTools.activeRaw(run),revision=activeRaw===null?null:(()=>{try{return JSON.parse(activeRaw)?.saveMeta?.revision??null}catch{return null}})(),exported=(()=>{try{return{value:persistenceTools.internal(run,'p9.export()'),error:null}}catch(thrown){return{value:null,error:{name:thrown?.name??'',message:thrown?.message??String(thrown)}}}})(),observation={fixture:fixture.id,result,error,bootError:run.thrown?{name:run.thrown.name,message:run.thrown.message}:null,state:activeRaw===null?null:persistenceTools.internal(run,'p9.state()'),ui:Object.fromEntries(Object.entries(run.nodes).map(([key,node])=>[key,{innerHTML:node.innerHTML,className:node.className,dataset:node.dataset,style:node.style}])),activeRaw,revision,slots:Object.values(persistenceTools.keys).map((key,index)=>({ordinal:index+1,key,present:run.slots.has(key),value:run.slots.get(key)})),exported,storageLog:run.storageLog,persistenceLog:run.persistenceLog,nativeCalls:run.nativeCalls,runtime:persistenceTools.internal(run,'p9.runtime()')};return deepFreeze(captureExact(observation))};
const persistenceGroups=[[persistenceFixtures[0]],[persistenceFixtures[1],persistenceFixtures[2]],[persistenceFixtures[3]],[persistenceFixtures[4]],[persistenceFixtures[5]],[persistenceFixtures[6]],[persistenceFixtures[7]],[persistenceFixtures[8]],[persistenceFixtures[9]],[persistenceFixtures[10]],[persistenceFixtures[11]],[persistenceFixtures[12],persistenceFixtures[13]],[persistenceFixtures[14],persistenceFixtures[15]],[persistenceFixtures[16]],[persistenceFixtures[17]],[persistenceFixtures[18]]];if(persistenceFixtures.length!==19||persistenceGroups.length!==16||new Set(persistenceGroups.flat().map(item=>item.id)).size!==19)throw new Error('Persistence fixture/group allocation drift');
for(let i=0;i<16;i++){const group=persistenceGroups[i],comparisons=group.map(fixture=>{const baseObservation=persistenceObservation(instrumentedBase,fixture),candidateObservation=persistenceObservation(instrumentedCandidate,fixture);return exactValue(baseObservation,candidateObservation)}),ok=comparisons.every(Boolean);record(failRows[64+i].id,preimage?'PENDING':ok?'PASS':'FAIL',preimage?`${group.map(item=>item.id).join('+')}: candidate persistence observation intentionally absent`:`${group.map(item=>item.id).join('+')}: descriptor/type/Float64 exact isolated return,error,state,UI,raw,revision,12-slot,export,log parity`)}
let buildCheck=null;try{buildCheck=JSON.parse(execFileSync(process.execPath,[resolve(QA,'build-contract.mjs')],{cwd:ROOT,encoding:'utf8',maxBuffer:8*1024*1024,timeout:30000}))}catch{}const noEffects=value=>value.storage.length===0&&value.ui.length===0&&value.timer.length===0&&value.network.length===0,isolationCases=[
  [realm.effects.storage.length===0,'output realm zero storage'],
  [realm.effects.ui.length===0,'output realm zero UI'],
  [realm.effects.timer.length===0,'output realm zero timers'],
  [realm.effects.network.length===0,'output realm zero network'],
  [JSON.stringify(realm.effects.listeners)===JSON.stringify(expectedListeners),'output realm exact inherited listeners only'],
  [realm.restoredSha256===identity.artifactSha256&&realm.restoredByteLength===identity.artifactByteLength,'output realm inverse byte restoration'],
  [callTraceControl.effects.storage.length===0,'call-trace realm zero storage'],
  [callTraceControl.effects.ui.length===0,'call-trace realm zero UI'],
  [callTraceControl.effects.timer.length===0,'call-trace realm zero timers'],
  [callTraceControl.effects.network.length===0,'call-trace realm zero network'],
  [JSON.stringify(callTraceControl.effects.listeners)===JSON.stringify(expectedListeners),'call-trace realm exact inherited listeners only'],
  [callTraceControl.restoredSha256===identity.artifactSha256&&callTraceControl.restoredByteLength===identity.artifactByteLength&&probeControl.realmSeparation===true,'call-trace inverse and realm separation'],
  [noEffects(mutationControl.effects)&&JSON.stringify(mutationControl.effects.listeners)===JSON.stringify(expectedListeners),'mutation realm zero effects and exact listeners'],
  [mutationControl.restoredSha256===identity.artifactSha256&&probeControl.definitions===true,'mutation inverse and exact 48/51 definitions'],
  [buildCheck?.writes===0&&buildCheck?.artifact?.artifactSha256===identity.artifactSha256&&buildCheck?.executableFiles===13,'ordinary builder read-only and identity-bound'],
  [true,'full owned plus 224-file predecessor snapshot checked after execution']
];if(isolationCases.length!==16)throw new Error('Probe/build/no-write isolation allocation drift');for(let i=80;i<96;i++){const [ok,evidence]=isolationCases[i-80];record(failRows[i].id,ok?'PASS':'FAIL',evidence)}

for(const mutation of scenarios.mutationRows){const row=registry.rows.find(item=>item.id.startsWith(`mutation-${String(mutation.id).padStart(2,'0')}-`));if(preimage)record(row.id,'PENDING','one-defect source window intentionally absent from preimage');else{const outcomes=mutation.subcases.map(subcase=>createMutationRealm(mutation.id,subcase)),ok=outcomes.length===mutation.subcases.length&&outcomes.every(result=>result.executed===true&&result.controlPassed===true&&result.mutantFailed===true&&result.failurePath===result.expectedFailurePath&&result.failurePathMatches===true);record(row.id,ok?'PASS':'FAIL','isolated genuine mutation executions with exact expected failure paths')}}

const ordered=registry.rows.map(authority=>results.get(authority.id)??{id:authority.id,status:'FAIL',evidence:'missing result'});
for(let index=0;index<registry.rows.length;index++){const authority=registry.rows[index],result=ordered[index],expected=preimage?authority.preimageExpectation:authority.candidateExpectation;if(authority.ordinal!==index+1||result.status!==expected){result.status='FAIL';result.evidence+=`; expected ${expected} at ordinal ${index+1}`}}
const after=snapshot(),writePreserved=before.size===after.size&&[...before].every(([path,value])=>{const observed=after.get(path);return observed?.exists===value.exists&&(!value.exists||observed.sha256===value.sha256&&observed.byteLength===value.byteLength)});if(!writePreserved){const row=ordered.find(item=>item.id==='fail-probe-build-isolation-16');row.status='FAIL';row.evidence='verifier created, deleted, or changed an owned output or accepted predecessor path'}
const counts=ordered.reduce((sum,row)=>(sum[row.status]=(sum[row.status]||0)+1,sum),{PASS:0,PENDING:0,FAIL:0});
console.log(`Phase 10B-2 focused ${preimage?'PREIMAGE_READY':'candidate'}: ${counts.PASS} passed, ${counts.PENDING} pending, ${counts.FAIL} failed (${registry.rows.length} registered rows)`);console.log(`Categories: ${JSON.stringify(registry.categoryAllocation)}`);console.log(`Artifact: ${identity.artifactSha256} (${identity.artifactByteLength} bytes)`);
if(counts.FAIL){for(const row of ordered.filter(row=>row.status==='FAIL').slice(0,30))console.error('FAIL '+row.id+': '+row.evidence);process.exit(1)}
if(process.argv.includes('--release')&&preimage){console.error('FAIL release mode refuses PREIMAGE_READY; executable candidate is required');process.exit(2)}
