(() => {
  'use strict';
  const CHANNEL='everstead-phase-16-independent';
  const json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config){
    const slots=new Map(),writes=[],errors=[],nativeStorageAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);
    let saveIndex=0,transactionIndex=0,nativeStorageInstrumented=false;
    window.matchMedia=query=>({matches:config.viewport.reducedMotion&&query==='(prefers-reduced-motion: reduce)',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});
    document.documentElement.style.fontSize=`${config.viewport.copyScale||1}em`;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));
    const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>{key=String(key);writes.push({op:'set',key,value:String(value)});slots.set(key,String(value))},removeItem:key=>{key=String(key);writes.push({op:'remove',key});slots.delete(key)}};
    Object.assign(window,{__P16I_CONFIG__:config,__P16I_SLOTS__:slots,__P16I_WRITES__:writes,__P16I_ERRORS__:errors,__P16I_NATIVE_ACCESSES__:nativeStorageAccesses,__P16I_NATIVE_INSTRUMENTED__:nativeStorageInstrumented});
    window.__EVERSTEAD_RUNTIME__={storage:memoryStorage,clock:{now:()=>config.fixtures.frozenNow,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.375,confirm:()=>true,ids:{save:()=>`save-p16i-${++saveIndex}`,transaction:()=>`tx-p16i-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
  }

  function runSuite(){
    const config=window.__P16I_CONFIG__,f=config.fixtures,results=[];
    const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));const until=async(predicate,limit=8000)=>{const started=performance.now();while(performance.now()-started<limit){if(predicate())return true;await wait(25)}return false};
    const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),unique=values=>new Set(values).size===values.length,sorted=values=>[...new Set(values)].sort();
    const add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:typeof detail==='string'?detail:JSON.stringify(detail)});
    const send=()=>parent.postMessage({channel:config.channel,nonce:config.nonce,results,errors:window.__P16I_ERRORS__.slice()},'*');
    const bridge=()=>window.__EVERSTEAD_PHASE_16_QA__,safe=(label,fn)=>{try{return fn()}catch(error){add(label,false,error.stack||error.message);return null}},call=(group,name,...args)=>safe(`${name}-call`,()=>bridge()[group][name](...args));
    const stateOf=snapshot=>snapshot?.state||null,revision=snapshot=>stateOf(snapshot)?.saveMeta?.revision,restaurant=data=>data?.restaurant||data?.facility?.restaurant||null,customers=data=>restaurant(data)?.customers||[],offers=data=>restaurant(data)?.offers||[],outcomes=data=>restaurant(data)?.outcomes||[],archive=data=>data?.claimArchive||data?.claims?.archive||null,resources=data=>data?.resources||{},local=data=>restaurant(data)?.localProgress||{};
    const opportunity=data=>customers(data)[0],restaurantTutorials=data=>(data?.tutorials?.items||data?.tutorials||[]).filter(item=>f.tutorialIds.includes(item.id));
    const economyComplete=policy=>Boolean(policy&&typeof policy.id==='string'&&Number.isSafeInteger(policy.version)&&f.economyRequiredPaths.every(path=>{const value=path.split('.').reduce((node,key)=>node?.[key],policy);return value!==null&&value!==undefined}));
    const shareWithin=(entry,target)=>{if(!entry||!target)return false;const passive=entry.passiveGold,active=entry.activeGold,total=entry.totalGold;if(![passive,active,total].every(Number.isSafeInteger)||passive<0||active<0||total!==passive+active)return false;const n=target.numerator,d=target.denominator;return Number.isSafeInteger(n)&&Number.isSafeInteger(d)&&n>=0&&d>0&&active*d<=total*n};

    (async()=>{
      await until(()=>bridge(),5000);const qa=bridge();add('bridge-present',Boolean(qa));
      if(!qa){add('phase16-contract-unavailable',false,'Expected before Phase 16 implementation: window.__EVERSTEAD_PHASE_16_QA__ is absent.');send();return}
      add('bridge-version',qa.version===f.bridgeVersion,qa.version);
      const requiredRead=['definitions','snapshot','validate','derive','raw','exportSave','passiveBaseline','economyReport'];
      const requiredDestructive=['resetFixture','event','openRestaurant','settle','begin','cancel','prepare','serve','claim','tutorial','advanceOffline','reload','importFixture','simulateConcurrent','probeFinalizerFailure','mutateInvalid'];
      add('bridge-read-surface',requiredRead.every(name=>typeof qa.read?.[name]==='function'),Object.keys(qa.read||{}));add('bridge-destructive-surface',requiredDestructive.every(name=>typeof qa.destructive?.[name]==='function'),Object.keys(qa.destructive||{}));
      if(!requiredRead.every(name=>typeof qa.read?.[name]==='function')||!requiredDestructive.every(name=>typeof qa.destructive?.[name]==='function')){send();return}

      const defs=call('read','definitions');if(!defs){send();return}
      add('phase15-seam-inherited',defs.phase15?.bridgeVersion===f.phase15BridgeVersion&&defs.phase15?.physicalBoard===true&&defs.phase15?.v2Archive===true&&defs.phase15?.trustedFinalizers===true,defs.phase15);
      add('restaurant-definition-lineage',defs.schemaVersion===f.schemaVersion&&defs.configId===f.configId&&defs.definitionSetId===f.definitionSetId&&defs.facilityFrameworkConfigId===f.facilityFrameworkConfigId,defs);
      add('western-plaza-story-opening-contract',defs.facility?.id===f.facilityId&&defs.facility?.mapAnchor===f.physicalMapAnchor&&defs.facility?.discoveryContentId===f.discoveryContentId&&defs.facility?.requiredCapabilityId===f.requiredCapabilityId&&defs.facility?.openingContentId===f.openingContentId&&defs.presentation?.bottomNavigationCount===5&&defs.presentation?.detachedManagementGrid===false,defs.facility);
      add('restaurant-content-identities',same((defs.customers||[]).map(item=>item.id),f.customerIds)&&same((defs.preferences||[]).map(item=>item.id),f.preferenceIds)&&same((defs.recipes||[]).map(item=>item.id),f.recipeIds)&&same((defs.stations||[]).map(item=>item.id),f.stationIds),defs);
      add('nonexpiring-manual-customer-contract',defs.opportunity?.id===f.opportunityDefinitionId&&defs.opportunity?.expires===false&&defs.opportunity?.claimMode==='manual'&&defs.opportunity?.activityId===f.activityId,defs.opportunity);
      add('immutable-restaurant-finalizer-contract',defs.claims?.sourceType===f.phase12ClaimSourceType&&defs.claims?.sourceId===f.activityId&&defs.claims?.immutableFinalizerRegistry===true&&defs.claims?.singleCoordinatorCommit===true&&defs.claims?.callerSuppliedCallbackAllowed===false&&defs.claims?.restaurantFinalizerRegistered===true,defs.claims);
      add('v2-archive-contract',defs.archivePolicy?.configId===f.archiveConfigId&&defs.archivePolicy?.recentReceiptLimit===512&&defs.archivePolicy?.foldBatchSize===128&&defs.archivePolicy?.stableOrdinals===true,defs.archivePolicy);
      const tutorialDefs=defs.tutorials||[],cast=defs.castHooks||[];
      add('seven-gradual-tutorials',same(tutorialDefs.map(item=>item.id),f.tutorialIds)&&tutorialDefs.every(item=>item.skippable===true&&item.loggable===true&&item.replayable===true&&item.reward==null&&item.blocking===false),tutorialDefs);
      add('exact-seven-cast-hooks',same(sorted(cast.map(item=>item.actorId)),sorted(f.actorIds))&&cast.every(item=>item.registered===true&&item.mechanicalCopyIndependent===true),cast);
      add('cast-selection-and-visual-fallback',defs.castPolicy?.lockedFellowsExcluded===true&&same(defs.castPolicy?.artFallbackOrder,f.approvedVisualFallbacks)&&defs.castPolicy?.forbiddenPresentation==='unframed-full-background-profile-overlay',defs.castPolicy);

      const policyReport=call('read','economyReport'),enabled=defs.productionEnabled===true;
      if(enabled){const policy=policyReport?.policy,reports=policyReport?.simulations||[],target=policy?.activeProfitTargetShare;add('enabled-economy-policy-complete-versioned',economyComplete(policy)&&policyReport?.approved===true,policyReport);add('economy-all-profile-horizon-reports',f.economyProfiles.every(profile=>f.economyHorizons.every(horizon=>reports.some(row=>row.profile===profile&&row.horizon===horizon))),reports);add('economy-active-share-within-candidate-target',reports.every(row=>shareWithin(row,target)),{target,reports});add('economy-headroom-and-passive-preservation',Number(policy?.headroomYears)>=5&&reports.every(row=>row.safeIntegerHeadroom===true&&row.passiveBaselinePreserved===true)&&policyReport?.permanentMultiplierIntroduced===false&&policyReport?.passiveIncomeReduced===false&&policyReport?.newCurrencyIntroduced===false&&policyReport?.debtPossible===false,policyReport)}else{add('disabled-economy-fails-closed',policyReport?.productionEnabled===false&&policyReport?.accrualEnabled===false&&policyReport?.serviceEnabled===false,policyReport)}

      const passiveBefore=call('read','passiveBaseline');
      call('destructive','resetFixture',f.saveFixtures.fresh);const beforeUnlock=call('read','derive'),historical=call('destructive','event','story.scene-resolved',{sceneId:f.discoveryContentId,occurredAt:f.frozenNow-50000000}),unlock=call('destructive','event','facility.capability-granted',{facilityId:f.facilityId,capabilityId:f.requiredCapabilityId,capturedAt:f.frozenNow}),afterUnlock=call('read','derive'),unlocked=restaurant(afterUnlock);
      add('story-discovers-capability-opens-without-backdating',historical?.ok===true&&unlock?.ok===true&&unlocked?.unlockedAt===f.frozenNow&&unlocked?.cursorAt===f.frozenNow&&customers(afterUnlock).length===0,{historical,unlock,unlocked});
      const reopenRaw=call('read','raw'),reopen=call('destructive','event','facility.capability-granted',{facilityId:f.facilityId,capabilityId:f.requiredCapabilityId,capturedAt:f.frozenNow+1});add('repeated-unlock-write-free',reopen?.ok===false&&Number(reopen?.writes||0)===0&&call('read','raw')===reopenRaw,reopen);

      call('destructive','resetFixture',f.saveFixtures.unlocked);const empty=call('read','derive'),emptyResources=resources(empty),emptyLocal=local(empty),partial=call('destructive','settle',f.facilityId,f.frozenNow+f.syntheticPolicy.intervalMs-1),partialState=call('read','derive');
      add('partial-interval-carries-with-zero-credit',partial?.ok===true&&partial?.createdCount===0&&partial?.carryMs===f.syntheticPolicy.intervalMs-1&&customers(partialState).length===0&&same(resources(partialState),emptyResources)&&same(local(partialState),emptyLocal),partial);
      call('destructive','resetFixture',f.saveFixtures.unlocked);const settled=call('destructive','settle',f.facilityId,f.frozenNow+2*f.syntheticPolicy.intervalMs),settledState=call('read','derive'),settledCustomers=customers(settledState);
      add('deterministic-customer-bank-and-ordinals',settled?.ok===true&&settled?.createdCount===2&&same(settledCustomers.map(item=>item.ordinal),[1,2])&&unique(settledCustomers.map(item=>item.identity))&&settledCustomers.every(item=>item.status==='banked'&&item.expiresAt==null),{settled,settledCustomers});
      const reloadRaw=call('read','raw');call('destructive','reload');add('bank-identities-stable-reload',call('read','raw')===reloadRaw&&same(customers(call('read','derive')),settledCustomers),customers(call('read','derive')));
      const saturated=call('destructive','settle',f.facilityId,f.frozenNow+48*f.syntheticPolicy.intervalMs),saturatedCustomers=customers(call('read','derive'));add('bank-saturates-nonexpiring-no-debt',saturated?.ok===true&&saturatedCustomers.length===f.syntheticPolicy.bankCapacity&&saturatedCustomers.every(item=>item.expiresAt==null)&&saturated?.hiddenDebtMs===0&&saturated?.elapsedAppliedMs<=f.offlineCapMs,{saturated,saturatedCustomers});
      const rollbackRaw=call('read','raw'),rollback=call('destructive','settle',f.facilityId,f.frozenNow-1);add('clock-rollback-write-free',rollback?.ok===true&&Number(rollback?.writes||0)===0&&call('read','raw')===rollbackRaw,rollback);
      const timeCases=call('destructive','advanceOffline',{kind:'epoch-equivalence',elapsedMs:f.offlineCapMs*2,includeMidnight:true,includeDst:true});add('offline-midnight-dst-epoch-equivalent',timeCases?.ok===true&&timeCases?.appliedMs===f.offlineCapMs&&timeCases?.timezoneEquivalent===true&&timeCases?.midnightSegmented===false&&timeCases?.dstSegmented===false,timeCases);

      call('destructive','resetFixture',f.saveFixtures.banked);let item=opportunity(call('read','derive'));const begin=call('destructive','begin',item.id,item.identity),begun=opportunity(call('read','derive'));add('preference-visible-on-begin',begin?.ok===true&&begun?.status==='engaged'&&f.preferenceIds.includes(begun?.preferenceId),begun);
      const preCancelRaw=call('read','raw'),cancel=call('destructive','cancel',begun.id,begun.identity),cancelled=opportunity(call('read','derive'));add('safe-cancel-before-commit-rebanks',cancel?.ok===true&&cancelled?.status==='banked'&&cancelled?.identity===begun.identity&&offers(call('read','derive')).length===0&&outcomes(call('read','derive')).length===0,{cancel,cancelled,changed:call('read','raw')!==preCancelRaw});
      const beginAgain=call('destructive','begin',cancelled.id,cancelled.identity),engaged=opportunity(call('read','derive')),recipe=f.recipeIds[0],station=f.stationIds[0],prepare=call('destructive','prepare',engaged.id,engaged.identity,{recipeId:recipe,stationId:station,stockIdentity:'stock.qa.hearth-stew.1'}),prepared=opportunity(call('read','derive')),preparedRaw=call('read','raw');call('destructive','reload');const resumed=opportunity(call('read','derive'));
      add('preparation-commit-resumes-exactly',beginAgain?.ok===true&&prepare?.ok===true&&prepared?.status==='preparing'&&resumed?.identity===prepared.identity&&resumed?.recipeId===recipe&&resumed?.stationId===station&&resumed?.stockIdentity==='stock.qa.hearth-stew.1'&&call('read','raw')===preparedRaw,{prepare,prepared,resumed});
      const postCommitClose=call('destructive','cancel',resumed.id,resumed.identity);add('post-commit-cancel-does-not-rollback',postCommitClose?.ok===false&&Number(postCommitClose?.writes||0)===0&&call('read','raw')===preparedRaw,postCommitClose);
      const beforeServe=call('read','derive'),serve=call('destructive','serve',resumed.id,resumed.identity),served=call('read','derive'),ready=opportunity(served);add('serve-creates-immutable-result-zero-payment',serve?.ok===true&&ready?.status==='claim-ready'&&outcomes(served).length===1&&offers(served).length===1&&offers(served)[0]?.sourceId===f.activityId&&same(resources(served),resources(beforeServe))&&same(local(served),local(beforeServe)),{serve,ready,outcomes:outcomes(served),offers:offers(served)});

      call('destructive','resetFixture',f.saveFixtures.partialReady);const partialReady=opportunity(call('read','derive')),partialOffer=offers(call('read','derive'))[0];add('imperfect-result-smaller-nonnegative',partialReady?.result==='partial'&&Number.isSafeInteger(partialOffer?.preview?.gold)&&partialOffer.preview.gold>=0&&partialOffer.preview.gold<f.syntheticPolicy.baseSale+f.syntheticPolicy.matchedTip&&partialOffer?.preview?.debt==null&&partialReady?.status==='claim-ready',{partialReady,partialOffer});

      call('destructive','resetFixture',f.saveFixtures.matchedReady);const claimReady=opportunity(call('read','derive')),offer=offers(call('read','derive'))[0],beforeClaim=call('read','derive'),beforeSnapshot=call('read','snapshot'),claim=call('destructive','claim',offer.id,offer.identity),claimed=call('read','derive'),receipt=(archive(claimed)?.recentReceipts||[]).at(-1);
      add('claim-atomic-global-local-metrics-lineage',claim?.ok===true&&revision(call('read','snapshot'))===revision(beforeSnapshot)+1&&claim?.globalApplications===1&&claim?.localApplications===1&&claim?.stockApplications===1&&claim?.metricApplications>=1&&claim?.receiptApplications===1&&customers(claimed).length===0&&offers(claimed).length===0&&Number(resources(claimed).gold)>Number(resources(beforeClaim).gold)&&Number(local(claimed).reputation)>=Number(local(beforeClaim).reputation)&&receipt?.sourceId===f.activityId&&receipt?.ordinal===claimReady.ordinal,{claim,receipt,before:beforeClaim,after:claimed});
      const claimedRaw=call('read','raw'),repeat=call('destructive','claim',offer.id,offer.identity);add('claim-exactly-once-reload-safe',repeat?.ok===false&&Number(repeat?.writes||0)===0&&call('read','raw')===claimedRaw,repeat);call('destructive','reload');add('claimed-effects-persist-exactly',call('read','raw')===claimedRaw&&call('read','validate')?.ok===true,call('read','derive'));
      for(const mode of ['missing','throw','stock','archive']){call('destructive','resetFixture',f.saveFixtures.matchedReady);const before=call('read','raw'),failure=call('destructive','probeFinalizerFailure',mode);add(`restaurant-finalizer-${mode}-atomic-refusal`,failure?.ok===false&&Number(failure?.writes||0)===0&&call('read','raw')===before,failure)}
      for(const kind of ['settle','prepare','serve','claim']){const race=call('destructive','simulateConcurrent',kind);add(`two-client-${kind}-one-winner`,race?.ok===true&&race?.winnerCount===1&&race?.loserCount===1&&race?.losingWrites===0&&race?.duplicateCustomerCount===0&&race?.duplicateOutcomeCount===0&&race?.duplicateReceiptCount===0&&race?.finalValid===true,race)}

      call('destructive','resetFixture',f.saveFixtures.namedVisitorReady);const visitorOffer=offers(call('read','derive'))[0],beforeVisitor=call('read','derive');add('named-visitor-hook-absent-before-claim',!(beforeVisitor?.chronicle?.queuedHookIds||[]).includes(f.namedVisitor.chronicleHookId),beforeVisitor?.chronicle);const visitorClaim=call('destructive','claim',visitorOffer.id,visitorOffer.identity),afterVisitor=call('read','derive'),hookIds=afterVisitor?.chronicle?.queuedHookIds||[];add('named-visitor-queues-original-hook-after-claim-once',visitorClaim?.ok===true&&hookIds.filter(id=>id===f.namedVisitor.chronicleHookId).length===1&&visitorClaim?.rewardApplications===1,{visitorClaim,hookIds});const visitorRaw=call('read','raw'),play=call('destructive','event','chronicle.play',{hookId:f.namedVisitor.chronicleHookId}),replay=call('destructive','event','chronicle.replay',{hookId:f.namedVisitor.chronicleHookId});add('chronicle-play-replay-reward-neutral',play?.ok===true&&replay?.ok===true&&call('read','raw')===visitorRaw,{play,replay});

      call('destructive','resetFixture',f.saveFixtures.archiveWindow);const archiveBefore=archive(call('read','derive')),archiveOffer=offers(call('read','derive'))[0],archiveClaim=call('destructive','claim',archiveOffer.id,archiveOffer.identity),archiveAfter=archive(call('read','derive'));add('v2-archive-folds-with-stable-lineage',archiveBefore?.recentReceipts?.length===512&&archiveClaim?.ok===true&&archiveAfter?.recentReceipts?.length===f.archivePolicy.expectedRecentAfterNextClaim&&archiveAfter?.throughSequence===f.archivePolicy.expectedThroughAfterNextClaim&&archiveAfter?.nextSequence===513&&archiveAfter?.throughSequence+archiveAfter?.recentReceipts?.length===archiveAfter?.nextSequence,{before:archiveBefore,after:archiveAfter});
      const exported=call('read','exportSave'),exportRaw=call('read','raw'),imported=call('destructive','importFixture',exported);add('export-import-preserves-restaurant-and-archive',imported?.ok===true&&call('read','raw')===exportRaw&&call('read','validate')?.ok===true&&same(archive(call('read','derive')),archiveAfter),imported);

      call('destructive','resetFixture',f.saveFixtures.migrated);const migrated=call('read','derive');add('migration-no-retroactive-restaurant-value',call('read','validate')?.ok===true&&restaurant(migrated)?.historicalBaseline==='unknown'&&customers(migrated).length===0&&offers(migrated).length===0&&outcomes(migrated).length===0&&restaurant(migrated)?.unlockedAt==null,migrated);
      call('destructive','resetFixture',f.saveFixtures.recovery);const recoveryBefore=call('read','derive'),recovery=call('destructive','reload'),recoveryAfter=call('read','derive');add('recovery-one-authority-no-duplicates',recovery?.ok===true&&call('read','validate')?.ok===true&&unique(customers(recoveryAfter).map(item=>item.identity))&&archive(recoveryAfter)?.nextSequence===archive(recoveryBefore)?.nextSequence,{recovery,before:recoveryBefore,after:recoveryAfter});
      call('destructive','resetFixture',f.saveFixtures.fresh);const safeRaw=call('read','raw'),corrupt=call('destructive','resetFixture',f.saveFixtures.corrupt);add('corrupt-refused-original-exportable',corrupt?.ok===false&&Number(corrupt?.writes||0)===0&&corrupt?.preservedForExport===true&&call('read','raw')===safeRaw,corrupt);const future=call('destructive','resetFixture',f.saveFixtures.future);add('future-refused-original-exportable',future?.ok===false&&future?.reason==='future-version'&&future?.preservedForExport===true&&Number(future?.writes||0)===0&&call('read','raw')===safeRaw,future);
      const invalid= f.invalidMutationChecks.map(kind=>call('destructive','mutateInvalid',kind));add('malformed-imports-fail-closed',invalid.every((result,index)=>result?.ok===false&&result?.check===f.invalidMutationChecks[index]&&Number(result?.writes||0)===0)&&call('read','raw')===safeRaw,invalid);

      call('destructive','resetFixture',f.saveFixtures.unlocked);const firstTutorial=call('destructive','tutorial',f.tutorialIds[0],'open'),secondTutorial=call('destructive','tutorial',f.tutorialIds[1],'open'),skipped=call('destructive','tutorial',f.tutorialIds[0],'skip'),tutorialRaw=call('read','raw'),log=call('destructive','tutorial',f.tutorialIds[0],'log'),tutorialReplay=call('destructive','tutorial',f.tutorialIds[0],'replay'),tutorialState=restaurantTutorials(call('read','derive'));
      add('tutorial-one-safe-auto-presentation',firstTutorial?.ok===true&&firstTutorial?.autoPresented===true&&secondTutorial?.ok===false&&Number(secondTutorial?.writes||0)===0&&tutorialState.some(item=>item.id===f.tutorialIds[0]&&item.status==='dismissed'),{firstTutorial,secondTutorial,skipped,tutorialState});add('tutorial-skip-log-replay-neutral',skipped?.ok===true&&log?.ok===true&&tutorialReplay?.ok===true&&call('read','raw')===tutorialRaw,{skipped,log,tutorialReplay});
      call('destructive','resetFixture',f.saveFixtures.lockedRoster);call('destructive','openRestaurant');const dialogue=call('read','derive')?.dialogue||{},joined=call('read','derive')?.roster?.joinedFellowIds||[],selected=dialogue.selectedSpeakers||[];add('locked-fellows-never-speak',selected.every(actorId=>!String(actorId).startsWith('fellow.')||joined.includes(actorId)),{selected,joined});add('approved-visual-fallback-only',(dialogue.presentations||[]).every(item=>f.approvedVisualFallbacks.includes(item.mode)&&item.unframedFullPortrait!==true),dialogue.presentations);

      call('destructive','resetFixture',f.saveFixtures.banked);await wait(50);const nav=[...document.querySelectorAll('[data-tab],nav button,[role="navigation"] button')].filter(node=>{const style=getComputedStyle(node);return style.display!=='none'&&style.visibility!=='hidden'}),hotspot=document.querySelector('[data-phase15-facility-id="facility.restaurant"]'),board=document.querySelector('[data-phase15-facility-board]');
      add('actual-dom-five-nav-and-western-hotspot',nav.length===5&&Boolean(board)&&Boolean(hotspot)&&hotspot?.dataset.phase15MapAnchor===f.physicalMapAnchor,{nav:nav.map(node=>node.textContent.trim()),board:Boolean(board),hotspot:hotspot?.outerHTML?.slice(0,400)});
      const hotspotRect=hotspot?.getBoundingClientRect(),targetOk=hotspotRect&&hotspotRect.width>=44&&hotspotRect.height>=44&&hotspotRect.left>=0&&hotspotRect.right<=innerWidth+1&&hotspotRect.bottom<=innerHeight+1;add('actual-dom-hotspot-target-in-viewport',targetOk,hotspotRect);
      let focusOk=false,escapeOk=false,keyboardOk=false,requiredControls=false;if(hotspot){hotspot.focus();const beforeOpen=call('read','raw');hotspot.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));hotspot.click();await wait(30);const sheet=document.querySelector('[data-phase16-restaurant-sheet]');focusOk=Boolean(sheet)&&sheet.contains(document.activeElement);requiredControls=f.requiredDomSelectors.slice(2).every(selector=>document.querySelector(selector));keyboardOk=Boolean(sheet)&&Boolean(sheet.textContent.trim())&&[...sheet.querySelectorAll('button,[role="button"],input,select')].every(node=>node.matches(':disabled')||node.tabIndex>=0);document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(30);escapeOk=document.activeElement===hotspot&&call('read','raw')===beforeOpen}
      add('actual-dom-focus-keyboard-escape',focusOk&&keyboardOk&&escapeOk,{focusOk,keyboardOk,escapeOk,active:document.activeElement?.outerHTML?.slice(0,200)});add('actual-dom-restaurant-controls-present',requiredControls,f.requiredDomSelectors);
      const noOverflow=document.documentElement.scrollWidth<=document.documentElement.clientWidth+1&&document.body.scrollWidth<=document.body.clientWidth+1;add('actual-dom-no-overflow-at-copy-scale',noOverflow,{viewport:[innerWidth,innerHeight],copyScale:config.viewport.copyScale,document:[document.documentElement.clientWidth,document.documentElement.scrollWidth]});
      const reducedOk=config.viewport.reducedMotion?[...document.querySelectorAll('[data-phase15-facility-board],[data-phase15-facility-id="facility.restaurant"],[data-phase16-restaurant-sheet]')].every(node=>{const style=getComputedStyle(node);return style.animationName==='none'||style.animationDuration==='0s'}):true;add('actual-dom-reduced-motion-equivalence',reducedOk,{reducedMotion:config.viewport.reducedMotion});
      add('passive-buildings-gold-oaths-family-preserved',same(call('read','passiveBaseline'),passiveBefore),{before:passiveBefore,after:call('read','passiveBaseline')});add('final-state-valid',call('read','validate')?.ok===true,call('read','validate'));add('native-storage-instrumented',window.__P16I_NATIVE_INSTRUMENTED__===true);add('zero-native-storage-accesses',window.__P16I_NATIVE_ACCESSES__.length===0,window.__P16I_NATIVE_ACCESSES__);add('zero-warning-error-console',window.__P16I_ERRORS__.length===0,window.__P16I_ERRORS__);send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();if(source.indexOf('<script')<0)throw new Error('Production script tag missing');const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`;source=source.replace('<head>','<head><base href="../../">');const insertion=source.indexOf('<script');source=source.slice(0,insertion)+bootstrap+source.slice(insertion).replace('</body>',suite+'</body>');document.open();document.write(source);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
