import {createHash} from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
import {existsSync,readFileSync,readdirSync,statSync} from 'node:fs';
import {resolve} from 'node:path';

const ROOT=resolve(new URL('../..',import.meta.url).pathname),QA=resolve(ROOT,'qa/phase-16-independent'),NODE=process.execPath;
const BASE='8d356b7a1bb4922a354ec7bc93f8e6587c8b9514',PACKAGE_ONLY=process.argv.includes('--package-only');
const EXPECTED=['README.md','checksums.sha256','fixtures/contract-fixtures.json','fixtures/inherited-hashes.json','index.html','realm.html','realm.js','runner.js','verify.mjs'];
const rows=[],record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)});
const read=path=>readFileSync(resolve(ROOT,path)),text=path=>read(path).toString('utf8'),json=path=>JSON.parse(text(path)),sha=value=>createHash('sha256').update(value).digest('hex');
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),unique=values=>new Set(values).size===values.length,sorted=values=>[...new Set(values)].sort();
const git=args=>execFileSync('/usr/bin/git',args,{cwd:ROOT,encoding:'utf8',maxBuffer:128*1024*1024}),gitBytes=args=>execFileSync('/usr/bin/git',args,{cwd:ROOT,maxBuffer:256*1024*1024}),baseRead=path=>gitBytes(['show',`${BASE}:${path}`]);
const fixtures=json('qa/phase-16-independent/fixtures/contract-fixtures.json'),inherited=json('qa/phase-16-independent/fixtures/inherited-hashes.json');
const restaurant=json('design/phase-15-16/restaurant-definitions.json'),tutorials=json('design/phase-15-16/tutorial-extension.json'),cast=json('design/phase-15-16/cast-hooks.json'),designFixtures=json('design/phase-15-16/fixtures.json'),unlocks=json('design/phase-17/facility-unlocks.json'),phase14=json('design/phase-14/facility-definitions.json');

function filesBelow(directory,prefix=''){const paths=[];for(const name of readdirSync(directory)){const absolute=resolve(directory,name),path=prefix?`${prefix}/${name}`:name;if(statSync(absolute).isDirectory())paths.push(...filesBelow(absolute,path));else paths.push(path)}return paths.sort()}
function productionSources(){const files=[];function visit(directory,prefix=''){for(const entry of readdirSync(directory,{withFileTypes:true})){if(!prefix&&['.git','assets','design','docs','qa'].includes(entry.name))continue;const path=prefix?`${prefix}/${entry.name}`:entry.name,absolute=resolve(directory,entry.name);if(entry.isDirectory())visit(absolute,path);else if(/\.(?:html|m?js|json)$/.test(path))files.push(path)}}visit(ROOT);return files.sort()}
const ids=items=>items.map(item=>item.id);

record('base-commit-reachable',git(['merge-base','--is-ancestor',BASE,'HEAD'])==='');
record('package-topology',same(filesBelow(QA),EXPECTED),filesBelow(QA));
const checksumRows=existsSync(resolve(ROOT,'qa/phase-16-independent/checksums.sha256'))?text('qa/phase-16-independent/checksums.sha256').trim().split('\n').filter(Boolean).map(line=>{const match=line.match(/^([0-9a-f]{64})  (.+)$/);return match?{expected:match[1],path:match[2]}:null}):[];
const checksumFailures=checksumRows.filter(item=>!item||!existsSync(resolve(ROOT,item.path))||sha(read(item.path))!==item.expected).map(item=>item?.path||'malformed');
record('package-checksums',checksumRows.length===10&&checksumFailures.length===0,{count:checksumRows.length,failures:checksumFailures});
record('contract-and-result-documents',['docs/PHASE_16_INDEPENDENT_QA_CONTRACT.md','docs/PHASE_16_INDEPENDENT_QA_RESULT.md'].every(path=>existsSync(resolve(ROOT,path))));
const contract=text('docs/PHASE_16_INDEPENDENT_QA_CONTRACT.md');
record('contract-scope-correct',contract.includes('first complete consumer')&&contract.includes('does not implement production runtime')&&contract.includes('does not hard-code eventual production')&&contract.includes('without a sixth navigation item'));
record('contract-lifecycle-complete',['unlockedAt','cursorAt','retroactive','non-expiring','24 elapsed hours','preference → recipe and station choice → resumable preparation → serve result → explicit Claim','Cancel','imperfect valid match','smaller nonnegative','named visitor'].every(value=>contract.includes(value)));
record('contract-atomicity-and-lineage',['immutable registered finalizers','global Gold','Restaurant reputation','recipe mastery','stock','metrics','claimed ordinal/range lineage','V2 bounded archive/checkpoint lineage','two-client'].every(value=>contract.includes(value)));
record('contract-save-and-regression-matrix',['fresh, migrated, offline, recovery, import, future, corrupt','original four Buildings','global Gold/Oath state','Family assignments','Phases 12–15'].every(value=>contract.includes(value)));
record('contract-tutorial-cast-and-dom',['seven accepted Phase 16 tutorials','At most one tutorial auto-presents','Exactly seven Phase 16 cast hooks','locked Fellow','320×568','390×844','1024×768','175 percent copy','reduced motion','focus entry/return','Escape'].every(value=>contract.includes(value)));
record('contract-actual-dom-blind-spot',contract.includes('Actual-DOM browser gate')&&contract.includes('Normalized QA output alone cannot prove')&&contract.includes('actual nodes and styles'));

record('fixture-provenance',fixtures.contractVersion===1&&fixtures.bridgeVersion==='phase-16-independent-qa-v1'&&fixtures.baseCommit===BASE&&fixtures.schemaVersion===12);
record('fixture-restaurant-identities',fixtures.facilityId==='facility.restaurant'&&fixtures.activityId==='activity.restaurant-service'&&fixtures.opportunityDefinitionId==='opportunity.facility.restaurant.customer'&&fixtures.physicalMapAnchor==='western-plaza-restaurant');
record('fixture-definition-cardinality',fixtures.customerIds.length===3&&fixtures.preferenceIds.length===3&&fixtures.recipeIds.length===3&&fixtures.stationIds.length===2&&unique([...fixtures.customerIds,...fixtures.preferenceIds,...fixtures.recipeIds,...fixtures.stationIds]));
record('fixture-named-visitor',same(fixtures.namedVisitor,{id:'restaurant.visitor.route-envoy.01',actorId:'family.jaina',sourceEventId:'story.book1.restaurant.route-envoy-ready',customerDefinitionId:'restaurant.customer.route-envoy',chronicleHookId:'chronicle.restaurant.route-envoy.01'}));
record('fixture-seven-tutorials-and-cast',fixtures.tutorialIds.length===7&&fixtures.actorIds.length===7&&unique(fixtures.tutorialIds)&&unique(fixtures.actorIds));
record('fixture-save-matrix',same(Object.keys(fixtures.saveFixtures),['fresh','migrated','unlocked','banked','preCommit','prepared','matchedReady','partialReady','namedVisitorReady','archiveWindow','offline','recovery','corrupt','future','lockedRoster'])&&unique(Object.values(fixtures.saveFixtures)));
record('fixture-qa-policy-only',fixtures.syntheticPolicy.qaOnly===true&&Number.isSafeInteger(fixtures.syntheticPolicy.intervalMs)&&Number.isSafeInteger(fixtures.syntheticPolicy.bankCapacity)&&fixtures.syntheticPolicy.activeProfitTargetShare.denominator>0);
record('fixture-policy-is-not-production-numbers',!contract.includes(String(fixtures.syntheticPolicy.baseSale))&&!contract.includes(String(fixtures.syntheticPolicy.matchedTip)));
record('fixture-dynamic-economy-gate',fixtures.economyRequiredPaths.length>=15&&same(fixtures.economyProfiles,['fresh','midgame','established','highly-active','mostly-idle'])&&same(fixtures.economyHorizons,['short','long']));
record('fixture-fourteen-accepted-scenarios',fixtures.fixtureIds.length===14&&unique(fixtures.fixtureIds));
record('fixture-v2-archive-policy',fixtures.archiveConfigId==='claim-archive.phase-15.v1'&&same(fixtures.archivePolicy,{recentReceiptLimit:512,foldBatchSize:128,expectedRecentAfterNextClaim:385,expectedThroughAfterNextClaim:128}));
record('fixture-five-realms',fixtures.viewports.length===5&&fixtures.viewports.some(item=>item.width===320&&item.height===568)&&fixtures.viewports.some(item=>item.width===390&&item.height===844)&&fixtures.viewports.some(item=>item.width===1024&&item.height===768)&&fixtures.viewports.some(item=>item.reducedMotion)&&fixtures.viewports.some(item=>item.copyScale===1.75));
record('fixture-dom-and-invalid-matrix',fixtures.requiredDomSelectors.length===11&&fixtures.invalidMutationChecks.length===9&&unique(fixtures.requiredDomSelectors)&&unique(fixtures.invalidMutationChecks));

record('design-restaurant-provenance',restaurant.configId===fixtures.configId&&restaurant.definitionSetId===fixtures.definitionSetId&&restaurant.facilityFrameworkConfigId===fixtures.facilityFrameworkConfigId);
record('design-content-identities-exact',same(ids(restaurant.customers),fixtures.customerIds)&&same(ids(restaurant.preferences),fixtures.preferenceIds)&&same(ids(restaurant.recipes),fixtures.recipeIds)&&same(ids(restaurant.stations),fixtures.stationIds));
record('design-opportunity-manual-nonexpiring',restaurant.opportunityDefinition.id===fixtures.opportunityDefinitionId&&restaurant.opportunityDefinition.expires===false&&restaurant.opportunityDefinition.claimMode==='manual'&&restaurant.opportunityDefinition.activityId===fixtures.activityId);
record('design-candidate-economy-still-disabled',restaurant.productionEnabled===false&&restaurant.facility.operational.intervalMs===null&&restaurant.facility.operational.bankCapacity===null&&restaurant.facility.operational.activeProfitTargetShare===null&&Object.values(restaurant.economyPolicy.baseSaleByCustomerId).every(value=>value===null));
record('design-three-preferences',restaurant.preferences.every(item=>item.requiredRecipeTags.length===1&&item.likedRecipeTags.length===1));
record('design-recipe-station-references',restaurant.recipes.every(item=>item.compatibleStationIds.length>=1&&item.compatibleStationIds.every(id=>fixtures.stationIds.includes(id)))&&restaurant.facility.initialRecipeIds.every(id=>fixtures.recipeIds.includes(id))&&restaurant.facility.initialStationIds.every(id=>fixtures.stationIds.includes(id)));
record('design-named-visitor-exact',same({id:restaurant.namedVisitors[0].id,actorId:restaurant.namedVisitors[0].actorId,sourceEventId:restaurant.namedVisitors[0].sourceEventId,customerDefinitionId:restaurant.namedVisitors[0].customerDefinitionId,chronicleHookId:restaurant.namedVisitors[0].chronicleHookId},fixtures.namedVisitor)&&restaurant.namedVisitors[0].repeatable===false&&restaurant.namedVisitors[0].expires===false);
const p16Tutorials=tutorials.tutorials.filter(item=>item.runtimeDeliveryPhase===16),p16Cast=cast.actors.filter(item=>item.earliestFacilityPhase===16);
record('design-seven-tutorials-exact',same(ids(p16Tutorials),fixtures.tutorialIds)&&p16Tutorials.every(item=>item.stepIds.length>=3&&item.reward==null&&item.speaker?.primaryActorId));
record('design-seven-cast-exact',same(ids(p16Cast.map(item=>({id:item.actorId}))),fixtures.actorIds)&&p16Cast.every(item=>item.hookIds.length===2));
record('design-cast-selection-policy',cast.selectionPolicy.lockedFellowsExcluded===true&&cast.selectionPolicy.deterministicFallbackOrder===true&&cast.selectionPolicy.mechanicalCopyIndependentOfSpeaker===true&&same(cast.selectionPolicy.artFallbackOrder,fixtures.approvedVisualFallbacks)&&cast.selectionPolicy.forbiddenPresentation==='unframed-full-background-profile-overlay');
const restaurantUnlock=unlocks.facilityUnlocks.find(item=>item.facilityId===fixtures.facilityId);
record('phase17-physical-unlock-exact',restaurantUnlock.mapAnchor===fixtures.physicalMapAnchor&&restaurantUnlock.targetPhase===16&&restaurantUnlock.discovery.contentId===fixtures.discoveryContentId&&restaurantUnlock.activeInteraction.requiredCapabilityId===fixtures.requiredCapabilityId&&restaurantUnlock.activeInteraction.openingContentId===fixtures.openingContentId);
record('phase17-story-capability-separation',unlocks.globalRules.storyIsDiscoveryAuthority===true&&unlocks.globalRules.activeInteractionNeedsCapabilityAndOpening===true&&unlocks.globalRules.passiveBuildingStateIsIndependent===true&&unlocks.globalRules.neverRelockAnOperationalSuccessor===true);
const designP16=designFixtures.fixtures.filter(item=>item.phase===16);
record('design-fourteen-fixtures-exact',same(ids(designP16),fixtures.fixtureIds));
record('design-fixtures-cover-core-risks',['migration','unlock','offline','partial-interval','bank-cap','clock-rollback','engagement','safe-cancel','reload','manual-claim','two-tab','named-visitor','tutorial','economy','mobile','import','recovery'].every(tag=>designP16.some(item=>item.covers.includes(tag))));
record('phase15-waystone-stays-authored-event-only',phase14.facilities.find(item=>item.id==='facility.waystone')?.operational.generationMode==='authored-event'&&phase14.opportunityDefinitions.find(item=>item.facilityId==='facility.waystone')?.generation==='authored-event');
record('original-passive-facilities-preserved-by-design',fixtures.originalPassiveFacilityIds.every(id=>unlocks.facilityUnlocks.find(item=>item.facilityId===id)?.passivePolicy==='preserve-existing-building-production-and-family-assignment'));

const inheritedFailures=Object.entries(inherited.files).filter(([path,expected])=>{try{return sha(baseRead(path))!==expected}catch{return true}}).map(([path])=>path);
record('inherited-phase12-through-phase15-byte-frozen',inherited.baseCommit===BASE&&Object.keys(inherited.files).length===32&&inheritedFailures.length===0,{count:Object.keys(inherited.files).length,failures:inheritedFailures});
const assets=JSON.parse(baseRead('qa/phase-13-independent/fixtures/phase11h-assets.json').toString('utf8'));
record('phase11h-asset-manifest-byte-frozen',Object.keys(assets.files).length===47&&sha(baseRead('qa/phase-13-independent/fixtures/phase11h-assets.json'))===inherited.files['qa/phase-13-independent/fixtures/phase11h-assets.json'],{count:Object.keys(assets.files).length});
record('runner-isolated-and-fail-closed',text('qa/phase-16-independent/realm.js').includes('allowDestructive:true')&&text('qa/phase-16-independent/realm.js').includes('isolatedStorage:true')&&text('qa/phase-16-independent/realm.js').includes('phase16-contract-unavailable')&&text('qa/phase-16-independent/realm.js').includes('if(!qa){'));
record('runner-actual-dom-contract',['document.querySelector','document.querySelectorAll','getBoundingClientRect','getComputedStyle','document.activeElement','KeyboardEvent','scrollWidth'].every(value=>text('qa/phase-16-independent/realm.js').includes(value)));
record('runner-required-behavior-coverage',['story-discovers-capability-opens-without-backdating','deterministic-customer-bank-and-ordinals','offline-midnight-dst-epoch-equivalent','preparation-commit-resumes-exactly','serve-creates-immutable-result-zero-payment','imperfect-result-smaller-nonnegative','claim-atomic-global-local-metrics-lineage','two-client-${kind}-one-winner','named-visitor-queues-original-hook-after-claim-once','tutorial-one-safe-auto-presentation','actual-dom-focus-keyboard-escape','passive-buildings-gold-oaths-family-preserved'].every(id=>text('qa/phase-16-independent/realm.js').includes(id)));
for(const path of ['verify.mjs','runner.js','realm.js']){const run=spawnSync(NODE,['--check',`qa/phase-16-independent/${path}`],{cwd:ROOT,encoding:'utf8'});record(`syntax-${path}`,run.status===0,run.stderr.trim())}

if(PACKAGE_ONLY){const artifact=baseRead('index.html');record('exact-frozen-base-artifact',sha(artifact)===inherited.files['index.html']&&artifact.length===1126624,{sha256:sha(artifact),byteLength:artifact.length});record('base-has-phase12-phase13-no-phase16',artifact.includes(Buffer.from('__EVERSTEAD_PHASE_12_QA__'))&&artifact.includes(Buffer.from('__EVERSTEAD_PHASE_13_QA__'))&&!artifact.includes(Buffer.from('__EVERSTEAD_PHASE_16_QA__')))}else{
  const paths=productionSources(),combined=paths.map(path=>text(path)).join('\n'),versions=[...combined.matchAll(/CURRENT_SCHEMA_VERSION\s*=\s*(\d+)/g)].map(match=>Number(match[1]));
  record('candidate-phase16-bridge-contract',combined.includes('__EVERSTEAD_PHASE_16_QA__')&&combined.includes(fixtures.bridgeVersion)&&combined.includes('allowDestructive')&&combined.includes('isolatedStorage')&&combined.includes('NATIVE_STORAGE'),paths);
  record('candidate-restaurant-config-identities',combined.includes(fixtures.configId)&&combined.includes(fixtures.definitionSetId)&&[fixtures.facilityId,fixtures.physicalMapAnchor,...fixtures.customerIds,...fixtures.preferenceIds,...fixtures.recipeIds,...fixtures.stationIds].every(id=>combined.includes(id)));
  record('candidate-restaurant-dom-contract',combined.includes('data-phase16-restaurant-sheet')&&combined.includes('data-phase16-customer-id')&&combined.includes('data-phase16-preference')&&combined.includes('data-phase16-recipe-id')&&combined.includes('data-phase16-station-id')&&combined.includes('data-phase16-prepare')&&combined.includes('data-phase16-serve')&&combined.includes('data-phase16-claim'));
  record('candidate-customer-bank-contract',combined.includes('unlockedAt')&&combined.includes('cursorAt')&&combined.includes('bankCapacity')&&combined.includes('carryMs')&&combined.includes('ordinal')&&combined.includes('preferenceId')&&combined.includes('expiresAt'));
  record('candidate-service-finalizer-contract',combined.includes('stockIdentity')&&combined.includes('preparing')&&combined.includes('claim-ready')&&combined.includes('immutableFinalizer')&&combined.includes(fixtures.activityId)&&combined.includes(fixtures.archiveConfigId));
  record('candidate-economy-policy-gate',fixtures.economyRequiredPaths.every(path=>combined.includes(path.split('.').at(-1)))&&combined.includes('activeProfitTargetShare')&&combined.includes('headroomYears')&&combined.includes('productionEnabled'));
  record('candidate-visitor-tutorial-cast-contract',combined.includes(fixtures.namedVisitor.chronicleHookId)&&fixtures.tutorialIds.every(id=>combined.includes(id))&&fixtures.actorIds.every(id=>combined.includes(id))&&combined.includes('lockedFellowsExcluded'));
  record('candidate-phase16-inherited-seam-attestation',combined.includes(fixtures.bridgeVersion)&&combined.includes(fixtures.phase15BridgeVersion)&&combined.includes(fixtures.phase12ActivationId)&&combined.includes('claim-archive.phase-15.v1'));
  record('candidate-schema-remains-12',Math.max(0,...versions)===12,versions);
}

const owned=path=>['docs/PHASE_16_INDEPENDENT_QA_CONTRACT.md','docs/PHASE_16_INDEPENDENT_QA_RESULT.md'].includes(path)||path.startsWith('qa/phase-16-independent/'),packageCommits=git(['log','--format=%H',`${BASE}..HEAD`,'--','docs/PHASE_16_INDEPENDENT_QA_CONTRACT.md','docs/PHASE_16_INDEPENDENT_QA_RESULT.md','qa/phase-16-independent']).trim().split('\n').filter(Boolean),ownershipViolations=[];
for(const commit of packageCommits){for(const path of git(['diff-tree','--root','--no-commit-id','--name-only','-r',commit]).trim().split('\n').filter(Boolean))if(!owned(path))ownershipViolations.push({commit,path})}
record('committed-qa-paths-owned',packageCommits.length>=1&&ownershipViolations.length===0,{packageCommits,violations:ownershipViolations});
const passed=rows.filter(row=>row.pass).length,failed=rows.length-passed,result={phase:'16-independent-restaurant',mode:PACKAGE_ONLY?'PACKAGE_ONLY':'CANDIDATE',status:failed?'FAIL':'PASS',baseCommit:BASE,total:rows.length,passed,failed,rows};console.log(JSON.stringify(result,null,2));if(failed)process.exitCode=1;
