import {readFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';

const ROOT=resolve(fileURLToPath(new URL('../../',import.meta.url))),PACKAGE_ONLY=process.argv.includes('--package-only'),rows=[];
const rel=path=>resolve(ROOT,path),text=path=>readFileSync(rel(path),'utf8'),json=path=>JSON.parse(text(path)),sha=path=>createHash('sha256').update(readFileSync(rel(path))).digest('hex'),shaText=value=>createHash('sha256').update(value).digest('hex'),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail});
const contract=json('qa/phase-24c2c-zero-activation/contract.json'),runner=text('qa/phase-24c2c-zero-activation/runner.js'),realm=text('qa/phase-24c2c-zero-activation/realm.js'),page=text('qa/phase-24c2c-zero-activation/index.html'),readme=text('qa/phase-24c2c-zero-activation/README.md'),result=text('docs/PHASE_24C2C_ZERO_INTEGRATION_QA_RESULT.md');
const EXPECTED={
  acceptedCoordinator:'73737ab74efd4e33b2a5fdae1d1c76a6e88b4e51b1bb43453e034f47d5d5c7fb',
  projectedPre24C:'6109805093ee78f075257526b4822cf86c9ca22dbd2a2a05ab3ef7b0bcb8c5f3',
  candidateIndex:'7073db350bddfdea932bf89d900a449346c2e3e6b2b636bf55a1e8f8f3aa3356',
  activationSemantic:'556641d1997d7cee1734e79da510141154f00be97a21138f08bc088de2e68aaf',
  harness:{
    'qa/phase-24c2c-zero-activation/runner.js':'33ab326ec351c98cfc1c14d15fdab836f2dd1ae745633c75da25160bc92737d9',
    'qa/phase-24c2c-zero-activation/realm.js':'556375a1f922783fde67782ad0b8f1268f188f7812fa7586e2163f2982646147',
    'qa/phase-24c2c-zero-activation/index.html':'432f70887115b66867ecae0ddb428b9e9b61122d737ca4df95bdaf601a7fa60b',
    'qa/phase-24c2c-zero-activation/realm.html':'44023a9347091771b8e4cb3a951cde9b6a9ada06c71773d6e1c23db0b07db70d'
  },
  preGates:{
    'qa/phase-24c2c-activation-authority/checksums.sha256':'24c619d2c1993e505a060a647cfdb6b4d8b0f5cd760b3d6d072f23e62e596baa',
    'qa/phase-24c-foundation/README.md':'1c375402f54e06b1f55228c2914dee189abf97c89b00592722ca35546779e120',
    'qa/phase-24c-foundation/contract.json':'c75c8a80a833a8a39e8a27ef145c8d3a1f1eedf1416f5db4ea762c69ad376114',
    'qa/phase-24c-foundation/verify.mjs':'3f78a6f86dda816814ce13da8b75821f0b0d795c828f03c58540d9204c41a468',
    'docs/PHASE_24C_INACTIVE_FOUNDATION_CONTRACT.md':'eb9a4f5d6c1c5910b3b977549f32f0e0063aab116c3d474e5eba0981a0348555',
    'docs/PHASE_24C_INACTIVE_FOUNDATION_RESULT.md':'a94bda7e4efc911ff772104efc184ea6c3e612290c42cea60ad199c7cc0ed346',
    'qa/phase-24c-independent/README.md':'9fd648ea73f2d25518c9bb363e7fe609e45a768162d0febb409732630c649de0',
    'qa/phase-24c-independent/contract.json':'6817661bfa6e44ef955b88617f59bc8654da7a26f73df6f334decad473eba35c',
    'qa/phase-24c-independent/verify.mjs':'ccabf873bac7c63bba9a4408227a1db0626492f5406cb5f61b08a6f38a2359c4',
    'docs/PHASE_24C_INDEPENDENT_QA_CONTRACT.md':'5de2f113b82032a9f18e811d35330ff326f167fa619bd09ddb88fa7c49541da8',
    'docs/PHASE_24C_INDEPENDENT_QA_RESULT.md':'d1e66badf6b6f007b44480d8c0a8102a9dce646a6c99679b9e4d40a67c087084'
  },
  sources:{
    'src/phase18-19-runtime.js':'26686c97cc7c2a617224b8a287ab92933222e137c53bc309dedad6102d68df2e',
    'src/phase23-companion-catalog.js':'48da84995d57d78ab01899b4f1840763b2539b4c5605da68ccc309889d0c718f',
    'src/phase23-companion-runtime.js':'fd1455fef5cb5632fc53b055c935848e6b6f13f40175518520f0f4aa548dde40',
    'src/phase24-scaling-authority.js':'819fd4e308a98c699ac01a0c3df780eab11e777d933038b118850679d0f39d5c',
    'src/phase24c-zero-activation-authority.js':'88ba60568041b764794b74dec6b926e34890354d6c13175491f5f87c4c92a03f',
    'src/phase24c-durable-definitions.js':'101377044214d87478475ba9064c4342b9ce8fcbe62e5d4e1743a08f31767f70',
    'src/phase24c-durable-foundation.js':'fbf9c7865977b195786c15ffe6b6725649b5c6552c8f46b831421083831e4479'
  },
  loaders:['src/phase24c-zero-activation-authority.js','src/phase24c-durable-definitions.js','src/phase24c-durable-foundation.js'],
  productAllowedHostnames:['localhost','127.0.0.1','[::1]','::1'],
  denialLoopbackHostname:'127.0.0.1.nip.io',
  qaProbeGlobal:'__P24C2C_HOST_BOUNDARY__',
  slots:['active','rawBackup','preV2','preV3','preV4','preV5','preV6','preV7','preV8','preV9','preV10','preV11','preV12','preV13','preV14'],
  controls:['ordinaryStaging','journal','rollback'],
  reads:['snapshot','validate','saveSnapshot','installationIdentity','authority','zeroEvidence','outputAnchors','exportSave','diagnostics'],
  destructive:['resetDirectFresh','resetSafe','reload','migrateSchema13','migrateSchema12','recoverInterrupted','roundTripExportImport','roundTripRollback','advancePendingOffline','exportBlockedDiagnostics','probeInvalid','probeRefusal','probeOpeningRefusal','probeSuccess'],
  interruptions:['migration-before-stage','migration-after-stage','migration-after-active','ordinary-staging-after-active','safe-reset-committed-stage-after-forget','schema13-ordinary-staging-pending','schema13-ordinary-staging-committed','historical-schema11-staging-pending','safe-reset-after-journal','safe-reset-after-rollback','safe-reset-after-active','import-after-journal','import-after-rollback','import-after-active','rollback-after-journal','rollback-after-active','forensic-reset-future-schema','forensic-reset-invalid-schema13','forensic-reset-malformed-active','forensic-reset-missing-active'],
  invalid:['schema13-staging-foreign-prev14','historical-schema11-staging-malformed-envelope','historical-schema11-staging-foreign-provenance','historical-staging-future-schema','tampered-immediate-target','crossclass-fresh-safe-reset','crossclass-safe-reset-migrated','safe-reset-rollback-older-than-reset','foreign-journal-between-boot-read-adoption','foreign-journal-gameplay-commit','forged-validated-previous-lineage-invalid','forged-validated-previous-nonzero','forged-forensic-restorable-lineage-invalid','forged-forensic-restorable-nonzero','forged-sameclass-journal-lineage-invalid','forged-sameclass-journal-nonzero','foreign-invalid-rollback-before-ordinary-commit','safe-reset-committed-stage-older-previous','forged-null-reset-semantic-source','schema14-safe-reset-staging-pending-without-journal','schema14-safe-reset-staging-committed-without-journal'],
  legacyInvalid:{'historical-schema11-staging-malformed-envelope':{stageSchemaVersion:null,dispatchEntered:false,refusalCode:'staging-provenance'},'historical-schema11-staging-foreign-provenance':{stageSchemaVersion:11,dispatchEntered:true,refusalCode:'staging-provenance'},'historical-staging-future-schema':{stageSchemaVersion:99,dispatchEntered:false,refusalCode:'staging-provenance'}},
  forged:['forged-validated-previous-lineage-invalid','forged-validated-previous-nonzero','forged-forensic-restorable-lineage-invalid','forged-forensic-restorable-nonzero','forged-sameclass-journal-lineage-invalid','forged-sameclass-journal-nonzero'],
  boundaries:['foreign-journal-before-current-adopt','foreign-journal-before-committed-stage-cleanup','foreign-journal-before-inherited-active-write','foreign-journal-before-ordinary-staging-write','foreign-journal-before-ordinary-staging-cleanup'],
  unjournaledSafeReset:['schema14-safe-reset-staging-pending-without-journal','schema14-safe-reset-staging-committed-without-journal']
};

record('contract-exact-id-phase-schema-status',contract.contractId==='phase-24c2c-zero-integration-independent-qa.v1'&&contract.phase==='24C-2C'&&contract.status==='accepted-zero-only-integration-gate'&&contract.schemaVersion===14&&contract.predecessorSchemaVersion===13);
record('contract-hardcoded-accepted-index-pins',contract.baseline.acceptedCoordinatorIndexSha256===EXPECTED.acceptedCoordinator&&contract.baseline.projectedPre24CIndexSha256===EXPECTED.projectedPre24C);
record('contract-final-candidate-activation-semantic-and-behavior-harness-pins',contract.baseline.candidateIndexSha256===EXPECTED.candidateIndex&&contract.baseline.activationSemanticSha256===EXPECTED.activationSemantic&&same(contract.baseline.acceptedHarnessSha256,EXPECTED.harness)&&Object.entries(EXPECTED.harness).every(([path,expected])=>existsSync(rel(path))&&sha(path)===expected));
record('contract-reopened-v2-and-independent-pre-gates-are-current-byte-pinned-without-rewriting-historical-manifests',same(contract.baseline.acceptedReopenedPreGateSha256,EXPECTED.preGates)&&Object.entries(EXPECTED.preGates).every(([path,expected])=>existsSync(rel(path))&&sha(path)===expected)&&!Object.hasOwn(EXPECTED.preGates,'qa/phase-24c-foundation/checksums.sha256')&&!Object.hasOwn(EXPECTED.preGates,'qa/phase-24c-independent/checksums.sha256'));
record('contract-exact-loader-order',same(contract.loader.exactOrder,EXPECTED.loaders)&&contract.loader.beginMarker==='<!-- Phase 24C-2C zero-only authority load BEGIN -->'&&contract.loader.endMarker==='<!-- Phase 24C-2C zero-only authority load END -->'&&contract.loader.mustPrecedeInlineBoot===true);
record('contract-nonallowlisted-loopback-denial-host-boundary',same(contract.browserHostBoundary,{productAllowedHostnames:EXPECTED.productAllowedHostnames,denialLoopbackHostname:EXPECTED.denialLoopbackHostname,qaProbeGlobal:EXPECTED.qaProbeGlobal})&&!contract.browserHostBoundary.productAllowedHostnames.includes(contract.browserHostBoundary.denialLoopbackHostname));
record('contract-exact-schema14-authority-identities',contract.authority.activationGlobal==='EVERSTEAD_PHASE24C_ZERO_ACTIVATION_AUTHORITY'&&contract.authority.definitionsGlobal==='EVERSTEAD_PHASE24C_DEFINITIONS'&&contract.authority.foundationGlobal==='EVERSTEAD_PHASE24C_FOUNDATION'&&contract.authority.activationId==='phase-24c2c-zero-activation-authority.v1'&&contract.authority.configId==='phase-24c-durable-foundation.v1'&&contract.authority.foundationVersion===2&&contract.authority.predecessorValidatorId==='validator.schema-13.phase-24c-production.v1'&&contract.authority.directOriginValidatorId==='validator.direct-schema-14-origin.phase-24c-production.v1'&&contract.authority.migrationId==='migration.schema-13-to-14.phase-24c-foundation.v2');
record('contract-exact-three-lineages',same(contract.authority.allowedLineages,['direct-schema-14','safe-reset-schema-14','schema-13-to-14-migration']));
record('contract-exact-15-permanent-slot-names',same(contract.storage.slotNames,EXPECTED.slots)&&new Set(contract.storage.slotNames).size===15);
record('contract-exact-18-snapshot-topology',same(contract.storage.snapshotControlNames,EXPECTED.controls)&&contract.storage.snapshotCount===18&&new Set([...contract.storage.slotNames,...contract.storage.snapshotControlNames]).size===18);
record('contract-exact-storage-keys',contract.storage.namespace==='oathforge_new_world_proto_v01'&&contract.storage.activeKey===contract.storage.namespace&&contract.storage.stagingKey===contract.storage.namespace+'__staging'&&contract.storage.preV14Key===contract.storage.namespace+'__raw_backup_v13'&&contract.storage.journalKey===contract.storage.namespace+'__save_tool_journal_v1'&&contract.storage.rollbackKey===contract.storage.namespace+'__previous_installation_v1');
record('contract-save-v3-reset-v9',contract.storage.saveFormatVersion===3&&contract.storage.safeResetMarkerVersion===9);
record('contract-exact-bounded-bridge',contract.bridge.global==='__EVERSTEAD_PHASE_24C2C_QA__'&&contract.bridge.version==='phase-24c2c-zero-integration-qa-v1'&&same(contract.bridge.readMethods,EXPECTED.reads)&&same(contract.bridge.destructiveMethods,EXPECTED.destructive)&&same(contract.bridge.interruptionKinds,EXPECTED.interruptions)&&same(contract.bridge.invalidKinds,EXPECTED.invalid)&&same(contract.bridge.legacyStagingRefusalKinds,EXPECTED.legacyInvalid)&&same(contract.bridge.forgedInvalidKinds,EXPECTED.forged)&&same(contract.bridge.journalBoundaryKinds,EXPECTED.boundaries)&&same(contract.bridge.unjournaledSafeResetStagingKinds,EXPECTED.unjournaledSafeReset)&&same(contract.bridge.blockedDiagnosticsKinds,['future-schema','malformed-active'])&&contract.bridge.blockedDiagnosticsConflictKind==='interleaved-slot-change');
record('contract-exact-blocked-diagnostics-format-and-18-values',contract.blockedDiagnostics.format==='everstead-recovery-diagnostics'&&contract.blockedDiagnostics.formatVersion===3&&contract.blockedDiagnostics.integrityAlgorithm==='SHA-256'&&same(contract.blockedDiagnostics.snapshotKeys,[...EXPECTED.slots,...EXPECTED.controls])&&new Set(contract.blockedDiagnostics.snapshotKeys).size===18);
record('contract-exact-zero-output',same(contract.zero.activeReleaseIds,[])&&same(contract.zero.claimedDefinitionIds,[])&&same(contract.zero.recentGrantReceipts,[])&&same(contract.zero.totals,{powerBps:0,earningsBps:0,expBps:0,facilityBpsByFacilityId:{}})&&contract.zero.rankCapacityThrough===30&&contract.zero.rankReleasedThrough===5&&contract.zero.formulaReadsAllowed===false&&contract.zero.claimReadinessAllowed===false&&contract.zero.rewardApplicationsAllowed===false);
record('contract-exact-fresh-anchor',same(contract.anchors.fresh,{fellowCombatPower:35565,fellowEconomyPower:35150,companionActualPower:2200,companionMigrationFloorPower:0,companionEffectivePower:2200,fellowEconomyBps:390,companionEconomyBps:80,goldPerHour:27320.8092192}));
record('contract-exact-schema12-migrated-anchor',same(contract.anchors.freshlyMigratedSchema12,{fellowCombatPower:36366,trueFreshFellowCombatPower:35565,migrationProtectionDelta:801,companionActualPower:2200,protectedFellowIds:['cael','orin']}));
record('contract-exact-established-anchor',same(contract.anchors.migratedEstablished,{fellowCombatPower:36645,fellowEconomyPower:35150,companionActualPower:2272,companionMigrationFloorPower:2892,companionEffectivePower:2892,fellowEconomyBps:390,companionEconomyBps:83,goldPerHour:27328.94041242}));
record('contract-exact-pending-offline-anchor',same(contract.anchors.pendingOffline,{fellowCombatPower:1054194,fellowEconomyPower:1039700,companionActualPower:4329,companionMigrationFloorPower:23980,companionEffectivePower:23980,fellowEconomyBps:1368,companionEconomyBps:147,goldPerHour:30091.179009135998}));
record('contract-exact-bounded-ordered-realm-chunk-transport',same(contract.transport,{harnessCacheVersion:20,passDetailMaxCharacters:0,commandMaxBytes:196608,realmChunkMaxBytes:524288,realmChunkTargetBytes:393216,maxRealmChunks:8,finalResultMaxBytes:2097152,realmChunkEncoding:'bounded-attested-chunked-v1',orderedManifest:'row-id-and-evidence-correlation-digest-v1'}));
record('contract-six-required-authorized-realms',contract.authorizedRealms.length===6&&same(contract.authorizedRealms.map(item=>item.scenario),['direct-fresh','safe-reset','schema13-migration','schema12-chain','pending-offline','recovery'])&&contract.authorizedRealms.some(item=>item.width===320&&item.height===568)&&contract.authorizedRealms.some(item=>item.width===390&&item.height===844&&item.copyScale===1.3&&item.reducedMotion===true)&&contract.authorizedRealms.some(item=>item.width===1024&&item.height===768));
record('contract-six-denials-cover-every-boundary',contract.denialRealms.length===6&&contract.denialRealms.some(item=>!item.query)&&contract.denialRealms.some(item=>!item.allowDestructive)&&contract.denialRealms.some(item=>!item.isolatedStorage)&&contract.denialRealms.some(item=>!item.supplyStorage)&&contract.denialRealms.some(item=>item.query==='qa=1&qa=1')&&contract.denialRealms.some(item=>item.hostMode==='nonloopback'));
for(const [path,expected] of Object.entries(EXPECTED.sources))record(`accepted-source-byte-frozen-${path.replaceAll('/','-')}`,existsSync(rel(path))&&sha(path)===expected,existsSync(rel(path))?sha(path):'missing');
record('contract-source-pins-match-hardcoded-baselines',Object.entries(EXPECTED.sources).every(([path,expected])=>contract.baseline.acceptedSourceSha256[path]===expected));
record('contract-accepted-browser-evidence-exact',same(contract.acceptedBrowserEvidence,{focused:{passed:185,total:185,failed:0,blankFatal:true,warningErrorConsoleCount:0},denial:{passed:10,total:10,failed:0,blankFatal:true,warningErrorConsoleCount:0},fullRuns:[{passed:391,total:391,failed:0,blankFatal:true,warningErrorConsoleCount:0},{passed:391,total:391,failed:0,blankFatal:true,warningErrorConsoleCount:0}]}));

for(const file of ['runner.js','realm.js','verify.mjs']){const checked=spawnSync(process.execPath,['--check',`qa/phase-24c2c-zero-activation/${file}`],{cwd:ROOT,encoding:'utf8'});record(`syntax-${file}`,checked.status===0,checked.stderr.trim())}
record('harness-final-cache-version-is-synchronized',page.includes(`runner.js?v=${contract.transport.harnessCacheVersion}`)&&text('qa/phase-24c2c-zero-activation/realm.html').includes(`realm.js?v=${contract.transport.harnessCacheVersion}`)&&!page.includes('runner.js?v=9')&&!text('qa/phase-24c2c-zero-activation/realm.html').includes('realm.js?v=9'));
record('harness-independent-no-writer-verifier-import',!/(?:import|require)\s*\(?\s*['"][^'"]*(?:phase-24c2c-activation-authority|phase-24c2b-coordinator|verify\.mjs)/.test(runner+realm+text('qa/phase-24c2c-zero-activation/verify.mjs')));
record('realm-loads-real-production-candidate',realm.includes("fetch('../../index.html'")&&realm.includes("source.indexOf('<script')")&&realm.includes('document.write(source)')&&!/fake(?:Coordinator|Foundation|Schema|Save)/i.test(realm));
record('realm-installs-distinct-memory-adapter-before-candidate',realm.includes('__EVERSTEAD_RUNTIME__')&&realm.includes('memoryStorage')&&realm.includes("source.slice(0,insertion)+bootstrap")&&realm.includes('STORAGE_SOURCE')===false);
record('realm-instruments-and-restores-native-storage',realm.includes('nativePrior')&&realm.includes('restoreNative')&&realm.includes('__P24C2C_RESTORE_NATIVE__'));
record('realm-shared-adapter-dispatches-real-storage-events',realm.includes('__P24C2C_SHARED_STORES__')&&realm.includes("new peer.StorageEvent('storage'")&&realm.includes('storageArea:peer.localStorage')&&realm.includes('store.clients'));
record('runner-two-real-shared-clients',runner.includes("retainedClient(contract,{id:'shared-a'")&&runner.includes("retainedClient(contract,{id:'shared-b'")&&runner.includes('two-client-second-load-is-zero-write-byte-stable')&&runner.includes('two-client-storage-event-marks-other-client-stale')&&runner.includes('two-client-stale-loser-refuses-zero-write')&&runner.includes('two-client-foreign-journal-between-read-adoption-peer-interleaves')&&runner.includes('foreignJournalClientId===peerId')&&runner.includes('two-client-foreign-journal-between-read-adoption-fails-closed')&&runner.includes('two-client-gameplay-commit-refuses-foreign-journal-zero-active-staging-write')&&runner.includes('__P24C2C_COMMAND_READY__')&&realm.includes('listenerInstalled:true'));
record('runner-two-real-clients-interleave-five-exact-inner-journal-boundaries',runner.includes('sharedExactBoundaryInterleaving')&&runner.includes('fault-fired-at-exact-inner-boundary')&&runner.includes('refuses-current-adoption-preserves-journal')&&runner.includes('refuses-committed-stage-cleanup-preserves-bytes')&&runner.includes('refuses-inherited-active-write-after-validation')&&runner.includes('refuses-ordinary-staging-before-write')&&runner.includes('refuses-ordinary-staging-cleanup-after-active')&&realm.includes("'phase24c2c-current-adopt'")&&realm.includes("'after-terminal-snapshot'")&&realm.includes("'phase24c2c-committed-stage-cleanup'")&&realm.includes("'phase24c2c-inherited-active-write'")&&realm.includes("'after-staging-validation'")&&realm.includes("'phase24c2c-ordinary-staging-write'")&&realm.includes("'phase24c2c-ordinary-staging-cleanup'")&&realm.includes("'before-final-preflight'"));
record('runner-deep-invalid-authority-cases-use-case-specific-evidence',runner.includes('sharedDeepInvalidEvidence')&&contract.bridge.deepInvalidEvidenceKinds.length===5&&runner.includes('canonical-replay-authority')&&runner.includes('crossclass-fresh-safe-reset-authority')&&runner.includes('stagingAuthorityRejected===true')&&runner.includes("timingErrorCode==='schema-14-safe-reset-previous'")&&runner.includes('valid-previous-rejected-only-for-time')&&runner.includes('actually-interleaved-after-boot-read'));
record('runner-safe-reset-active-bad-rollback-two-client-preflight',runner.includes('sharedSafeResetRollbackPreflight')&&contract.bridge.rollbackBoundaryKind==='foreign-invalid-rollback-before-ordinary-commit'&&runner.includes('inserted-without-event')&&runner.includes('safe-reset-previous-and-refuses')&&realm.includes("'phase24c2c-ordinary-commit'")&&realm.includes("'before-final-preflight'"));
record('runner-nonloopback-denial-realm-uses-contract-host-and-preserves-url-components',runner.includes("hostMode!=='nonloopback'")&&runner.includes('BROWSER_HOST_BOUNDARY?.denialLoopbackHostname')&&runner.includes('BROWSER_HOST_BOUNDARY?.productAllowedHostnames')&&runner.includes('allowed.includes(hostname)')&&runner.includes('`${location.protocol}//${hostname}${location.port?`:${location.port}`')&&runner.includes("location.pathname.replace(/[^/]*$/,'')")&&!runner.includes('//0.0.0.0'));
record('realm-in-memory-host-boundary-instrumentation-is-single-anchor-fail-closed-and-qa-only',realm.includes("const hostBoundaryAnchor='const QA_BRIDGE_ALLOWED=qaBridgeAllowed();'")&&realm.includes('hostBoundaryAnchorCount=source.split(hostBoundaryAnchor).length-1')&&realm.includes('if(hostBoundaryAnchorCount!==1)throw new Error')&&realm.includes("hostBoundaryProbeGlobal!=='__P24C2C_HOST_BOUNDARY__'")&&realm.includes('source.includes(hostBoundaryProbeGlobal)')&&realm.includes('source=source.replace(hostBoundaryAnchor,hostBoundaryInstrumentation)')&&realm.includes('Object.defineProperty(window,${JSON.stringify(hostBoundaryProbeGlobal)}')&&realm.includes('value:Object.freeze({literal:QA_BRIDGE_ALLOWED,recomputed:qaBridgeAllowed(),hostname:location.hostname,instrumentationApplied:true})')&&realm.includes('configurable:false,enumerable:false,writable:false'));
record('realm-nonloopback-denial-requires-exact-frozen-probe-host-decisions-and-zero-boundary-writes',realm.includes('denial-nonallowlisted-loopback-hostname-exact-and-zero-boundary-writes')&&realm.includes('Object.getOwnPropertyDescriptor(window,hostBoundary.qaProbeGlobal)')&&realm.includes('facts.instrumentationApplied===true')&&realm.includes('facts.probeDescriptorPresent===true')&&realm.includes('facts.probeEnumerable===false')&&realm.includes('facts.probeConfigurable===false')&&realm.includes('facts.probeWritable===false')&&realm.includes('facts.probeFrozen===true')&&realm.includes('facts.probeHostname===location.hostname')&&realm.includes('facts.qaBridgeAllowedLiteral===false')&&realm.includes('facts.qaBridgeAllowedRecomputed===false')&&realm.includes('facts.bridgeDescriptorPresent===false')&&realm.includes('facts.bridgePresent===false')&&realm.includes('facts.boundaryWriteDelta===0'));
record('realm-transport-id-is-exact-parent-nonce-derived-with-no-secure-context-uuid-dependency',realm.includes('transportId=`realm-${config.nonce}`')&&realm.match(/transportId=`realm-\$\{config\.nonce\}`/g)?.length>=2&&!realm.includes('crypto.randomUUID'));
record('realm-scenario-failure-uses-one-shot-minimal-nonrecursive-chunk-publisher',realm.includes('let fatalSent=false')&&realm.includes('const sendFatal=error=>{if(fatalSent)return;fatalSent=true')&&realm.includes("failureRow={id:'realm-fatal'")&&realm.includes('chunkIndex:0,chunkCount:1,rowStart:0,rowCount:1,final:true')&&realm.includes('exactBytes!==message.transport.bytes||exactBytes>MAX_REALM_TRANSPORT_BYTES')&&realm.includes('runScenario()).catch(error=>sendFatal(error))')&&!realm.includes("add('realm-fatal',false,error.stack||error.message);send()"));
record('runner-focus-can-select-one-denial-realm-without-expanding-acceptance',runner.includes("denial=contract.denialRealms.find(item=>item.id===FOCUS_REALM_ID)")&&runner.includes("focused=denial?{...viewport,width:390,height:844,scenario:'denial'}:viewport")&&runner.includes("kind=denial?'denial':'authorized'")&&runner.includes("render('FOCUSED',rows)")&&runner.includes("prior?.mode!=='CANDIDATE'"));
record('realm-consumes-only-exact-bounded-surface',EXPECTED.reads.every(name=>realm.includes(name))&&EXPECTED.destructive.every(name=>realm.includes(name))&&![...EXPECTED.reads,...EXPECTED.destructive].some(name=>/(genericMutator|refusalToken|refusalMarker|writeRaw|setStorage|removeStorage)/.test(name)));
record('realm-tests-direct-fresh-first-boot-and-reboot',realm.includes('actual-candidate-empty-storage-boot-before-any-qa-reset')&&realm.includes('direct-fresh-first-boot-is-real-schema14-revision1')&&realm.includes('direct-fresh-first-boot-used-one-exact-terminal-transaction')&&realm.includes("expectedFirstTrace=[{op:'set',key:f.storage.stagingKey},{op:'set',key:f.storage.activeKey},{op:'remove',key:f.storage.stagingKey}]")&&realm.includes("initialRoot?.migrations?.lineageKind==='direct-schema-14'")&&realm.includes('direct-fresh-exact-origin-metadata')&&realm.includes('direct-fresh-no-pre-v14-checkpoint')&&realm.includes('direct-fresh-reload-byte-stable-zero-write'));
record('realm-tests-safe-reset-from-migrated-complete-previous-save',realm.includes('safe-reset-precondition-is-migrated-with-pre-v14-and-raw-backup')&&realm.includes('previousSaveRawBackupOccupied')&&realm.includes('safe-reset-new-save-id-revision1-and-v9-marker')&&realm.includes('safe-reset-complete-previous-save-bound')&&realm.includes('safe-reset-previous-created-at-equals-reset-at')&&realm.includes('safe-reset-retains-protected-pre-v14-and-raw-backup-byte-exact'));
record('realm-tests-real-schema13-migration',realm.includes("migrateSchema13','fresh'")&&realm.includes("migrateSchema13','established'")&&realm.includes('schema13-fresh-pre-v14-exact-checkpoint')&&realm.includes('schema13-fresh-one-real-receipt-revision-increment'));
record('realm-tests-real-schema12-chain',realm.includes("migrateSchema12','fresh'")&&realm.includes("migrateSchema12','established'")&&realm.includes('schema12-chain-authenticates-12-to-13-then-13-to-14'));
record('realm-tests-legacy-scope-restored-before-current-phase23-boot',realm.includes('schema13-established-current-phase23-definitions-and-runtime-restored-before-boot')&&realm.includes('schema12-fresh-current-phase23-definitions-and-runtime-restored-before-boot')&&realm.includes('schema12-established-current-phase23-definitions-and-runtime-restored-before-boot')&&realm.match(/currentPhase23DefinitionsRestoredBeforeBoot===true/g)?.length>=3&&realm.match(/currentPhase23RuntimeRestoredBeforeBoot===true/g)?.length>=3);
record('realm-tests-ordinary-direct-schema12-installation-retains-current-foundations-and-phase23-ensure-is-zero-write-noop',realm.includes('schema13-established-current-schema12-foundations-survive-direct-install-and-phase23-ensure-noop')&&realm.includes('schema12FoundationsCompleteBeforeMigration===true')&&realm.includes('currentPhase23FoundationsEnsureNoop===true')&&realm.includes('directCapturedSchema12Installation===true')&&realm.includes('legacyResetTargetUsed===false'));
record('realm-tests-dedicated-retained-backup-safe-reset-fixture-exact-binding-bounded-validated-activation-direct-adoption-and-foundation-noop',realm.includes("migrateSchema13','retained-backup'")&&realm.includes('safe-reset-precondition-dedicated-retained-backup-is-exact-bound-revalidated-and-foundation-complete')&&realm.includes('retainedBackupFixture===true')&&realm.includes('retainedBackupRawExactSource===true')&&realm.includes('retainedBackupMarkerBoundSource===true')&&realm.includes('retainedBackupRevalidatedAfterFoundations===true')&&realm.includes('inMemoryFoundationActivation===true')&&realm.includes('activationStorageWrites===0')&&realm.includes('authenticActivationValidation===true')&&realm.includes('finalRetainedInstallationAuthenticated===true')&&realm.includes('finalRetainedAdoptionIdentityExact===true')&&realm.includes('inMemoryCommitCoordinatorRestored===true')&&realm.includes('finalRetainedAdoptionValidated===true')&&realm.includes('finalRetainedAdoptionStorageWrites===0')&&realm.includes('currentPhase23RuntimeRestoredBeforeBoot===true')&&realm.includes('legacyResetTargetUsed===true'));
record('realm-tests-real-migrated-production-reload-path',realm.includes('schema12-migrated-production-reload-uses-real-load-path')&&realm.includes('schema12-migrated-production-reload-zero-write-byte-ui-stable')&&realm.includes('actualProductionLoadPath===true')&&realm.includes('usedPersistenceActionReload===true')&&realm.includes('phase23BootPending===false')&&realm.includes('phase23DeferredBootBlocked===false'));
record('realm-tests-all-interruptions',realm.includes('for(const kind of f.bridge.interruptionKinds)')&&EXPECTED.interruptions.every(kind=>JSON.stringify(contract).includes(kind))&&realm.includes('terminalControlsClean')&&realm.includes('foreignSlotsPreserved')&&Object.keys(contract.bridge.transactionInterruptionKinds||{}).length===12&&realm.includes('real-fault-exact-partial-18-slot-state')&&realm.includes('production-reboot-exact-terminal-direction-and-traces')&&realm.includes('partialSnapshotIdentity===expectedPartialIdentity')&&realm.includes('terminalInstallationIdentity==='));
record('realm-tests-schema13-and-historical-staging-recovery',EXPECTED.interruptions.includes('schema13-ordinary-staging-pending')&&EXPECTED.interruptions.includes('schema13-ordinary-staging-committed')&&EXPECTED.interruptions.includes('historical-schema11-staging-pending')&&EXPECTED.interruptions.includes('ordinary-staging-after-active')&&Object.keys(contract.bridge.legacyStagingRecoveryKinds||{}).length===3&&realm.includes('actual-raw-legacy-staging-through-captured-phase23')&&realm.includes('actualRawStagingFixture===true')&&realm.includes('capturedPhase23RecoveryUsed===true')&&realm.includes('normalizedByHelper===false')&&realm.includes('c2cLegacyStageGateCompatible===true')&&realm.includes('schema11SourceAuthority===true')&&realm.includes('schema11TargetAuthority===true')&&realm.includes('canonicalSchema11PendingStaging===true')&&realm.includes('seededLaterCheckpointsNull===true')&&realm.includes('preV12ExactRecoveredSchema11===true')&&realm.includes('unrelatedProtectedSlotsPreserved===true')&&realm.includes('historical-schema11-runtime-and-rosters-scoped-zero-write-restored-before-storage-and-bootstrap')&&realm.includes('schema11CurrentSchemaScoped')&&realm.includes('schema11ValidationScopedThroughEleven')&&realm.includes('schema11DefaultStateScopedThroughEleven')&&realm.includes('schema11SchemaScopedDefaultStateScopedThroughEleven')&&realm.includes('schema11LegacyCompanionCatalogScoped')&&realm.includes('schema11LegacyFellowCatalogScoped')&&realm.includes('schema11LegacyFamilyCatalogScoped')&&realm.includes('schema11ScopeStorageWrites===0')&&realm.includes('schema11CurrentSchemaRestoredBeforeStorageWrite')&&realm.includes('schema11CurrentSchemaRestoredBeforeBootstrap')&&realm.includes('schema11CurrentCatalogsRestoredBeforeStorageWrite')&&realm.includes('schema11CurrentCatalogsRestoredBeforeBootstrap')&&realm.includes('schema11CurrentCommitAuthorityRestoredBeforeStorageWrite')&&realm.includes('schema11CurrentCommitAuthorityRestoredBeforeBootstrap')&&realm.includes('schema11RuntimeRestoredBeforeStorageWrite')&&realm.includes('schema11RuntimeRestoredBeforeBootstrap'));
record('realm-tests-historical-schema11-exact-branch-only-recursion-dispatch-and-restoration',realm.includes('recovery-historical-schema11-staging-pending-exact-branch-only-recursion-dispatch-and-restoration')&&realm.includes('legacyStageDispatchSchemaVersion===11')&&realm.includes('legacyStageDispatchPrecondition===true')&&realm.includes('legacyStageBootstrapRestored===true')&&realm.includes('legacyStageSchemaRestored===true')&&realm.includes('legacyStageDispatchRestoredBeforeReread===true')&&realm.includes('capturedPhase23RecoveryUsed===true')&&realm.includes('c2cLegacyStageGateCompatible===true')&&realm.includes('same(facts.terminalSchemaPath,[11,12,13,14])'));
record('realm-tests-fixed-historical-staging-invalid-authority-cases-with-exact-bounded-facts',same(contract.bridge.legacyStagingRefusalKinds,EXPECTED.legacyInvalid)&&realm.includes('fixed-historical-staging-authority-and-zero-write-preservation')&&realm.includes('fixtureStageSchemaVersion===legacy.stageSchemaVersion')&&realm.includes('legacyDispatchEntered===legacy.dispatchEntered')&&realm.includes('expectedRefusalCode===legacy.refusalCode')&&realm.includes('actualRejectionCode===legacy.refusalCode')&&realm.includes('attemptWrites===0')&&realm.includes('attemptActiveBytesPreserved===true')&&realm.includes('attemptStagingBytesPreserved===true')&&realm.includes('attemptProtectedBytesPreserved===true')&&realm.includes('targetAdopted===false')&&realm.includes('cleanupPerformed===false')&&realm.includes('terminalValidationOk===true')&&realm.includes('bootstrapRestored===true')&&realm.includes('schemaRestored===true'));
record('realm-tests-safe-reset-committed-stage-missing-and-older-previous-context',EXPECTED.interruptions.includes('safe-reset-committed-stage-after-forget')&&EXPECTED.invalid.includes('safe-reset-committed-stage-older-previous')&&realm.includes('production-forget-allows-committed-adoption')&&realm.includes('safe-reset-bound-previous-refuses-committed-adoption')&&realm.includes("previousValidationRefusalCode==='schema-14-safe-reset-previous'")&&realm.includes("previousDisposition==='missing-after-production-forget'"));
record('realm-tests-ordinary-runtime-diagnostics-after-direct-and-migrated-boot',realm.includes("checkRuntimeDiagnostics('direct-fresh')")&&realm.includes("checkRuntimeDiagnostics('schema12-migrated')")&&realm.includes('runtimePersistenceDiagnosticsCalled===true')&&realm.includes('runtimePersistenceDiagnosticsCompatible===true')&&realm.includes('legacyExportCompatibility?.activeRawPresent===true')&&realm.includes('legacyExportCompatibility?.readErrorsObject===true'));
record('realm-tests-blocked-forensic-safe-reset-and-reboot',EXPECTED.interruptions.includes('forensic-reset-future-schema')&&EXPECTED.interruptions.includes('forensic-reset-invalid-schema13')&&EXPECTED.interruptions.includes('forensic-reset-malformed-active')&&EXPECTED.interruptions.includes('forensic-reset-missing-active')&&realm.includes('forensic-safe-reset-exact-source-marker-previous')&&realm.includes('forensic-complete-source-hash-and-raw-byte-binding')&&realm.includes('forensic-null-semantic-identity-v9-marker')&&realm.includes("previousRecordKind==='forensic'")&&realm.includes('previousRestorable===false')&&realm.includes('saveIdsMerged===false'));
record('realm-tests-forensic-null-pair-named-validator-and-forgery-refusal',EXPECTED.invalid.includes('forged-null-reset-semantic-source')&&realm.includes('forensic-null-pair-named-validator-approval')&&realm.includes('forged-null-reset-semantic-source-rejected-before-write'));
record('realm-tests-actual-blocked-diagnostics-exact-18-value-export',realm.includes("call('exportBlockedDiagnostics',kind)")&&realm.includes('actual-ui-action-zero-export-writes')&&realm.includes('exact-18-snapshot-values-no-omission')&&realm.includes('canonical-identity-and-digests')&&realm.includes('pre-v14-journal-rollback-occupied')&&realm.includes("payload?.format===f.blockedDiagnostics.format")&&realm.includes('saveIdsMerged===false'));
record('realm-tests-blocked-diagnostics-aggregate-read-conflict-refusal',realm.includes('blocked-diagnostics-interleaved-slot-change-fails-closed-no-hybrid-identity')&&realm.includes('aggregateVerifiedReadUsed===true')&&realm.includes('faultInterleavedBetweenAggregateReads===true')&&realm.includes('canonicalIdentityEmitted===false')&&realm.includes('hybridSnapshotEmitted===false'));
record('realm-tests-foreign-prev14-tamper-crossclass-old-rollback-and-journal-rejections',realm.includes('for(const kind of f.bridge.invalidKinds)')&&same(contract.bridge.invalidKinds,EXPECTED.invalid)&&EXPECTED.invalid.includes('safe-reset-rollback-older-than-reset')&&EXPECTED.invalid.includes('foreign-journal-between-boot-read-adoption')&&EXPECTED.invalid.includes('foreign-journal-gameplay-commit')&&realm.includes('rejected-zero-attempt-write')&&realm.includes('attemptSlotsUnchanged'));
record('realm-tests-forged-v3-previous-forensic-and-sameclass-journal-authority',realm.includes('forged-recomputed-outer-integrity-invalid-authority')&&realm.includes('forged-previous-nonrestorable-never-reconstructed')&&realm.includes('forged-forensic-full-semantic-validation')&&realm.includes('forged-sameclass-journal-never-reconstructed')&&realm.includes('journalReconstructionEntered===false')&&realm.includes('validDigestsAndIdentities===true'));
record('realm-tests-unjournaled-schema14-safe-reset-staging-refusal',realm.includes('unjournaled-safe-reset-staging-journal-only-zero-cleanup')&&realm.includes('journalAbsent===true')&&realm.includes('previousAbsent===true')&&realm.includes('schema14JournalOnlyEnforced===true'));
record('realm-tests-authentic-v1-v2-v3-import-adapters-and-rollback',realm.includes('for(const version of [1,2,3])')&&realm.includes("version===1?'12>13>14':version===2?'13>14':'14'")&&realm.includes('authentic-adapter-no-merge')&&realm.includes('rollback-swaps-complete-installations')&&realm.includes('rollback-reset-time-semantics-and-context-free-marker'));
record('realm-tests-nested-safe-reset-after-production-forget',contract.storage.nestedSafeReset?.previousInstallationSlotCount===15&&contract.storage.nestedSafeReset?.terminalSnapshotValueCount===18&&contract.storage.nestedSafeReset?.previousControlMerged===false&&contract.storage.nestedSafeReset?.productionForgetRequired===true&&realm.includes('nested-safe-reset-production-forget-and-second-reset-exact-binding')&&realm.includes('nestedSecondPreviousInstallationIdentity===nested.nestedFirstResetInstallationIdentity')&&realm.includes('nestedSecondMarkerPreResetSaveId===nested?.nestedFirstResetSaveId')&&realm.includes('nestedSaveIdsMerged===false'));
record('realm-tests-pending-offline-durable-zero-neutrality-source-revision-tracking-and-dedicated-anchor',realm.includes('durableZeroProjection')&&realm.includes('durableAnchorProjection')&&realm.includes('pending-offline-collection-neutrality-exact-durable-projection-and-source-revision-tracking')&&realm.includes('same(durableZeroProjection(beforeZero),durableZeroProjection(afterZero))')&&realm.includes('afterZero?.sourceRevision===beforeZero?.sourceRevision+1')&&realm.includes('pending-offline-dedicated-phase24a-output-anchor-stable')&&realm.includes('same(durableAnchorProjection(beforeAnchors),durableAnchorProjection(afterAnchors))')&&realm.includes('exactAnchor(beforeAnchors,f.anchors.pendingOffline)')&&realm.includes('exactAnchor(afterAnchors,f.anchors.pendingOffline)')&&realm.includes('collectionFormulaReads'));
record('realm-tests-c2b-authenticated-refusal',realm.includes('c2b-authenticated-refusal-zero-write-state-ui-focus-persistence')&&realm.includes('c2b-opening-refusal-zero-write-discarded-accrual-ui-focus')&&realm.includes('allUnchanged===true')&&realm.includes('snapshot?.focus'));
record('realm-tests-exact-zero-every-lineage',realm.includes('exactZero')&&realm.includes('root-release-and-claim-arrays-remain-empty')&&realm.includes('final-valid-schema14-zero-output'));
record('realm-tests-phase24a-exact-anchors',realm.includes('direct-fresh-exact-phase24a-output-anchor')&&realm.includes('schema12-chain-exact-migrated-anchor')&&realm.includes('schema13-established-exact-phase24a-anchor'));
record('realm-tests-15-slot-18-snapshot-topology',realm.includes('exact-15-slot-18-snapshot-shape')&&realm.includes("Object.keys(topology).sort()"));
record('realm-tests-write-traces-independently',realm.includes('traceSummary')&&realm.includes('exact-write-trace-present')&&realm.includes('bridge-trace-agrees-with-adapter'));
record('realm-tests-console-and-native-storage-cleanliness',realm.includes('zero-warning-error-console')&&realm.includes('authorized-zero-native-storage-accesses'));
record('realm-tests-current-and-loaded-schema14-diagnostics',realm.includes('diagnostics-current-loaded-schema14-empty-errors')&&realm.includes('currentSchemaVersion===14')&&realm.includes('loadedSchemaVersion===14')&&realm.includes('validationErrors'));
record('browser-runner-autostarts-and-publishes',runner.includes('run();')&&runner.includes('__EVERSTEAD_PHASE_24C2C_RESULT__')&&page.includes('Phase 24C-2C · Zero-only schema-14 integration'));
record('browser-runner-publishes-complete-outcomes-with-bounded-facts-and-correlation-digests',runner.includes("algorithm:'fnv1a32-tree-v1'")&&realm.includes("algorithm:'fnv1a32-tree-v1'")&&runner.includes('correlationDigest:measured.hash')&&realm.includes('correlationDigest:measured.hash')&&runner.includes('facts=factProjection(detail)')&&realm.includes('facts=explicitFacts===null?factProjection(detail):factProjection(explicitFacts)')&&runner.includes('evidence:attest(facts)')&&realm.includes('evidence:attest(facts)')&&runner.includes('stringCorrelation=value=>attest(value.length<=2048?value:')&&realm.includes('stringCorrelation=value=>attest(value.length<=2048?value:')&&runner.includes('exact targeted facts and deterministic correlation digest retained')&&!runner.includes('evidence:attest(detail)')&&!realm.includes('evidence:attest(detail)')&&!runner.includes('tamper-evident')&&!realm.includes('tamper-evident')&&!runner.includes("evidence:typeof detail==='object'&&detail!==null?detail:undefined")&&!realm.includes("evidence:typeof detail==='object'&&detail!==null?detail:undefined"));
record('realm-row-facts-cover-consumed-state-and-reload-operands',realm.includes("explicitFacts=null")&&realm.includes("first-boot-row-publishes-exact-consumed-state-facts")&&realm.includes("appliedMigrationCount:Array.isArray(state.saveMeta.appliedMigrations)?state.saveMeta.appliedMigrations.length:null")&&realm.includes("durableLineage={lineageKind:durable.migrations.lineageKind}")&&realm.includes("expectedRaw:reloadRaw")&&realm.includes("expectedRevision:reloadRevision")&&realm.includes("expectedUi:reloadUi")&&realm.includes("expectedWriteCount:reloadWrites")&&realm.includes("validationOk:reloadValid")&&realm.includes("zero:reloadZero"));
record('browser-transport-is-explicitly-bounded-at-row-command-realm-chunk-and-final-result',runner.includes('MAX_COMMAND_TRANSPORT_BYTES=196608')&&runner.includes('MAX_PUBLISHED_RESULT_BYTES=2097152')&&runner.includes('browser-command-serialized-transport-within-limit')&&runner.includes('browser-final-result-serialized-transport-within-limit')&&runner.includes('realm-envelope-serialized-transport-within-limit')&&realm.includes('MAX_REALM_TRANSPORT_BYTES=524288')&&realm.includes('realm-serialized-transport-within-limit')&&realm.includes("encoding:'bounded-attested-v1'")&&realm.includes('f.transport.realmChunkEncoding'));
record('browser-final-result-overflow-fail-closed-uses-mutable-publication-rows',runner.includes('let publishRows=[...publishedCandidateRows,transportRow],publishedMode=mode,published=')&&runner.includes("publishedMode='FATAL';const failure=row('browser-final-result-serialized-transport-within-limit'")&&runner.includes('publishRows=[failure];published=')&&!runner.includes('const publishRows='));
record('browser-final-result-omits-only-redundant-pass-detail-and-proves-row-facts-evidence-preservation',runner.includes('PASS_DETAIL_MAX_CHARACTERS=0')&&runner.includes("originalCandidateRows.map(item=>item.pass===true?{...item,detail:''}:item)")&&runner.includes('publishedCandidateRows.length===originalCandidateRows.length')&&runner.includes('publishedFailedCount===originalFailedCount')&&runner.includes('publishedBinding===originalBinding')&&runner.includes('item.facts===originalCandidateRows[index].facts&&item.evidence===originalCandidateRows[index].evidence')&&runner.includes('item.pass===true||item===originalCandidateRows[index]')&&runner.includes('assertionFactsEvidenceBindingBefore:originalBinding')&&runner.includes('assertionFactsEvidenceBindingAfter:publishedBinding')&&runner.includes('finalWithinLimit:finalCandidateBytes<=MAX_PUBLISHED_RESULT_BYTES')&&runner.includes('publishedRowCount:publishedCandidateRows.length+1')&&runner.includes('exactPublishedBytes:published.transport.bytes')&&!runner.includes('publishedCandidateRows=originalCandidateRows.filter'));
record('realm-chunk-sender-binds-complete-ordered-row-manifest-without-changing-row-facts',realm.includes("manifest={rowCount:baseRows.length,orderedDigest:attest(baseRows.map(item=>[item.id,item.evidence?.correlationDigest])).correlationDigest,algorithm:f.transport.orderedManifest}")&&realm.includes('itemBytes=new TextEncoder().encode(JSON.stringify(item)).length+1')&&realm.includes('groups.length>maxChunks')&&realm.includes("message={channel:config.channel,nonce:config.nonce,type:'result-chunk',transportId,chunkIndex,chunkCount:groups.length,rowStart,rowCount:rows.length,final,manifest,results:rows")&&realm.includes('if(final)message.errors=errors')&&realm.includes('exactBytes!==message.transport.bytes||exactBytes>MAX_REALM_TRANSPORT_BYTES'));
record('realm-chunk-receiver-recomputes-bytes-orders-deduplicates-and-accepts-only-complete-manifest',runner.includes("exactBytes=new TextEncoder().encode(JSON.stringify(data)).length")&&runner.includes("data?.type!=='result-chunk'")&&runner.includes('count>contract.transport.maxRealmChunks')&&runner.includes('index!==chunks.length')&&runner.includes("data.rowStart!==rows.length")&&runner.includes("rowIds.has(item.id)")&&runner.includes("Boolean(data.final)!==(index===count-1)")&&runner.includes("digest!==manifest.orderedDigest")&&runner.includes("chunks.length!==chunkCount")&&runner.includes("extra message after final chunk")&&runner.includes("setTimeout(()=>")&&runner.includes("},0)"));
record('browser-command-transport-omits-full-snapshot-and-json-clone-amplification',realm.includes("capture=()=>{const snap=read('snapshot')||{};return{state:{schemaVersion:snap.state?.schemaVersion},raw:snap.raw")&&realm.includes('value:transport(value)')&&!realm.includes('value:clone(value)')&&!realm.includes('snapshot:snap,state:snap.state,raw:snap.raw'));
record('browser-command-transport-stabilizes-and-verifies-exact-final-byte-count',realm.includes('for(let count=0;count<4;count++){bytes=new TextEncoder().encode(JSON.stringify(message)).length')&&realm.includes('const exactFinalBytes=new TextEncoder().encode(JSON.stringify(message)).length')&&realm.includes("if(exactFinalBytes!==message.transport.bytes)throw new Error('Command transport byte metadata did not stabilize')")&&realm.includes('if(exactFinalBytes>MAX_COMMAND_TRANSPORT_BYTES)throw new Error'));
record('browser-runner-publishes-bounded-progress-heartbeats',page.includes('id="progress"')&&runner.includes("event.data?.type==='progress'")&&runner.includes("setProgress('ordinary staging boundaries')")&&realm.includes("progress(`scenario ${v.scenario} start`)")&&realm.includes("progress('sending chunked results')"));
record('browser-runner-focused-authorized-realm-smokes-are-explicitly-nonacceptance',runner.includes("FOCUS_REALM_ID=new URLSearchParams(location.search).get('focus')")&&runner.includes("item.id===FOCUS_REALM_ID||item.scenario===FOCUS_REALM_ID")&&runner.includes("render('FOCUSED',rows)")&&runner.includes("if(prior?.mode!=='CANDIDATE')return"));
record('docs-present',existsSync(rel('docs/PHASE_24C2C_ZERO_INTEGRATION_QA_CONTRACT.md'))&&existsSync(rel('docs/PHASE_24C2C_ZERO_INTEGRATION_QA_RESULT.md')));
record('readme-records-frozen-acceptance-and-package-only-boundary',readme.includes('Accepted and frozen')&&readme.includes('Package-only PASS remains non-acceptance by itself')&&readme.includes('391/391')&&readme.includes(EXPECTED.candidateIndex));
record('result-records-exact-browser-runs-identities-residual-risks-and-exclusions',result.includes('**Verdict:** PASS')&&result.includes('185/185')&&result.includes('10/10')&&(result.match(/391\/391/g)||[]).length>=2&&result.includes(EXPECTED.candidateIndex)&&result.includes(EXPECTED.sources['src/phase24c-zero-activation-authority.js'])&&result.includes(EXPECTED.activationSemantic)&&result.includes('Residual risks')&&result.includes('Release exclusions'));
const checksumPath='qa/phase-24c2c-zero-activation/checksums.sha256',expectedChecksumPaths=['index.html','src/phase18-19-runtime.js','src/phase23-companion-catalog.js','src/phase23-companion-runtime.js','src/phase24-scaling-authority.js','src/phase24c-zero-activation-authority.js','src/phase24c-durable-definitions.js','src/phase24c-durable-foundation.js','qa/phase-24c2c-activation-authority/checksums.sha256','qa/phase-24c-foundation/README.md','qa/phase-24c-foundation/contract.json','qa/phase-24c-foundation/verify.mjs','docs/PHASE_24C_INACTIVE_FOUNDATION_CONTRACT.md','docs/PHASE_24C_INACTIVE_FOUNDATION_RESULT.md','qa/phase-24c-independent/README.md','qa/phase-24c-independent/contract.json','qa/phase-24c-independent/verify.mjs','docs/PHASE_24C_INDEPENDENT_QA_CONTRACT.md','docs/PHASE_24C_INDEPENDENT_QA_RESULT.md','qa/phase-24c2c-zero-activation/contract.json','qa/phase-24c2c-zero-activation/index.html','qa/phase-24c2c-zero-activation/realm.html','qa/phase-24c2c-zero-activation/runner.js','qa/phase-24c2c-zero-activation/realm.js','qa/phase-24c2c-zero-activation/verify.mjs','qa/phase-24c2c-zero-activation/README.md','docs/PHASE_24C2C_ZERO_INTEGRATION_QA_CONTRACT.md','docs/PHASE_24C2C_ZERO_INTEGRATION_QA_RESULT.md'];
if(existsSync(rel(checksumPath))){const checksumRows=text(checksumPath).trim().split(/\r?\n/).filter(Boolean),matches=checksumRows.map(line=>/^([0-9a-f]{64})  (.+)$/.exec(line)),paths=matches.map(match=>match?.[2]??null),bad=matches.flatMap((match,index)=>!match||!existsSync(rel(match[2]))||sha(match[2])!==match[1]?[checksumRows[index]]:[]);record('package-checksum-manifest-exact-ordered-unique-closure',checksumRows.length===expectedChecksumPaths.length&&same(paths,expectedChecksumPaths)&&new Set(paths).size===paths.length&&bad.length===0,{paths,bad})}else record('package-checksum-manifest-exact-ordered-unique-closure',false,'missing');

function extractMarked(source){
  const loaderPattern=/[\t ]*<!-- Phase 24C-2C zero-only authority load BEGIN -->[\s\S]*?<!-- Phase 24C-2C zero-only authority load END -->(?:\r?\n)?/g,jsPattern=/(^[\t ]*)?\/\* Phase 24C-2C ([^\r\n*]+?) BEGIN \*\/[\s\S]*?\/\* Phase 24C-2C \2 END \*\/(?:\r?\n)?/gm,loaders=[...source.matchAll(loaderPattern)],js=[];let normalized=source.replace(loaderPattern,'');normalized=normalized.replace(jsPattern,(full,_indent,name)=>{js.push({name,full});return''});return{normalized,loaders,js,loaderBegin:(source.match(/<!-- Phase 24C-2C zero-only authority load BEGIN -->/g)||[]).length,loaderEnd:(source.match(/<!-- Phase 24C-2C zero-only authority load END -->/g)||[]).length,jsBegin:(source.match(/\/\* Phase 24C-2C [^\r\n*]+? BEGIN \*\//g)||[]).length,jsEnd:(source.match(/\/\* Phase 24C-2C [^\r\n*]+? END \*\//g)||[]).length};
}
function inlineSyntax(source){const failures=[];for(const [index,match] of [...source.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].entries()){if(!match[1].trim())continue;const checked=spawnSync(process.execPath,['--check'],{cwd:ROOT,encoding:'utf8',input:match[1]});if(checked.status!==0)failures.push({index,error:checked.stderr.trim()})}return failures}

if(!PACKAGE_ONLY){
  const candidate=text('index.html'),marked=extractMarked(candidate),loader=marked.loaders[0]?.[0]||'',loaderSources=[...loader.matchAll(/<script\s+[^>]*src=["']([^"']+)["'][^>]*><\/script>/gi)].map(match=>match[1].split('?')[0]),firstInline=[...candidate.matchAll(/<script(?![^>]*\bsrc=)[^>]*>/gi)][0]?.index??-1,loaderAt=candidate.indexOf(contract.loader.beginMarker),loaderEndAt=candidate.indexOf(contract.loader.endMarker),legacyFixtureStart=candidate.indexOf('function phase24c2cQaLegacyFixture'),legacyFixtureDirectEnd=candidate.indexOf('const phase24c2cQaLegacyFixtureDirect='),legacyFixtureEnd=candidate.indexOf('function phase24c2cQaSeedSchema13'),legacyFixture=legacyFixtureStart>=0&&legacyFixtureDirectEnd>legacyFixtureStart?candidate.slice(legacyFixtureStart,legacyFixtureDirectEnd):'',retainedBackupFixture=legacyFixtureDirectEnd>=0&&legacyFixtureEnd>legacyFixtureDirectEnd?candidate.slice(legacyFixtureDirectEnd,legacyFixtureEnd):'',predecessorValidStart=candidate.indexOf('function phase24c2cPredecessorValid'),predecessorValidEnd=candidate.indexOf('function phase24c2cResetMarkerShape'),predecessorValid=predecessorValidStart>=0&&predecessorValidEnd>predecessorValidStart?candidate.slice(predecessorValidStart,predecessorValidEnd):'',inheritedLegacyStageStart=candidate.indexOf('if(legacyStage){'),inheritedLegacyStageEnd=candidate.indexOf('const staged=phase24c2cStage',inheritedLegacyStageStart),inheritedLegacyStage=inheritedLegacyStageStart>=0&&inheritedLegacyStageEnd>inheritedLegacyStageStart?candidate.slice(inheritedLegacyStageStart,inheritedLegacyStageEnd):'',inheritedLegacyStageTokens=['const prior=CURRENT_SCHEMA_VERSION','priorBootstrap=bootstrapPersistence','legacyStageSchemaVersion=legacyStage.state.schemaVersion','dispatchPrecondition=prior===14','priorBootstrap===bootstrapPersistencePhase24C2CCurrent','Number.isInteger(legacyStageSchemaVersion)','legacyStageSchemaVersion>=0&&legacyStageSchemaVersion<=13','CURRENT_SCHEMA_VERSION=13','bootstrapPersistence=bootstrapPersistenceBeforePhase23','try{bootstrapPersistenceBeforePhase24C2C()}','finally{bootstrapPersistence=priorBootstrap;CURRENT_SCHEMA_VERSION=prior}','if(bootstrapPersistence!==bootstrapPersistencePhase24C2CCurrent||CURRENT_SCHEMA_VERSION!==14)','if(PERSISTENCE_BLOCKED)return',"phase24c2cSaveRead('phase24c2c-after-inherited-staging')",'snapshot.journal!==null||snapshot.ordinaryStaging!==null','phase24c2cSlotsFromSnapshot(snapshot)','phase24c2cClassify(slots.activeRaw,slots)','PHASE_24C2C_SKIP_EPILOGUE_BOOT=true'];
  record('candidate-final-index-byte-frozen',sha('index.html')===EXPECTED.candidateIndex&&contract.baseline.candidateIndexSha256===EXPECTED.candidateIndex,{actual:sha('index.html'),expected:EXPECTED.candidateIndex});
  const currentCommitStart=candidate.indexOf('const commitPreparedBeforePhase24C2C=commitPrepared'),currentCommitEnd=candidate.indexOf('const commitPreparedBeforePhase24C2CStagingGate=',currentCommitStart),currentCommit=currentCommitStart>=0&&currentCommitEnd>currentCommitStart?candidate.slice(currentCommitStart,currentCommitEnd):'',legacyInvalidStart=candidate.indexOf('function phase24c2cQaLegacyStageInvalid'),legacyInvalidEnd=candidate.indexOf('function phase24c2cQaWriteTrace',legacyInvalidStart),legacyInvalid=legacyInvalidStart>=0&&legacyInvalidEnd>legacyInvalidStart?candidate.slice(legacyInvalidStart,legacyInvalidEnd):'';
  record('candidate-one-balanced-loader-block',marked.loaderBegin===1&&marked.loaderEnd===1&&marked.loaders.length===1,{begin:marked.loaderBegin,end:marked.loaderEnd,matched:marked.loaders.length});
  record('candidate-loader-exact-least-authority-order',same(loaderSources,EXPECTED.loaders),loaderSources);
  record('candidate-loader-precedes-inline-boot',loaderAt>=0&&loaderEndAt>loaderAt&&firstInline>loaderEndAt,{loaderAt,loaderEndAt,firstInline});
  const pendingMarkers=contract.markers.requiredJavascriptBlocks.includes('PENDING-WRITER-MARKER-NAMES');
  record('candidate-js-markers-finalized',!pendingMarkers,contract.markers.requiredJavascriptBlocks);
  if(!pendingMarkers){const names=marked.js.map(item=>item.name);record('candidate-all-js-markers-balanced-recognized-once',marked.jsBegin===marked.jsEnd&&marked.jsBegin===marked.js.length&&same([...names].sort(),[...contract.markers.requiredJavascriptBlocks].sort())&&new Set(names).size===names.length,{begin:marked.jsBegin,end:marked.jsEnd,names})}
  record('candidate-c2c-projection-exact-accepted-c2b',shaText(marked.normalized)===EXPECTED.acceptedCoordinator,{actual:shaText(marked.normalized),expected:EXPECTED.acceptedCoordinator,blocks:marked.js.map(item=>item.name)});
  record('candidate-current-schema14',candidate.includes('CURRENT_SCHEMA_VERSION=14')&&!/CURRENT_SCHEMA_VERSION\s*=\s*15/.test(candidate));
  record('candidate-pre-v14-physical-key-and-slot',candidate.includes("__raw_backup_v13")&&candidate.includes('preV14'));
  record('candidate-save-v3-and-reset-v9',/(?:formatVersion|version)\s*[:=]\s*3/.test(candidate)&&/(?:markerVersion|version)\s*[:=]\s*9/.test(candidate));
  record('candidate-boot-adoption-preflights-terminal-18-slot-snapshot',candidate.includes("phase24c2cSaveRead('phase24c2c-terminal-snapshot')")&&candidate.includes("if(snapshot.journal!==null)throw new PersistenceConflictError('A Save & Recovery journal appeared before schema-14 adoption')")&&candidate.includes('slots=phase24c2cSlotsFromSnapshot(snapshot)'));
  record('candidate-ordinary-commit-preflights-foreign-journal-and-active',candidate.includes("phase24c2cSaveRead('phase24c2c-ordinary-commit-preflight')")&&candidate.includes("if(snapshot.journal!==null)throw new PersistenceConflictError('Save & Recovery owns persistence; ordinary commit was refused')")&&candidate.includes('if(snapshot.active!==expectedActiveRaw)throw new PersistenceConflictError'));
  record('candidate-opening-epilogue-skips-redundant-first-boot-write',candidate.includes('PHASE_24C2C_SKIP_EPILOGUE_BOOT')&&candidate.includes('if(skip||!preview.changed)return{ok:true')&&candidate.includes('phase24c2cOpeningPreview'));
  record('candidate-phase23-predecessor-authority-physical-active-is-canonical-phase23-projection-raw',predecessorValid.includes('projected=phase24c2cPhase23Projection(candidate)')&&predecessorValid.includes('checked=phase23Validation(projected)')&&predecessorValid.includes('projectedRaw=JSON.stringify(projected)')&&predecessorValid.includes('phase23CurrentAuthority(projected,{...slots,activeRaw:projectedRaw})===true')&&!predecessorValid.includes('activeRaw:JSON.stringify(candidate)')&&!predecessorValid.includes('activeRaw:candidate'));
  record('candidate-authentic-schema12-fixtures-use-direct-captured-installation-complete-foundations-and-zero-write-phase23-ensure',legacyFixture.includes('PHASE_23_LEGACY_SAVE_RUNTIME.validateInstallation(PHASE_23_LEGACY_SAVE_RUNTIME.installation(legacySlots))')&&legacyFixture.includes('PHASE_ELEVEN_B_SLOT_NAMES.every(name=>Object.hasOwn(schema12Installation.slots,name))')&&legacyFixture.includes('exactCanonicalActive=schema12Raw===sourceRaw')&&legacyFixture.includes('phase23Schema12Raw(schema12Raw)')&&legacyFixture.includes('schema12FoundationsCompleteBeforeMigration')&&legacyFixture.includes('directCapturedSchema12Installation')&&legacyFixture.includes('legacyResetTargetUsed:false')&&legacyFixture.includes('currentPhase23FoundationsEnsureNoop')&&legacyFixture.includes('phase23FoundationEnsureChanged===false')&&legacyFixture.includes('phase23FoundationEnsureRawBefore===phase23FoundationEnsureRawAfter')&&legacyFixture.includes('phase23FoundationEnsureWrites===0')&&!legacyFixture.includes('PHASE_23_LEGACY_SAVE_RUNTIME.resetTarget'));
  record('candidate-dedicated-retained-backup-fixture-binds-exact-source-validates-every-in-memory-activation-authenticates-one-final-installation-and-keeps-phase23-ensure-noop',retainedBackupFixture.includes("kind!=='retained-backup'")&&retainedBackupFixture.includes('PHASE_23_LEGACY_SAVE_RUNTIME.resetTarget(sourceSnapshot)')&&retainedBackupFixture.includes('resetInstallation.slots.rawBackup===originalActive')&&retainedBackupFixture.includes('marker?.version===7')&&retainedBackupFixture.includes('marker.preResetActiveRawIdentity===rawIdentity(originalActive)')&&retainedBackupFixture.includes('marker.backupRawIdentity===rawIdentity(originalActive)')&&retainedBackupFixture.includes('commitBeforeInMemoryActivation=commitPrepared')&&retainedBackupFixture.includes('const checked=validation(candidate)')&&retainedBackupFixture.includes('activationValidationCount+=1')&&retainedBackupFixture.includes('activationStorageWrites===0')&&retainedBackupFixture.includes('finally{commitPrepared=commitBeforeInMemoryActivation}')&&retainedBackupFixture.includes('finalSlots={...resetInstallation.slots,active:PERSISTED_RAW}')&&retainedBackupFixture.includes('PHASE_23_LEGACY_SAVE_RUNTIME.validateInstallation(PHASE_23_LEGACY_SAVE_RUNTIME.installation(finalSlots))')&&retainedBackupFixture.includes('finalRetainedInstallationAuthenticated')&&retainedBackupFixture.includes('authenticated.installation.slots.rawBackup===originalActive')&&retainedBackupFixture.includes('retainedBackupRevalidatedAfterFoundations')&&retainedBackupFixture.includes('schema12FoundationsCompleteBeforeMigration')&&retainedBackupFixture.includes('currentPhase23FoundationsEnsureNoop')&&retainedBackupFixture.includes('ensureChanged===false')&&retainedBackupFixture.includes('ensureRawBefore===ensureRawAfter')&&retainedBackupFixture.includes('ensureWrites===0')&&retainedBackupFixture.includes('legacyResetTargetUsed:true'));
  record('candidate-retained-backup-direct-adoption-validates-exact-final-active-writes-zero-and-restores-coordinators-before-schema13-boot',retainedBackupFixture.includes('finalAdoptionWriteIndex=PERSISTENCE_LOG.length')&&retainedBackupFixture.includes("adopted=phase23Schema12Raw(snapshot.active)")&&retainedBackupFixture.includes('finalRetainedAdoptionValidated=Boolean(adopted)&&JSON.stringify(adopted)===snapshot.active')&&retainedBackupFixture.includes('S=clone(adopted);PERSISTED_RAW=snapshot.active;PERSISTED_IDENTITY=saveIdentity(snapshot.active)')&&retainedBackupFixture.includes('finalRetainedAdoptionStorageWrites=phase23QaSuccessfulStorageWrites(finalAdoptionWriteIndex)')&&retainedBackupFixture.includes('finalRetainedAdoptionIdentityExact')&&retainedBackupFixture.includes('inMemoryCommitCoordinatorRestored=commitPrepared===commitBeforeInMemoryActivation')&&retainedBackupFixture.includes('finalRetainedAdoptionStorageWrites!==0')&&retainedBackupFixture.includes('commitPrepared===commitPreparedBeforePhase24C2C')&&!retainedBackupFixture.includes('phase23QaAdoptLegacySeed(context)')&&!retainedBackupFixture.includes('phase24c2c-retained-profile'));
  record('candidate-legacy-scope-exits-before-current-phase23-boot-and-reports-restoration',candidate.includes("}),currentPhase23DefinitionsRestoredBeforeBoot=PHASE_23_LEGACY_SCOPE_DEPTH===0")&&candidate.includes('currentPhase23RuntimeRestoredBeforeBoot=PHASE_23_LEGACY_SCOPE_DEPTH===0')&&candidate.includes("if(!currentPhase23DefinitionsRestoredBeforeBoot||!currentPhase23RuntimeRestoredBeforeBoot)throw new PersistenceError('phase24c2c-qa-phase23-scope-restore'")&&candidate.indexOf('const checked=phase23Validation(S)')>candidate.indexOf('currentPhase23RuntimeRestoredBeforeBoot=PHASE_23_LEGACY_SCOPE_DEPTH===0'));
  record('candidate-historical-schema11-staging-fixture-uses-released-authority-and-proves-exact-protected-migration',candidate.includes("CURRENT_SCHEMA_VERSION=11")&&candidate.includes('phaseElevenFSchemaElevenAuthority(predecessor,activeRaw,physical)===true')&&candidate.includes('phaseElevenFSchemaElevenAuthority(candidate,candidateRaw,{...physical,activeRaw:candidateRaw})===true')&&candidate.includes('seededLaterCheckpointsNull=fixture.preV12===null&&fixture.preV13===null&&fixture.preV14===null')&&candidate.includes('preV12ExactRecoveredSchema11=!schema11||terminal.preV12===candidateRaw')&&candidate.includes('unrelatedProtectedSlotsPreserved'));
  const schema11ScopeStart=candidate.indexOf('function phase24c2cQaSchemaElevenRuntimeScope'),schema11RecoveryStart=candidate.indexOf('function phase24c2cQaLegacyStageRecovery'),schema11RecoveryEnd=candidate.indexOf('function phase24c2cQaWriteTrace'),schema11Scope=schema11ScopeStart>=0&&schema11RecoveryStart>schema11ScopeStart?candidate.slice(schema11ScopeStart,schema11RecoveryStart):'',schema11Recovery=schema11RecoveryStart>=0&&schema11RecoveryEnd>schema11RecoveryStart?candidate.slice(schema11RecoveryStart,schema11RecoveryEnd):'';
  record('candidate-historical-schema11-fixture-binds-exact-released-runtime-and-rosters-with-zero-writes',schema11Scope.includes('CURRENT_SCHEMA_VERSION=11')&&schema11Scope.includes('validation=validationThroughEleven')&&schema11Scope.includes('defaultState=defaultStateThroughEleven')&&schema11Scope.includes('schemaScopedDefaultState=schemaScopedDefaultStateThroughEleven')&&schema11Scope.includes('phase23LegacyScope(()=>phaseElevenFLegacyRosterScope(operation))')&&schema11Recovery.includes('schema11CurrentSchemaScoped=CURRENT_SCHEMA_VERSION===11')&&schema11Recovery.includes('schema11ValidationScopedThroughEleven=validation===validationThroughEleven')&&schema11Recovery.includes('schema11DefaultStateScopedThroughEleven=defaultState===defaultStateThroughEleven')&&schema11Recovery.includes('schema11SchemaScopedDefaultStateScopedThroughEleven=schemaScopedDefaultState===schemaScopedDefaultStateThroughEleven')&&schema11Recovery.includes('JSON.stringify(PHASE_23_LEGACY_IDS)')&&schema11Recovery.includes('JSON.stringify(PHASE_ELEVEN_F_LEGACY_FELLOWS.map(item=>item.id))')&&schema11Recovery.includes('JSON.stringify(PHASE_ELEVEN_F_LEGACY_FAMILY.map(item=>item.id))')&&schema11Recovery.includes("schema11ScopeStorageWrites=PERSISTENCE_LOG.slice(scopeLogIndex).filter(entry=>['setItem','removeItem'].includes(entry.operation)&&entry.status==='begin').length")&&schema11Recovery.includes('schema11ScopeStorageWrites!==0'));
  record('candidate-historical-schema11-restores-exact-current-runtime-rosters-schema14-and-commit-authority-before-storage-and-production-bootstrap',schema11Recovery.includes('schema11RuntimeBefore.schemaVersion===14&&CURRENT_SCHEMA_VERSION===14')&&schema11Recovery.includes('PHASE_23_LEGACY_SCOPE_DEPTH===0')&&schema11Recovery.includes('schema11CurrentSchemaRestoredBeforeStorageWrite=schema11RuntimeBefore.schemaVersion===14&&CURRENT_SCHEMA_VERSION===14')&&schema11Recovery.includes('schema11RuntimeRestoredBeforeStorageWrite=schema11CurrentSchemaRestoredBeforeStorageWrite&&schema11RuntimeRestored()&&schema11CurrentCatalogsRestoredBeforeStorageWrite&&schema11CurrentCommitAuthorityRestoredBeforeStorageWrite')&&schema11Recovery.includes('!schema11CurrentSchemaRestoredBeforeStorageWrite||!schema11RuntimeRestoredBeforeStorageWrite')&&schema11Recovery.indexOf('!schema11CurrentSchemaRestoredBeforeStorageWrite||!schema11RuntimeRestoredBeforeStorageWrite')<schema11Recovery.indexOf('phase24c2cQaWriteSnapshot(fixture)')&&schema11Recovery.includes('schema11CurrentSchemaRestoredBeforeBootstrap=schema11RuntimeBefore.schemaVersion===14&&CURRENT_SCHEMA_VERSION===14')&&schema11Recovery.includes('schema11RuntimeRestoredBeforeBootstrap=schema11CurrentSchemaRestoredBeforeBootstrap&&schema11RuntimeRestored()&&schema11CurrentCatalogsRestoredBeforeBootstrap&&schema11CurrentCommitAuthorityRestoredBeforeBootstrap')&&schema11Recovery.includes('!schema11CurrentSchemaRestoredBeforeBootstrap||!schema11RuntimeRestoredBeforeBootstrap')&&schema11Recovery.indexOf('!schema11CurrentSchemaRestoredBeforeBootstrap||!schema11RuntimeRestoredBeforeBootstrap')<schema11Recovery.indexOf('bootstrapPersistence()')&&schema11Recovery.includes('commitPrepared===schema11RuntimeBefore.commitPrepared&&commitPrepared!==commitPreparedBeforePhase24C2C'));
  record('candidate-inherited-legacy-staging-uses-exact-branch-only-phase12-recursion-dispatch-before-current-reread',inheritedLegacyStage.length>0&&inheritedLegacyStageTokens.every((token,index)=>{const at=inheritedLegacyStage.indexOf(token);return at>=0&&(index===0||at>inheritedLegacyStage.indexOf(inheritedLegacyStageTokens[index-1]))})&&!inheritedLegacyStage.includes('validation=')&&!inheritedLegacyStage.includes('commitPrepared='),{sliceFound:inheritedLegacyStage.length>0,tokens:inheritedLegacyStageTokens});
  record('candidate-legacy-stage-dispatch-has-no-production-global-evidence-or-shortcut',!candidate.includes('PHASE_24C2C_LEGACY_STAGE_DISPATCH_EVIDENCE')&&!/PHASE_24C2C_[A-Z0-9_]*DISPATCH_(?:EVIDENCE|PROOF|TRACE|CACHE)/.test(candidate));
  record('candidate-current-schema14-commit-validation-remains-context-current-and-unweakened',currentCommit.includes('const checked=validation(state)')&&!currentCommit.includes('const checked=validation(state,state.schemaVersion)')&&!currentCommit.includes('const checked=validation(state, state.schemaVersion)'));
  record('candidate-fixed-historical-staging-invalid-bridge-is-case-authentic-and-observes-actual-dispatch',Object.keys(EXPECTED.legacyInvalid).every(kind=>legacyInvalid.includes(`'${kind}'`))&&legacyInvalid.includes("expectedRefusalCode:'staging-provenance'")&&legacyInvalid.includes('actualRejectionCode:blockedCode')&&legacyInvalid.includes("entry.operation==='getItem'&&entry.step==='phase23-save-tool-boot-first-active'&&entry.status==='begin'")&&legacyInvalid.includes('attemptWrites=trace.length')&&legacyInvalid.includes('attemptProtectedBytesPreserved=PHASE_24C2C_SAVE_SLOT_NAMES.slice(1).every')&&legacyInvalid.includes('targetAdopted:attemptAfter.active!==attemptBefore.active')&&legacyInvalid.includes('cleanupPerformed')&&legacyInvalid.includes('terminalValidationOk')&&legacyInvalid.includes('bootstrapRestored')&&legacyInvalid.includes('schemaRestored'));
  record('candidate-invalid-bridge-reports-exact-schema13-collision-trace-and-older-previous-bootstrap',candidate.includes("rejectionTrace:blockedCode?[blockedCode]:[]")&&candidate.includes("let attemptRejected=false,productionBootstrapInvoked=false;try{productionBootstrapInvoked=true;bootstrapPersistence()")&&candidate.includes('resetAt:reset.resetAt,productionBootstrapInvoked,boundPreviousValidationReached'));
  record('candidate-exact-bridge-global-version',candidate.includes(contract.bridge.global)&&candidate.includes(contract.bridge.version));
  record('candidate-bridge-exact-method-vocabulary',EXPECTED.reads.every(name=>candidate.includes(name))&&EXPECTED.destructive.every(name=>candidate.includes(name)));
  record('candidate-bridge-requires-existing-full-boundary',candidate.includes('QA_BRIDGE_ALLOWED')&&candidate.includes('QA_ALLOW_DESTRUCTIVE')&&candidate.includes('requireQaDestructiveAuthorization')&&candidate.includes("segment==='qa=1'")&&candidate.includes("RUNTIME_QA.allowDestructive===true")&&candidate.includes("RUNTIME_QA.isolatedStorage===true")&&candidate.includes('STORAGE_SOURCE!==NATIVE_STORAGE'));
  record('candidate-product-qa-host-allowlist-exactly-excludes-contract-denial-host',candidate.includes("!['localhost','127.0.0.1','[::1]','::1'].includes(host)")&&!candidate.includes(EXPECTED.denialLoopbackHostname)&&same(contract.browserHostBoundary.productAllowedHostnames,EXPECTED.productAllowedHostnames)&&!EXPECTED.productAllowedHostnames.includes(contract.browserHostBoundary.denialLoopbackHostname));
  record('candidate-host-boundary-anchor-is-exactly-once-and-qa-probe-is-absent-from-production-bytes',candidate.split('const QA_BRIDGE_ALLOWED=qaBridgeAllowed();').length-1===1&&!candidate.includes(EXPECTED.qaProbeGlobal)&&contract.browserHostBoundary.qaProbeGlobal===EXPECTED.qaProbeGlobal);
  const qaBlock=marked.js.find(item=>/QA bridge/i.test(item.name))?.full||'';
  record('candidate-bridge-no-arbitrary-write-callback-token-api',qaBlock&&!/(genericMutator|refusalToken|refusalMarker|writeRaw|setItem\s*[:=]|removeItem\s*[:=]|captureCollectionGrantPayload|previewCollectionGrant|finalizeCollectionGrant|evaluateAdditive)/.test(qaBlock));
  const integrationBlocks=marked.js.filter(item=>!/QA bridge/i.test(item.name)).map(item=>item.full).join('\n');
  record('candidate-no-temporary-c2c-validation-trace-migration-proof-cache-evidence-or-console-diagnostics',!/PHASE_24C2C_[A-Z0-9_]*(?:PROOF|TRACE|CACHE|EVIDENCE)/.test(candidate)&&!/phase24c2c[A-Za-z0-9]*(?:Proof|Trace|Cache|Evidence)|phase24c2c-validation-reentry|console\.(?:error|warn|log)\s*\(/.test(integrationBlocks)&&!/(?:schema11Step|phase24c2c-qa-schema11-step|phase24c2c-qa-legacy-stage-stack|trace=\$\{JSON\.stringify\(trace\)\}|state=\$\{JSON\.stringify\()/.test(integrationBlocks));
  record('candidate-zero-integration-does-not-call-forbidden-foundation-apis',!/(captureCollectionGrantPayload|previewCollectionGrant|finalizeCollectionGrant|foldCollectionReceiptsInState|planRankReleaseActivation|planFamilyAlignment|evaluateAdditiveNumberBase|evaluateAdditivePool)\s*\(/.test(integrationBlocks));
  record('candidate-retains-c2b-private-weakset-refusal',candidate.includes('PERSISTED_MUTATION_REFUSAL_SIGNALS=new WeakSet()')&&candidate.includes('allowRefusal===true&&isPersistedMutationRefusal(error)'));
  for(const path of EXPECTED.loaders){const expected=contract.baseline.acceptedSourceSha256[path];record(`candidate-loaded-source-frozen-${path.replaceAll('/','-')}`,typeof expected==='string'&&/^[0-9a-f]{64}$/.test(expected)&&sha(path)===expected,{actual:sha(path),expected})}
  const syntaxFailures=inlineSyntax(candidate);record('candidate-inline-script-syntax',syntaxFailures.length===0,syntaxFailures);
}

const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;
for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` :: ${typeof row.detail==='string'?row.detail:JSON.stringify(row.detail)}`:''}`);
console.log(`SUMMARY ${passed}/${rows.length} passed; ${failed} failed; mode=${PACKAGE_ONLY?'package-only':'candidate'}`);
process.exitCode=failed?1:0;
