import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {existsSync,readFileSync,readdirSync,statSync} from 'node:fs';
import {resolve} from 'node:path';
import {Script,createContext,runInContext} from 'node:vm';

const ROOT=resolve(new URL('../..',import.meta.url).pathname),QA=resolve(ROOT,'qa/phase-22b-independent'),EXPECTED=['README.md','checksums.sha256','fixtures/contract.json','index.html','realm.html','realm.js','runner.js','verify.mjs'],rows=[];
const read=path=>readFileSync(resolve(ROOT,path)),text=path=>read(path).toString('utf8'),json=path=>JSON.parse(text(path)),sha=value=>createHash('sha256').update(value).digest('hex'),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)});
const filesBelow=(directory,prefix='')=>readdirSync(directory).flatMap(name=>{const absolute=resolve(directory,name),path=prefix?`${prefix}/${name}`:name;return statSync(absolute).isDirectory()?filesBelow(absolute,path):[path]}).sort();
const f=json('qa/phase-22b-independent/fixtures/contract.json'),focused=json('qa/phase-22b-features/fixtures/contract.json'),realmSource=text('qa/phase-22b-independent/realm.js'),runnerSource=text('qa/phase-22b-independent/runner.js'),index=text('index.html');

async function generatedFailClosed(){
  let written='',loaderMessage=null,resolveWritten;const writtenPromise=new Promise(resolvePromise=>{resolveWritten=resolvePromise}),config={channel:'everstead-phase-22b-independent-v2',nonce:'verify-p22b-generated',viewport:f.viewports[0],fixtures:f,mode:'active'};
  const loaderWindow={name:JSON.stringify(config)},loaderContext={window:loaderWindow,document:{open(){},write(value){written=String(value);resolveWritten()},close(){}},fetch:async()=>({ok:true,text:async()=>index}),parent:{postMessage(value){loaderMessage=value;resolveWritten()}},console,setTimeout,clearTimeout};loaderWindow.window=loaderWindow;createContext(loaderContext);
  try{runInContext(realmSource,loaderContext,{filename:'qa/phase-22b-independent/realm.js'});await Promise.race([writtenPromise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('loader generation timed out')),1000))]);if(loaderMessage)throw new Error(`loader posted before generation: ${JSON.stringify(loaderMessage)}`);const scripts=[...written.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(match=>match[1]),bootstrap=scripts.find(source=>source.includes('function installRuntime(config)')),suite=scripts.find(source=>source.includes('function runSuite()'));if(!bootstrap||!suite)throw new Error(`generated payload missing: bootstrap=${Boolean(bootstrap)} suite=${Boolean(suite)}`);new Script(bootstrap,{filename:'generated-p22b-bootstrap.js'});const suiteScript=new Script(suite,{filename:'generated-p22b-suite.js'});
    let now=0,resolvePosted;const postedPromise=new Promise(resolvePromise=>{resolvePosted=resolvePromise}),suiteWindow={__P22B_CONFIG__:config,__P22B_ERRORS__:[]},suiteContext={window:suiteWindow,parent:{postMessage:value=>resolvePosted(value)},performance:{now:()=>{now+=11000;return now}},setTimeout:callback=>{queueMicrotask(callback);return 1},clearTimeout(){},console,document:{},innerWidth:320,innerHeight:568};suiteWindow.window=suiteWindow;createContext(suiteContext);suiteScript.runInContext(suiteContext);const posted=await Promise.race([postedPromise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('generated suite did not fail closed')),1000))]);return{ok:posted.channel===config.channel&&posted.nonce===config.nonce&&posted.results?.length===1&&posted.results[0].id==='trusted-phase20-21-bridge-present-version'&&posted.results[0].pass===false&&posted.errors?.length===0,ids:posted.results?.map(item=>item.id),errors:posted.errors};
  }catch(error){return{ok:false,error:error.stack||error.message,loaderMessage,writtenBytes:written.length}}
}

record('package-topology',same(filesBelow(QA),EXPECTED),filesBelow(QA));
const checksumRows=text('qa/phase-22b-independent/checksums.sha256').trim().split('\n').filter(line=>line&&!line.startsWith('#')).map(line=>{const match=line.match(/^([0-9a-f]{64})  (.+)$/);return match?{expected:match[1],path:match[2]}:null}),checksumFailures=checksumRows.filter(item=>!item||!existsSync(resolve(ROOT,item.path))||sha(read(item.path))!==item.expected).map(item=>item?.path||'malformed');record('package-checksums',checksumRows.length===7&&checksumFailures.length===0,{count:checksumRows.length,failures:checksumFailures});
record('fixture-current-base-source-bridge-and-frozen-identity',f.contractVersion===2&&f.baseCommit===focused.baseCommit&&f.sourceCommit==='ddc129935eac809f106c2782bb63b0b138fe0ad0'&&f.sourceCommit===focused.sourceCommit&&f.sourceFrozen===true&&focused.sourceFrozen===true&&f.bridgeVersion==='phase-20-21-independent-qa-v2'&&f.indexSha256===focused.indexSha256&&f.indexBytes===focused.indexBytes&&f.phase17Sha256===focused.phase17Sha256&&f.phase17Bytes===focused.phase17Bytes&&f.stylesheetHref===focused.stylesheetHref&&f.stylesheetSha256===focused.stylesheetSha256&&f.phase22aStylesheetSha256===focused.phase22aStylesheetSha256);
record('fixture-non-vacuous-legacy-state-sequence',same(f.legacyStateSetup,{resetFixture:'p13.fixture.fresh.v1',progressEvent:'oath.first-completed',recordedEvent:'campaign.first-clear-committed',recordedStageId:'broken-roads-1',resolutionStoryId:'story.book1.chapter1.village-toll.resolution',storyReadySourceId:'story.book1.chapter1.village-toll.resolution',claimSourceId:'legacy.oathkeeper.tier-1',remainingReadySourceId:'legacy.feat.first-campaign-clear'}));
record('fixture-exact-navigation-roster-and-viewports',same(f.navigation,['village','oaths','fellows','adventure','more'])&&same(f.rosterTabs,['fellows','family','companions','relics'])&&f.minimumTargetPx===44&&f.viewports.length===7&&same(f.viewports.slice(0,5).map(item=>[item.width,item.height]),[[320,568],[390,844],[430,932],[768,1024],[1024,768]])&&f.viewports.some(item=>item.copyScale===1.3)&&f.viewports.some(item=>item.reducedMotion)&&f.inactiveViewport.width===390&&f.inactiveViewport.height===844);
record('production-single-cache-versioned-phase22b-stylesheet',Boolean(focused.stylesheetInclude)&&index.split(focused.stylesheetInclude).length===2&&index.indexOf(f.phase22aStylesheetHref)<index.indexOf(f.stylesheetHref)&&!index.includes('__EVERSTEAD_PHASE_22B_QA__'));
record('runner-loads-real-candidate-and-current-bridge',realmSource.includes("fetch('../../index.html'")&&realmSource.includes('__EVERSTEAD_PHASE_20_21_QA__')&&realmSource.includes('qa.version===f.bridgeVersion')&&!realmSource.includes('fakeEngine'));
record('runner-explicit-safe-payload-splice',realmSource.includes("lastIndexOf('</body>')")&&realmSource.includes('source.slice(0,insertion)+bootstrap+source.slice(insertion,bodyClose)+suite+source.slice(bodyClose)')&&!realmSource.includes("replace('</body>',suite"));
record('runner-source-load-identity',['../../index.html','../../src/phase17-runtime.js','f.indexSha256','f.phase17Sha256','f.phase22aStylesheetHref','f.stylesheetHref','crypto.subtle.digest','f.stylesheetSha256','cache-versioned-phase22a-and-phase22b-source-load-byte-identity'].every(value=>realmSource.includes(value)));
record('runner-fellowship-and-full-art-coverage',['fellowship-exact-tabs-and-roster-visible','fellow-full-art-sheet-real-and-safe','family-full-art-sheet-real-and-safe','naturalWidth','objectFit','fellow-sheet-escape-exact-focus-return','family-sheet-escape-exact-focus-return'].every(value=>realmSource.includes(value)));
record('runner-wayfarer-campaign-profile-separation',['campaign-exactly-one-separate-wayfarer-presentation','campaign-record-matches-existing-state','wayfarer-profile-distinct-full-art-and-safe','data-phase17-campaign-identity-card','data-phase22b-wayfarer-stage','data-phase22b-campaign-record','data-phase17-player-profile','dataset.playerRosterMember','!wayfarer.closest(\'.roster-grid\')'].every(value=>realmSource.includes(value)));
record('runner-non-vacuous-legacy-state-coverage',['phase13-legacy-fixture-bridge-present','legacy-incomplete-feat-and-progress-live-state','legacy-recorded-progress-story-ready-feat-ready-and-oath-claimed-live-states','legacy-incomplete-visual-visit-save-reward-neutral','legacy-recorded-mixed-visual-visit-save-reward-neutral',"phase13Call('destructive','story',f.legacyStateSetup.resolutionStoryId,'skip')","same(states,['claimed','ready','ready'])",'readyButtons.length===2','readyButtons.every(target)',"phase13().version==='phase-13-independent-qa-v1'",'document.activeElement===mixedInvoker','oldInvokerConnected','sameOldNode','currentSemanticMatch'].every(value=>realmSource.includes(value)));
record('runner-legacy-chronicle-more-storage',['achievements-and-legacy-current-state-present','chronicle-existing-groups-records-or-honest-empty-safe','more-storage-surface-present-readable-and-safe','data-phase22b-legacy','data-phase22b-chronicle-group','data-phase22b-more-storage','data-phase13-legacy','data-phase17-chronicle-open','data-save-recovery'].every(value=>realmSource.includes(value)));
record('runner-hidden-storage-input-accessible-not-visible-target',['intentionallyHiddenFile','input[type="file"][data-save-recovery-file]','label[for=','!visible(fileInput)','target(choose)'].every(value=>realmSource.includes(value)));
record('runner-44px-focus-overflow-cta',['minimumTargetPx','visible-keyboard-focus','getBoundingClientRect','scrollWidth','overlap(rectData(node),bottomRect)','all-required-feature-and-five-route-surfaces-no-overflow-44px-or-covered-cta'].every(value=>realmSource.includes(value)));
record('runner-post-setup-save-and-reward-neutral',['prepare','rawBefore','writesBefore','post-setup-visual-traversal-zero-save-writes','post-setup-visual-traversal-reward-neutral','rawAfter===rawBefore','revision(snapshotAfter)===revision(snapshotBefore)','rewardFingerprint'].every(value=>realmSource.includes(value)));
record('runner-reduced-copy-and-inactive-production',['copyScale','reduced-motion-authoritative-and-static','config.mode===\'active\'','production-inactive-no-qa-bridge','production-flags-remain-inactive','inactive-visual-traversal-zero-save-writes'].every(value=>realmSource.includes(value)));
record('runner-isolated-storage-and-console-safety',['allowDestructive:true','isolatedStorage:true','zero-native-storage-accesses','zero-warning-error-console','inactive-zero-native-storage-accesses','inactive-zero-warning-error-console'].every(value=>realmSource.includes(value)));
record('runner-seven-active-plus-one-inactive',runnerSource.includes('for(const viewport of f.viewports)')&&runnerSource.includes("realm(f,f.inactiveViewport,'inactive')")&&runnerSource.includes('__EVERSTEAD_PHASE_22B_INDEPENDENT_RESULT__'));
for(const file of ['runner.js','realm.js','verify.mjs']){const checked=spawnSync(process.execPath,['--check',`qa/phase-22b-independent/${file}`],{cwd:ROOT,encoding:'utf8'});record(`syntax-${file}`,checked.status===0,checked.stderr.trim())}
const generated=await generatedFailClosed();record('runtime-generated-realm-fails-closed',generated.ok,generated);

const passed=rows.filter(row=>row.pass).length,failed=rows.length-passed;for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` — ${row.detail}`:''}`);console.log(`RESULT ${passed} passed, ${failed} failed`);process.exitCode=failed?1:0;
