(() => {
  'use strict';
  const CHANNEL='everstead-phase-5',inlineJson=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  function installRuntime(config){
    const slots=new Map(Object.entries(config.slots)),nativeSetTimeout=window.setTimeout.bind(window),nativeClearTimeout=window.clearTimeout.bind(window);let saveIndex=0,transactionIndex=0;
    const nativeStorageAccesses=[],errors=[];let nativeStorageInstrumented=false;
    let exactNativeStorage=null;try{const nativeStorage=window.localStorage;exactNativeStorage=nativeStorage;if(config.mode==='native-storage')for(const key of Object.values(config.keys))nativeStorage.removeItem(key);for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    const presentationTimers=[];window.__PHASE_5_CONFIG__=config;window.__PHASE_5_SLOTS__=slots;window.__PHASE_5_ERRORS__=errors;window.__PHASE_5_NATIVE_STORAGE_ACCESSES__=nativeStorageAccesses;window.__PHASE_5_NATIVE_STORAGE_INSTRUMENTED__=nativeStorageInstrumented;window.__PHASE_5_PRESENTATION_TIMERS__=presentationTimers;window.matchMedia=query=>({matches:query==='(prefers-reduced-motion: reduce)'&&config.mode==='reduced-motion',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return true}});
    window.addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));window.addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>slots.set(String(key),String(value)),removeItem:key=>slots.delete(String(key))},runtime={storage:config.mode==='native-storage'?exactNativeStorage:memoryStorage,clock:{now:()=>config.now,setTimeout(callback,delay){if(delay===1100)presentationTimers.push(delay);return nativeSetTimeout(callback,delay)},clearTimeout:nativeClearTimeout},random:()=>.5,confirm:()=>true,ids:{save:()=>config.saveId??`save-p5-browser-${++saveIndex}`,transaction:()=>`tx-p5-browser-${++transactionIndex}`},qa:config.mode==='unattested'?{allowDestructive:true,isolatedStorage:false}:{allowDestructive:true,isolatedStorage:true}};
    if(config.features)runtime.features=config.features;window.__EVERSTEAD_RUNTIME__=runtime;
  }
  function runSuite(){
    const channel='everstead-phase-5',config=window.__PHASE_5_CONFIG__,slots=window.__PHASE_5_SLOTS__,results=[],add=(id,pass,detail='')=>results.push({id,pass:Boolean(pass),detail:String(detail)}),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),click=selector=>{const node=document.querySelector(selector);if(node)node.click();return node},send=()=>parent.postMessage({channel,nonce:config.nonce,results,errors:window.__PHASE_5_ERRORS__.slice(),slots:Object.fromEntries(slots)},'*');
    (async()=>{await wait(500);const bridge=window.__EVERSTEAD_QA__;if(!config.expectBridge){add('encoded-query-bridge-absent',bridge===undefined);add('encoded-query-zero-errors',window.__PHASE_5_ERRORS__.length===0,window.__PHASE_5_ERRORS__.join('\n'));send();return}
      add('bridge-present',Boolean(bridge));add('viewport-exact',innerWidth===config.viewport.width&&innerHeight===config.viewport.height,`${innerWidth}x${innerHeight}`);add('no-horizontal-overflow',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);const first=bridge.snapshot(),state=first.state,flags=bridge.flags().features;add('schema6-snapshot',first.ok&&state.schemaVersion===6);add('player-shape',state.player.avatarId==='wayfarer'&&state.player.rankExp===0&&state.player.rank===1);add('campaign-shape',state.fellowCampaign&&Array.isArray(state.fellowCampaign.clearedStageIds)&&state.fellowCampaign.runOrdinal===0&&state.fellowCampaign.lastReceipt===null);add('retired-flags-false',['story','tower','trading','patrol','operations'].every(key=>flags[key]===false));add('campaign-flag',flags.fellowCampaign===(config.mode!=='all-disabled'));
      if(config.mode==='schema1-seed'){add('seed-pre-v6-present',JSON.parse(slots.get(config.keys.backupV5)).schemaVersion===5);add('seed-schema6-receipt',state.saveMeta.appliedMigrations.at(-1).id==='schema-5-to-6');add('seed-position-only',state.fellowCampaign.selectedStageId==='broken-roads-6'&&state.fellowCampaign.clearedStageIds.length===5&&state.player.rankExp===0);add('seed-no-retro-gifts',state.gifts===JSON.parse(slots.get(config.keys.backupV5)).gifts);add('seed-zero-errors',window.__PHASE_5_ERRORS__.length===0,window.__PHASE_5_ERRORS__.join('\n'));send();return}
      if(config.mode==='fresh'){
        add('fresh-stage1',state.fellowCampaign.selectedStageId==='broken-roads-1'&&state.fellowCampaign.clearedStageIds.length===0);add('fresh-no-checkpoints',[0,1,2,3,4,5].every(version=>!slots.has(config.keys[`backupV${version}`])));const topbar=document.querySelector('.topbar')?.textContent||'';add('topbar-gift-gold-rank',topbar.includes('◆')&&topbar.includes('◈')&&topbar.includes('R1'));add('patrol-badge-absent',!document.querySelector('.badge-dot'));click('[data-nav="adventure"]');await wait(20);let text=document.querySelector('main.screen')?.textContent||'';add('campaign-ui-live',text.includes('Fellow Campaign')&&text.includes('The Wayfarer')&&text.includes('Village Toll')&&text.includes('Total Fellow Roster Power')&&text.includes('Target Fellow'));add('ten-progress-nodes',document.querySelectorAll('[data-campaign-stage]').length===10);add('walking-art-hook',Boolean(document.querySelector('.campaign-walk .campaign-player')));add('legacy-tabs-absent',!text.includes('Trading Hall')&&!text.includes('Tower'));
        const beforeGold=state.gold,stageOne=bridge.act('campaign-run',{id:'broken-roads-1'}),afterOne=stageOne.state;add('stage1-first-clear-live',stageOne.ok&&stageOne.changed&&afterOne.fellowCampaign.clearedStageIds.join(',')==='broken-roads-1');add('stage1-receipt-live',afterOne.fellowCampaign.lastReceipt.firstClear===true&&afterOne.fellowCampaign.lastReceipt.rewards.fellowExp.cael===120&&afterOne.fellowCampaign.lastReceipt.rewards.fellowShards.cael===2);add('stage1-gold-spend-live',beforeGold-afterOne.gold===afterOne.fellowCampaign.lastReceipt.effectiveCost);add('stage1-rank-live',afterOne.player.rankExp===25&&afterOne.player.rank===1);
        const stageTwo=bridge.act('campaign-run',{id:'broken-roads-2'});add('stage2-rank2-live',stageTwo.ok&&stageTwo.state.player.rankExp===55&&stageTwo.state.player.rank===2);const select=bridge.act('campaign-select',{id:'broken-roads-1'}),replay=bridge.act('campaign-run',{id:'broken-roads-1'});add('replay-live',select.ok&&replay.ok&&!replay.state.fellowCampaign.lastReceipt.firstClear&&replay.state.fellowCampaign.lastReceipt.rewards.rankExp===0&&replay.state.fellowCampaign.runOrdinal===3);
        const exported=bridge.recovery.export().data;add('safe-export-eight-slots',exported.exportVersion===6&&exported.preV6BackupKey===config.keys.backupV5&&Object.keys(exported.readErrors).length===8);const reload=bridge.recovery.reload();add('reload-persists-campaign',reload.ok&&reload.state.fellowCampaign.runOrdinal===3&&reload.state.player.rank===2)
      }
      if(config.mode==='schema5'){add('schema5-checkpoint-exact',slots.get(config.keys.backupV5)===config.originalActiveRaw);add('schema5-position-migration',state.fellowCampaign.selectedStageId==='broken-roads-6'&&state.fellowCampaign.clearedStageIds.length===5);add('schema5-one-receipt',state.saveMeta.appliedMigrations.filter(item=>item.id==='schema-5-to-6').length===1);add('schema5-rank-zero',state.player.rankExp===0&&state.player.rank===1)}
      if(config.mode==='stage10'){add('stage10-position',state.fellowCampaign.selectedStageId==='broken-roads-10'&&state.fellowCampaign.clearedStageIds.length===9);add('stage10-unclaimed',!state.fellowCampaign.clearedStageIds.includes('broken-roads-10')&&!state.fellowCampaign.firstClearClaimedStageIds.includes('broken-roads-10'));add('stage10-rank-zero',state.player.rankExp===0&&state.player.rank===1);add('stage10-no-retro-rewards',state.gifts===JSON.parse(config.originalActiveRaw).gifts)}
      if(config.mode==='legacy'){add('legacy-v0-exact',slots.get(config.keys.backupV0)===config.originalActiveRaw);add('legacy-all-checkpoints',[1,2,3,4,5].every(version=>JSON.parse(slots.get(config.keys[`backupV${version}`])).schemaVersion===version));add('legacy-unicode',state.oaths.some(oath=>oath.title==='Fixture café review 🌵'));add('legacy-position-only',state.fellowCampaign.selectedStageId==='broken-roads-6'&&state.player.rankExp===0)}
      if(config.mode==='disabled-override'){const before=slots.get(config.keys.active),refused=['story','tower','trade','patrol-start','operation-start'].map(name=>bridge.act(name));add('explicit-true-retired-still-false',['story','tower','trading','patrol','operations'].every(key=>flags[key]===false));add('retired-actions-refused',refused.every(value=>!value.ok));add('retired-actions-zero-write',slots.get(config.keys.active)===before);click('[data-nav="village"]');let text=document.querySelector('main.screen')?.textContent||'';add('patrol-control-absent',!text.includes('PATROL'));click('[data-nav="more"]');text=document.querySelector('main.screen')?.textContent||'';add('operations-control-absent',!text.includes('Operations'))}
      if(config.mode==='unattested'){const before=slots.get(config.keys.active),revision=state.saveMeta.revision,refused=[bridge.act('campaign-select',{id:'broken-roads-1'}),bridge.act('campaign-run',{id:'broken-roads-1'})];add('unattested-campaign-actions-refused',refused.every(item=>!item.ok));add('unattested-zero-write',slots.get(config.keys.active)===before&&bridge.snapshot().state.saveMeta.revision===revision)}
      if(config.mode==='all-disabled'){click('[data-nav="adventure"]');await wait(20);const before=slots.get(config.keys.active),revision=bridge.snapshot().state.saveMeta.revision,ui=document.body.innerHTML;add('all-disabled-no-campaign-control',!document.querySelector('[data-campaign-run]'));const refused=[bridge.act('campaign-select',{id:'broken-roads-1'}),bridge.act('campaign-run',{id:'broken-roads-1'})];add('all-disabled-actions-refused',refused.every(item=>!item.ok));add('all-disabled-zero-write',slots.get(config.keys.active)===before&&bridge.snapshot().state.saveMeta.revision===revision);add('all-disabled-zero-ui-mutation',document.body.innerHTML===ui)}
      if(config.mode==='replay-hit'||config.mode==='replay-miss'){const expected=config.mode==='replay-hit'?1:0,firstClear=bridge.act('campaign-run',{id:'broken-roads-1'}),secondClear=bridge.act('campaign-run',{id:'broken-roads-2'}),selected=bridge.act('campaign-select',{id:'broken-roads-1'}),replay=bridge.act('campaign-run',{id:'broken-roads-1'}),receipt=replay.state.fellowCampaign.lastReceipt;add('replay-sequence-live',firstClear.ok&&secondClear.ok&&selected.ok&&replay.ok&&receipt.sequence===3&&receipt.firstClear===false);add('replay-outcome-live',receipt.rewards.fellowShards.cael===expected,JSON.stringify(receipt.rewards));add('replay-rank-live',replay.state.player.rank===2&&replay.state.player.rankExp===55)}
      if(config.mode==='normal-motion'||config.mode==='reduced-motion'){const reduced=config.mode==='reduced-motion',rules=[...document.styleSheets].flatMap(sheet=>{try{return[...sheet.cssRules]}catch{return[]}}),media=rules.find(rule=>rule.conditionText?.includes('prefers-reduced-motion')),reducedRule=[...(media?.cssRules||[])].find(rule=>rule.style);add('motion-media-selector-live',matchMedia('(prefers-reduced-motion: reduce)').matches===reduced);add('reduced-motion-rule-live',Boolean(media));add('reduced-motion-disables-animation',reducedRule?.style.animationName==='none',reducedRule?.style.animation||'');add('reduced-motion-disables-transition',reducedRule?.style.transitionProperty==='none',reducedRule?.style.transition||'');click('[data-nav="adventure"]');await wait(20);const button=document.querySelector('[data-campaign-run]');add('production-run-button-live',Boolean(button));button?.click();const immediate=bridge.snapshot().state,walk=document.querySelector('.campaign-walk'),overlay=document.querySelector('#overlay')?.textContent||'';add('production-run-receipt-immediate',immediate.fellowCampaign.runOrdinal===1&&immediate.fellowCampaign.lastReceipt?.stageId==='broken-roads-1');if(reduced){add('reduced-result-modal-synchronous',overlay.includes('Stage cleared')&&overlay.includes('Village Toll'));add('reduced-no-running-class',!walk?.classList.contains('running'));add('reduced-no-presentation-timer',window.__PHASE_5_PRESENTATION_TIMERS__.length===0,window.__PHASE_5_PRESENTATION_TIMERS__.join(','))}else{add('normal-running-class-immediate',walk?.classList.contains('running'));add('normal-result-modal-delayed',!overlay.includes('Stage cleared')&&window.__PHASE_5_PRESENTATION_TIMERS__.length===1,window.__PHASE_5_PRESENTATION_TIMERS__.join(','));await wait(1200);const resultText=document.querySelector('#overlay')?.textContent||'';add('normal-result-modal-after-walk',resultText.includes('Stage cleared')&&resultText.includes('Village Toll'))}}
      if(config.mode==='native-storage'){window.__PHASE_5_NATIVE_STORAGE_ACCESSES__.length=0;const revision=state.saveMeta.revision,ui=document.body.innerHTML,refused=[bridge.act('campaign-select',{id:'broken-roads-1'}),bridge.act('campaign-run',{id:'broken-roads-1'})];add('native-actions-refused',refused.every(item=>!item.ok));add('native-zero-state-mutation',bridge.snapshot().state.saveMeta.revision===revision);add('native-zero-ui-mutation',document.body.innerHTML===ui);add('native-zero-action-storage-calls',window.__PHASE_5_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_5_NATIVE_STORAGE_ACCESSES__.join(','));add('native-realm-zero-errors',window.__PHASE_5_ERRORS__.length===0,window.__PHASE_5_ERRORS__.join('\n'));send();return}
      const diagnostics=bridge.diagnostics().diagnostics;add('diagnostics-phase5',diagnostics.schema.current===6&&Object.hasOwn(diagnostics,'preV6Backup')&&Number.isSafeInteger(diagnostics.totalFellowRosterPower));add('native-storage-instrumented',window.__PHASE_5_NATIVE_STORAGE_INSTRUMENTED__===true);add('zero-native-storage-calls',window.__PHASE_5_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_5_NATIVE_STORAGE_ACCESSES__.join(','));add('realm-zero-errors',window.__PHASE_5_ERRORS__.length===0,window.__PHASE_5_ERRORS__.join('\n'));send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }
  (async()=>{const config=JSON.parse(window.name);window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error('index.html: HTTP '+response.status);const source=await response.text(),firstScript=source.indexOf('<script>');if(firstScript<0)throw new Error('Production script is missing');const bootstrap='<script>('+installRuntime.toString()+')('+inlineJson(config)+')<\/script>',suite='<script>('+runSuite.toString()+')()<\/script>',instrumented=source.slice(0,firstScript)+bootstrap+source.slice(firstScript).replace('</body>',suite+'</body>');document.open();document.write(instrumented);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce:'unknown',results:[{id:'realm-loader-fatal',pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
