import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'../..');
const contract=JSON.parse(fs.readFileSync(path.join(here,'contract.json'),'utf8'));
const S=contract.selectors;
const rows=[];
const record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.jpeg':'image/jpeg','.woff2':'font/woff2'};

function server(){return http.createServer((request,response)=>{
  const url=new URL(request.url,'http://127.0.0.1');
  if(url.pathname==='/__phase24l_b3b_host__.html'){
    response.writeHead(200,{'content-type':mime['.html'],'cache-control':'no-store'}).end(`<!doctype html><html style="width:100%;height:100%"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phase 24L-B3B QA host</title><style>html,body{width:100%;height:100%;margin:0;overflow:hidden}#realm{display:block;width:100%;height:100%;border:0}</style></head><body><iframe id="realm" title="Everstead Phase 24L-B3B QA realm" src="/index.html?${contract.integration.query.replaceAll('&','&amp;')}"></iframe></body></html>`);return;
  }
  const relative=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname).replace(/^\/+/,''),target=path.resolve(root,relative);
  if(target!==root&&!target.startsWith(root+path.sep)){response.writeHead(403).end();return}
  fs.readFile(target,(error,data)=>{if(error){response.writeHead(404).end();return}response.writeHead(200,{'content-type':mime[path.extname(target)]||'application/octet-stream','cache-control':'no-store'}).end(data)});
})}
async function listen(instance){await new Promise((resolve,reject)=>{instance.once('error',reject);instance.listen(0,'127.0.0.1',resolve)});return`http://127.0.0.1:${instance.address().port}`}

async function installMemoryRuntime(context){await context.addInitScript(()=>{
  if(window===window.top){Object.defineProperty(window,'__P24LB3B_SHARED__',{configurable:false,enumerable:false,writable:false,value:{slots:new Map(),writes:[],reads:[],removes:[],native:[],clients:new Set(),clientIndex:0,saveIndex:0,transactionIndex:0,now:1810000000000}});return}
  const shared=window.top.__P24LB3B_SHARED__,clientId=`phase24l-b3b-client-${++shared.clientIndex}`;shared.clients.add(window);
  const nativeGet=Storage.prototype.getItem,nativeSet=Storage.prototype.setItem,nativeRemove=Storage.prototype.removeItem;
  Storage.prototype.getItem=function(...args){shared.native.push(['getItem',String(args[0])]);return nativeGet.apply(this,args)};
  Storage.prototype.setItem=function(...args){shared.native.push(['setItem',String(args[0])]);return nativeSet.apply(this,args)};
  Storage.prototype.removeItem=function(...args){shared.native.push(['removeItem',String(args[0])]);return nativeRemove.apply(this,args)};
  const notify=(key,oldValue,newValue)=>{for(const peer of shared.clients){if(peer===window||peer.closed)continue;setTimeout(()=>{try{peer.dispatchEvent(new peer.StorageEvent('storage',{key,oldValue,newValue,url:peer.location.href,storageArea:peer.localStorage}))}catch{}},0)}};
  const memory=Object.freeze({getItem(key){key=String(key);shared.reads.push([key,clientId]);return shared.slots.get(key)??null},setItem(key,value){key=String(key);value=String(value);const oldValue=shared.slots.get(key)??null;shared.writes.push([key,value,clientId]);shared.slots.set(key,value);notify(key,oldValue,value)},removeItem(key){key=String(key);const oldValue=shared.slots.get(key)??null;shared.removes.push([key,clientId]);shared.slots.delete(key);notify(key,oldValue,null)}});
  const nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);
  window.__EVERSTEAD_RUNTIME__={storage:memory,clock:{now:()=>shared.now,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.4375,confirm:()=>true,ids:{save:()=>`save-phase24l-b3b-${++shared.saveIndex}`,transaction:()=>`tx-phase24l-b3b-${++shared.transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
  window.__EVERSTEAD_PERSISTENCE_TEST__={storage:memory,operationLog:[],status:{}};
})}
async function realm(page){const handle=await page.waitForSelector('#realm'),frame=await handle.contentFrame();await frame.waitForLoadState('domcontentloaded',{timeout:120000});await frame.waitForFunction(({candidate,p13,b0,b1})=>Boolean(window[candidate])&&Boolean(window[p13])&&Boolean(window[b0])&&Boolean(window[b1]),{candidate:contract.candidate.resultGlobal,p13:contract.integration.phase13Bridge,b0:contract.integration.phase24lB0Bridge,b1:contract.integration.phase24lB1Bridge},{timeout:60000});return frame}
async function invoke(frame,globalName,pathName,args=[]){return frame.evaluate(({globalName,pathName,args})=>{let value=window[globalName];for(const part of pathName.split('.'))value=value?.[part];if(typeof value!=='function')return{ok:false,reason:`missing:${globalName}.${pathName}`};try{return value(...args)}catch(error){return{ok:false,reason:String(error?.code||error?.message||error),stack:error?.stack}}},{globalName,pathName,args})}
const p13=(frame,path,...args)=>invoke(frame,contract.integration.phase13Bridge,path,args);
const b0=(frame,path,...args)=>invoke(frame,contract.integration.phase24lB0Bridge,path,args);
const b1=(frame,path,...args)=>invoke(frame,contract.integration.phase24lB1Bridge,path,args);
async function shared(page){return page.evaluate(key=>{const value=window.__P24LB3B_SHARED__,raw=value.slots.get(key)??null;let revision=null,state=null;try{state=raw?JSON.parse(raw):null;revision=state?.saveMeta?.revision??null}catch{}return{raw,revision,state,writes:value.writes.length,reads:value.reads.length,removes:value.removes.length,native:value.native.slice()}},contract.storageKey)}
const neutral=(before,after)=>before.raw===after.raw&&before.revision===after.revision&&before.writes===after.writes;
const same=(left,right)=>JSON.stringify(left)===JSON.stringify(right);
const visible=node=>{if(!node)return false;const rect=node.getBoundingClientRect(),style=getComputedStyle(node);return!node.hidden&&rect.width>0&&rect.height>0&&style.display!=='none'&&style.visibility!=='hidden'};

async function dismissAmbient(frame){for(let count=0;count<60;count++){const result=await frame.evaluate(()=>{const visible=node=>{if(!node)return false;const rect=node.getBoundingClientRect(),style=getComputedStyle(node);return!node.hidden&&rect.width>0&&rect.height>0&&style.display!=='none'&&style.visibility!=='hidden'};const guide=[...document.querySelectorAll('[data-phase24l-b3a-guide]')].find(visible);if(guide){guide.querySelector('[data-phase24l-b3a-guide-close]')?.click();return'guide'}const overlay=[...document.querySelectorAll('[data-overlay]')].filter(visible).at(-1);if(!overlay)return'done';const skip=[...overlay.querySelectorAll('[data-phase13-story="skip"],[data-phase13-tutorial-action="skip"],[data-phase15-tutorial-action="skip"],[data-phase16-tutorial-action="skip"]')].find(visible);if(skip){skip.click();return'skip'}const close=[...overlay.querySelectorAll('[data-modal-close]')].find(visible);if(close){close.click();return'close'}document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));return'escape'});if(result==='done')return true;await frame.waitForTimeout(60)}return false}
async function forceMore(frame){await dismissAmbient(frame);const more=frame.locator('.bottom-nav [data-nav="more"]');if(await more.getAttribute('class').then(value=>value?.split(/\s+/).includes('on')))await frame.locator('.bottom-nav [data-nav="oaths"]').click();await more.click();await frame.waitForSelector(S.more);await frame.waitForTimeout(100);const guide=frame.locator(`${S.more} [data-phase24l-b3a-guide]:not([hidden])`);if(await guide.count())await guide.locator('[data-phase24l-b3a-guide-close]').click();await frame.waitForTimeout(50)}
async function openInventory(frame){await forceMore(frame);await frame.locator(`${S.more} ${S.inventoryOpen}`).click();await frame.waitForSelector(`${S.inventory}:visible`);await frame.waitForTimeout(60)}
async function selectInventoryTab(frame,id){const target=frame.locator(`${S.inventoryTab}[data-phase24l-b3b-category="${id}"]`);if(await target.getAttribute('aria-selected')!=='true')await target.click();await frame.waitForSelector(`${S.inventoryGrid}[data-phase24l-b3b-grid="${id}"]`);await frame.waitForTimeout(30)}
async function collectInventoryCategory(frame,id){await selectInventoryTab(frame,id);const items=[],pages=[];for(let guard=0;guard<20;guard++){const snapshot=await frame.evaluate(({item,grid})=>{const root=document.querySelector(grid),cards=[...document.querySelectorAll(item)].map(node=>({key:node.dataset.phase24lB3bItem,kind:node.dataset.phase24lB3bKind,amount:Number(node.dataset.phase24lB3bAmount),name:node.querySelector('.phase24l-b3b-item-name')?.textContent.trim()})),status=document.querySelector('[data-phase24l-b3b-page-status]')?.textContent.trim(),next=document.querySelector('[data-phase24l-b3b-page-next]');return{category:root?.dataset.phase24lB3bGrid,cards,status,nextDisabled:Boolean(next?.disabled)}},{item:S.inventoryItem,grid:S.inventoryGrid});items.push(...snapshot.cards);pages.push(snapshot);if(snapshot.nextDisabled)break;await frame.locator('[data-phase24l-b3b-page-next]').click();await frame.waitForTimeout(30)}return{items,pages}}
async function closeModal(frame){const close=frame.locator('[data-overlay]:not([hidden]) [data-modal-close]').first();if(await close.count())await close.click();await frame.waitForTimeout(60)}
function modalMetrics(node){const rect=node.getBoundingClientRect(),controls=[...node.querySelectorAll('button,[role="tab"]')].filter(visible),bad=controls.filter(item=>{const value=item.getBoundingClientRect();return value.width<43.9||value.height<43.9});return{rect:{left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom,width:rect.width,height:rect.height},viewport:{width:innerWidth,height:innerHeight},fits:rect.left>=-2&&rect.right<=innerWidth+2&&rect.top>=-2&&rect.bottom<=innerHeight+2,badTargets:bad.map(item=>({text:item.textContent.trim().slice(0,40),rect:(()=>{const r=item.getBoundingClientRect();return{width:r.width,height:r.height}})()})),document:{x:scrollX,y:scrollY,width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight}}}

async function inventoryJourney(page,frame,viewport,step){
  const activation=await b1(frame,'destructive.activate');await frame.waitForTimeout(80);await dismissAmbient(frame);const before=await shared(page);await openInventory(frame);
  const install=await frame.evaluate(({global,result,id})=>{const api=window[global],outcome=window[result],apiDescriptor=Object.getOwnPropertyDescriptor(window,global),resultDescriptor=Object.getOwnPropertyDescriptor(window,result);return{api:{id:api?.id,version:api?.version,frozen:Object.isFrozen(api)},outcome,descriptors:{api:apiDescriptor&&{enumerable:apiDescriptor.enumerable,writable:apiDescriptor.writable,configurable:apiDescriptor.configurable},result:resultDescriptor&&{enumerable:resultDescriptor.enumerable,writable:resultDescriptor.writable,configurable:resultDescriptor.configurable}},id}},{global:contract.candidate.global,result:contract.candidate.resultGlobal,id:contract.candidate.id});
  step('runtime-and-install-result-are-hidden-frozen-and-safe',activation?.ok===true&&install.api.id===contract.candidate.id&&install.api.version===1&&install.api.frozen&&install.outcome?.ok===true&&install.outcome?.saveChanged===false&&install.outcome?.mechanicsChanged===false&&install.descriptors.api?.enumerable===false&&install.descriptors.api?.writable===false&&install.descriptors.result?.enumerable===false&&install.descriptors.result?.writable===false,install);
  const structure=await frame.evaluate(({inventory,tab,launches})=>{const shown=node=>{if(!node)return false;const rect=node.getBoundingClientRect(),style=getComputedStyle(node);return!node.hidden&&rect.width>0&&rect.height>0&&style.display!=='none'&&style.visibility!=='hidden'},metrics=node=>{const rect=node.getBoundingClientRect(),controls=[...node.querySelectorAll('button,[role="tab"]')].filter(shown),bad=controls.filter(item=>{const value=item.getBoundingClientRect();return value.width<43.9||value.height<43.9});return{rect:{left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom,width:rect.width,height:rect.height},viewport:{width:innerWidth,height:innerHeight},fits:rect.left>=-2&&rect.right<=innerWidth+2&&rect.top>=-2&&rect.bottom<=innerHeight+2,badTargets:bad.map(item=>({text:item.textContent.trim().slice(0,40),rect:(()=>{const r=item.getBoundingClientRect();return{width:r.width,height:r.height}})()})),document:{x:scrollX,y:scrollY,width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight}}},modal=document.querySelector(inventory),outer=modal?.closest('.modal'),overlay=modal?.closest('[data-overlay]'),tabs=[...modal?.querySelectorAll(tab)||[]],launch=document.querySelector(launches),launchButtons=[...launch?.querySelectorAll('button')||[]];return{dialog:{role:outer?.getAttribute('role'),modal:outer?.getAttribute('aria-modal'),labelledby:outer?.getAttribute('aria-labelledby')},tabs:tabs.map(node=>({id:node.dataset.phase24lB3bCategory,selected:node.getAttribute('aria-selected'),controls:node.getAttribute('aria-controls'),tabIndex:node.tabIndex})),panels:modal?.querySelectorAll('[role="tabpanel"]').length||0,livePanels:[...modal?.querySelectorAll('[role="tabpanel"]')||[]].filter(shown).length,launches:launchButtons.map(node=>({text:node.textContent.replace(/\s+/g,' ').trim(),width:node.getBoundingClientRect().width,height:node.getBoundingClientRect().height})),overlayVisible:shown(overlay),metrics:metrics(outer)}},{inventory:S.inventory,tab:S.inventoryTab,launches:S.launches});
  step('more-exposes-legacy-and-inventory-as-compact-touch-launches',structure.launches.length===2&&structure.launches.some(item=>item.text.startsWith('LEGACY'))&&structure.launches.some(item=>item.text==='INVENTORY')&&structure.launches.every(item=>item.width>=44&&item.height>=44),structure.launches);
  step('inventory-is-one-bounded-labelled-dialog-with-five-roving-tabs',structure.dialog.role==='dialog'&&structure.dialog.modal==='true'&&structure.tabs.map(item=>item.id).join(',')===contract.inventory.tabs.join(',')&&structure.tabs.filter(item=>item.selected==='true'&&item.tabIndex===0).length===1&&structure.tabs.every(item=>item.controls==='phase24l-b3b-inventory-grid')&&structure.panels===1&&structure.livePanels===1&&structure.overlayVisible&&structure.metrics.fits&&structure.metrics.badTargets.length===0,structure);
  const snapshot=(await p13(frame,'read.snapshot'))?.state;
  const materials=await collectInventoryCategory(frame,'materials'),gifts=await collectInventoryCategory(frame,'gifts'),shards=await collectInventoryCategory(frame,'shards'),relics=await collectInventoryCategory(frame,'relics');await selectInventoryTab(frame,'keepsakes');const keepsakes=await frame.evaluate(()=>({cards:document.querySelectorAll('[data-phase24l-b3b-item]').length,empty:document.querySelector('[data-phase24l-b3b-empty]')?.textContent.replace(/\s+/g,' ').trim(),page:document.querySelector('[data-phase24l-b3b-page-status]')?.textContent.trim()}));
  const expectedMaterials=new Map([['Fellow EXP',snapshot?.experienceProgression?.wallets?.fellow?.balance??0],['Relic Stones',snapshot?.relicStones??0]]),materialTruth=materials.items.length===2&&materials.items.every(item=>expectedMaterials.get(item.name)===item.amount);
  step('materials-are-exactly-shared-fellow-exp-and-relic-stones',materialTruth,{items:materials.items,expected:Object.fromEntries(expectedMaterials)});
  step('gifts-are-one-existing-family-resource',gifts.items.length===1&&gifts.items[0].name===contract.inventory.gift&&gifts.items[0].amount===(snapshot?.gifts??0),{items:gifts.items,expected:snapshot?.gifts});
  const expectedShardKeys=[...Object.keys(snapshot?.fellows||{}).map(id=>`shard.fellow.${id}`),...Object.keys(snapshot?.family||{}).map(id=>`shard.family.${id}`),...Object.keys(snapshot?.companions||{}).map(id=>`shard.companion.${id}`)].sort(),actualShardKeys=shards.items.map(item=>item.key).sort();
  step('all-58-existing-roster-shards-appear-once-across-pages',shards.items.length===contract.inventory.shardCatalogSize&&new Set(actualShardKeys).size===contract.inventory.shardCatalogSize&&same(actualShardKeys,expectedShardKeys)&&shards.pages.every(page=>page.cards.length<=viewport.inventoryPageSize),{actualCount:shards.items.length,expectedCount:expectedShardKeys.length,pageCounts:shards.pages.map(page=>page.cards.length),statuses:shards.pages.map(page=>page.status),duplicates:actualShardKeys.filter((key,index)=>actualShardKeys.indexOf(key)!==index)});
  const expectedRelicKeys=Object.entries(snapshot?.relics||{}).filter(([,item])=>item?.owned===true).map(([id])=>`relic.${id}`).sort(),actualRelicKeys=relics.items.map(item=>item.key).sort();
  step('relics-project-owned-one-copy-items-only',same(actualRelicKeys,expectedRelicKeys)&&relics.items.every(item=>item.amount===1),{actual:actualRelicKeys,expected:expectedRelicKeys});
  step('keepsakes-are-truthfully-empty-without-fabricated-authority',keepsakes.cards===0&&keepsakes.empty?.includes(contract.inventory.emptyKeepsakes)&&keepsakes.page==='Page 1 of 1 · 0 items',keepsakes);
  await selectInventoryTab(frame,'materials');const tabs=frame.locator(S.inventoryTab),first=tabs.first();await first.focus();await first.press('ArrowRight');await frame.waitForTimeout(40);const keyboard=await frame.evaluate(tab=>({active:document.activeElement?.dataset.phase24lB3bCategory,selected:[...document.querySelectorAll(tab)].filter(node=>node.getAttribute('aria-selected')==='true').map(node=>node.dataset.phase24lB3bCategory),tabStops:[...document.querySelectorAll(tab)].filter(node=>node.tabIndex===0).map(node=>node.dataset.phase24lB3bCategory)}),S.inventoryTab);step('inventory-tabs-support-arrow-key-roving-focus',keyboard.active==='gifts'&&same(keyboard.selected,['gifts'])&&same(keyboard.tabStops,['gifts']),keyboard);
  await selectInventoryTab(frame,'materials');await frame.locator(S.inventoryItem).first().click();await frame.waitForSelector(S.inventoryDetail);const detailBefore=await shared(page);await frame.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true})));await frame.waitForTimeout(50);const detail=await frame.evaluate(({detail,inventory})=>({detail:document.querySelectorAll(detail).length,inventory:document.querySelectorAll(inventory).length}),{detail:S.inventoryDetail,inventory:S.inventory}),detailAfter=await shared(page);step('escape-closes-item-detail-before-inventory-dialog',detail.detail===0&&detail.inventory===1&&neutral(detailBefore,detailAfter),{detail,before:{revision:detailBefore.revision,writes:detailBefore.writes},after:{revision:detailAfter.revision,writes:detailAfter.writes}});
  await closeModal(frame);const after=await shared(page),focus=await frame.evaluate(()=>({inventory:document.querySelectorAll('[data-phase24l-b3b-inventory]').length,active:document.activeElement?.dataset.phase24lB3bInventoryOpen!==undefined}));step('all-inventory-presentation-actions-are-byte-revision-write-neutral-and-return-focus',neutral(before,after)&&focus.inventory===0&&focus.active,{before:{revision:before.revision,writes:before.writes},after:{revision:after.revision,writes:after.writes},focus});
}

async function legacyJourney(page,frame,step){
  const reset=await b0(frame,'destructive.resetDirectFresh'),oath=await p13(frame,'destructive.event','oath.first-completed',{}),derived=await p13(frame,'read.derive'),oathClaim=derived?.claims?.find(item=>item.sourceId==='legacy.oathkeeper.tier-1');
  step('mixed-legacy-fixture-setup-operations-succeed',reset?.ok===true&&oath?.ok===true&&Boolean(oathClaim),{reset:{ok:reset?.ok,error:reset?.error,reason:reset?.reason},oath:{ok:oath?.ok,reason:oath?.reason},oathClaim:oathClaim?.id});
  await frame.waitForTimeout(80);await dismissAmbient(frame);await forceMore(frame);await frame.waitForTimeout(500);await dismissAmbient(frame);await forceMore(frame);const before=await shared(page),invoker=frame.locator(`${S.more} [data-phase13-legacy]`);await invoker.focus();await invoker.click();await frame.waitForSelector(S.legacy);await frame.waitForTimeout(100);
  const structure=await frame.evaluate(({legacy,tab,panel,allowed,forbidden})=>{const shown=node=>{if(!node)return false;const rect=node.getBoundingClientRect(),style=getComputedStyle(node);return!node.hidden&&rect.width>0&&rect.height>0&&style.display!=='none'&&style.visibility!=='hidden'},metrics=node=>{const rect=node.getBoundingClientRect(),controls=[...node.querySelectorAll('button,[role="tab"]')].filter(shown),bad=controls.filter(item=>{const value=item.getBoundingClientRect();return value.width<43.9||value.height<43.9});return{rect:{left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom,width:rect.width,height:rect.height},viewport:{width:innerWidth,height:innerHeight},fits:rect.left>=-2&&rect.right<=innerWidth+2&&rect.top>=-2&&rect.bottom<=innerHeight+2,badTargets:bad.map(item=>({text:item.textContent.trim().slice(0,40),rect:(()=>{const r=item.getBoundingClientRect();return{width:r.width,height:r.height}})()})),document:{x:scrollX,y:scrollY,width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight}}},shell=document.querySelector(legacy),modal=shell?.closest('.modal'),tabs=[...shell?.querySelectorAll(tab)||[]],panels=[...shell?.querySelectorAll(panel)||[]],cards=[...shell?.querySelectorAll('[data-phase22b-legacy-category]')||[]].map(node=>({category:node.dataset.phase22bLegacyCategory,state:node.dataset.phase22bLegacyState,source:node.dataset.phase22bLegacySource||null,claimButtons:node.querySelectorAll('[data-phase13-claim]').length,text:node.textContent.replace(/\s+/g,' ').trim()})),allText=shell?.textContent.toLowerCase()||'';return{modal:{role:modal?.getAttribute('role'),ariaModal:modal?.getAttribute('aria-modal')},tabs:tabs.map(node=>({id:node.dataset.phase24lB3bLegacyTab,selected:node.getAttribute('aria-selected'),controls:node.getAttribute('aria-controls'),tabIndex:node.tabIndex,width:node.getBoundingClientRect().width,height:node.getBoundingClientRect().height})),panels:panels.length,livePanels:panels.filter(shown).length,cards,unknownClaims:cards.filter(card=>card.claimButtons&&!allowed.includes(card.source)),forbidden:forbidden.filter(term=>allText.includes(term.toLowerCase())),metrics:metrics(modal)}},{legacy:S.legacy,tab:S.legacyTab,panel:S.legacyPanel,allowed:contract.legacy.allowedClaimSources,forbidden:contract.legacy.forbiddenClaimTerms});
  const tabCards=[];for(const id of contract.legacy.tabs){await frame.locator(`${S.legacyTab}[data-phase24l-b3b-legacy-tab="${id}"]`).click();await frame.waitForTimeout(25);tabCards.push(...await frame.evaluate(({panel,id})=>[...document.querySelector(panel)?.children||[]].filter(node=>node.matches('[data-phase22b-legacy-category]')).map(node=>({tab:id,category:node.dataset.phase22bLegacyCategory,state:node.dataset.phase22bLegacyState,source:node.dataset.phase22bLegacySource||null,claimButtons:node.querySelectorAll('[data-phase13-claim]').length,text:node.textContent.replace(/\s+/g,' ').trim()})),{panel:S.legacyPanel,id}))}
  const counts=Object.fromEntries(contract.legacy.tabs.map(id=>[id,tabCards.filter(card=>card.tab===id).length]));
  step('mixed-legacy-fixture-is-authentic',reset?.ok===true&&oath?.ok===true&&Boolean(oathClaim),{reset:reset?.ok,oath:oath?.ok,oathClaim:oathClaim?.id});
  step('legacy-is-one-bounded-labelled-dialog-with-four-roving-tabs',structure.modal.role==='dialog'&&structure.modal.ariaModal==='true'&&structure.tabs.map(item=>item.id).join(',')===contract.legacy.tabs.join(',')&&structure.tabs.filter(item=>item.selected==='true'&&item.tabIndex===0).length===1&&structure.tabs.every(item=>item.controls==='phase24l-b3b-legacy-panel'&&item.width>=44&&item.height>=44)&&structure.panels===1&&structure.livePanels===1&&structure.metrics.fits&&structure.metrics.badTargets.length===0,{structure,counts});
  const unknownClaims=tabCards.filter(card=>card.claimButtons&&!contract.legacy.allowedClaimSources.includes(card.source)),forbidden=contract.legacy.forbiddenClaimTerms.filter(term=>tabCards.some(card=>card.text.toLowerCase().includes(term.toLowerCase())));
  step('legacy-groups-track-feat-ready-and-empty-history-with-one-live-panel',counts.tracks===1&&counts.feats===1&&counts.ready===1&&counts.history===0,{counts,cards:tabCards});
  step('legacy-exposes-only-three-established-phase13-sources-and-no-phase18-or-phase19-claims',unknownClaims.length===0&&forbidden.length===0&&tabCards.filter(card=>card.claimButtons).every(card=>card.tab==='ready'&&card.category==='claim'&&card.state==='ready'),{unknownClaims,forbidden,cards:tabCards});
  const tracks=frame.locator(`${S.legacyTab}[data-phase24l-b3b-legacy-tab="tracks"]`);await tracks.click();await tracks.focus();await tracks.press('ArrowRight');await frame.waitForTimeout(40);const keyboard=await frame.evaluate(({tab,panel})=>{const selected=[...document.querySelectorAll(tab)].filter(node=>node.getAttribute('aria-selected')==='true'),panels=[...document.querySelectorAll(panel)];return{active:document.activeElement?.dataset.phase24lB3bLegacyTab,selected:selected.map(node=>node.dataset.phase24lB3bLegacyTab),tabStops:[...document.querySelectorAll(tab)].filter(node=>node.tabIndex===0).map(node=>node.dataset.phase24lB3bLegacyTab),panels:panels.length,labelledby:panels[0]?.getAttribute('aria-labelledby'),category:panels[0]?.dataset.phase24lB3bLegacyPanel,children:panels[0]?.children.length}} ,{tab:S.legacyTab,panel:S.legacyPanel});step('legacy-tabs-support-arrow-key-roving-focus-and-one-live-panel',keyboard.active==='feats'&&same(keyboard.selected,['feats'])&&same(keyboard.tabStops,['feats'])&&keyboard.panels===1&&keyboard.labelledby==='phase24l-b3b-legacy-tab-feats'&&keyboard.category==='feats'&&keyboard.children===1,keyboard);
  await frame.locator(`${S.legacyTab}[data-phase24l-b3b-legacy-tab="ready"]`).click();await frame.waitForTimeout(40);const presentationAfter=await shared(page);step('legacy-navigation-is-byte-revision-write-neutral',neutral(before,presentationAfter),{before:{revision:before.revision,writes:before.writes},after:{revision:presentationAfter.revision,writes:presentationAfter.writes}});
  await closeModal(frame);const closeFocus=await frame.evaluate(()=>({legacy:document.querySelectorAll('[data-phase24l-b3b-legacy]').length,active:document.activeElement?.matches?.('[data-phase13-legacy]')===true}));step('explicit-legacy-close-removes-dialog-and-restores-launch-focus',closeFocus.legacy===0&&closeFocus.active,closeFocus);await frame.locator(`${S.more} [data-phase13-legacy]`).click();await frame.waitForSelector(S.legacy);await frame.waitForTimeout(80);await frame.locator(`${S.legacyTab}[data-phase24l-b3b-legacy-tab="ready"]`).click();
  const claimLocator=frame.locator(`${S.legacyPanel} [data-phase13-claim]`).first(),claimId=await claimLocator.getAttribute('data-phase13-claim'),handle=await claimLocator.elementHandle(),claimBefore=await shared(page);await claimLocator.click();await frame.waitForTimeout(180);const claimAfter=await shared(page),post=await p13(frame,'read.derive'),claimed=post?.claims?.find(item=>item.id===claimId);await dismissAmbient(frame);await forceMore(frame);await frame.locator(`${S.more} [data-phase13-legacy]`).click();await frame.waitForSelector(S.legacy);await frame.waitForTimeout(80);const postCounts={};for(const id of ['ready','history']){await frame.locator(`${S.legacyTab}[data-phase24l-b3b-legacy-tab="${id}"]`).click();await frame.waitForTimeout(25);postCounts[id]=await frame.locator(`${S.legacyPanel} [data-phase22b-legacy-category]`).count()}
  step('real-manual-legacy-claim-commits-once-and-refreshes-tabs',Boolean(claimId)&&claimAfter.raw!==claimBefore.raw&&claimAfter.revision>claimBefore.revision&&claimAfter.writes>claimBefore.writes&&claimed?.status==='claimed'&&claimed?.receiptCount===1&&postCounts.ready===0&&postCounts.history===1,{claimId,before:{revision:claimBefore.revision,writes:claimBefore.writes},after:{revision:claimAfter.revision,writes:claimAfter.writes},claimed,postCounts});
  const retryBefore=await shared(page);if(handle)await handle.evaluate(node=>node.click());await frame.waitForTimeout(100);const retryAfter=await shared(page),retryDerived=await p13(frame,'read.derive'),retryClaim=retryDerived?.claims?.find(item=>item.id===claimId);step('detached-claim-control-retry-is-exactly-once-and-write-neutral',neutral(retryBefore,retryAfter)&&retryClaim?.status==='claimed'&&retryClaim?.receiptCount===1,{claimId,before:{revision:retryBefore.revision,writes:retryBefore.writes},after:{revision:retryAfter.revision,writes:retryAfter.writes},retryClaim});
  await closeModal(frame);await dismissAmbient(frame);
}

function watchPage(page){const errors=[],requests=[];page.setDefaultTimeout(30000);page.on('pageerror',error=>errors.push(`pageerror:${error.stack||error.message}`));page.on('console',message=>{if(['warning','error'].includes(message.type()))errors.push(`console.${message.type()}:${message.text()}`)});page.on('response',response=>{if(response.status()>=400)requests.push(`${response.status()}:${response.url()}`)});page.on('requestfailed',request=>requests.push(`${request.url()}:${request.failure()?.errorText||'failed'}`));return{errors,requests}}
async function viewportJourney(browser,baseURL,viewport){const step=(id,pass,detail='')=>record(`${viewport.id}-${id}`,pass,detail);let context,page,frame;try{context=await browser.newContext({viewport:{width:viewport.width,height:viewport.height},reducedMotion:'reduce'});await installMemoryRuntime(context);page=await context.newPage();const watch=watchPage(page);const response=await page.goto(`${baseURL}/__phase24l_b3b_host__.html`,{waitUntil:'domcontentloaded',timeout:120000});frame=await realm(page);await frame.waitForTimeout(300);await dismissAmbient(frame);step('candidate-loads-successfully',response?.ok()===true,response?.status());await legacyJourney(page,frame,step);await inventoryJourney(page,frame,viewport,step);const final=await shared(page);step('isolated-realm-never-accesses-native-web-storage',final.native.length===0,final.native);step('journey-has-zero-warning-error-or-request-failures',watch.errors.length===0&&watch.requests.length===0,watch)}catch(error){let diagnostic=null;try{diagnostic=await frame?.evaluate(()=>({url:location.href,ready:document.readyState,text:document.body?.innerText?.replace(/\s+/g,' ').trim().slice(0,1800),modal:document.querySelector('.modal')?.innerText?.replace(/\s+/g,' ').trim().slice(0,1200)}))}catch{}step('journey-fatal',false,{error:error.stack||error.message,diagnostic})}if(context)await context.close()}

const WORKER_FLAG='EVERSTEAD_PHASE24L_B3B_BROWSER_WORKER';
const PLAYWRIGHT_MODULE=process.env.EVERSTEAD_PLAYWRIGHT_MODULE||'playwright';
const progress=message=>console.error(`[phase24l-b3b] ${new Date().toISOString()} ${message}`);
const bounded=(promise,ms,label)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`${label} timed out after ${ms}ms`)),ms);Promise.resolve(promise).then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})});
async function runWorker(){const instance=server();let browser;try{const baseURL=await bounded(listen(instance),10000,'HTTP server startup');progress(`server ready at ${baseURL}; loading Chromium`);const {chromium}=await import(PLAYWRIGHT_MODULE);browser=await chromium.launch({headless:true,timeout:45000});const selected=process.env.EVERSTEAD_PHASE24L_B3B_VIEWPORT,viewports=selected?contract.viewports.filter(item=>item.id===selected):contract.viewports;if(!viewports.length)throw new Error(`Unknown Phase 24L-B3B viewport: ${selected}`);for(const viewport of viewports){progress(`running ${viewport.id}`);await viewportJourney(browser,baseURL,viewport)}}catch(error){record('browser-suite-fatal',false,error.stack||error.message)}finally{if(browser)try{await bounded(browser.close(),15000,'Chromium shutdown')}catch(error){record('browser-shutdown-fatal',false,error.stack||error.message)}instance.closeAllConnections?.();if(instance.listening)try{await bounded(new Promise((resolve,reject)=>instance.close(error=>error?reject(error):resolve())),10000,'HTTP server shutdown')}catch(error){record('server-shutdown-fatal',false,error.stack||error.message)}}const failed=rows.filter(row=>!row.pass);for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` · ${row.detail}`:''}`);console.log(`RESULT ${rows.length-failed.length} passed, ${failed.length} failed`);if(failed.length)process.exitCode=1}
async function supervise(){progress(`starting supervised browser worker (hard timeout ${contract.limits.browserHardTimeoutMs/60000} minutes)`);const child=spawn(process.execPath,[fileURLToPath(import.meta.url)],{cwd:process.cwd(),env:{...process.env,[WORKER_FLAG]:'1'},stdio:'inherit'});let timedOut=false,forceTimer;const hardTimer=setTimeout(()=>{timedOut=true;progress('browser worker exceeded hard timeout; terminating it');child.kill('SIGTERM');forceTimer=setTimeout(()=>child.kill('SIGKILL'),5000);forceTimer.unref?.()},contract.limits.browserHardTimeoutMs);const result=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',(code,signal)=>resolve({code,signal}))});clearTimeout(hardTimer);if(forceTimer)clearTimeout(forceTimer);if(timedOut){console.error('FAIL browser-suite-hard-timeout');process.exitCode=1;return}if(result.signal){console.error(`FAIL browser-worker-signal · ${result.signal}`);process.exitCode=1;return}process.exitCode=result.code??1}
if(process.env[WORKER_FLAG]==='1')await runWorker();else await supervise();
