(() => {
  'use strict';
  const CHANNEL='everstead-phase-10a',inlineJson=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  function installRuntime(config){
    const slots=new Map(Object.entries(config.slots)),nativeSetTimeout=window.setTimeout.bind(window),nativeClearTimeout=window.clearTimeout.bind(window);let saveIndex=0,transactionIndex=0;
    const nativeStorageAccesses=[],errors=[];let nativeStorageInstrumented=false;try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    window.__PHASE_10A_CONFIG__=config;window.__PHASE_10A_SLOTS__=slots;window.__PHASE_10A_ERRORS__=errors;window.__PHASE_10A_NATIVE_STORAGE_ACCESSES__=nativeStorageAccesses;window.__PHASE_10A_NATIVE_STORAGE_INSTRUMENTED__=nativeStorageInstrumented;
    window.matchMedia=query=>({matches:query==='(prefers-reduced-motion: reduce)'&&config.motion==='reduced-motion',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return true}});
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>slots.set(String(key),String(value)),removeItem:key=>slots.delete(String(key))},runtime={storage:memoryStorage,clock:{now:()=>config.now,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.5,confirm:()=>true,ids:{save:()=>config.saveId??`save-p10a-browser-${++saveIndex}`,transaction:()=>`tx-p10a-browser-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
    window.__EVERSTEAD_RUNTIME__=runtime;
  }
  function runSuite(){
    const channel='everstead-phase-10a',config=window.__PHASE_10A_CONFIG__,slots=window.__PHASE_10A_SLOTS__,results=[],add=(id,pass,detail='')=>results.push({id,pass:Boolean(pass),detail:String(detail)}),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),send=()=>parent.postMessage({channel,nonce:config.nonce,results,errors:window.__PHASE_10A_ERRORS__.slice(),slots:Object.fromEntries(slots)},'*'),snapshot=()=>window.__EVERSTEAD_QA__.snapshot().state,activeRaw=()=>slots.get(config.keys.active)??null;
    const prepare=bridge=>{bridge.controls.grant({resource:'gold',amount:1000000000});bridge.controls.grant({resource:'fellowExp',id:'cael',amount:1000000});for(let stage=1;stage<=6;stage++){const result=bridge.act('campaign-run',{id:`broken-roads-${stage}`});if(!result.ok)throw new Error(`Campaign setup failed at ${stage}`)}for(const id of ['bramble','cinderwing'])bridge.controls.grant({resource:'companionExp',id,amount:1000000});const tower=bridge.act('companion-tower-clear'),expedition=bridge.act('fellow-expedition-push');if(!tower.ok||!expedition.ok)throw new Error(`Idle setup failed: tower=${tower.ok} expedition=${expedition.ok}`)};
    (async()=>{await wait(500);const bridge=window.__EVERSTEAD_QA__;add('bridge-present',Boolean(bridge));add('viewport-exact',innerWidth===config.viewport.width&&innerHeight===config.viewport.height,`${innerWidth}x${innerHeight}`);add('no-horizontal-overflow-initial',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);add('native-storage-instrumented',window.__PHASE_10A_NATIVE_STORAGE_INSTRUMENTED__===true);prepare(bridge);const base=snapshot(),baseTower=base.companionTower.idle,baseExpedition=base.fellowExpedition.idle;add('schema10-progressed-ready',base.schemaVersion===10&&base.companionTower.highestFloor===1&&base.fellowExpedition.highestStage>0);add('initial-cursors-shared',baseTower.cursorAt===config.now&&baseExpedition.cursorAt===config.now);config.now+=3600000;
      const routeTower=bridge.act('adventure',{tab:'companionTower'}),settled=snapshot();document.querySelector('[data-nav="adventure"]')?.click();await wait(20);add('tower-route-opens',routeTower.ok&&settled.ui.adventure==='companionTower');add('shared-captured-clock',settled.companionTower.idle.cursorAt===config.now&&settled.fellowExpedition.idle.cursorAt===config.now);add('settled-once-each',settled.companionTower.idle.segments.reduce((n,item)=>n+item.elapsedMs,0)===3600000&&settled.fellowExpedition.idle.segments.reduce((n,item)=>n+item.elapsedMs,0)===3600000);add('preview-does-not-claim',settled.companionTower.idle.claimOrdinal===0&&settled.fellowExpedition.idle.claimOrdinal===0);const towerText=document.body.innerText;add('tower-preview-visible',towerText.includes('1 interval ready')&&towerText.includes('CLAIM TOWER REWARDS'),towerText.slice(-500));const towerButton=document.querySelector('[data-companion-tower-claim]');towerButton?.click();await wait(20);const afterTower=snapshot(),towerReceipt=afterTower.companionTower.idle.lastReceipt;add('tower-production-button',Boolean(towerButton));add('tower-claim-exact',towerReceipt?.intervalOrdinalEnd-towerReceipt?.intervalOrdinalStart===1&&afterTower.companionTower.idle.claimOrdinal===1);add('tower-preserves-expedition-history',afterTower.fellowExpedition.idle.claimOrdinal===0&&afterTower.fellowExpedition.idle.intervalOrdinal===0);const afterTowerRaw=activeRaw(),towerRevision=afterTower.saveMeta.revision;document.querySelector('[data-companion-tower-claim]')?.click();await wait(20);const towerRepeat=snapshot();add('tower-repeat-no-save',activeRaw()===afterTowerRaw&&towerRepeat.saveMeta.revision===towerRevision&&towerRepeat.companionTower.idle.claimOrdinal===1);
      document.querySelector('[data-adventure="fellowExpedition"]')?.click();await wait(20);const expeditionText=document.body.innerText;add('expedition-preview-visible',expeditionText.includes('1 interval ready')&&expeditionText.includes('CLAIM EXPEDITION REWARDS'),expeditionText.slice(-500));const expeditionButton=document.querySelector('[data-expedition-claim]');expeditionButton?.click();await wait(20);const afterExpedition=snapshot(),expeditionReceipt=afterExpedition.fellowExpedition.idle.lastReceipt;add('expedition-production-button',Boolean(expeditionButton));add('expedition-claim-exact',expeditionReceipt?.intervalOrdinalEnd-expeditionReceipt?.intervalOrdinalStart===1&&afterExpedition.fellowExpedition.idle.claimOrdinal===1);add('expedition-preserves-tower-history',JSON.stringify(afterExpedition.companionTower.idle)===JSON.stringify(afterTower.companionTower.idle));const afterExpeditionRaw=activeRaw(),expeditionRevision=afterExpedition.saveMeta.revision;document.querySelector('[data-expedition-claim]')?.click();await wait(20);const expeditionRepeat=snapshot();add('expedition-repeat-no-save',activeRaw()===afterExpeditionRaw&&expeditionRepeat.saveMeta.revision===expeditionRevision&&expeditionRepeat.fellowExpedition.idle.claimOrdinal===1);
      const reload=bridge.recovery.reload();await wait(20);const reloaded=snapshot();add('reload-committed-receipts',reload.ok&&reloaded.companionTower.idle.claimOrdinal===1&&reloaded.fellowExpedition.idle.claimOrdinal===1&&reloaded.companionTower.idle.lastReceipt&&reloaded.fellowExpedition.idle.lastReceipt);add('reload-no-staging',!slots.has(config.keys.staging));add('no-horizontal-overflow-final',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);add('zero-native-storage-calls',window.__PHASE_10A_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_10A_NATIVE_STORAGE_ACCESSES__.join(','));add('realm-zero-errors',window.__PHASE_10A_ERRORS__.length===0,window.__PHASE_10A_ERRORS__.join('\n'));add('motion-mode-active',config.motion==='reduced-motion'?matchMedia('(prefers-reduced-motion: reduce)').matches:!matchMedia('(prefers-reduced-motion: reduce)').matches);send()})().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }
  let loaderNonce='unknown';(async()=>{const config=JSON.parse(window.name);loaderNonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error('index.html: HTTP '+response.status);const source=await response.text(),firstScript=source.indexOf('<script>');if(firstScript<0)throw new Error('Production script is missing');const bootstrap='<script>('+installRuntime.toString()+')('+inlineJson(config)+')<\/script>',suite='<script>('+runSuite.toString()+')()<\/script>',instrumented=source.slice(0,firstScript)+bootstrap+source.slice(firstScript).replace('</body>',suite+'</body>');document.open();document.write(instrumented);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce:loaderNonce,results:[{id:'realm-loader-fatal',pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
