import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve(new URL('../..',import.meta.url).pathname),read=path=>readFileSync(resolve(root,path)),hash=value=>createHash('sha256').update(value).digest('hex'),rows=[],check=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:String(detail)}),publishedHead='068a5a3ea2d9b3b339e96bf3fed0a0c945cf62a5';
const current=read('index.html').toString('utf8'),published=execFileSync('git',['show',`${publishedHead}:index.html`],{cwd:root,encoding:'utf8',maxBuffer:32*1024*1024}),currentLines=current.split('\n'),publishedLines=published.split('\n'),changed=[];for(let index=0;index<Math.max(currentLines.length,publishedLines.length);index++)if(currentLines[index]!==publishedLines[index])changed.push({line:index+1,before:publishedLines[index],after:currentLines[index]});
check('phase9-artifact-preimage',hash(published)==='1e9d22150a5a0d2b2b4fbec403a5a50bf81c3b22153e688b659bda9b6bc67529',hash(published));
check('phase10a-two-line-successor',changed.length===2,changed.length);
check('phase10a-only-tower-guard',changed.some(item=>item.before?.includes('state?.schemaVersion!==8')&&item.after?.includes('![8,9,10].includes(state?.schemaVersion)')&&item.after.includes('settleCompanionTowerElapsedThroughSix')));
check('phase10a-only-expedition-guard',changed.some(item=>item.before?.includes('state?.schemaVersion!==8')&&item.after?.includes('![8,9,10].includes(state?.schemaVersion)')&&item.after.includes('settleFellowExpeditionElapsed')));
check('phase9-schema-still-10',current.includes('CURRENT_SCHEMA_VERSION=10;')&&!current.includes('CURRENT_SCHEMA_VERSION=11'));
const historicalPaths=['docs/PHASE_9_IMPLEMENTATION_CONTRACT.md','docs/PHASE_9_EXECUTION.md','docs/PHASE_9_RESULT.md',...['README.md','build-contract.mjs','checksums.sha256','current-manifest.json','index.html','realm.html','realm.js','regress-phase-8.mjs','runner.js','scenarios.json','verify.mjs'].map(name=>'qa/phase-9/'+name)];for(const path of historicalPaths){const expected=execFileSync('git',['show',`${publishedHead}:${path}`],{cwd:root,maxBuffer:32*1024*1024});check('phase9-byte-frozen-'+path,hash(read(path))===hash(expected),path)}
const checksumLines=read('qa/phase-9/checksums.sha256').toString('utf8').trim().split('\n'),checksumResults=checksumLines.map(row=>{const [expected,path]=row.split(/\s{2}/);return{path,pass:hash(read(path))===expected}});check('phase9-checksum-entry-count',checksumResults.length===14,checksumResults.length);check('phase9-checksums-13-of-14',checksumResults.filter(item=>item.pass).length===13,JSON.stringify(checksumResults.filter(item=>!item.pass)));check('phase9-only-artifact-superseded',JSON.stringify(checksumResults.filter(item=>!item.pass).map(item=>item.path))===JSON.stringify(['index.html']),JSON.stringify(checksumResults.filter(item=>!item.pass)));
const failures=rows.filter(row=>!row.pass);console.log(JSON.stringify({total:rows.length,passed:rows.length-failures.length,failed:failures.length,failures},null,2));if(failures.length)process.exitCode=1;
