(() => {
  'use strict';
  const CHANNEL='everstead-phase-10a',byId=id=>document.getElementById(id),result=(id,pass,detail='')=>({id,pass:Boolean(pass),detail:String(detail)}),escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),hex=bytes=>[...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,'0')).join(''),sha256=async bytes=>hex(await crypto.subtle.digest('SHA-256',bytes)),decode=bytes=>new TextDecoder('utf-8',{fatal:true}).decode(bytes);
  async function bytes(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return new Uint8Array(await response.arrayBuffer())}
  async function loadContract(){const manifest=JSON.parse(decode(await bytes('./current-manifest.json'))),scenarioBytes=await bytes('./scenarios.json'),scenarios=JSON.parse(decode(scenarioBytes));if(await sha256(scenarioBytes)!==manifest.scenarios.sha256)throw new Error('Scenario checksum mismatch');const staticResults=[result('frozen-history-manifest',Object.keys(manifest.frozenHistoricalFiles).length===188,Object.keys(manifest.frozenHistoricalFiles).length)],artifactBytes=await bytes('../../index.html'),artifactHash=await sha256(artifactBytes);if(artifactHash!==manifest.artifact.sha256||artifactBytes.byteLength!==manifest.artifact.byteLength)throw new Error('Artifact checksum mismatch');staticResults.push(result('artifact-checksum',true,artifactHash));return{manifest,scenarios,staticResults}}
  function executeRealm(contract,viewport,motion){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),config={nonce,viewport,motion,now:Date.parse(contract.scenarios.frozenNow),keys:contract.scenarios.storageKeys,slots:{}};frame.name=JSON.stringify(config);frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0`;const finish=(error,value)=>{clearTimeout(timeout);removeEventListener('message',onMessage);frame.remove();error?reject(error):resolve(value)},onMessage=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=event.data.results.map(item=>({...item,id:`${viewport.id}-${motion}-${item.id}`}));if(event.data.errors?.length)rows.push(result(`${viewport.id}-${motion}-captured-errors`,false,event.data.errors.join('\n')));finish(null,rows)},timeout=setTimeout(()=>finish(new Error(`${viewport.id}/${motion} timed out`)),90000);addEventListener('message',onMessage);frame.src=`./realm.html?qa=1&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  function render(rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)}${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_10A_RESULT__={passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const data=await loadContract(),rows=[...data.staticResults];for(const viewport of data.scenarios.viewports)for(const motion of data.scenarios.motionModes)rows.push(...await executeRealm(data,viewport,motion));render(rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render([result('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
