import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import vm from 'node:vm';

const repoRoot=resolve(new URL('../..',import.meta.url).pathname),read=path=>readFileSync(resolve(repoRoot,path));
const artifact=read('index.html'),source=artifact.toString('utf8'),published=execFileSync('git',['show','068a5a3ea2d9b3b339e96bf3fed0a0c945cf62a5:index.html'],{cwd:repoRoot,encoding:'utf8',maxBuffer:32*1024*1024});
const sha256=value=>createHash('sha256').update(value).digest('hex'),clone=value=>JSON.parse(JSON.stringify(value)),rows=[],check=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:String(detail)});
const line=(text,prefix)=>{const found=text.split('\n').find(value=>value.startsWith(prefix));if(!found)throw new Error(`Missing ${prefix}`);return found};
const originalTower=line(source,'function settleCompanionTowerElapsed('),currentTower=line(source,'settleCompanionTowerElapsed=function('),publishedTower=line(published,'settleCompanionTowerElapsed=function('),currentExpedition=line(source,'function settleFellowExpeditionElapsed('),publishedExpedition=line(published,'function settleFellowExpeditionElapsed(');
function settlementRuntime(towerLine,expeditionLine,{refuseSafeAdd=false}={}){const context={COMPANION_TOWER_CONFIG:{elapsedCapMs:86400000},FELLOW_EXPEDITION_CONFIG:{elapsedCapMs:86400000},towerTick:value=>Math.floor(value),expeditionTick:value=>Math.floor(value),towerSegmentsElapsed:segments=>segments.reduce((sum,item)=>sum+item.elapsedMs,0),expeditionSegmentsElapsed:segments=>segments.reduce((sum,item)=>sum+item.elapsedMs,0),safeAddInteger:(left,right,label)=>{if(refuseSafeAdd)throw new Error(`refused ${label}`);const result=left+right;if(!Number.isSafeInteger(result))throw new Error(label);return result},S:null};vm.createContext(context);vm.runInContext(originalTower,context);vm.runInContext(`const settleCompanionTowerElapsedThroughSix=settleCompanionTowerElapsed;${towerLine}`,context);vm.runInContext(expeditionLine,context);return context}
const releasedRuntime=settlementRuntime(publishedTower,publishedExpedition),currentRuntime=settlementRuntime(currentTower,currentExpedition),clean=value=>JSON.parse(JSON.stringify(value));
const directState=(version,{floor=2,stage=3,cursor=1000,towerSegments=[],expeditionSegments=[]}={})=>({schemaVersion:version,companionTower:{highestFloor:floor,idle:{cursorAt:cursor,segments:clean(towerSegments)}},fellowExpedition:{highestStage:stage,idle:{cursorAt:cursor,segments:clean(expeditionSegments)}}});
const settle=(runtime,lane,state,at)=>{const fn=lane==='tower'?'settleCompanionTowerElapsed':'settleFellowExpeditionElapsed',draft=clean(state),result=runtime[fn](at,draft);return{result:clean(result),state:draft}};
const same=(left,right)=>JSON.stringify(left)===JSON.stringify(right),assets=text=>[...text.matchAll(/data:image\/[^;"']+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]);

check('artifact-repair-sha',sha256(artifact)==='717160cdddc5fa540532cdebd29f30d127ded2f761edd677684a2609fde9a4ed',sha256(artifact));
check('artifact-repair-bytes',artifact.length===18916682,artifact.length);
check('published-preimage-sha',sha256(published)==='1e9d22150a5a0d2b2b4fbec403a5a50bf81c3b22153e688b659bda9b6bc67529',sha256(published));
check('schema-remains-10',source.includes('CURRENT_SCHEMA_VERSION=10;')&&!source.includes('CURRENT_SCHEMA_VERSION=11'));
check('twelve-slots-retained',source.includes("PRE_V10_BACKUP_KEY=NS+'__raw_backup_v9'")&&!source.includes('PRE_V11_BACKUP_KEY'));
check('tower-guard-exact',currentTower.includes('if(![8,9,10].includes(state?.schemaVersion))return settleCompanionTowerElapsedThroughSix'));
check('expedition-guard-exact',currentExpedition.includes('if(![8,9,10].includes(state?.schemaVersion))return{elapsed:0,credited:0,discarded:0}'));
const currentAssets=assets(source),publishedAssets=assets(published);check('embedded-assets-count',currentAssets.length===publishedAssets.length,currentAssets.length);check('embedded-assets-byte-exact',same(currentAssets,publishedAssets));

for(const version of [7,8])check(`tower-released-parity-schema-${version}`,same(settle(currentRuntime,'tower',directState(version),5000),settle(releasedRuntime,'tower',directState(version),5000)));
check('expedition-released-parity-schema-8',same(settle(currentRuntime,'expedition',directState(8),5000),settle(releasedRuntime,'expedition',directState(8),5000)));
for(const version of [7,8,9,10]){const result=settle(currentRuntime,'tower',directState(version),5000);check(`tower-schema-${version}-eligible`,result.result.elapsed===4000&&result.result.credited===4000&&result.result.discarded===0&&result.state.companionTower.idle.cursorAt===5000&&result.state.companionTower.idle.segments[0].elapsedMs===4000,result)}
for(const version of [8,9,10]){const result=settle(currentRuntime,'expedition',directState(version),5000);check(`expedition-schema-${version}-eligible`,result.result.elapsed===4000&&result.result.credited===4000&&result.result.discarded===0&&result.state.fellowExpedition.idle.cursorAt===5000&&result.state.fellowExpedition.idle.segments[0].elapsedMs===4000,result)}
for(const version of [0,1,2,3,4,5,6,11]){const state=directState(version),result=settle(currentRuntime,'tower',state,5000);check(`tower-schema-${version}-prior-neutral`,same(result.state,state)&&same(result.result,{elapsed:0,credited:0,discarded:0}),result)}
for(const version of [0,1,2,3,4,5,6,7,11]){const state=directState(version),result=settle(currentRuntime,'expedition',state,5000);check(`expedition-schema-${version}-neutral`,same(result.state,state)&&same(result.result,{elapsed:0,credited:0,discarded:0}),result)}

for(const lane of ['tower','expedition']){const version=10,key=lane==='tower'?'companionTower':'fellowExpedition',progress=lane==='tower'?'highestFloor':'highestStage',segments=lane==='tower'?'towerSegments':'expeditionSegments',segmentKey=lane==='tower'?'floor':'stage';
  for(const [name,at,elapsed] of [['zero',1000,0],['rollback',999.75,0],['interval-minus-one',3600999,3599999],['exact-interval',3601000,3600000],['interval-plus-one',3601001,3600001],['multiple-intervals',10801000,10800000],['exact-24h',86401000,86400000],['over-24h',90001000,90000000]]){const result=settle(currentRuntime,lane,directState(version),at);check(`${lane}-time-${name}`,result.result.elapsed===elapsed&&result.result.credited===Math.min(elapsed,86400000)&&result.result.discarded===Math.max(0,elapsed-86400000),result)}
  const empty=settle(currentRuntime,lane,directState(version,{floor:0,stage:0}),5000);check(`${lane}-empty-progress-discards`,empty.result.elapsed===4000&&empty.result.credited===0&&empty.result.discarded===4000&&empty.state[key].idle.cursorAt===5000,empty);
  const partialSegment={[segmentKey]:lane==='tower'?2:3,elapsedMs:82800000},partial=settle(currentRuntime,lane,directState(version,{[segments]:[partialSegment]}),7201000);check(`${lane}-partial-cap`,partial.result.credited===3600000&&partial.result.discarded===3600000&&partial.state[key].idle.segments[0].elapsedMs===86400000,partial);
  const fullSegment={[segmentKey]:lane==='tower'?2:3,elapsedMs:86400000},full=settle(currentRuntime,lane,directState(version,{[segments]:[fullSegment]}),5000);check(`${lane}-full-cap`,full.result.credited===0&&full.result.discarded===4000&&full.state[key].idle.segments[0].elapsedMs===86400000,full);
  const matchingSegment={[segmentKey]:lane==='tower'?2:3,elapsedMs:100},matching=settle(currentRuntime,lane,directState(version,{[segments]:[matchingSegment]}),5000);check(`${lane}-matching-segment-extension`,matching.state[key].idle.segments.length===1&&matching.state[key].idle.segments[0].elapsedMs===4100,matching);
  const olderSegment={[segmentKey]:lane==='tower'?1:2,elapsedMs:100},appended=settle(currentRuntime,lane,directState(version,{[segments]:[olderSegment]}),5000);check(`${lane}-new-segment-append`,appended.state[key].idle.segments.length===2&&appended.state[key].idle.segments[1][segmentKey]===(lane==='tower'?2:3)&&appended.state[key].idle.segments[1].elapsedMs===4000,appended);
  const combined=settle(currentRuntime,lane,directState(version),7201000),splitState=directState(version);settle(currentRuntime,lane,splitState,3601000);const split=settle(currentRuntime,lane,splitState,7201000);check(`${lane}-split-combined-equivalence`,same(combined.state[key],split.state[key]),{combined,split});
  const refusing=settlementRuntime(currentTower,currentExpedition,{refuseSafeAdd:true}),refuseState=directState(version,{[segments]:[matchingSegment]});let refused=false;try{settle(refusing,lane,refuseState,5000)}catch(error){refused=error.message.includes('refused')}check(`${lane}-safe-add-refusal`,refused);
}

const phaseNineVerifier=read('qa/phase-9/verify.mjs').toString('utf8');
let phaseNineModule=phaseNineVerifier.slice(0,phaseNineVerifier.lastIndexOf('\nconst suite=String.raw`')).replace("const repoRoot=resolve(new URL('../..',import.meta.url).pathname);",`const repoRoot=${JSON.stringify(repoRoot)};`)+'\nexport {harness};\n';
const {harness:phaseNineHarness}=await import('data:text/javascript;base64,'+Buffer.from(phaseNineModule).toString('base64'));
let harness=phaseNineHarness.replace('    tamperClear(){',`    p10a:Object.freeze({
      state:()=>clone(S),valid:()=>validation(S,10),runtime:()=>qaRuntimeSnapshot(),raw:()=>PERSISTED_RAW,
      towerSettle:(state,at)=>{const draft=clone(state);return{result:settleCompanionTowerElapsed(at,draft),state:draft}},expeditionSettle:(state,at)=>{const draft=clone(state);return{result:settleFellowExpeditionElapsed(at,draft),state:draft}},
      towerPreview:companionTowerIdlePreview,expeditionPreview:fellowExpeditionIdlePreview,towerClaim:options=>claimCompanionTower(options),expeditionClaim:options=>claimFellowExpedition(options),towerClear:options=>clearCompanionTower(options),expeditionPush:options=>pushFellowExpedition(options),
      route:tab=>setAdventure(tab,{present:false}),ordinary:()=>qaGrant({resource:'gold',amount:1}),reset:()=>persistenceAction('safe-reset'),
      setup(kind='both'){qaGrant({resource:'gold',amount:1000000000});qaGrant({resource:'fellowExp',id:'cael',amount:1000000});for(const stage of FELLOW_CAMPAIGN_STAGES.slice(0,6)){const result=runFellowCampaign(stage.id,{confirmed:true,present:false});if(!result?.ok)throw new Error('Campaign setup failed '+stage.id)}if(kind==='tower'||kind==='both'){for(const def of COMPANION_DEFS)qaGrant({resource:'companionExp',id:def.id,amount:1000000});const result=clearCompanionTower({confirmed:true,present:false});if(!result?.ok)throw new Error('Tower setup failed')}if(kind==='expedition'||kind==='both'){const result=pushFellowExpedition({confirmed:true,present:false});if(!result?.ok)throw new Error('Expedition setup failed')}return JSON.stringify(S)},
      strengthenFellows(){for(const def of FELLOW_DEFS)qaGrant({resource:'fellowExp',id:def.id,amount:1000000});return JSON.stringify(S)},
      projectNine(){const state=clone(S);delete state.playerUnlocks;state.schemaVersion=9;state.saveMeta.appliedMigrations=state.saveMeta.appliedMigrations.filter(item=>item?.id!=='schema-9-to-10');delete state.saveMeta.retainedCheckpointLineage;return JSON.stringify(state)}
    }),
    tamperClear(){`);

const suite=String.raw`
const p10=(run,expression)=>internal(run,'p10a.'+expression),slotsOf=run=>JSON.stringify(Object.fromEntries(run.slots)),sumSegments=(segments,key)=>segments.reduce((sum,item)=>sum+item.elapsedMs,0),t0=1787853600000;
const origin=runRealm(freshOptions),bothRaw=p10(origin,"setup('both')"),both=JSON.parse(bothRaw);
check('lifecycle-fixture-both-valid',p10(origin,'valid().ok')===true,p10(origin,'valid().errors'));
check('lifecycle-fixture-progressed',both.companionTower.highestFloor===1&&both.fellowExpedition.highestStage>0,both.fellowExpedition.highestStage);
const towerOrigin=runRealm(freshOptions),towerRaw=p10(towerOrigin,"setup('tower')"),expeditionOrigin=runRealm(freshOptions),expeditionRaw=p10(expeditionOrigin,"setup('expedition')");
const boot=runRealm({...freshOptions,activeRaw:bothRaw,now:t0+7200000}),bootState=active(boot);check('boot-both-cursors-once',bootState.companionTower.idle.cursorAt===t0+7200000&&bootState.fellowExpedition.idle.cursorAt===t0+7200000);check('boot-both-segments-once',sumSegments(bootState.companionTower.idle.segments,'floor')===7200000&&sumSegments(bootState.fellowExpedition.idle.segments,'stage')===7200000);check('boot-current-valid',p10(boot,'valid().ok')===true,p10(boot,'valid().errors'));
const previewRun=runRealm({...freshOptions,activeRaw:bothRaw,now:t0}),previewRaw=activeRaw(previewRun),previewSlots=slotsOf(previewRun),previewState=JSON.stringify(p10(previewRun,'state()'));previewRun.clock.value+=3600000;const towerPreview=p10(previewRun,'towerPreview()'),expeditionPreview=p10(previewRun,'expeditionPreview()');check('preview-readiness',towerPreview.intervals===1&&expeditionPreview.intervals===1,{towerPreview,expeditionPreview});check('preview-clone-only',activeRaw(previewRun)===previewRaw&&slotsOf(previewRun)===previewSlots&&JSON.stringify(p10(previewRun,'state()'))===previewState);
const claimRun=runRealm({...freshOptions,activeRaw:bothRaw,now:t0});claimRun.clock.value+=3600000;const towerClaim=p10(claimRun,'towerClaim({present:false})'),afterTower=clone(active(claimRun)),towerRawAfter=activeRaw(claimRun),towerWrites=writes(claimRun);check('tower-claim-exact-once',towerClaim.ok===true&&afterTower.companionTower.idle.intervalOrdinal===1&&afterTower.companionTower.idle.claimOrdinal===1);check('tower-claim-settles-expedition-only',afterTower.fellowExpedition.idle.cursorAt===t0+3600000&&afterTower.fellowExpedition.idle.claimOrdinal===0&&sumSegments(afterTower.fellowExpedition.idle.segments,'stage')===3600000);const towerRepeat=p10(claimRun,'towerClaim({present:false})');check('tower-same-tick-repeat-noop',towerRepeat===false&&activeRaw(claimRun)===towerRawAfter&&writes(claimRun)===towerWrites);
const towerHistory=JSON.stringify(afterTower.companionTower.idle),expeditionClaim=p10(claimRun,'expeditionClaim({present:false})'),afterExpedition=clone(active(claimRun));check('expedition-claim-exact-once',expeditionClaim.ok===true&&afterExpedition.fellowExpedition.idle.intervalOrdinal===1&&afterExpedition.fellowExpedition.idle.claimOrdinal===1);check('expedition-claim-preserves-tower-history',JSON.stringify(afterExpedition.companionTower.idle)===towerHistory);const expeditionRawAfter=activeRaw(claimRun),expeditionWrites=writes(claimRun),expeditionRepeat=p10(claimRun,'expeditionClaim({present:false})');check('expedition-same-tick-repeat-noop',expeditionRepeat===false&&activeRaw(claimRun)===expeditionRawAfter&&writes(claimRun)===expeditionWrites);const claimReload=runRealm({initialSlots:Object.fromEntries(claimRun.slots),now:t0+3600000});check('claim-reload-exact',p10(claimReload,'valid().ok')===true&&active(claimReload).companionTower.idle.claimOrdinal===1&&active(claimReload).fellowExpedition.idle.claimOrdinal===1,p10(claimReload,'valid().errors'));
const unrelated=runRealm({...freshOptions,activeRaw:bothRaw,now:t0});unrelated.clock.value+=1800000;const beforeGold=active(unrelated).gold;p10(unrelated,'ordinary()');const unrelatedState=active(unrelated);check('unrelated-shared-clock',unrelatedState.companionTower.idle.cursorAt===t0+1800000&&unrelatedState.fellowExpedition.idle.cursorAt===t0+1800000);check('unrelated-no-double-segment',sumSegments(unrelatedState.companionTower.idle.segments,'floor')===1800000&&sumSegments(unrelatedState.fellowExpedition.idle.segments,'stage')===1800000);check('unrelated-legitimate-gold-mutation',unrelatedState.gold>=beforeGold+1);
const routeRun=runRealm({...freshOptions,activeRaw:bothRaw,now:t0});routeRun.clock.value+=900000;p10(routeRun,"route('companionTower')");const routeState=active(routeRun);check('route-shared-clock',routeState.companionTower.idle.cursorAt===t0+900000&&routeState.fellowExpedition.idle.cursorAt===t0+900000);check('route-no-claim-consumption',routeState.companionTower.idle.claimOrdinal===0&&routeState.fellowExpedition.idle.claimOrdinal===0);
const clearRun=runRealm({...freshOptions,activeRaw:towerRaw,now:t0});clearRun.clock.value+=1800000;const clear=p10(clearRun,'towerClear({confirmed:true,present:false})'),clearState=active(clearRun);check('tower-clear-succeeds',clear.ok===true&&clearState.companionTower.highestFloor===2);check('tower-clear-old-floor-attribution',clearState.companionTower.idle.segments.at(-1).floor===1&&clearState.companionTower.idle.segments.at(-1).elapsedMs===1800000,clearState.companionTower.idle.segments);
const pushRun=runRealm({...freshOptions,activeRaw:expeditionRaw,now:t0});pushRun.clock.value+=1800000;const oldStage=JSON.parse(expeditionRaw).fellowExpedition.highestStage;p10(pushRun,'strengthenFellows()');const afterStrengthen=active(pushRun),pushRaw=activeRaw(pushRun),pushWrites=writes(pushRun),push=p10(pushRun,'expeditionPush({confirmed:true,present:false})'),pushState=active(pushRun);check('expedition-power-change-old-stage-attribution',afterStrengthen.fellowExpedition.idle.segments.at(-1).stage===oldStage&&afterStrengthen.fellowExpedition.idle.segments.at(-1).elapsedMs===1800000,JSON.stringify(afterStrengthen.fellowExpedition.idle.segments));check('expedition-push-same-tick-no-reprice',push===false&&pushState.fellowExpedition.highestStage===oldStage&&activeRaw(pushRun)===pushRaw&&writes(pushRun)===pushWrites,JSON.stringify({push,oldStage,current:pushState.fellowExpedition.highestStage}));
const schemaNineRaw=p10(origin,'projectNine()'),migrated=runRealm({...freshOptions,activeRaw:schemaNineRaw,now:t0}),migratedBase=activeRaw(migrated);migrated.clock.value+=3600000;const migratedClaim=p10(migrated,'towerClaim({present:false})');check('schema9-migrates-current-settlement',migratedClaim.ok===true&&active(migrated).schemaVersion===10&&active(migrated).companionTower.idle.intervalOrdinal===1);check('schema9-migration-valid',p10(migrated,'valid().ok')===true,p10(migrated,'valid().errors'));
const resetOrigin=runRealm({...freshOptions,activeRaw:bothRaw,now:t0});p10(resetOrigin,'reset()');const safeRaw=p10(resetOrigin,"setup('both')"),safeState=JSON.parse(safeRaw);check('safe-reset-authority-form',safeState.saveMeta.retainedCheckpointLineage?.version===5);const safeRun=runRealm({initialSlots:Object.fromEntries(resetOrigin.slots),now:t0});safeRun.clock.value+=3600000;check('safe-reset-current-settlement',p10(safeRun,'expeditionClaim({present:false})').ok===true&&active(safeRun).fellowExpedition.idle.intervalOrdinal===1);check('safe-reset-valid',p10(safeRun,'valid().ok')===true,p10(safeRun,'valid().errors'));

const faultHooks=[['staging-new-owner','getItem'],['staging-write','setItem'],['staging-verify','getItem'],['active-conflict-check','getItem'],['active-write','setItem'],['active-verify','getItem'],['staging-cleanup-owner','getItem'],['staging-cleanup','removeItem'],['staging-cleanup-verify','getItem']];
for(const [kind,raw,lane] of [['tower',towerRaw,'tower'],['expedition',expeditionRaw,'expedition'],['combined',bothRaw,'tower']])for(const [step,operation] of faultHooks){const prefix='fault-'+kind+'-'+step,interrupted=runRealm({...freshOptions,activeRaw:raw,now:t0}),before=slotsOf(interrupted),beforeActive=activeRaw(interrupted),beforeState=JSON.stringify(p10(interrupted,'state()'));interrupted.clock.value+=3600000;Object.assign(interrupted.fault,{enabled:true,operation,step,remaining:1,skip:0});p10(interrupted,lane==='tower'?'towerClaim({present:false})':'expeditionClaim({present:false})');check(prefix+'-triggered',interrupted.fault.remaining===0,interrupted.persistenceLog.slice(-8));const hasStage=interrupted.slots.has(keys.staging),activeChanged=activeRaw(interrupted)!==beforeActive,stateSame=JSON.stringify(p10(interrupted,'state()'))===beforeState,detail=JSON.stringify({hasStage,activeChanged,stateSame,blocked:p10(interrupted,'runtime().blocked'),slots:Object.keys(Object.fromEntries(interrupted.slots))});if(['staging-new-owner','staging-write'].includes(step))check(prefix+'-prestage-exact',slotsOf(interrupted)===before&&stateSame,detail);else if(['staging-verify','active-conflict-check','active-write'].includes(step))check(prefix+'-pending-stage',!activeChanged&&hasStage&&stateSame,detail);else if(step==='active-verify')check(prefix+'-committed-stage',activeChanged&&hasStage,detail);else check(prefix+'-cleanup-class',activeChanged,detail);const retry=runRealm({initialSlots:Object.fromEntries(interrupted.slots),now:t0+3600000});let retryState=active(retry),sequence=lane==='tower'?retryState.companionTower.idle.claimOrdinal:retryState.fellowExpedition.idle.claimOrdinal;if(sequence===0)p10(retry,lane==='tower'?'towerClaim({present:false})':'expeditionClaim({present:false})');retryState=active(retry);const ordinal=lane==='tower'?retryState.companionTower.idle.intervalOrdinal:retryState.fellowExpedition.idle.intervalOrdinal,claimOrdinal=lane==='tower'?retryState.companionTower.idle.claimOrdinal:retryState.fellowExpedition.idle.claimOrdinal;check(prefix+'-retry-once',ordinal===1&&claimOrdinal===1&&!retry.slots.has(keys.staging),JSON.stringify({ordinal,claimOrdinal,blocked:p10(retry,'runtime().blocked')}));check(prefix+'-retry-valid',p10(retry,'valid().ok')===true,JSON.stringify(p10(retry,'valid().errors')))}
globalThis.__EVERSTEAD_PHASE_10A_CLI_ROWS__=rows;
`;
eval(harness+suite);

rows.push(...(globalThis.__EVERSTEAD_PHASE_10A_CLI_ROWS__??[]));delete globalThis.__EVERSTEAD_PHASE_10A_CLI_ROWS__;
const failures=rows.filter(row=>!row.pass);console.log(JSON.stringify({total:rows.length,passed:rows.length-failures.length,failed:failures.length,failures},null,2));if(failures.length)process.exitCode=1;
