import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import vm from 'node:vm';

const repoRoot=resolve(new URL('../..',import.meta.url).pathname),read=path=>readFileSync(resolve(repoRoot,path));
const artifact=read('index.html'),source=artifact.toString('utf8'),published=execFileSync('git',['show','068a5a3ea2d9b3b339e96bf3fed0a0c945cf62a5:index.html'],{cwd:repoRoot,encoding:'utf8',maxBuffer:32*1024*1024});
const sha256=value=>createHash('sha256').update(value).digest('hex'),clone=value=>JSON.parse(JSON.stringify(value)),rows=[],check=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:String(detail)});
const line=(text,prefix)=>{const found=text.split('\n').find(value=>value.startsWith(prefix));if(!found)throw new Error(`Missing ${prefix}`);return found};
const originalTower=line(source,'function settleCompanionTowerElapsed('),currentTower=line(source,'settleCompanionTowerElapsed=function('),publishedTower=line(published,'settleCompanionTowerElapsed=function('),currentExpedition=line(source,'function settleFellowExpeditionElapsed('),publishedExpedition=line(published,'function settleFellowExpeditionElapsed(');
function settlementRuntime(towerLine,expeditionLine,{refuseSafeAdd=false}={}){const context={COMPANION_TOWER_CONFIG:{elapsedCapMs:86400000},FELLOW_EXPEDITION_CONFIG:{elapsedCapMs:86400000},towerTick:value=>Math.floor(value),expeditionTick:value=>Math.floor(value),towerSegmentsElapsed:segments=>segments.reduce((sum,item)=>sum+item.elapsedMs,0),expeditionSegmentsElapsed:segments=>segments.reduce((sum,item)=>sum+item.elapsedMs,0),safeAddInteger:(left,right,label)=>{if(refuseSafeAdd)throw new Error(`refused ${label}`);const result=left+right;if(!Number.isSafeInteger(result))throw new Error(label);return result},S:null};vm.createContext(context);vm.runInContext(originalTower,context);vm.runInContext(`const settleCompanionTowerElapsedThroughSix=settleCompanionTowerElapsed;${towerLine}`,context);vm.runInContext(expeditionLine,context);return context}
const releasedRuntime=settlementRuntime(publishedTower,publishedExpedition),currentRuntime=settlementRuntime(currentTower,currentExpedition),clean=value=>JSON.parse(JSON.stringify(value));
const directState=(version,{floor=2,stage=3,cursor=1000,towerSegments=[],expeditionSegments=[]}={})=>({schemaVersion:version,companionTower:{highestFloor:floor,idle:{cursorAt:cursor,segments:clean(towerSegments)}},fellowExpedition:{highestStage:stage,idle:{cursorAt:cursor,segments:clean(expeditionSegments)}}});
const settle=(runtime,lane,state,at)=>{const fn=lane==='tower'?'settleCompanionTowerElapsed':'settleFellowExpeditionElapsed',draft=clean(state),result=runtime[fn](at,draft);return{result:clean(result),state:draft}};
const same=(left,right)=>JSON.stringify(left)===JSON.stringify(right),assets=text=>[...text.matchAll(/data:image\/[^;"']+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]);

check('artifact-repair-sha',sha256(artifact)==='717160cdddc5fa540532cdebd29f30d127ded2f761edd677684a2609fde9a4ed',sha256(artifact));
check('artifact-repair-bytes',artifact.length===18916682,artifact.length);
check('published-preimage-sha',sha256(published)==='1e9d22150a5a0d2b2b4fbec403a5a50bf81c3b22153e688b659bda9b6bc67529',sha256(published));
check('schema-remains-10',source.includes('CURRENT_SCHEMA_VERSION=10;')&&!source.includes('CURRENT_SCHEMA_VERSION=11'));
check('twelve-slots-retained',source.includes("PRE_V10_BACKUP_KEY=NS+'__raw_backup_v9'")&&!source.includes('PRE_V11_BACKUP_KEY'));
check('tower-guard-exact',currentTower.includes('if(![8,9,10].includes(state?.schemaVersion))return settleCompanionTowerElapsedThroughSix'));
check('expedition-guard-exact',currentExpedition.includes('if(![8,9,10].includes(state?.schemaVersion))return{elapsed:0,credited:0,discarded:0}'));
const currentAssets=assets(source),publishedAssets=assets(published);check('embedded-assets-count',currentAssets.length===publishedAssets.length,currentAssets.length);check('embedded-assets-byte-exact',same(currentAssets,publishedAssets));

const focusedSettlementVectors=lane=>{const segmentKey=lane==='tower'?'floor':'stage',segments=lane==='tower'?'towerSegments':'expeditionSegments',progress=lane==='tower'?'floor':'stage',current=lane==='tower'?2:3;return[
  ['zero',{},1000],['rollback',{},999.75],['sub-interval',{},3600999],['exact-interval',{},3601000],['interval-plus-one',{},3601001],['multi-interval',{},10801000],['exact-cap',{},86401000],['over-cap',{},90001000],
  ['empty-progress',{[progress]:0},5000],['partial-cap',{[segments]:[{[segmentKey]:current,elapsedMs:82800000}]},7201000],['full-cap',{[segments]:[{[segmentKey]:current,elapsedMs:86400000}]},5000],
  ['matching-segment',{[segments]:[{[segmentKey]:current,elapsedMs:100}]},5000],['new-segment',{[segments]:[{[segmentKey]:current-1,elapsedMs:100}]},5000]
]};
for(const [lane,version] of [['tower',7],['tower',8],['expedition',8]])for(const [name,options,at] of focusedSettlementVectors(lane)){const candidate=settle(currentRuntime,lane,directState(version,options),at),released=settle(releasedRuntime,lane,directState(version,options),at);check(`${lane}-released-parity-schema-${version}-${name}`,same(candidate,released),{candidate,released})}
for(const version of [7,8,9,10]){const result=settle(currentRuntime,'tower',directState(version),5000);check(`tower-schema-${version}-eligible`,result.result.elapsed===4000&&result.result.credited===4000&&result.result.discarded===0&&result.state.companionTower.idle.cursorAt===5000&&result.state.companionTower.idle.segments[0].elapsedMs===4000,result)}
for(const version of [8,9,10]){const result=settle(currentRuntime,'expedition',directState(version),5000);check(`expedition-schema-${version}-eligible`,result.result.elapsed===4000&&result.result.credited===4000&&result.result.discarded===0&&result.state.fellowExpedition.idle.cursorAt===5000&&result.state.fellowExpedition.idle.segments[0].elapsedMs===4000,result)}
for(const version of [0,1,2,3,4,5,6,11]){const state=directState(version),result=settle(currentRuntime,'tower',state,5000);check(`tower-schema-${version}-prior-neutral`,same(result.state,state)&&same(result.result,{elapsed:0,credited:0,discarded:0}),result)}
for(const version of [0,1,2,3,4,5,6,7,11]){const state=directState(version),result=settle(currentRuntime,'expedition',state,5000);check(`expedition-schema-${version}-neutral`,same(result.state,state)&&same(result.result,{elapsed:0,credited:0,discarded:0}),result)}

for(const lane of ['tower','expedition']){const version=10,key=lane==='tower'?'companionTower':'fellowExpedition',progress=lane==='tower'?'highestFloor':'highestStage',segments=lane==='tower'?'towerSegments':'expeditionSegments',segmentKey=lane==='tower'?'floor':'stage';
  for(const [name,at,elapsed] of [['zero',1000,0],['rollback',999.75,0],['interval-minus-one',3600999,3599999],['exact-interval',3601000,3600000],['interval-plus-one',3601001,3600001],['multiple-intervals',10801000,10800000],['exact-24h',86401000,86400000],['over-24h',90001000,90000000]]){const result=settle(currentRuntime,lane,directState(version),at);check(`${lane}-time-${name}`,result.result.elapsed===elapsed&&result.result.credited===Math.min(elapsed,86400000)&&result.result.discarded===Math.max(0,elapsed-86400000),result)}
  const empty=settle(currentRuntime,lane,directState(version,{floor:0,stage:0}),5000);check(`${lane}-empty-progress-discards`,empty.result.elapsed===4000&&empty.result.credited===0&&empty.result.discarded===4000&&empty.state[key].idle.cursorAt===5000,empty);
  const partialSegment={[segmentKey]:lane==='tower'?2:3,elapsedMs:82800000},partial=settle(currentRuntime,lane,directState(version,{[segments]:[partialSegment]}),7201000);check(`${lane}-partial-cap`,partial.result.credited===3600000&&partial.result.discarded===3600000&&partial.state[key].idle.segments[0].elapsedMs===86400000,partial);
  const fullSegment={[segmentKey]:lane==='tower'?2:3,elapsedMs:86400000},full=settle(currentRuntime,lane,directState(version,{[segments]:[fullSegment]}),5000);check(`${lane}-full-cap`,full.result.credited===0&&full.result.discarded===4000&&full.state[key].idle.segments[0].elapsedMs===86400000,full);
  const matchingSegment={[segmentKey]:lane==='tower'?2:3,elapsedMs:100},matching=settle(currentRuntime,lane,directState(version,{[segments]:[matchingSegment]}),5000);check(`${lane}-matching-segment-extension`,matching.state[key].idle.segments.length===1&&matching.state[key].idle.segments[0].elapsedMs===4100,matching);
  const olderSegment={[segmentKey]:lane==='tower'?1:2,elapsedMs:100},appended=settle(currentRuntime,lane,directState(version,{[segments]:[olderSegment]}),5000);check(`${lane}-new-segment-append`,appended.state[key].idle.segments.length===2&&appended.state[key].idle.segments[1][segmentKey]===(lane==='tower'?2:3)&&appended.state[key].idle.segments[1].elapsedMs===4000,appended);
  const combined=settle(currentRuntime,lane,directState(version),7201000),firstSplit=settle(currentRuntime,lane,directState(version),3601000),split=settle(currentRuntime,lane,firstSplit.state,7201000);check(`${lane}-true-split-combined-equivalence`,same(combined.state[key],split.state[key]),{combined,firstSplit,split});
  const reloadFirst=settle(currentRuntime,lane,directState(version),3601000),reloadedState=JSON.parse(JSON.stringify(reloadFirst.state)),reloadSplit=settle(currentRuntime,lane,reloadedState,7201000);check(`${lane}-reload-split-combined-equivalence`,same(combined.state[key],reloadSplit.state[key]),{combined,reloadFirst,reloadSplit});
  const refusing=settlementRuntime(currentTower,currentExpedition,{refuseSafeAdd:true}),refuseState=directState(version,{[segments]:[matchingSegment]});let refused=false;try{settle(refusing,lane,refuseState,5000)}catch(error){refused=error.message.includes('refused')}check(`${lane}-safe-add-refusal`,refused);
}

const phaseNineVerifier=read('qa/phase-9/verify.mjs').toString('utf8');
let phaseNineModule=phaseNineVerifier.slice(0,phaseNineVerifier.lastIndexOf('\nconst suite=String.raw`')).replace("const repoRoot=resolve(new URL('../..',import.meta.url).pathname);",`const repoRoot=${JSON.stringify(repoRoot)};`)+'\nexport {harness};\n';
const {harness:phaseNineHarness}=await import('data:text/javascript;base64,'+Buffer.from(phaseNineModule).toString('base64'));
let harness=phaseNineHarness.replace('    tamperClear(){',`    p10a:Object.freeze({
      state:()=>clone(S),valid:()=>validation(S,10),runtime:()=>qaRuntimeSnapshot(),raw:()=>PERSISTED_RAW,
      towerSettle:(state,at)=>{const draft=clone(state);return{result:settleCompanionTowerElapsed(at,draft),state:draft}},expeditionSettle:(state,at)=>{const draft=clone(state);return{result:settleFellowExpeditionElapsed(at,draft),state:draft}},
      towerPreview:companionTowerIdlePreview,expeditionPreview:fellowExpeditionIdlePreview,towerClaim:options=>claimCompanionTower(options),expeditionClaim:options=>claimFellowExpedition(options),towerClear:options=>clearCompanionTower(options),expeditionPush:options=>pushFellowExpedition(options),towerConsume:state=>consumeTowerIntervals(state),expeditionConsume:state=>consumeExpeditionIntervals(state),towerHistory:(saveId,counts)=>towerHistoryReplay(saveId,counts),expeditionHistory:(saveId,counts,owned)=>expeditionHistoryReplay(saveId,counts,owned),
      route:tab=>setAdventure(tab,{present:false}),ordinary:()=>qaGrant({resource:'gold',amount:1}),reset:()=>persistenceAction('safe-reset'),
      setup(kind='both'){qaGrant({resource:'gold',amount:1000000000});qaGrant({resource:'fellowExp',id:'cael',amount:1000000});for(const stage of FELLOW_CAMPAIGN_STAGES.slice(0,6)){const result=runFellowCampaign(stage.id,{confirmed:true,present:false});if(!result?.ok)throw new Error('Campaign setup failed '+stage.id)}if(kind==='tower'||kind==='both'){for(const def of COMPANION_DEFS)qaGrant({resource:'companionExp',id:def.id,amount:1000000});const result=clearCompanionTower({confirmed:true,present:false});if(!result?.ok)throw new Error('Tower setup failed')}if(kind==='expedition'||kind==='both'){const result=pushFellowExpedition({confirmed:true,present:false});if(!result?.ok)throw new Error('Expedition setup failed')}return JSON.stringify(S)},
      setupAdvancingExpedition(){for(const id of ['selene','mira'])qaGrant({resource:'fellowExp',id,amount:1000});const result=pushFellowExpedition({confirmed:true,present:false});if(!result?.ok)throw new Error('Initial Expedition setup failed');return JSON.stringify(S)},
      strengthenFellows(){for(const def of FELLOW_DEFS)qaGrant({resource:'fellowExp',id:def.id,amount:1000000});return JSON.stringify(S)},pushPreview:()=>previewFellowExpedition(),
      pendingRaw(towerMs=0,expeditionMs=0){const state=clone(S);if(towerMs>0)state.companionTower.idle.segments=[{floor:state.companionTower.highestFloor,elapsedMs:towerMs}];if(expeditionMs>0)state.fellowExpedition.idle.segments=[{stage:state.fellowExpedition.highestStage,elapsedMs:expeditionMs}];return JSON.stringify(state)},
      towerOverflowRaw(towerMs=COMPANION_TOWER_CONFIG.intervalMs){const state=clone(S),target=COMPANION_DEFS[0],before=state.companions[target.id].exp,delta=Number.MAX_SAFE_INTEGER-before;state.companionTower.idle.segments=[{floor:state.companionTower.highestFloor,elapsedMs:towerMs}];state.companions[target.id].exp=Number.MAX_SAFE_INTEGER;state.companions[target.id].level=companionLevelForExp(state.companions[target.id].exp);state.companionProgressLedger.qaCredits.companionExp[target.id]+=delta;return JSON.stringify(state)},validRaw:raw=>validation(JSON.parse(raw),10),
      ui:()=>clone({app:document.querySelector('#app')?.innerHTML??'',overlay:document.querySelector('#overlay')?.innerHTML??'',toast:document.querySelector('#toast')?.innerHTML??''}),
      outcome:()=>clone({blocked:PERSISTENCE_BLOCKED&&{kind:PERSISTENCE_BLOCKED.kind,message:PERSISTENCE_BLOCKED.message},notice:PERSISTENCE_NOTICE,outcome:PERSISTENCE_OUTCOME,app:document.querySelector('#app')?.innerHTML??'',overlay:document.querySelector('#overlay')?.innerHTML??'',toast:document.querySelector('#toast')?.innerHTML??''}),
      projectNine(){const state=clone(S);delete state.playerUnlocks;state.schemaVersion=9;state.saveMeta.appliedMigrations=state.saveMeta.appliedMigrations.filter(item=>item?.id!=='schema-9-to-10');delete state.saveMeta.retainedCheckpointLineage;return JSON.stringify(state)}
    }),
    tamperClear(){`);

const suite=String.raw`
const p10=(run,expression)=>internal(run,'p10a.'+expression),slotsOf=run=>JSON.stringify(Object.fromEntries(run.slots)),sumSegments=(segments,key)=>segments.reduce((sum,item)=>sum+item.elapsedMs,0),t0=1787853600000;
const origin=runRealm(freshOptions),bothRaw=p10(origin,"setup('both')"),both=JSON.parse(bothRaw);
check('lifecycle-fixture-both-valid',p10(origin,'valid().ok')===true,p10(origin,'valid().errors'));
check('lifecycle-fixture-progressed',both.companionTower.highestFloor===1&&both.fellowExpedition.highestStage>0,both.fellowExpedition.highestStage);
const towerCarryState=clone(both);towerCarryState.companionTower.idle.segments=[{floor:1,elapsedMs:1800000},{floor:2,elapsedMs:2700000}];const towerCarry=p10(origin,'towerConsume('+JSON.stringify(towerCarryState)+')');check('tower-partial-carry-consumption',towerCarry.intervals===1&&towerCarry.consumedElapsedMs===3600000&&towerCarry.counts['1']===1&&JSON.stringify(towerCarry.segments)===JSON.stringify([{floor:2,elapsedMs:900000}]),towerCarry);
const expeditionCarryState=clone(both);expeditionCarryState.fellowExpedition.idle.segments=[{stage:1,elapsedMs:1800000},{stage:2,elapsedMs:2700000}];const expeditionCarry=p10(origin,'expeditionConsume('+JSON.stringify(expeditionCarryState)+')');check('expedition-partial-carry-consumption',expeditionCarry.intervals===1&&expeditionCarry.consumedElapsedMs===3600000&&expeditionCarry.counts['1']===1&&JSON.stringify(expeditionCarry.segments)===JSON.stringify([{stage:2,elapsedMs:900000}]),expeditionCarry);
const combinedTwoHour=runRealm({...freshOptions,activeRaw:bothRaw,now:t0+7200000}),combinedTwoHourState=active(combinedTwoHour),splitFirst=runRealm({...freshOptions,activeRaw:bothRaw,now:t0+3600000}),splitReload=runRealm({initialSlots:Object.fromEntries(splitFirst.slots),now:t0+7200000}),splitReloadState=active(splitReload);check('production-reload-split-tower-equivalence',JSON.stringify(combinedTwoHourState.companionTower.idle)===JSON.stringify(splitReloadState.companionTower.idle),JSON.stringify({combined:combinedTwoHourState.companionTower.idle,split:splitReloadState.companionTower.idle}));check('production-reload-split-expedition-equivalence',JSON.stringify(combinedTwoHourState.fellowExpedition.idle)===JSON.stringify(splitReloadState.fellowExpedition.idle),JSON.stringify({combined:combinedTwoHourState.fellowExpedition.idle,split:splitReloadState.fellowExpedition.idle}));
const pendingRaw=p10(origin,'pendingRaw(3600000,3600000)'),frozenClaims=runRealm({...freshOptions,activeRaw:pendingRaw,now:t0}),frozenBefore=clone(active(frozenClaims)),towerExpected=p10(frozenClaims,'towerPreview()'),expeditionExpected=p10(frozenClaims,'expeditionPreview()'),frozenTowerClaim=p10(frozenClaims,'towerClaim({present:false})'),frozenAfterTower=clone(active(frozenClaims)),frozenTowerReceipt=frozenAfterTower.companionTower.idle.lastReceipt;
check('tower-frozen-claim-succeeds',frozenTowerClaim.ok===true&&frozenTowerReceipt.intervalOrdinalEnd-frozenTowerReceipt.intervalOrdinalStart===1,frozenTowerClaim);
check('tower-exact-reward-map',JSON.stringify(frozenTowerReceipt.companionExp)===JSON.stringify(towerExpected.companionExp)&&JSON.stringify(frozenTowerReceipt.companionShards)===JSON.stringify(towerExpected.companionShards),JSON.stringify({receipt:frozenTowerReceipt,expected:towerExpected}));
check('tower-frozen-reward-literals',JSON.stringify(frozenTowerReceipt.companionExp)===JSON.stringify({bramble:22,cinderwing:22})&&JSON.stringify(frozenTowerReceipt.companionShards)===JSON.stringify({bramble:0,cinderwing:0})&&frozenTowerReceipt.masteryNominal===1&&frozenTowerReceipt.masteryAwarded===1&&frozenTowerReceipt.pityAfter===1,JSON.stringify(frozenTowerReceipt));
check('tower-exact-pity',frozenTowerReceipt.preClaimPityMisses===towerExpected.pityBefore&&frozenTowerReceipt.pityAfter===towerExpected.pityAfter&&frozenAfterTower.companionTower.idle.pityMisses===towerExpected.pityAfter,JSON.stringify({receipt:frozenTowerReceipt,expected:towerExpected}));
check('tower-exact-resource-deltas',Object.keys(towerExpected.companionExp).every(id=>frozenAfterTower.companions[id].exp-frozenBefore.companions[id].exp===towerExpected.companionExp[id]&&frozenAfterTower.companions[id].shards-frozenBefore.companions[id].shards===towerExpected.companionShards[id])&&frozenAfterTower.companionMastery.points-frozenBefore.companionMastery.points===frozenTowerReceipt.masteryAwarded);
check('tower-frozen-gold-neutral',frozenAfterTower.gold===frozenBefore.gold&&frozenAfterTower.pendingGold===frozenBefore.pendingGold,JSON.stringify({before:[frozenBefore.gold,frozenBefore.pendingGold],after:[frozenAfterTower.gold,frozenAfterTower.pendingGold]}));
const frozenExpeditionClaim=p10(frozenClaims,'expeditionClaim({present:false})'),frozenAfterExpedition=clone(active(frozenClaims)),frozenExpeditionReceipt=frozenAfterExpedition.fellowExpedition.idle.lastReceipt;check('expedition-frozen-claim-succeeds',frozenExpeditionClaim.ok===true&&frozenExpeditionReceipt.intervalOrdinalEnd-frozenExpeditionReceipt.intervalOrdinalStart===1,frozenExpeditionClaim);check('expedition-exact-reward-map',JSON.stringify(frozenExpeditionReceipt.fellowShards)===JSON.stringify(expeditionExpected.fellowShards)&&frozenExpeditionReceipt.mightNominal===expeditionExpected.mightNominal,JSON.stringify({receipt:frozenExpeditionReceipt,expected:expeditionExpected}));check('expedition-frozen-reward-literals',JSON.stringify(frozenExpeditionReceipt.fellowShards)===JSON.stringify({cael:0,lyra:0,orin:0,selene:0,rook:0,mira:0})&&frozenExpeditionReceipt.mightNominal===3&&frozenExpeditionReceipt.mightAwarded===3&&frozenExpeditionReceipt.pityAfter===1,JSON.stringify(frozenExpeditionReceipt));check('expedition-exact-pity',frozenExpeditionReceipt.preClaimPityMisses===expeditionExpected.pityBefore&&frozenExpeditionReceipt.pityAfter===expeditionExpected.pityAfter&&frozenAfterExpedition.fellowExpedition.idle.pityMisses===expeditionExpected.pityAfter);check('expedition-exact-resource-deltas',Object.keys(expeditionExpected.fellowShards).every(id=>frozenAfterExpedition.fellows[id].shards-frozenAfterTower.fellows[id].shards===expeditionExpected.fellowShards[id])&&frozenAfterExpedition.fellowMight.points-frozenAfterTower.fellowMight.points===frozenExpeditionReceipt.mightAwarded);check('expedition-frozen-gold-neutral',frozenAfterExpedition.gold===frozenBefore.gold&&frozenAfterExpedition.pendingGold===frozenBefore.pendingGold);
const towerOrigin=runRealm(freshOptions),towerRaw=p10(towerOrigin,"setup('tower')"),expeditionOrigin=runRealm(freshOptions),expeditionRaw=p10(expeditionOrigin,"setup('expedition')");
const boot=runRealm({...freshOptions,activeRaw:bothRaw,now:t0+7200000}),bootState=active(boot);check('boot-both-cursors-once',bootState.companionTower.idle.cursorAt===t0+7200000&&bootState.fellowExpedition.idle.cursorAt===t0+7200000);check('boot-both-segments-once',sumSegments(bootState.companionTower.idle.segments,'floor')===7200000&&sumSegments(bootState.fellowExpedition.idle.segments,'stage')===7200000);check('boot-current-valid',p10(boot,'valid().ok')===true,p10(boot,'valid().errors'));
const previewRun=runRealm({...freshOptions,activeRaw:bothRaw,now:t0}),previewRaw=activeRaw(previewRun),previewSlots=slotsOf(previewRun),previewState=JSON.stringify(p10(previewRun,'state()'));previewRun.clock.value+=3600000;const towerPreview=p10(previewRun,'towerPreview()'),expeditionPreview=p10(previewRun,'expeditionPreview()');check('preview-readiness',towerPreview.intervals===1&&expeditionPreview.intervals===1,{towerPreview,expeditionPreview});check('preview-clone-only',activeRaw(previewRun)===previewRaw&&slotsOf(previewRun)===previewSlots&&JSON.stringify(p10(previewRun,'state()'))===previewState);
const claimRun=runRealm({...freshOptions,activeRaw:bothRaw,now:t0});claimRun.clock.value+=3600000;const towerClaim=p10(claimRun,'towerClaim({present:false})'),afterTower=clone(active(claimRun)),towerRawAfter=activeRaw(claimRun),towerWrites=writes(claimRun);check('tower-claim-exact-once',towerClaim.ok===true&&afterTower.companionTower.idle.intervalOrdinal===1&&afterTower.companionTower.idle.claimOrdinal===1);check('tower-claim-settles-expedition-only',afterTower.fellowExpedition.idle.cursorAt===t0+3600000&&afterTower.fellowExpedition.idle.claimOrdinal===0&&sumSegments(afterTower.fellowExpedition.idle.segments,'stage')===3600000);const towerRepeat=p10(claimRun,'towerClaim({present:false})');check('tower-same-tick-repeat-noop',towerRepeat===false&&activeRaw(claimRun)===towerRawAfter&&writes(claimRun)===towerWrites);
const towerHistory=JSON.stringify(afterTower.companionTower.idle),expeditionClaim=p10(claimRun,'expeditionClaim({present:false})'),afterExpedition=clone(active(claimRun));check('expedition-claim-exact-once',expeditionClaim.ok===true&&afterExpedition.fellowExpedition.idle.intervalOrdinal===1&&afterExpedition.fellowExpedition.idle.claimOrdinal===1);check('expedition-claim-preserves-tower-history',JSON.stringify(afterExpedition.companionTower.idle)===towerHistory);const expeditionRawAfter=activeRaw(claimRun),expeditionWrites=writes(claimRun),expeditionRepeat=p10(claimRun,'expeditionClaim({present:false})');check('expedition-same-tick-repeat-noop',expeditionRepeat===false&&activeRaw(claimRun)===expeditionRawAfter&&writes(claimRun)===expeditionWrites);const claimReload=runRealm({initialSlots:Object.fromEntries(claimRun.slots),now:t0+3600000});check('claim-reload-exact',p10(claimReload,'valid().ok')===true&&active(claimReload).companionTower.idle.claimOrdinal===1&&active(claimReload).fellowExpedition.idle.claimOrdinal===1,p10(claimReload,'valid().errors'));
const advancingExpeditionRun=runRealm({...freshOptions,activeRaw:bothRaw,now:t0});advancingExpeditionRun.clock.value+=3600000;const advancingExpeditionClaim=p10(advancingExpeditionRun,'expeditionClaim({present:false})'),advancingExpeditionState=active(advancingExpeditionRun);check('advancing-expedition-claim-succeeds',advancingExpeditionClaim.ok===true&&advancingExpeditionState.fellowExpedition.idle.claimOrdinal===1);check('advancing-expedition-claim-settles-tower',advancingExpeditionState.companionTower.idle.cursorAt===t0+3600000&&advancingExpeditionState.companionTower.idle.claimOrdinal===0&&advancingExpeditionState.companionTower.idle.intervalOrdinal===0&&sumSegments(advancingExpeditionState.companionTower.idle.segments,'floor')===3600000,advancingExpeditionState.companionTower.idle);
const unrelated=runRealm({...freshOptions,activeRaw:bothRaw,now:t0});unrelated.clock.value+=1800000;const beforeGold=active(unrelated).gold;p10(unrelated,'ordinary()');const unrelatedState=active(unrelated);check('unrelated-shared-clock',unrelatedState.companionTower.idle.cursorAt===t0+1800000&&unrelatedState.fellowExpedition.idle.cursorAt===t0+1800000);check('unrelated-no-double-segment',sumSegments(unrelatedState.companionTower.idle.segments,'floor')===1800000&&sumSegments(unrelatedState.fellowExpedition.idle.segments,'stage')===1800000);check('unrelated-legitimate-gold-mutation',unrelatedState.gold>=beforeGold+1);
const routeRun=runRealm({...freshOptions,activeRaw:bothRaw,now:t0});routeRun.clock.value+=900000;p10(routeRun,"route('companionTower')");const routeState=active(routeRun);check('route-shared-clock',routeState.companionTower.idle.cursorAt===t0+900000&&routeState.fellowExpedition.idle.cursorAt===t0+900000);check('route-no-claim-consumption',routeState.companionTower.idle.claimOrdinal===0&&routeState.fellowExpedition.idle.claimOrdinal===0);
const clearRun=runRealm({...freshOptions,activeRaw:towerRaw,now:t0});clearRun.clock.value+=1800000;const clear=p10(clearRun,'towerClear({confirmed:true,present:false})'),clearState=active(clearRun);check('tower-clear-succeeds',clear.ok===true&&clearState.companionTower.highestFloor===2);check('tower-clear-old-floor-attribution',clearState.companionTower.idle.segments.at(-1).floor===1&&clearState.companionTower.idle.segments.at(-1).elapsedMs===1800000,clearState.companionTower.idle.segments);
const pushLegacyOrigin=runRealm(freshOptions),pushNineRaw=p10(pushLegacyOrigin,'projectNine()'),pushRun=runRealm({...freshOptions,activeRaw:pushNineRaw,now:t0});p10(pushRun,'setupAdvancingExpedition()');const oldStage=active(pushRun).fellowExpedition.highestStage;p10(pushRun,'strengthenFellows()');const strengthenedPreview=p10(pushRun,'pushPreview()');pushRun.clock.value+=1800000;const push=p10(pushRun,'expeditionPush({confirmed:true,present:false})'),pushState=active(pushRun);check('expedition-advancing-push-succeeds',strengthenedPreview.newHigh===true&&push.ok===true&&pushState.fellowExpedition.highestStage===strengthenedPreview.resolution.highestStage&&pushState.fellowExpedition.highestStage>oldStage,JSON.stringify({preview:strengthenedPreview,push,current:pushState.fellowExpedition.highestStage,oldStage}));check('expedition-advancing-push-old-stage-attribution',pushState.fellowExpedition.idle.cursorAt===t0+1800000&&pushState.fellowExpedition.idle.segments.at(-1).stage===oldStage&&pushState.fellowExpedition.idle.segments.at(-1).elapsedMs===1800000,JSON.stringify(pushState.fellowExpedition.idle.segments));check('expedition-advancing-push-receipt',pushState.fellowExpedition.lastBestReceipt.priorHighestStage===oldStage&&pushState.fellowExpedition.lastBestReceipt.highestStage===pushState.fellowExpedition.highestStage&&pushState.fellowExpedition.lastBestReceipt.achievedAt===t0+1800000,pushState.fellowExpedition.lastBestReceipt);
const schemaNineRaw=p10(origin,'projectNine()'),migrated=runRealm({...freshOptions,activeRaw:schemaNineRaw,now:t0}),migratedBase=activeRaw(migrated);migrated.clock.value+=3600000;const migratedClaim=p10(migrated,'towerClaim({present:false})');check('schema9-migrates-current-settlement',migratedClaim.ok===true&&active(migrated).schemaVersion===10&&active(migrated).companionTower.idle.intervalOrdinal===1);check('schema9-migration-valid',p10(migrated,'valid().ok')===true,p10(migrated,'valid().errors'));
const resetOrigin=runRealm({...freshOptions,activeRaw:bothRaw,now:t0});p10(resetOrigin,'reset()');const safeRaw=p10(resetOrigin,"setup('both')"),safeState=JSON.parse(safeRaw);check('safe-reset-authority-form',safeState.saveMeta.retainedCheckpointLineage?.version===5);const safeRun=runRealm({initialSlots:Object.fromEntries(resetOrigin.slots),now:t0});safeRun.clock.value+=3600000;check('safe-reset-current-settlement',p10(safeRun,'expeditionClaim({present:false})').ok===true&&active(safeRun).fellowExpedition.idle.intervalOrdinal===1);check('safe-reset-valid',p10(safeRun,'valid().ok')===true,p10(safeRun,'valid().errors'));

const overflowRaw=p10(towerOrigin,'towerOverflowRaw()'),overflowValidity=p10(towerOrigin,'validRaw('+JSON.stringify(overflowRaw)+')'),overflowRun=runRealm({...freshOptions,activeRaw:overflowRaw,now:t0}),overflowSlotsBefore=slotsOf(overflowRun),overflowActiveBefore=activeRaw(overflowRun),overflowStateBefore=JSON.stringify(p10(overflowRun,'state()')),overflowUiBefore=JSON.stringify(p10(overflowRun,'ui()')),overflowResult=p10(overflowRun,'towerClaim({present:true})'),overflowRuntime=p10(overflowRun,'runtime()'),overflowUi=p10(overflowRun,'ui()');check('tower-production-overflow-fixture-valid',overflowValidity.ok===true,overflowValidity.errors);check('tower-production-safe-add-overflow-refused',overflowResult?.ok===false&&overflowResult?.error?.code==='reward-overflow'&&overflowRuntime.blocked?.kind==='reward-overflow'&&overflowRuntime.blocked?.message==='Bramble Tower idle EXP would overflow safe integer precision',JSON.stringify({result:overflowResult,kind:overflowRuntime.blocked?.kind,message:overflowRuntime.blocked?.message}));check('tower-production-overflow-coordinator-rollback',slotsOf(overflowRun)===overflowSlotsBefore&&activeRaw(overflowRun)===overflowActiveBefore&&JSON.stringify(p10(overflowRun,'state()'))===overflowStateBefore,JSON.stringify({slots:slotsOf(overflowRun)===overflowSlotsBefore,active:activeRaw(overflowRun)===overflowActiveBefore}));check('tower-production-overflow-ui-not-success',JSON.stringify(overflowUi)!==overflowUiBefore&&overflowUi.app.includes('Save Needs Attention')&&!overflowUi.toast.includes('Tower claim ·'),JSON.stringify(overflowUi));

const faultHooks=[['staging-new-owner','getItem'],['staging-write','setItem'],['staging-verify','getItem'],['active-conflict-check','getItem'],['active-write','setItem'],['active-verify','getItem'],['staging-cleanup-owner','getItem'],['staging-cleanup','removeItem'],['staging-cleanup-verify','getItem']];
const faultAttemptAt=t0+3600000,faultLaterAt=t0+7200000,cleanupNotice='The save committed, but staging cleanup will be retried on the next load.',blockedApp='<main class="screen" data-persistence-outcome="REJECT_PRESERVE"><div class="page-head"><div><div class="eyebrow">Everstead save protection</div><h1>Save Needs Attention</h1><p>injected step failure</p></div></div><section class="card"><p class="soft" style="font-size:9px">The active payload was not replaced. Write-once recovery backups remain under the compatibility namespace.</p><button class="btn wide" data-persistence-act="reload">RELOAD LATEST SAVE</button><button class="btn wide" data-persistence-act="export">EXPORT PROTECTED DATA</button><button class="btn danger wide" data-persistence-act="safe-reset">SAFE RESET EVERSTEAD · KEEP BACKUPS</button></section></main>',prestageSteps=new Set(['staging-new-owner','staging-write']),pendingSteps=new Set(['staging-verify','active-conflict-check','active-write']),cleanupSteps=new Set(['staging-cleanup-owner','staging-cleanup','staging-cleanup-verify']),stageSteps=new Set(['staging-verify','active-conflict-check','active-write','active-verify','staging-cleanup-owner','staging-cleanup']),committedSteps=new Set(['active-verify','staging-cleanup-owner','staging-cleanup','staging-cleanup-verify']);
const claimFor=(run,lane)=>p10(run,lane==='tower'?'towerClaim({present:false})':'expeditionClaim({present:false})'),laneIdle=(state,lane)=>lane==='tower'?state.companionTower.idle:state.fellowExpedition.idle,laneSegments=(state,lane)=>laneIdle(state,lane).segments.reduce((sum,item)=>sum+item.elapsedMs,0),protectedWithoutStage=run=>JSON.stringify(Object.fromEntries([...run.slots].filter(([key])=>key!==keys.staging))),checkpointSlots=run=>JSON.stringify(Object.fromEntries([...run.slots].filter(([key])=>key!==keys.active&&key!==keys.staging)));
for(const [kind,raw,lane] of [['tower',towerRaw,'tower'],['expedition',expeditionRaw,'expedition'],['combined',bothRaw,'tower']])for(const [step,operation] of faultHooks){const prefix='fault-'+kind+'-'+step,interrupted=runRealm({...freshOptions,activeRaw:raw,now:t0}),before=slotsOf(interrupted),beforeWithoutStage=protectedWithoutStage(interrupted),beforeCheckpoints=checkpointSlots(interrupted),beforeActive=activeRaw(interrupted),beforeState=JSON.stringify(p10(interrupted,'state()')),beforeUi=JSON.stringify(p10(interrupted,'ui()'));interrupted.clock.value=faultAttemptAt;Object.assign(interrupted.fault,{enabled:true,operation,step,remaining:1,skip:0});const interruptedResult=claimFor(interrupted,lane),outcome=p10(interrupted,'outcome()'),hasStage=interrupted.slots.has(keys.staging),activeChanged=activeRaw(interrupted)!==beforeActive,stateSame=JSON.stringify(p10(interrupted,'state()'))===beforeState,stageRaw=interrupted.slots.get(keys.staging)??null,stageState=stageRaw?JSON.parse(stageRaw).state:null,expectedStage=stageSteps.has(step),expectedCommitted=committedSteps.has(step),detail=JSON.stringify({hasStage,activeChanged,stateSame,outcome,interruptedResult});
  check(prefix+'-triggered',interrupted.fault.remaining===0,interrupted.persistenceLog.slice(-8));
  check(prefix+'-exact-stage-category',hasStage===expectedStage&&activeChanged===expectedCommitted&&(!expectedStage||stageState?.schemaVersion===10)&&(!expectedCommitted||!expectedStage||activeRaw(interrupted)===JSON.stringify(stageState)),detail);
  check(prefix+'-protected-slots',checkpointSlots(interrupted)===beforeCheckpoints&&(prestageSteps.has(step)?slotsOf(interrupted)===before&&protectedWithoutStage(interrupted)===beforeWithoutStage:expectedCommitted?activeChanged:activeRaw(interrupted)===beforeActive),detail);
  if(cleanupSteps.has(step))check(prefix+'-cleanup-success-notice-ui',interruptedResult?.ok===true&&outcome.blocked===null&&outcome.notice===cleanupNotice&&outcome.outcome==='NORMAL'&&outcome.app!==blockedApp&&!outcome.app.includes('Save Needs Attention')&&outcome.overlay===''&&outcome.toast===''&&JSON.stringify(p10(interrupted,'ui()'))!==beforeUi,detail);else check(prefix+'-precommit-blocked-runtime-ui',interruptedResult?.ok===false&&interruptedResult?.error?.code==='injected-failure'&&outcome.blocked?.kind==='injected-failure'&&outcome.blocked?.message==='injected step failure'&&outcome.notice==='injected step failure'&&outcome.outcome==='REJECT_PRESERVE'&&outcome.app===blockedApp&&outcome.overlay===''&&outcome.toast===''&&stateSame,detail);
  const sameClock=runRealm({initialSlots:Object.fromEntries(interrupted.slots),now:faultAttemptAt});let sameState=active(sameClock),sameIdle=laneIdle(sameState,lane);if(sameIdle.claimOrdinal===0)claimFor(sameClock,lane);sameState=active(sameClock);sameIdle=laneIdle(sameState,lane);const sameOther=lane==='tower'?sameState.fellowExpedition.idle:sameState.companionTower.idle;check(prefix+'-same-clock-recovery',sameIdle.intervalOrdinal===1&&sameIdle.claimOrdinal===1&&sameIdle.cursorAt===faultAttemptAt&&sameIdle.segments.length===0&&!sameClock.slots.has(keys.staging)&&p10(sameClock,'valid().ok')===true,JSON.stringify({sameIdle,blocked:p10(sameClock,'runtime().blocked')}));check(prefix+'-same-clock-both-lane-exact',sameOther.cursorAt===faultAttemptAt&&(kind==='combined'?sameOther.claimOrdinal===0&&sameOther.intervalOrdinal===0&&laneSegments(sameState,lane==='tower'?'expedition':'tower')===3600000:laneSegments(sameState,lane==='tower'?'expedition':'tower')===0),JSON.stringify(sameOther));
  const laterClock=runRealm({initialSlots:Object.fromEntries(interrupted.slots),now:faultLaterAt});let laterState=active(laterClock),laterIdle=laneIdle(laterState,lane);if(laterIdle.intervalOrdinal<2)claimFor(laterClock,lane);laterState=active(laterClock);laterIdle=laneIdle(laterState,lane);const laterOther=lane==='tower'?laterState.fellowExpedition.idle:laterState.companionTower.idle,expectedLaterClaims=prestageSteps.has(step)?1:2;check(prefix+'-later-clock-recovery',laterIdle.intervalOrdinal===2&&laterIdle.claimOrdinal===expectedLaterClaims&&laterIdle.lastReceipt?.intervalOrdinalEnd===2&&laterIdle.cursorAt===faultLaterAt&&laterIdle.segments.length===0&&!laterClock.slots.has(keys.staging)&&p10(laterClock,'valid().ok')===true,JSON.stringify({laterIdle,expectedLaterClaims,blocked:p10(laterClock,'runtime().blocked')}));check(prefix+'-later-clock-both-lane-no-loss-no-double',laterOther.cursorAt===faultLaterAt&&(kind==='combined'?laterOther.claimOrdinal===0&&laterOther.intervalOrdinal===0&&laneSegments(laterState,lane==='tower'?'expedition':'tower')===7200000:laneSegments(laterState,lane==='tower'?'expedition':'tower')===0),JSON.stringify(laterOther));
}
globalThis.__EVERSTEAD_PHASE_10A_CLI_ROWS__=rows;
`;
eval(harness+suite);

rows.push(...(globalThis.__EVERSTEAD_PHASE_10A_CLI_ROWS__??[]));delete globalThis.__EVERSTEAD_PHASE_10A_CLI_ROWS__;
const failures=rows.filter(row=>!row.pass);console.log(JSON.stringify({total:rows.length,passed:rows.length-failures.length,failed:failures.length,failures},null,2));if(failures.length)process.exitCode=1;
