import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {existsSync,readFileSync,readdirSync,statSync} from 'node:fs';
import {resolve} from 'node:path';
import {Script} from 'node:vm';

const ROOT=resolve(new URL('../..',import.meta.url).pathname),QA=resolve(ROOT,'qa/phase-22b-features'),rows=[];
const read=path=>readFileSync(resolve(ROOT,path)),text=path=>read(path).toString('utf8'),json=path=>JSON.parse(text(path)),sha=value=>createHash('sha256').update(value).digest('hex'),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)});
const filesBelow=(directory,prefix='')=>readdirSync(directory).flatMap(name=>{const absolute=resolve(directory,name),path=prefix?`${prefix}/${name}`:name;return statSync(absolute).isDirectory()?filesBelow(absolute,path):[path]}).sort();
const f=json('qa/phase-22b-features/fixtures/contract.json'),index=text('index.html'),phase17=text('src/phase17-runtime.js'),css=existsSync(resolve(ROOT,f.stylesheet))?text(f.stylesheet):'',cssBundle=text(f.phase22aStylesheet)+css,git=(args,options={})=>spawnSync('git',args,{cwd:ROOT,encoding:'utf8',maxBuffer:64*1024*1024,...options}),baseIndex=git(['show',`${f.baseCommit}:index.html`],{encoding:null}),basePhase17=git(['show',`${f.baseCommit}:src/phase17-runtime.js`],{encoding:null}),sourceIndex=git(['show',`${f.sourceCommit}:index.html`],{encoding:null}),sourcePhase17=git(['show',`${f.sourceCommit}:src/phase17-runtime.js`],{encoding:null}),sourceCss=git(['show',`${f.sourceCommit}:${f.stylesheet}`],{encoding:null}),sourceAncestor=git(['merge-base','--is-ancestor',f.sourceCommit,'HEAD']),trackedDelta=git(['diff','--name-only',f.baseCommit,f.sourceCommit,'--','index.html','src']),indexDiff=git(['diff','--unified=0',f.baseCommit,f.sourceCommit,'--','index.html']).stdout,phase17Diff=git(['diff','--unified=0',f.baseCommit,f.sourceCommit,'--','src/phase17-runtime.js']).stdout;

record('package-topology',same(filesBelow(QA),['README.md','fixtures/contract.json','verify.mjs']),filesBelow(QA));
record('contract-exact-base-source-and-scope',f.contractVersion===2&&f.phase==='22B'&&f.baseCommit==='d29be5f9c6881ee6ed47bf38a57b97d91dab25d0'&&f.sourceCommit==='ddc129935eac809f106c2782bb63b0b138fe0ad0'&&f.bridgeVersion==='phase-20-21-independent-qa-v2'&&f.publicRelease===false);
record('phase22b-source-commit-is-reachable',sourceAncestor.status===0,f.sourceCommit);
record('phase22b-source-identity-is-frozen',f.sourceFrozen===true&&typeof f.stylesheetVersion==='string'&&typeof f.stylesheetHref==='string'&&typeof f.stylesheetInclude==='string'&&/^[0-9a-f]{64}$/.test(f.stylesheetSha256)&&Number.isSafeInteger(f.stylesheetBytes)&&/^[0-9a-f]{64}$/.test(f.indexSha256)&&Number.isSafeInteger(f.indexBytes)&&/^[0-9a-f]{64}$/.test(f.phase17Sha256)&&Number.isSafeInteger(f.phase17Bytes),{sourceFrozen:f.sourceFrozen,stylesheetVersion:f.stylesheetVersion,stylesheetSha256:f.stylesheetSha256,indexSha256:f.indexSha256,phase17Sha256:f.phase17Sha256});
record('base-tip-source-identity',baseIndex.status===0&&Buffer.byteLength(baseIndex.stdout)===f.baseIndexBytes&&sha(baseIndex.stdout)===f.baseIndexSha256&&basePhase17.status===0,{baseIndexBytes:baseIndex.stdout?.length,baseIndexSha256:baseIndex.stdout?sha(baseIndex.stdout):null});
record('working-phase22b-production-source-identity',Buffer.byteLength(index)===f.indexBytes&&sha(index)===f.indexSha256&&Buffer.byteLength(phase17)===f.phase17Bytes&&sha(phase17)===f.phase17Sha256&&Buffer.byteLength(css)===f.stylesheetBytes&&sha(css)===f.stylesheetSha256,{index:{bytes:Buffer.byteLength(index),sha256:sha(index)},phase17:{bytes:Buffer.byteLength(phase17),sha256:sha(phase17)},stylesheet:{bytes:Buffer.byteLength(css),sha256:css?sha(css):null}});
record('working-production-matches-source-commit',sourceIndex.status===0&&sourcePhase17.status===0&&sourceCss.status===0&&sourceIndex.stdout.toString('hex')===read('index.html').toString('hex')&&sourcePhase17.stdout.toString('hex')===read('src/phase17-runtime.js').toString('hex')&&sourceCss.stdout.toString('hex')===read(f.stylesheet).toString('hex'));
record('exact-authorized-committed-production-delta',trackedDelta.status===0&&same(trackedDelta.stdout.trim().split('\n').filter(Boolean),['index.html','src/phase17-runtime.js',f.stylesheet]),trackedDelta.stdout.trim());
record('phase22b-index-delta-is-presentation-only',indexDiff.includes('phase22b-feature-polish.css')&&indexDiff.includes('Phase 22B · feature-screen presentation')&&indexDiff.includes('data-phase22b-feature-surface')&&!/^[+]\s*.*(?:mutatePersisted|localStorage|setItem|phaseTwelveApplyRewards|S\.(?:gold|gifts|prosperity)\s*[+\-=])/m.test(indexDiff));
record('phase17-delta-is-chronicle-presentation-only',phase17Diff.includes('data-phase22b-chronicle-group')&&phase17Diff.includes('data-phase22b-chronicle-record-count')&&!/^[+]\s*.*(?:mutatePersisted|localStorage|setItem|addEventListener|onclick\s*=)/m.test(phase17Diff));
record('single-cache-versioned-phase22b-stylesheet-after-phase22a',Boolean(f.stylesheetInclude)&&index.split(f.stylesheetInclude).length===2&&index.indexOf(f.phase22aStylesheetHref)<index.indexOf(f.stylesheetHref)&&index.indexOf(f.stylesheetHref)<index.indexOf('</head>')&&f.stylesheetHref.endsWith(`?v=${f.stylesheetVersion}`));
record('phase22a-source-identity-preserved',sha(read(f.phase22aStylesheet))===f.phase22aStylesheetSha256&&index.includes(f.phase22aStylesheetHref));
record('phase22b-stylesheet-source-identity',css.length>0&&Buffer.byteLength(css)===f.stylesheetBytes&&sha(css)===f.stylesheetSha256,{bytes:Buffer.byteLength(css),sha256:css?sha(css):null});
record('stylesheet-local-presentation-only',css.length>0&&!/@import\b|@font-face\b|url\s*\(|javascript:|https?:\/\/|addEventListener|localStorage|setItem|mutatePersisted/i.test(css));
record('stylesheet-no-reference-ingestion',!/IMG_70\d\d|64B0ECA4|checkerboard|reference-game|isekai|screenshot[- ]copy/i.test(css));

record('exact-five-navigation-source-preserved',same(f.navigation,['village','oaths','fellows','adventure','more'])&&index.includes("const items=[['village','⌂','Village'],['oaths','✓','Oaths'],['fellows','♙','Fellowship'],['adventure','⌁','Adventure'],['more','•••','More']]"));
record('more-dialog-invokers-have-exact-late-phase22b-focus-descriptors',index.includes("const phaseTenBThreeFocusDescriptorBeforePhaseTwentyTwoB=phaseTenBThreeFocusDescriptor;phaseTenBThreeFocusDescriptor=function(element){")&&index.includes("for(const attribute of ['data-phase13-legacy','data-phase13-chronicle','data-phase13-tutorial-log','data-phase13-objective','data-phase17-chronicle-open'])")&&index.includes('return phaseTenBThreeFocusDescriptorBeforePhaseTwentyTwoB(element)'));
record('fellowship-tabs-cards-and-full-art-hooks-preserved',same(f.rosterTabs,['fellows','family','companions','relics'])&&index.includes('data-roster="${id}"')&&['fellows','family','companions','relics'].every(value=>index.includes(`['${value}'`)||index.includes(`,'${value}'`))&&['data-fellow','data-family','data-companion','data-relic-card','data-phase22b-feature-surface="fellowship"','phase22bFullArtKind','phase22bFullArtId','phase22bArtTreatment'].every(value=>index.includes(value))&&index.includes("detail?'':'thumb/'"));
record('campaign-single-wayfarer-record-and-profile-hooks-preserved',['data-phase17-campaign-identity-card="player.wayfarer"','data-phase17-player-character="player.wayfarer"','data-player-roster-member="false"'].every(value=>phase17.includes(value))&&['data-phase22b-feature-surface="campaign"','data-phase22b-campaign-record','data-phase22b-stage-run-count','data-phase22b-stage-clear-state','data-phase22b-stage-last-result','data-phase22b-wayfarer-stage="player.wayfarer"','data-phase22b-wayfarer-profile'].every(value=>index.includes(value))&&!index.includes('player.wayfarer" data-fellow'));
record('legacy-chronicle-and-more-storage-hooks-preserved',['data-phase13-legacy','phase22bLegacy','phase22bLegacyCategory','phase22bLegacyState','data-phase22b-feature-surface="more"','data-phase22b-more-storage','data-phase22b-more-story','data-phase22b-more-codex'].every(value=>index.includes(value))&&['data-phase17-chronicle-open','data-phase22b-chronicle','data-phase22b-chronicle-group','data-phase22b-chronicle-record-count','data-phase17-chronicle-entry'].every(value=>phase17.includes(value)));
record('no-remaining-semantic-hook-gaps',same(f.semanticHookGaps,[])&&Object.keys(f.semanticHooks).length===15);
record('phase22b-css-covers-required-real-surfaces',['[data-phase22b-feature-surface="fellowship"]','[data-phase22b-full-art-kind]','[data-phase22b-wayfarer-stage="player.wayfarer"]','[data-phase22b-feature-surface="campaign"]','[data-phase22b-campaign-record]','[data-phase22b-legacy="true"]','[data-phase22b-chronicle]','[data-phase22b-feature-surface="more"]','[data-phase22b-more-storage]'].every(value=>css.includes(value)),['[data-phase22b-feature-surface="fellowship"]','[data-phase22b-full-art-kind]','[data-phase22b-wayfarer-stage="player.wayfarer"]','[data-phase22b-feature-surface="campaign"]','[data-phase22b-campaign-record]','[data-phase22b-legacy="true"]','[data-phase22b-chronicle]','[data-phase22b-feature-surface="more"]','[data-phase22b-more-storage]'].filter(value=>!css.includes(value)));
record('minimum-target-focus-overflow-contract',f.minimumTargetPx===44&&['44px',':focus-visible','overflow-wrap: anywhere','min-width: 0'].every(value=>cssBundle.includes(value)));
record('all-required-responsive-breakpoints',css.includes('@media (max-width: 420px)')&&css.includes('@media (max-width: 360px)')&&css.includes('@media (min-width: 760px)')&&f.viewports.length===7&&same(f.viewports.slice(0,5).map(v=>[v.width,v.height]),[[320,568],[390,844],[430,932],[768,1024],[1024,768]])&&f.viewports.some(v=>v.copyScale===1.3));
record('reduced-motion-real-css-contract',css.includes('@media (prefers-reduced-motion: reduce)')&&css.includes('html.phase15-reduced-motion')&&css.includes('animation: none !important')&&css.includes('transition: none !important')&&f.viewports.some(v=>v.reducedMotion));
record('inactive-production-remains-closed',f.publicRelease===false&&index.includes('publicReleaseAllowed:false')&&text('src/phase20-21-facilities.js').includes('publicRelease:false')&&text('src/phase20-21-facilities.js').includes('productionEnabled:false')&&phase17.includes('publicRelease:false'));

const inlineScripts=[...index.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(match=>match[1]).filter(Boolean);let syntaxError='';for(let index=0;index<inlineScripts.length;index++)try{new Script(inlineScripts[index],{filename:`index-inline-${index}.js`})}catch(error){syntaxError=error.stack||error.message;break}record('index-inline-script-syntax',syntaxError==='',syntaxError);
const phase17Syntax=spawnSync(process.execPath,['--check','src/phase17-runtime.js'],{cwd:ROOT,encoding:'utf8'});record('phase17-module-syntax',phase17Syntax.status===0,phase17Syntax.stderr.trim());

const passed=rows.filter(row=>row.pass).length,failed=rows.length-passed;for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` — ${row.detail}`:''}`);console.log(`RESULT ${passed} passed, ${failed} failed`);process.exitCode=failed?1:0;
