import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';

const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..');
const contract=JSON.parse(fs.readFileSync(path.join(here,'contract.json'),'utf8'));
const rows=[],record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.webp':'image/webp','.json':'application/json; charset=utf-8'};
function server(){return http.createServer((request,response)=>{const pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),target=path.resolve(root,relative);if(target!==root&&!target.startsWith(root+path.sep)){response.writeHead(403).end();return}fs.readFile(target,(error,data)=>{if(error){response.writeHead(404).end();return}response.writeHead(200,{'content-type':mime[path.extname(target)]||'application/octet-stream','cache-control':'no-store'}).end(data)})})}
async function listen(instance){await new Promise((resolve,reject)=>{instance.once('error',reject);instance.listen(0,'127.0.0.1',resolve)});return`http://127.0.0.1:${instance.address().port}`}
async function dismiss(page){for(let n=0;n<50;n++){const state=await page.evaluate(()=>{const shown=node=>{const rect=node.getBoundingClientRect(),style=getComputedStyle(node);return rect.width>0&&rect.height>0&&style.display!=='none'&&style.visibility!=='hidden'};const overlay=[...document.querySelectorAll('[data-overlay]')].filter(shown).at(-1);if(!overlay)return'done';const button=[...overlay.querySelectorAll('[data-modal-close],[data-phase13-story="skip"],[data-phase13-tutorial-action="skip"],[data-phase15-tutorial-action="skip"],[data-phase16-tutorial-action="skip"]')].find(shown);if(button){button.click();return'click'}document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));return'escape'});if(state==='done')return true;await page.waitForTimeout(60)}return false}
async function storage(page,reset=false){return page.evaluate(({key,reset})=>{if(reset)window.__PHASE24K_WRITES__=0;const raw=localStorage.getItem(key);let revision=null;try{revision=JSON.parse(raw)?.saveMeta?.revision??null}catch{}return{raw,revision,writes:window.__PHASE24K_WRITES__||0}}, {key:contract.storageKey,reset})}
async function exercise(browser,baseURL,viewport,reduced=false){const prefix=`${viewport.id}-${reduced?'reduced':'normal'}`,errors=[],failedRequests=[];const context=await browser.newContext({viewport:{width:viewport.width,height:viewport.height},reducedMotion:reduced?'reduce':'no-preference'});await context.addInitScript(()=>{const prior=Storage.prototype.setItem;Object.defineProperty(window,'__PHASE24K_WRITES__',{configurable:false,writable:true,value:0});Storage.prototype.setItem=function(...args){window.__PHASE24K_WRITES__++;return prior.apply(this,args)}});const page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',error=>errors.push(`pageerror:${error.stack||error.message}`));page.on('console',message=>{if(['warning','error'].includes(message.type()))errors.push(`console.${message.type()}:${message.text()}`)});page.on('requestfailed',request=>failedRequests.push(`${request.url()}:${request.failure()?.errorText||'failed'}`));const step=(id,pass,detail='')=>record(`${prefix}-${id}`,pass,detail);
 try{
  const response=await page.goto(`${baseURL}/index.html?phase24k=${prefix}`,{waitUntil:'domcontentloaded',timeout:60000});await dismiss(page);await page.waitForSelector('[data-phase24k-village-speech]');await page.waitForTimeout(250);
  step('boot-current-schema',response?.ok()===true&&await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).schemaVersion===14,contract.storageKey));
  const fetched=await page.evaluate(async assets=>Object.fromEntries(await Promise.all(assets.map(async asset=>[asset,(await fetch(asset,{cache:'no-store'})).status]))),Object.values(contract.assets));
  step('all-assets-load',Object.values(fetched).every(status=>status===200),fetched);step('no-failed-requests',failedRequests.length===0,failedRequests);
  let before=await storage(page,true);
  const village=await page.evaluate(()=>{const speech=document.querySelector('[data-phase24k-village-speech]'),character=document.querySelector('[data-phase24k-village-character]'),hide=document.querySelector('[data-phase24k-speaker-hide]');return{speech:!!speech,character:!!character,hide:hide?.getBoundingClientRect().width>=44&&hide?.getBoundingClientRect().height>=44}});step('village-speaker-starts-visible-with-touch-close',village.speech&&village.character&&village.hide,village);
  await page.locator('[data-phase24k-speaker-hide]').click();let hidden=await page.evaluate(()=>({speech:document.querySelector('[data-phase24k-village-speech]')?.hidden,character:document.querySelector('[data-phase24k-village-character]')?.hidden,show:!document.querySelector('[data-phase24k-speaker-show]')?.hidden}));step('village-hide-removes-quote-and-character-together',hidden.speech&&hidden.character&&hidden.show,hidden);
  await page.locator('[data-nav="fellows"]').click();await page.locator('[data-nav="village"]').click();hidden=await page.evaluate(()=>({speech:document.querySelector('[data-phase24k-village-speech]')?.hidden,character:document.querySelector('[data-phase24k-village-character]')?.hidden}));step('village-hidden-state-survives-session-navigation',hidden.speech&&hidden.character,hidden);await page.locator('[data-phase24k-speaker-show]').click();
  let after=await storage(page);step('village-controls-are-save-neutral',before.raw===after.raw&&before.revision===after.revision&&after.writes===0,{before:{revision:before.revision},after:{revision:after.revision,writes:after.writes}});
  await page.locator('[data-phase24k-speaker-hide]').click();await page.reload({waitUntil:'domcontentloaded',timeout:30000});await dismiss(page);await page.waitForSelector('[data-phase24k-village-speech]');const reloadedSpeaker=await page.evaluate(()=>({speech:document.querySelector('[data-phase24k-village-speech]')?.hidden,character:document.querySelector('[data-phase24k-village-character]')?.hidden}));step('village-speaker-resets-visible-after-reload',reloadedSpeaker.speech===false&&reloadedSpeaker.character===false,reloadedSpeaker);
  before=await storage(page,true);const invoker=page.locator('[data-player-profile]').first();await invoker.focus();await invoker.click();await page.waitForSelector('[data-phase24k-wayfarer-profile]');await page.waitForFunction(()=>document.querySelector('[data-phase24k-wayfarer-profile-art] img')?.naturalWidth>0);const profile=await page.evaluate(()=>{const modal=document.querySelector('[data-phase24k-wayfarer-profile]'),img=modal?.querySelector('[data-phase24k-wayfarer-profile-art] img'),close=modal?.querySelector('.phase24k-wayfarer-profile-close'),rect=img?.getBoundingClientRect(),closeRect=close?.getBoundingClientRect();return{count:modal?.querySelectorAll('[data-phase24k-wayfarer-profile-art]').length,natural:[img?.naturalWidth,img?.naturalHeight],height:rect?.height,close:[closeRect?.width,closeRect?.height],nonRoster:modal?.dataset.playerRosterMember,roadmap:!!modal?.querySelector('[data-player-roadmap]'),labelled:modal?.getAttribute('aria-labelledby')==='everstead-modal-title'}});step('top-right-profile-shows-full-wayfarer-art',profile.count===1&&profile.natural[0]===1024&&profile.natural[1]===1536&&profile.height>=Math.min(470,viewport.height*.6)&&profile.close.every(value=>value>=44)&&profile.nonRoster==='false'&&profile.roadmap&&profile.labelled,profile);await page.keyboard.press('Escape');const focusReturned=await page.evaluate(()=>document.activeElement?.matches?.('[data-player-profile]')===true);after=await storage(page);step('profile-open-close-is-save-neutral-and-returns-focus',before.raw===after.raw&&after.writes===0&&focusReturned,{writes:after.writes,rawEqual:before.raw===after.raw,focusReturned});
  await page.locator('[data-nav="fellows"]').click();await page.waitForSelector('[data-phase24k-fellowship-hero] img');await page.waitForFunction(()=>document.querySelector('[data-phase24k-fellowship-hero] img')?.naturalWidth>0);const fellowship=await page.evaluate(()=>{const screen=document.querySelector('[data-phase24k-fellowship]'),hero=screen?.querySelector('[data-phase24k-fellowship-hero]'),heroImg=hero?.querySelector('img'),cards=[...screen?.querySelectorAll('.roster-grid [data-fellow]')||[]],tabs=[...screen?.querySelectorAll('.tabs [data-roster]')||[]],ribbon=[...screen?.querySelectorAll('[data-phase24k-panel-toggle]')||[]];return{background:getComputedStyle(screen).backgroundImage,hero:hero?.getBoundingClientRect(),heroImage:heroImg?.naturalWidth,cards:cards.length,cardColumns:new Set(cards.slice(0,3).map(card=>Math.round(card.getBoundingClientRect().left))).size,tabs:tabs.map(node=>[node.getBoundingClientRect().width,node.getBoundingClientRect().height]),ribbon:ribbon.map(node=>[node.getBoundingClientRect().width,node.getBoundingClientRect().height]),panels:[...screen?.querySelectorAll('[data-phase24k-disclosure]')||[]].map(node=>node.hidden),overflow:document.body.scrollWidth<=innerWidth}});step('fellowship-is-art-first-and-preserves-roster',fellowship.background.includes('fellowship-hall-phase24k.webp')&&fellowship.hero?.height>=200&&fellowship.heroImage>0&&fellowship.cards===18&&fellowship.cardColumns===(viewport.width<=360?2:3)&&fellowship.tabs.length===4&&fellowship.tabs.every(([,height])=>height>=44)&&fellowship.ribbon.every(([,height])=>height>=44)&&fellowship.panels.every(Boolean)&&fellowship.overflow,fellowship);
  before=await storage(page,true);await page.locator('[data-phase24k-panel-toggle="might"]').click();let disclosures=await page.evaluate(()=>[...document.querySelectorAll('[data-phase24k-disclosure]')].map(node=>({key:node.dataset.phase24kDisclosure,hidden:node.hidden})));await page.locator('[data-phase24k-panel-toggle="path"]').click();let disclosures2=await page.evaluate(()=>[...document.querySelectorAll('[data-phase24k-disclosure]')].map(node=>({key:node.dataset.phase24kDisclosure,hidden:node.hidden})));after=await storage(page);step('fellowship-drawers-are-exclusive-and-save-neutral',disclosures.filter(item=>!item.hidden).map(item=>item.key).join()==='might'&&disclosures2.filter(item=>!item.hidden).map(item=>item.key).join()==='path'&&before.raw===after.raw&&after.writes===0,{disclosures,disclosures2,writes:after.writes});
  await page.locator('[data-nav="adventure"]').click();await page.waitForSelector('[data-phase24k-wayfarer-cutout]');await page.waitForFunction(()=>document.querySelector('[data-phase24k-wayfarer-cutout]')?.naturalWidth>0);const adventure=await page.evaluate(()=>{const scene=document.querySelector('[data-phase24k-adventure-scene]'),runner=scene?.querySelector('[data-phase24k-wayfarer-cutout]'),badge=scene?.querySelector('[data-phase24k-wayfarer-badge]'),sceneRect=scene?.getBoundingClientRect(),badgeRect=badge?.getBoundingClientRect(),stages=[...document.querySelectorAll('[data-campaign-stage]')];return{background:getComputedStyle(scene).backgroundImage,runner:[runner?.naturalWidth,runner?.naturalHeight],badge:[badgeRect?.width,badgeRect?.height],scene:[sceneRect?.top,sceneRect?.height],stages:stages.length,run:!!document.querySelector('[data-campaign-run]'),record:!!document.querySelector('[data-phase22b-campaign-record]'),overflow:document.body.scrollWidth<=innerWidth}});step('adventure-is-painted-and-preserves-campaign',adventure.background.includes('broken-roads-phase24k.webp')&&adventure.runner[0]===1024&&adventure.runner[1]===1536&&adventure.badge.every(value=>value>=44)&&adventure.scene[1]>=(viewport.width<=360?245:340)&&adventure.stages===10&&adventure.run&&adventure.record&&adventure.overflow,adventure);
  before=await storage(page,true);await page.locator('[data-phase24k-wayfarer-badge]').click();await page.waitForSelector('[data-phase24k-wayfarer-profile]');await page.keyboard.press('Escape');after=await storage(page);step('campaign-wayfarer-profile-path-is-save-neutral',before.raw===after.raw&&after.writes===0,{writes:after.writes});
  if(reduced){const animation=await page.evaluate(()=>getComputedStyle(document.querySelector('[data-phase24k-wayfarer-cutout]')).animationDuration);step('reduced-motion-stops-wayfarer-animation',String(animation).split(',').every(value=>Number.parseFloat(value)===0),animation)}
 }catch(error){step('journey-fatal',false,error.stack||error.message)}
 step('zero-warning-error-console',errors.length===0,errors);await context.close();
}

const selectedViewports=process.env.PHASE24K_VIEWPORT?contract.viewports.filter(viewport=>viewport.id===process.env.PHASE24K_VIEWPORT):contract.viewports;
const selectedMotions=process.env.PHASE24K_MOTION==='normal'?[false]:process.env.PHASE24K_MOTION==='reduced'?[true]:[false,true];
if(!selectedViewports.length)throw new Error(`Unknown PHASE24K_VIEWPORT: ${process.env.PHASE24K_VIEWPORT}`);
const instance=server();let browser;
try{const baseURL=await listen(instance);browser=await chromium.launch({headless:true});for(const viewport of selectedViewports)for(const reduced of selectedMotions)await exercise(browser,baseURL,viewport,reduced)}finally{if(browser)await browser.close();instance.closeAllConnections?.();await new Promise(resolve=>instance.close(resolve))}
const failed=rows.filter(row=>!row.pass);for(const row of failed)console.error(`FAIL ${row.id}${row.detail?` · ${row.detail}`:''}`);console.log(`RESULT ${rows.length-failed.length} passed, ${failed.length} failed`);if(failed.length)process.exitCode=1;
