(() => {
  'use strict';
  const CHANNEL='everstead-phase-14-independent',byId=id=>document.getElementById(id),escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),row=(id,actual,detail='')=>({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)});
  async function loadJson(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.json()}
  function realm(fixtures,phase13,viewport){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),config={channel:CHANNEL,nonce,viewport,fixtures,phase13};frame.name=JSON.stringify(config);frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0`;let timer;const finish=(error,value)=>{clearTimeout(timer);removeEventListener('message',receive);frame.remove();error?reject(error):resolve(value)},receive=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=(event.data.results||[]).map(item=>({...item,id:`${viewport.id}-${item.id}`}));if(event.data.errors?.length&&!rows.some(item=>item.id.endsWith('zero-warning-error-console')&&!item.pass))rows.push(row(`${viewport.id}-captured-errors`,false,event.data.errors.join('\n')));finish(null,rows)};timer=setTimeout(()=>finish(new Error(`${viewport.id} timed out`)),180000);addEventListener('message',receive);frame.src=`./realm.html?qa=1&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  function render(mode,rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('mode').textContent=mode;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)} · observed ${item.actual?'true':'false'} · expected true${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_14_INDEPENDENT_RESULT__={mode,passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const [fixtures,phase13]=await Promise.all([loadJson('./fixtures/contract-fixtures.json'),loadJson('../phase-13-independent/fixtures/contract-fixtures.json')]),rows=[];rows.push(row('fixture-contract-v1',fixtures.contractVersion===1&&fixtures.bridgeVersion==='phase-13-independent-qa-v1'));rows.push(row('fixture-five-first-covenant-scenes',fixtures.phase13StoryIds.length===5&&JSON.stringify(fixtures.phase13StoryIds)===JSON.stringify(phase13.storyIds)));rows.push(row('fixture-save-matrix',Object.keys(fixtures.saveFixtures).length===8&&['fresh','midgame','migrated','established','corrupt','offline','claimReady','tutorialReady'].every(id=>fixtures.saveFixtures[id])));rows.push(row('fixture-static-twelve-facility-tuples',fixtures.facilities.length===12));rows.push(row('fixture-static-facility-economy-disabled',fixtures.productionEnabled===false));rows.push(row('fixture-thirty-eight-cast',fixtures.actorIds.length===38&&phase13.fellowIds.length+phase13.familyIds.length===38));rows.push(row('four-isolated-realms',fixtures.viewports.length===4&&fixtures.viewports.some(item=>item.width===1024)&&fixtures.viewports.some(item=>item.reducedMotion)));for(const viewport of fixtures.viewports)rows.push(...await realm(fixtures,phase13,viewport));render('CANDIDATE',rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render('FATAL',[row('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
