(()=>{
  'use strict';
  const CHANNEL='everstead-phase-24a-balance-report-v1';
  const byId=id=>document.getElementById(id);
  const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])])):value;
  const render=value=>JSON.stringify(stable(value),null,2);
  async function loadJson(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.json()}
  function realm(recipes){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),config={channel:CHANNEL,nonce,recipes};frame.name=JSON.stringify(config);frame.style.cssText='position:absolute;left:-20000px;top:0;width:390px;height:844px;border:0';let timer;const finish=(error,value)=>{clearTimeout(timer);removeEventListener('message',receive);frame.remove();error?reject(error):resolve(value)},receive=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;finish(null,event.data)};timer=setTimeout(()=>finish(new Error('Phase 24A report realm timed out')),120000);addEventListener('message',receive);frame.src=`./realm.html?qa=1&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const recipes=await loadJson('./fixtures/recipes.json'),captured=await realm(recipes);if(captured.errors?.length)throw new Error(captured.errors.join('\n'));const report={contractId:recipes.contractId,contractVersion:recipes.contractVersion,frozenNow:recipes.frozenNow,authority:captureAuthority(captured),profiles:captured.profiles,historicalMigrationComparisons:recipes.historicalMigrationComparisons,nearCapQaEvidence:recipes.nearCapQaEvidence,collectionsPlanningBoundary:{currentStatus:'reserved-inactive',currentContributionBps:0,currentMultiplier:1,forwardAuthority:'Decision 40',staleAppendixLanguageImplemented:false}};byId('mode').textContent='CAPTURED';byId('profiles').textContent=String(report.profiles.length);byId('errors').textContent='0';byId('phase24-report').textContent=render(report);window.__EVERSTEAD_PHASE24A_BALANCE_REPORT__=stable(report)}catch(error){byId('mode').textContent='FATAL';byId('errors').textContent='1';byId('fatal').textContent=error.stack||error.message;byId('phase24-report').textContent=''}finally{byId('run').disabled=false}}
  function captureAuthority(captured){return{definitions:captured.definitions,productionSources:captured.productionSources,neutrality:captured.neutrality,nativeStorageAccesses:captured.nativeStorageAccesses}}
  byId('run').onclick=run;run();
})();
