(() => {
  'use strict';
  const CHANNEL='everstead-phase-3',inlineJson=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  function installRuntime(config){
    const slots=new Map(Object.entries(config.slots)),nativeSetTimeout=window.setTimeout.bind(window),nativeClearTimeout=window.clearTimeout.bind(window);let saveIndex=0,transactionIndex=0;
    const nativeStorageAccesses=[],errors=[];let nativeStorageInstrumented=false;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    window.__PHASE_3_CONFIG__=config;window.__PHASE_3_SLOTS__=slots;window.__PHASE_3_ERRORS__=errors;window.__PHASE_3_NATIVE_STORAGE_ACCESSES__=nativeStorageAccesses;window.__PHASE_3_NATIVE_STORAGE_INSTRUMENTED__=nativeStorageInstrumented;
    window.addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));window.addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const runtime={storage:{getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>slots.set(String(key),String(value)),removeItem:key=>slots.delete(String(key))},clock:{now:()=>config.now,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.5,confirm:()=>true,ids:{save:()=>`save-p3-browser-${++saveIndex}`,transaction:()=>`tx-p3-browser-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};if(config.features)runtime.features=config.features;window.__EVERSTEAD_RUNTIME__=runtime;
  }
  function runSuite(){
    const config=window.__PHASE_3_CONFIG__,slots=window.__PHASE_3_SLOTS__,results=[],add=(id,pass,detail='')=>results.push({id,pass:Boolean(pass),detail:String(detail)}),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),click=selector=>{const node=document.querySelector(selector);if(node)node.click();return node},send=()=>parent.postMessage({channel:'everstead-phase-3',nonce:config.nonce,results,errors:window.__PHASE_3_ERRORS__.slice()},'*');
    (async()=>{await wait(450);const bridge=window.__EVERSTEAD_QA__;if(!config.expectBridge){add('encoded-query-bridge-absent',bridge===undefined);add('encoded-query-zero-errors',window.__PHASE_3_ERRORS__.length===0,window.__PHASE_3_ERRORS__.join('\n'));send();return}
      add('bridge-present',Boolean(bridge));add('viewport-exact',innerWidth===config.viewport.width&&innerHeight===config.viewport.height,`${innerWidth}x${innerHeight}`);add('no-horizontal-overflow',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);const first=bridge.snapshot();add('schema4-snapshot',first.ok&&first.state.schemaVersion===4);add('canonical-family-shape',first.ok&&Object.values(first.state.family).every(item=>Number.isFinite(item.intimacy)&&Number.isInteger(item.rarity)&&Number.isSafeInteger(item.shards)&&Object.hasOwn(item,'assignedBuildingId')&&Array.isArray(item.claimedIntimacyMilestoneIds)&&!Object.hasOwn(item,'progress')&&!Object.hasOwn(item,'level')));add('starter-gift',first.state.gifts===1);
      if(config.mode==='fresh'){add('fresh-assignments',first.state.family.elara.assignedBuildingId==='hearth'&&first.state.family.tamsin.assignedBuildingId==='training'&&first.state.family.isolde.assignedBuildingId==='archives');add('fresh-checkpoints-empty',!slots.has(config.keys.backupV1)&&!slots.has(config.keys.backupV2)&&!slots.has(config.keys.backupV3))}
      if(config.mode==='schema3'){add('schema3-checkpoint-exact',slots.get(config.keys.backupV3)===config.originalActiveRaw);add('schema3-no-retro-drops',Object.values(first.state.familyDrops.buildings).every(item=>item.nextRollOrdinal===0))}
      if(config.mode==='legacy'){add('legacy-v0-exact',slots.get(config.keys.backupV0)===config.originalActiveRaw);add('legacy-all-checkpoints',[1,2,3].every(version=>JSON.parse(slots.get(config.keys[`backupV${version}`])).schemaVersion===version));add('legacy-unicode',first.state.oaths.some(oath=>oath.title==='Fixture café review 🌵'))}
      if(config.mode==='disabled'){const flags=bridge.flags();add('all-disabled',flags.ok&&Object.values(flags.features).every(value=>value===false));const before=slots.get(config.keys.active),refused=['story','tower','trade','patrol-start','operation-start'].map(name=>bridge.act(name));add('disabled-actions-refused',refused.every(value=>!value.ok));add('disabled-zero-write',slots.get(config.keys.active)===before)}else{
        click('[data-nav="fellows"]');click('[data-roster="family"]');add('three-family-cards',document.querySelectorAll('[data-family].char-card').length===3);let text=document.querySelector('main.screen')?.textContent||'';add('family-roster-copy',text.includes('Intimacy')&&text.includes('Gift available')&&!/Relationship \d|Saved progress|Future links/.test(text));click('[data-family="elara"]');text=document.querySelector('#overlay')?.textContent||'';add('family-profile-copy',text.includes('INTIMACY')&&text.includes('GIVE 1 GIFT')&&text.includes('Linked Fellow bonuses')&&!/Blessing|Deepen|Affection/.test(text));const giftBefore=bridge.snapshot().state.family.elara.intimacy;click('[data-modal-act="give-family-gift"]');add('gift-ui-persists',bridge.snapshot().state.family.elara.intimacy===giftBefore+10&&bridge.snapshot().state.gifts===0);
        click('[data-modal-close]');click('[data-nav="village"]');click('[data-building="command"]');const beforeRate=bridge.diagnostics().diagnostics.buildingRateComponents.command.rate,select=document.querySelector('[data-family-assignment]');select.value='elara';select.dispatchEvent(new Event('change',{bubbles:true}));const assigned=bridge.snapshot().state;add('assignment-move',assigned.family.elara.assignedBuildingId==='command'&&!Object.values(assigned.family).some(item=>item.assignedBuildingId==='hearth'));add('assignment-rate-change',bridge.diagnostics().diagnostics.buildingRateComponents.command.rate>beforeRate);const second=document.querySelector('[data-family-assignment]');second.value='isolde';second.dispatchEvent(new Event('change',{bubbles:true}));add('assignment-replace',bridge.snapshot().state.family.isolde.assignedBuildingId==='command'&&bridge.snapshot().state.family.elara.assignedBuildingId===null);const third=document.querySelector('[data-family-assignment]');third.value='';third.dispatchEvent(new Event('change',{bubbles:true}));add('assignment-unassign',bridge.snapshot().state.family.isolde.assignedBuildingId===null);
        const powerBefore=bridge.diagnostics().diagnostics.fellowPowerComponents.lyra.effectivePower;bridge.controls.grant({resource:'gifts',amount:1});bridge.act('family-gift',{id:'elara'});const powerAfter=bridge.diagnostics().diagnostics.fellowPowerComponents.lyra.effectivePower;add('linked-power-change',powerAfter>powerBefore);const refuse=bridge.act('family-ascend',{id:'elara'});add('ascend-refusal',!refuse.ok);const shardsBefore=bridge.snapshot().state.family.elara.shards;bridge.controls.grant({resource:'familyShards',id:'elara',amount:20});const ascend=bridge.act('family-ascend',{id:'elara'});add('ascend-success',ascend.ok&&ascend.state.family.elara.rarity===2&&ascend.state.family.elara.shards===shardsBefore,JSON.stringify({ok:ascend.ok,error:ascend.error,rarity:ascend.state?.family?.elara?.rarity,shards:ascend.state?.family?.elara?.shards,expectedShards:shardsBefore}));
        bridge.clock.freeze(config.now);bridge.clock.advance(14_400_000);const claim=bridge.act('collect'),claimed=bridge.snapshot().state,ordinals=Object.fromEntries(Object.entries(claimed.familyDrops.buildings).map(([id,value])=>[id,value.nextRollOrdinal]));add('deterministic-four-hour-roll',Object.values(ordinals).every(item=>item===1),JSON.stringify(ordinals));add('claim-receipt',claim.ok&&claimed.familyDrops.claimSequence===1&&claimed.familyDrops.lastReceipt.sequence===1);const sequence=claimed.familyDrops.claimSequence;bridge.act('collect');add('double-claim-no-receipt',bridge.snapshot().state.familyDrops.claimSequence===sequence);
        const diagnostic=bridge.diagnostics();add('diagnostics-v3-checkpoint',diagnostic.ok&&Object.hasOwn(diagnostic.diagnostics,'preV4Backup'));add('diagnostics-no-roll',diagnostic.diagnostics.familyDrops.buildings.hearth.nextRollOrdinal===bridge.snapshot().state.familyDrops.buildings.hearth.nextRollOrdinal);add('safe-export-six-slots',bridge.recovery.export().data.exportVersion===4&&bridge.recovery.export().data.preV4BackupKey===config.keys.backupV3);const reload=bridge.recovery.reload();add('reload-persists-family',reload.ok&&reload.state.family.elara.rarity===2&&reload.state.familyDrops.claimSequence===sequence);
      }
      add('native-storage-instrumented',window.__PHASE_3_NATIVE_STORAGE_INSTRUMENTED__===true);add('zero-native-storage-calls',window.__PHASE_3_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_3_NATIVE_STORAGE_ACCESSES__.join(','));add('realm-zero-errors',window.__PHASE_3_ERRORS__.length===0,window.__PHASE_3_ERRORS__.join('\n'));send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }
  (async()=>{const config=JSON.parse(window.name);window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error('index.html: HTTP '+response.status);const source=await response.text(),firstScript=source.indexOf('<script>');if(firstScript<0)throw new Error('Production script is missing');const bootstrap='<script>('+installRuntime.toString()+')('+inlineJson(config)+')<\/script>',suite='<script>('+runSuite.toString()+')()<\/script>',instrumented=source.slice(0,firstScript)+bootstrap+source.slice(firstScript).replace('</body>',suite+'</body>');document.open();document.write(instrumented);document.close()})().catch(error=>parent.postMessage({channel:'everstead-phase-3',nonce:'unknown',results:[{id:'realm-loader-fatal',pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
