import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const qaRoot=dirname(fileURLToPath(import.meta.url)),repoRoot=resolve(qaRoot,'..','..');
const read=path=>readFileSync(resolve(repoRoot,path)),htmlBytes=read('index.html'),html=htmlBytes.toString('utf8'),source=html.match(/<script>([\s\S]*?)<\/script>/)?.[1];
const schemaOneRaw=read('qa/gate-0b/fixtures/current-v1.txt').toString('utf8'),legacyRaw=read('qa/fixtures/representative-v0.1.txt').toString('utf8'),futureRaw=read('qa/gate-0b/fixtures/future-v99.txt').toString('utf8'),corruptRaw=read('qa/gate-0b/fixtures/corrupt-json.txt').toString('utf8');
const keys={active:'oathforge_new_world_proto_v01',backupV0:'oathforge_new_world_proto_v01__raw_backup_v0_1',backupV1:'oathforge_new_world_proto_v01__raw_backup_v1',backupV2:'oathforge_new_world_proto_v01__raw_backup_v2',backupV3:'oathforge_new_world_proto_v01__raw_backup_v3',staging:'oathforge_new_world_proto_v01__staging'};
const checks=[],check=(id,pass,detail='')=>checks.push({id,pass:Boolean(pass),detail:String(detail)}),clone=value=>JSON.parse(JSON.stringify(value)),sha256=value=>createHash('sha256').update(value).digest('hex');
const stateFrom=(raw,version=4)=>{try{const value=JSON.parse(raw);return value?.schemaVersion===version?value:null}catch{return null}};
const rawIdentity=raw=>{if(raw===null)return'null:0:00000000';let hash=2166136261;for(let index=0;index<raw.length;index++){hash^=raw.charCodeAt(index);hash=Math.imul(hash,16777619)}return`fnv1a32:${raw.length}:${(hash>>>0).toString(16).padStart(8,'0')}`},stableHost=(saveId,buildingId,ordinal,salt)=>{const value=`${saveId}\u001f${buildingId}\u001f${ordinal}\u001f${salt}`;let hash=2166136261;for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return(hash>>>0)/4294967296},staging=(activeRaw,state,source)=>{const activeState=stateFrom(activeRaw,state.schemaVersion-1);return JSON.stringify({stagingVersion:1,transactionId:`qa-${state.schemaVersion}`,baseSaveId:activeState?.saveMeta.saveId??null,baseRevision:activeState?.saveMeta.revision??null,sourceRawIdentity:rawIdentity(activeRaw),source,state})};

function instrument(script){const hook=`globalThis.__P3_INTERNAL__=Object.freeze({state:()=>clone(S),validation:(v,n=CURRENT_SCHEMA_VERSION)=>validation(v,n),migrate:(v,n,c,t=CURRENT_SCHEMA_VERSION)=>runMigrations(v,n,c,t),familyConfig:()=>clone(FAMILY_CONFIG),familyBonus:(id,v=S)=>linkedFamilyBonusComponents(id,v),buildingBonus:(id,v=S)=>familyBuildingBonusComponents(id,v),components:(id,v=S)=>effectiveFellowPowerComponents(id,v),rate:(id,v=S,at=runtimeNow())=>buildingRateComponents(id,v,at),stable:stableRandomUnit,recipient:(id,ordinal,v=S)=>familyRollRecipient(id,ordinal,v),settle:(elapsed,v=S)=>settleFamilyDrops(elapsed,v),offline:(at,v=S)=>offlineClaimPreview(at,v),giftResult:familyGiftResult,canonicalPending:canonicalPendingCollection,assign:assignFamilyToBuilding,gift:giveFamilyGift,ascend:ascendFamily,collect:collectGold,complete:completeOath,undo:applyOathUndo,building:openBuilding,family:openFamily,fellow:openFellow,roster:rosterScreen,export:safePersistenceExport,diagnostics:persistenceDiagnostics,runtime:()=>clone({raw:PERSISTED_RAW,identity:PERSISTED_IDENTITY,blocked:PERSISTENCE_BLOCKED,notice:PERSISTENCE_NOTICE,outcome:PERSISTENCE_OUTCOME,stale:PERSISTENCE_STALE})});`;return script.replace(/\n\}\)\(\);\s*$/,match=>'\n'+hook+'\n'+match)}
function makeDate(now){const NativeDate=Date;return class FixedDate extends NativeDate{constructor(...args){super(...(args.length?args:[now.value]))}static now(){return now.value}static parse(v){return NativeDate.parse(v)}static UTC(...args){return NativeDate.UTC(...args)}}}
function runRealm(options={}){
  const slots=new Map(Object.entries(options.initialSlots??{}));
  for(const [name,key]of Object.entries({activeRaw:keys.active,backupRaw:keys.backupV0,preV2BackupRaw:keys.backupV1,preV3BackupRaw:keys.backupV2,preV4BackupRaw:keys.backupV3,stagingRaw:keys.staging}))if(Object.hasOwn(options,name)){const value=options[name];if(value===null)slots.delete(key);else slots.set(key,String(value))}
  const storageLog=[],persistenceLog=[],fault={enabled:false,remaining:1,operation:'setItem',step:null,key:null,...(options.fault??{})};
  const storage=options.storage??{getItem(key){storageLog.push(['get',String(key)]);if(fault.enabled&&!fault.step&&fault.remaining>0&&fault.operation==='getItem'&&(!fault.key||fault.key===key)){fault.remaining--;throw new Error('injected read')}return slots.get(String(key))??null},setItem(key,value){storageLog.push(['set',String(key)]);if(fault.enabled&&!fault.step&&fault.remaining>0&&fault.operation==='setItem'&&(!fault.key||fault.key===key)){fault.remaining--;throw new Error('injected write')}slots.set(String(key),String(value))},removeItem(key){storageLog.push(['remove',String(key)]);if(fault.enabled&&!fault.step&&fault.remaining>0&&fault.operation==='removeItem'&&(!fault.key||fault.key===key)){fault.remaining--;throw new Error('injected remove')}slots.delete(String(key))}};
  const node=()=>({innerHTML:'',dataset:{},style:{},className:'',classList:{add(){},remove(){}}}),nodes={'#app':node(),'#overlay':node(),'#toast':node()};
  const document={querySelector:selector=>nodes[selector]??null,querySelectorAll:()=>[],documentElement:{scrollWidth:options.width??390}};
  const clock={value:options.now??Date.parse('2026-08-27T18:00:00Z')},FixedDate=makeDate(clock);let timerId=0;const timers=new Map(),clockAdapter={now:()=>clock.value,setTimeout(callback){const id=++timerId;timers.set(id,callback);if(!options.deferTimers)callback();return id},clearTimeout:id=>timers.delete(id)};
  const nativeStorage=options.nativeStorage??{getItem(){throw new Error('native get')},setItem(){throw new Error('native set')},removeItem(){throw new Error('native remove')}};
  const runtime={clock:clockAdapter,random:()=>.5,storage,confirm:()=>true,ids:{save:()=>options.saveId??'save-phase-3',transaction:(()=>{let n=0;return()=>`tx-p3-${++n}`})()},qa:options.qa??{allowDestructive:true,isolatedStorage:true}};
  if(Object.hasOwn(options,'features'))runtime.features=options.features;
  const location={protocol:'http:',hostname:'127.0.0.1',search:options.search??'?qa=1'},listeners={};
  const context={console,Math:Object.create(Math),Date:FixedDate,document,localStorage:nativeStorage,confirm:()=>true,setTimeout:callback=>{callback();return 1},clearTimeout(){},crypto:{randomUUID:()=> 'native-id'},URLSearchParams,location,history:{pushState(){}},addEventListener(type,fn){(listeners[type]??=[]).push(fn)}};
  context.window=context;context.globalThis=context;context.__EVERSTEAD_RUNTIME__=runtime;context.__EVERSTEAD_PERSISTENCE_TEST__={storage,operationLog:persistenceLog,fault(info){if(fault.enabled&&fault.step&&fault.remaining>0&&info.step===fault.step&&info.operation===fault.operation){fault.remaining--;return{type:'throw',message:'injected step failure'}}return null},status:{}};
  vm.createContext(context);let thrown=null;try{vm.runInContext(instrument(source),context,{timeout:30000})}catch(error){thrown=error}
  return{context,slots,storageLog,persistenceLog,nodes,clock,timers,listeners,nativeStorage,thrown,fault};
}
const evaluate=(run,expression)=>vm.runInContext(expression,run.context,{timeout:10000}),activeRaw=run=>run.slots.get(keys.active)??null,active=run=>stateFrom(activeRaw(run)),writes=run=>run.storageLog.filter(([op])=>op==='set'||op==='remove').length,snapshot=run=>Object.fromEntries(Object.values(keys).map(key=>[key,run.slots.get(key)??null]));
const act=(run,name,payload={})=>evaluate(run,`__EVERSTEAD_QA__.act(${JSON.stringify(name)},${JSON.stringify(payload)})`),grant=(run,resource,amount,id)=>evaluate(run,`__EVERSTEAD_QA__.controls.grant(${JSON.stringify({resource,amount,...(id?{id}: {})})})`);

check('production-source-present',Boolean(source));
check('schema4-static',source.includes('CURRENT_SCHEMA_VERSION=4')&&source.includes("PRE_V4_BACKUP_KEY=NS+'__raw_backup_v3'")&&source.includes("id:'schema-3-to-4'"));
check('single-family-power-hook',(source.match(/function linkedFamilyBonusComponents\(/g)||[]).length===1&&(source.match(/function effectiveFellowPowerComponents\(/g)||[]).length===1);
check('deterministic-roll-static',source.includes('function stableRandomUnit(')&&source.includes("'family-shard-success'")&&source.includes("'family-shard-recipient'")&&source.includes("'family-gift'"));
check('legacy-active-ui-absent',!source.includes('Family · Phase 3 preview')&&!source.includes('Saved progress')&&!source.includes('future links')&&!source.includes('Relationship progress +')&&!source.includes('deepen Family bonds'));

const fresh=runRealm({activeRaw:null,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null});
check('fresh-no-throw',fresh.thrown===null,fresh.thrown?.stack??'');check('fresh-schema4',active(fresh)?.schemaVersion===4);check('fresh-starter-gift',active(fresh)?.gifts===1);check('fresh-assignments',active(fresh)?.family.elara.assignedBuildingId==='hearth'&&active(fresh)?.family.tamsin.assignedBuildingId==='training'&&active(fresh)?.family.isolde.assignedBuildingId==='archives');check('fresh-command-unassigned',!Object.values(active(fresh)?.family??{}).some(item=>item.assignedBuildingId==='command'));check('fresh-no-checkpoints',![keys.backupV0,keys.backupV1,keys.backupV2,keys.backupV3].some(key=>fresh.slots.has(key)));
check('fresh-carry-context-canonical',Object.entries(active(fresh)?.familyDrops?.buildings??{}).every(([id,roll])=>roll.carryContext?.buildingLevel===1&&roll.carryContext.assignedFamilyId===({hearth:'elara',training:'tamsin',archives:'isolde',command:null})[id]));

const fromOne=runRealm({activeRaw:schemaOneRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null}),schemaTwoRaw=fromOne.slots.get(keys.backupV2),schemaThreeRaw=fromOne.slots.get(keys.backupV3);
check('schema1-to4',active(fromOne)?.schemaVersion===4,fromOne.thrown?.stack??'');check('six-slot-lineage',fromOne.slots.get(keys.backupV0)===schemaOneRaw&&fromOne.slots.get(keys.backupV1)===schemaOneRaw&&stateFrom(schemaTwoRaw,2)&&stateFrom(schemaThreeRaw,3));check('receipt-order',active(fromOne)?.saveMeta.appliedMigrations.map(item=>item.id).join(',')==='legacy-v0.1-to-1,schema-1-to-2,schema-2-to-3,schema-3-to-4'||active(fromOne)?.saveMeta.appliedMigrations.map(item=>item.id).join(',')==='schema-1-to-2,schema-2-to-3,schema-3-to-4');check('migrated-assignment-null',Object.values(active(fromOne)?.family??{}).every(item=>item.assignedBuildingId===null));check('migrated-starter-gift-once',active(fromOne)?.gifts===1);
check('pending-undo-migrated-v2',active(fromOne)?.undo?.version===2&&Object.hasOwn(active(fromOne).undo.inverse,'gifts')&&Object.hasOwn(active(fromOne).undo.expected,'oathGiftTracker')&&(!active(fromOne).undo.inverse.family||Object.hasOwn(active(fromOne).undo.inverse.family,'intimacy')));
const migratedUndoRun=runRealm({activeRaw:schemaOneRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null}),migratedInverse=clone(active(migratedUndoRun).undo.inverse),migratedUndoApplied=evaluate(migratedUndoRun,'__P3_INTERNAL__.undo()');check('pending-undo-applies-after-migration',migratedUndoApplied===true&&active(migratedUndoRun).undo===null&&active(migratedUndoRun).gifts===migratedInverse.gifts&&JSON.stringify(active(migratedUndoRun).oathGiftTracker)===JSON.stringify(migratedInverse.oathGiftTracker)&&(!migratedInverse.family||active(migratedUndoRun).family[migratedInverse.family.id].intimacy===migratedInverse.family.intimacy));
const fromTwo=runRealm({activeRaw:schemaTwoRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null}),fromThree=runRealm({activeRaw:schemaThreeRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null}),fromLegacy=runRealm({activeRaw:legacyRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null});
check('schema2-to4',active(fromTwo)?.schemaVersion===4);check('schema3-to4',active(fromThree)?.schemaVersion===4);check('schema3-checkpoint-exact',fromThree.slots.get(keys.backupV3)===schemaThreeRaw);check('legacy-to4',active(fromLegacy)?.schemaVersion===4);check('legacy-unicode',active(fromLegacy)?.oaths.some(item=>item.title==='Fixture café review 🌵'&&item.notes.includes('測試')));
check('migration-carry-context-boundary',Object.entries(active(fromThree)?.familyDrops?.buildings??{}).every(([id,roll])=>roll.rollCarryMs===0&&roll.carryContext?.assignedFamilyId===null&&roll.carryContext?.buildingLevel===stateFrom(schemaThreeRaw,3).buildings[id].level));
const evolvedV3=clone(stateFrom(schemaThreeRaw,3));evolvedV3.family.elara.progress+=.75;evolvedV3.saveMeta.revision+=4;evolvedV3.saveMeta.updatedAt+=4_000;evolvedV3.saveMeta.source='phase-2-gameplay';const evolvedV3Raw=JSON.stringify(evolvedV3),evolvedV3Run=runRealm({activeRaw:evolvedV3Raw,backupRaw:schemaThreeRaw,preV2BackupRaw:schemaOneRaw,preV3BackupRaw:schemaTwoRaw,preV4BackupRaw:null,stagingRaw:null});
check('evolved-schema3-lineage-migrates',active(evolvedV3Run)?.schemaVersion===4&&active(evolvedV3Run)?.family.elara.intimacy===evolvedV3.family.elara.progress&&evolvedV3Run.slots.get(keys.backupV3)===evolvedV3Raw,evolvedV3Run.thrown?.stack??evolvedV3Run.nodes['#app'].innerHTML);const evolvedV3Reload=runRealm({initialSlots:Object.fromEntries(evolvedV3Run.slots),now:evolvedV3.saveMeta.updatedAt+86_400_000});check('evolved-schema3-lineage-reloads',active(evolvedV3Reload)?.schemaVersion===4&&active(evolvedV3Reload)?.saveMeta.saveId===evolvedV3.saveMeta.saveId&&evolvedV3Reload.nodes['#app'].innerHTML.includes('VILLAGE'),evolvedV3Reload.nodes['#app'].innerHTML);
const evolvedV2=clone(stateFrom(schemaTwoRaw,2));evolvedV2.family.tamsin.progress+=.5;evolvedV2.saveMeta.revision+=3;evolvedV2.saveMeta.updatedAt+=3_000;evolvedV2.saveMeta.source='phase-1-gameplay';const evolvedV2Raw=JSON.stringify(evolvedV2),evolvedV2Run=runRealm({activeRaw:evolvedV2Raw,backupRaw:schemaTwoRaw,preV2BackupRaw:schemaOneRaw,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null});check('evolved-schema2-lineage-migrates',active(evolvedV2Run)?.schemaVersion===4&&active(evolvedV2Run)?.family.tamsin.intimacy===evolvedV2.family.tamsin.progress&&evolvedV2Run.slots.get(keys.backupV2)===evolvedV2Raw,evolvedV2Run.nodes['#app'].innerHTML);
const sameIdForeign=clone(evolvedV3);sameIdForeign.family.elara.progress+=1;const sameIdForeignRaw=JSON.stringify(sameIdForeign),sameIdForeignRun=runRealm({activeRaw:evolvedV3Raw,backupRaw:sameIdForeignRaw,preV2BackupRaw:schemaOneRaw,preV3BackupRaw:schemaTwoRaw,preV4BackupRaw:null,stagingRaw:null});check('same-revision-foreign-raw-backup-zero-write',writes(sameIdForeignRun)===0&&activeRaw(sameIdForeignRun)===evolvedV3Raw&&sameIdForeignRun.slots.get(keys.backupV0)===sameIdForeignRaw,writes(sameIdForeignRun));
const later=runRealm({initialSlots:Object.fromEntries(fromLegacy.slots),now:Date.parse('2026-08-28T18:00:00Z')});check('schema4-idempotent',active(later)?.saveMeta.appliedMigrations.filter(item=>item.id==='schema-3-to-4').length===1&&active(later)?.gifts===1);

const fractionalV3=clone(stateFrom(schemaThreeRaw,3));fractionalV3.family.elara.progress=150.5;fractionalV3.family.elara.level=999;fractionalV3.family.elara.futureUnicode='家族🌵';const fractionalRun=runRealm({activeRaw:JSON.stringify(fractionalV3),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null});
check('fractional-intimacy-exact',active(fractionalRun)?.family.elara.intimacy===150.5);check('legacy-level-no-value',active(fractionalRun)?.family.elara.rarity===1&&active(fractionalRun)?.family.elara.shards===0);check('crossed-milestone-marked',active(fractionalRun)?.family.elara.claimedIntimacyMilestoneIds.join(',')==='intimacy-150');check('unknown-unicode-preserved',active(fractionalRun)?.family.elara.futureUnicode==='家族🌵');check('reserved-shadows-removed',!['level','progress','blessing','calculatedPower','assignment'].some(key=>Object.hasOwn(active(fractionalRun)?.family.elara??{},key)));
grant(fractionalRun,'gifts',1);const fractionalBefore=active(fractionalRun).family.elara.intimacy;const fractionalGift=act(fractionalRun,'family-gift',{id:'elara'});check('fractional-intimacy-gift-exact',fractionalGift.ok&&active(fractionalRun).family.elara.intimacy-fractionalBefore===10&&active(fractionalRun).family.elara.intimacy===160.5);

const maxSafeState=clone(active(fresh));maxSafeState.family.elara.intimacy=Number.MAX_SAFE_INTEGER;const maxSafeRaw=JSON.stringify(maxSafeState),maxSafeRun=runRealm({activeRaw:maxSafeRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null}),maxSafeWrites=writes(maxSafeRun),maxSafeBefore=activeRaw(maxSafeRun),maxSafeGift=act(maxSafeRun,'family-gift',{id:'elara'});check('max-safe-intimacy-gift-zero-write',!maxSafeGift.ok&&writes(maxSafeRun)===maxSafeWrites&&activeRaw(maxSafeRun)===maxSafeBefore&&evaluate(maxSafeRun,'__P3_INTERNAL__.runtime().blocked')===null);
check('max-value-gift-result-refused',evaluate(fresh,'__P3_INTERNAL__.giftResult(Number.MAX_VALUE)')===null);
const maxValueState=clone(active(fresh));maxValueState.family.elara.intimacy=Number.MAX_VALUE;const maxValueRaw=JSON.stringify(maxValueState),maxValueRun=runRealm({activeRaw:maxValueRaw,backupRaw:maxValueRaw,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null});check('max-value-intimacy-schema4-refused',writes(maxValueRun)===0&&activeRaw(maxValueRun)===maxValueRaw&&/Save Needs Attention/.test(maxValueRun.nodes['#app'].innerHTML));

for(const [label,mutate]of [['unsafe-gifts',value=>value.gifts=Number.MAX_SAFE_INTEGER+1],['unsafe-family-shards',value=>value.family.elara.shards=Number.MAX_SAFE_INTEGER+1],['duplicate-assignment',value=>value.family.isolde.assignedBuildingId='hearth'],['legacy-shadow',value=>value.family.elara.level=2],['bad-roll-ordinal',value=>value.familyDrops.buildings.hearth.nextRollOrdinal=Number.MAX_SAFE_INTEGER+1],['bad-tracker',value=>value.oathGiftTracker.uniqueOathIds=['o1','o1']],['foreign-family-key',value=>value.family.foreign=clone(value.family.elara)],['foreign-pending-shard-key',value=>value.familyDrops.pendingShards.foreign=9],['foreign-building-drop-key',value=>value.familyDrops.buildings.foreign=clone(value.familyDrops.buildings.hearth)],['foreign-receipt-shard-key',value=>{value.familyDrops.lastReceipt={sequence:1,claimedAt:value.lastSeen,gold:0,gifts:0,shards:{elara:0,tamsin:0,isolde:0,foreign:9}}}]]){const value=clone(active(fresh));mutate(value);const raw=JSON.stringify(value),run=runRealm({activeRaw:raw,backupRaw:raw,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null});check(`invalid-${label}-refused`,writes(run)===0&&activeRaw(run)===raw&&/Save Needs Attention/.test(run.nodes['#app'].innerHTML))}

const formulaRun=runRealm({activeRaw:activeRaw(fresh),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null}),formulaState=active(formulaRun);
const migrationNow=Date.parse('2026-08-27T18:00:00Z'),stagedTwo=clone(stateFrom(schemaTwoRaw,2)),stagedThree=evaluate(formulaRun,`__P3_INTERNAL__.migrate(${JSON.stringify(stagedTwo)},2,{source:'schema-2',now:${migrationNow}},3)`),stagedFour=evaluate(formulaRun,`__P3_INTERNAL__.migrate(${JSON.stringify(stateFrom(schemaThreeRaw,3))},3,{source:'schema-3',now:${migrationNow}},4)`),phaseOneStageRun=runRealm({activeRaw:schemaOneRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:staging(schemaOneRaw,stagedTwo,'schema-1-migration')}),phaseTwoStageRun=runRealm({activeRaw:schemaTwoRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:staging(schemaTwoRaw,stagedThree,'schema-2-migration')}),phaseThreeStageRun=runRealm({activeRaw:schemaThreeRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:staging(schemaThreeRaw,stagedFour,'schema-3-migration')});
check('phase1-schema2-staging-recovery',active(phaseOneStageRun)?.schemaVersion===4&&!phaseOneStageRun.slots.has(keys.staging)&&stateFrom(phaseOneStageRun.slots.get(keys.backupV2),2)&&stateFrom(phaseOneStageRun.slots.get(keys.backupV3),3),phaseOneStageRun.nodes['#app'].innerHTML);check('phase2-schema3-staging-recovery',active(phaseTwoStageRun)?.schemaVersion===4&&!phaseTwoStageRun.slots.has(keys.staging)&&phaseTwoStageRun.slots.get(keys.backupV2)===schemaTwoRaw&&JSON.stringify(stateFrom(phaseTwoStageRun.slots.get(keys.backupV3),3))===JSON.stringify(stagedThree),phaseTwoStageRun.nodes['#app'].innerHTML);check('phase3-schema4-staging-recovery',active(phaseThreeStageRun)?.schemaVersion===4&&!phaseThreeStageRun.slots.has(keys.staging)&&phaseThreeStageRun.slots.get(keys.backupV3)===schemaThreeRaw&&active(phaseThreeStageRun)?.saveMeta.appliedMigrations.filter(item=>item.id==='schema-3-to-4').length===1,phaseThreeStageRun.nodes['#app'].innerHTML);
const tamperedMigratable=clone(stagedFour);tamperedMigratable.family.elara.intimacy+=1;const tamperedMigratableRaw=staging(schemaThreeRaw,tamperedMigratable,'schema-3-migration'),tamperedMigratableOptions={activeRaw:schemaThreeRaw,backupRaw:schemaOneRaw,preV2BackupRaw:schemaOneRaw,preV3BackupRaw:schemaTwoRaw,preV4BackupRaw:schemaThreeRaw,stagingRaw:tamperedMigratableRaw},tamperedMigratableRun=runRealm(tamperedMigratableOptions),tamperedMigratableSlots={activeRaw:schemaThreeRaw,backupRaw:schemaOneRaw,preV2BackupRaw:schemaOneRaw,preV3BackupRaw:schemaTwoRaw,preV4BackupRaw:schemaThreeRaw,stagingRaw:tamperedMigratableRaw};check('migratable-generic-schema4-staging-zero-write',writes(tamperedMigratableRun)===0&&JSON.stringify(snapshot(tamperedMigratableRun))===JSON.stringify({[keys.active]:tamperedMigratableSlots.activeRaw,[keys.backupV0]:tamperedMigratableSlots.backupRaw,[keys.backupV1]:tamperedMigratableSlots.preV2BackupRaw,[keys.backupV2]:tamperedMigratableSlots.preV3BackupRaw,[keys.backupV3]:tamperedMigratableSlots.preV4BackupRaw,[keys.staging]:tamperedMigratableSlots.stagingRaw})&&/Save Needs Attention/.test(tamperedMigratableRun.nodes['#app'].innerHTML),`writes=${writes(tamperedMigratableRun)}`);
const recoveredFour=evaluate(formulaRun,`__P3_INTERNAL__.migrate(${JSON.stringify(stateFrom(schemaThreeRaw,3))},3,{source:'recovered-schema-3-backup',now:${migrationNow}},4)`),missingTampered=clone(recoveredFour);missingTampered.gifts=99;missingTampered.family.elara.shards=77;const missingTamperedRaw=staging(null,missingTampered,'schema-3-backup-recovery'),missingTamperedRun=runRealm({activeRaw:null,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:schemaThreeRaw,stagingRaw:missingTamperedRaw});check('missing-active-resource-injection-staging-zero-write',writes(missingTamperedRun)===0&&activeRaw(missingTamperedRun)===null&&missingTamperedRun.slots.get(keys.backupV3)===schemaThreeRaw&&missingTamperedRun.slots.get(keys.staging)===missingTamperedRaw&&/Save Needs Attention/.test(missingTamperedRun.nodes['#app'].innerHTML),`writes=${writes(missingTamperedRun)}`);
const foreignMissingRaw=staging(null,recoveredFour,'foreign-source'),foreignMissingRun=runRealm({activeRaw:null,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:schemaThreeRaw,stagingRaw:foreignMissingRaw});check('missing-active-foreign-source-staging-zero-write',writes(foreignMissingRun)===0&&activeRaw(foreignMissingRun)===null&&foreignMissingRun.slots.get(keys.backupV3)===schemaThreeRaw&&foreignMissingRun.slots.get(keys.staging)===foreignMissingRaw);
const exactMissingRaw=staging(null,recoveredFour,'schema-3-backup-recovery'),exactMissingRun=runRealm({activeRaw:null,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:schemaThreeRaw,stagingRaw:exactMissingRaw});check('missing-active-exact-schema4-staging-recovers',active(exactMissingRun)?.schemaVersion===4&&active(exactMissingRun)?.gifts===1&&active(exactMissingRun)?.family.elara.shards===0&&!exactMissingRun.slots.has(keys.staging));
const currentBaseRaw=activeRaw(fresh),currentBase=active(fresh),currentPending=clone(currentBase);currentPending.prosperity+=1;currentPending.saveMeta.revision++;currentPending.saveMeta.updatedAt++;currentPending.saveMeta.source='gameplay';const currentPendingRaw=JSON.stringify({stagingVersion:1,transactionId:'qa-current',baseSaveId:currentBase.saveMeta.saveId,baseRevision:currentBase.saveMeta.revision,sourceRawIdentity:rawIdentity(currentBaseRaw),source:'gameplay',state:currentPending}),currentPendingRun=runRealm({activeRaw:currentBaseRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:currentPendingRaw});check('current-mutation-staging-still-recovers',active(currentPendingRun)?.prosperity>=currentPending.prosperity&&!currentPendingRun.slots.has(keys.staging),currentPendingRun.nodes['#app'].innerHTML);
const committedCurrentRaw=JSON.stringify({stagingVersion:1,transactionId:'qa-committed-current',baseSaveId:currentBase.saveMeta.saveId,baseRevision:currentBase.saveMeta.revision-1,sourceRawIdentity:'committed-source',source:'gameplay',state:currentBase}),committedCurrentRun=runRealm({activeRaw:currentBaseRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:committedCurrentRaw});check('committed-current-staging-cleanup-preserved',active(committedCurrentRun)?.saveMeta.saveId===currentBase.saveMeta.saveId&&!committedCurrentRun.slots.has(keys.staging));
const close=(left,right)=>Math.abs(left-right)<1e-12,hearth=evaluate(formulaRun,"__P3_INTERNAL__.buildingBonus('hearth')");check('building-formula-components',hearth.baseBonus===.01&&close(hearth.intimacyBonus,.022)&&hearth.rarityBonus===0&&hearth.specialtyBonus===.01&&close(hearth.bonus,.042)&&close(hearth.multiplier,1.042));
const capState=clone(formulaState);capState.family.elara.intimacy=999999;capState.family.elara.rarity=5;const capped=evaluate(formulaRun,`__P3_INTERNAL__.buildingBonus('hearth',${JSON.stringify(capState)})`);check('building-bonus-cap',capped.intimacyBonus===.10&&capped.rarityBonus===.08&&capped.bonus===.20);
const lyra=evaluate(formulaRun,"__P3_INTERNAL__.familyBonus('lyra')");check('lyra-two-links',lyra.links.map(item=>item.id).join(',')==='elara,isolde');check('linked-formula-exact',close(lyra.links[0].intimacyBonus,.011)&&lyra.links[0].rarityBonus===0&&close(lyra.links[0].bonus,.011));check('linked-aggregate-exact',close(lyra.bonus,.0168)&&close(lyra.multiplier,1.0168));
const linkCap=clone(formulaState);for(const member of Object.values(linkCap.family)){member.intimacy=999999;member.rarity=5}const lyraCap=evaluate(formulaRun,`__P3_INTERNAL__.familyBonus('lyra',${JSON.stringify(linkCap)})`);check('linked-per-and-aggregate-caps',lyraCap.links.every(item=>item.bonus===.09)&&lyraCap.bonus===.12);
const power=evaluate(formulaRun,"__P3_INTERNAL__.components('lyra')");check('family-power-active',power.familyBondMultiplier===1.0168&&power.effectivePower===Math.round(power.afterBondMilestone*1*1*1.0168*1));check('power-round-once',power.formulaOrder.at(-1)==='round'&&power.unroundedPower!==power.effectivePower);

const actionRun=runRealm({activeRaw:activeRaw(fresh),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null});
let result=act(actionRun,'family-assign',{familyId:'elara',buildingId:'command'});check('assignment-move',result.ok&&result.state.family.elara.assignedBuildingId==='command'&&!Object.values(result.state.family).some(item=>item.assignedBuildingId==='hearth'));result=act(actionRun,'family-assign',{familyId:'isolde',buildingId:'command'});check('assignment-replace',result.ok&&result.state.family.isolde.assignedBuildingId==='command'&&result.state.family.elara.assignedBuildingId===null);result=act(actionRun,'family-assign',{familyId:null,buildingId:'command'});check('assignment-unassign',result.ok&&result.state.family.isolde.assignedBuildingId===null);
grant(actionRun,'gifts',4);for(let index=0;index<4;index++)act(actionRun,'family-gift',{id:'elara'});check('gift-intimacy-only',active(actionRun).family.elara.intimacy===150&&active(actionRun).gifts===1&&active(actionRun).family.elara.shards===5&&active(actionRun).family.elara.claimedIntimacyMilestoneIds.join(',')==='intimacy-150');grant(actionRun,'gifts',1);act(actionRun,'family-gift',{id:'elara'});check('milestone-once',active(actionRun).family.elara.shards===5);const refusedAsc=act(actionRun,'family-ascend',{id:'elara'});check('ascend-refusal',!refusedAsc.ok&&active(actionRun).family.elara.rarity===1);grant(actionRun,'familyShards',15,'elara');const asc=act(actionRun,'family-ascend',{id:'elara'});check('ascend-success-exact',asc.ok&&asc.state.family.elara.rarity===2&&asc.state.family.elara.shards===0&&asc.state.family.elara.intimacy===160);

const interval=14_400_000,rollBase=clone(active(fresh));rollBase.lastGoldAt=rollBase.familyDrops.eligibleAt=Date.parse('2026-08-27T18:00:00Z');rollBase.lastSeen=rollBase.lastGoldAt;const below=clone(rollBase);evaluate(formulaRun,`__P3_INTERNAL__.settle(${interval-1},${JSON.stringify(below)})`);check('roll-interval-minus-one',Object.values(below.familyDrops.buildings).every(item=>item.nextRollOrdinal===0));const exact=clone(rollBase),exactReport=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(exact)},r=__P3_INTERNAL__.settle(${interval},s);return{s,r}})()`);check('roll-exact-interval',exactReport.r.rolls===4&&Object.values(exactReport.s.familyDrops.buildings).every(item=>item.nextRollOrdinal===1));const day=clone(rollBase),dayReport=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(day)},r=__P3_INTERNAL__.settle(${6*interval},s);return{s,r}})()`);check('roll-24h-count',dayReport.r.rolls===24&&Object.values(dayReport.s.familyDrops.buildings).every(item=>item.nextRollOrdinal===6));check('hearth-only-gift-channel',Object.entries(dayReport.r.byBuilding).every(([id,value])=>id==='hearth'||value.gifts===0));
const pity=clone(rollBase);for(const def of Object.keys(pity.familyDrops.buildings))pity.familyDrops.buildings[def].shardDrought=7;const pityReport=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(pity)},r=__P3_INTERNAL__.settle(${interval},s);return{s,r}})()`);check('eighth-roll-pity',Object.values(pityReport.r.shards).reduce((a,b)=>a+b,0)===4&&Object.values(pityReport.s.familyDrops.buildings).every(item=>item.shardDrought===0));
const combined=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(rollBase)};__P3_INTERNAL__.settle(${3*interval},s);return s})()`),split=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(rollBase)};__P3_INTERNAL__.settle(${interval},s);__P3_INTERNAL__.settle(${2*interval},s);return s})()`);check('split-combined-drop-equality',JSON.stringify(combined.familyDrops)===JSON.stringify(split.familyDrops));
let carryRecipientOrdinal=0;while(!(stableHost(rollBase.saveMeta.saveId,'hearth',carryRecipientOrdinal,'family-shard-recipient')>1/3&&stableHost(rollBase.saveMeta.saveId,'hearth',carryRecipientOrdinal,'family-shard-recipient')<.75))carryRecipientOrdinal++;
const carryAssignment=clone(rollBase);carryAssignment.familyDrops.buildings.hearth.nextRollOrdinal=carryRecipientOrdinal;carryAssignment.familyDrops.buildings.hearth.shardDrought=7;const carryAssignmentResult=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(carryAssignment)};__P3_INTERNAL__.settle(${3*3600000},s);const carried=JSON.parse(JSON.stringify(s.familyDrops.buildings.hearth));s.family.elara.assignedBuildingId='command';const report=__P3_INTERNAL__.settle(${3600000},s);return{s,carried,report}})()`);check('partial-carry-preserves-old-assignment',carryAssignmentResult.carried.rollCarryMs===3*3600000&&carryAssignmentResult.carried.carryContext.assignedFamilyId==='elara'&&carryAssignmentResult.report.byBuilding.hearth.shards.elara===1&&carryAssignmentResult.report.byBuilding.hearth.shards.tamsin===0&&carryAssignmentResult.report.byBuilding.hearth.shards.isolde===0);
const carryExact=clone(carryAssignment);const carryExactResult=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(carryExact)};__P3_INTERNAL__.settle(${3*3600000},s);s.family.elara.assignedBuildingId='command';__P3_INTERNAL__.settle(${3600000},s);return s.familyDrops.buildings.hearth})()`);check('partial-carry-exact-completion-context',carryExactResult.rollCarryMs===0&&carryExactResult.carryContext.assignedFamilyId===null&&carryExactResult.nextRollOrdinal===carryRecipientOrdinal+1);
const carryMultiple=clone(carryAssignment);const carryMultipleResult=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(carryMultiple)};__P3_INTERNAL__.settle(${3*3600000},s);s.family.elara.assignedBuildingId='command';const report=__P3_INTERNAL__.settle(${10*3600000},s);return{roll:s.familyDrops.buildings.hearth,report}})()`);check('partial-carry-multiple-roll-remainder-context',carryMultipleResult.report.byBuilding.hearth.rolls===3&&carryMultipleResult.roll.rollCarryMs===3600000&&carryMultipleResult.roll.carryContext.assignedFamilyId===null&&carryMultipleResult.roll.nextRollOrdinal===carryRecipientOrdinal+3);
const carryLevel=clone(rollBase);let carryLevelOrdinal=0;while(!(stableHost(carryLevel.saveMeta.saveId,'hearth',carryLevelOrdinal,'family-shard-success')>=.10&&stableHost(carryLevel.saveMeta.saveId,'hearth',carryLevelOrdinal,'family-shard-success')<.11))carryLevelOrdinal++;carryLevel.familyDrops.buildings.hearth.nextRollOrdinal=carryLevelOrdinal;const carryLevelResult=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(carryLevel)};__P3_INTERNAL__.settle(${3*3600000},s);s.buildings.hearth.level=2;const report=__P3_INTERNAL__.settle(${3600000},s);return{roll:s.familyDrops.buildings.hearth,report}})()`);check('partial-carry-preserves-old-building-level',carryLevelResult.report.byBuilding.hearth.shards.elara===0&&carryLevelResult.report.byBuilding.hearth.shards.tamsin===0&&carryLevelResult.report.byBuilding.hearth.shards.isolde===0&&carryLevelResult.roll.shardDrought===1&&carryLevelResult.roll.carryContext.buildingLevel===2);
const carryReloadState=clone(carryAssignment);carryReloadState.lastGoldAt=carryReloadState.familyDrops.eligibleAt=rollBase.lastGoldAt;const carryReloadRun=runRealm({activeRaw:JSON.stringify(carryReloadState),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null,now:rollBase.lastGoldAt});evaluate(carryReloadRun,`__EVERSTEAD_QA__.clock.freeze(${rollBase.lastGoldAt});__EVERSTEAD_QA__.clock.advance(${3*3600000})`);act(carryReloadRun,'family-assign',{familyId:'elara',buildingId:'command'});const persistedCarry=clone(active(carryReloadRun).familyDrops.buildings.hearth),carryReloaded=runRealm({initialSlots:Object.fromEntries(carryReloadRun.slots),now:rollBase.lastGoldAt+4*3600000});check('partial-carry-reload-provenance',persistedCarry.rollCarryMs===3*3600000&&persistedCarry.carryContext.assignedFamilyId==='elara'&&active(carryReloaded)?.familyDrops.pendingShards.elara===1&&active(carryReloaded)?.familyDrops.buildings.hearth.rollCarryMs===0);
const stableA=evaluate(formulaRun,"__P3_INTERNAL__.stable('save','hearth',7,'family-gift')"),stableB=evaluate(formulaRun,"__P3_INTERNAL__.stable('save','hearth',7,'family-gift')");check('stable-unit-retry',stableA===stableB&&stableA>=0&&stableA<1);
const assignedCounts={elara:0,tamsin:0,isolde:0};for(let ordinal=0;ordinal<4000;ordinal++)assignedCounts[evaluate(formulaRun,`__P3_INTERNAL__.recipient('hearth',${ordinal})`)]++;check('assigned-weight-75',Math.abs(assignedCounts.elara/4000-.75)<.025,JSON.stringify(assignedCounts));const unassignedState=clone(rollBase);unassignedState.family.elara.assignedBuildingId=null;const uniformCounts={elara:0,tamsin:0,isolde:0};for(let ordinal=0;ordinal<3000;ordinal++)uniformCounts[evaluate(formulaRun,`__P3_INTERNAL__.recipient('hearth',${ordinal},${JSON.stringify(unassignedState)})`)]++;check('unassigned-uniform-weight',Object.values(uniformCounts).every(value=>Math.abs(value/3000-1/3)<.03),JSON.stringify(uniformCounts));

const timeState=clone(active(fresh));timeState.lastGoldAt=Date.UTC(2026,7,27,23,30);timeState.pendingGold=.625;let timePreview=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(timeState)};s.lastGoldAt=new Date(2026,7,27,23,30).getTime();return __P3_INTERNAL__.offline(new Date(2026,7,28,1,30).getTime(),s)})()`);check('offline-midnight-segmented',timePreview.elapsed===7_200_000&&timePreview.segments.length===2&&timePreview.pendingBefore===.625);timePreview=evaluate(formulaRun,`__P3_INTERNAL__.offline(${timeState.lastGoldAt+48*3_600_000},${JSON.stringify(timeState)})`);check('offline-24h-cap',timePreview.elapsed===86_400_000&&timePreview.nextLastGoldAt===timeState.lastGoldAt+48*3_600_000);timePreview=evaluate(formulaRun,`__P3_INTERNAL__.offline(${timeState.lastGoldAt-1},${JSON.stringify(timeState)})`);check('offline-clock-rollback-noop',timePreview.elapsed===0&&timePreview.nextLastGoldAt===timeState.lastGoldAt);const epochState=clone(timeState);epochState.lastGoldAt=0;timePreview=evaluate(formulaRun,`__P3_INTERNAL__.offline(3600000,${JSON.stringify(epochState)})`);check('offline-epoch-zero',timePreview.elapsed===3_600_000);timePreview=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(timeState)};s.lastGoldAt=NaN;return __P3_INTERNAL__.offline(${timeState.lastGoldAt},s)})()`);check('offline-invalid-timestamp-noop',timePreview.elapsed===0&&timePreview.timestampValid===false);
const rollbackForward=clone(rollBase),rollbackBefore=JSON.stringify(rollbackForward.familyDrops);evaluate(formulaRun,`__P3_INTERNAL__.settle(-60000,${JSON.stringify(rollbackForward)})`);const rollbackForwardResult=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(rollbackForward)};const negative=__P3_INTERNAL__.settle(-60000,s),forward=__P3_INTERNAL__.settle(${interval},s);return{s,negative,forward}})()`);check('drop-rollback-forward',rollbackForwardResult.negative.rolls===0&&rollbackBefore===JSON.stringify(rollbackForward.familyDrops)&&rollbackForwardResult.forward.rolls===4&&Object.values(rollbackForwardResult.s.familyDrops.buildings).every(item=>item.nextRollOrdinal===1));

const settleBeforeState=clone(active(fresh)),settleNow=Date.parse('2026-08-27T18:00:00Z');settleBeforeState.lastGoldAt=settleBeforeState.familyDrops.eligibleAt=settleNow;for(const item of Object.values(settleBeforeState.familyDrops.buildings))item.shardDrought=7;const expectedBefore=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(settleBeforeState)};__P3_INTERNAL__.settle(${interval},s);return s.familyDrops})()`),settleAction=runRealm({activeRaw:JSON.stringify(settleBeforeState),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null,now:settleNow});evaluate(settleAction,`__EVERSTEAD_QA__.clock.freeze(${settleNow})`);evaluate(settleAction,`__EVERSTEAD_QA__.clock.advance(${interval})`);const movedAfterSettle=act(settleAction,'family-assign',{familyId:'elara',buildingId:'command'}).state;check('settle-before-assignment',JSON.stringify(movedAfterSettle.familyDrops)===JSON.stringify(expectedBefore)&&movedAfterSettle.family.elara.assignedBuildingId==='command');
const entitlementState=clone(active(fresh));entitlementState.lastGoldAt=entitlementState.familyDrops.eligibleAt=settleNow;let assignedOrdinal=0,assignedUnit=stableHost(entitlementState.saveMeta.saveId,'hearth',assignedOrdinal,'family-shard-recipient');while(assignedUnit<1/3||assignedUnit>=.75)assignedUnit=stableHost(entitlementState.saveMeta.saveId,'hearth',++assignedOrdinal,'family-shard-recipient');entitlementState.familyDrops.buildings.hearth.nextRollOrdinal=assignedOrdinal;entitlementState.familyDrops.buildings.hearth.shardDrought=7;const entitlementOld=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(entitlementState)};__P3_INTERNAL__.settle(${interval},s);return s.familyDrops})()`),entitlementNew=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(entitlementState)};s.family.elara.assignedBuildingId='command';__P3_INTERNAL__.settle(${interval},s);return s.familyDrops})()`),entitlementRun=runRealm({activeRaw:JSON.stringify(entitlementState),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null,now:settleNow});evaluate(entitlementRun,`__EVERSTEAD_QA__.clock.freeze(${settleNow});__EVERSTEAD_QA__.clock.advance(${interval})`);const entitlementMoveResult=act(entitlementRun,'family-assign',{familyId:'elara',buildingId:'command'}),entitlementMoved=entitlementMoveResult.state;check('old-assignment-drop-entitlement',JSON.stringify(entitlementMoved.familyDrops)===JSON.stringify(entitlementOld)&&JSON.stringify(entitlementOld)!==JSON.stringify(entitlementNew)&&entitlementMoved.family.elara.assignedBuildingId==='command',JSON.stringify({ok:entitlementMoveResult.ok,blocked:evaluate(entitlementRun,'__P3_INTERNAL__.runtime().blocked'),actual:entitlementMoved.familyDrops,old:entitlementOld,next:entitlementNew}));
const levelState=clone(active(fresh));levelState.lastGoldAt=levelState.familyDrops.eligibleAt=settleNow;let thresholdOrdinal=0;while(!(stableHost(levelState.saveMeta.saveId,'hearth',thresholdOrdinal,'family-shard-success')>=.10&&stableHost(levelState.saveMeta.saveId,'hearth',thresholdOrdinal,'family-shard-success')<.11))thresholdOrdinal++;levelState.familyDrops.buildings.hearth.nextRollOrdinal=thresholdOrdinal;const oldLevelDrops=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(levelState)};__P3_INTERNAL__.settle(${interval},s);return s.familyDrops})()`),newLevelDrops=evaluate(formulaRun,`(()=>{const s=${JSON.stringify(levelState)};s.buildings.hearth.level=2;__P3_INTERNAL__.settle(${interval},s);return s.familyDrops})()`),levelRun=runRealm({activeRaw:JSON.stringify(levelState),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null,now:settleNow});evaluate(levelRun,`__EVERSTEAD_QA__.clock.freeze(${settleNow});__EVERSTEAD_QA__.clock.advance(${interval})`);const levelResult=act(levelRun,'building-upgrade',{id:'hearth'}),upgradedAfterSettle=levelResult.state;check('old-level-drop-entitlement',upgradedAfterSettle.buildings.hearth.level===2&&JSON.stringify(upgradedAfterSettle.familyDrops)===JSON.stringify(oldLevelDrops)&&JSON.stringify(oldLevelDrops)!==JSON.stringify(newLevelDrops),JSON.stringify({ok:levelResult.ok,blocked:evaluate(levelRun,'__P3_INTERNAL__.runtime().blocked'),actual:upgradedAfterSettle.familyDrops,old:oldLevelDrops,next:newLevelDrops,level:upgradedAfterSettle.buildings.hearth.level}));

const claimState=clone(active(fresh));claimState.pendingGold=42.75;claimState.familyDrops.pendingGifts=2;claimState.familyDrops.pendingShards={elara:3,tamsin:0,isolde:1};const claimRun=runRealm({activeRaw:JSON.stringify(claimState),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null});const firstClaim=act(claimRun,'collect'),firstState=active(claimRun),sequence=firstState.familyDrops.claimSequence,secondClaimRaw=activeRaw(claimRun),secondClaimWrites=writes(claimRun),secondClaim=act(claimRun,'collect');check('claim-atomic-transfer',firstClaim.ok&&firstState.gold===claimState.gold+42&&firstState.pendingGold===.75&&firstState.gifts===3&&firstState.family.elara.shards===3&&firstState.family.isolde.shards===1);check('claim-receipt-once',sequence===1&&firstState.familyDrops.lastReceipt.gold===42&&active(claimRun).familyDrops.claimSequence===sequence&&secondClaim.ok);check('immediate-double-claim-zero-write',secondClaim.changed===false&&activeRaw(claimRun)===secondClaimRaw&&writes(claimRun)===secondClaimWrites&&JSON.stringify(active(claimRun).familyDrops.lastReceipt)===JSON.stringify(firstState.familyDrops.lastReceipt));
const foreignPendingProbe=clone(claimState);foreignPendingProbe.pendingGold=0;foreignPendingProbe.familyDrops.pendingGifts=0;foreignPendingProbe.familyDrops.pendingShards={elara:0,tamsin:0,isolde:0,foreign:99};const canonicalProbe=evaluate(formulaRun,`__P3_INTERNAL__.canonicalPending(${JSON.stringify(foreignPendingProbe)})`);check('collection-ignores-foreign-family-keys',canonicalProbe.any===false&&canonicalProbe.hasShards===false&&Object.keys(canonicalProbe.shards).join(',')==='elara,tamsin,isolde');

const oathRun=runRealm({activeRaw:activeRaw(fresh),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null});const beforeIntimacy=active(oathRun).family.elara.intimacy;for(const id of ['o1','o2','o3','o4','o5'])act(oathRun,'complete-oath',{id});check('oath-fifth-unique-guarantee',active(oathRun).gifts===2&&active(oathRun).oathGiftTracker.awarded&&active(oathRun).oathGiftTracker.uniqueOathIds.length===5);check('oath-no-direct-intimacy',active(oathRun).family.elara.intimacy===beforeIntimacy);const undoState=clone(active(oathRun));const undoResult=evaluate(oathRun,'__P3_INTERNAL__.undo()');check('oath-undo-reverses-gift-tracker',undoResult===true&&active(oathRun).gifts===1&&!active(oathRun).oathGiftTracker.awarded&&active(oathRun).oathGiftTracker.uniqueOathIds.length===4);act(oathRun,'complete-oath',{id:'o5'});act(oathRun,'family-gift',{id:'elara'});const rawBeforeRefusal=activeRaw(oathRun),spentRefusal=evaluate(oathRun,'__P3_INTERNAL__.undo()');check('spent-gift-undo-refused-zero-write',spentRefusal===false&&activeRaw(oathRun)===rawBeforeRefusal);
const oathId='o1',oathDay=active(fresh).day,findSave=hit=>{for(let index=0;index<10000;index++){const id=`oath-${hit?'hit':'miss'}-${index}`,unit=stableHost(id,oathId,oathDay,'oath-gift');if(hit?unit<.05:unit>=.05)return id}throw new Error('Unable to find deterministic Oath test seed')},hitSave=findSave(true),missSave=findSave(false),hitRun=runRealm({activeRaw:null,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null,saveId:hitSave}),missRun=runRealm({activeRaw:null,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null,saveId:missSave});act(hitRun,'complete-oath',{id:oathId});act(missRun,'complete-oath',{id:oathId});check('oath-deterministic-hit',active(hitRun).gifts===2&&active(hitRun).oathGiftTracker.awarded);check('oath-deterministic-miss',active(missRun).gifts===1&&!active(missRun).oathGiftTracker.awarded&&active(missRun).oathGiftTracker.uniqueOathIds.join(',')===oathId);for(const id of ['o2','o3','o4','o5'])act(hitRun,'complete-oath',{id});check('oath-max-one-gift-per-day',active(hitRun).gifts===2&&active(hitRun).oathGiftTracker.uniqueOathIds.length===5);const recompleteRun=runRealm({activeRaw:null,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null,saveId:hitSave});act(recompleteRun,'complete-oath',{id:oathId});evaluate(recompleteRun,'__P3_INTERNAL__.undo()');act(recompleteRun,'complete-oath',{id:oathId});check('oath-undo-recompletion-replays',active(recompleteRun).gifts===2&&active(recompleteRun).oathGiftTracker.awarded&&active(recompleteRun).oathGiftTracker.uniqueOathIds.join(',')===oathId);

const staleRun=runRealm({activeRaw:activeRaw(fresh),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null}),staleWrites=writes(staleRun),staleRaw=activeRaw(staleRun);staleRun.listeners.storage[0]({storageArea:staleRun.nativeStorage,key:keys.active});const staleAction=act(staleRun,'family-assign',{familyId:'elara',buildingId:'command'});check('stale-tab-conflict-zero-write',!staleAction.ok&&writes(staleRun)===staleWrites&&activeRaw(staleRun)===staleRaw&&evaluate(staleRun,'__P3_INTERNAL__.runtime().blocked.kind')==='conflict');

for(const [label,raw]of [['future',futureRaw],['corrupt',corruptRaw]]){const run=runRealm({activeRaw:raw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null});check(`${label}-active-preserved`,activeRaw(run)===raw)}
for(const [label,slot,value]of [['foreign-v3','preV4BackupRaw',JSON.stringify({...stateFrom(schemaThreeRaw,3),saveMeta:{...stateFrom(schemaThreeRaw,3).saveMeta,saveId:'foreign'}})],['malformed-v3','preV4BackupRaw','{bad'],['foreign-staging','stagingRaw',JSON.stringify({stagingVersion:1,transactionId:'foreign',baseSaveId:null,baseRevision:null,sourceRawIdentity:'wrong',source:'foreign',state:active(fresh)})]]){const options={activeRaw:schemaThreeRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null,[slot]:value},run=runRealm(options);check(`${label}-zero-write`,writes(run)===0&&snapshot(run)[keys[slot==='preV4BackupRaw'?'backupV3':'staging']]===value,writes(run))}

for(const step of ['pre-v4-backup-write','staging-write','active-write','active-verify','staging-cleanup']){const run=runRealm({activeRaw:schemaThreeRaw,backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null,fault:{enabled:true,operation:step==='active-verify'?'getItem':step==='staging-cleanup'?'removeItem':'setItem',step}});check(`fault-${step}-no-duplicate-receipt`,active(run)?.saveMeta.appliedMigrations.filter(item=>item.id==='schema-3-to-4').length<=1||activeRaw(run)===schemaThreeRaw)}

const exportData=evaluate(formulaRun,'__P3_INTERNAL__.export()'),diagnostics=evaluate(formulaRun,'__P3_INTERNAL__.diagnostics()');check('export-v4-six-slot',exportData.exportVersion===4&&exportData.preV4BackupKey===keys.backupV3&&Object.hasOwn(exportData.readErrors,'preV4Backup'));check('diagnostics-family-no-roll',diagnostics.familyConfig.starterGifts===1&&diagnostics.familyDrops.buildings.hearth.nextRollOrdinal===active(formulaRun).familyDrops.buildings.hearth.nextRollOrdinal&&diagnostics.buildingRateComponents.hearth.familyAssignment.familyId==='elara');
check('campaign-gift-hook-neutral',diagnostics.familyConfig.campaignGiftChance===0);
const familyHtml=evaluate(formulaRun,"(()=>{__P3_INTERNAL__.family('elara');return document.querySelector('#overlay').innerHTML})()"),buildingHtml=evaluate(formulaRun,"(()=>{__P3_INTERNAL__.building('hearth');return document.querySelector('#overlay').innerHTML})()"),fellowHtml=evaluate(formulaRun,"(()=>{__P3_INTERNAL__.fellow('lyra');return document.querySelector('#overlay').innerHTML})()");check('family-ui-contract',/INTIMACY/.test(familyHtml)&&/GIVE 1 GIFT/.test(familyHtml)&&/Linked Fellow bonuses/.test(familyHtml)&&!/Saved progress|Blessing|Deepen/.test(familyHtml));check('building-ui-contract',/Family assignment/.test(buildingHtml)&&/Specialty/.test(buildingHtml)&&/Gold\/hr/.test(buildingHtml));check('fellow-ui-family-multiplier',/Linked Family/.test(fellowHtml)&&/Family/.test(fellowHtml));
const renderDrops=JSON.stringify(active(formulaRun).familyDrops),renderRevision=active(formulaRun).saveMeta.revision;evaluate(formulaRun,"__P3_INTERNAL__.roster();__P3_INTERNAL__.family('tamsin');__P3_INTERNAL__.building('training');__P3_INTERNAL__.fellow('cael')");check('render-does-not-roll-or-save',JSON.stringify(active(formulaRun).familyDrops)===renderDrops&&active(formulaRun).saveMeta.revision===renderRevision);

for(const operation of ['setItem','removeItem'])for(const [slotName,key]of Object.entries({activeRaw:keys.active,backupRaw:keys.backupV0,preV2BackupRaw:keys.backupV1,preV3BackupRaw:keys.backupV2,preV4BackupRaw:keys.backupV3,stagingRaw:keys.staging})){
  const run=runRealm({activeRaw:activeRaw(fresh),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null}),beforeSlots=snapshot(run),beforeState=JSON.stringify(active(run)),beforeApp=run.nodes['#app'].innerHTML,beforeOverlay=run.nodes['#overlay'].innerHTML,beforeToast=run.nodes['#toast'].innerHTML;
  run.fault.enabled=true;run.fault.operation=operation;run.fault.key=key;run.fault.remaining=1;run.fault.step=null;
  const value=operation==='setItem'?'fixture-value':null,payload={activeRaw:value,backupRaw:value,preV2BackupRaw:value,preV3BackupRaw:value,preV4BackupRaw:value,stagingRaw:value},result=evaluate(run,`__EVERSTEAD_QA__.controls.installFixture(${JSON.stringify(payload)})`);
  check(`fixture-${operation}-${slotName}-refused`,result.ok===false,result.error);check(`fixture-${operation}-${slotName}-six-slot-rollback`,JSON.stringify(snapshot(run))===JSON.stringify(beforeSlots));check(`fixture-${operation}-${slotName}-runtime-ui-rollback`,JSON.stringify(active(run))===beforeState&&run.nodes['#app'].innerHTML===beforeApp&&run.nodes['#overlay'].innerHTML===beforeOverlay&&run.nodes['#toast'].innerHTML===beforeToast);
}
{
  const run=runRealm({activeRaw:activeRaw(fresh),backupRaw:null,preV2BackupRaw:null,preV3BackupRaw:null,preV4BackupRaw:null,stagingRaw:null});run.fault.enabled=true;run.fault.operation='setItem';run.fault.key=keys.active;run.fault.remaining=2;run.fault.step=null;const result=evaluate(run,`__EVERSTEAD_QA__.controls.installFixture(${JSON.stringify({activeRaw:'next',backupRaw:'next',preV2BackupRaw:'next',preV3BackupRaw:'next',preV4BackupRaw:'next',stagingRaw:'next'})})`);check('fixture-rollback-failure-explicit',result.ok===false&&/rollback failed/i.test(result.error),result.error)
}

for(let index=0;index<120;index++){const value=clone(active(fresh)),id=['elara','tamsin','isolde'][index%3];value.family[id].intimacy=index*7.25;const result=evaluate(formulaRun,`__P3_INTERNAL__.validation(${JSON.stringify(value)}).ok`);check(`validation-matrix-${index}`,result)}

const passed=checks.filter(item=>item.pass).length,failed=checks.length-passed;for(const item of checks)console.log(`${item.pass?'PASS':'FAIL'} ${item.id}${item.detail?` :: ${item.detail}`:''}`);console.log(`\nPhase 3 CLI: ${passed}/${checks.length} passed`);console.log(`Artifact SHA-256: ${sha256(htmlBytes)}`);if(failed)process.exitCode=1;
