(()=>{
  'use strict';
  const CHANNEL='everstead-phase-24c2b-coordinator-v1',json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');
  function installRuntime(config){
    const slots=new Map(),writes=[],errors=[],nativeStorageAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);let saveIndex=0,transactionIndex=0,nativeStorageInstrumented=false;
    const memoryStorage={getItem:key=>{key=String(key);if(!config.viewport.supplyStorage)nativeStorageAccesses.push(`getItem:${key}`);return slots.get(key)??null},setItem:(key,value)=>{key=String(key);if(!config.viewport.supplyStorage)nativeStorageAccesses.push(`setItem:${key}`);writes.push({operation:'setItem',key,value:String(value)});slots.set(key,String(value))},removeItem:key=>{key=String(key);if(!config.viewport.supplyStorage)nativeStorageAccesses.push(`removeItem:${key}`);writes.push({operation:'removeItem',key});slots.delete(key)}};
    if(!config.viewport.supplyStorage)try{Object.defineProperty(window,'localStorage',{configurable:true,enumerable:true,value:memoryStorage})}catch(error){errors.push(`native-storage-surrogate ${error.message||error}`)}
    window.matchMedia=query=>({matches:config.viewport.reducedMotion&&query.includes('prefers-reduced-motion'),media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});
    try{const nativeStorage=window.localStorage;if(nativeStorage===memoryStorage)nativeStorageInstrumented=true;else for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)};nativeStorageInstrumented=true}}catch{}
    addEventListener('error',event=>{const target=event.target;if(target&&target!==window&&(target.src||target.href)){if(target.matches?.('img[data-roster-art],img[data-village-cutout],[data-phase23-companion-full-art],[data-phase23-companion-thumb]'))return;errors.push(`asset-error ${target.src||target.href}`)}else errors.push(String(event.error?.stack||event.message))},true);
    addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    Object.assign(window,{__P24C2B_CONFIG__:config,__P24C2B_SLOTS__:slots,__P24C2B_WRITES__:writes,__P24C2B_ERRORS__:errors,__P24C2B_NATIVE_ACCESSES__:nativeStorageAccesses,__P24C2B_NATIVE_INSTRUMENTED__:nativeStorageInstrumented});
    const runtime={clock:{now:()=>config.contract.frozenNow,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.999,confirm:()=>true,ids:{save:()=>`save-p24c2b-${++saveIndex}`,transaction:()=>`tx-p24c2b-${++transactionIndex}`},qa:{allowDestructive:config.viewport.allowDestructive,isolatedStorage:config.viewport.isolatedStorage}};
    if(config.viewport.supplyStorage)runtime.storage=memoryStorage;
    window.__EVERSTEAD_RUNTIME__=runtime;
  }
  function runSuite(){
    const config=window.__P24C2B_CONFIG__,f=config.contract,v=config.viewport,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),send=(errors=window.__P24C2B_ERRORS__.slice())=>parent.postMessage({channel:config.channel,nonce:config.nonce,results,errors},'*');
    const bridge=()=>window[f.bridge.global],safe=(label,operation)=>{try{return operation()}catch(error){add(`${label}-call`,false,error.stack||error.message);return null}},read=()=>safe('snapshot',()=>bridge()?.read?.snapshot?.()),call=name=>safe(name,()=>bridge()?.destructive?.[name]?.()),focusKey=()=>{const node=document.activeElement;if(!node)return null;return{id:node.id||'',tag:node.tagName||'',name:node.getAttribute?.('name')||'',role:node.getAttribute?.('role')||'',dataNav:node.getAttribute?.('data-nav')||'',text:String(node.textContent||'').trim().slice(0,120)}},clone=value=>value===undefined?undefined:JSON.parse(JSON.stringify(value));
    const persistence=value=>{const p=value?.persistence||value||{};return{blocked:clone(p.blocked??p.persistenceBlocked??null),notice:p.notice??p.persistenceNotice??null,outcome:p.outcome??p.persistenceOutcome??null,stale:p.stale??p.persistenceStale??null,writeInProgress:p.writeInProgress??p.persistenceWriteInProgress??null}};
    const parseState=raw=>{try{return raw===null?null:JSON.parse(raw)}catch{return null}},live=()=>{const logical=read(),slots=[...window.__P24C2B_SLOTS__.entries()].sort(([a],[b])=>a.localeCompare(b)),activeRaw=window.__P24C2B_SLOTS__.get(f.storage.activeKey)??null,state=parseState(activeRaw);return{logical,state,stateJson:JSON.stringify(state),raw:activeRaw,revision:state?.saveMeta?.revision??logical?.revision??null,persistence:persistence(logical),slots,activeRaw,stagingRaw:window.__P24C2B_SLOTS__.get(f.storage.stagingKey)??null,writes:window.__P24C2B_WRITES__.length,appHtml:document.getElementById('app')?.innerHTML??'',overlayHtml:document.getElementById('overlay')?.innerHTML??'',toastClass:document.getElementById('toast')?.className??'',toastText:document.getElementById('toast')?.textContent??'',focus:focusKey()}};
    const resultOf=value=>value?.transaction??value?.result??value?.coordinatorResult??value,stable=(before,after)=>same(before.state,after.state)&&before.raw===after.raw&&before.revision===after.revision&&same(before.persistence,after.persistence)&&same(before.slots,after.slots)&&before.activeRaw===after.activeRaw&&before.stagingRaw===after.stagingRaw&&before.writes===after.writes&&before.appHtml===after.appHtml&&before.overlayHtml===after.overlayHtml&&before.toastClass===after.toastClass&&before.toastText===after.toastText&&same(before.focus,after.focus),zeroWrites=(before,after)=>after.writes===before.writes&&same(before.slots,after.slots)&&before.activeRaw===after.activeRaw&&before.stagingRaw===after.stagingRaw;
    function prepareContinuityUi(){const overlay=document.getElementById('overlay'),toast=document.getElementById('toast');overlay.innerHTML='<div class="overlay" data-overlay><div class="modal" role="dialog" aria-modal="true" aria-labelledby="phase24c2b-qa-title" tabindex="-1"><h2 id="phase24c2b-qa-title">Coordinator continuity</h2><button type="button" data-modal-close>Keep focus</button></div></div>';toast.textContent='Coordinator continuity notice';toast.className='toast show';overlay.querySelector('[data-modal-close]')?.focus()}
    const unchangedProof=value=>value?.allUnchanged===true&&value?.writes===0&&value?.logDelta===0&&value?.revisionDelta===0&&value?.rawChanged===false&&value?.activeChanged===false&&value?.stagingChanged===false&&value?.unchanged&&Object.values(value.unchanged).every(Boolean);
    async function resetFresh(label){const reset=call('resetFresh');await wait(90);add(`${label}-fresh-reset`,reset?.ok===true&&reset?.schemaVersion===13&&!reset?.blocked,reset);return live()}
    async function blockingControl(name,label,expectedCode=null){await resetFresh(label);prepareContinuityUi();const before=live(),probe=call(name);await wait(45);const after=live(),transaction=resultOf(probe),code=transaction?.errorCode||null,uiChanged=after.appHtml!==before.appHtml||after.overlayHtml!==before.overlayHtml;add(`${label}-is-blocking-error-not-refusal`,transaction?.ok===false&&transaction?.refused!==true&&typeof transaction?.errorMessage==='string'&&transaction.errorMessage.length>0&&(expectedCode===null||code===expectedCode),transaction);add(`${label}-zero-save-restored-live-state`,zeroWrites(before,after)&&same(before.state,after.state)&&before.raw===after.raw&&before.revision===after.revision&&probe?.writes===0&&probe?.revisionDelta===0&&probe?.rawChanged===false&&probe?.activeChanged===false&&probe?.stagingChanged===false,{probe,writes:[before.writes,after.writes],revision:[before.revision,after.revision]});add(`${label}-blocks-and-renders`,Boolean(after.persistence.blocked)&&(uiChanged||probe?.unchanged?.appHtml===false||probe?.unchanged?.bodyHtml===false),{blocked:after.persistence.blocked,uiChanged,unchanged:probe?.unchanged})}
    (async()=>{await wait(1100);document.documentElement.style.fontSize=`${16*v.copyScale}px`;const candidate=bridge();
      add('durable-globals-remain-absent',f.durableGlobalsForbidden.every(name=>window[name]===undefined),Object.fromEntries(f.durableGlobalsForbidden.map(name=>[name,typeof window[name]])));
      add('durable-loaders-remain-absent',[...document.scripts].every(script=>!f.durableLoadersForbidden.some(path=>(script.src||'').includes(path))),[...document.scripts].map(script=>script.src).filter(Boolean));
      if(!v.expectedBridge){const capturedErrors=window.__P24C2B_ERRORS__.slice();add('qa-bridge-absent-outside-exact-realm',candidate===undefined,{query:location.search,allowDestructive:v.allowDestructive,isolatedStorage:v.isolatedStorage,supplyStorage:v.supplyStorage,descriptor:Boolean(Object.getOwnPropertyDescriptor(window,f.bridge.global))});if(v.supplyStorage)add('native-storage-not-used-in-supplied-adapter-denial-realms',window.__P24C2B_NATIVE_ACCESSES__.length===0,window.__P24C2B_NATIVE_ACCESSES__);else add('exact-captured-native-storage-is-rejected-by-qa-boundary',window.__P24C2B_NATIVE_INSTRUMENTED__===true&&window.__P24C2B_NATIVE_ACCESSES__.length>0,window.__P24C2B_NATIVE_ACCESSES__);add('zero-warning-error-console',capturedErrors.length===0,capturedErrors);send();return}
      const descriptor=Object.getOwnPropertyDescriptor(window,f.bridge.global),methodsOk=candidate?.version===f.bridge.version&&f.bridge.readMethods.every(name=>typeof candidate?.read?.[name]==='function')&&f.bridge.destructiveMethods.every(name=>typeof candidate?.destructive?.[name]==='function');add('authorized-bridge-is-nonenumerable-guarded-interface',methodsOk&&descriptor?.enumerable===false&&typeof descriptor?.get==='function',{version:candidate?.version,descriptor:{enumerable:descriptor?.enumerable,get:typeof descriptor?.get}});if(!methodsOk){send();return}
      const initial=await resetFresh('initial');add('fresh-live-schema-remains-13',initial.state?.schemaVersion===13&&initial.logical?.schemaVersion===13&&initial.logical?.refusalGlobal===false&&initial.logical?.phase24cLoaded===false&&initial.logical?.phase24cScriptLoaded===false,{stateSchema:initial.state?.schemaVersion,logical:initial.logical});add('fresh-staging-empty-and-active-authenticated',initial.activeRaw===initial.raw&&initial.activeRaw!==null&&initial.stagingRaw===null,{activeMatches:initial.activeRaw===initial.raw,staging:initial.stagingRaw});
      prepareContinuityUi();const refusalBefore=live(),refusal=call('probeRefusal');await wait(35);const refusalAfter=live(),refusalResult=resultOf(refusal);add('refusal-result-is-explicit-nonerror',refusalResult?.ok===false&&refusalResult?.refused===true&&refusalResult?.reason==='already-claimed'&&refusalResult?.errorCode===null&&refusalResult?.errorMessage===null&&refusalResult?.value===null&&refusalResult?.accrual===null,refusalResult);add('refusal-internal-full-invariant-proof',unchangedProof(refusal),refusal);add('refusal-zero-active-staging-successful-writes',zeroWrites(refusalBefore,refusalAfter),{writes:[refusalBefore.writes,refusalAfter.writes],activeStable:refusalBefore.activeRaw===refusalAfter.activeRaw,stagingStable:refusalBefore.stagingRaw===refusalAfter.stagingRaw});add('refusal-live-state-raw-revision-persistence-ui-focus-unchanged',stable(refusalBefore,refusalAfter),{revision:[refusalBefore.revision,refusalAfter.revision],persistence:[refusalBefore.persistence,refusalAfter.persistence],focus:[refusalBefore.focus,refusalAfter.focus]});
      prepareContinuityUi();const openingBefore=live(),opening=call('probeOpeningRefusal');await wait(35);const openingAfter=live(),openingResult=resultOf(opening);add('opening-refusal-result-discards-returned-accrual',openingResult?.ok===false&&openingResult?.refused===true&&openingResult?.reason==='duplicate-collection-claim'&&openingResult?.errorCode===null&&openingResult?.errorMessage===null&&openingResult?.accrual===null,openingResult);add('opening-refusal-internal-full-invariant-proof',unchangedProof(opening),opening);add('opening-refusal-zero-active-staging-successful-writes',zeroWrites(openingBefore,openingAfter),{writes:[openingBefore.writes,openingAfter.writes],activeStable:openingBefore.activeRaw===openingAfter.activeRaw,stagingStable:openingBefore.stagingRaw===openingAfter.stagingRaw});add('opening-refusal-live-state-raw-revision-persistence-ui-focus-unchanged',stable(openingBefore,openingAfter),{revision:[openingBefore.revision,openingAfter.revision],persistence:[openingBefore.persistence,openingAfter.persistence],focus:[openingBefore.focus,openingAfter.focus]});
      prepareContinuityUi();const successBefore=live(),success=call('probeSuccess');await wait(35);const successAfter=live(),successResult=resultOf(success);add('success-control-still-commits',successResult?.ok===true&&successResult?.refused!==true&&successResult?.value?.goldDelta===1&&success?.revisionDelta===1&&success?.writes>0&&successAfter.revision===successBefore.revision+1&&successAfter.raw!==successBefore.raw&&successAfter.activeRaw===successAfter.raw&&successAfter.writes>successBefore.writes&&successAfter.stagingRaw===null,{result:successResult,probe:success,revision:[successBefore.revision,successAfter.revision],writes:[successBefore.writes,successAfter.writes]});add('success-control-schema13-unblocked',successAfter.state?.schemaVersion===13&&!successAfter.persistence.blocked&&successAfter.persistence.stale!==true&&successAfter.persistence.writeInProgress!==true,{schema:successAfter.state?.schemaVersion,persistence:successAfter.persistence});
      await blockingControl('probeException','ordinary-exception');await blockingControl('probePersistenceError','persistence-error','phase24c2b-persistence-control');await blockingControl('probeLookalike','lookalike-refusal');await blockingControl('probeMalformedRefusal','malformed-refusal');await blockingControl('probeAuthenticWithoutOptIn','authentic-without-opt-in');const final=live();
      add('final-schema13-no-durable-activation',final.state?.schemaVersion===13&&f.durableGlobalsForbidden.every(name=>window[name]===undefined),{schema:final.state?.schemaVersion});add('native-storage-instrumented',window.__P24C2B_NATIVE_INSTRUMENTED__===true);add('zero-native-storage-accesses',window.__P24C2B_NATIVE_ACCESSES__.length===0,window.__P24C2B_NATIVE_ACCESSES__);add('zero-warning-error-console',window.__P24C2B_ERRORS__.length===0,window.__P24C2B_ERRORS__);send()
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }
  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();if(source.indexOf('<script')<0)throw new Error('Production script tag missing');source=source.replace('<head>','<head><base href="../../">');const insertion=source.indexOf('<script'),bodyClose=source.lastIndexOf('</body>');if(bodyClose<0)throw new Error('Production body closing tag missing');const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`;source=source.slice(0,insertion)+bootstrap+source.slice(insertion,bodyClose)+suite+source.slice(bodyClose);document.open();document.write(source);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
