(()=>{
  'use strict';
  const CHANNEL='everstead-phase-24c2b-coordinator-v1',byId=id=>document.getElementById(id),escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),row=(id,actual,detail='')=>({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)});
  async function loadJson(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.json()}
  function realm(contract,viewport){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),config={channel:CHANNEL,nonce,contract,viewport};frame.name=JSON.stringify(config);frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0`;let timer;const finish=(error,value)=>{clearTimeout(timer);removeEventListener('message',receive);frame.remove();error?reject(error):resolve(value)},receive=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=(event.data.results||[]).map(item=>({...item,id:`${viewport.id}-${item.id}`}));if(event.data.errors?.length)rows.push(row(`${viewport.id}-captured-errors`,false,event.data.errors.join('\n')));finish(null,rows)};timer=setTimeout(()=>finish(new Error(`${viewport.id} realm timed out`)),120000);addEventListener('message',receive);const suffix=viewport.query?`?${viewport.query}&nonce=${encodeURIComponent(nonce)}`:`?nonce=${encodeURIComponent(nonce)}`;frame.src=`./realm.html${suffix}`;document.body.appendChild(frame)})}
  function render(mode,rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('mode').textContent=mode;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)} · observed ${item.actual?'true':'false'} · expected true${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_24C2B_RESULT__={mode,passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const contract=await loadJson('./contract.json'),rows=[];rows.push(row('contract-v1-schema13',contract.contractVersion===1&&contract.phase==='24C-2B'&&contract.schemaVersion===13));rows.push(row('contract-exact-baseline',contract.baseline.indexSha256==='6109805093ee78f075257526b4822cf86c9ca22dbd2a2a05ab3ef7b0bcb8c5f3'));rows.push(row('contract-exact-bridge-surface',contract.bridge.global==='__EVERSTEAD_PHASE_24C2B_QA__'&&contract.bridge.readMethods.join(',')==='snapshot'&&contract.bridge.destructiveMethods.join(',')==='resetFresh,probeRefusal,probeOpeningRefusal,probeSuccess,probeException,probePersistenceError,probeLookalike,probeMalformedRefusal,probeAuthenticWithoutOptIn'));rows.push(row('contract-two-allowed-four-denied-realms',contract.realms.filter(item=>item.expectedBridge).length===2&&contract.realms.filter(item=>!item.expectedBridge).length===4));for(const viewport of contract.realms)rows.push(...await realm(contract,viewport));render('CANDIDATE',rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render('FATAL',[row('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
