(()=>{
  'use strict';
  const CHANNEL='everstead-phase-22c-independent-v1',json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config){
    const slots=new Map(),writes=[],errors=[],nativeAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);let saveIndex=0,transactionIndex=0,nativeInstrumented=false;
    window.matchMedia=query=>({matches:Boolean(config.viewport.reducedMotion)&&query==='(prefers-reduced-motion: reduce)',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});
    document.documentElement.style.fontSize=`${config.viewport.copyScale||1}em`;
    try{const native=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===native)nativeAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeInstrumented=true}catch{}
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push(`console.warn ${args.join(' ')}`);warn(...args)};console.error=(...args)=>{errors.push(`console.error ${args.join(' ')}`);error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>{key=String(key);writes.push({op:'set',key,value:String(value)});slots.set(key,String(value))},removeItem:key=>{key=String(key);writes.push({op:'remove',key});slots.delete(key)}};
    Object.assign(window,{__P22C_CONFIG__:config,__P22C_SLOTS__:slots,__P22C_WRITES__:writes,__P22C_ERRORS__:errors,__P22C_NATIVE_ACCESSES__:nativeAccesses,__P22C_NATIVE_INSTRUMENTED__:nativeInstrumented});
    window.__EVERSTEAD_RUNTIME__={storage:memoryStorage,clock:{now:()=>config.fixtures.frozenNow,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.4375,confirm:()=>true,ids:{save:()=>`save-p22c-${++saveIndex}`,transaction:()=>`tx-p22c-${++transactionIndex}`},qa:{allowDestructive:config.mode==='active',isolatedStorage:true}};
  }

  function runSuite(){
    const config=window.__P22C_CONFIG__,f=config.fixtures,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),until=async(predicate,limit=12000)=>{const started=performance.now();while(performance.now()-started<limit){if(predicate())return true;await wait(25)}return false},same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),clone=value=>JSON.parse(JSON.stringify(value));
    const add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),send=()=>parent.postMessage({channel:config.channel,nonce:config.nonce,results,errors:window.__P22C_ERRORS__.slice()},'*'),safe=(label,operation)=>{try{return operation()}catch(error){add(label,false,error.stack||error.message);return null}};
    const p16=()=>window.__EVERSTEAD_PHASE_16_QA__,p1819=()=>window.__EVERSTEAD_PHASE_18_19_QA__,p2021=()=>window.__EVERSTEAD_PHASE_20_21_QA__,call=(bridge,group,name,...args)=>safe(`${name}-call`,()=>bridge()[group][name](...args)),snapshot=bridge=>call(bridge,'read','snapshot'),raw=bridge=>call(bridge,'read','raw'),state=value=>value?.state||value,revision=value=>state(value)?.saveMeta?.revision;
    const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(byte=>byte.toString(16).padStart(2,'0')).join(''),loadText=async path=>{const response=await fetch(`../../${path}`,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.text()};
    const rewardFingerprint=value=>{const s=state(value)||{},foundation=s.phase15FacilityFramework||s.phase15||{},restaurant=s.phase16Restaurant||s.phase16||{},successor=s.phase2021||{},school=s.phase1819||{};return JSON.stringify({resources:{gold:s.gold,gifts:s.gifts,relicStones:s.relicStones,prosperity:s.prosperity,pendingGold:s.pendingGold},claims:s.rewardClaims,foundationClaims:{pendingOffers:foundation.pendingOffers,claimArchive:foundation.claimArchive,successorClaimAuthorityByFacilityId:foundation.successorClaimAuthorityByFacilityId},restaurantLocal:restaurant.localProgress,phase1819:{apothecary:school.apothecary,schoolhouse:school.schoolhouse},phase2021Profiles:successor.profilesByFacilityId})};
    const awaitWriteQuiescence=async(limit=6000)=>{const started=performance.now();let prior=window.__P22C_WRITES__.length,stableSince=started;while(performance.now()-started<limit){await wait(50);const current=window.__P22C_WRITES__.length,toastHidden=!document.querySelector('#toast.show');if(current!==prior||!toastHidden){prior=current;stableSince=performance.now()}else if(performance.now()-stableSince>=400)return true}return false};
    const visible=node=>{if(!node||node.hidden||node.getAttribute('aria-hidden')==='true'||node.matches('input[type="hidden"]'))return false;const style=getComputedStyle(node),rect=node.getBoundingClientRect();return style.display!=='none'&&style.visibility!=='hidden'&&Number(style.opacity)!==0&&rect.width>0&&rect.height>0},target=node=>{const rect=node.getBoundingClientRect();return rect.width+0.5>=f.minimumTargetPx&&rect.height+0.5>=f.minimumTargetPx},nav=()=>[...document.querySelectorAll('.bottom-nav [data-nav]')],goVillage=async()=>{const button=document.querySelector('[data-nav="village"]');button?.click();await wait(35);return button};
    const surfaceAudit=surface=>{const controls=[...surface.querySelectorAll('button,select,input,textarea,[role="button"]')].filter(visible),small=controls.filter(node=>!target(node)).map(node=>({tag:node.tagName,attrs:[...node.attributes].filter(a=>a.name.startsWith('data-')).map(a=>`${a.name}=${a.value}`),rect:node.getBoundingClientRect().toJSON?.()||{width:node.getBoundingClientRect().width,height:node.getBoundingClientRect().height}})),disabled=controls.filter(node=>node.matches(':disabled')),unreadableDisabled=disabled.filter(node=>getComputedStyle(node).opacity!=='1'),modal=surface.closest('.modal'),overflow=surface.scrollWidth>surface.clientWidth+1||modal&&modal.scrollWidth>modal.clientWidth+1;return{ok:controls.length>0&&small.length===0&&unreadableDisabled.length===0&&!overflow,controls:controls.length,small,disabled:disabled.length,unreadableDisabled:unreadableDisabled.length,overflow,surface:[surface.clientWidth,surface.scrollWidth],modal:modal?[modal.clientWidth,modal.scrollWidth]:null}};
    const motionAudit=surface=>{const nodes=[surface,...surface.querySelectorAll('*')].filter(visible),moving=nodes.filter(node=>{const style=getComputedStyle(node);return style.animationName!=='none'&&style.animationDuration!=='0s'||style.transitionDuration.split(',').some(value=>parseFloat(value)>0)});return{ok:!config.viewport.reducedMotion||moving.length===0,moving:moving.slice(0,5).map(node=>node.tagName)}};
    const ctaAudit=surface=>{const modal=surface.closest('.modal'),dock=surface.querySelector('.es-action-dock'),footer=surface.querySelector('.phase20-21-sheet-footer'),actionScope=dock||footer,scroller=modal;scroller?.scrollTo?.({top:scroller.scrollHeight,behavior:'auto'});const controls=[...actionScope?.querySelectorAll('button:not([hidden])')||[]].filter(visible),details=controls.map(node=>{const rect=node.getBoundingClientRect(),x=Math.max(0,Math.min(innerWidth-1,rect.left+rect.width/2)),y=Math.max(0,Math.min(innerHeight-1,rect.top+rect.height/2)),top=document.elementFromPoint(x,y),covered=rect.bottom>innerHeight+1||rect.right>innerWidth+1||rect.left<-1||!top||!(top===node||node.contains(top));return{covered,control:node.outerHTML.slice(0,180),rect:{left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom,width:rect.width,height:rect.height},point:{x,y},hit:top?{tag:top.tagName,data:[...top.attributes].filter(a=>a.name.startsWith('data-')).map(a=>`${a.name}=${a.value}`),outerHTML:top.outerHTML.slice(0,220)}:null}}),scopeRect=actionScope?.getBoundingClientRect(),modalRect=modal?.getBoundingClientRect();scroller?.scrollTo?.({top:0,behavior:'auto'});return{ok:Boolean(actionScope)&&controls.length>0&&details.every(item=>!item.covered),scope:dock?'action-dock':'sheet-footer',controls:controls.length,scopeRect:scopeRect&&{left:scopeRect.left,top:scopeRect.top,right:scopeRect.right,bottom:scopeRect.bottom},modalRect:modalRect&&{left:modalRect.left,top:modalRect.top,right:modalRect.right,bottom:modalRect.bottom},details}};
    const visit=async({id,facilityId,kind,bridge,assertions})=>{await goVillage();const invoker=document.querySelector(`[data-phase15-facility-id="${facilityId}"]`);add(`${id}-real-village-invoker`,Boolean(invoker)&&visible(invoker)&&target(invoker),invoker?.outerHTML.slice(0,220)||'missing');if(!invoker)return null;invoker.focus({preventScroll:true});const preOpen=snapshot(bridge),preOpenWrites=window.__P22C_WRITES__.length;invoker.click();const opened=await until(()=>document.querySelector(`[data-phase22c-facility-surface="${kind}"]`));await wait(60);const toastQuiescent=await until(()=>document.querySelector('#toast:not(.show)'),5000),surface=document.querySelector(`[data-phase22c-facility-surface="${kind}"]`),postOpen=snapshot(bridge);add(`${id}-actual-production-sheet-opened`,opened&&toastQuiescent&&surface?.dataset.phase22cFacilitySurface===kind&&surface.closest('[data-overlay]'),{surface:surface?.outerHTML.slice(0,180)||'missing',toastQuiescent});add(`${id}-open-resource-and-reward-neutral`,rewardFingerprint(preOpen)===rewardFingerprint(postOpen),{revision:[revision(preOpen),revision(postOpen)],writeDelta:window.__P22C_WRITES__.length-preOpenWrites});if(!surface)return null;const baseline=snapshot(bridge),rawBefore=raw(bridge),writesBefore=window.__P22C_WRITES__.length,rewardBefore=rewardFingerprint(baseline),geometry=surfaceAudit(surface),motion=motionAudit(surface),semantic=Boolean(safe(`${id}-semantic-assertion`,()=>assertions(surface,baseline))),cta=ctaAudit(surface);dispatchEvent(new Event('resize'));surface.closest('.modal')?.scrollTo?.({top:Math.max(0,surface.scrollHeight/2),behavior:'auto'});await wait(20);surface.closest('.modal')?.scrollTo?.({top:0,behavior:'auto'});const hadFocus=surface.closest('.modal')?.contains(document.activeElement);surface.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));await until(()=>!document.querySelector('[data-overlay]'),3000);await wait(35);const after=snapshot(bridge),neutral=raw(bridge)===rawBefore&&window.__P22C_WRITES__.length===writesBefore&&revision(after)===revision(baseline)&&rewardFingerprint(after)===rewardBefore;add(`${id}-semantic-geometry-motion-and-uncovered-cta`,semantic&&geometry.ok&&motion.ok&&cta.ok,{semantic,geometry,motion,cta});add(`${id}-focus-entry-escape-exact-return`,hadFocus&&document.activeElement===invoker,{hadFocus,returned:document.activeElement?.outerHTML?.slice(0,160)});add(`${id}-post-setup-inspect-resize-scroll-escape-zero-write-resource-local-reward-neutral`,neutral,{writes:[writesBefore,window.__P22C_WRITES__.length],revision:[revision(baseline),revision(after)],rawSame:raw(bridge)===rawBefore,rewardSame:rewardFingerprint(after)===rewardBefore});return{surface,preOpen,postOpen}};
    const successorRecord=(id)=>call(p2021,'read','derive')?.facilities?.[id]?.records?.[0],setupSuccessor=(id,stateKind='claim-ready')=>{call(p2021,'destructive','resetFixture',f.fixtures.successors);call(p2021,'destructive','seedRecord',id);let record=successorRecord(id);if(stateKind==='banked')return record;call(p2021,'destructive','begin',id,record.opportunity.id,record.identity);record=successorRecord(id);call(p2021,'destructive','choose',id,record.opportunity.id,record.identity,f.choiceIds[id]);record=successorRecord(id);if(['facility.training-grounds','facility.hearth'].includes(id))call(p2021,'destructive','selectParticipants',id,record.opportunity.id,record.identity,f.participants);record=successorRecord(id);if(stateKind==='engaged'||stateKind==='reserved')return record;call(p2021,'destructive','commit',id,record.opportunity.id,record.identity);record=successorRecord(id);if(id==='facility.gardens'){if(stateKind==='growing')return record;call(p2021,'destructive','advanceGrowth',f.frozenNow+f.gardenGrowthMs)}else call(p2021,'destructive','resolve',id,record.opportunity.id,record.identity);return successorRecord(id)};

    (async()=>{
      await until(()=>document.querySelector('#app')&&nav().length===5,10000);
      const sourceRows=[f.index,...f.sources],identities=[];for(const item of sourceRows){const value=await loadText(item.path);identities.push({path:item.path,bytes:new TextEncoder().encode(value).length,sha256:await digest(value),expectedBytes:item.bytes,expectedSha256:item.sha256})}add('cache-versioned-source-load-byte-identity',identities.every(item=>item.bytes===item.expectedBytes&&item.sha256===item.expectedSha256),identities.filter(item=>item.bytes!==item.expectedBytes||item.sha256!==item.expectedSha256));const links=[...document.querySelectorAll(`link[href$="${f.stylesheetHref}"]`)];add('phase22c-stylesheet-loaded-once-after-phase22b',links.length===1&&[...document.styleSheets].some(sheet=>sheet.href?.endsWith(f.stylesheetHref))&&document.documentElement.outerHTML.indexOf('phase22b-feature-polish.css')<document.documentElement.outerHTML.indexOf(f.stylesheetHref),links.map(link=>link.href));add('exact-five-navigation',nav().length===5&&same(nav().map(node=>node.dataset.nav),f.navigation));
      if(config.mode==='inactive'){
        const bootQuiescent=await awaitWriteQuiescence(),beforeWrites=window.__P22C_WRITES__.length,before=[...window.__P22C_SLOTS__.entries()];for(const item of nav()){item.click();await wait(10)}add('inactive-boot-quiescent-before-baseline',bootQuiescent,{writesAtBaseline:beforeWrites});add('production-inactive-no-qa-bridges',!p16()&&!p1819()&&!p2021());add('production-inactive-no-phase22c-facility-surfaces',document.querySelectorAll('[data-phase22c-facility-surface]').length===0);add('inactive-five-route-visual-traversal-zero-save-writes',window.__P22C_WRITES__.length===beforeWrites&&same([...window.__P22C_SLOTS__.entries()],before),{writes:[beforeWrites,window.__P22C_WRITES__.length]});add('inactive-zero-native-storage-accesses',window.__P22C_NATIVE_INSTRUMENTED__&&window.__P22C_NATIVE_ACCESSES__.length===0,window.__P22C_NATIVE_ACCESSES__);add('inactive-zero-warning-error-console',window.__P22C_ERRORS__.length===0,window.__P22C_ERRORS__);send();return;
      }
      await until(()=>p16()&&p1819()&&p2021(),10000);add('accepted-three-real-bridges',p16()?.version===f.bridges.restaurant&&p1819()?.version===f.bridges.phase1819&&p2021()?.version===f.bridges.phase2021,{restaurant:p16()?.version,phase1819:p1819()?.version,phase2021:p2021()?.version});if(!p16()||!p1819()||!p2021()){send();return}

      call(p16,'destructive','resetFixture',f.fixtures.restaurantReady);await visit({id:'restaurant-claim-ready-stock',facilityId:'facility.restaurant',kind:'restaurant',bridge:p16,assertions:(surface)=>{const definitions=call(p16,'read','definitions'),derived=call(p16,'read','derive'),level=derived.restaurant.localProgress.reputationLevel,expected=definitions.recipes.filter(item=>item.unlockReputationLevel<=level).map(item=>item.id).sort(),stock=[...surface.querySelectorAll('[data-phase22c-stock-item]')].map(item=>item.dataset.phase22cStockItem).sort(),options=[...surface.querySelectorAll('[data-phase16-recipe-id] option')].map(item=>item.value).sort(),offer=derived.restaurant.offers[0],outcome=derived.restaurant.outcomes[0],gold=(offer?.rewards||[]).filter(reward=>reward.kind==='gold').reduce((sum,reward)=>sum+reward.amount,0),summary=surface.querySelector('[data-phase22c-claim-kind="restaurant-service"]'),breakdown=outcome?.baseSaleGold+outcome?.tipGold===gold&&outcome?.totalGold===gold;return surface.dataset.phase22cLifecycleState==='claim-ready'&&summary?.querySelector(`[data-phase22c-reward-gold="${gold}"]`)&&summary.textContent.includes(`${gold.toLocaleString()} Gold`)&&(!breakdown||summary.textContent.includes('Sale')&&summary.textContent.includes('Tip'))&&same(stock,expected)&&same(options,expected)}});

      call(p1819,'destructive','resetFixture',f.fixtures.apothecaryRecheck);await visit({id:'apothecary-recheck',facilityId:'facility.apothecary',kind:'apothecary',bridge:p1819,assertions:surface=>surface.dataset.phase22cLifecycleState==='recheck'&&surface.querySelector('[data-phase18-recheck]')?.textContent.includes('Recheck')&&surface.querySelectorAll('[data-phase22c-evidence-group] [data-phase18-clue-id]').length===3});
      call(p1819,'destructive','resetFixture',f.fixtures.apothecaryReady);await visit({id:'apothecary-claim-ready',facilityId:'facility.apothecary',kind:'apothecary',bridge:p1819,assertions:surface=>surface.dataset.phase22cLifecycleState==='claim-ready'&&surface.querySelector('[data-phase22c-claim-kind="apothecary-case"]')&&surface.querySelector('[data-phase18-claim]:not(:disabled)')});
      call(p1819,'destructive','resetFixture',f.fixtures.schoolhouseLessonReady);await visit({id:'schoolhouse-lesson-claim-ready',facilityId:'facility.schoolhouse',kind:'schoolhouse',bridge:p1819,assertions:surface=>surface.dataset.phase22cLifecycleState==='claim-ready'&&surface.querySelector('[data-phase22c-claim-kind="schoolhouse-lesson"]')&&surface.querySelectorAll('[data-phase22c-domain-progress]').length===3});
      call(p1819,'destructive','resetFixture',f.fixtures.schoolhouseGraduation);await visit({id:'schoolhouse-graduation-synthetic-offer-truth',facilityId:'facility.schoolhouse',kind:'schoolhouse',bridge:p1819,assertions:surface=>{const derived=call(p1819,'read','derive'),offer=derived.claims.pendingOffers.find(item=>item.domainClaimKind==='schoolhouse-graduation'),summary=surface.querySelector('[data-phase22c-claim-kind="schoolhouse-graduation"]'),copy=summary?.textContent||'',gold=offer?.rewards?.[0],policy=f.liveFixturePolicy.schoolhouseGraduation;return surface.dataset.phase22cLifecycleState==='graduation-ready'&&summary&&same(offer.rewards.map(reward=>reward.kind),policy.rewardKinds)&&gold.kind==='gold'&&copy.includes(gold.amount.toLocaleString())&&copy.includes('Gold')&&!copy.includes('Gift')&&!copy.includes('Relic Stone')&&summary.querySelector('p')?.textContent.includes(`+${offer.localSnapshot.education}`)&&policy.seatCapacity==='maximum'&&surface.querySelectorAll('[data-phase22c-seat-locked]').length===policy.lockedSeatCount}});

      for(const facilityId of f.facilityIds){setupSuccessor(facilityId);await visit({id:`successor-${facilityId.slice(9)}-claim-ready`,facilityId,kind:'successor',bridge:p2021,assertions:surface=>surface.dataset.facilityId===facilityId&&surface.dataset.phase22cLifecycleState==='claim-ready'&&surface.querySelector(`[data-phase22c-reward-gold="${f.goldByFacility[facilityId]}"]`)&&surface.querySelector(`[data-phase22c-reward-local-progress="${f.localProgressByFacility[facilityId]}"]`)&&surface.querySelector('[data-phase20-21-claim]:not(:disabled)')})}
      setupSuccessor('facility.market-workshop','reserved');await visit({id:'market-workshop-reservation-and-stock-summary',facilityId:'facility.market-workshop',kind:'successor',bridge:p2021,assertions:surface=>surface.dataset.phase22cLifecycleState==='engaged'&&surface.querySelector('[data-phase22c-stock-summary]')?.textContent.includes('Reserved')});
      setupSuccessor('facility.training-grounds','engaged');await visit({id:'training-participant-selection',facilityId:'facility.training-grounds',kind:'successor',bridge:p2021,assertions:surface=>surface.querySelector('[data-phase20-21-participant-selection]')&&surface.querySelectorAll('[data-phase20-21-actor-choice][aria-pressed="true"]').length===f.participants.length});
      setupSuccessor('facility.gardens','growing');await visit({id:'gardens-growth',facilityId:'facility.gardens',kind:'successor',bridge:p2021,assertions:surface=>surface.dataset.phase22cLifecycleState==='growing'&&surface.querySelector('[data-phase20-21-growth-status]')&&surface.querySelector('[data-phase20-21-resume]')});
      let receiptRecord=setupSuccessor('facility.command-center'),receiptOffer=receiptRecord?.outcome;call(p2021,'destructive','claim',receiptOffer.offerId,receiptOffer.offerIdentity);await visit({id:'successor-exact-once-receipt-summary',facilityId:'facility.command-center',kind:'successor',bridge:p2021,assertions:surface=>surface.querySelector('[data-phase22c-claim-summary="claimed"][data-phase22c-receipt-id]')&&surface.querySelector('[data-phase20-21-receipt-summary]')});

      add('all-measured-traversals-exclude-claim-clicks',true,'Claims are bridge-only fixture setup; visit() dispatches only invoker, resize, scroll, and Escape.');add('final-real-state-valid',call(p2021,'read','validate')?.ok===true);add('zero-native-storage-accesses',window.__P22C_NATIVE_INSTRUMENTED__&&window.__P22C_NATIVE_ACCESSES__.length===0,window.__P22C_NATIVE_ACCESSES__);add('zero-warning-error-console',window.__P22C_ERRORS__.length===0,window.__P22C_ERRORS__);send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();if(source.indexOf('<script')<0)throw new Error('Production script tag missing');const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`;source=source.replace('<head>','<head><base href="../../">');const insertion=source.indexOf('<script'),bodyClose=source.lastIndexOf('</body>');if(bodyClose<0)throw new Error('Production body closing tag missing');source=source.slice(0,insertion)+bootstrap+source.slice(insertion,bodyClose)+suite+source.slice(bodyClose);document.open();document.write(source);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
