import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {existsSync,readFileSync,readdirSync,statSync} from 'node:fs';
import {resolve} from 'node:path';
import {Script,createContext,runInContext} from 'node:vm';

const ROOT=resolve(new URL('../..',import.meta.url).pathname),QA=resolve(ROOT,'qa/phase-22c-independent'),rows=[];
const read=path=>readFileSync(resolve(ROOT,path)),text=path=>read(path).toString('utf8'),json=path=>JSON.parse(text(path)),sha=value=>createHash('sha256').update(value).digest('hex'),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),add=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),filesBelow=(directory,prefix='')=>readdirSync(directory).flatMap(name=>{const absolute=resolve(directory,name),path=prefix?`${prefix}/${name}`:name;return statSync(absolute).isDirectory()?filesBelow(absolute,path):[path]}).sort();
const f=json('qa/phase-22c-independent/fixtures/contract.json'),focused=json('qa/phase-22c-facility-polish/fixtures/contract.json'),realm=text('qa/phase-22c-independent/realm.js'),runner=text('qa/phase-22c-independent/runner.js'),index=text('index.html'),git=args=>spawnSync('git',args,{cwd:ROOT,encoding:'utf8',maxBuffer:64*1024*1024});

async function generatedPayloadCompiles(){let written='',posted=null,resolveWritten;const writtenPromise=new Promise(resolvePromise=>resolveWritten=resolvePromise),config={channel:'everstead-phase-22c-independent-v1',nonce:'verify-generated',viewport:f.viewports[0],fixtures:f,mode:'active'},loaderWindow={name:JSON.stringify(config)},context={window:loaderWindow,document:{open(){},write(value){written=String(value);resolveWritten()},close(){}},fetch:async()=>({ok:true,text:async()=>index}),parent:{postMessage(value){posted=value;resolveWritten()}},console,setTimeout,clearTimeout};loaderWindow.window=loaderWindow;createContext(context);try{runInContext(realm,context,{filename:'qa/phase-22c-independent/realm.js'});await Promise.race([writtenPromise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('generated realm timeout')),2000))]);if(posted)throw new Error(`loader failed: ${JSON.stringify(posted)}`);const scripts=[...written.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(match=>match[1]),bootstrap=scripts.find(value=>value.includes('function installRuntime(config)')),suite=scripts.find(value=>value.includes('function runSuite()'));if(!bootstrap||!suite)throw new Error('generated payload missing');new Script(bootstrap,{filename:'generated-phase22c-bootstrap.js'});new Script(suite,{filename:'generated-phase22c-suite.js'});return{ok:true,writtenBytes:written.length,bootstrapBytes:bootstrap.length,suiteBytes:suite.length}}catch(error){return{ok:false,error:error.stack||error.message,writtenBytes:written.length}}}

add('package-topology',same(filesBelow(QA),['README.md','checksums.sha256','fixtures/contract.json','index.html','realm.html','realm.js','runner.js','verify.mjs']),filesBelow(QA));
const checksumRows=text('qa/phase-22c-independent/checksums.sha256').trim().split('\n').filter(line=>line&&!line.startsWith('#')).map(line=>{const match=line.match(/^([0-9a-f]{64})  (.+)$/);return match?{expected:match[1],path:match[2]}:null}),checksumFailures=checksumRows.filter(item=>!item||!existsSync(resolve(ROOT,item.path))||sha(read(item.path))!==item.expected).map(item=>item?.path||'malformed');add('package-checksums',checksumRows.length===7&&checksumFailures.length===0,{count:checksumRows.length,failures:checksumFailures});
add('frozen-source-contract-matches-focused',f.contractVersion===1&&f.sourceFrozen===true&&f.baseCommit===focused.baseCommit&&f.sourceCommit===focused.sourceCommit&&f.sourceCommit==='ee2ea1e73660562ba735d92e1d715b073c37b1eb'&&f.index.sha256===focused.indexSha256&&f.index.bytes===focused.indexBytes);
const identities=[f.index,...f.sources],identityFailures=identities.filter(item=>Buffer.byteLength(read(item.path))!==item.bytes||sha(read(item.path))!==item.sha256);add('all-frozen-source-identities',identityFailures.length===0,identityFailures);
add('source-commit-reachable-and-exact-four-file-delta',git(['merge-base','--is-ancestor',f.sourceCommit,'HEAD']).status===0&&same(git(['diff','--name-only',f.baseCommit,f.sourceCommit,'--','index.html','src']).stdout.trim().split('\n'),['index.html','src/phase18-19-runtime.js','src/phase20-21-presentation.js','src/phase22c-facility-polish.css']));
add('single-cache-versioned-phase22c-source',index.split(`  <link rel="stylesheet" href="${f.stylesheetHref}">\n`).length===2&&index.indexOf('phase22b-feature-polish.css')<index.indexOf(f.stylesheetHref));
add('exact-bridge-fixture-and-viewport-contract',same(f.bridges,{restaurant:'phase-16-independent-qa-v1',phase1819:'phase-18-19-independent-qa-v1',phase2021:'phase-20-21-independent-qa-v2'})&&f.facilityIds.length===8&&Object.keys(f.choiceIds).length===8&&f.minimumTargetPx===44&&f.viewports.length===7&&same(f.viewports.slice(0,5).map(v=>[v.width,v.height]),[[320,568],[390,844],[430,932],[768,1024],[1024,768]])&&f.viewports.some(v=>v.copyScale===1.3)&&f.viewports.some(v=>v.reducedMotion));
add('real-candidate-loader-and-isolated-storage',['fetch(\'../../index.html\'','allowDestructive:config.mode===\'active\'','isolatedStorage:true','__EVERSTEAD_PHASE_16_QA__','__EVERSTEAD_PHASE_18_19_QA__','__EVERSTEAD_PHASE_20_21_QA__','lastIndexOf(\'</body>\')','source.slice(0,insertion)+bootstrap+source.slice(insertion,bodyClose)+suite+source.slice(bodyClose)'].every(token=>realm.includes(token)));
add('exact-source-load-byte-identity',['crypto.subtle.digest','f.index,...f.sources','cache-versioned-source-load-byte-identity','phase22c-stylesheet-loaded-once-after-phase22b'].every(token=>realm.includes(token)));
add('restaurant-canonical-gold-stock-and-fail-closed-breakdown',['restaurant-claim-ready-stock','unlockReputationLevel<=level','data-phase22c-stock-item','data-phase22c-reward-gold','baseSaleGold+outcome?.tipGold===gold','summary.textContent.includes(\'Sale\')'].every(token=>realm.includes(token)));
add('apothecary-recheck-and-ready',['apothecary-recheck','data-phase18-recheck','data-phase22c-evidence-group','apothecary-claim-ready','data-phase22c-claim-kind="apothecary-case"'].every(token=>realm.includes(token)));
add('schoolhouse-live-synthetic-and-static-production-policy-truth',same(f.liveFixturePolicy.schoolhouseGraduation,{rewardKinds:['gold'],seatCapacity:'maximum',lockedSeatCount:0})&&['schoolhouse-lesson-claim-ready','schoolhouse-graduation-synthetic-offer-truth','same(offer.rewards.map(reward=>reward.kind),policy.rewardKinds)','!copy.includes(\'Gift\')','!copy.includes(\'Relic Stone\')','data-phase22c-seat-locked'].every(token=>realm.includes(token))&&focused.graduationRewards.gifts===1&&focused.graduationRewards.relicStones===3&&text('src/phase18-19-runtime.js').includes('UNLOCK: 36 EDUCATION + 1 GRADUATION + YOUNG FUTURES'));
add('all-eight-successor-exact-gold-local-progress',realm.includes('for(const facilityId of f.facilityIds)')&&realm.includes('data-phase22c-reward-gold')&&realm.includes('data-phase22c-reward-local-progress')&&Object.values(f.goldByFacility).length===8&&Object.values(f.localProgressByFacility).length===8);
add('reservations-participants-growth-receipts',['market-workshop-reservation-and-stock-summary','training-participant-selection','gardens-growth','successor-exact-once-receipt-summary','data-phase20-21-participant-selection','data-phase20-21-growth-status','data-phase20-21-resume','data-phase22c-receipt-id'].every(token=>realm.includes(token)));
add('actual-dom-44-focus-overflow-cta-disabled-readable',['getBoundingClientRect','f.minimumTargetPx','unreadableDisabled','scrollWidth>surface.clientWidth+1','elementFromPoint','es-action-dock','phase20-21-sheet-footer','control:node.outerHTML','modalRect','toast:not(.show)','focus-entry-escape-exact-return','document.activeElement===invoker'].every(token=>realm.includes(token))&&f.liveFixturePolicy.receiptActionScope==='phase20-21-sheet-footer');
add('post-setup-literal-neutrality-and-no-measured-claims',['const baseline=snapshot(bridge)','rawBefore=raw(bridge)','writesBefore=window.__P22C_WRITES__.length','rewardBefore=rewardFingerprint(baseline)','post-setup-inspect-resize-scroll-escape-zero-write-resource-local-reward-neutral','raw(bridge)===rawBefore','revision(after)===revision(baseline)','rewardFingerprint(after)===rewardBefore','all-measured-traversals-exclude-claim-clicks'].every(token=>realm.includes(token)));
add('reduced-motion-copy-inactive-and-safety',['copyScale','reducedMotion','motionAudit','awaitWriteQuiescence','inactive-boot-quiescent-before-baseline','production-inactive-no-qa-bridges','production-inactive-no-phase22c-facility-surfaces','inactive-five-route-visual-traversal-zero-save-writes','zero-native-storage-accesses','zero-warning-error-console'].every(token=>realm.includes(token)));
add('runner-seven-active-plus-inactive',runner.includes('for(const viewport of f.viewports)')&&runner.includes("realm(f,f.inactiveViewport,'inactive')")&&runner.includes('__EVERSTEAD_PHASE_22C_INDEPENDENT_RESULT__'));
for(const file of ['runner.js','realm.js','verify.mjs']){const checked=spawnSync(process.execPath,['--check',`qa/phase-22c-independent/${file}`],{cwd:ROOT,encoding:'utf8'});add(`syntax-${file}`,checked.status===0,checked.stderr.trim())}
const generated=await generatedPayloadCompiles();add('runtime-generated-production-payload-compiles',generated.ok,generated);
const passed=rows.filter(row=>row.pass).length,failed=rows.length-passed;for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` — ${row.detail}`:''}`);console.log(`RESULT ${passed} passed, ${failed} failed`);process.exitCode=failed?1:0;
