(() => {
  'use strict';
  const CHANNEL='everstead-phase-10c3';
  const json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');
  function installRuntime(config){
    const slots=new Map(),nativeSetTimeout=window.setTimeout.bind(window),nativeClearTimeout=window.clearTimeout.bind(window),nativeStorageAccesses=[],errors=[],keydownListeners=new Set();let saveIndex=0,transactionIndex=0,nativeStorageInstrumented=false;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    const add=document.addEventListener.bind(document),remove=document.removeEventListener.bind(document);document.addEventListener=function(type,listener,options){if(type==='keydown')keydownListeners.add(listener);return add(type,listener,options)};document.removeEventListener=function(type,listener,options){if(type==='keydown')keydownListeners.delete(listener);return remove(type,listener,options)};
    window.__PHASE_10C3_CONFIG__=config;window.__PHASE_10C3_SLOTS__=slots;window.__PHASE_10C3_ERRORS__=errors;window.__PHASE_10C3_NATIVE_STORAGE_ACCESSES__=nativeStorageAccesses;window.__PHASE_10C3_NATIVE_STORAGE_INSTRUMENTED__=nativeStorageInstrumented;window.__PHASE_10C3_KEYDOWN_LISTENERS__=keydownListeners;
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>slots.set(String(key),String(value)),removeItem:key=>slots.delete(String(key))};
    window.__EVERSTEAD_RUNTIME__={storage:memoryStorage,clock:{now:()=>config.now,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.5,confirm:()=>true,ids:{save:()=>`save-p10c3-browser-${++saveIndex}`,transaction:()=>`tx-p10c3-browser-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
  }
  function runSuite(){
    const channel='everstead-phase-10c3',config=window.__PHASE_10C3_CONFIG__,slots=window.__PHASE_10C3_SLOTS__,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)}),bridge=()=>window.__EVERSTEAD_QA__,snapshot=()=>bridge().snapshot().state,send=()=>parent.postMessage({channel,nonce:config.nonce,results,errors:window.__PHASE_10C3_ERRORS__.slice(),slots:Object.fromEntries(slots)},'*');
    const navigate=async view=>{const result=bridge().act('navigate',{view});if(!result.ok)throw new Error(`Navigation to ${view} failed: ${result.error}`);await wait(10)};
    const roster=async tab=>{const result=bridge().act('roster',{tab});if(!result.ok)throw new Error(`Roster ${tab} failed: ${result.error}`);await wait(10)};
    const close=async()=>{document.querySelector('[data-modal-close]')?.click();await wait(10)};
    const focusables=dialog=>[...dialog.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(node=>!node.hidden&&getComputedStyle(node).display!=='none');
    const intersects=(a,b)=>Math.min(a.right,b.right)-Math.max(a.left,b.left)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>1;
    const geometry=()=>{const blockers=[document.querySelector('.village-hud'),document.querySelector('.bottom-nav'),document.querySelector('.topbar')].filter(Boolean).map(node=>node.getBoundingClientRect()),items=[...document.querySelectorAll('.building-hotspot')].map(button=>{const rect=button.getBoundingClientRect(),points=[[.5,.5],[.25,.25],[.75,.25],[.25,.75],[.75,.75]].map(([x,y])=>[rect.left+rect.width*x,rect.top+rect.height*y]),hits=points.every(([x,y])=>{const target=document.elementFromPoint(x,y);return target===button||button.contains(target)});return{id:button.dataset.building,width:rect.width,height:rect.height,inside:rect.left>=-1&&rect.top>=-1&&rect.right<=innerWidth+1&&rect.bottom<=innerHeight+1,clear:blockers.every(blocker=>!intersects(rect,blocker)),hits}});return{items,ok:items.length===4&&items.every(item=>item.width>=44&&item.height>=44&&item.inside&&item.clear&&item.hits)}};
    const compact=value=>value>=1e6?(value/1e6).toFixed(value>=1e7?1:2)+'M':value>=1e3?(value/1e3).toFixed(value>=1e5?0:1)+'K':String(Math.floor(value));
    const metricMap=root=>Object.fromEntries(root?[...root.querySelectorAll('.metric')].map(metric=>[metric.querySelector('span')?.textContent.trim(),metric.querySelector('b')?.textContent.trim()]):[]);
    const modalEvidence=()=>{const modal=document.querySelector('.modal'),details=modal?.querySelector('[data-building-production-details]'),preview=modal?.querySelector('[data-building-upgrade-preview]'),labels=details?[...details.querySelectorAll('.metric span')].map(node=>node.textContent.trim()):[],button=modal?.querySelector('[data-modal-act="upgrade-building"]'),reason=modal?.querySelector('[data-building-upgrade-reason]');return{modal,labels,factors:metricMap(details),preview:metricMap(preview),button,reason,text:modal?.textContent.replace(/\s+/g,' ').trim()||''}};
    async function dialogTarget(){
      await navigate('village');const trigger=document.querySelector('[data-building="training"]');trigger.focus();trigger.click();await wait(20);const modal=document.querySelector('.modal'),titles=modal?[...modal.querySelectorAll('#everstead-modal-title')]:[],nodes=modal?focusables(modal):[],last=nodes.at(-1)||modal,semantic=Boolean(modal?.matches('[role="dialog"][aria-modal="true"][aria-labelledby="everstead-modal-title"]'))&&titles.length===1&&modal.contains(document.activeElement),inertOpen=Boolean(document.querySelector('#app')?.inert||document.querySelector('#app')?.hasAttribute('inert'));modal?.focus();document.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true,cancelable:true}));await wait(5);const trapped=document.activeElement===last;document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));await wait(15);return{ok:semantic&&inertOpen&&trapped&&!document.querySelector('[data-overlay]')&&document.activeElement===trigger,semantic,inertOpen,trapped,restored:document.activeElement===trigger}}
    async function successorModalTarget(){
      await navigate('village');const trigger=document.querySelector('[data-building="training"]'),listenerCounts=[];let cycles=true;for(let index=0;index<3;index++){trigger.focus();trigger.click();await wait(10);const modal=document.querySelector('.modal'),semantic=Boolean(modal?.matches('[role="dialog"][aria-modal="true"][aria-labelledby="everstead-modal-title"]'))&&modal.contains(document.activeElement),inertOpen=Boolean(document.querySelector('#app')?.inert||document.querySelector('#app')?.hasAttribute('inert'));document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));await wait(10);const inertClosed=!document.querySelector('#app')?.inert&&!document.querySelector('#app')?.hasAttribute('inert');listenerCounts.push(window.__PHASE_10C3_KEYDOWN_LISTENERS__.size);cycles=cycles&&semantic&&inertOpen&&!document.querySelector('[data-overlay]')&&document.activeElement===trigger&&inertClosed}trigger.focus();trigger.click();await wait(10);const overlay=document.querySelector('[data-overlay]');overlay?.click();await wait(10);const overlayClosed=!document.querySelector('[data-overlay]')&&document.activeElement===trigger&&!document.querySelector('#app')?.inert&&!document.querySelector('#app')?.hasAttribute('inert'),listenerStable=listenerCounts.length===3&&new Set(listenerCounts).size===1&&listenerCounts[0]<=1&&window.__PHASE_10C3_KEYDOWN_LISTENERS__.size===listenerCounts[0];return{ok:cycles&&overlayClosed&&listenerStable,cycles,overlayClosed,listenerStable,listenerCounts,finalListeners:window.__PHASE_10C3_KEYDOWN_LISTENERS__.size}}
    async function rosterTabTarget(){
      await navigate('fellows');await roster('fellows');const inspect=()=>{const list=document.querySelector('[role="tablist"][aria-label="Fellowship roster"]'),tabs=list?[...list.querySelectorAll('[role="tab"]')]:[],selected=tabs.filter(tab=>tab.getAttribute('aria-selected')==='true'),panel=document.querySelector('[role="tabpanel"]');return{list,tabs,selected,panel,ok:Boolean(list)&&tabs.length===4&&selected.length===1&&Boolean(panel)&&tabs.every(tab=>tab.id&&tab.getAttribute('aria-controls')==='fellowship-panel'&&tab.tabIndex===(tab===selected[0]?0:-1))&&panel.getAttribute('aria-labelledby')===selected[0].id}};let state=inspect();if(!state.ok)return{ok:false,initial:state};const dispatch=key=>{const selected=document.querySelector('[role="tab"][aria-selected="true"]');selected.focus();selected.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}))},selected=(tab,kind)=>tab?.dataset.roster===kind&&document.activeElement===tab;dispatch('ArrowRight');await wait(10);let tab=document.querySelector('[role="tab"][aria-selected="true"]');const right=selected(tab,'family');dispatch('End');await wait(10);tab=document.querySelector('[role="tab"][aria-selected="true"]');const end=selected(tab,'relics');dispatch('Home');await wait(10);tab=document.querySelector('[role="tab"][aria-selected="true"]');const home=selected(tab,'fellows');dispatch('ArrowLeft');await wait(10);tab=document.querySelector('[role="tab"][aria-selected="true"]');const left=selected(tab,'relics');state=inspect();return{ok:state.ok&&right&&end&&home&&left,right,end,home,left,final:state.selected[0]?.dataset.roster}}
    async function inspectFreshAndShortage(){
      await navigate('village');const hotspot=document.querySelector('[data-building="training"]');hotspot.click();await wait(15);let evidence=modalEvidence();
      const exactFactors=Object.entries(config.oracle.trainingFactors).every(([label,value])=>evidence.factors[label]===value);add('fresh-modal-authoritative-factors',evidence.labels.join('|')==='Building level|Family|Fellow roster|Companion roster|Oaths|Final Gold/hr'&&exactFactors,JSON.stringify(evidence.factors));
      const exactPreview=Object.entries(config.oracle.trainingPreview).every(([label,value])=>evidence.preview[label]===value);add('fresh-modal-preview',exactPreview&&/Level 1 → Level 2/.test(evidence.text)&&/UPGRADE TO LEVEL 2 · 15\.0K GOLD/.test(evidence.text)&&!evidence.button.disabled,JSON.stringify(evidence.preview));
      await close();let result=bridge().act('building-upgrade',{id:'training'});if(!result.ok)throw new Error(`Upgrade 1 failed: ${result.error}`);await wait(20);const status=document.querySelector('#everstead-status'),records=[],observer=new MutationObserver(()=>records.push(status.textContent));observer.observe(status,{childList:true,characterData:true,subtree:true});result=bridge().act('building-upgrade',{id:'training'});if(!result.ok)throw new Error(`Upgrade 2 failed: ${result.error}`);await wait(30);observer.disconnect();evidence=modalEvidence();const upgradeStatus=status?.textContent||'',upgradeExact='Training Grounds reached Level 3 · 10.3K Gold per hour.';
      add('successful-upgrade-polite-copy',upgradeStatus===upgradeExact&&records.filter(value=>value==='').length===1&&records.filter(value=>value===upgradeExact).length===1,`${upgradeStatus} · ${JSON.stringify(records)}`);
      add('unaffordable-modal-reason',snapshot().buildings.training.level===3&&snapshot().gold===16400&&evidence.button.disabled&&/Need 6\.7K more Gold\./.test(evidence.reason?.textContent||'')&&/UPGRADE TO LEVEL 4 · 23\.1K GOLD/.test(evidence.text),`${snapshot().gold} · ${evidence.text}`);await close();
    }
    async function offlineAndStatus(){
      const status=document.querySelector('#everstead-status');let result=bridge().act('simulate',{});if(!result.ok)throw new Error(`Simulate failed: ${result.error}`);await wait(15);let modal=document.querySelector('.modal'),lines=modal?[...modal.querySelectorAll('.offline-line')]:[];
      const rawRates={...config.oracle.preActivationRates,training:config.oracle.preActivationRates.training*Math.pow(config.oracle.buildingLevelGrowth,2)},rawLines=Object.fromEntries(Object.entries(rawRates).map(([id,rate])=>[id,rate*2])),rawTotal=Object.values(rawLines).reduce((sum,value)=>sum+value,0),names={training:'Training Grounds',command:'Command Center',archives:'Archives',hearth:'Hearth'},visible=Object.fromEntries([...modal.querySelectorAll('.offline-line:not([data-offline-gold-total])')].map(line=>[line.querySelector('span')?.textContent.trim(),line.querySelector('b')?.textContent.trim()])),expectedVisible=Object.fromEntries(Object.entries(rawLines).map(([id,value])=>[names[id],`+${compact(value)} Gold`])),totalText=modal.querySelector('[data-offline-gold-total] b')?.textContent.trim();
      add('offline-player-copy-and-total',Boolean(modal)&&/Offline Village rewards · up to 24 hours/.test(modal.textContent)&&/hours of Village production/.test(modal.textContent)&&modal.querySelectorAll('[data-offline-gold-total]').length===1&&lines.length>=5&&!modal.textContent.includes('Timestamp-based')&&JSON.stringify(visible)===JSON.stringify(expectedVisible)&&Object.is(rawTotal,56980.6688)&&totalText===`+${compact(rawTotal)} Gold`,JSON.stringify({visible,expectedVisible,rawTotal,totalText}));
      const collectionRecords=[],collectionObserver=new MutationObserver(()=>collectionRecords.push(status.textContent));collectionObserver.observe(status,{childList:true,characterData:true,subtree:true});modal.querySelector('[data-modal-act="collect-offline"]')?.click();await wait(30);collectionObserver.disconnect();const collected=status.textContent;result=bridge().act('collect',{});if(!result.ok)throw new Error(`Empty collection failed: ${result.error}`);await wait(30);const first=status.textContent,records=[],observer=new MutationObserver(()=>records.push(status.textContent));observer.observe(status,{childList:true,characterData:true,subtree:true});result=bridge().act('collect',{});if(!result.ok)throw new Error(`Repeated empty collection failed: ${result.error}`);await wait(30);observer.disconnect();
      add('collection-polite-announcement',collected==='Collected 57.0K Gold.'&&collectionRecords.filter(value=>value==='').length===1&&collectionRecords.filter(value=>value===collected).length===1,`${collected} · ${JSON.stringify(collectionRecords)}`);add('repeated-identical-polite-announcement',first==='Nothing is ready to collect.'&&status.textContent===first&&records.filter(value=>value==='').length===1&&records.filter(value=>value===first).length===1,`${first} · ${JSON.stringify(records)}`);
      const before=status.textContent;document.querySelector('[data-oath="o1"]')||await navigate('oaths');const complete=bridge().act('complete-oath',{id:'o1'});await wait(15);add('undo-action-excluded-from-status',complete.ok&&document.querySelector('[data-modal-act="undo-oath"]')?.textContent.trim()==='UNDO'&&status.textContent===before,status.textContent);await close();
    }
    async function rosterSummaries(){
      await navigate('fellows');await roster('fellows');let nodes=document.querySelectorAll('[data-village-roster-multiplier="fellow"]'),text=nodes[0]?.textContent.replace(/\s+/g,' ').trim()||'',oracle=config.oracle.fellowSummary;add('fellow-village-summary-once',nodes.length===1&&text.includes(`Village production · ${oracle.multiplier}`)&&text.includes(`${oracle.power} owned Fellow Power strengthens every Building.`),text);await roster('companions');nodes=document.querySelectorAll('[data-village-roster-multiplier="companion"]');text=nodes[0]?.textContent.replace(/\s+/g,' ').trim()||'';oracle=config.oracle.companionSummary;add('companion-village-summary-once',nodes.length===1&&text.includes(`Village production · ${oracle.multiplier}`)&&text.includes(`${oracle.power} owned Companion Power strengthens every Building.`),text);
    }
    async function deepLevels(){
      if(!config.viewport.deep)return;await navigate('village');bridge().controls.grant({resource:'gold',amount:config.deepGoldGrant});while(snapshot().buildings.training.level<51){const result=bridge().act('building-upgrade',{id:'training'});if(!result.ok)throw new Error(`Deep upgrade failed at ${snapshot().buildings.training.level}: ${result.error}`)}await wait(10);let evidence=modalEvidence(),before=snapshot(),beforeRaw=slots.get(config.keys.active),beforeProfile=JSON.stringify(before.economyProfile);add('level51-preview',before.buildings.training.level===51&&!evidence.button.disabled&&evidence.text.includes(`UPGRADE TO LEVEL 52 · ${compact(config.level51Cost)} GOLD`),evidence.text);const result=bridge().act('building-upgrade',{id:'training'});if(!result.ok)throw new Error(`Level 52 upgrade failed: ${result.error}`);await wait(10);evidence=modalEvidence();const after=snapshot(),afterRaw=slots.get(config.keys.active);add('level52-cap',after.buildings.training.level===52&&after.gold===before.gold-config.level51Cost&&after.saveMeta.revision===before.saveMeta.revision+1&&JSON.stringify(after.economyProfile)===beforeProfile&&afterRaw!==beforeRaw&&evidence.button.disabled&&evidence.button.textContent.trim()==='MAXIMUM LEVEL'&&/Maximum level reached\./.test(evidence.reason?.textContent||''),JSON.stringify({beforeGold:before.gold,afterGold:after.gold,beforeRevision:before.saveMeta.revision,afterRevision:after.saveMeta.revision,profilePreserved:JSON.stringify(after.economyProfile)===beforeProfile,text:evidence.text}));const capState=JSON.stringify(after),capRaw=afterRaw,refusal=bridge().act('building-upgrade',{id:'training'}),refusedState=JSON.stringify(snapshot()),refusedRaw=slots.get(config.keys.active);add('level52-refusal-byte-state-exact',refusal.ok===false&&refusedState===capState&&refusedRaw===capRaw,JSON.stringify({ok:refusal.ok,error:refusal.error,rawUnchanged:refusedRaw===capRaw,stateUnchanged:refusedState===capState}));await close();
    }
    (async()=>{
      await wait(500);add('bridge-present',Boolean(bridge()));add('viewport-exact',innerWidth===config.viewport.width&&innerHeight===config.viewport.height,`${innerWidth}x${innerHeight}`);add('schema11-runtime',snapshot().schemaVersion===11,snapshot().schemaVersion);add('thirteen-protected-slots',Object.keys(config.keys).length===13,Object.keys(config.keys).length);add('native-storage-instrumented',window.__PHASE_10C3_NATIVE_STORAGE_INSTRUMENTED__===true);
      await navigate('village');const geo=geometry();add('village-hotspots-unobstructed',geo.ok,JSON.stringify(geo.items));const hotspots=[...document.querySelectorAll('.building-hotspot')],hud=document.querySelector('[data-village-production-total]'),hotspotEvidence=hotspots.map(node=>({id:node.dataset.building,name:node.querySelector('strong')?.textContent.trim(),visible:node.querySelector('span')?.textContent.trim(),aria:node.getAttribute('aria-label')})),expectedHotspots=config.oracle.freshHotspots;add('hotspot-accessible-names',JSON.stringify(hotspotEvidence)===JSON.stringify(expectedHotspots),JSON.stringify(hotspotEvidence));add('aggregate-hud-accessible-name',hud?.textContent.trim()===config.oracle.hudVisible&&hud?.getAttribute('aria-label')===config.oracle.hudAria,JSON.stringify({visible:hud?.textContent.trim(),aria:hud?.getAttribute('aria-label')}));add('navigation-and-actions-preserved',document.querySelectorAll('.bottom-nav [data-nav]').length===5&&hotspots.length===4&&Boolean(document.querySelector('[data-act="collect"]')));
      const dialog=await dialogTarget();add('dialog-focus-escape-return',dialog.ok,JSON.stringify(dialog));const successorModal=await successorModalTarget();add('successor-modal-lifecycle-listener-overlay',successorModal.ok,JSON.stringify(successorModal));await inspectFreshAndShortage();const tabs=await rosterTabTarget();add('successor-four-tab-keyboard',tabs.ok,JSON.stringify(tabs));await rosterSummaries();await offlineAndStatus();await deepLevels();
      add('no-horizontal-overflow',document.documentElement.scrollWidth<=innerWidth,`${document.documentElement.scrollWidth}/${innerWidth}`);add('zero-native-storage-writes',window.__PHASE_10C3_NATIVE_STORAGE_ACCESSES__.filter(item=>item.startsWith('setItem:')||item.startsWith('removeItem:')).length===0,window.__PHASE_10C3_NATIVE_STORAGE_ACCESSES__.join(','));add('zero-native-storage-accesses',window.__PHASE_10C3_NATIVE_STORAGE_ACCESSES__.length===0,window.__PHASE_10C3_NATIVE_STORAGE_ACCESSES__.join(','));add('zero-warning-error-console',window.__PHASE_10C3_ERRORS__.length===0,window.__PHASE_10C3_ERRORS__.join('\n'));send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }
  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);const source=await response.text(),firstScript=source.indexOf('<script>');if(firstScript<0)throw new Error('Production script is missing');const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`,instrumented=source.slice(0,firstScript)+bootstrap+source.slice(firstScript).replace('</body>',suite+'</body>');document.open();document.write(instrumented);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
