#!/usr/bin/env python3
"""Build the browser-native immutable Phase 18–19 definition module."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APPROVED = ROOT / "design" / "phase-18-19-policy-approved"
DESIGN = ROOT / "design" / "phase-18-19"
OUTPUT = ROOT / "src" / "phase18-19-facilities.js"


def load(path: Path):
    return json.loads(path.read_text())


def compact(value):
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False).replace("<", "\\u003c")


def source():
    policy = load(APPROVED / "policy-approved.json")
    table = load(APPROVED / "fixed-reward-table.json")
    apothecary = load(DESIGN / "apothecary-definitions.json")
    schoolhouse = load(DESIGN / "schoolhouse-definitions.json")
    tutorials = load(APPROVED / "tutorial-timing.json")
    cast = load(APPROVED / "cast-schedule.json")
    return f"""/* Generated by scripts/build-phase18-19-runtime.py. Do not edit directly. */
(function(root){{
  'use strict';
  const POLICY={compact(policy)};
  const TABLE={compact(table)};
  const APOTHECARY={compact(apothecary)};
  const SCHOOLHOUSE={compact(schoolhouse)};
  const TUTORIALS={compact(tutorials)};
  const CAST={compact(cast)};
  const clone=value=>JSON.parse(JSON.stringify(value));
  const deepFreeze=value=>{{if(value&&typeof value==='object'&&!Object.isFrozen(value)){{Object.freeze(value);for(const child of Object.values(value))deepFreeze(child)}}return value}};
  const hash=text=>{{let value=2166136261;for(let index=0;index<text.length;index++){{value^=text.charCodeAt(index);value=Math.imul(value,16777619)}}return(value>>>0).toString(16).padStart(8,'0')}};
  const identity=(kind,saveId,parts)=>`${{kind}}:${{hash([saveId,...parts].join('\\u001f'))}}`;
  const randomUnit=(saveId,kind,ordinal)=>parseInt(hash(`${{saveId}}\\u001f${{kind}}\\u001f${{ordinal}}`),16)/4294967296;
  const weighted=(items,weightFor,unit)=>{{const eligible=items.filter(item=>weightFor(item)>0),total=eligible.reduce((sum,item)=>sum+weightFor(item),0);if(!eligible.length||!Number.isFinite(total)||total<=0)return null;let cursor=unit*total;for(const item of eligible){{cursor-=weightFor(item);if(cursor<0)return item}}return eligible.at(-1)}};
  const bandForRate=rate=>{{if(!Number.isSafeInteger(rate)||rate<0)return null;return TABLE.bands.find(item=>rate>=item.minimumGoldPerHourInclusive&&(item.maximumGoldPerHourInclusive===null||rate<=item.maximumGoldPerHourInclusive))||null}};
  const caseForOrdinal=(saveId,ordinal,eligibleCaseIds=APOTHECARY.caseTemplates.map(item=>item.id))=>weighted(APOTHECARY.caseTemplates.filter(item=>eligibleCaseIds.includes(item.id)),item=>POLICY.phase18ApothecaryPolicy.selectionPolicy.caseWeightById[item.id]||0,randomUnit(saveId,'apothecary-case',ordinal));
  const lessonForOrdinal=(saveId,ordinal,eligibleLessonIds=SCHOOLHOUSE.lessons.map(item=>item.id))=>weighted(SCHOOLHOUSE.lessons.filter(item=>eligibleLessonIds.includes(item.id)),item=>POLICY.phase19SchoolhousePolicy.selectionPolicy.lessonWeightById[item.id]||0,randomUnit(saveId,'schoolhouse-lesson',ordinal));
  const pupilOrder=saveId=>SCHOOLHOUSE.pupils.slice().sort((left,right)=>randomUnit(saveId,'schoolhouse-pupil',SCHOOLHOUSE.pupils.indexOf(left)+1)-randomUnit(saveId,'schoolhouse-pupil',SCHOOLHOUSE.pupils.indexOf(right)+1));
  const api={{
    configId:'phase-18-19-private-runtime-v1',definitionSetId:'definition-set.phase-18-19-private-runtime.v1',productionEnabled:true,privateReleaseOnly:true,publicReleaseAllowed:false,
    policy:POLICY,rewardTable:TABLE,apothecary:APOTHECARY,schoolhouse:SCHOOLHOUSE,tutorials:TUTORIALS,cast:CAST,
    clone,identity,randomUnit,weighted,bandForRate,caseForOrdinal,lessonForOrdinal,pupilOrder
  }};
  Object.defineProperty(root,'EVERSTEAD_PHASE_18_19',{{value:deepFreeze(api),enumerable:false,configurable:false,writable:false}});
}})(globalThis);
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = source()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print("FAIL src/phase18-19-facilities.js is stale")
            return 1
        print("PASS src/phase18-19-facilities.js is deterministic")
        return 0
    OUTPUT.write_text(expected)
    print(f"WROTE {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
