(()=>{
  'use strict';
  const CHANNEL='everstead-phase-22a-independent-v2',json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config){
    const slots=new Map(),writes=[],errors=[],nativeStorageAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);let saveIndex=0,transactionIndex=0,nativeStorageInstrumented=false;
    window.matchMedia=query=>({matches:config.viewport.reducedMotion&&query==='(prefers-reduced-motion: reduce)',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});document.documentElement.style.fontSize=`${config.viewport.copyScale||1}em`;
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    addEventListener('error',event=>{const target=event.target;if(target&&target!==window&&(target.src||target.href))errors.push(`asset-error ${target.src||target.href}`);else errors.push(String(event.error?.stack||event.message))},true);addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>{key=String(key);writes.push({op:'set',key,value:String(value)});slots.set(key,String(value))},removeItem:key=>{key=String(key);writes.push({op:'remove',key});slots.delete(key)}};
    Object.assign(window,{__P22A_CONFIG__:config,__P22A_SLOTS__:slots,__P22A_WRITES__:writes,__P22A_ERRORS__:errors,__P22A_NATIVE_ACCESSES__:nativeStorageAccesses,__P22A_NATIVE_INSTRUMENTED__:nativeStorageInstrumented});const runtime={storage:memoryStorage,clock:{now:()=>config.fixtures.frozenNow,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.4375,confirm:()=>true,ids:{save:()=>`save-p22a-${++saveIndex}`,transaction:()=>`tx-p22a-${++transactionIndex}`}};if(config.mode==='active')runtime.qa={allowDestructive:true,isolatedStorage:true};window.__EVERSTEAD_RUNTIME__=runtime;
  }

  function runSuite(){
    const config=window.__P22A_CONFIG__,f=config.fixtures,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),until=async(predicate,limit=10000)=>{const started=performance.now();while(performance.now()-started<limit){if(predicate())return true;await wait(25)}return false},same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),send=()=>parent.postMessage({channel:config.channel,nonce:config.nonce,results,errors:window.__P22A_ERRORS__.slice()},'*'),bridge=()=>window.__EVERSTEAD_PHASE_20_21_QA__,safe=(label,operation)=>{try{return operation()}catch(error){add(`${label}-call`,false,error.stack||error.message);return null}},call=(group,name,...args)=>safe(name,()=>bridge()[group][name](...args));
    const visible=node=>{if(!node)return false;const style=getComputedStyle(node),rect=node.getBoundingClientRect();return style.display!=='none'&&style.visibility!=='hidden'&&rect.width>0&&rect.height>0},rectData=node=>{const rect=node?.getBoundingClientRect();return rect?{left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom,width:rect.width,height:rect.height}:null},within=node=>{const rect=node?.getBoundingClientRect();return Boolean(rect&&rect.left>=-1&&rect.right<=innerWidth+1&&rect.top>=-1&&rect.bottom<=innerHeight+1)},target=node=>{const rect=node?.getBoundingClientRect();return Boolean(rect&&rect.width+0.1>=f.minimumTargetPx&&rect.height+0.1>=f.minimumTargetPx)},overlap=(a,b)=>Boolean(a&&b&&Math.max(a.left,b.left)<Math.min(a.right,b.right)&&Math.max(a.top,b.top)<Math.min(a.bottom,b.bottom)),revision=snapshot=>snapshot?.state?.saveMeta?.revision;
    const noOverflow=()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1&&document.body.scrollWidth<=document.body.clientWidth+1,hotspot=facilityId=>document.querySelector(`[data-phase15-facility-id="${facilityId}"]`),facility=facilityId=>call('read','derive')?.facilities?.[facilityId],recordFor=facilityId=>facility(facilityId)?.records?.at(-1)||null;
    const sha256=async value=>{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')};
    const sourceIdentity=async()=>{const link=[...document.querySelectorAll('link[rel="stylesheet"]')].find(node=>node.getAttribute('href')===f.stylesheetHref),sheet=[...document.styleSheets].find(item=>{try{const url=new URL(item.href);return url.pathname.endsWith(`/${f.stylesheet}`)&&url.searchParams.get('v')===f.stylesheetVersion}catch{return false}}),response=link?await fetch(link.href,{cache:'no-store'}):null,source=response?.ok?await response.text():'';return{ok:Boolean(link&&sheet&&response?.ok)&&await sha256(source)===f.stylesheetSha256,link:link?.getAttribute('href'),sheet:sheet?.href,sha256:source?await sha256(source):null}};
    const rewardFingerprint=()=>{const derived=call('read','derive'),state=call('read','snapshot')?.state,facilities=Object.fromEntries(Object.entries(derived?.facilities||{}).map(([id,value])=>[id,{claimedCount:value.claimedCount,localProgress:value.localProgress,lastReceiptId:value.lastReceiptId,records:value.records.map(record=>({id:record.opportunity.id,status:record.status,offerId:record.outcome?.offerId||null}))}]));return{resources:derived?.resources,facilities,recentReceipts:state?.phase15FacilityFoundation?.claimArchive?.recentReceipts?.map(item=>item.id),pendingOfferIds:Object.keys(state?.phase15FacilityFoundation?.pendingOffers||{}).sort()}};
    const dismissAmbient=async()=>{for(let count=0;count<4;count++){const close=document.querySelector('[data-modal-close],[data-phase17-close],[data-phase20-21-close]');if(!close)break;close.click();await wait(35)}};
    const prepareTruth=async()=>{const prepared=[];prepared.push(call('destructive','resetFixture',f.fixtureId));await wait(45);await dismissAmbient();const definitions=call('read','definitions'),tutorialStatus=call('read','derive')?.tutorials?.statusById||{};for(const tutorial of definitions?.tutorials?.filter(item=>item.enabled)||[]){const status=tutorialStatus[tutorial.id];if(status==='unseen')prepared.push(call('destructive','tutorial',tutorial.id,'seen'));if(['unseen','seen'].includes(status))prepared.push(call('destructive','tutorial',tutorial.id,'complete'))}for(const state of ['opportunity-ready','in-progress','claim-ready']){const facilityId=f.truthFixtures[state],seed=call('destructive','seedRecord',facilityId);prepared.push(seed);let record=recordFor(facilityId);if(state!=='opportunity-ready'){prepared.push(call('destructive','begin',facilityId,record.opportunity.id,record.identity));record=recordFor(facilityId)}if(state==='claim-ready'){const choice=window.EVERSTEAD_PHASE20_21_FACILITIES?.choicesFor(facilityId,record.templateId)?.[0]?.id;prepared.push(call('destructive','choose',facilityId,record.opportunity.id,record.identity,choice));record=recordFor(facilityId);prepared.push(call('destructive','commit',facilityId,record.opportunity.id,record.identity));record=recordFor(facilityId);prepared.push(call('destructive','resolve',facilityId,record.opportunity.id,record.identity))}}
      document.querySelector('.bottom-nav button[data-nav="oaths"]')?.click();await wait(35);document.querySelector('.bottom-nav button[data-nav="village"]')?.click();await wait(60);await dismissAmbient();return prepared;
    };
    const shellMetrics=()=>{const topbar=document.querySelector('.topbar'),brand=document.querySelector('.brand'),resources=document.querySelector('.resources'),bottom=document.querySelector('.bottom-nav'),topRect=rectData(topbar),brandRect=visible(brand)?rectData(brand):null,resourceRect=rectData(resources),bottomRect=rectData(bottom),buttons=[...document.querySelectorAll('#app button')].filter(visible),primary=[...document.querySelectorAll('#app main.screen .btn.primary,#app .screen .btn.primary')].filter(node=>visible(node)&&node.getBoundingClientRect().bottom>0&&node.getBoundingClientRect().top<innerHeight),covered=primary.filter(node=>overlap(rectData(node),bottomRect));return{pass:noOverflow()&&within(topbar)&&within(resources)&&within(bottom)&&resources.scrollWidth<=resources.clientWidth+1&&(!brandRect||!overlap(brandRect,resourceRect))&&buttons.every(target)&&covered.length===0,overflow:{document:[document.documentElement.clientWidth,document.documentElement.scrollWidth],body:[document.body.clientWidth,document.body.scrollWidth]},top:topRect,brand:brandRect,resources:resourceRect,bottom:bottomRect,targets:buttons.filter(node=>!target(node)).map(node=>({text:node.textContent.trim().slice(0,30),rect:rectData(node),className:node.className})),covered:covered.map(rectData)}};

    async function activeSuite(){
      await until(()=>bridge(),8000);const qa=bridge();add('trusted-phase20-21-bridge-present-version',Boolean(qa)&&qa.version===f.bridgeVersion,qa?.version);if(!qa){send();return}add('bridge-minimal-read-and-prep-surface',['raw','snapshot','validate','derive'].every(name=>typeof qa.read?.[name]==='function')&&['resetFixture','seedRecord','begin','choose','commit','resolve'].every(name=>typeof qa.destructive?.[name]==='function'));
      const prepared=await prepareTruth();add('truth-fixture-prepared-before-baseline',prepared.every(item=>item?.ok===true),prepared.map(item=>({ok:item?.ok,reason:item?.reason})));
      const source=await sourceIdentity();add('cache-versioned-source-load-byte-identity',source.ok,source);
      const nav=[...document.querySelectorAll('.bottom-nav button[data-nav]')].filter(visible),navIds=nav.map(node=>node.dataset.nav);add('exact-five-navigation-visible',same(navIds,f.navigation)&&nav.length===5,navIds);add('five-navigation-targets-contained',nav.every(node=>target(node)&&within(node)),nav.map(rectData));
      const truth=Object.entries(f.truthFixtures).map(([state,facilityId])=>{const node=hotspot(facilityId),after=node&&getComputedStyle(node,'::after'),style=node&&getComputedStyle(node);return{state,facilityId,phase15:node?.getAttribute('data-phase15-state'),board:node?.getAttribute('data-phase20-21-board-state'),label:node?.getAttribute('aria-label'),content:after?.content,background:after?.backgroundColor,border:style?.borderTopColor,shadow:style?.boxShadow,rect:rectData(node),pass:Boolean(node)&&node.getAttribute('data-phase15-state')==='ready'&&node.getAttribute('data-phase20-21-board-state')===state&&String(after?.content||'').includes(f.truthLabels[state])&&target(node)&&within(node)}});add('phase20-ready-active-claim-exact-live-truth',truth.every(item=>item.pass)&&new Set(truth.map(item=>item.content)).size===3&&new Set(truth.map(item=>`${item.background}|${item.border}|${item.shadow}`)).size===3,truth);
      const modalRawBefore=call('read','raw'),modalSnapshotBefore=call('read','snapshot'),modalRewardBefore=rewardFingerprint(),modalWritesBefore=window.__P22A_WRITES__.length,phase20Focus=hotspot(f.truthFixtures['in-progress']);phase20Focus?.focus();const focusStyle=phase20Focus&&getComputedStyle(phase20Focus);add('visible-keyboard-focus',document.activeElement===phase20Focus&&Number.parseFloat(focusStyle?.outlineWidth||'0')>=3,{active:document.activeElement?.getAttribute('data-phase15-facility-id'),outline:focusStyle?.outline});document.querySelector('.bottom-nav button[data-nav="fellows"]')?.click();await wait(100);const firstCard=document.querySelector('.char-card');firstCard?.focus();firstCard?.click();await wait(60);const overlay=document.querySelector('[data-overlay]'),modal=overlay?.querySelector('.modal[role="dialog"]'),close=modal?.querySelector('[data-modal-close],.close'),focusIn=Boolean(modal?.contains(document.activeElement)),layered=Number.parseInt(getComputedStyle(overlay||document.body).zIndex||'0',10)>Number.parseInt(getComputedStyle(document.querySelector('.bottom-nav')||document.body).zIndex||'0',10);add('modal-entry-controls-layer-and-targets',Boolean(modal)&&target(close)&&within(close)&&focusIn&&layered&&[...modal.querySelectorAll('button')].filter(visible).every(target),{modal:rectData(modal),close:rectData(close),focusIn,layered,active:document.activeElement?.outerHTML?.slice(0,140)});document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(60);add('modal-escape-exact-focus-return',!document.querySelector('[data-overlay]')&&document.activeElement===firstCard,{overlay:Boolean(document.querySelector('[data-overlay]')),active:document.activeElement?.className});const modalRawAfter=call('read','raw'),modalSnapshotAfter=call('read','snapshot'),modalRewardAfter=rewardFingerprint();add('modal-visit-save-and-reward-neutral',window.__P22A_WRITES__.length===modalWritesBefore&&modalRawAfter===modalRawBefore&&revision(modalSnapshotAfter)===revision(modalSnapshotBefore)&&same(modalRewardAfter,modalRewardBefore),{writeDelta:window.__P22A_WRITES__.length-modalWritesBefore,rawEqual:modalRawAfter===modalRawBefore,beforeRevision:revision(modalSnapshotBefore),afterRevision:revision(modalSnapshotAfter),rewardEqual:same(modalRewardAfter,modalRewardBefore)});
      const rawBefore=call('read','raw'),snapshotBefore=call('read','snapshot'),rewardBefore=rewardFingerprint(),writesBefore=window.__P22A_WRITES__.length;
      const traversal=[];for(const id of f.navigation){const button=[...document.querySelectorAll('.bottom-nav button[data-nav]')].find(node=>node.dataset.nav===id);button?.click();await wait(50);const active=[...document.querySelectorAll('.bottom-nav button[data-nav]')].find(node=>node.getAttribute('aria-current')==='page'||node.classList.contains('on')),metrics=shellMetrics();traversal.push({id,active:active?.dataset.nav,metrics});}add('all-five-surfaces-no-overflow-44px-or-covered-cta',traversal.every(item=>item.active===item.id&&item.metrics.pass),traversal);
      document.querySelector('.bottom-nav button[data-nav="village"]')?.click();await wait(45);const reducedNode=hotspot(f.truthFixtures['opportunity-ready']),reducedStyle=getComputedStyle(reducedNode||document.body),navStyle=getComputedStyle(document.querySelector('.bottom-nav button')||document.body),reducedClass=document.documentElement.classList.contains('phase15-reduced-motion');add('reduced-motion-authoritative-and-static',config.viewport.reducedMotion?(reducedStyle.animationName==='none'&&navStyle.transitionDuration==='0s'):(reducedStyle.animationName!=='none'&&!reducedClass),{requested:config.viewport.reducedMotion,reducedClass,animation:reducedStyle.animationName,transition:navStyle.transitionDuration});
      const rawAfter=call('read','raw'),snapshotAfter=call('read','snapshot'),rewardAfter=rewardFingerprint(),writeDelta=window.__P22A_WRITES__.length-writesBefore;add('visual-traversal-zero-save-writes',writeDelta===0&&rawAfter===rawBefore&&revision(snapshotAfter)===revision(snapshotBefore),{writeDelta,rawEqual:rawAfter===rawBefore,beforeRevision:revision(snapshotBefore),afterRevision:revision(snapshotAfter)});add('visual-traversal-zero-reward-writes',same(rewardAfter,rewardBefore),{before:rewardBefore,after:rewardAfter});add('final-state-valid',call('read','validate')?.ok===true,call('read','validate'));add('native-storage-instrumented',window.__P22A_NATIVE_INSTRUMENTED__===true);add('zero-native-storage-accesses',window.__P22A_NATIVE_ACCESSES__.length===0,window.__P22A_NATIVE_ACCESSES__);add('zero-warning-error-console',window.__P22A_ERRORS__.length===0,window.__P22A_ERRORS__);send();
    }

    async function inactiveSuite(){
      await wait(900);const source=await sourceIdentity();add('inactive-cache-versioned-source-load-byte-identity',source.ok,source);add('production-inactive-no-qa-bridge',!bridge());const definition=window.EVERSTEAD_PHASE20_21_FACILITIES;add('production-flags-remain-inactive',definition?.productionEnabled===false&&definition?.publicRelease===false,{productionEnabled:definition?.productionEnabled,publicRelease:definition?.publicRelease});const saves=[...window.__P22A_SLOTS__.values()].map(raw=>{try{return JSON.parse(raw)}catch{return null}}).filter(Boolean);add('inactive-save-has-no-phase20-21-root',saves.every(value=>!value.phase2021),saves.map(value=>({phase2021:Boolean(value.phase2021)})));const navIds=[...document.querySelectorAll('.bottom-nav button[data-nav]')].filter(visible).map(node=>node.dataset.nav),beforeWrites=window.__P22A_WRITES__.length;for(const id of navIds){document.querySelector(`.bottom-nav button[data-nav="${id}"]`)?.click();await wait(35)}const currentNav=[...document.querySelectorAll('.bottom-nav button[data-nav]')].filter(visible),metrics=shellMetrics();add('inactive-exact-five-shell-safe',same(navIds,f.navigation)&&same(currentNav.map(node=>node.dataset.nav),f.navigation)&&currentNav.every(target)&&metrics.pass,{nav:currentNav.map(node=>node.dataset.nav),metrics});add('inactive-visual-traversal-zero-save-writes',window.__P22A_WRITES__.length===beforeWrites,{beforeWrites,afterWrites:window.__P22A_WRITES__.length});add('inactive-no-phase20-board-ownership',[...document.querySelectorAll('[data-phase15-facility-id]')].every(node=>!node.hasAttribute('data-phase20-21-board-state')));add('inactive-zero-native-storage-accesses',window.__P22A_NATIVE_ACCESSES__.length===0,window.__P22A_NATIVE_ACCESSES__);add('inactive-zero-warning-error-console',window.__P22A_ERRORS__.length===0,window.__P22A_ERRORS__);send();
    }

    (config.mode==='active'?activeSuite():inactiveSuite()).catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();source=source.replace('<head>','<head><base href="../../">');const insertion=source.indexOf('<script'),bodyClose=source.lastIndexOf('</body>');if(insertion<0)throw new Error('Production script tag missing');if(bodyClose<0)throw new Error('Production body closing tag missing');const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`;source=source.slice(0,insertion)+bootstrap+source.slice(insertion,bodyClose)+suite+source.slice(bodyClose);document.open();document.write(source);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
