import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {existsSync,readFileSync,readdirSync,statSync} from 'node:fs';
import {resolve} from 'node:path';

const ROOT=resolve(new URL('../..',import.meta.url).pathname),QA=resolve(ROOT,'qa/phase-22a-independent'),EXPECTED=['README.md','checksums.sha256','fixtures/contract.json','index.html','realm.html','realm.js','runner.js','verify.mjs'],rows=[];
const read=path=>readFileSync(resolve(ROOT,path)),text=path=>read(path).toString('utf8'),json=path=>JSON.parse(text(path)),sha=value=>createHash('sha256').update(value).digest('hex'),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)});
const filesBelow=(directory,prefix='')=>readdirSync(directory).flatMap(name=>{const absolute=resolve(directory,name),path=prefix?`${prefix}/${name}`:name;return statSync(absolute).isDirectory()?filesBelow(absolute,path):[path]}).sort();
const git=(args,options={})=>spawnSync('git',args,{cwd:ROOT,encoding:'utf8',maxBuffer:64*1024*1024,...options});
const f=json('qa/phase-22a-independent/fixtures/contract.json'),focused=json('qa/phase-22a-shell/fixtures/contract.json'),realmSource=text('qa/phase-22a-independent/realm.js'),runnerSource=text('qa/phase-22a-independent/runner.js'),index=text('index.html'),normalized=index.replace(focused.stylesheetInclude,'');

record('package-topology',same(filesBelow(QA),EXPECTED),filesBelow(QA));
const checksumRows=text('qa/phase-22a-independent/checksums.sha256').trim().split('\n').filter(Boolean).map(line=>{const match=line.match(/^([0-9a-f]{64})  (.+)$/);return match?{expected:match[1],path:match[2]}:null}),checksumFailures=checksumRows.filter(item=>!item||!existsSync(resolve(ROOT,item.path))||sha(read(item.path))!==item.expected).map(item=>item?.path||'malformed');record('package-checksums',checksumRows.length===7&&checksumFailures.length===0,{count:checksumRows.length,failures:checksumFailures});
record('fixture-current-base-bridge-and-source',f.contractVersion===2&&f.baseCommit===focused.baseCommit&&f.sourceCommit===focused.sourceCommit&&f.bridgeVersion==='phase-20-21-independent-qa-v2'&&f.stylesheetHref===focused.stylesheetHref&&f.stylesheetSha256===focused.stylesheetSha256);
const sourceAncestor=git(['merge-base','--is-ancestor',f.sourceCommit,'HEAD']),sourceIndex=git(['show',`${f.sourceCommit}:index.html`],{encoding:null}),sourceCss=git(['show',`${f.sourceCommit}:${f.stylesheet}`],{encoding:null});
record('phase22a-source-commit-is-reachable',sourceAncestor.status===0,f.sourceCommit);
record('production-matches-frozen-source-commit',sourceIndex.status===0&&sourceCss.status===0&&sourceIndex.stdout.toString('hex')===read('index.html').toString('hex')&&sourceCss.stdout.toString('hex')===read(f.stylesheet).toString('hex'));
record('fixture-exact-navigation-and-truth',same(f.navigation,['village','oaths','fellows','adventure','more'])&&f.minimumTargetPx===44&&same(f.truthLabels,{'opportunity-ready':'READY','in-progress':'ACTIVE','claim-ready':'CLAIM'})&&new Set(Object.values(f.truthFixtures)).size===3);
record('fixture-all-required-realms',f.viewports.length===7&&same(f.viewports.slice(0,5).map(item=>[item.width,item.height]),[[320,568],[390,844],[430,932],[768,1024],[1024,768]])&&f.viewports.some(item=>item.copyScale===1.3)&&f.viewports.some(item=>item.reducedMotion)&&f.inactiveViewport.width===390&&f.inactiveViewport.height===844);
record('production-normalizes-to-exact-current-tip',Buffer.byteLength(normalized)===focused.baseIndexBytes&&sha(normalized)===focused.baseIndexSha256,{sha256:sha(normalized),bytes:Buffer.byteLength(normalized)});
record('production-single-cache-versioned-stylesheet',index.split(focused.stylesheetInclude).length===2&&index.indexOf(focused.stylesheetInclude)>index.lastIndexOf('</style>')&&!index.includes('__EVERSTEAD_PHASE_22A_QA__'));
record('runner-loads-real-candidate-and-current-bridge',realmSource.includes("fetch('../../index.html'")&&realmSource.includes('__EVERSTEAD_PHASE_20_21_QA__')&&realmSource.includes('qa.version===f.bridgeVersion')&&!realmSource.includes('fakeEngine'));
record('runner-explicit-safe-payload-splice',realmSource.includes("lastIndexOf('</body>')")&&realmSource.includes('source.slice(0,insertion)+bootstrap+source.slice(insertion,bodyClose)+suite+source.slice(bodyClose)')&&!realmSource.includes("replace('</body>',suite"));
record('runner-source-load-identity',['f.stylesheetHref','f.stylesheetVersion','crypto.subtle.digest','f.stylesheetSha256','cache-versioned-source-load-byte-identity'].every(value=>realmSource.includes(value)));
record('runner-five-nav-target-overflow-cta',['exact-five-navigation-visible','five-navigation-targets-contained','all-five-surfaces-no-overflow-44px-or-covered-cta','getBoundingClientRect','scrollWidth','overlap(rectData(node),bottomRect)'].every(value=>realmSource.includes(value)));
record('runner-phase20-distinct-truth',['truthFixtures','truthLabels','opportunity-ready','in-progress','claim-ready','getComputedStyle(node,\'::after\')','new Set(truth.map(item=>item.content)).size===3','new Set(truth.map(item=>`${item.background}|${item.border}|${item.shadow}`)).size===3'].every(value=>realmSource.includes(value))&&same(f.truthLabels,{'opportunity-ready':'READY','in-progress':'ACTIVE','claim-ready':'CLAIM'}));
record('runner-focus-escape-and-return',['visible-keyboard-focus','KeyboardEvent','Escape','modal-entry-controls-layer-and-targets','modal-escape-exact-focus-return','document.activeElement===firstCard'].every(value=>realmSource.includes(value)));
record('runner-zero-save-and-reward-writes',['filter(item=>item.enabled)','tutorial.id,\'complete\'','modal-visit-save-and-reward-neutral','modalRawAfter===modalRawBefore','writesBefore','visual-traversal-zero-save-writes','visual-traversal-zero-reward-writes','rawAfter===rawBefore','revision(snapshotAfter)===revision(snapshotBefore)','rewardFingerprint'].every(value=>realmSource.includes(value)));
record('runner-reduced-copy-and-inactive-production',['copyScale','reduced-motion-authoritative-and-static','config.mode===\'active\'','production-inactive-no-qa-bridge','production-flags-remain-inactive','inactive-visual-traversal-zero-save-writes'].every(value=>realmSource.includes(value)));
record('runner-isolated-storage-and-console-safety',['allowDestructive:true','isolatedStorage:true','zero-native-storage-accesses','zero-warning-error-console','inactive-zero-native-storage-accesses','inactive-zero-warning-error-console'].every(value=>realmSource.includes(value)));
record('runner-seven-active-plus-one-inactive',runnerSource.includes('for(const viewport of f.viewports)')&&runnerSource.includes("realm(f,f.inactiveViewport,'inactive')")&&runnerSource.includes('__EVERSTEAD_PHASE_22A_INDEPENDENT_RESULT__'));
for(const file of ['runner.js','realm.js','verify.mjs']){const checked=spawnSync(process.execPath,['--check',`qa/phase-22a-independent/${file}`],{cwd:ROOT,encoding:'utf8'});record(`syntax-${file}`,checked.status===0,checked.stderr.trim())}

const passed=rows.filter(row=>row.pass).length,failed=rows.length-passed;for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` — ${row.detail}`:''}`);console.log(`RESULT ${passed} passed, ${failed} failed`);process.exitCode=failed?1:0;
