(()=>{
  'use strict';
  const CHANNEL='everstead-phase-23-successor-compatibility-v1';
  const json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config){
    const slots=new Map(),writes=[],errors=[],nativeStorageAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);let saveIndex=0,transactionIndex=0,nativeStorageInstrumented=false;
    window.matchMedia=query=>({matches:false,media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    addEventListener('error',event=>{const target=event.target;if(target&&target!==window&&(target.src||target.href)){if(target.matches?.('img[data-roster-art],img[data-village-cutout],[data-phase23-companion-full-art],[data-phase23-companion-thumb]'))return;errors.push(`asset-error ${target.src||target.href}`)}else errors.push(String(event.error?.stack||event.message))},true);
    addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));
    const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>{key=String(key);writes.push({op:'set',key,value:String(value)});slots.set(key,String(value))},removeItem:key=>{key=String(key);writes.push({op:'remove',key});slots.delete(key)}};
    Object.assign(window,{__P23C_CONFIG__:config,__P23C_SLOTS__:slots,__P23C_WRITES__:writes,__P23C_ERRORS__:errors,__P23C_NATIVE_ACCESSES__:nativeStorageAccesses,__P23C_NATIVE_INSTRUMENTED__:nativeStorageInstrumented});
    window.__EVERSTEAD_RUNTIME__={storage:memoryStorage,clock:{now:()=>config.contract.frozenNow,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.999,confirm:()=>true,ids:{save:()=>`save-p23c-${++saveIndex}`,transaction:()=>`tx-p23c-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
  }

  function runSuite(){
    const config=window.__P23C_CONFIG__,f=config.contract,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),near=(a,b,epsilon=1e-9)=>typeof a==='number'&&typeof b==='number'&&Math.abs(a-b)<=epsilon*Math.max(1,Math.abs(a),Math.abs(b)),add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),send=()=>parent.postMessage({channel:config.channel,nonce:config.nonce,results,errors:window.__P23C_ERRORS__.slice()},'*');
    const p23=()=>window.__EVERSTEAD_PHASE_23_QA__,main=()=>window.__EVERSTEAD_QA__,p1819=()=>window.__EVERSTEAD_PHASE_18_19_QA__,safe=(label,operation)=>{try{return operation()}catch(error){add(`${label}-call`,false,error.stack||error.message);return null}},call23=(group,name,...args)=>safe(name,()=>p23()[group][name](...args)),revision=snapshot=>snapshot?.state?.saveMeta?.revision,visible=node=>{if(!node)return false;const style=getComputedStyle(node),rect=node.getBoundingClientRect();return style.display!=='none'&&style.visibility!=='hidden'&&style.opacity!=='0'&&rect.width>0&&rect.height>0};
    const click=async node=>{node?.click();await wait(55)},nav=id=>[...document.querySelectorAll('.bottom-nav button[data-nav]')].find(node=>node.dataset.nav===id),dismissPresentations=async()=>{for(let attempt=0;attempt<20;attempt++){const overlays=[...document.querySelectorAll('.overlay')].filter(visible),overlay=overlays.at(-1);if(!overlay)return true;const close=[...overlay.querySelectorAll('[data-modal-close],[data-phase17-close],[data-phase13-story="skip"],[data-phase15-tutorial-action="skip"],[data-phase16-tutorial-action="skip"]')].find(visible);if(close)close.click();else document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await wait(40)}return ![...document.querySelectorAll('.overlay')].some(visible)},snapshot=()=>call23('read','snapshot'),diagnostics=()=>safe('diagnostics',()=>main().diagnostics({at:f.frozenNow})?.diagnostics),passive=()=>safe('passive-baseline',()=>p1819().read.passiveBaseline(f.frozenNow)),actualWrites=()=>window.__P23C_WRITES__.length;
    const buildingById=baseline=>{const map={'facility.command-center':'command','facility.archives':'archives','facility.training-grounds':'training','facility.hearth':'hearth'};return Object.fromEntries((baseline?.buildingSemantics||[]).map(item=>[map[item.facilityId],item]))},goldFingerprint=state=>({gold:state.gold,prosperity:state.prosperity,pendingGold:state.pendingGold,gifts:state.gifts,relicStones:state.relicStones,might:state.fellowMight,expedition:state.fellowExpedition});

    async function reset(id){const result=call23('destructive','resetFixture',id);await wait(120);await dismissPresentations();return result}

    async function testFreshEconomy(){
      const prepared=await reset(f.fixtureIds.fresh),snap=snapshot(),state=snap?.state,base=passive(),rows=buildingById(base),expected=f.freshEconomy;
      const exactRows=Object.entries(expected.buildings).every(([id,want])=>{const got=rows[id];return got&&got.level===1&&got.baseGoldPerHour===want.base&&near(got.familyAssignmentMultiplier,want.familyMultiplier)&&near(got.effectiveGoldPerHour,want.rate)&&got.effectiveOathBoost===0});
      const diag=diagnostics(),components=diag?.buildingRateComponents||{},command=components.command;
      add('schema13-fresh-valid-authority',prepared?.ok===true&&state?.schemaVersion===13&&call23('read','validate')?.ok===true,{prepared,validation:call23('read','validate')});
      add('fresh-exact-joined-fellow-economy-power-and-bonus',command?.fellowRosterPower===expected.fellowPower&&command?.fellowRosterBps===expected.fellowBps&&near(command?.fellowRosterMultiplier,expected.fellowMultiplier),command);
      add('fresh-exact-20-companion-economy-power-and-bonus',command?.companionRosterPower===expected.companionPower&&command?.companionRosterBps===expected.companionBps&&near(command?.companionRosterMultiplier,expected.companionMultiplier),command);
      add('fresh-exact-four-building-rates-and-total',exactRows&&near((base?.buildingSemantics||[]).reduce((sum,item)=>sum+item.effectiveGoldPerHour,0),expected.totalRate),base);
      const direct=document.querySelector('[data-building="command"]'),facility=document.querySelector('[data-phase15-facility-id="facility.command-center"]');if(direct)await click(direct);else if(facility){await click(facility);await click(document.querySelector('[data-phase15-open-building="command"]'))}const details=document.querySelector('[data-building-production-details]'),detailsText=details?.innerText||'';
      add('building-production-sheet-projects-schema13-roster-multipliers',visible(details)&&detailsText.includes('×1.0390')&&detailsText.includes('×1.0080'),detailsText);
      await dismissPresentations();
    }

    async function testJoinedProjection(){
      await reset(f.fixtureIds.fresh);await click(nav('fellows'));await dismissPresentations();const path=document.querySelector('[data-phase-11g-path]'),tab=document.querySelector('[data-roster="fellows"]'),cards=[...document.querySelectorAll('[data-fellow]')],unlocked=cards.filter(card=>!card.classList.contains('phase-11g-locked')).map(card=>card.dataset.fellow),locked=cards.filter(card=>card.classList.contains('phase-11g-locked')).map(card=>card.dataset.fellow);
      add('fellowship-screen-derived-rank1-joined-count-and-order',/6\/18 Fellows joined/.test(path?.innerText||'')&&/Fellows\s*·\s*6\/18/.test(tab?.textContent||'')&&same(unlocked,f.joinedFellowIdsAtRank1)&&same(locked,f.allFellowIds.slice(6)),{path:path?.innerText,tab:tab?.textContent,unlocked,locked});
      await click(nav('adventure'));await dismissPresentations();const fellowTab=document.querySelector('[data-adventure="fellowCampaign"]');await click(fellowTab);const target=document.querySelector('[data-phase-11g-training-target]'),targetId=target?.querySelector('[data-roster-art]')?.getAttribute('data-roster-art'),powerNode=document.querySelector('[data-combat-fellow-roster-power="campaign"]'),diag=diagnostics();
      add('fellow-campaign-target-and-total-use-exact-joined-roster',targetId===f.stageOneTargetPool[0]&&f.stageOneTargetPool.includes(targetId)&&diag?.totalFellowRosterPower===f.freshCombatFellowPower&&powerNode?.textContent.trim()==='36.4K',{targetId,powerText:powerNode?.textContent,diagnosticTotal:diag?.totalFellowRosterPower,economyPower:f.freshEconomy.fellowPower});
      await click(nav('village'));await dismissPresentations();const cutout=document.querySelector('[data-village-cutout]'),speakerId=cutout?.getAttribute('data-village-cutout');add('village-speaker-selection-excludes-unjoined-fellows',f.joinedFellowIdsAtRank1.includes(speakerId),speakerId);
    }

    async function testRankLocks(){
      await reset(f.fixtureIds.fresh);await click(nav('adventure'));await dismissPresentations();const before=snapshot(),rawBefore=call23('read','raw'),writesBefore=actualWrites(),evidence=[];
      for(const [route,requiredRank] of Object.entries(f.rankOneLockedRoutes)){const button=document.querySelector(`[data-adventure="${route}"]`),markup={route,requiredRank,aria:button?.getAttribute('aria-disabled'),copy:button?.textContent};await click(button);const afterClick=snapshot(),heading=document.querySelector('main.screen h1')?.textContent.trim(),action=safe(`rank-action-${route}`,()=>main().act('adventure',{tab:route})),afterAction=snapshot();evidence.push({...markup,heading,uiAfterClick:afterClick?.state?.ui?.adventure,uiAfterAction:afterAction?.state?.ui?.adventure,actionOk:action?.ok,rawStable:call23('read','raw')===rawBefore,revisionStable:revision(afterAction)===revision(before)})}
      add('rank1-locked-route-clicks-and-actions-refuse-with-screen-state-aligned',evidence.every(item=>item.aria==='true'&&item.copy.includes(`R${item.requiredRank}`)&&item.uiAfterClick==='fellowCampaign'&&item.uiAfterAction==='fellowCampaign'&&item.actionOk===false&&item.heading==='Fellow Campaign'&&item.rawStable&&item.revisionStable)&&actualWrites()===writesBefore,evidence);
    }

    async function testBuildingLadder(){
      await reset(f.fixtureIds.allUnlocked);const costs=f.buildingUpgrade.costsByStartingLevel,observed=[],start=snapshot();for(const expectedCost of costs){const before=snapshot(),result=safe('building-upgrade',()=>main().act('building-upgrade',{id:f.buildingUpgrade.id})),after=snapshot();observed.push({expectedCost,actualCost:before?.state?.gold-after?.state?.gold,beforeLevel:before?.state?.buildings?.[f.buildingUpgrade.id]?.level,afterLevel:after?.state?.buildings?.[f.buildingUpgrade.id]?.level,ok:result?.ok,valid:call23('read','validate')?.ok});await dismissPresentations()}const atCap=snapshot(),rawAtCap=call23('read','raw'),writesAtCap=actualWrites(),refused=safe('building-at-cap',()=>main().act('building-upgrade',{id:f.buildingUpgrade.id})),afterRefused=snapshot();
      add('building-upgrade-exact-1.24-cost-ladder-through-level52',start?.state?.buildings?.[f.buildingUpgrade.id]?.level===1&&observed.every((row,index)=>row.ok===true&&row.beforeLevel===index+1&&row.afterLevel===index+2&&row.actualCost===row.expectedCost&&row.valid===true)&&atCap?.state?.buildings?.[f.buildingUpgrade.id]?.level===f.buildingUpgrade.levelCap,observed.filter(row=>!row.ok||row.actualCost!==row.expectedCost||!row.valid));
      add('building-level52-cap-refuses-with-zero-write',refused?.ok===false&&call23('read','raw')===rawAtCap&&revision(afterRefused)===revision(atCap)&&actualWrites()===writesAtCap,{refused,revision:[revision(atCap),revision(afterRefused)],writes:[writesAtCap,actualWrites()]});
      const raw=call23('read','raw'),revisionBefore=revision(atCap),reloaded=call23('destructive','reload'),afterReload=snapshot();add('building-ladder-reload-byte-stable-and-valid',reloaded?.ok===true&&call23('read','raw')===raw&&revision(afterReload)===revisionBefore&&call23('read','validate')?.ok===true,{reloaded,rawStable:call23('read','raw')===raw,revision:[revisionBefore,revision(afterReload)]});
    }

    async function testRelic(){
      await reset(f.fixtureIds.allUnlocked);const beforeState=snapshot()?.state,beforeDiag=diagnostics(),before=beforeDiag?.fellowPowerComponents?.[f.relic.fellowId],beforeTotal=beforeDiag?.totalFellowRosterPower,result=safe('relic-equip',()=>main().act('relic-equip',{fellowId:f.relic.fellowId,relicId:f.relic.id})),afterState=snapshot()?.state,afterDiag=diagnostics(),after=afterDiag?.fellowPowerComponents?.[f.relic.fellowId],expectedAfterRelic=before?.afterBondMilestone*f.relic.multiplier,expectedAfterCompanion=expectedAfterRelic+before?.transferredPower,expectedUnrounded=expectedAfterCompanion*before?.familyBondMultiplier*before?.globalMultiplier,expectedPower=Math.round(expectedUnrounded),expectedTotal=beforeTotal-before?.effectivePower+expectedPower;
      add('schema13-relic-equip-applies-exact-power-order-and-total',result?.ok===true&&beforeState?.relics?.[f.relic.id]?.owned===true&&afterState?.fellows?.[f.relic.fellowId]?.relicSlots?.[0]===f.relic.id&&after?.relicId===f.relic.id&&after?.relicBonusBps===f.relic.bonusBps&&near(after?.relicMultiplier,f.relic.multiplier)&&near(after?.afterRelic,expectedAfterRelic)&&near(after?.afterCompanion,expectedAfterCompanion)&&near(after?.unroundedPower,expectedUnrounded)&&after?.effectivePower===expectedPower&&afterDiag?.totalFellowRosterPower===expectedTotal,{result,before,after,expectedPower,expectedTotal,actualTotal:afterDiag?.totalFellowRosterPower});
      const raw=call23('read','raw'),rev=revision(snapshot()),reload=call23('destructive','reload'),reloaded=diagnostics()?.fellowPowerComponents?.[f.relic.fellowId];add('schema13-relic-effect-reloads-without-reversion',reload?.ok===true&&call23('read','raw')===raw&&revision(snapshot())===rev&&reloaded?.relicId===f.relic.id&&reloaded?.effectivePower===expectedPower&&call23('read','validate')?.ok===true,{reload,reloaded,expectedPower});
    }

    async function testExpeditionBoundary(){
      const hook=p23()?.destructive?.exerciseFellowExpeditionBoundary;add('expedition-boundary-genuine-bridge-hook-present',typeof hook==='function',typeof hook);if(typeof hook!=='function')return;
      const proof=safe('expedition-boundary',()=>hook()),expected=f.expeditionBoundary,stageA=proof?.progression?.stageA,stageB=proof?.progression?.stageB,first=proof?.boundaries?.first,second=proof?.boundaries?.second,receipt=proof?.claim?.receipt,pricing=proof?.claim?.preClaimPricing,firstSegment=first?.segments?.[0],secondSegments=second?.segments||[],progressionGenuine=proof?.guard?.qaOnly===true&&proof?.guard?.isolatedStorage===true&&proof?.guard?.destructiveAuthorized===true&&proof?.progression?.campaignStageIds?.length===9&&proof?.progression?.campaignReceiptIdentities?.length===9&&new Set(proof.progression.campaignReceiptIdentities).size===9&&proof?.progression?.rank===5&&proof?.progression?.firstBestReceipt?.highestStage===stageA&&proof?.progression?.secondBestReceipt?.highestStage===stageB;
      add('expedition-segmented-two-stage-shared-24h-cap-exact',proof?.ok===true&&progressionGenuine&&Number.isInteger(stageA)&&Number.isInteger(stageB)&&stageB>stageA&&proof?.policy?.intervalMs===expected.intervalMs&&proof?.policy?.elapsedCapMs===expected.capMs&&first?.settlement?.elapsed===expected.firstElapsedMs&&first?.settlement?.credited===expected.firstElapsedMs&&first?.settlement?.discarded===0&&first?.segments?.length===1&&firstSegment?.stage===stageA&&firstSegment?.elapsedMs===expected.firstElapsedMs&&second?.settlement?.elapsed===expected.secondElapsedMs&&second?.settlement?.credited===expected.secondIntervals*expected.intervalMs&&second?.settlement?.discarded===expected.discardedMs&&second?.creditedHours===expected.secondIntervals&&second?.discardedHours===expected.discardedMs/expected.intervalMs&&secondSegments.length===2&&secondSegments[0]?.stage===stageA&&secondSegments[0]?.elapsedMs===expected.firstElapsedMs&&secondSegments[1]?.stage===stageB&&secondSegments[1]?.elapsedMs===expected.secondIntervals*expected.intervalMs&&second?.intervalCountsByStage?.[String(stageA)]===expected.firstIntervals&&second?.intervalCountsByStage?.[String(stageB)]===expected.secondIntervals,proof);
      const frozenPricing=receipt?.preClaimBestRunSequence===pricing?.bestRunSequence&&receipt?.preClaimHighestStage===pricing?.highestStage&&receipt?.preClaimCursorAt===pricing?.cursorAt&&same(receipt?.preClaimSegments,pricing?.segments)&&pricing?.highestStage===stageB&&pricing?.cursorAt===second?.at,exactClaim=proof?.claim?.receiptExact===true&&receipt?.consumedElapsedMs===expected.capMs&&receipt?.intervalOrdinalEnd-receipt?.intervalOrdinalStart===expected.totalIntervals&&receipt?.intervalCountsByStage?.[String(stageA)]===expected.firstIntervals&&receipt?.intervalCountsByStage?.[String(stageB)]===expected.secondIntervals&&receipt?.mightAwarded===210&&proof?.claim?.rewardDelta?.might===210&&same(receipt?.fellowShards,proof?.claim?.rewardDelta?.fellowShards)&&proof?.claim?.postClaimedIntervalsByStage?.[String(stageA)]===expected.firstIntervals&&proof?.claim?.postClaimedIntervalsByStage?.[String(stageB)]===expected.secondIntervals&&proof?.claim?.postClaimSegments?.length===0;
      add('expedition-exact-claim-reload-replay-no-repricing',exactClaim&&frozenPricing&&proof?.claim?.claimWrites>0&&proof?.reload?.ok===true&&proof?.reload?.writes===0&&proof?.reload?.rawUnchanged===true&&proof?.replay?.ok===false&&proof?.replay?.refused===true&&proof?.replay?.writes===0&&proof?.replay?.rawUnchanged===true&&proof?.replay?.revisionUnchanged===true&&proof?.validation?.ok===true,proof);
    }

    (async()=>{await wait(900);add('trusted-real-phase23-bridge-present',p23()?.version===f.bridgeVersion,p23()?.version);add('inherited-main-and-phase18-bridges-present',main()?.version===1&&p1819()?.version==='phase-18-19-independent-qa-v1',{main:main()?.version,phase1819:p1819()?.version});if(p23()?.version!==f.bridgeVersion||main()?.version!==1||p1819()?.version!=='phase-18-19-independent-qa-v1'){send();return}await testFreshEconomy();await testJoinedProjection();await testRankLocks();await testBuildingLadder();await testRelic();await testExpeditionBoundary();add('final-schema13-state-valid',call23('read','validate')?.ok===true,call23('read','validate'));add('native-storage-instrumented',window.__P23C_NATIVE_INSTRUMENTED__===true);add('zero-native-storage-accesses',window.__P23C_NATIVE_ACCESSES__.length===0,window.__P23C_NATIVE_ACCESSES__);add('zero-warning-error-console',window.__P23C_ERRORS__.length===0,window.__P23C_ERRORS__);send()})().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();if(source.indexOf('<script')<0)throw new Error('Production script tag missing');source=source.replace('<head>','<head><base href="../../">');const insertion=source.indexOf('<script'),bodyClose=source.lastIndexOf('</body>');if(bodyClose<0)throw new Error('Production body closing tag missing');const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`;source=source.slice(0,insertion)+bootstrap+source.slice(insertion,bodyClose)+suite+source.slice(bodyClose);document.open();document.write(source);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
