(()=>{
  'use strict';
  const CHANNEL='everstead-phase-23-successor-compatibility-v1';
  const byId=id=>document.getElementById(id);
  const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const row=(id,actual,detail='')=>({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)});
  async function loadJson(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.json()}
  function realm(contract){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),config={channel:CHANNEL,nonce,contract};frame.name=JSON.stringify(config);frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${contract.viewport.width}px;height:${contract.viewport.height}px;border:0`;let timer;const finish=(error,value)=>{clearTimeout(timer);removeEventListener('message',receive);frame.remove();error?reject(error):resolve(value)},receive=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=(event.data.results||[]).map(item=>({...item,id:`${contract.viewport.id}-${item.id}`}));if(event.data.errors?.length)rows.push(row(`${contract.viewport.id}-captured-errors`,false,event.data.errors.join('\n')));finish(null,rows)};timer=setTimeout(()=>finish(new Error('successor compatibility realm timed out')),120000);addEventListener('message',receive);frame.src=`./realm.html?qa=1&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  function render(mode,rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('mode').textContent=mode;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)} · observed ${item.actual?'true':'false'} · expected true${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_23_SUCCESSOR_COMPATIBILITY_RESULT__={mode,passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const contract=await loadJson('./fixtures/contract.json'),rows=[];rows.push(row('fixture-contract-v1',contract.contractVersion===1&&contract.phase===23&&contract.schemaVersion===13&&contract.bridgeVersion==='phase-23-independent-qa-v1'));rows.push(row('fixture-1.24-exact-cost-table',contract.buildingUpgrade.costsByStartingLevel.length===contract.buildingUpgrade.levelCap-1&&contract.buildingUpgrade.costsByStartingLevel.every((cost,index)=>cost===Math.round(contract.buildingUpgrade.baseCost*Math.pow(contract.buildingUpgrade.growth,index)))));rows.push(row('fixture-exact-rank-one-joined-set',contract.joinedFellowIdsAtRank1.join(',')===contract.allFellowIds.slice(0,6).join(',')&&contract.allFellowIds.length===18));rows.push(row('fixture-exact-economy-total',Object.values(contract.freshEconomy.buildings).reduce((sum,item)=>sum+item.rate,0)===contract.freshEconomy.totalRate));rows.push(...await realm(contract));render('CANDIDATE',rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render('FATAL',[row('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
