(() => {
  'use strict';
  const CHANNEL='everstead-phase-11b2c',byId=id=>document.getElementById(id),escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),row=(id,actual,detail='')=>({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:String(detail)});
  async function bytes(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return new Uint8Array(await response.arrayBuffer())}
  async function contract(){const [scenarioBytes,artifactBytes]=await Promise.all([bytes('./scenarios.json'),bytes('../../index.html')]),scenarios=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(scenarioBytes)),source=new TextDecoder('utf-8',{fatal:true}).decode(artifactBytes),assets=[...source.matchAll(/data:image\/[^;]+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]),digest=async value=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',value))].map(byte=>byte.toString(16).padStart(2,'0')).join(''),artifactSha=await digest(artifactBytes),assetSha=await digest(new TextEncoder().encode(assets.join('\n'))),rows=[],slotMarkers=['const NS=','RAW_BACKUP_KEY','PRE_V2_BACKUP_KEY','PRE_V3_BACKUP_KEY','PRE_V4_BACKUP_KEY','PRE_V5_BACKUP_KEY','PRE_V6_BACKUP_KEY','PRE_V7_BACKUP_KEY','PRE_V8_BACKUP_KEY','PRE_V9_BACKUP_KEY','PRE_V10_BACKUP_KEY','PRE_V11_BACKUP_KEY','STAGING_KEY','PHASE_ELEVEN_B_TWO_JOURNAL_KEY','PHASE_ELEVEN_B_TWO_ROLLBACK_KEY'];rows.push(row('artifact-sha-exact',artifactSha===scenarios.artifact.sha256,artifactSha));rows.push(row('artifact-byte-length-exact',artifactBytes.byteLength===scenarios.artifact.byteLength,artifactBytes.byteLength));rows.push(row('schema-11-static',source.includes('CURRENT_SCHEMA_VERSION=11')));rows.push(row('phase-11b2c-static',source.includes('Phase 11B-2c · player-facing import')&&source.includes('Phase 11B-2c · recovery-surface accessibility')));rows.push(row('fifteen-slot-static',Object.keys(scenarios.storageKeys).length===15&&new Set(Object.values(scenarios.storageKeys)).size===15&&slotMarkers.length===15&&slotMarkers.every(marker=>source.includes(marker))));rows.push(row('embedded-assets-byte-identical',assets.length===scenarios.artifact.assetCount&&assetSha===scenarios.artifact.assetAggregateSha256,`${assets.length} · ${assetSha}`));return{scenarios,rows}}
  function realm(contract,viewport){return new Promise((resolve,reject)=>{const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),config={channel:CHANNEL,nonce,viewport,now:Date.parse(contract.scenarios.frozenNow),keys:contract.scenarios.storageKeys,fixture:contract.scenarios.fixture};frame.name=JSON.stringify(config);frame.style.cssText=`position:absolute;left:-20000px;top:0;width:${viewport.width}px;height:${viewport.height}px;border:0`;let timer;const done=(error,value)=>{clearTimeout(timer);removeEventListener('message',message);frame.remove();error?reject(error):resolve(value)},message=event=>{if(event.source!==frame.contentWindow||event.data?.channel!==CHANNEL||event.data?.nonce!==nonce)return;const rows=event.data.results.map(item=>({...item,id:`${viewport.id}-${item.id}`}));if(event.data.errors?.length&&!rows.some(item=>item.id.endsWith('zero-warning-error-console')&&!item.pass))rows.push(row(`${viewport.id}-captured-errors`,false,event.data.errors.join('\n')));done(null,rows)};timer=setTimeout(()=>done(new Error(`${viewport.id} timed out`)),180000);addEventListener('message',message);frame.src=`./realm.html?qa=1&nonce=${encodeURIComponent(nonce)}`;document.body.appendChild(frame)})}
  function render(mode,rows){const passed=rows.filter(item=>item.pass).length,failed=rows.length-passed;byId('mode').textContent=mode;byId('total').textContent=rows.length;byId('passed').textContent=passed;byId('failed').textContent=failed;byId('results').innerHTML=rows.map(item=>`<article class="result"><code>${escapeHtml(item.id)} · observed ${item.actual?'true':'false'} · expected true${item.detail?` · ${escapeHtml(item.detail)}`:''}</code><b class="${item.pass?'pass':'fail'}">${item.pass?'PASS':'FAIL'}</b></article>`).join('');window.__EVERSTEAD_PHASE_11B2C_RESULT__={mode,passed,failed,total:rows.length,results:rows}}
  async function run(){byId('run').disabled=true;byId('fatal').textContent='';try{const data=await contract(),rows=[...data.rows];for(const viewport of data.scenarios.viewports)rows.push(...await realm(data,viewport));render('CANDIDATE',rows)}catch(error){byId('fatal').textContent=error.stack||error.message;render('FATAL',[row('runner-fatal',false,error.stack||error.message)])}finally{byId('run').disabled=false}}
  byId('run').onclick=run;run();
})();
