import {createHash,webcrypto} from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
import {existsSync,readFileSync,readdirSync} from 'node:fs';
import vm from 'node:vm';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),QA=resolve(ROOT,'qa/phase-11b2c'),NODE=process.execPath;
const EXPECTED_NAMES=['README.md','build-contract.mjs','checksums.sha256','current-manifest.json','final-probe.mjs','index.html','realm.html','realm.js','runner.js','scenarios.json','verify.mjs'];
const SOURCE_FILES=EXPECTED_NAMES.filter(name=>!['checksums.sha256','current-manifest.json'].includes(name)).map(name=>`qa/phase-11b2c/${name}`);
const PHASE_11B2A=['qa/phase-11b2a/README.md','qa/phase-11b2a/idle-probe.mjs','qa/phase-11b2a/probe.mjs'];
const PHASE_11B2B=['qa/phase-11b2b/README.md','qa/phase-11b2b/engine-probe.mjs'];
const PHASE_11A=['README.md','build-contract.mjs','checksums.sha256','current-manifest.json','index.html','probe.mjs','realm.html','realm.js','runner.js','scenarios.json','verify.mjs'].map(name=>`qa/phase-11a/${name}`);
const PHASE_11B1=['README.md','build-contract.mjs','checksums.sha256','current-manifest.json','index.html','probe.mjs','realm.html','realm.js','runner.js','scenarios.json','verify.mjs'].map(name=>`qa/phase-11b1/${name}`);
const EXECUTABLE=['index.html',...PHASE_11B2A,...PHASE_11B2B,...SOURCE_FILES],RESULT_DOC='docs/PHASE_11B2_SAVE_RECOVERY_RESULT.md';
const results=[],record=(id,pass,detail='')=>results.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),sha=value=>createHash('sha256').update(value).digest('hex'),read=path=>readFileSync(resolve(ROOT,path)),identity=raw=>({sha256:sha(raw),byteLength:raw.length}),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const scenarios=JSON.parse(read('qa/phase-11b2c/scenarios.json')),source=read('index.html'),text=source.toString('utf8'),artifact=identity(source),expectedArtifact={sha256:scenarios.artifact.sha256,byteLength:scenarios.artifact.byteLength};
const git=(args,options={})=>execFileSync('git',args,{cwd:ROOT,encoding:'utf8',maxBuffer:64*1024*1024,...options});

record('production-commit-reachable',git(['merge-base','--is-ancestor',scenarios.authority.productionCommit,'HEAD'])==='');
record('production-last-index-change',git(['log','-1','--format=%H','--','index.html']).trim()===scenarios.authority.productionCommit);
record('exact-production-artifact',same(artifact,expectedArtifact),artifact);
const assets=[...text.matchAll(/data:image\/[^;]+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]),assetSha=sha(Buffer.from(assets.join('\n')));record('embedded-assets-byte-frozen',assets.length===scenarios.artifact.assetCount&&assetSha===scenarios.artifact.assetAggregateSha256,`${assets.length} · ${assetSha}`);
record('schema-and-fifteen-slot-boundary',text.includes('CURRENT_SCHEMA_VERSION=11')&&['PHASE_ELEVEN_B_TWO_JOURNAL_KEY','PHASE_ELEVEN_B_TWO_ROLLBACK_KEY','PHASE_ELEVEN_B_TWO_SNAPSHOT_KEYS'].every(marker=>text.includes(marker))&&Object.keys(scenarios.storageKeys).length===15&&new Set(Object.values(scenarios.storageKeys)).size===15);
record('package-topology',same(readdirSync(QA).sort(),EXPECTED_NAMES),readdirSync(QA).sort());
const changed=git(['diff','--name-only',scenarios.authority.productionCommit,'--']).trim().split('\n').filter(Boolean),owned=path=>path.startsWith('qa/phase-11b2c/')||path===RESULT_DOC;record('post-production-owned-paths-only',changed.length>0&&changed.every(owned),changed);

function frozenAt(commit,paths){const failures=[];for(const path of paths){try{const historical=execFileSync('git',['show',`${commit}:${path}`],{cwd:ROOT,maxBuffer:64*1024*1024});if(!historical.equals(read(path)))failures.push(path)}catch{failures.push(path)}}return failures}
record('phase11a-package-byte-frozen',frozenAt(scenarios.authority.phase11b1SealCommit,PHASE_11A).length===0,frozenAt(scenarios.authority.phase11b1SealCommit,PHASE_11A));
record('phase11b1-package-byte-frozen',frozenAt(scenarios.authority.phase11b1SealCommit,PHASE_11B1).length===0,frozenAt(scenarios.authority.phase11b1SealCommit,PHASE_11B1));
function checksumFailures(path){const failures=[];for(const line of read(path).toString('utf8').trim().split('\n')){const match=line.match(/^([0-9a-f]{64})  (.+)$/);if(!match||!existsSync(resolve(ROOT,match[2]))||sha(read(match[2]))!==match[1])failures.push(match?.[2]||line)}return failures.sort()}
const phase11aChecksumFailures=checksumFailures('qa/phase-11a/checksums.sha256'),phase11b1ChecksumFailures=checksumFailures('qa/phase-11b1/checksums.sha256');
record('phase11a-checksum-supersession-exact',same(phase11aChecksumFailures,['index.html']),phase11aChecksumFailures);
record('phase11b1-checksum-supersession-exact',same(phase11b1ChecksumFailures,['docs/PHASE_11B_SAVE_RECOVERY_CONTRACT.md','index.html']),phase11b1ChecksumFailures);

const phase11aProbe=spawnSync(NODE,['qa/phase-11a/probe.mjs'],{cwd:ROOT,encoding:'utf8',maxBuffer:64*1024*1024}),phase11aSemanticFailures=phase11aProbe.stdout.split('\n').filter(line=>line.startsWith('FAIL ')).map(line=>line.slice(5).split(' · ')[0]).sort();
record('phase11a-semantic-supersession-exact',phase11aProbe.status===1&&/Phase 11A probe: 166\/168/.test(phase11aProbe.stdout)&&same(phase11aSemanticFailures,['engine-idle-cursors-independent-from-gold','engine-probe-100-of-100'].sort()),phase11aSemanticFailures);
const phase11aVerify=spawnSync(NODE,['qa/phase-11a/verify.mjs'],{cwd:ROOT,encoding:'utf8',maxBuffer:64*1024*1024});let phase11aGate=null;try{phase11aGate=JSON.parse(phase11aVerify.stdout)}catch{}const phase11aVerifierFailures=phase11aGate?.results?.filter(row=>!row.pass).map(row=>row.id).sort()||[],expectedPhase11aVerifierFailures=['candidate-last-production-commit','exact-candidate-artifact','historical-qa-byte-frozen','additive-owned-paths-only','focused-engine-idle-cursors-independent-from-gold','focused-engine-probe-100-of-100','focused-probe-168-of-168','phase11a-checksums'].sort();record('phase11a-verifier-supersession-exact',phase11aVerify.status===1&&phase11aGate?.passed===172&&phase11aGate?.failed===8&&same(phase11aVerifierFailures,expectedPhase11aVerifierFailures),phase11aVerifierFailures);

async function phase11b1Successor(){
  const checks=[],check=(id,pass)=>checks.push({id,pass:Boolean(pass)}),marker='/* Phase 11B-1 · read-only save health, recovery bundle download, and migration history. */',next='/* Phase 11B-2a · strict recovery bundle inspection and canonical installation validation. */',candidate=git(['show','ccf7fed6ccb84b15388900fbb79f01b4b13b0162:index.html']),candidateMarker=candidate.indexOf(marker),candidateBoot=candidate.lastIndexOf('const report=load();render();installQaBridge();if(report)runtimeSetTimeout(()=>openOffline(report),250);'),markerIndex=text.indexOf(marker),nextIndex=text.indexOf(next),block=markerIndex>=0&&nextIndex>markerIndex?text.slice(markerIndex,nextIndex):'',candidateBlock=candidateMarker>=0&&candidateBoot>candidateMarker?candidate.slice(candidateMarker,candidateBoot):'';
  check('authority',git(['merge-base','--is-ancestor','f36a84eca29820dfc1a29efbe93309bef6e9f762','HEAD'])==='');check('single-marker',markerIndex>=0&&markerIndex===text.lastIndexOf(marker)&&nextIndex>markerIndex);check('block-byte-frozen',block===candidateBlock);check('read-only',Boolean(block)&&!/(?:storageSet|storageRemove|commitPrepared|mutatePersisted|setItem\(|removeItem\()/.test(block));check('constants',block.includes("PHASE_ELEVEN_B_BUNDLE_FORMAT='everstead-recovery-bundle'")&&block.includes('PHASE_ELEVEN_B_BUNDLE_VERSION=1')&&block.includes('PHASE_ELEVEN_B_MAX_FILE_BYTES=33554432'));const slotKeys=['active','rawBackup','preV2','preV3','preV4','preV5','preV6','preV7','preV8','preV9','preV10','preV11'];check('slot-order',block.includes(`Object.freeze(['${slotKeys.join("','")}'])`));check('health-lineage',block.includes('phaseTenCReadProtectedSlots()')&&block.includes('phaseTenCCurrentLineage(active.value,slots)'));check('privacy-copy',block.includes('Recovery files contain your Oaths, private memos, links, and full progress.')&&!block.includes('<textarea'));const predecessor=git(['show','7c9e370f37830eaf9f756972dbbc1744d68e0270:index.html']),predecessorAssets=[...predecessor.matchAll(/data:image\/[^;]+;base64,[A-Za-z0-9+/=]+/g)].map(match=>match[0]);check('assets',same(assets,predecessorAssets));
  const coreEnd=block.indexOf('function phaseElevenBDateStamp'),core=coreEnd>0?block.slice(0,coreEnd):'',activeRaw=JSON.stringify({schemaVersion:11,saveMeta:{saveId:'probe',revision:7}}),slotFixture={activeRaw,backupRaw:'raw-backup',preV2Raw:'pre-v2',preV3Raw:null,preV4Raw:'pre-v4',preV5Raw:null,preV6Raw:'pre-v6',preV7Raw:null,preV8Raw:'pre-v8',preV9Raw:null,preV10Raw:'pre-v10',preV11Raw:'pre-v11',stagingRaw:null},context={crypto:webcrypto,TextEncoder,VERSION:'Phase 11B-1 successor',runtimeNow:()=>1907953200000,phaseTenCReadProtectedSlots:()=>slotFixture,classifyRaw:raw=>raw===activeRaw?{kind:'current',schemaVersion:11,value:JSON.parse(raw)}:{kind:'invalid'},phaseTenCCurrentLineage:()=>{context.lineageCalls++},lineageCalls:0,PersistenceError:class PersistenceError extends Error{constructor(code,message){super(message);this.code=code}}};vm.createContext(context);vm.runInContext(`${core}\nglobalThis.__probe=async()=>{const health=phaseElevenBReadHealth(),bundle=await phaseElevenBRecoveryBundle(1907953200000);let bad=null;try{await phaseElevenBRecoveryBundle(-1)}catch(error){bad={code:error.code}}return{health,bundle,bad}}`,context);const pure=await context.__probe(),expectedSlots={active:slotFixture.activeRaw,rawBackup:slotFixture.backupRaw,preV2:slotFixture.preV2Raw,preV3:slotFixture.preV3Raw,preV4:slotFixture.preV4Raw,preV5:slotFixture.preV5Raw,preV6:slotFixture.preV6Raw,preV7:slotFixture.preV7Raw,preV8:slotFixture.preV8Raw,preV9:slotFixture.preV9Raw,preV10:slotFixture.preV10Raw,preV11:slotFixture.preV11Raw},{integrity,...payload}=pure.bundle;check('topology',same(Object.keys(pure.bundle),['product','format','formatVersion','exportedAt','appVersion','slots','integrity'])&&same(Object.keys(pure.bundle.slots),slotKeys));check('slots',same(pure.bundle.slots,expectedSlots)&&!Object.hasOwn(pure.bundle.slots,'staging'));check('digest',integrity.algorithm==='SHA-256'&&integrity.digest===sha(JSON.stringify(payload)));check('metadata',pure.bundle.product==='Everstead'&&pure.bundle.formatVersion===1&&pure.bundle.appVersion==='Phase 11B-1 successor');check('health-count',pure.health.ok&&pure.health.present===7&&pure.health.total===11&&context.lineageCalls===2);check('invalid-time',pure.bad?.code==='bundle-time');slotFixture.stagingRaw='occupied';check('occupied-staging',vm.runInContext('phaseElevenBReadHealth()',context).ok===false);slotFixture.stagingRaw=null;
  const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),lineContaining=needle=>text.split('\n').find(line=>line.includes(needle))||'',historyContext={S:{saveMeta:{appliedMigrations:[{id:'<img data-x>',from:4,to:5,appliedAt:1907953200000,migrationSource:'<svg data-y>'}],retainedCheckpointLineage:null}},PHASE_ELEVEN_B_MIGRATION_LABELS:Object.freeze({}),esc:escape,runtimeDate:value=>new Date(value)};vm.createContext(historyContext);vm.runInContext(`${lineContaining('function phaseElevenBMigrationHistoryHtml')}\nglobalThis.__html=phaseElevenBMigrationHistoryHtml()`,historyContext);check('history-escape',historyContext.__html.includes('&lt;img')&&historyContext.__html.includes('&lt;svg')&&!historyContext.__html.includes('<img'));const healthContext={phaseElevenBReadHealth:()=>({ok:true,active:{saveMeta:{revision:9,updatedAt:1907953200000,source:'<svg data-y>',saveId:'<img data-x>'}},slots:{activeRaw:'active'}}),esc:escape,runtimeDate:value=>new Date(value),rawIdentity:()=>'<b data-z>'};vm.createContext(healthContext);vm.runInContext(`${lineContaining('function phaseElevenBSaveHealthHtml')}\nglobalThis.__html=phaseElevenBSaveHealthHtml()`,healthContext);check('health-escape',healthContext.__html.includes('&lt;svg')&&healthContext.__html.includes('&lt;img')&&healthContext.__html.includes('&lt;b')&&!healthContext.__html.includes('<svg'));check('normal-bundle-size',Buffer.byteLength(JSON.stringify(pure.bundle))<33554432);return checks}
const phase11b1Checks=await phase11b1Successor();record('phase11b1-readonly-semantic-successor',phase11b1Checks.length===19&&phase11b1Checks.every(item=>item.pass),phase11b1Checks.filter(item=>!item.pass));

function focused(path,label,total){const run=spawnSync(NODE,[path],{cwd:ROOT,encoding:'utf8',maxBuffer:128*1024*1024}),pattern=new RegExp(`${label}: ${total}\\/${total}`);return{pass:run.status===0&&pattern.test(run.stdout),status:run.status,tail:run.stdout.trim().split('\n').slice(-1)[0],stderr:run.stderr.trim().slice(-500)}}
const inspect=focused('qa/phase-11b2a/probe.mjs','Phase 11B-2a probe',42),idle=focused('qa/phase-11b2a/idle-probe.mjs','Phase 11B idle prerequisite probe',8),engine=focused('qa/phase-11b2b/engine-probe.mjs','Phase 11B-2b engine probe',103),final=focused('qa/phase-11b2c/final-probe.mjs','Phase 11B-2c final recovery probe',133);record('focused-inspection-42-of-42',inspect.pass,inspect);record('focused-idle-8-of-8',idle.pass,idle);record('focused-engine-103-of-103',engine.pass,engine);record('focused-final-133-of-133',final.pass,final);record('focused-total-286-of-286',[inspect,idle,engine,final].every(item=>item.pass));
for(const file of ['build-contract.mjs','final-probe.mjs','realm.js','runner.js']){try{execFileSync(NODE,['--check',`qa/phase-11b2c/${file}`],{cwd:ROOT,encoding:'utf8'});record(`syntax-${file}`,true)}catch(error){record(`syntax-${file}`,false,error.stderr||error.message)}}

const manifest=JSON.parse(read('qa/phase-11b2c/current-manifest.json'));record('manifest-authority',manifest.phase==='11B-2'&&manifest.status==='PASS_LOCAL'&&manifest.productionCommit===scenarios.authority.productionCommit&&git(['merge-base','--is-ancestor',manifest.packageCommit,'HEAD'])===''&&same(manifest.artifact,expectedArtifact)&&manifest.schemaVersion===11&&manifest.runtimeSlots.total===15&&manifest.focusedRows.total===286&&manifest.sealedCliRows===29&&manifest.liveRows===198&&manifest.observedGate?.sealedCli?.passed===29&&manifest.observedGate?.sealedCli?.failed===0&&manifest.observedGate?.sealedCli?.runs===2&&manifest.observedGate?.liveBrowser?.passed===198&&manifest.observedGate?.liveBrowser?.failed===0&&manifest.observedGate?.liveBrowser?.runs===2&&manifest.reviews?.length===2&&manifest.reviews.every(review=>review.status==='PASS'&&review.artifactSha256===artifact.sha256),manifest);
const packageFailures=Object.entries(manifest.packageFiles).filter(([path,entry])=>!same(identity(read(path)),entry)).map(([path])=>path);record('manifest-package-identities',Object.keys(manifest.packageFiles).length===SOURCE_FILES.length&&packageFailures.length===0,packageFailures);
const executableFailures=Object.entries(manifest.executableFiles).filter(([path,entry])=>!same(identity(read(path)),entry)).map(([path])=>path);record('manifest-executable-identities',Object.keys(manifest.executableFiles).length===EXECUTABLE.length&&executableFailures.length===0,executableFailures);
const checksumRows=read('qa/phase-11b2c/checksums.sha256').toString('utf8').trim().split('\n'),checksumFinalFailures=checksumRows.filter(line=>{const match=line.match(/^([0-9a-f]{64})  (.+)$/);return!match||!existsSync(resolve(ROOT,match[2]))||sha(read(match[2]))!==match[1]});record('phase11b2-checksums-42-of-42',checksumRows.length===42&&checksumFinalFailures.length===0,checksumFinalFailures);
try{const output=execFileSync(NODE,['qa/phase-11b2c/build-contract.mjs'],{cwd:ROOT,encoding:'utf8'}),built=JSON.parse(output);record('builder-read-only',built.writes===0&&built.artifact.sha256===artifact.sha256&&built.executableFiles===15&&built.checksumEntries===42,built)}catch(error){record('builder-read-only',false,error.stderr||error.message)}
record('clean-worktree',git(['status','--porcelain']).trim()==='',git(['status','--porcelain']).trim());

const passed=results.filter(row=>row.pass).length,failed=results.length-passed;console.log(JSON.stringify({phase:'11B-2',status:failed?'FAIL':'PASS',productionCommit:scenarios.authority.productionCommit,packageCommit:manifest.packageCommit,artifact:expectedArtifact,focused:{total:286,inspection:42,idle:8,engine:103,final:133},total:results.length,passed,failed,results},null,2));if(failed)process.exitCode=1;
