import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'../..');
const contract=JSON.parse(fs.readFileSync(path.join(here,'contract.json'),'utf8'));
const S=contract.selectors;
const rows=[];
const record=(id,pass,detail='')=>rows.push({id,pass:Boolean(pass),detail:typeof detail==='string'?detail:JSON.stringify(detail)});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.jpeg':'image/jpeg','.woff2':'font/woff2'};

function server(){
  return http.createServer((request,response)=>{
    const url=new URL(request.url,'http://127.0.0.1');
    if(url.pathname==='/__phase24l_b3a_host__.html'){
      response.writeHead(200,{'content-type':mime['.html'],'cache-control':'no-store'}).end('<!doctype html><html style="width:100%;height:100%"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phase 24L-B3A QA host</title><style>html,body{width:100%;height:100%;margin:0;overflow:hidden}#realm{display:block;width:100%;height:100%;border:0}</style></head><body><iframe id="realm" title="Everstead Phase 24L-B3A QA realm" src="/index.html"></iframe></body></html>');
      return;
    }
    const relative=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname).replace(/^\/+/,''),target=path.resolve(root,relative);
    if(target!==root&&!target.startsWith(root+path.sep)){response.writeHead(403).end();return}
    fs.readFile(target,(error,data)=>{if(error){response.writeHead(404).end();return}response.writeHead(200,{'content-type':mime[path.extname(target)]||'application/octet-stream','cache-control':'no-store'}).end(data)});
  });
}
async function listen(instance){await new Promise((resolve,reject)=>{instance.once('error',reject);instance.listen(0,'127.0.0.1',resolve)});return`http://127.0.0.1:${instance.address().port}`}

async function installMemoryRuntime(context){
  await context.addInitScript(()=>{
    if(window===window.top){Object.defineProperty(window,'__P24LB3A_SHARED__',{configurable:false,enumerable:false,writable:false,value:{slots:new Map(),writes:[],reads:[],removes:[],native:[],clients:new Set(),clientIndex:0,saveIndex:0,transactionIndex:0,now:1810000000000}});return}
    const shared=window.top.__P24LB3A_SHARED__,clientId=`phase24l-b3a-client-${++shared.clientIndex}`;shared.clients.add(window);
    const nativeGet=Storage.prototype.getItem,nativeSet=Storage.prototype.setItem,nativeRemove=Storage.prototype.removeItem;
    Storage.prototype.getItem=function(...args){shared.native.push(['getItem',String(args[0])]);return nativeGet.apply(this,args)};
    Storage.prototype.setItem=function(...args){shared.native.push(['setItem',String(args[0])]);return nativeSet.apply(this,args)};
    Storage.prototype.removeItem=function(...args){shared.native.push(['removeItem',String(args[0])]);return nativeRemove.apply(this,args)};
    const notify=(key,oldValue,newValue)=>{for(const peer of shared.clients){if(peer===window||peer.closed)continue;setTimeout(()=>{try{peer.dispatchEvent(new peer.StorageEvent('storage',{key,oldValue,newValue,url:peer.location.href,storageArea:peer.localStorage}))}catch{}},0)}};
    const memory=Object.freeze({
      getItem(key){key=String(key);shared.reads.push([key,clientId]);return shared.slots.get(key)??null},
      setItem(key,value){key=String(key);value=String(value);const oldValue=shared.slots.get(key)??null;shared.writes.push([key,value,clientId]);shared.slots.set(key,value);notify(key,oldValue,value)},
      removeItem(key){key=String(key);const oldValue=shared.slots.get(key)??null;shared.removes.push([key,clientId]);shared.slots.delete(key);notify(key,oldValue,null)}
    });
    const nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);
    window.__EVERSTEAD_RUNTIME__={storage:memory,clock:{now:()=>shared.now,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.4375,confirm:()=>true,ids:{save:()=>`save-phase24l-b3a-${++shared.saveIndex}`,transaction:()=>`tx-phase24l-b3a-${++shared.transactionIndex}`}};
  });
}
async function realm(page){
  const handle=await page.waitForSelector('#realm'),frame=await handle.contentFrame();
  await frame.waitForLoadState('domcontentloaded',{timeout:120000});
  await frame.waitForFunction(({runtime,result})=>Boolean(window[runtime])&&Boolean(window[result]),{runtime:contract.candidate.global,result:contract.candidate.resultGlobal},{timeout:60000});
  return frame;
}
async function shared(page){return page.evaluate(key=>{const value=window.__P24LB3A_SHARED__,raw=value.slots.get(key)??null;let revision=null;try{revision=raw?JSON.parse(raw).saveMeta?.revision??null:null}catch{}return{raw,revision,writes:value.writes.length,reads:value.reads.length,removes:value.removes.length,native:value.native.slice()}},contract.storageKey)}
const neutral=(before,after)=>before.raw===after.raw&&before.revision===after.revision&&before.writes===after.writes;
const shown=node=>node&&!node.hidden;
async function dismissBlockingOverlays(frame){
  for(let count=0;count<50;count++){
    const status=await frame.evaluate(()=>{const visible=node=>{if(!node)return false;const rect=node.getBoundingClientRect(),style=getComputedStyle(node);return!node.hidden&&rect.width>0&&rect.height>0&&style.display!=='none'&&style.visibility!=='hidden'};const overlay=[...document.querySelectorAll('[data-overlay]')].filter(visible).at(-1);if(!overlay)return'done';const close=[...overlay.querySelectorAll('[data-modal-close],[data-phase13-story="skip"],[data-phase13-tutorial-action="skip"],[data-phase15-tutorial-action="skip"],[data-phase16-tutorial-action="skip"]')].find(visible);if(close){close.click();return'clicked'}document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));return'escaped'});
    if(status==='done')return true;await frame.waitForTimeout(70);
  }
  return false;
}
async function visibleCount(frame,selector){return frame.evaluate(selector=>[...document.querySelectorAll(selector)].filter(node=>{const rect=node.getBoundingClientRect(),style=getComputedStyle(node);return!node.hidden&&rect.width>0&&rect.height>0&&style.display!=='none'&&style.visibility!=='hidden'}).length,selector)}
async function pressEscape(frame){await frame.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true})));await frame.waitForTimeout(40)}
async function navigate(frame,view){await frame.locator(`.bottom-nav [data-nav="${view}"]`).click();await frame.waitForSelector(`${S.screen}[data-phase24l-compact-screen="${view}"]`);await frame.waitForTimeout(50)}

async function closeGuide(frame,screenSelector,speaker){
  const evidence=await frame.evaluate(({screenSelector,guide,close,speaker})=>{const screen=document.querySelector(screenSelector),node=[...screen?.querySelectorAll(guide)||[]].find(item=>{const rect=item.getBoundingClientRect(),style=getComputedStyle(item);return!item.hidden&&rect.width>0&&rect.height>0&&style.display!=='none'}),button=node?.querySelector(close),rect=button?.getBoundingClientRect(),text=(node?.textContent||'').replaceAll('’',"'");return{count:node?1:0,speaker:text.includes(speaker.replaceAll('’',"'")),touch:Boolean(rect&&rect.width>=44&&rect.height>=44)}} ,{screenSelector,guide:S.guide,close:S.guideClose,speaker});
  if(evidence.count)await frame.locator(`${screenSelector} ${S.guide}:not([hidden]) ${S.guideClose}`).click();
  await frame.waitForTimeout(40);return{...evidence,closed:await visibleCount(frame,`${screenSelector} ${S.guide}`)===0};
}
async function documentEvidence(frame,screenSelector){
  await frame.evaluate(()=>scrollTo(1000,1000));await frame.waitForTimeout(20);
  return frame.evaluate(screenSelector=>{const rect=node=>node?(()=>{const value=node.getBoundingClientRect();return{top:value.top,bottom:value.bottom,left:value.left,right:value.right,width:value.width,height:value.height}})():null,html=document.documentElement,body=document.body,app=document.querySelector('#app'),screen=document.querySelector(screenSelector),top=document.querySelector('.topbar'),bottom=document.querySelector('.bottom-nav');return{scroll:{x:scrollX,y:scrollY,height:html.scrollHeight,viewport:innerHeight,width:html.scrollWidth,viewportWidth:innerWidth},classed:html.classList.contains('phase24l-b3a-active'),screen:rect(screen),top:rect(top),bottom:rect(bottom),overflow:{html:getComputedStyle(html).overflowY,body:getComputedStyle(body).overflowY,app:getComputedStyle(app).overflowY}}},screenSelector);
}
function documentLocked(value){return value.classed&&value.scroll.x===0&&value.scroll.y===0&&value.scroll.height===value.scroll.viewport&&value.scroll.width<=value.scroll.viewportWidth+contract.limits.fitTolerancePx&&value.overflow.html==='hidden'&&value.overflow.body==='hidden'&&value.top?.top>=-2&&value.bottom?.bottom<=value.scroll.viewport+2&&value.screen?.top>=-2&&value.screen?.bottom<=value.scroll.viewport+2}
async function panelState(frame,screenSelector){return frame.evaluate(({screenSelector,panel,tab,guide})=>{const screen=document.querySelector(screenSelector),visible=node=>{if(!node)return false;const rect=node.getBoundingClientRect(),style=getComputedStyle(node);return!node.hidden&&rect.width>0&&rect.height>0&&style.display!=='none'&&style.visibility!=='hidden'},panels=[...screen?.querySelectorAll(panel)||[]].map(node=>({id:node.dataset.phase24lCompactPanel,visible:visible(node),rect:(()=>{const r=node.getBoundingClientRect();return{top:r.top,bottom:r.bottom,width:r.width,height:r.height}})()})),tabs=[...screen?.querySelectorAll(tab)||[]].map(node=>{const r=node.getBoundingClientRect();return{id:node.dataset.phase24lCompactTab,selected:node.getAttribute('aria-selected'),expanded:node.getAttribute('aria-expanded'),width:r.width,height:r.height,controls:node.getAttribute('aria-controls')}}),guides=[...screen?.querySelectorAll(guide)||[]].filter(visible).length;return{active:screen?.dataset.phase24lCompactPanel,sheetOpen:screen?.dataset.phase24lCompactSheetOpen,panels,tabs,visible:panels.filter(item=>item.visible).map(item=>item.id),guides,viewport:innerHeight}}, {screenSelector,panel:S.panel,tab:S.tab,guide:S.guide})}
function matchesState(value,active){return value.active===(active||'closed')&&value.sheetOpen===String(Boolean(active))&&value.guides===0&&value.visible.length===(active?1:0)&&(!active||value.visible[0]===active)&&value.tabs.every(tab=>tab.selected===String(tab.id===active)&&tab.expanded===String(tab.id===active))}
async function activate(frame,screenSelector,id){const button=frame.locator(`${screenSelector} ${S.tab}[data-phase24l-compact-tab="${id}"]`);await button.click();await frame.waitForTimeout(40);return panelState(frame,screenSelector)}
async function ensureActive(frame,screenSelector,id){const current=await panelState(frame,screenSelector);return matchesState(current,id)?current:activate(frame,screenSelector,id)}
function boundedPanel(state,active){const panel=state.panels.find(item=>item.id===active),tab=state.tabs.find(item=>item.id===active);return matchesState(state,active)&&Boolean(panel&&tab&&panel.rect.top>=-2&&panel.rect.bottom<=state.viewport+2&&panel.rect.height<=state.viewport*contract.limits.maximumPanelViewportRatio+2&&tab.width>=44&&tab.height>=44)}
async function modalJourney(frame,trigger,expected){
  const node=frame.locator(trigger).first();if(await node.count()!==1)return{present:false};
  await node.click();await frame.waitForTimeout(60);const evidence=await frame.evaluate(expected=>{const overlays=[...document.querySelectorAll('[data-overlay]')],visible=overlays.filter(node=>{const r=node.getBoundingClientRect(),s=getComputedStyle(node);return!node.hidden&&r.width>0&&r.height>0&&s.display!=='none'}),text=(visible.at(-1)?.textContent||'').replace(/\s+/g,' ').trim();return{visible:visible.length,text,matched:text.includes(expected)}},expected);
  if(evidence.visible)await frame.locator('[data-overlay]:not([hidden]) [data-modal-close]').first().click();await frame.waitForTimeout(40);return evidence;
}

async function oathJourney(page,frame,step){
  const before=await shared(page);await navigate(frame,'oaths');
  const guide=await closeGuide(frame,S.oaths,contract.oaths.guideSpeaker);step('oaths-first-visit-shows-session-tavi-guide',guide.count===1&&guide.speaker&&guide.touch&&guide.closed,guide);
  const doc=await documentEvidence(frame,S.oaths);step('oaths-locks-exact-document-viewport-and-keeps-global-rails',documentLocked(doc),doc);
  const structure=await frame.evaluate(({root,stage,dock,tab,panel,tabs})=>{const screen=document.querySelector(root),buttons=[...screen?.querySelectorAll(`${dock} ${tab}`)||[]],panels=[...screen?.querySelectorAll(panel)||[]],stageNode=screen?.querySelector(stage),globalNav=document.querySelector('.bottom-nav')?.getBoundingClientRect(),local=screen?.querySelector(dock)?.getBoundingClientRect(),mapping=panels.map(node=>({id:node.dataset.phase24lCompactPanel,heading:(node.querySelector('h2')?.textContent||'').trim()}));return{tabs:buttons.map(node=>node.dataset.phase24lCompactTab),panelIds:panels.map(node=>node.dataset.phase24lCompactPanel),mapping,stage:Boolean(stageNode),dockAboveGlobal:Boolean(local&&globalNav&&local.bottom<=globalNav.top+2),controls:{add:Boolean(stageNode?.querySelector('[data-act="add-oath"]')),oaths:screen?.querySelectorAll(`${panel} [data-oath]`).length||0,edits:screen?.querySelectorAll(`${panel} [data-edit-oath]`).length||0,hide:Boolean(screen?.querySelector(`${panel}[data-phase24l-compact-panel="manage"] [data-act="hide-done"]`))},handlers:{add:typeof screen?.querySelector('[data-act="add-oath"]')?.onclick,check:typeof screen?.querySelector('[data-oath]')?.onclick,edit:typeof screen?.querySelector('[data-edit-oath]')?.onclick,hide:typeof screen?.querySelector('[data-act="hide-done"]')?.onclick},strays:[...screen?.children||[]].filter(node=>node.matches?.('.oath-section,.settings-row')).length}}, {root:S.oaths,stage:S.stage,dock:S.dock,tab:S.tab,panel:S.panel,tabs:contract.oaths.tabs});
  const expected=contract.oaths.tabs.map(item=>item.id),headings=Object.fromEntries(contract.oaths.tabs.map(item=>[item.id,item.source]));step('oaths-has-exact-five-mapped-tabs-and-reparented-real-controls',structure.tabs.join(',')===expected.join(',')&&structure.panelIds.join(',')===expected.join(',')&&structure.mapping.every(item=>item.heading===headings[item.id])&&structure.stage&&structure.dockAboveGlobal&&structure.controls.add&&structure.controls.oaths>0&&structure.controls.oaths===structure.controls.edits&&structure.controls.hide&&Object.values(structure.handlers).every(value=>value==='function')&&structure.strays===0,structure);
  const panelRows=[];for(const id of expected){const state=await ensureActive(frame,S.oaths,id);panelRows.push({id,ok:boundedPanel(state,id),state})}step('oath-tabs-open-one-bounded-exclusive-sheet',panelRows.every(row=>row.ok),panelRows);
  const collapsed=await activate(frame,S.oaths,'manage');step('oath-selected-tab-second-activation-collapses-sheet',matchesState(collapsed,null),collapsed);
  await ensureActive(frame,S.oaths,'work');await pressEscape(frame);const escaped=await panelState(frame,S.oaths);step('escape-collapses-oath-sheet-before-navigation',matchesState(escaped,null),escaped);
  const modalBefore=await shared(page),newModal=await modalJourney(frame,`${S.oaths} [data-act="add-oath"]`,'New Oath');await ensureActive(frame,S.oaths,'prepare');const editModal=await modalJourney(frame,`${S.oaths} [data-edit-oath]`,'Edit Oath'),modalAfter=await shared(page);step('new-and-edit-oath-bindings-remain-live-and-save-neutral-before-submit',newModal.matched&&editModal.matched&&neutral(modalBefore,modalAfter),{newModal,editModal,before:modalBefore,after:modalAfter});
  const guideBefore=await shared(page);await frame.locator(`${S.oaths} ${S.guideOpen}`).click();const replay=await closeGuide(frame,S.oaths,contract.oaths.guideSpeaker),guideAfter=await shared(page);step('oath-guide-is-replayable-and-save-neutral',replay.count===1&&replay.speaker&&neutral(guideBefore,guideAfter),{replay,before:guideBefore,after:guideAfter});
  const afterPresentation=await shared(page);step('all-oath-presentation-actions-are-byte-revision-write-neutral',neutral(before,afterPresentation),{before,after:afterPresentation});
  await ensureActive(frame,S.oaths,'prepare');const actionBefore=await shared(page),check=frame.locator(`${S.oaths} [data-oath]:not([disabled])`).first(),actionId=await check.getAttribute('data-oath'),beforeOath=JSON.parse(actionBefore.raw).oaths.find(item=>item.id===actionId);await check.click();await frame.waitForTimeout(180);const actionAfter=await shared(page),afterOath=JSON.parse(actionAfter.raw).oaths.find(item=>item.id===actionId),oathChanged=JSON.stringify(beforeOath)!==JSON.stringify(afterOath);step('real-oath-completion-commits-through-existing-authority-after-reparenting',Boolean(actionId)&&oathChanged&&actionAfter.raw!==actionBefore.raw&&Number.isSafeInteger(actionAfter.revision)&&actionAfter.revision>actionBefore.revision&&actionAfter.writes>actionBefore.writes,{actionId,before:{revision:actionBefore.revision,writes:actionBefore.writes,oath:beforeOath},after:{revision:actionAfter.revision,writes:actionAfter.writes,oath:afterOath}});await dismissBlockingOverlays(frame);
}

async function moreJourney(page,frame,step){
  await navigate(frame,'more');const before=await shared(page);const guide=await closeGuide(frame,S.more,contract.more.guideSpeaker);step('more-first-visit-shows-session-shallan-guide',guide.count===1&&guide.speaker&&guide.touch&&guide.closed,guide);
  const doc=await documentEvidence(frame,S.more);step('more-locks-exact-document-viewport-and-keeps-global-rails',documentLocked(doc),doc);
  const structure=await frame.evaluate(({root,stage,dock,tab,panel,required,tabs})=>{const screen=document.querySelector(root),buttons=[...screen?.querySelectorAll(`${dock} ${tab}`)||[]],panels=[...screen?.querySelectorAll(panel)||[]],globalNav=document.querySelector('.bottom-nav')?.getBoundingClientRect(),local=screen?.querySelector(dock)?.getBoundingClientRect(),ownership=Object.fromEntries(required.map(selector=>{const node=screen?.querySelector(selector);return[selector,{present:Boolean(node),insidePanel:Boolean(node?.closest(panel)),panel:node?.closest(panel)?.dataset.phase24lCompactPanel||null,handler:typeof(node?.matches('[data-setting]')?node.onchange:node?.querySelector?.('button')?.onclick??node?.onclick)}]})),phase17=document.querySelector('[data-phase17-reference]');return{tabs:buttons.map(node=>node.dataset.phase24lCompactTab),panels:panels.map(node=>node.dataset.phase24lCompactPanel),stage:Boolean(screen?.querySelector(stage)),dockAboveGlobal:Boolean(local&&globalNav&&local.bottom<=globalNav.top+2),ownership,phase17:{present:Boolean(phase17),insideCodex:Boolean(phase17?.closest(`${panel}[data-phase24l-compact-panel="codex"]`))},strays:[...screen?.children||[]].filter(node=>!node.matches('.page-head,[data-phase24l-b3a-stage],[data-phase24l-compact-dock],[data-phase24l-compact-panel],[data-phase24l-b3a-guide]')).map(node=>node.outerHTML.slice(0,100))}}, {root:S.more,stage:S.stage,dock:S.dock,tab:S.tab,panel:S.panel,required:contract.more.requiredMovedSelectors,tabs:contract.more.tabs});
  step('more-has-exact-five-tabs-and-accounts-for-every-top-level-card',structure.tabs.join(',')===contract.more.tabs.join(',')&&structure.panels.join(',')===contract.more.tabs.join(',')&&structure.stage&&structure.dockAboveGlobal&&Object.values(structure.ownership).every(item=>item.present&&item.insidePanel)&&(!structure.phase17.present||structure.phase17.insideCodex)&&structure.strays.length===0,structure);
  const panelRows=[];for(const id of contract.more.tabs){const state=await ensureActive(frame,S.more,id);panelRows.push({id,ok:boundedPanel(state,id),state})}step('more-tabs-open-one-bounded-exclusive-sheet',panelRows.every(row=>row.ok),panelRows);
  const collapsed=await activate(frame,S.more,'save');step('more-selected-tab-second-activation-collapses-sheet',matchesState(collapsed,null),collapsed);
  await ensureActive(frame,S.more,'journey');await pressEscape(frame);const escaped=await panelState(frame,S.more);step('escape-collapses-more-sheet-before-navigation',matchesState(escaped,null),escaped);
  const liveBefore=await shared(page);await ensureActive(frame,S.more,'journey');const wayfarer=await modalJourney(frame,`${S.more} [data-player-profile]`,'The Wayfarer');await ensureActive(frame,S.more,'codex');const codex=await modalJourney(frame,`${S.more} [data-phase-11d-codex-open]`,'Everstead Codex');await ensureActive(frame,S.more,'save');const handlers=await frame.evaluate(root=>{const screen=document.querySelector(root),setting=screen?.querySelector('[data-setting]'),exportButton=screen?.querySelector('[data-act="export"]'),recovery=screen?.querySelector('[data-save-recovery-action="choose"]');return{setting:typeof setting?.onchange,export:typeof exportButton?.onclick,recovery:recovery?typeof recovery.onclick:'absent'}},S.more);const liveAfter=await shared(page);step('wayfarer-codex-preference-export-recovery-bindings-remain-live-and-save-neutral',wayfarer.matched&&codex.matched&&handlers.setting==='function'&&handlers.export==='function'&&['function','absent'].includes(handlers.recovery)&&neutral(liveBefore,liveAfter),{wayfarer,codex,handlers,before:liveBefore,after:liveAfter});
  const guideBefore=await shared(page);await frame.locator(`${S.more} ${S.guideOpen}`).click();const replay=await closeGuide(frame,S.more,contract.more.guideSpeaker),guideAfter=await shared(page);step('more-guide-is-replayable-and-save-neutral',replay.count===1&&replay.speaker&&neutral(guideBefore,guideAfter),{replay,before:guideBefore,after:guideAfter});
  const after=await shared(page);step('all-more-presentation-actions-are-byte-revision-write-neutral',neutral(before,after),{before,after});
  await frame.locator('.bottom-nav [data-nav="village"]').click();await frame.waitForFunction(()=>document.querySelector('.bottom-nav [data-nav="village"]')?.classList.contains('on')&&!document.querySelector('[data-phase24l-compact-screen]'));await frame.waitForTimeout(40);const exit=await frame.evaluate(()=>({compact:document.querySelectorAll('[data-phase24l-compact-screen]').length,active:document.documentElement.classList.contains('phase24l-b3a-active')}));step('global-navigation-exits-compact-hub-and-clears-root-state',exit.compact===0&&!exit.active,exit);
  await navigate(frame,'oaths');const returnGuide=await visibleCount(frame,`${S.oaths} ${S.guide}`);step('oath-guide-does-not-auto-reopen-on-second-session-visit',returnGuide===0,returnGuide);
}

function watchPage(page){const errors=[],requests=[];page.setDefaultTimeout(30000);page.on('pageerror',error=>errors.push(`pageerror:${error.stack||error.message}`));page.on('console',message=>{if(['warning','error'].includes(message.type()))errors.push(`console.${message.type()}:${message.text()}`)});page.on('response',response=>{if(response.status()>=400)requests.push(`${response.status()}:${response.url()}`)});page.on('requestfailed',request=>requests.push(`${request.url()}:${request.failure()?.errorText||'failed'}`));return{errors,requests}}

async function viewportJourney(browser,baseURL,viewport){
  const step=(id,pass,detail='')=>record(`${viewport.id}-${id}`,pass,detail);let context,page,frame;
  try{
    context=await browser.newContext({viewport:{width:viewport.width,height:viewport.height},reducedMotion:'reduce'});await installMemoryRuntime(context);page=await context.newPage();const watch=watchPage(page);const response=await page.goto(`${baseURL}/__phase24l_b3a_host__.html`,{waitUntil:'domcontentloaded',timeout:120000});frame=await realm(page);await dismissBlockingOverlays(frame);
    const install=await frame.evaluate(({runtime,result,id})=>{const api=window[runtime],outcome=window[result],apiDescriptor=Object.getOwnPropertyDescriptor(window,runtime),resultDescriptor=Object.getOwnPropertyDescriptor(window,result);return{api:{version:api?.version,id:api?.id,frozen:Object.isFrozen(api)},outcome,descriptors:{api:apiDescriptor&&{enumerable:apiDescriptor.enumerable,writable:apiDescriptor.writable,configurable:apiDescriptor.configurable},result:resultDescriptor&&{enumerable:resultDescriptor.enumerable,writable:resultDescriptor.writable,configurable:resultDescriptor.configurable}},id}}, {runtime:contract.candidate.global,result:contract.candidate.resultGlobal,id:contract.candidate.id});
    step('runtime-and-install-result-are-ready-and-read-only',response?.ok()===true&&install.api.version===1&&install.api.id===contract.candidate.id&&install.api.frozen&&install.outcome?.ok===true&&install.outcome?.id===contract.candidate.id&&install.outcome?.saveChanged===false&&install.outcome?.mechanicsChanged===false&&install.descriptors.api?.enumerable===false&&install.descriptors.api?.writable===false&&install.descriptors.result?.enumerable===false&&install.descriptors.result?.writable===false,install);
    await oathJourney(page,frame,step);await moreJourney(page,frame,step);const memory=await shared(page);step('isolated-realm-never-accesses-native-web-storage',memory.native.length===0,memory.native);step('journey-has-zero-warning-error-or-request-failures',watch.errors.length===0&&watch.requests.length===0,watch);
  }catch(error){let diagnostic=null;try{diagnostic=await frame?.evaluate(()=>({url:location.href,ready:document.readyState,screen:document.querySelector('[data-phase24l-compact-screen]')?.dataset.phase24lCompactScreen||null,text:document.body?.innerText?.replace(/\s+/g,' ').trim().slice(0,1600)}))}catch{}step('journey-fatal',false,{error:error.stack||error.message,diagnostic})}
  if(context)await context.close();
}

const WORKER_FLAG='EVERSTEAD_PHASE24L_B3A_BROWSER_WORKER';
const PLAYWRIGHT_MODULE=process.env.EVERSTEAD_PLAYWRIGHT_MODULE||'playwright';
const progress=message=>console.error(`[phase24l-b3a] ${new Date().toISOString()} ${message}`);
const bounded=(promise,ms,label)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`${label} timed out after ${ms}ms`)),ms);Promise.resolve(promise).then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})});
async function runWorker(){const instance=server();let browser;try{const baseURL=await bounded(listen(instance),10000,'HTTP server startup');progress(`server ready at ${baseURL}; loading Chromium`);const {chromium}=await import(PLAYWRIGHT_MODULE);browser=await chromium.launch({headless:true,timeout:45000});const selected=process.env.EVERSTEAD_PHASE24L_B3A_VIEWPORT,viewports=selected?contract.viewports.filter(item=>item.id===selected):contract.viewports;if(!viewports.length)throw new Error(`Unknown Phase 24L-B3A viewport: ${selected}`);for(const viewport of viewports){progress(`running ${viewport.id}`);await viewportJourney(browser,baseURL,viewport)}}catch(error){record('browser-suite-fatal',false,error.stack||error.message)}finally{if(browser)try{await bounded(browser.close(),15000,'Chromium shutdown')}catch(error){record('browser-shutdown-fatal',false,error.stack||error.message)}instance.closeAllConnections?.();if(instance.listening)try{await bounded(new Promise((resolve,reject)=>instance.close(error=>error?reject(error):resolve())),10000,'HTTP server shutdown')}catch(error){record('server-shutdown-fatal',false,error.stack||error.message)}}const failed=rows.filter(row=>!row.pass);for(const row of failed)console.error(`FAIL ${row.id}${row.detail?` · ${row.detail}`:''}`);console.log(`RESULT ${rows.length-failed.length} passed, ${failed.length} failed`);if(failed.length)process.exitCode=1}
async function supervise(){progress(`starting supervised browser worker (hard timeout ${contract.limits.browserHardTimeoutMs/60000} minutes)`);const child=spawn(process.execPath,[fileURLToPath(import.meta.url)],{cwd:process.cwd(),env:{...process.env,[WORKER_FLAG]:'1'},stdio:'inherit'});let timedOut=false,forceTimer;const hardTimer=setTimeout(()=>{timedOut=true;progress('browser worker exceeded hard timeout; terminating it');child.kill('SIGTERM');forceTimer=setTimeout(()=>child.kill('SIGKILL'),5000);forceTimer.unref?.()},contract.limits.browserHardTimeoutMs);const result=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',(code,signal)=>resolve({code,signal}))});clearTimeout(hardTimer);if(forceTimer)clearTimeout(forceTimer);if(timedOut){console.error('FAIL browser-suite-hard-timeout');process.exitCode=1;return}if(result.signal){console.error(`FAIL browser-worker-signal · ${result.signal}`);process.exitCode=1;return}process.exitCode=result.code??1}
if(process.env[WORKER_FLAG]==='1')await runWorker();else await supervise();
