import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..');
const read=relative=>fs.readFileSync(path.join(root,relative),'utf8'),bytes=relative=>fs.readFileSync(path.join(root,relative));
const hash=value=>crypto.createHash('sha256').update(value).digest('hex'),fileHash=relative=>hash(bytes(relative));
const contract=JSON.parse(read('qa/phase-24c2c-activation-authority/contract.json'));
const candidateSource=read('src/phase24c-zero-activation-authority.js');

const BASELINE=Object.freeze({
  candidateSourceSha256:'88ba60568041b764794b74dec6b926e34890354d6c13175491f5f87c4c92a03f',candidateSemanticSha256:'556641d1997d7cee1734e79da510141154f00be97a21138f08bc088de2e68aaf',
  definitionsSemanticSha256:'bcec7874519dc9a2cd6041ee56a9c681034ff064995d1357987dd73ff4631fd1',
  projectedPredecessorIndexSha256:'6109805093ee78f075257526b4822cf86c9ca22dbd2a2a05ab3ef7b0bcb8c5f3',
  acceptedSourcePins:Object.freeze({
    'src/phase24c-durable-definitions.js':'101377044214d87478475ba9064c4342b9ce8fcbe62e5d4e1743a08f31767f70',
    'src/phase24c-durable-foundation.js':'fbf9c7865977b195786c15ffe6b6725649b5c6552c8f46b831421083831e4479',
    'docs/PHASE_24C_INACTIVE_FOUNDATION_CONTRACT.md':'eb9a4f5d6c1c5910b3b977549f32f0e0063aab116c3d474e5eba0981a0348555',
    'docs/PHASE_24C_INACTIVE_FOUNDATION_RESULT.md':'a94bda7e4efc911ff772104efc184ea6c3e612290c42cea60ad199c7cc0ed346'
  }),
  acceptedCoordinatorPins:Object.freeze({
    'index.html':'73737ab74efd4e33b2a5fdae1d1c76a6e88b4e51b1bb43453e034f47d5d5c7fb',
    'docs/PHASE_24C2B_COORDINATOR_QA_CONTRACT.md':'61c39a6c55345f3f2795d1546ae623e880b93e0a827a82142278c7b384297e94',
    'docs/PHASE_24C2B_COORDINATOR_QA_RESULT.md':'fce10369eb2a9d48ed8291af3b8db75081976847247a5d469f778818d16c2b4a',
    'qa/phase-24c2b-coordinator/contract.json':'b0eac1046f4f434d71808e8e89cb59fa0854fee3ee47b0d03827b065b74de7ed',
    'qa/phase-24c2b-coordinator/verify.mjs':'d0ebb316032a2d93cbe491f04a35008cc35ef80fa015f27f01fcd6ca6870f842',
    'qa/phase-24c2b-coordinator/checksums.sha256':'dc4cc5d8a643affe9091cb18250d79e3e97c25f6696063dfb7f8fad28e0ae3c6'
  }),
  productionPins:Object.freeze({
    'src/phase18-19-runtime.js':'26686c97cc7c2a617224b8a287ab92933222e137c53bc309dedad6102d68df2e',
    'src/phase23-companion-catalog.js':'48da84995d57d78ab01899b4f1840763b2539b4c5605da68ccc309889d0c718f',
    'src/phase23-companion-runtime.js':'fd1455fef5cb5632fc53b055c935848e6b6f13f40175518520f0f4aa548dde40',
    'src/phase24-scaling-authority.js':'819fd4e308a98c699ac01a0c3df780eab11e777d933038b118850679d0f39d5c'
  }),
  phase24aFixtureSha256:'3e03402cd2b5211bee1f9f232b278e9d04724eacdeb0ade9da8976c3ad3f1ed5',
  phase24aReportSha256:'e7ede3199b5addabee64c13710985f822f8538e1313a946b0ef85c992a0dd353'
});

const EXPECTED=Object.freeze({
  constructors:['createDirectSchema14','migrateSchema13To14'],
  validators:['validateDefinitions','validateReleaseAuthority','validateSuccessorState'],
  proofPreparation:['capturePreSuccessorCheckpoint','attestPreSuccessorCheckpoint','currentSchema13Projection','canonicalStringify','sha256'],
  metadata:['version','configId','status','rootKey','successorSchema','migrationId','recentGrantLimit','grantFoldBatch','definitions','manifestHash','formulaOrder'],
  forbidden:['authorityHash','releaseSetIdentity','releaseManifestHash','detectBootstrapPolicy','captureDirectOriginAttestation','createInactiveRoot','emptyCollectionTotals','collectionTotals','validateCollectionDefinition','captureCollectionGrantPayload','previewCollectionGrant','finalizeCollectionGrant','foldCollectionReceiptsInState','rankProjection','planRankReleaseActivation','planFamilyAlignment','nextLegacyTier','evaluateAdditiveNumberBase','evaluateAdditivePool'],
  lineages:['direct-schema-14','safe-reset-schema-14','schema-13-to-14-migration'],
  validatorIds:{predecessor:'validator.schema-13.phase-24c-production.v1',directOrigin:'validator.direct-schema-14-origin.phase-24c-production.v1'},
  anchors:{
    fresh:{fellowCombatPower:35565,fellowEconomyPower:35150,companionActualPower:2200,companionMigrationFloorPower:0,companionEffectivePower:2200,fellowEconomyBps:390,companionEconomyBps:80,goldPerHour:27320.8092192},
    freshlyMigratedSchema12:{fellowCombatPower:36366,trueFreshFellowCombatPower:35565,migrationProtectionDelta:801,companionActualPower:2200,protectedFellowIds:['cael','orin']},
    migratedEstablished:{fellowCombatPower:36645,fellowEconomyPower:35150,companionActualPower:2272,companionMigrationFloorPower:2892,companionEffectivePower:2892,fellowEconomyBps:390,companionEconomyBps:83,goldPerHour:27328.94041242}
  },
  futurePolicy:{
    status:'locked-future-policy-inactive-in-zero-only-activation',mode:'uncapped-additive-named-pools',sharedLifetimeCapBps:null,overflowConversion:null,futureCollectionsContinueRewards:true,releaseBudgetsAreLifetimeCaps:false,mandatoryProgression:'permanent-only',compoundingAllowed:false,applicationBase:'unboosted-base-only',
    applicationOrder:{power:'base-roster-power-plus-might-bps-plus-collection-power-bps',earnings:'structural-building-earnings-plus-oath-bps-plus-collection-earnings-bps',exp:'raw-authored-fellow-or-companion-exp-plus-authored-exp-bps-plus-collection-exp-bps',facility:'base-active-facility-reward-plus-authored-active-bps-plus-local-collection-facility-bps',passiveBuildingGold:'earnings-pool-only'},
    alreadyBoostedTotalsMayBeMultiplied:false,excludedTargets:['player-rank-exp','family-intimacy','achievement-progress','event-progress','full-level-grants','already-captured-old-claims'],claimApplicationPolicy:'manual-exactly-once',receiptReplayPolicy:'migration-reload-and-replay-idempotent',limitedRerunProgressPolicy:'preserve-across-reruns',neverRerunsPermanentAlternativePolicy:'equivalent-permanent-alternative-required',stressThroughBps:100000,formulaReadsAllowedInZeroOnlyActivation:false
  }
});

const TOPOLOGY=Object.freeze({
  '$':['version','authorityId','manifestId','status','productionLoaded','purpose','supersession','acceptedSourceAuthority','acceptedCoordinatorPredecessor','productionPins','zeroOutputAnchors','activationSurface','validatorAuthority','checkpointAuthority','saveFormatAuthority','lineageContracts','zeroOnlyState','futureCollectionPolicy','forbiddenFoundationApis','forbiddenFeatures','integrationPrerequisites','releaseDeploymentPrerequisites'],
  '$.supersession':['scope','supersededAcceptedPath','acceptedValue','candidateAuthorizedValue','sourceStatusUnchanged','sourceConfigUnchanged','sourceDefinitionsUnchanged','sourceFormulasUnchanged','sourceBytesRemainImmutable','sourceSemanticAuthorityRemainsImmutable','noImplicitAuthorization'],
  '$.acceptedSourceAuthority':['definitionsGlobal','foundationGlobal','definitionsVersion','foundationVersion','configId','definitionsFileSha256','definitionsSemanticSha256','foundationFileSha256','acceptedContractSha256','acceptedResultSha256'],
  '$.acceptedCoordinatorPredecessor':['status','candidateIndexSha256','projectedPredecessorIndexSha256','contractSha256','resultSha256','qaContractSha256','qaVerifierSha256','qaChecksumsSha256','packageChecksPassed','staticChecksPassed','browserChecksPassed','productionSchema','phase24cSchema14WriteAuthority'],
  '$.productionPins':['phase1819RuntimeSha256','phase23CompanionCatalogSha256','phase23CompanionRuntimeSha256','phase24ScalingAuthoritySha256','phase24ScalingConfigId','predecessorSchema','successorSchema'],
  '$.zeroOutputAnchors':['fresh','freshlyMigratedSchema12','migratedEstablished','comparison','tolerance'],
  '$.zeroOutputAnchors.fresh':['fellowCombatPower','fellowEconomyPower','companionActualPower','companionMigrationFloorPower','companionEffectivePower','fellowEconomyBps','companionEconomyBps','goldPerHour'],
  '$.zeroOutputAnchors.freshlyMigratedSchema12':['fellowCombatPower','trueFreshFellowCombatPower','migrationProtectionDelta','companionActualPower','protectedFellowIds'],
  '$.zeroOutputAnchors.migratedEstablished':['fellowCombatPower','fellowEconomyPower','companionActualPower','companionMigrationFloorPower','companionEffectivePower','fellowEconomyBps','companionEconomyBps','goldPerHour'],
  '$.activationSurface':['allowedConstructors','allowedValidators','proofPreparationOnly','immutableMetadataOnly','allowedLineages','initialAuthorityMustBeExactAcceptedSource','validationRequiredBeforeAndAfterSerialization','validationRequiredBeforeAndAfterCommit','physicalResolverRequiredOnEveryValidation','callbacksExposed','capabilityTokensExposed','mutationPrimitivesExposed'],
  '$.validatorAuthority':['predecessorValidatorId','directOriginValidatorId','predecessorValidatorRequiresPhase23Shape','predecessorValidatorRequiresPhysicalPhase23Authority','directFreshRequiresCanonicalPhase23FreshOrigin','safeResetRequiresCanonicalPhase23ResetOrigin','safeResetRequiresAuthenticatedPreviousSave','safeResetRequiresDistinctPriorSaveId','safeResetForensicNullPairRequiresVersionNineMarker','safeResetForensicNullPairRequiresNamedValidator','safeResetForensicNullPairRequiresCompleteSourceBinding','safeResetNonNullPairRulesUnchanged','validatorInputsMustBeCloned','falseThrowOrMutationMustFailClosed'],
  '$.checkpointAuthority':['storageNamespace','storageKey','semanticSlotName','checkpointKind','checkpointIdPrefix','checkpointIdSuffix','checkpointIdDigest','checkpointIdTemplate','predecessorSchema','exactRawBytesRequired','canonicalActiveBytesRequired','writeOnceRequired','exactRereadRequired','ownerCheckedBeforeAndAfterWrite','resolverReturnsCheckpointAndRaw','directFreshCreatesCheckpoint','safeResetCreatesCheckpoint','realMigrationCreatesCheckpoint'],
  '$.saveFormatAuthority':['product','format','predecessorFormatVersion','successorFormatVersion','activeSchemaVersion','slotNames','snapshotControlNames','importPolicy','schema12ImportPolicy','futureSchemaPolicy','rollbackPolicy','safeResetPolicy'],
  '$.lineageContracts':['directFresh','safeReset','realMigration'],
  '$.lineageContracts.directFresh':['lineageKind','source','initialRevision','migrationReceipts','preV14Checkpoint','historicalRewardApplications','retainedCheckpointLineage'],
  '$.lineageContracts.safeReset':['lineageKind','source','initialRevision','migrationReceipts','preV14Checkpoint','historicalRewardApplications','retainedCheckpointLineage','previousSaveRequired'],
  '$.lineageContracts.realMigration':['lineageKind','stateSource','stagingSource','revisionIncrement','migrationId','migrationReceipts','preV14Checkpoint','historicalRewardApplications'],
  '$.zeroOnlyState':['activeReleaseIds','collectionTotals','recentGrantReceipts','claimedDefinitionIds','collectionContributionCount','collectionCheckpointThroughSequence','rankCapacityThrough','rankReleasedThrough','pendingRankTransitionIds','acknowledgedRankTransitionIds','familyAlignmentStatus','activeLegacyTrackIds','activeEventTrackIds','activeFacilityLadderIds','formulaReadsAllowed','claimReadinessAllowed','rewardApplicationsAllowed'],
  '$.zeroOnlyState.collectionTotals':['powerBps','earningsBps','expBps','facilityBpsByFacilityId'],
  '$.zeroOnlyState.collectionTotals.facilityBpsByFacilityId':[],
  '$.futureCollectionPolicy':['status','mode','sharedLifetimeCapBps','overflowConversion','futureCollectionsContinueRewards','releaseBudgetsAreLifetimeCaps','mandatoryProgression','compoundingAllowed','applicationBase','applicationOrder','alreadyBoostedTotalsMayBeMultiplied','excludedTargets','claimApplicationPolicy','receiptReplayPolicy','limitedRerunProgressPolicy','neverRerunsPermanentAlternativePolicy','stressThroughBps','formulaReadsAllowedInZeroOnlyActivation'],
  '$.futureCollectionPolicy.applicationOrder':['power','earnings','exp','facility','passiveBuildingGold']
});

let passed=0,failed=0;const failures=[];
function check(name,condition,detail=''){if(condition){passed++;return}failed++;failures.push({name,detail:String(detail)})}
function same(actual,expected){return JSON.stringify(actual)===JSON.stringify(expected)}
function equal(name,actual,expected){check(name,same(actual,expected),`actual=${JSON.stringify(actual)} expected=${JSON.stringify(expected)}`)}
function rejects(name,operation,pattern=/.*/){try{operation();check(name,false,'did not throw')}catch(error){check(name,pattern.test(String(error?.message||error)),error?.message)}}
function canonical(value,seen=new Set()){
  if(value===null)return'null';if(typeof value==='string'||typeof value==='boolean')return JSON.stringify(value);
  if(typeof value==='number'){if(!Number.isFinite(value))throw new TypeError('non-finite');return Object.is(value,-0)?'0':JSON.stringify(value)}
  if(!value||typeof value!=='object'||seen.has(value))throw new TypeError('non-plain');
  const isArray=Array.isArray(value),prototype=Object.getPrototypeOf(value),keys=Reflect.ownKeys(value),descriptors=Object.getOwnPropertyDescriptors(value);
  if(keys.some(key=>typeof key==='symbol')||keys.some(key=>Object.hasOwn(descriptors[key],'get')||Object.hasOwn(descriptors[key],'set')))throw new TypeError('symbol-or-accessor');
  if(isArray){if(Object.prototype.toString.call(value)!=='[object Array]'||!prototype||Object.getPrototypeOf(prototype)?.constructor?.name!=='Object')throw new TypeError('non-plain-array')}
  else if(Object.prototype.toString.call(value)!=='[object Object]'||!prototype||Object.getPrototypeOf(prototype)!==null||prototype.constructor?.name!=='Object')throw new TypeError('non-plain-object');
  seen.add(value);
  if(isArray){const result=`[${Object.keys(value).map(key=>canonical(descriptors[key].value,seen)).join(',')}]`;seen.delete(value);return result}
  const result=`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(descriptors[key].value,seen)}`).join(',')}}`;seen.delete(value);return result;
}
function at(value,pointer){return pointer==='$'?value:pointer.slice(2).split('.').reduce((row,key)=>row?.[key],value)}
function topologyErrors(value){const errors=[];for(const[pointer,keys]of Object.entries(TOPOLOGY)){const row=at(value,pointer),actual=row&&typeof row==='object'&&!Array.isArray(row)?Reflect.ownKeys(row):null;if(!actual||actual.some(key=>typeof key!=='string')||!same([...actual].sort(),[...keys].sort()))errors.push(pointer)}return errors}
function walk(value,visit,pointer='$',seen=new Set()){if(!value||typeof value!=='object'||seen.has(value))return;seen.add(value);visit(value,pointer);if(Array.isArray(value))value.forEach((child,index)=>walk(child,visit,`${pointer}[${index}]`,seen));else for(const[key,child]of Object.entries(value))walk(child,visit,`${pointer}.${key}`,seen)}
function hardeningErrors(value,{objectPrototype,arrayPrototype,requireFrozen=true}){const errors=[];walk(value,(row,pointer)=>{const isArray=Array.isArray(row),prototype=Object.getPrototypeOf(row),keys=Reflect.ownKeys(row),descriptors=Object.getOwnPropertyDescriptors(row);if(prototype!==(isArray?arrayPrototype:objectPrototype))errors.push(`${pointer}:prototype`);if(keys.some(key=>typeof key==='symbol'))errors.push(`${pointer}:symbol`);for(const key of keys){const descriptor=descriptors[key];if(Object.hasOwn(descriptor,'get')||Object.hasOwn(descriptor,'set'))errors.push(`${pointer}.${String(key)}:accessor`);if(key!=='length'&&(descriptor.enumerable!==true||requireFrozen&&(descriptor.writable!==false||descriptor.configurable!==false)))errors.push(`${pointer}.${String(key)}:descriptor`)}if(isArray){const length=descriptors.length;if(!length||length.enumerable!==false||requireFrozen&&(length.writable!==false||length.configurable!==false))errors.push(`${pointer}.length:descriptor`)}if(requireFrozen&&!Object.isFrozen(row))errors.push(`${pointer}:not-frozen`)});return errors}
function deepFreezeHost(value,seen=new Set()){if(!value||typeof value!=='object'||seen.has(value))return value;seen.add(value);for(const descriptor of Object.values(Object.getOwnPropertyDescriptors(value)))if(Object.hasOwn(descriptor,'value'))deepFreezeHost(descriptor.value,seen);return Object.freeze(value)}
const clone=value=>JSON.parse(JSON.stringify(value)),sum=(rows,key)=>rows.reduce((total,row)=>total+row[key],0),rosterBps=(config,power)=>Math.min(config.capBps,Math.floor(config.numeratorBps*power/(power+config.kneePower)));
function c2cProjection(source){const loaderPattern=/[\t ]*<!-- Phase 24C-2C zero-only authority load BEGIN -->[\s\S]*?<!-- Phase 24C-2C zero-only authority load END -->(?:\r?\n)?/g,jsPattern=/(^[\t ]*)?\/\* Phase 24C-2C ([^\r\n*]+?) BEGIN \*\/[\s\S]*?\/\* Phase 24C-2C \2 END \*\/(?:\r?\n)?/gm,loaders=[...source.matchAll(loaderPattern)];let normalized=source.replace(loaderPattern,'');normalized=normalized.replace(jsPattern,'');const loader=loaders[0]?.[0]||'',loaderSources=[...loader.matchAll(/<script\s+[^>]*src=["']([^"']+)["'][^>]*><\/script>/gi)].map(match=>match[1].split('?')[0]);return{normalized,loaderSources,loaderCount:loaders.length,beginCount:(source.match(/<!-- Phase 24C-2C zero-only authority load BEGIN -->/g)||[]).length,endCount:(source.match(/<!-- Phase 24C-2C zero-only authority load END -->/g)||[]).length}}

const candidateRealm=vm.createContext({}),beforeGlobals=new Set(Object.getOwnPropertyNames(candidateRealm));
vm.runInContext(candidateSource,candidateRealm,{filename:'src/phase24c-zero-activation-authority.js'});
const manifest=candidateRealm.EVERSTEAD_PHASE24C_ZERO_ACTIVATION_AUTHORITY,descriptor=Object.getOwnPropertyDescriptor(candidateRealm,'EVERSTEAD_PHASE24C_ZERO_ACTIVATION_AUTHORITY'),realmPrototypes=vm.runInContext('({object:Object.prototype,array:Array.prototype})',candidateRealm),afterGlobals=Object.getOwnPropertyNames(candidateRealm).filter(name=>!beforeGlobals.has(name));
const sourceSha256=hash(candidateSource),semanticSha256=hash(canonical(manifest));
const productionIndexText=read('index.html'),productionProjection=c2cProjection(productionIndexText);

check('candidate source hash is independently frozen',BASELINE.candidateSourceSha256!=='PENDING_FREEZE'&&sourceSha256===BASELINE.candidateSourceSha256,sourceSha256);
check('candidate semantic hash is independently frozen',BASELINE.candidateSemanticSha256!=='PENDING_FREEZE'&&semanticSha256===BASELINE.candidateSemanticSha256,semanticSha256);
check('QA contract mirrors independently frozen source hash',contract.expectedCandidateSourceSha256===BASELINE.candidateSourceSha256,contract.expectedCandidateSourceSha256);
check('QA contract mirrors independently frozen semantic hash',contract.expectedCandidateSemanticSha256===BASELINE.candidateSemanticSha256,contract.expectedCandidateSemanticSha256);
check('candidate installs exactly one global',same(afterGlobals,['EVERSTEAD_PHASE24C_ZERO_ACTIVATION_AUTHORITY']),afterGlobals);
check('candidate global descriptor is hidden immutable data',descriptor&&descriptor.enumerable===false&&descriptor.writable===false&&descriptor.configurable===false&&!Object.hasOwn(descriptor,'get')&&!Object.hasOwn(descriptor,'set'));
check('candidate exact topology has no missing or extra field',topologyErrors(manifest).length===0,topologyErrors(manifest));
const hardening=hardeningErrors(manifest,{objectPrototype:realmPrototypes.object,arrayPrototype:realmPrototypes.array});
check('every manifest node has exact realm prototype, no symbols/accessors, and frozen data descriptors',hardening.length===0,hardening);
check('candidate source has no storage, network, DOM, or messaging authority',!/(?:\blocalStorage\b|\bsessionStorage\b|\bindexedDB\b|\.setItem\s*\(|\.removeItem\s*\(|\bfetch\s*\(|\bXMLHttpRequest\b|\bWebSocket\b|\bdocument\b|\bwindow\b|\bpostMessage\s*\()/m.test(candidateSource));
check('candidate status is unloaded only',manifest.status==='unloaded-candidate-only'&&manifest.productionLoaded===false);

for(const[relative,expected]of Object.entries(BASELINE.acceptedSourcePins))check(`accepted source pin ${relative}`,fileHash(relative)===expected,fileHash(relative));
for(const[relative,expected]of Object.entries(BASELINE.acceptedCoordinatorPins)){const actual=relative==='index.html'?hash(productionProjection.normalized):fileHash(relative);check(`accepted C2B pin ${relative}`,actual===expected,actual)}
for(const[relative,expected]of Object.entries(BASELINE.productionPins))check(`production source pin ${relative}`,fileHash(relative)===expected,fileHash(relative));
equal('contract accepted-source pins are external-baseline exact',contract.acceptedSourcePins,BASELINE.acceptedSourcePins);
equal('contract accepted-C2B pins are external-baseline exact',contract.acceptedCoordinatorPins,BASELINE.acceptedCoordinatorPins);
equal('contract production pins are external-baseline exact',contract.productionPins,BASELINE.productionPins);
equal('contract lineages are current',contract.expectedLineages,EXPECTED.lineages);
equal('contract constructors are current',contract.expectedAllowedConstructors,EXPECTED.constructors);
equal('contract validators are current',contract.expectedAllowedValidators,EXPECTED.validators);
equal('contract proof preparation APIs are current',contract.expectedProofPreparationOnly,EXPECTED.proofPreparation);
equal('contract immutable metadata partition is current',contract.expectedImmutableMetadataOnly,EXPECTED.metadata);
equal('contract forbidden API partition is current',contract.expectedForbiddenFoundationApis,EXPECTED.forbidden);
check('contract header, candidate identity, status, and global are current',contract.contractId==='phase-24c2c-zero-activation-authority-qa.v1'&&contract.candidateSource==='src/phase24c-zero-activation-authority.js'&&contract.candidateGlobal==='EVERSTEAD_PHASE24C_ZERO_ACTIVATION_AUTHORITY'&&contract.status==='inactive-authority-physically-loaded-zero-integration-only');
check('contract definitions semantic identity is current',contract.definitionsSemanticSha256===BASELINE.definitionsSemanticSha256);
check('contract pre-v14 key is current',contract.expectedPreV14StorageKey==='oathforge_new_world_proto_v01__raw_backup_v13');
check('contract pre-v14 slot is current',contract.expectedPreV14Slot==='preV14');
check('contract successor format/schema are current',contract.expectedSuccessorFormatVersion===3&&contract.expectedSuccessorSchema===14);
check('contract predecessor projection hash is current',contract.expectedProjectedPredecessorIndexSha256===BASELINE.projectedPredecessorIndexSha256);
equal('contract least-authority loader order is current',contract.zeroIntegrationLoader?.exactOrder,['src/phase24c-zero-activation-authority.js','src/phase24c-durable-definitions.js','src/phase24c-durable-foundation.js']);
check('contract Phase24A fixture pin is external-baseline exact',contract.phase24aFixtureSha256===BASELINE.phase24aFixtureSha256);
check('contract Phase24A report pin is external-baseline exact',contract.phase24aReportSha256===BASELINE.phase24aReportSha256);
check('Phase24A fixture bytes are exact',fileHash('qa/phase-24a-scaling-authority/fixtures/contract.json')===BASELINE.phase24aFixtureSha256);
check('Phase24A report bytes are exact',fileHash('qa/phase-24-baseline/reports/phase24a-balance-report.json')===BASELINE.phase24aReportSha256);

const supersession=manifest.supersession;
check('supersession is bounded to foundation-v2 forensic null pair plus production-load metadata',supersession.scope==='foundation-v2-forensic-null-pair-plus-production-load-metadata'&&supersession.supersededAcceptedPath==='definitions.activation.productionLoaded'&&supersession.acceptedValue===false&&supersession.candidateAuthorizedValue===true);
check('supersession preserves status, config, definitions, and formulas while explicitly reopening foundation bytes and semantics',supersession.sourceStatusUnchanged==='inactive-foundation-only'&&supersession.sourceConfigUnchanged===true&&supersession.sourceDefinitionsUnchanged===true&&supersession.sourceFormulasUnchanged===true&&supersession.sourceBytesRemainImmutable===false&&supersession.sourceSemanticAuthorityRemainsImmutable===false&&supersession.noImplicitAuthorization===true);
check('accepted source identities are exact',manifest.acceptedSourceAuthority.definitionsFileSha256===BASELINE.acceptedSourcePins['src/phase24c-durable-definitions.js']&&manifest.acceptedSourceAuthority.foundationFileSha256===BASELINE.acceptedSourcePins['src/phase24c-durable-foundation.js']&&manifest.acceptedSourceAuthority.acceptedContractSha256===BASELINE.acceptedSourcePins['docs/PHASE_24C_INACTIVE_FOUNDATION_CONTRACT.md']&&manifest.acceptedSourceAuthority.acceptedResultSha256===BASELINE.acceptedSourcePins['docs/PHASE_24C_INACTIVE_FOUNDATION_RESULT.md']&&manifest.acceptedSourceAuthority.definitionsSemanticSha256===BASELINE.definitionsSemanticSha256);
const c2b=manifest.acceptedCoordinatorPredecessor;
check('C2B predecessor index and package identities are exact',c2b.candidateIndexSha256===BASELINE.acceptedCoordinatorPins['index.html']&&c2b.projectedPredecessorIndexSha256===BASELINE.projectedPredecessorIndexSha256&&c2b.contractSha256===BASELINE.acceptedCoordinatorPins['docs/PHASE_24C2B_COORDINATOR_QA_CONTRACT.md']&&c2b.resultSha256===BASELINE.acceptedCoordinatorPins['docs/PHASE_24C2B_COORDINATOR_QA_RESULT.md']&&c2b.qaContractSha256===BASELINE.acceptedCoordinatorPins['qa/phase-24c2b-coordinator/contract.json']&&c2b.qaVerifierSha256===BASELINE.acceptedCoordinatorPins['qa/phase-24c2b-coordinator/verify.mjs']&&c2b.qaChecksumsSha256===BASELINE.acceptedCoordinatorPins['qa/phase-24c2b-coordinator/checksums.sha256']);
check('C2B accepted refusal evidence is exact',c2b.status==='accepted-zero-write-refusal'&&c2b.packageChecksPassed===28&&c2b.staticChecksPassed===40&&c2b.browserChecksPassed===104&&c2b.productionSchema===13&&c2b.phase24cSchema14WriteAuthority===false);
check('production pins inside manifest are exact',manifest.productionPins.phase1819RuntimeSha256===BASELINE.productionPins['src/phase18-19-runtime.js']&&manifest.productionPins.phase23CompanionCatalogSha256===BASELINE.productionPins['src/phase23-companion-catalog.js']&&manifest.productionPins.phase23CompanionRuntimeSha256===BASELINE.productionPins['src/phase23-companion-runtime.js']&&manifest.productionPins.phase24ScalingAuthoritySha256===BASELINE.productionPins['src/phase24-scaling-authority.js']);

const sourceRealm=vm.createContext({});
vm.runInContext(read('src/phase24c-durable-definitions.js'),sourceRealm,{filename:'src/phase24c-durable-definitions.js'});vm.runInContext(read('src/phase24c-durable-foundation.js'),sourceRealm,{filename:'src/phase24c-durable-foundation.js'});
const definitions=sourceRealm.EVERSTEAD_PHASE24C_DEFINITIONS,foundation=sourceRealm.EVERSTEAD_PHASE24C_FOUNDATION;
check('accepted definitions remain inactive and unloaded',definitions.status==='inactive-foundation-only'&&definitions.activation.productionLoaded===false&&definitions.activation.activeReleaseIds.length===0);
check('accepted foundation v2 remains inactive',foundation.version===2&&manifest.acceptedSourceAuthority.foundationVersion===2&&foundation.status==='inactive-foundation-only');
check('accepted semantic manifest recomputes exactly',foundation.manifestHash===BASELINE.definitionsSemanticSha256,foundation.manifestHash);
check('accepted definitions validator passes',foundation.validateDefinitions().ok===true,foundation.validateDefinitions().errors);
check('accepted release validator passes',foundation.validateReleaseAuthority().ok===true,foundation.validateReleaseAuthority().errors);
check('accepted definitions have no grant and only reserved release',definitions.collections.grantDefinitions.length===0&&definitions.releaseManifests.length===1&&definitions.releaseManifests[0].active===false&&definitions.releaseManifests[0].status==='reserved');
check('accepted Rank capacity is 30 and released through 5',definitions.rank.capacityThrough===30&&definitions.rank.releasedThrough===5);

const activationValidatorId='validator.schema-13.phase-24c-production.v1',activationDirectValidatorId='validator.direct-schema-14-origin.phase-24c-production.v1';
function activationSchema13(value){return Boolean(value&&value.schemaVersion===13&&value.saveMeta&&typeof value.saveMeta.saveId==='string'&&value.saveMeta.saveId&&Number.isSafeInteger(value.saveMeta.revision)&&value.saveMeta.revision===1&&Number.isSafeInteger(value.saveMeta.createdAt)&&value.saveMeta.createdAt===value.saveMeta.updatedAt&&value.saveMeta.source==='safe-reset'&&Array.isArray(value.saveMeta.appliedMigrations)&&Number.isSafeInteger(value.gold)&&value.gold>=0&&value.player&&Number.isSafeInteger(value.player.rankExp)&&value.player.rankExp>=0&&value.family&&typeof value.family==='object'&&!Array.isArray(value.family))}
function activationForensicOrigin(id,rawIdentity='null:0:00000000'){return{schemaVersion:13,saveMeta:{saveId:id,revision:1,createdAt:1000,updatedAt:1000,source:'safe-reset',appliedMigrations:[],retainedCheckpointLineage:{kind:'safe-reset-retained-checkpoints',version:9,saveId:id,resetAt:1000,preResetSaveId:null,preResetRevision:null,preResetActiveRawIdentity:rawIdentity,phase24cPreviousInstallationIdentity:'a'.repeat(64)}},gold:5000,player:{rankExp:0},family:{elara:{intimacy:0,claimedIntimacyMilestoneIds:[]}}}}
function activationForensic(input,validator){const origins=new Map(),context={validatePredecessor:activationSchema13,predecessorValidatorId:activationValidatorId,validateDirectOrigin:validator,directOriginValidatorId:activationDirectValidatorId,resolveDirectOrigin:requested=>origins.get(requested)||null},result=foundation.createDirectSchema14(input,{...context,lineageKind:'safe-reset-schema-14'});origins.set(result.attestation.identity,clone(input));return{...result,context}}
let activationNullValidatorCalls=0;
const activationNullValidator=expectedRaw=>(value,lineageKind)=>{activationNullValidatorCalls++;const marker=value?.saveMeta?.retainedCheckpointLineage;return activationSchema13(value)&&lineageKind==='safe-reset-schema-14'&&marker?.version===9&&marker?.preResetSaveId===null&&marker?.preResetRevision===null&&marker?.preResetActiveRawIdentity===expectedRaw&&marker?.phase24cPreviousInstallationIdentity==='a'.repeat(64)};
const activationMissing=activationForensic(activationForensicOrigin('save-activation-null-missing'),activationNullValidator('null:0:00000000'));
check('activation gate physically exercises accepted missing-origin null pair through named validator',activationMissing.changed===true&&activationNullValidatorCalls===2&&foundation.validateSuccessorState(activationMissing.state,activationMissing.context).ok,foundation.validateSuccessorState(activationMissing.state,activationMissing.context).errors);
const activationCallsAfterMissing=activationNullValidatorCalls,activationMalformed=activationForensic(activationForensicOrigin('save-activation-null-malformed','fnv1a32:1:00000000'),activationNullValidator('fnv1a32:1:00000000'));
check('activation gate physically exercises accepted malformed-origin null pair through named validator',activationMalformed.changed===true&&activationNullValidatorCalls===activationCallsAfterMissing+2&&foundation.validateSuccessorState(activationMalformed.state,activationMalformed.context).ok,foundation.validateSuccessorState(activationMalformed.state,activationMalformed.context).errors);
const activationIncomplete=activationForensicOrigin('save-activation-null-incomplete');delete activationIncomplete.saveMeta.retainedCheckpointLineage.phase24cPreviousInstallationIdentity;
rejects('activation gate rejects incomplete forensic null binding',()=>activationForensic(activationIncomplete,()=>true),/canonical direct/);
const activationForged=activationForensicOrigin('save-activation-null-forged','fnv1a32:20:12345678');
rejects('activation gate rejects forged semantic source beside null pair',()=>activationForensic(activationForged,()=>false),/validators/);
const activationFalse=activationForensicOrigin('save-activation-null-false'),activationFalseBefore=canonical(activationFalse);
rejects('activation gate rejects false named forensic validator',()=>activationForensic(activationFalse,value=>{value.gold=-1;return false}),/validators/);
check('activation gate false validator cannot mutate caller',canonical(activationFalse)===activationFalseBefore);
const activationThrow=activationForensicOrigin('save-activation-null-throw'),activationThrowBefore=canonical(activationThrow);
rejects('activation gate rejects throwing named forensic validator',()=>activationForensic(activationThrow,value=>{value.gold=-1;throw new Error('hostile-forensic-validator')}),/validators/);
check('activation gate throwing validator cannot mutate caller',canonical(activationThrow)===activationThrowBefore);
const activationMutate=activationForensicOrigin('save-activation-null-mutate'),activationMutateBefore=canonical(activationMutate),activationMutateResult=activationForensic(activationMutate,value=>{value.gold=-1;return true});
check('activation gate approving mutating validator receives only a clone',activationMutateResult.state.gold===5000&&canonical(activationMutate)===activationMutateBefore);

equal('constructors exact',manifest.activationSurface.allowedConstructors,EXPECTED.constructors);equal('validators exact',manifest.activationSurface.allowedValidators,EXPECTED.validators);equal('proof preparation APIs exact',manifest.activationSurface.proofPreparationOnly,EXPECTED.proofPreparation);equal('immutable metadata exports exact',manifest.activationSurface.immutableMetadataOnly,EXPECTED.metadata);equal('forbidden APIs exact',manifest.forbiddenFoundationApis,EXPECTED.forbidden);equal('lineage union exact',manifest.activationSurface.allowedLineages,EXPECTED.lineages);
const partitions=[...EXPECTED.metadata,...EXPECTED.constructors,...EXPECTED.validators,...EXPECTED.proofPreparation,...EXPECTED.forbidden];
check('foundation export partition has no duplicate',new Set(partitions).size===partitions.length,partitions);equal('foundation export partition is exhaustive',partitions.slice().sort(),Object.keys(foundation).sort());
for(const name of [...EXPECTED.constructors,...EXPECTED.validators,...EXPECTED.proofPreparation,...EXPECTED.forbidden])check(`partitioned function exists: ${name}`,typeof foundation[name]==='function');
for(const name of EXPECTED.metadata)check(`partitioned immutable metadata exists: ${name}`,Object.hasOwn(foundation,name)&&typeof foundation[name]!=='function');
check('activation manifest exposes no callback, token, or mutator',manifest.activationSurface.callbacksExposed===false&&manifest.activationSurface.capabilityTokensExposed===false&&manifest.activationSurface.mutationPrimitivesExposed===false);
check('validator IDs are exact pinned values',manifest.validatorAuthority.predecessorValidatorId===EXPECTED.validatorIds.predecessor&&manifest.validatorAuthority.directOriginValidatorId===EXPECTED.validatorIds.directOrigin);equal('contract validator IDs are exact external values',contract.expectedValidatorIds,EXPECTED.validatorIds);
check('validators are clone-isolated and fail closed',manifest.validatorAuthority.validatorInputsMustBeCloned===true&&manifest.validatorAuthority.falseThrowOrMutationMustFailClosed===true&&manifest.validatorAuthority.predecessorValidatorRequiresPhysicalPhase23Authority===true);
check('forensic null-pair authority is exact and non-null rules stay unchanged',manifest.validatorAuthority.safeResetForensicNullPairRequiresVersionNineMarker===true&&manifest.validatorAuthority.safeResetForensicNullPairRequiresNamedValidator===true&&manifest.validatorAuthority.safeResetForensicNullPairRequiresCompleteSourceBinding===true&&manifest.validatorAuthority.safeResetNonNullPairRulesUnchanged===true&&contract.expectedForensicNullPairAuthority?.markerVersion===9&&contract.expectedForensicNullPairAuthority?.pairedNullRequired===true&&contract.expectedForensicNullPairAuthority?.namedValidatorRequired===true&&contract.expectedForensicNullPairAuthority?.completeSourceBindingRequired===true&&contract.expectedForensicNullPairAuthority?.nonNullPairRulesUnchanged===true);

check('pre-v14 key and semantic slot are exact',manifest.checkpointAuthority.storageKey==='oathforge_new_world_proto_v01__raw_backup_v13'&&manifest.checkpointAuthority.semanticSlotName==='preV14');
check('pre-v14 checkpoint is exact, write-once, owner-checked, and resolver-backed',manifest.checkpointAuthority.predecessorSchema===13&&manifest.checkpointAuthority.exactRawBytesRequired===true&&manifest.checkpointAuthority.canonicalActiveBytesRequired===true&&manifest.checkpointAuthority.writeOnceRequired===true&&manifest.checkpointAuthority.exactRereadRequired===true&&manifest.checkpointAuthority.ownerCheckedBeforeAndAfterWrite===true&&manifest.checkpointAuthority.resolverReturnsCheckpointAndRaw===true);
check('only real migration creates pre-v14 checkpoint',manifest.checkpointAuthority.directFreshCreatesCheckpoint===false&&manifest.checkpointAuthority.safeResetCreatesCheckpoint===false&&manifest.checkpointAuthority.realMigrationCreatesCheckpoint===true);
for(const saveId of ['save-phase24c2c-fixture','00000000-0000-4000-8000-000000000000','Save ID with imported punctuation']){const actual=`${manifest.checkpointAuthority.checkpointIdPrefix}${foundation.sha256(saveId)}${manifest.checkpointAuthority.checkpointIdSuffix}`,expected=`checkpoint.pre-v14.p${foundation.sha256(saveId)}.v1`;check(`checkpoint ID exact deterministic derivation: ${saveId}`,actual===expected&&/^[a-z][a-z0-9]*(?:[.-][a-z0-9]+)*$/.test(actual),actual)}
check('save format advances exactly 2 to 3 at schema 14',manifest.saveFormatAuthority.predecessorFormatVersion===2&&manifest.saveFormatAuthority.successorFormatVersion===3&&manifest.saveFormatAuthority.activeSchemaVersion===14);equal('save slots append preV14 exactly once',manifest.saveFormatAuthority.slotNames,['active','rawBackup','preV2','preV3','preV4','preV5','preV6','preV7','preV8','preV9','preV10','preV11','preV12','preV13','preV14']);
check('save policies never merge or accept future schema',manifest.saveFormatAuthority.importPolicy==='replace-one-authenticated-installation-never-merge'&&manifest.saveFormatAuthority.futureSchemaPolicy==='reject-with-zero-writes'&&manifest.saveFormatAuthority.schema12ImportPolicy==='authenticate-12-to-13-then-authenticate-13-to-14');

const fresh=manifest.lineageContracts.directFresh,reset=manifest.lineageContracts.safeReset,migration=manifest.lineageContracts.realMigration;
check('direct fresh exact reward-neutral lineage',fresh.lineageKind==='direct-schema-14'&&fresh.source==='fresh'&&fresh.initialRevision===1&&fresh.migrationReceipts===0&&fresh.preV14Checkpoint===false&&fresh.historicalRewardApplications===0&&fresh.retainedCheckpointLineage===false);
check('safe reset exact reward-neutral lineage',reset.lineageKind==='safe-reset-schema-14'&&reset.source==='safe-reset'&&reset.initialRevision===1&&reset.migrationReceipts===0&&reset.preV14Checkpoint===false&&reset.historicalRewardApplications===0&&reset.retainedCheckpointLineage===true&&reset.previousSaveRequired===true);
check('real migration exact one-hop reward-neutral lineage',migration.lineageKind==='schema-13-to-14-migration'&&migration.stateSource==='schema-13-to-14'&&migration.stagingSource==='schema-13-migration'&&migration.revisionIncrement===1&&migration.migrationId===foundation.migrationId&&migration.migrationReceipts===1&&migration.preV14Checkpoint===true&&migration.historicalRewardApplications===0);

equal('zero anchors exact deep/type equality',manifest.zeroOutputAnchors,{...EXPECTED.anchors,comparison:'exact-value-and-type',tolerance:0});equal('contract anchors exact deep/type equality',contract.expectedAnchors,EXPECTED.anchors);
equal('zero Collection totals exact',manifest.zeroOnlyState.collectionTotals,{powerBps:0,earningsBps:0,expBps:0,facilityBpsByFacilityId:{}});
check('zero state has no release, receipt, claim, contribution, or transition',manifest.zeroOnlyState.activeReleaseIds.length===0&&manifest.zeroOnlyState.recentGrantReceipts.length===0&&manifest.zeroOnlyState.claimedDefinitionIds.length===0&&manifest.zeroOnlyState.collectionContributionCount===0&&manifest.zeroOnlyState.collectionCheckpointThroughSequence===0&&manifest.zeroOnlyState.pendingRankTransitionIds.length===0&&manifest.zeroOnlyState.acknowledgedRankTransitionIds.length===0);
check('zero state has no Rank above 5 or inactive-family/track release',manifest.zeroOnlyState.rankCapacityThrough===30&&manifest.zeroOnlyState.rankReleasedThrough===5&&manifest.zeroOnlyState.familyAlignmentStatus==='reserved-inactive'&&manifest.zeroOnlyState.activeLegacyTrackIds.length===0&&manifest.zeroOnlyState.activeEventTrackIds.length===0&&manifest.zeroOnlyState.activeFacilityLadderIds.length===0);
check('zero state forbids formula reads, claims, and rewards',manifest.zeroOnlyState.formulaReadsAllowed===false&&manifest.zeroOnlyState.claimReadinessAllowed===false&&manifest.zeroOnlyState.rewardApplicationsAllowed===false);
equal('future Collection policy exact named adjacency and exclusions',manifest.futureCollectionPolicy,EXPECTED.futurePolicy);equal('contract future Collection policy exact',contract.expectedFutureCollectionPolicy,EXPECTED.futurePolicy);

const scalingRealm=vm.createContext({});vm.runInContext(read('src/phase23-companion-catalog.js'),scalingRealm,{filename:'src/phase23-companion-catalog.js'});vm.runInContext(read('src/phase24-scaling-authority.js'),scalingRealm,{filename:'src/phase24-scaling-authority.js'});
const scaling=scalingRealm.EVERSTEAD_PHASE24_SCALING,report=JSON.parse(read('qa/phase-24-baseline/reports/phase24a-balance-report.json'));
check('Phase24A runtime authority is exact live schema-13 baseline',scaling.version===1&&scaling.configId==='everstead-scaling-live-baseline.phase-24a.v1'&&scaling.status==='live-baseline-only'&&scaling.schemaVersion===13);
equal('future Collection release policy agrees with frozen Phase24A authority',{mode:scaling.active.collection.futureLockedPolicy.mode,futureCollectionsContinueRewards:scaling.active.collection.futureLockedPolicy.futureCollectionsContinueRewards,releaseBudgetsAreLifetimeCaps:scaling.active.collection.futureLockedPolicy.releaseBudgetsAreLifetimeCaps,mandatoryProgression:scaling.active.collection.futureLockedPolicy.mandatoryProgression,stressThroughBps:scaling.active.collection.futureLockedPolicy.stressThroughBps},{mode:EXPECTED.futurePolicy.mode,futureCollectionsContinueRewards:EXPECTED.futurePolicy.futureCollectionsContinueRewards,releaseBudgetsAreLifetimeCaps:EXPECTED.futurePolicy.releaseBudgetsAreLifetimeCaps,mandatoryProgression:EXPECTED.futurePolicy.mandatoryProgression,stressThroughBps:EXPECTED.futurePolicy.stressThroughBps});
const reportById=Object.fromEntries(report.profiles.map(row=>[row.profileId,row]));
function recompute(row){const fellowEconomyPower=sum(row.fellowEconomy.members,'effectivePower'),fellowCombatPower=sum(row.fellowCombat.members,'effectivePower'),companionActualPower=sum(row.companion.members,'effectivePower'),companionMigrationFloorPower=row.companion.migrationFloorRosterPower,companionEffectivePower=Math.max(companionActualPower,companionMigrationFloorPower),fellowEconomyBps=rosterBps(scaling.active.economy.fellowRoster,fellowEconomyPower),companionEconomyBps=rosterBps(scaling.active.economy.companionRoster,companionActualPower),rates=row.economy.buildings.map(building=>{const level=building.base*building.levelMultiplier,character=((building.familyAssignmentMultiplier*(1+fellowEconomyBps/10000))*(1+companionEconomyBps/10000))*building.overallDayMultiplier;return(level*character)*building.oathMultiplier}),ratesExact=rates.every((value,index)=>Object.is(value,row.economy.buildings[index].unroundedGoldPerHour));return{anchor:{fellowCombatPower,fellowEconomyPower,companionActualPower,companionMigrationFloorPower,companionEffectivePower,fellowEconomyBps,companionEconomyBps,goldPerHour:rates.reduce((total,value)=>total+value,0)},ratesExact}}
for(const[id,anchorKey]of [['phase24a.fresh.schema13.v1','fresh'],['phase24a.migrated-established.schema13.v1','migratedEstablished']]){const row=reportById[id],actual=recompute(row);equal(`independent frozen report/runtime recomputation ${anchorKey}`,actual.anchor,EXPECTED.anchors[anchorKey]);check(`production Gold core grouping is exact for every building ${anchorKey}`,actual.ratesExact);check(`report fields agree exactly with independent recomputation ${anchorKey}`,row.fellowEconomy.rosterPower===actual.anchor.fellowEconomyPower&&row.fellowCombat.rosterPower===actual.anchor.fellowCombatPower&&row.companion.actualRosterPower===actual.anchor.companionActualPower&&row.companion.effectiveThresholdRosterPower===actual.anchor.companionEffectivePower&&row.economy.fellowRosterBps===actual.anchor.fellowEconomyBps&&row.economy.companionRosterBps===actual.anchor.companionEconomyBps&&Object.is(row.economy.totalGoldPerHour,actual.anchor.goldPerHour))}
const historical=report.historicalMigrationComparisons.freshSchema12To13.expectedAnchors,authorityHistorical=scaling.historicalAnchors.freshlyMigratedSchema12;
equal('historical migrated anchor recomputed from frozen runtime/report',{fellowCombatPower:historical.fellowCombatPower,trueFreshFellowCombatPower:reportById['phase24a.fresh.schema13.v1'].fellowCombat.rosterPower,migrationProtectionDelta:historical.fellowCombatPower-reportById['phase24a.fresh.schema13.v1'].fellowCombat.rosterPower,companionActualPower:historical.companionActualPower,protectedFellowIds:Object.values(historical.migrationTransferFloors).map(row=>row.assignedFellowId).sort()},EXPECTED.anchors.freshlyMigratedSchema12);equal('historical migrated authority declaration matches recomputation',{fellowCombatPower:authorityHistorical.fellowCombatPower,trueFreshFellowCombatPower:authorityHistorical.trueFreshFellowCombatPower,migrationProtectionDelta:authorityHistorical.migrationProtectionDelta,companionActualPower:authorityHistorical.companionActualRosterPower,protectedFellowIds:authorityHistorical.protectedFellowIds},EXPECTED.anchors.freshlyMigratedSchema12);

for(const required of ['active-collection-release','nonzero-collection-total','collection-formula-read','collection-formula-application','rank-release-above-five','family-alignment-or-readiness','phase24b-runtime-curve-adoption','new-reward-source','new-user-interface','storage-write-by-authority-manifest','commit-merge-push-deploy-or-public-release'])check(`forbidden feature explicit: ${required}`,manifest.forbiddenFeatures.includes(required));
for(const required of ['accepted-phase24c2b-zero-write-refusal','physical-prev14-checkpoint-and-resolver','physical-direct-origin-and-previous-save-resolver','schema14-contextual-validation-dispatch','exact-zero-output-differential-gate','browser-mobile-multitab-gate','explicit-production-activation-approval'])check(`integration prerequisite explicit: ${required}`,manifest.integrationPrerequisites.includes(required));
check('real-device/Safari is release-deployment gate, not local integration gate',!manifest.integrationPrerequisites.some(value=>/real-device|safari/i.test(value))&&manifest.releaseDeploymentPrerequisites.includes('real-device-and-safari-gates'));

function candidateAccepted(value,prototypes){try{if(topologyErrors(value).length||hardeningErrors(value,prototypes).length)return false;return hash(canonical(value))===BASELINE.candidateSemanticSha256}catch{return false}}
check('exact hardened candidate acceptance closes over frozen semantic identity',candidateAccepted(manifest,{objectPrototype:realmPrototypes.object,arrayPrototype:realmPrototypes.array}));
const hostPrototypes={objectPrototype:Object.prototype,arrayPrototype:Array.prototype},hostile=[];function attack(id,mutate){const value=clone(manifest);let setup=true;try{mutate(value);deepFreezeHost(value)}catch{setup=false}hostile.push({id,rejected:setup&&!candidateAccepted(value,hostPrototypes)})}
attack('extra-top-level',value=>{value.grants=[]});attack('extra-constructor',value=>{value.activationSurface.allowedConstructors.push('grantCollection')});attack('extra-release',value=>{value.zeroOnlyState.activeReleaseIds.push('release.collection.v1')});attack('nonzero-power',value=>{value.zeroOnlyState.collectionTotals.powerBps=1});attack('formula-read',value=>{value.zeroOnlyState.formulaReadsAllowed=true});attack('rank-six',value=>{value.zeroOnlyState.rankReleasedThrough=6});attack('validator-id-substitution',value=>{value.validatorAuthority.predecessorValidatorId='validator.attacker.v1'});attack('predecessor-pin-substitution',value=>{value.acceptedCoordinatorPredecessor.candidateIndexSha256='0'.repeat(64)});attack('compounding-enable',value=>{value.futureCollectionPolicy.compoundingAllowed=true});attack('lifetime-cap-injection',value=>{value.futureCollectionPolicy.sharedLifetimeCapBps=3000});attack('forbidden-target-removal',value=>{value.futureCollectionPolicy.excludedTargets.pop()});attack('automatic-claim-substitution',value=>{value.futureCollectionPolicy.claimApplicationPolicy='automatic'});attack('limited-rerun-progress-reset',value=>{value.futureCollectionPolicy.limitedRerunProgressPolicy='reset-on-rerun'});attack('never-reruns-alternative-removal',value=>{delete value.futureCollectionPolicy.neverRerunsPermanentAlternativePolicy});attack('missing-required-field',value=>{delete value.checkpointAuthority.exactRereadRequired});attack('callback-field',value=>{value.activationSurface.callback='attacker'});attack('token-field',value=>{value.activationSurface.token='attacker'});attack('ui-field',value=>{value.ui={enabled:true}});attack('storage-write-field',value=>{value.storageWrite={enabled:true}});
attack('forensic-version-nine-bypass',value=>{value.validatorAuthority.safeResetForensicNullPairRequiresVersionNineMarker=false});attack('forensic-named-validator-bypass',value=>{value.validatorAuthority.safeResetForensicNullPairRequiresNamedValidator=false});attack('forensic-complete-binding-bypass',value=>{value.validatorAuthority.safeResetForensicNullPairRequiresCompleteSourceBinding=false});attack('forensic-non-null-rules-bypass',value=>{value.validatorAuthority.safeResetNonNullPairRulesUnchanged=false});
const symbolVariant=clone(manifest);Object.defineProperty(symbolVariant,Symbol('grant'),{value:true,enumerable:false});deepFreezeHost(symbolVariant);hostile.push({id:'symbol-field',rejected:!candidateAccepted(symbolVariant,hostPrototypes)});const accessorVariant=clone(manifest);Object.defineProperty(accessorVariant,'purpose',{get(){return manifest.purpose},enumerable:true,configurable:true});deepFreezeHost(accessorVariant);hostile.push({id:'accessor-field',rejected:!candidateAccepted(accessorVariant,hostPrototypes)});const prototypeVariant=clone(manifest);Object.setPrototypeOf(prototypeVariant,{grant:true});deepFreezeHost(prototypeVariant);hostile.push({id:'prototype-substitution',rejected:!candidateAccepted(prototypeVariant,hostPrototypes)});
check('hostile negative mutation corpus is exhaustive and all rejected',hostile.length===26&&hostile.every(row=>row.rejected),hostile);

check('production index has exactly one bounded zero-integration loader',productionProjection.loaderCount===1&&productionProjection.beginCount===1&&productionProjection.endCount===1,{loaderCount:productionProjection.loaderCount,beginCount:productionProjection.beginCount,endCount:productionProjection.endCount});
equal('production zero-integration loader order is exact least authority',productionProjection.loaderSources,contract.zeroIntegrationLoader.exactOrder);
check('removing only bounded C2C loader/integration blocks yields exact accepted C2B bytes',hash(productionProjection.normalized)===BASELINE.acceptedCoordinatorPins['index.html'],hash(productionProjection.normalized));
const checksumPath='qa/phase-24c2c-activation-authority/checksums.sha256',expectedChecksumPaths=['src/phase24c-zero-activation-authority.js','qa/phase-24c2c-activation-authority/README.md','qa/phase-24c2c-activation-authority/contract.json','qa/phase-24c2c-activation-authority/verify.mjs','docs/PHASE_24C2C_ZERO_ACTIVATION_AUTHORITY_CONTRACT.md','docs/PHASE_24C2C_ZERO_ACTIVATION_AUTHORITY_RESULT.md'];if(fs.existsSync(path.join(root,checksumPath))){const rows=read(checksumPath).trim().split(/\r?\n/).filter(Boolean),parsed=rows.map(row=>/^([0-9a-f]{64})  (.+)$/.exec(row)),paths=parsed.map(match=>match?.[2]??null),bad=parsed.flatMap((match,index)=>!match||!fs.existsSync(path.join(root,match[2]))||fileHash(match[2])!==match[1]?[rows[index]]:[]);check('package checksum manifest exact ordered unique closure',rows.length===6&&same(paths,expectedChecksumPaths)&&new Set(paths).size===paths.length&&bad.length===0,{paths,bad})}else check('package checksum manifest exact ordered unique closure',false,'missing');

const reportOut={contractId:contract.contractId,passed,failed,candidateSourceSha256:sourceSha256,candidateSemanticSha256:semanticSha256,acceptedC2BIndexSha256:hash(productionProjection.normalized),phase24aReportSha256:fileHash('qa/phase-24-baseline/reports/phase24a-balance-report.json'),productionLoaded:false,hostileMutationsRejected:hostile.filter(row=>row.rejected).length,failures};console.log(JSON.stringify(reportOut,null,2));if(failed)process.exitCode=1;
