import {chromium} from '/Users/westmanfamily/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';

const origin=(process.argv[2]||'http://127.0.0.1:8840').replace(/\/$/,'');
const sizes=[{id:'small',width:320,height:568},{id:'standard',width:390,height:844}];
const rows=[];
const add=(size,id,ok,detail='')=>rows.push({id:`${size}-${id}`,pass:Boolean(ok),detail});
const browser=await chromium.launch({headless:true});

for(const size of sizes){
 const context=await browser.newContext({viewport:{width:size.width,height:size.height}});
 const errors=[];
 await context.addInitScript(()=>{
  const slots=new Map(),writes=[];
  let saveIndex=0,transactionIndex=0;
  const nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);
  const storage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>{slots.set(String(key),String(value));writes.push({op:'set',key:String(key),value:String(value)})},removeItem:key=>{slots.delete(String(key));writes.push({op:'remove',key:String(key)})}};
  Object.defineProperty(window,'__B3C_WRITES__',{value:writes});
  window.__EVERSTEAD_RUNTIME__={storage,clock:{now:()=>100000000,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.375,confirm:()=>true,ids:{save:()=>`save-b3c-${++saveIndex}`,transaction:()=>`tx-b3c-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
 });
 let page=await context.newPage();
 const watch=current=>{current.on('console',message=>{if(['warning','error'].includes(message.type()))errors.push(`${message.type()}: ${message.text()}`)});current.on('pageerror',error=>errors.push(`pageerror: ${error.message}`))};
 watch(page);
 await page.goto(`${origin}/index.html?qa=1&phase24l-b3c=1`,{waitUntil:'load'});
 await page.waitForFunction(()=>window.__EVERSTEAD_PHASE24L_B3C_RESULT__&&window.__EVERSTEAD_PHASE_16_QA__);
 const raw=()=>page.evaluate(()=>window.__EVERSTEAD_PHASE_16_QA__.read.raw());
 const revision=async()=>JSON.parse(await raw()).saveMeta.revision;

 if(!(await page.locator('[data-building="training"]').count()))await page.locator('[data-nav="village"]').click();
 const rawBeforeOpen=await raw();
 await page.locator('[data-building="training"]').click();
 await page.waitForSelector('[data-phase24l-b3c-building]');
 const buildingLayout=await page.evaluate(()=>{const modal=document.querySelector('.modal'),shell=document.querySelector('[data-phase24l-b3c-building]'),panel=shell?.querySelector('[data-phase24l-b3c-panel="production"]'),targets=[...shell.querySelectorAll('[data-phase24l-b3c-tabs="building"] [role="tab"]')].map(node=>node.getBoundingClientRect());return{shells:document.querySelectorAll('[data-phase24l-b3c-building]').length,tabs:targets.length,selected:shell?.querySelector('[role="tab"][aria-selected="true"]')?.dataset.phase24lB3cTab,visible:[...shell.querySelectorAll('[data-phase24l-b3c-panel]')].filter(node=>!node.hidden).length,minimumTargets:targets.every(rect=>rect.width>=44&&rect.height>=44),modalScroll:modal.scrollHeight-modal.clientHeight,panelScroll:panel.scrollHeight-panel.clientHeight,bodyScroll:document.scrollingElement.scrollHeight-document.scrollingElement.clientHeight,overflowX:document.documentElement.scrollWidth-document.documentElement.clientWidth}});
 add(size.id,'building-opens-write-neutral',await raw()===rawBeforeOpen,buildingLayout);
 add(size.id,'building-one-shell-three-tabs',buildingLayout.shells===1&&buildingLayout.tabs===3&&buildingLayout.selected==='production'&&buildingLayout.visible===1,buildingLayout);
 add(size.id,'building-bounded-no-page-overflow-and-touch-safe',buildingLayout.minimumTargets&&buildingLayout.modalScroll===0&&buildingLayout.bodyScroll===0&&buildingLayout.overflowX===0,buildingLayout);
 const rawBeforeBuildingTrap=await raw();
 await page.locator('.modal').focus();
 await page.keyboard.press('Shift+Tab');
 const buildingTrapLast=await page.evaluate(()=>({inside:document.querySelector('.modal')?.contains(document.activeElement)===true,tab:document.activeElement?.dataset?.phase24lB3cTab||null,tabIndex:document.activeElement?.tabIndex,hiddenAncestor:Boolean(document.activeElement?.closest?.('[hidden],[inert],[aria-hidden="true"]'))}));
 await page.keyboard.press('Tab');
 const buildingTrapFirst=await page.evaluate(()=>({inside:document.querySelector('.modal')?.contains(document.activeElement)===true,close:document.activeElement?.matches?.('[data-modal-close]')===true,hiddenAncestor:Boolean(document.activeElement?.closest?.('[hidden],[inert],[aria-hidden="true"]'))}));
 add(size.id,'building-tab-trap-excludes-inactive-and-hidden-controls',await raw()===rawBeforeBuildingTrap&&buildingTrapLast.inside&&buildingTrapLast.tab==='production'&&buildingTrapLast.tabIndex===0&&!buildingTrapLast.hiddenAncestor&&buildingTrapFirst.inside&&buildingTrapFirst.close&&!buildingTrapFirst.hiddenAncestor,{last:buildingTrapLast,first:buildingTrapFirst});
 const rawBeforeTabs=await raw();
 for(const id of ['assign','production','upgrade','assign'])await page.locator(`[data-phase24l-b3c-tabs="building"] [data-phase24l-b3c-tab="${id}"]`).click();
 const tabState=await page.evaluate(()=>({selected:document.querySelector('[data-phase24l-b3c-tabs="building"] [aria-selected="true"]')?.dataset.phase24lB3cTab,visible:[...document.querySelectorAll('[data-phase24l-b3c-building] [data-phase24l-b3c-panel]')].filter(node=>!node.hidden).length,inactiveEscapes:[...document.querySelectorAll('[data-phase24l-b3c-building] [data-phase24l-b3c-panel][hidden]')].filter(node=>!node.inert).length}));
 add(size.id,'building-tabs-write-neutral-exclusive-inert',await raw()===rawBeforeTabs&&tabState.selected==='assign'&&tabState.visible===1&&tabState.inactiveEscapes===0,tabState);

 const assignment=page.locator('[data-family-assignment]');
 const choice=await assignment.evaluate(select=>[...select.options].map(option=>option.value).find(value=>value&&value!==select.value));
 const rawBeforePreview=await raw();
 await assignment.selectOption(choice);
 add(size.id,'assignment-selection-is-preview-only',await raw()===rawBeforePreview);
 const assignmentRevision=await revision();
 await page.locator('[data-phase-11d-family-apply]').click();
 await page.waitForFunction(previous=>JSON.parse(window.__EVERSTEAD_PHASE_16_QA__.read.raw()).saveMeta.revision===previous+1,assignmentRevision);
 const assignmentAfter=await page.evaluate(()=>({selected:document.querySelector('[data-phase24l-b3c-tabs="building"] [aria-selected="true"]')?.dataset.phase24lB3cTab,shells:document.querySelectorAll('[data-phase24l-b3c-building]').length,apply:document.querySelectorAll('[data-phase-11d-family-apply]').length}));
 add(size.id,'assignment-commits-once-and-retains-tab',(await revision())===assignmentRevision+1&&assignmentAfter.selected==='assign'&&assignmentAfter.shells===1&&assignmentAfter.apply===1,assignmentAfter);

 await page.locator('[data-phase24l-b3c-tab="upgrade"]').click();
 const upgradeRevision=await revision();
 const upgradeEnabled=await page.locator('[data-modal-act="upgrade-building"]').evaluate(button=>!button.disabled);
 if(upgradeEnabled){
  await page.locator('[data-modal-act="upgrade-building"]').click();
  await page.waitForFunction(previous=>JSON.parse(window.__EVERSTEAD_PHASE_16_QA__.read.raw()).saveMeta.revision===previous+1,upgradeRevision);
 }
 const upgradeAfter=await page.evaluate(()=>({selected:document.querySelector('[data-phase24l-b3c-tabs="building"] [aria-selected="true"]')?.dataset.phase24lB3cTab,shells:document.querySelectorAll('[data-phase24l-b3c-building]').length,actions:document.querySelectorAll('[data-modal-act="upgrade-building"]').length}));
 add(size.id,'upgrade-commits-once-and-retains-tab',upgradeEnabled&&(await revision())===upgradeRevision+1&&upgradeAfter.selected==='upgrade'&&upgradeAfter.shells===1&&upgradeAfter.actions===1,upgradeAfter);
 const rawBeforeBuildingClose=await raw();
 await page.keyboard.press('Escape');
 await page.waitForSelector('[data-phase24l-b3c-building]',{state:'detached'});
 const buildingClose=await page.evaluate(()=>({overlayChildren:document.querySelector('#overlay')?.children.length??-1,focusReturned:document.activeElement?.matches?.('[data-building="training"]')===true}));
 add(size.id,'building-escape-closes-write-neutral-and-restores-focus',await raw()===rawBeforeBuildingClose&&buildingClose.overlayChildren===0&&buildingClose.focusReturned,buildingClose);

 await page.close();
 page=await context.newPage();watch(page);
 await page.goto(`${origin}/index.html?qa=1&phase24l-b3c=1`,{waitUntil:'load'});
 await page.waitForFunction(()=>window.__EVERSTEAD_PHASE24L_B3C_RESULT__&&window.__EVERSTEAD_PHASE_16_QA__&&window.__EVERSTEAD_PHASE_24L_B3C_QA__);
 const preparedDiscovery=await page.evaluate(()=>window.__EVERSTEAD_PHASE_24L_B3C_QA__.destructive.prepareRestaurant());
 await page.locator('[data-nav="village"]').click();
 const discoveryHotspot=await page.locator('[data-phase15-facility-id="facility.restaurant"]').evaluate(button=>({disabled:button.disabled,state:button.dataset.phase15State,label:button.getAttribute('aria-label')}));
 add(size.id,'restaurant-current-schema-discovery-prepared',preparedDiscovery?.ok===true&&!discoveryHotspot.disabled&&discoveryHotspot.state==='discovered',{preparedDiscovery,discoveryHotspot});
 await page.locator('[data-phase15-facility-id="facility.restaurant"]').click();
 await page.waitForSelector('[data-phase17-facility-introduction]');
 const introductionRevision=await revision();
 await page.locator('[data-phase17-opening-resolution="watched"][data-phase17-opening-facility="facility.restaurant"]').click();
 await page.waitForFunction(previous=>JSON.parse(window.__EVERSTEAD_PHASE_16_QA__.read.raw()).saveMeta.revision>previous,introductionRevision);
 await page.waitForSelector('[data-phase17-facility-introduction]',{state:'detached'});
 await page.locator('[data-phase15-facility-id="facility.restaurant"]').click();
 await page.waitForSelector('[data-phase24l-b3c-restaurant]');
 const openedRestaurantRevision=await revision();
 const openedRestaurant=await page.evaluate(()=>window.__EVERSTEAD_PHASE_16_QA__.read.derive().restaurant);
 add(size.id,'restaurant-opens-through-real-story-route',openedRestaurantRevision>=introductionRevision+1&&Number.isSafeInteger(openedRestaurant.unlockedAt),{introductionRevision,openedRestaurantRevision,unlockedAt:openedRestaurant.unlockedAt});
 await page.locator('[data-phase16-close]').first().click();
 const interval=await page.evaluate(()=>window.__EVERSTEAD_PHASE_16_QA__.read.economyReport()?.policy?.intervalMs||3600000);
 const settled=await page.evaluate(intervalMs=>window.__EVERSTEAD_PHASE_16_QA__.destructive.advanceOffline({kind:'phase24l-b3c-capture',elapsedMs:intervalMs*2}),interval);
 const banked=await page.evaluate(()=>window.__EVERSTEAD_PHASE_16_QA__.read.derive().restaurant.customers);
 add(size.id,'restaurant-banks-real-customers-without-expiry',settled?.ok===true&&banked.length>=2&&banked.slice(0,2).every(item=>item.status==='banked'),{settled:{ok:settled?.ok,createdCount:settled?.createdCount,elapsedAppliedMs:settled?.elapsedAppliedMs,rewardApplications:settled?.rewardApplications},bankedCount:banked.length});
 const rawBeforeRestaurantOpen=await raw();
 await page.locator('[data-phase15-facility-id="facility.restaurant"]').click();
 await page.waitForSelector('[data-phase24l-b3c-restaurant]');
 const restaurantLayout=await page.evaluate(()=>{const modal=document.querySelector('.modal'),root=document.querySelector('[data-phase24l-b3c-restaurant]'),targets=[...root.querySelectorAll('[data-phase24l-b3c-tabs="restaurant"] [role="tab"],:scope > .phase16-actions .btn')].map(node=>node.getBoundingClientRect());return{shells:document.querySelectorAll('[data-phase24l-b3c-restaurant]').length,tabs:root.querySelectorAll('[data-phase24l-b3c-tabs="restaurant"] [role="tab"]').length,selected:root.querySelector('[role="tab"][aria-selected="true"]')?.dataset.phase24lB3cTab,visible:[...root.querySelectorAll('[data-phase24l-b3c-panel]')].filter(node=>!node.hidden).length,actions:root.querySelectorAll(':scope > .phase16-actions').length,minimumTargets:targets.every(rect=>rect.width>=44&&rect.height>=44),modalScroll:modal.scrollHeight-modal.clientHeight,bodyScroll:document.scrollingElement.scrollHeight-document.scrollingElement.clientHeight,overflowX:document.documentElement.scrollWidth-document.documentElement.clientWidth}});
 add(size.id,'restaurant-opens-write-neutral',await raw()===rawBeforeRestaurantOpen,restaurantLayout);
 add(size.id,'restaurant-one-shell-four-tabs-one-dock',restaurantLayout.shells===1&&restaurantLayout.tabs===4&&restaurantLayout.selected==='guest'&&restaurantLayout.visible===1&&restaurantLayout.actions===1,restaurantLayout);
 add(size.id,'restaurant-bounded-no-page-overflow-and-touch-safe',restaurantLayout.minimumTargets&&restaurantLayout.modalScroll===0&&restaurantLayout.bodyScroll===0&&restaurantLayout.overflowX===0,restaurantLayout);
 const rawBeforeRestaurantTrap=await raw();
 await page.locator('.modal').focus();
 await page.keyboard.press('Shift+Tab');
 const restaurantTrapLast=await page.evaluate(()=>({inside:document.querySelector('.modal')?.contains(document.activeElement)===true,tab:document.activeElement?.dataset?.phase24lB3cTab||null,tabIndex:document.activeElement?.tabIndex,hiddenAncestor:Boolean(document.activeElement?.closest?.('[hidden],[inert],[aria-hidden="true"]'))}));
 await page.keyboard.press('Tab');
 const restaurantTrapFirst=await page.evaluate(()=>({inside:document.querySelector('.modal')?.contains(document.activeElement)===true,close:document.activeElement?.matches?.('[data-modal-close]')===true,hiddenAncestor:Boolean(document.activeElement?.closest?.('[hidden],[inert],[aria-hidden="true"]'))}));
 add(size.id,'restaurant-tab-trap-excludes-inactive-and-hidden-controls',await raw()===rawBeforeRestaurantTrap&&restaurantTrapLast.inside&&restaurantTrapLast.tab==='guest'&&restaurantTrapLast.tabIndex===0&&!restaurantTrapLast.hiddenAncestor&&restaurantTrapFirst.inside&&restaurantTrapFirst.close&&!restaurantTrapFirst.hiddenAncestor,{last:restaurantTrapLast,first:restaurantTrapFirst});
 const rawBeforeRestaurantTabs=await raw();
 for(const id of ['kitchen','pantry','result','guest'])await page.locator(`[data-phase24l-b3c-tabs="restaurant"] [data-phase24l-b3c-tab="${id}"]`).click();
 const restaurantTabState=await page.evaluate(()=>({selected:document.querySelector('[data-phase24l-b3c-tabs="restaurant"] [aria-selected="true"]')?.dataset.phase24lB3cTab,visible:[...document.querySelectorAll('[data-phase24l-b3c-restaurant] [data-phase24l-b3c-panel]')].filter(node=>!node.hidden).length,inactiveEscapes:[...document.querySelectorAll('[data-phase24l-b3c-restaurant] [data-phase24l-b3c-panel][hidden]')].filter(node=>!node.inert).length}));
 add(size.id,'restaurant-tabs-write-neutral-exclusive-inert',await raw()===rawBeforeRestaurantTabs&&restaurantTabState.selected==='guest'&&restaurantTabState.visible===1&&restaurantTabState.inactiveEscapes===0,restaurantTabState);
 const rawBeforeKeyboardTabs=await raw();
 await page.locator('[data-phase24l-b3c-tabs="restaurant"] [data-phase24l-b3c-tab="guest"]').focus();
 await page.keyboard.press('ArrowRight');
 const keyboardTabState=await page.evaluate(()=>({selected:document.querySelector('[data-phase24l-b3c-tabs="restaurant"] [aria-selected="true"]')?.dataset.phase24lB3cTab,focused:document.activeElement?.dataset?.phase24lB3cTab||null,visible:[...document.querySelectorAll('[data-phase24l-b3c-restaurant] [data-phase24l-b3c-panel]')].filter(node=>!node.hidden).length}));
 add(size.id,'restaurant-arrow-navigation-is-roving-exclusive-and-write-neutral',await raw()===rawBeforeKeyboardTabs&&keyboardTabState.selected==='kitchen'&&keyboardTabState.focused==='kitchen'&&keyboardTabState.visible===1,keyboardTabState);
 const beginRevision=await revision();
 await page.locator('[data-phase16-prepare]').click();
 await page.waitForFunction(previous=>JSON.parse(window.__EVERSTEAD_PHASE_16_QA__.read.raw()).saveMeta.revision===previous+1,beginRevision);
 const begun=await page.evaluate(()=>({selected:document.querySelector('[data-phase24l-b3c-tabs="restaurant"] [aria-selected="true"]')?.dataset.phase24lB3cTab,shells:document.querySelectorAll('[data-phase24l-b3c-restaurant]').length,docks:document.querySelectorAll('[data-phase24l-b3c-restaurant] > .phase16-actions').length,label:document.querySelector('[data-phase16-prepare]')?.textContent}));
 add(size.id,'welcome-rebuilds-on-kitchen-once',(await revision())===beginRevision+1&&begun.selected==='kitchen'&&begun.shells===1&&begun.docks===1&&begun.label==='PREPARE',begun);
 const prepareRevision=await revision();
 await page.locator('[data-phase16-prepare]').click();
 await page.waitForFunction(previous=>JSON.parse(window.__EVERSTEAD_PHASE_16_QA__.read.raw()).saveMeta.revision===previous+1,prepareRevision);
 const prepared=await page.evaluate(()=>({selected:document.querySelector('[data-phase24l-b3c-tabs="restaurant"] [aria-selected="true"]')?.dataset.phase24lB3cTab,shells:document.querySelectorAll('[data-phase24l-b3c-restaurant]').length,docks:document.querySelectorAll('[data-phase24l-b3c-restaurant] > .phase16-actions').length}));
 add(size.id,'prepare-rebuilds-on-kitchen-once',(await revision())===prepareRevision+1&&prepared.selected==='kitchen'&&prepared.shells===1&&prepared.docks===1,prepared);
 const preparation=await page.evaluate(()=>window.__EVERSTEAD_PHASE_16_QA__.read.derive().restaurant.customers[0]);
 const completed=await page.evaluate(record=>window.__EVERSTEAD_PHASE_16_QA__.destructive.advancePreparation(record.id,record.identity,record.preparationCompletesAt),preparation);
 add(size.id,'preparation-completes-through-current-authority',completed?.ok===true&&completed?.completed===true,{ok:completed?.ok,completed:completed?.completed,batchLostCount:completed?.batchLostCount,writes:completed?.writes});
 await page.locator('[data-phase16-close]').first().click();
 await page.locator('[data-phase15-facility-id="facility.restaurant"]').click();
 await page.waitForSelector('[data-phase24l-b3c-restaurant]');
 const transferRevision=await revision();
 const transferLabel=await page.locator('[data-phase16-prepare]').textContent();
 await page.locator('[data-phase16-prepare]').click();
 await page.waitForFunction(previous=>JSON.parse(window.__EVERSTEAD_PHASE_16_QA__.read.raw()).saveMeta.revision===previous+1,transferRevision);
 const transferred=await page.evaluate(()=>({selected:document.querySelector('[data-phase24l-b3c-tabs="restaurant"] [aria-selected="true"]')?.dataset.phase24lB3cTab,shells:document.querySelectorAll('[data-phase24l-b3c-restaurant]').length,docks:document.querySelectorAll('[data-phase24l-b3c-restaurant] > .phase16-actions').length,serveDisabled:document.querySelector('[data-phase16-serve]')?.disabled}));
 add(size.id,'transfer-rebuilds-on-kitchen-once',transferLabel?.trim()==='TRANSFER BATCH'&&(await revision())===transferRevision+1&&transferred.selected==='kitchen'&&transferred.shells===1&&transferred.docks===1&&transferred.serveDisabled===false,{transferLabel,transferred});
 const serveRevision=await revision();
 const goldBeforeServe=await page.evaluate(()=>window.__EVERSTEAD_PHASE_16_QA__.read.derive().resources.gold);
 await page.locator('[data-phase16-serve]').click();
 await page.waitForFunction(previous=>JSON.parse(window.__EVERSTEAD_PHASE_16_QA__.read.raw()).saveMeta.revision===previous+1,serveRevision);
 const goldAfterServe=await page.evaluate(()=>window.__EVERSTEAD_PHASE_16_QA__.read.derive().resources.gold);
 const claimReady=await page.evaluate(()=>({selected:document.querySelector('[data-phase24l-b3c-tabs="restaurant"] [aria-selected="true"]')?.dataset.phase24lB3cTab,result:document.querySelectorAll('.phase16-result').length,claimDisabled:document.querySelector('[data-phase16-claim]')?.disabled,shells:document.querySelectorAll('[data-phase24l-b3c-restaurant]').length,docks:document.querySelectorAll('[data-phase24l-b3c-restaurant] > .phase16-actions').length}));
 add(size.id,'serve-commits-once-without-early-reward',(await revision())===serveRevision+1&&goldAfterServe===goldBeforeServe,{goldBeforeServe,goldAfterServe,claimReady});
 add(size.id,'claim-ready-defaults-to-result',claimReady.selected==='result'&&claimReady.result===1&&!claimReady.claimDisabled&&claimReady.shells===1&&claimReady.docks===1,claimReady);
 const claimRevision=await revision();
 const goldBeforeClaim=goldAfterServe;
 await page.locator('[data-phase16-claim]').click();
 await page.waitForFunction(previous=>JSON.parse(window.__EVERSTEAD_PHASE_16_QA__.read.raw()).saveMeta.revision===previous+1,claimRevision);
 const goldAfterClaim=await page.evaluate(()=>window.__EVERSTEAD_PHASE_16_QA__.read.derive().resources.gold);
 const claimed=await page.evaluate(()=>({selected:document.querySelector('[data-phase24l-b3c-tabs="restaurant"] [aria-selected="true"]')?.dataset.phase24lB3cTab,shells:document.querySelectorAll('[data-phase24l-b3c-restaurant]').length,docks:document.querySelectorAll('[data-phase24l-b3c-restaurant] > .phase16-actions').length,claims:document.querySelectorAll('[data-phase16-claim]').length}));
 add(size.id,'claim-commits-once-applies-reward-and-rebuilds-cleanly',(await revision())===claimRevision+1&&goldAfterClaim>goldBeforeClaim&&claimed.selected==='guest'&&claimed.shells===1&&claimed.docks===1&&claimed.claims===1,{goldBeforeClaim,goldAfterClaim,claimed});
 const geometry=await page.evaluate(()=>{const root=document.querySelector('[data-phase24l-b3c-restaurant]'),tabs=root.querySelector('[data-phase24l-b3c-tabs="restaurant"]'),dock=root.querySelector(':scope > .phase16-actions'),rect=node=>{const value=node.getBoundingClientRect();return{left:value.left,right:value.right,top:value.top,bottom:value.bottom,width:value.width,height:value.height}};return{root:rect(root),tabs:rect(tabs),dock:rect(dock),viewport:[innerWidth,innerHeight]}});
 add(size.id,'restaurant-tabs-and-actions-remain-visible',geometry.tabs.bottom<=size.height+1&&geometry.tabs.top>=0&&geometry.dock.bottom<=geometry.tabs.top+1&&geometry.dock.top>=0,geometry);
 const rawBeforeRestaurantClose=await raw();
 await page.keyboard.press('Escape');
 await page.waitForSelector('[data-phase24l-b3c-restaurant]',{state:'detached'});
 const restaurantClose=await page.evaluate(()=>({overlayChildren:document.querySelector('#overlay')?.children.length??-1,focusReturned:document.activeElement?.matches?.('[data-phase15-facility-id="facility.restaurant"]')===true}));
 add(size.id,'restaurant-escape-closes-write-neutral-and-restores-hotspot-focus',await raw()===rawBeforeRestaurantClose&&restaurantClose.overlayChildren===0&&restaurantClose.focusReturned,restaurantClose);
 add(size.id,'zero-warning-error-console',errors.length===0,errors);
 await context.close();
}

await browser.close();
for(const row of rows)console.log(`${row.pass?'PASS':'FAIL'} ${row.id}${row.detail?` · ${typeof row.detail==='string'?row.detail:JSON.stringify(row.detail)}`:''}`);
const failed=rows.filter(row=>!row.pass);
console.log(`RESULT ${rows.length-failed.length} passed, ${failed.length} failed`);
if(failed.length)process.exitCode=1;
