(() => {
  'use strict';
  const CHANNEL='everstead-phase-12-independent',json=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');

  function installRuntime(config){
    const slots=new Map(),writes=[],errors=[],nativeStorageAccesses=[],nativeSetTimeout=setTimeout.bind(window),nativeClearTimeout=clearTimeout.bind(window);let saveIndex=0,transactionIndex=0,nativeStorageInstrumented=false;
    window.matchMedia=query=>({matches:config.viewport.reducedMotion&&query==='(prefers-reduced-motion: reduce)',media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}});
    try{const nativeStorage=window.localStorage;for(const name of ['getItem','setItem','removeItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===nativeStorage)nativeStorageAccesses.push(`${name}:${String(args[0])}`);return original.apply(this,args)}}nativeStorageInstrumented=true}catch{}
    addEventListener('error',event=>errors.push(String(event.error?.stack||event.message)));addEventListener('unhandledrejection',event=>errors.push(String(event.reason?.stack||event.reason)));const warn=console.warn.bind(console),error=console.error.bind(console);console.warn=(...args)=>{errors.push('console.warn '+args.join(' '));warn(...args)};console.error=(...args)=>{errors.push('console.error '+args.join(' '));error(...args)};
    const memoryStorage={getItem:key=>slots.get(String(key))??null,setItem:(key,value)=>{key=String(key);writes.push({op:'set',key,value:String(value)});slots.set(key,String(value))},removeItem:key=>{key=String(key);writes.push({op:'remove',key});slots.delete(key)}};
    Object.assign(window,{__P12I_CONFIG__:config,__P12I_SLOTS__:slots,__P12I_WRITES__:writes,__P12I_ERRORS__:errors,__P12I_NATIVE_ACCESSES__:nativeStorageAccesses,__P12I_NATIVE_INSTRUMENTED__:nativeStorageInstrumented});
    window.__EVERSTEAD_RUNTIME__={storage:memoryStorage,clock:{now:()=>config.fixtures.frozenNow,setTimeout:nativeSetTimeout,clearTimeout:nativeClearTimeout},random:()=>.375,confirm:()=>true,ids:{save:()=>`save-p12i-${++saveIndex}`,transaction:()=>`tx-p12i-${++transactionIndex}`},qa:{allowDestructive:true,isolatedStorage:true}};
  }

  function runSuite(){
    const config=window.__P12I_CONFIG__,f=config.fixtures,results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),until=async(predicate,limit=8000)=>{const started=performance.now();while(performance.now()-started<limit){if(predicate())return true;await wait(25)}return false},same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),add=(id,actual,detail='')=>results.push({id,actual:Boolean(actual),expected:true,pass:Boolean(actual),detail:typeof detail==='string'?detail:JSON.stringify(detail)}),send=()=>parent.postMessage({channel:config.channel,nonce:config.nonce,results,errors:window.__P12I_ERRORS__.slice()},'*'),bridge=()=>window.__EVERSTEAD_PHASE_12_QA__,stableId=/^[a-z][a-z0-9]*(?:[.-][a-z0-9]+)+$/;
    const safe=(label,fn)=>{try{return fn()}catch(error){add(label,false,error.stack||error.message);return null}},stateOf=snapshot=>snapshot?.state||null,revision=snapshot=>stateOf(snapshot)?.saveMeta?.revision,receipts=state=>state?.saveMeta?.appliedMigrations||[],derive=()=>bridge().read.derive(),snapshot=()=>bridge().read.snapshot(),raw=()=>bridge().read.raw(),tutorialState=(id,data=derive())=>(data?.tutorials||[]).find(item=>item.id===id),claimState=(id,data=derive())=>(data?.claims||[]).find(item=>item.id===id);
    (async()=>{
      await until(()=>bridge(),5000);const qa=bridge();add('bridge-present',Boolean(qa));if(!qa){add('phase12-contract-unavailable',false,'Expected before Phase 12 implementation: window.__EVERSTEAD_PHASE_12_QA__ is absent.');send();return}
      add('bridge-version',qa.version===f.bridgeVersion,qa.version);const requiredRead=['definitions','snapshot','validate','derive','raw'],requiredDestructive=['reset','reload','advanceOffline','claim','tutorial','legacyMode','simulateConcurrentActivation','simulateConcurrentClaim'];add('bridge-read-surface',requiredRead.every(name=>typeof qa.read?.[name]==='function'),Object.keys(qa.read||{}));add('bridge-destructive-surface',requiredDestructive.every(name=>typeof qa.destructive?.[name]==='function'),Object.keys(qa.destructive||{}));if(!requiredRead.every(name=>typeof qa.read?.[name]==='function')||!requiredDestructive.every(name=>typeof qa.destructive?.[name]==='function')){send();return}

      const definitions=safe('definitions-readable',()=>qa.read.definitions());if(!definitions){send();return}const catalog=definitions.catalog||[],catalogIds=catalog.map(item=>item.id),catalogSet=new Set(catalogIds),referenceUniverse=new Set([...catalogIds,...f.fellowIds,...f.familyIds,...f.buildingIds,...f.companionIds,'wayfarer']);
      add('definition-set-versioned',definitions.predecessorSchemaVersion===f.schema.predecessor&&definitions.schemaVersion===f.schema.candidate&&typeof definitions.definitionSetId==='string'&&stableId.test(definitions.definitionSetId)&&definitions.migrationId===f.schema.activationId,{schema:definitions.schemaVersion,predecessor:definitions.predecessorSchemaVersion,definitionSetId:definitions.definitionSetId,migrationId:definitions.migrationId});
      add('catalog-nonempty-stable-unique',catalog.length>=10&&catalogIds.every(id=>stableId.test(id))&&catalogSet.size===catalogIds.length,{count:catalog.length,duplicates:catalogIds.filter((id,index)=>catalogIds.indexOf(id)!==index)});
      const dangling=[];for(const item of catalog)for(const ref of item.references||[])if(!referenceUniverse.has(ref))dangling.push(`${item.id}->${ref}`);add('catalog-reference-integrity',dangling.length===0,dangling);
      const rewards=definitions.rewards||[],rewardIds=new Set(rewards.map(item=>item.id)),invalidRewardDefs=rewards.filter(item=>!stableId.test(item.id)||!Number.isSafeInteger(item.version)||item.version<1),badRewardRefs=catalog.filter(item=>item.reward&&(typeof item.reward.id!=='string'||!rewardIds.has(item.reward.id)||!Number.isSafeInteger(item.reward.version)||item.reward.version!==rewards.find(reward=>reward.id===item.reward.id)?.version));add('reward-identities-versioned',rewards.length>0&&invalidRewardDefs.length===0&&badRewardRefs.length===0,{invalidRewardDefs,badRewardRefs:badRewardRefs.map(item=>item.id)});

      const features=definitions.features||[],tutorials=definitions.tutorials||[],requiredFeatures=features.filter(item=>item.tutorialRequired),featureIds=new Set(features.map(item=>item.id)),tutorialFeatureCounts=Object.fromEntries(features.map(feature=>[feature.id,tutorials.filter(item=>item.featureId===feature.id).length]));add('required-phase12-features-registered',f.requiredFeatureIds.every(id=>featureIds.has(id)),[...featureIds]);add('tutorial-coverage-exact',requiredFeatures.length>=f.requiredFeatureIds.length&&requiredFeatures.every(item=>tutorialFeatureCounts[item.id]===1),tutorialFeatureCounts);const ranks=tutorials.map(item=>item.trigger?.rank);add('tutorial-rank-triggers-valid',tutorials.length>=f.requiredFeatureIds.length&&tutorials.every(item=>stableId.test(item.id)&&featureIds.has(item.featureId)&&Number.isInteger(item.trigger?.rank)&&item.trigger.rank>=1&&item.trigger.rank<=5&&item.skipAllowed===true&&item.replayAllowed===true&&Number.isSafeInteger(item.rewardVersion)&&item.rewardVersion>=1),tutorials);add('tutorials-gradual-across-ranks',tutorials.length<2||new Set(ranks).size>=2,ranks);

      const expectedSpeakers=[...f.fellowIds,...f.familyIds].sort(),speakers=definitions.speakers||[],speakerIds=speakers.map(item=>item.id).sort(),coverage=definitions.dialogueCoverage||{},badCoverage=[];for(const id of expectedSpeakers){const ids=coverage[id];if(!Array.isArray(ids)||ids.length<1||ids.some(contentId=>!catalogSet.has(contentId)))badCoverage.push({id,contentIds:ids})}add('speaker-registry-exact-all-rosters',same(speakerIds,expectedSpeakers)&&speakers.filter(item=>item.rosterKind==='fellow').length===18&&speakers.filter(item=>item.rosterKind==='family').length===20,{actual:speakerIds,expected:expectedSpeakers});add('dialogue-coverage-all-rosters',badCoverage.length===0,badCoverage);
      add('legacy-modes-declared-dormant',f.requiredLegacyModes.every(id=>definitions.legacyModes?.[id]===false),definitions.legacyModes);

      const fresh=safe('fresh-reset-call',()=>qa.destructive.reset(f.fixtures.fresh)),freshSnap=snapshot();add('fresh-reset-valid',fresh?.ok===true&&qa.read.validate().ok===true&&stateOf(freshSnap)?.schemaVersion===definitions.schemaVersion,{fresh,validation:qa.read.validate()});const freshRaw=raw(),freshReload=safe('fresh-reload-call',()=>qa.destructive.reload()),freshReloadSnap=snapshot();add('fresh-reload-idempotent',freshReload?.ok===true&&qa.read.validate().ok===true&&raw()===freshRaw&&revision(freshReloadSnap)===revision(freshSnap),{beforeRevision:revision(freshSnap),afterRevision:revision(freshReloadSnap)});
      const tampered=structuredClone(stateOf(freshReloadSnap)),claimBucket=tampered?.rewardClaims?.pendingOffers||tampered?.phase12?.claims||tampered?.claims,danglingClaim={id:'qa-dangling-claim',definitionId:'missing.definition',rewardId:'missing.reward',rewardVersion:1,status:'ready'};if(Array.isArray(claimBucket))claimBucket.push(danglingClaim);else if(claimBucket&&typeof claimBucket==='object')claimBucket[danglingClaim.id]=danglingClaim;const tamperedValidation=claimBucket?safe('dangling-reference-validation-call',()=>qa.read.validate(tampered)):null;add('dangling-reference-rejected',Boolean(claimBucket)&&tamperedValidation?.ok===false,tamperedValidation||'Candidate snapshot exposes no claim state for validator tampering.');

      const migrated=safe('schema12-activation-call',()=>qa.destructive.reset(f.fixtures.schema12Established)),migratedSnap=snapshot(),migratedDerived=derive(),migrationReceipts=receipts(stateOf(migratedSnap)).filter(item=>item?.id===definitions.migrationId),statById=new Map((migratedDerived.statistics||[]).map(item=>[item.id,item])),unknownFailures=(definitions.accumulatedStatisticIds||[]).filter(id=>{const item=statById.get(id);return!item||item.baseline?.status!=='unknown-historical'||item.baseline?.at!==migrationReceipts[0]?.appliedAt||item.value!==0});add('schema12-established-activates-valid',migrated?.ok===true&&migrated.transactionClass==='activation'&&migrated.checkpointWrites===0&&migrated.protectedAuthorityPreserved===true&&qa.read.validate().ok===true&&stateOf(migratedSnap)?.schemaVersion===12,{migrated,validation:qa.read.validate()});add('activation-receipt-exactly-once',migrationReceipts.length===1&&migrationReceipts[0]?.id===f.schema.activationId&&migrationReceipts[0]?.from===12&&migrationReceipts[0]?.to===12&&migrationReceipts[0]?.definitionSetId===definitions.definitionSetId,migrationReceipts);add('unknown-history-baselines-explicit',(definitions.accumulatedStatisticIds||[]).length>0&&unknownFailures.length===0,unknownFailures);
      const migratedRaw=raw(),migratedRevision=revision(migratedSnap),migratedResources=migratedDerived.resources,migratedReload=safe('activated-reload-call',()=>qa.destructive.reload()),migratedReloadSnap=snapshot(),migratedReloadDerived=derive(),migrationReceiptsAfter=receipts(stateOf(migratedReloadSnap)).filter(item=>item?.id===definitions.migrationId);add('activation-reload-idempotent',migratedReload?.ok===true&&raw()===migratedRaw&&revision(migratedReloadSnap)===migratedRevision&&migrationReceiptsAfter.length===1&&same(migratedReloadDerived.resources,migratedResources),{beforeRevision:migratedRevision,afterRevision:revision(migratedReloadSnap),receiptCount:migrationReceiptsAfter.length});const activationRace=safe('concurrent-activation-call',()=>qa.destructive.simulateConcurrentActivation());add('two-tab-activation-one-winner',activationRace?.ok===true&&activationRace.winnerCount===1&&activationRace.loserCount===1&&activationRace.receiptCount===1&&activationRace.losingWrites===0&&activationRace.checkpointWrites===0&&activationRace.protectedAuthorityPreserved===true&&activationRace.finalValid===true,activationRace);

      const claimReset=safe('claim-fixture-reset-call',()=>qa.destructive.reset(f.fixtures.claimReady)),beforeClaimSnap=snapshot(),beforeClaimDerived=derive(),ready=claimState(f.examples.claimId,beforeClaimDerived);add('claim-ready-banked-unpaid',claimReset?.ok===true&&ready?.status==='ready'&&ready?.paid===false&&ready?.expiresAt==null,{claimReset,ready});const first=safe('first-claim-call',()=>qa.destructive.claim(f.examples.claimId)),afterFirstSnap=snapshot(),afterFirstDerived=derive(),afterReady=claimState(f.examples.claimId,afterFirstDerived);add('first-claim-commits-once',first?.ok===true&&first.receipt?.claimId===f.examples.claimId&&Number.isSafeInteger(first.receipt?.rewardVersion)&&afterReady?.status==='claimed'&&revision(afterFirstSnap)===revision(beforeClaimSnap)+1,{first,beforeRevision:revision(beforeClaimSnap),afterRevision:revision(afterFirstSnap),claim:afterReady});const claimedRaw=raw(),claimedRevision=revision(afterFirstSnap),claimedResources=afterFirstDerived.resources,second=safe('duplicate-claim-call',()=>qa.destructive.claim(f.examples.claimId));add('immediate-duplicate-write-free',second?.ok===false&&raw()===claimedRaw&&revision(snapshot())===claimedRevision&&same(derive().resources,claimedResources)&&Number(second.writes||0)===0,second);
      safe('claimed-reload-call',()=>qa.destructive.reload());const reloadRaw=raw(),reloadRevision=revision(snapshot()),reloadDuplicate=safe('reload-duplicate-claim-call',()=>qa.destructive.claim(f.examples.claimId));add('reload-duplicate-write-free',reloadDuplicate?.ok===false&&raw()===reloadRaw&&revision(snapshot())===reloadRevision&&same(derive().resources,claimedResources)&&Number(reloadDuplicate.writes||0)===0,reloadDuplicate);

      safe('offline-claim-fixture-reset-call',()=>qa.destructive.reset(f.fixtures.claimReady));const offlineBefore=derive(),offline=safe('offline-advance-call',()=>qa.destructive.advanceOffline(f.offline.requestedMs)),offlineAfter=derive(),offlineReady=claimState(f.examples.claimId,offlineAfter);add('offline-cap-preserved',offline?.ok===true&&offline.appliedMs===f.offline.capMs&&offline.requestedMs===f.offline.requestedMs,offline);add('offline-keeps-claim-banked',offlineReady?.status==='ready'&&offlineReady?.paid===false&&offlineReady?.expiresAt==null&&same(offlineBefore.claims,offlineAfter.claims),{before:offlineBefore.claims,after:offlineAfter.claims});
      safe('offline-claim-once-call',()=>qa.destructive.claim(f.examples.claimId));const offlineClaimedRaw=raw(),offlineClaimedRevision=revision(snapshot()),offlineDuplicate=safe('offline-duplicate-call',()=>qa.destructive.claim(f.examples.claimId));add('offline-duplicate-write-free',offlineDuplicate?.ok===false&&raw()===offlineClaimedRaw&&revision(snapshot())===offlineClaimedRevision&&Number(offlineDuplicate.writes||0)===0,offlineDuplicate);
      const race=safe('concurrent-claim-call',()=>qa.destructive.simulateConcurrentClaim(f.examples.claimId));add('two-tab-one-winner',race?.ok===true&&race.winnerCount===1&&race.loserCount===1&&race.receiptCount===1&&race.rewardApplications===1&&race.losingWrites===0&&race.finalValid===true,race);

      const tutorialReset=safe('tutorial-fixture-reset-call',()=>qa.destructive.reset(f.fixtures.tutorialReady)),tutorialId=f.examples.tutorialId,trigger=safe('tutorial-trigger-call',()=>qa.destructive.tutorial('trigger',tutorialId)),triggered=tutorialState(tutorialId),complete=safe('tutorial-complete-call',()=>qa.destructive.tutorial('complete',tutorialId)),completed=tutorialState(tutorialId),completeRaw=raw(),completeRewards=derive().resources,repeatComplete=safe('tutorial-repeat-complete-call',()=>qa.destructive.tutorial('complete',tutorialId));add('tutorial-trigger-and-complete',tutorialReset?.ok===true&&trigger?.ok===true&&['ready','active'].includes(triggered?.status)&&complete?.ok===true&&completed?.status==='completed'&&completed?.completionReceiptCount===1,{trigger,triggered,complete,completed});add('tutorial-completion-no-duplicate',repeatComplete?.ok===false&&raw()===completeRaw&&same(derive().resources,completeRewards)&&tutorialState(tutorialId)?.completionReceiptCount===1&&Number(repeatComplete.writes||0)===0,repeatComplete);
      safe('tutorial-skip-reset-call',()=>qa.destructive.reset(f.fixtures.tutorialReady));safe('tutorial-skip-trigger-call',()=>qa.destructive.tutorial('trigger',tutorialId));const skip=safe('tutorial-skip-call',()=>qa.destructive.tutorial('skip',tutorialId)),skipped=tutorialState(tutorialId),skipRewards=derive().resources;add('tutorial-skip-nonblocking',skip?.ok===true&&skipped?.status==='skipped'&&skipped?.featureAvailable===true&&skipped?.completionReceiptCount===0,{skip,skipped});safe('tutorial-skip-reload-call',()=>qa.destructive.reload());const replay=safe('tutorial-replay-call',()=>qa.destructive.tutorial('replay',tutorialId)),replayed=tutorialState(tutorialId);add('tutorial-skip-replay-safe',replay?.ok===true&&replayed?.replayCount===1&&replayed?.completionReceiptCount===0&&same(derive().resources,skipRewards)&&Number(replay.rewardApplications||0)===0,{replay,replayed});

      for(const mode of f.requiredLegacyModes){const before=raw(),beforeRevision=revision(snapshot()),result=safe(`legacy-${mode}-call`,()=>qa.destructive.legacyMode(mode));add(`legacy-${mode}-write-free-refusal`,result?.ok===false&&raw()===before&&revision(snapshot())===beforeRevision&&Number(result.writes||0)===0,result)}
      add('phase11h-art-path-separation',definitions.presentation?.villageCutoutPath==='assets/portraits/fellows/village/{art}.png'&&definitions.presentation?.fellowProfilePath==='assets/portraits/fellows/{art}.webp',definitions.presentation);add('reduced-motion-realm',definitions.runtime?.reducedMotion===config.viewport.reducedMotion,definitions.runtime);add('final-state-valid',qa.read.validate().ok===true,qa.read.validate());add('native-storage-instrumented',window.__P12I_NATIVE_INSTRUMENTED__===true);add('zero-native-storage-accesses',window.__P12I_NATIVE_ACCESSES__.length===0,window.__P12I_NATIVE_ACCESSES__);add('zero-warning-error-console',window.__P12I_ERRORS__.length===0,window.__P12I_ERRORS__);send();
    })().catch(error=>{add('realm-fatal',false,error.stack||error.message);send()});
  }

  let nonce='unknown';(async()=>{const config=JSON.parse(window.name);nonce=config.nonce;window.name='';const response=await fetch('../../index.html',{cache:'no-store'});if(!response.ok)throw new Error(`index.html: HTTP ${response.status}`);let source=await response.text();const firstScript=source.indexOf('<script');if(firstScript<0)throw new Error('Production script tag missing');const bootstrap=`<script>(${installRuntime.toString()})(${json(config)})<\/script>`,suite=`<script>(${runSuite.toString()})()<\/script>`;source=source.replace('<head>','<head><base href="../../">');const insertion=source.indexOf('<script');source=source.slice(0,insertion)+bootstrap+source.slice(insertion).replace('</body>',suite+'</body>');document.open();document.write(source);document.close()})().catch(error=>parent.postMessage({channel:CHANNEL,nonce,results:[{id:'realm-loader-fatal',actual:false,expected:true,pass:false,detail:error.stack||error.message}],errors:[String(error.stack||error.message)]},'*'));
})();
